### ISSUE TITLE
Harmoniseren beschrijvende info

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#1]
@StefanJacques vulde [dit document](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/c88e9092-114d-4b3a-8192-d9b235da8d29) aan met de regels in verband met de eigenschappen in de Onderwerpentabel, zie hoofdstuk "Beschrijving van de onderwerpen". @DavidCardinaels zal deze achteraf toepassen op de bestaande onderwerpen.

**Comment by davidcardinaels** [comment]
Dit heb ik vorig jaar in orde gebracht voor de bestaande beschrijvingen, op basis van het document van Stefan. Er zitten wel nog een hoop lege beschrijvingen in die ingevuld moeten worden door de domeinverantwoordelijken.
