### ISSUE TITLE
Mogelijkheid presentatie AIV beurs

### ISSUE THREAD

**Issue by dgees** [provinciesincijfers/PinC-taakopvolging#100]
Voorlopig voorstel:

Spreker: de diensten Data & Analyse van de Vlaamse provincies
Titel: Fijnmazige gegevens in functie van het lokale beleid

Lokale besturen willen een zicht krijgen op de werkelijkheid om gerichter beleidsacties te kunnen ondernemen. Ze zijn daarom op zoek naar cijfergegevens op laag niveau, toegankelijk en beleidsdomein overschrijdend. 
De provinciale steunpunten Data & Analyse hebben een dienstverlening uitgewerkt waar lokale besturen gratis (provincies.incijfers.be) en op vraag (maatwerk) cijferreeksen en analyses kunnen opvragen. 
We willen deze dienstverlening graag voorstellen aan de hand van enkele voorbeelden uit de praktijk.

Ondertussen heeft AIV meer info doorgegeven m.b.t. de presentaties. 
https://overheid.vlaanderen.be/informatie-vlaanderen/nieuws/de-themas-voor-de-trefdag-digitaal-vlaanderen-zijn-gekend

**Comment by StefanJacques** [comment]
Op de Redactiegroep van 07/04/2020 werd beslist om voorbeelden te zoeken van waar wij concreet data aanleveren voor beleidsondersteuning. De moeilijkheid is om allesomvattend te zijn en toch specifiek genoeg. Als we de voorbeelden erin zetten, over verschillende domeinen kunnen we misschien beter duiden wat we bedoelen. Maar de nadruk ligt wel op de meerwaarde die D&A hebben, gaat dus veel verder dan PinC. 
We denken er nog eens over na en iedereen laat tegen eind van de week weten of er nog aanvullingen zijn. @dgees
