### ISSUE TITLE
Opvolging uitdovende onderwerpen

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#101]
(Wanneer) mogen uitdovende onderwerpen definitief verwijderd worden?

**Comment by joostschouppe** [comment]
Gegeven het feit dat de centrumsteden uitdovende onderwerpen niet uit hun versie verwijderen, moeten we eerst missings inladen

**Comment by VickyVB** [comment]
Redactiegroep 30/4:
- na 6 maanden missing data inlezen zodat dit doorgegeven wordt in de connector;
- na 1 jaar onderwerpen verwijderen.
Elke verantwoordelijke bekijkt zijn uitdovende onderwerpen.
