### ISSUE TITLE
teller en noemer hebben verschillende bron

### ISSUE THREAD

**Issue by StefanieWVL** [provinciesincijfers/PinC-taakopvolging#103]
Wat indien teller en noemer verschillende bron zijn en dit vreemde resultaten geeft? Vb. Mesen sociale huisvesting: aantal appartementen geteld door de VMSW (teller) is groter dan aantal appartementen volgens kadaster (noemer). > % is meer dan 100% ...

Wat doen we hiermee? 

Alvast een voorstel van Joost dat afgeklopt kan worden?

_Collega’s,

Op zich vind ik het helemaal niet vreemd dat dit zich voordoet. Elke berekening waar twee bronnen gecombineerd worden, heeft dit risico. Zelfs als die bronnen heel dicht op elkaar zitten.

Moesten we een FAQ hebben, dan zouden we het daar kunnen zetten. Maar dat hebben we niet, het is geen AQ en al zeker geen F AQ.

In de metadatafiche zou ik dat niet zetten, juist omdat het overal kan voorkomen.

De enige aanpassing die ik wel zou voorstellen is dit NIET als een percentage aan te duiden. Dat zou ik beperken tot waar je berekening tot één bron behoort en je echt weet “dit totaal valt zo onder te verdelen”. In dit geval zou ik gewoon een “ratio van iets per 100 van iets anders zetten”. Daarmee geef je aan dat je gewoon een standaardisering van dit cijfer probeert te doen. En een standaardisering kan nu eenmaal af en toe misgaan.

Inderdaad kunnen we hier bij Mesen ook wel een driehoekje met een waarschuwing laten verschijnen.
Als er maar voor één jaar een probleem is: maak gewoon een rij aan in deze tabel:
https://provincies.incijfers.be/Admin/Studio/Table?tableName=Info_

**Comment by joostschouppe** [comment]
Dubbel met https://github.com/provinciesincijfers/PinC-taakopvolging/issues/97
