### ISSUE TITLE
dashboards op wijkniveau

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#104]
- **Moeten we tot op SS niveau gaan?** Voor bevolking is dit waarschijnlijk interessant, maar voor leerlingengegevens en werkzoekendengegevens zijn heel wat SS met verborgen waarden. Dit kan per dashboard apart ingesteld worden zodat we voor leerlingen bv max tot wijk of deelgemeente gaan en voor bevolking tot SS. Maar is dit wenselijk? Of voegen we een tekstvak in waar je mensen suggereert een hoger niveau te kiezen?
[Arbeidsdeelname (wijkdata).pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/4437137/Arbeidsdeelname.wijkdata.pdf)

- Wat is het **vergelijkingsgebied**? Ik denk zelf dat er veel voor te zeggen is om dat tot de (deel)gemeente te beperken.

- In grafieken vallen de observaties **onder de drempelwaarde** gewoon weg. Kan dit anders?

- Door het beperkt aantal observaties gaan we beperkt zijn tot de meer **algemene variabelen.** Mijn voorstel:
**NWWZ op 1/1**: aantal NWWZ,  % NWWZ, (minderjarigen in gezin met werkloosheid)
**Basisonderwijs**: aantal kleuters, aantal leerlingen, %indicatorleerlingen, OKI _(moet waarschijnlijk wel strenger gedrempeld worden)_
**Secundair onderwijs**: aantal leerlingen, %indicatorleerlingen, OKI _(moet waarschijnlijk wel strenger gedrempeld worden)_

**Comment by karolienbloemen** [comment]
Zorgaanbod: nvt: geen indicatoren kleiner dan gemeentelijk niveau beschikbaar.

**Comment by Inejacobs** [comment]
nvt voor Veiligheid --> kleinste niveau is gemeente

**Comment by StefanieWVL** [comment]
wonen>% huurders (t.o.v. van huishoudens) komt in aanmerking
           >% sociale huurwoningen liever niet (want komt niet voor in elke gemeente en vaak zeer lage aantallen - ziet er dus niet altijd mooi uit ;-)

**Comment by StefanJacques** [comment]
dashboard klimaat: nvt

**Comment by joostschouppe** [comment]
Vraag voor ABF: Is het mogelijk om binnen Dashboard te werken met drempels op aantallen?
Vraag voor ABF: helderdere communiceren over ontbrekende data
Todo: nakijken of er nog thema's niet geevalueerd zijn
Voorstel: één iemand bekijkt de huidige voorbeelden en probeer op basis daarvan een soort sjabloon te maken van dingen die werken @VickyVB 

Te verkennen: effect om keuze ts wijk/statsec mogelijk te maken

**Comment by KoenSnyers** [comment]
TIP aan iedereen die dashboards aanmaakt op stat sector-niveau:
zet de tegel van dat dashboard op onzichtbaar op de startpagina, want anders verschijnt de tegel op de online startpagina zoals vandaag het geval is; naar het dashboard op stat sectorniveau zal (als het klaar is voor publicatie) verwezen worden via een tegel op de themapagina (naar analogie van de submappen Basisonderwijs en Secaundair onderwijs in het thema Onderwijs).

**Comment by joostschouppe** [comment]
Joost & Vicky bekijken de issues op 16/10

**Comment by joostschouppe** [comment]
## voor abf
* ABF: proberen ervoor zorgen dat je in de juiste gemeente terecht komt (link met parameters gebruiken!)
* inseinen bij ABF: de keuze van statsec beperken tot die van de gekozen gemeente (mogelijk alternatief: "tussenkaartje" gemeente uitgesplitst naar statsec, klik op kaart binnen dashboard om gebied aan te passen)
* voorstel: alles op wijkniveau (aangevraagd bij ABF) en enkel vergelijken met gemeente
* vraag voor ABF: kunnen we grafieken in Dashboard laten vallen indien bepaald onderwerp kleine waarde is? (cfr conditionele sectie)
* vraag voor ABF: op kaartjes duidelijker het ontbreken van gegevens aanduiden (nu lijkt het op "kleine waarde")

## structuur
* vaste beginstructuur: kaartje met absolute aantallen van de basis populatie (vb leerlingen, bevolking), en daarnaast cijfer met datzelfde cijfer voor gebied zelf (eventueel met waarschuwing erbij)
* eraan denken dat als er een rapport is dat subgemeentelijk kan, dat we daar dan naar doorverwijzen (met parameters)

**Comment by joostschouppe** [comment]
Thema-verantwoordelijken geven seintje aan Koen als het klaar is voor opname.

**Comment by joostschouppe** [comment]
Status per thema:
- Landbouw: na te kijken of zinvol
- Detailhandel: voorstel te maken!
- Wonen: voorstel staat klaar
- Demografie: voorstel moet bevestigd door AN
- Onderwijs: voorstel moet bevestigd door VB

**Comment by Tine-VB** [comment]
Wat landbouw betreft zijn enkel de teelten beschikbaar op statistisch sector niveau, wat zeker interessant kan zijn op een lager niveau dan gemeente. Maar bij de laatste verwerking hebben we gemerkt dat het departement landbouw een perceelskaart gebruikt die niet overeenkomt met de standaard kaarten van (statistische sector) grenzen die wij gebruiken. Daardoor kwamen bijvoorbeeld gronden (en dus ha teelten) van grensgemeenten in Wallonië terecht, terwijl ze in realiteit in Vlaanderen liggen. Dit zal ook fouten geven op gemeenteniveau en zeker op statistisch sectorniveau. Het lijkt me dan ook beter om dat eerst proberen te verbeteren vooraleer het dashboard uit te breiden naar statistisch sectorniveau. 
Een voorbeeldje:

**Comment by KoenSnyers** [comment]
Collega's

Deze dashboards op wijkniveau staan alvast online:

- bevolking: https://provincies.incijfers.be/dashboard/dashboard/bevolking---wijkniveau
- huishoudens: https://provincies.incijfers.be/dashboard/dashboard/huishoudens---wijkniveau

Ik werk nog aan wonen, nationaliteit en herkomst, en de twee van onderwijs ...

Belangrijke dingen voor de (wijk)dashboards:

- we kiezen uitsluitend voor wijk als gebiedsniveau en voor gemeente als vergelijkingsgebiedsniveau
- onderaan rechts op het gemeentelijk dashboard van een thema komt een link naar het dashboard op wijkniveau, die (met dank aan Joost) linkt naar de eerste wijk van de geselecteerde gemeente in het dashboard; voor de thema's bevolking en huishoudens zal dit al te zien zijn vanaf morgen (23 juni) (zie afbeelding)

![afbeelding](https://user-images.githubusercontent.com/62065726/122928541-45719d80-d36a-11eb-8ca0-a629449e4d53.png)

- we maken geen gebruik van kubussen in dashboards/wijkdashboards; ik paste dit al aan voor bevolking en huishoudens, en ik zal dat ook doen voor nationaliteit en herkomst; dashboards en wijkdashboards pretenderen kerncijfers te bevatten, dus zijn er geen kubussen nodig om cijfers in dashboards op te nemen

**Comment by KoenSnyers** [comment]
Ook het wijkdashboard van het thema wonen staat online:
https://provincies.incijfers.be/dashboard/dashboard/wonen---wijkniveau

**Comment by KoenSnyers** [comment]
Ook het wijkdashboard van het thema nationaliteit en herkomst staat online:
https://provincies.incijfers.be/dashboard/dashboard/nationaliteit-en-herkomst---wijkniveau

Ter info ook nog dit, van de kaartjes in de wijkdashboards is de detailview voorlopig overal (behalve in het thema bevolking, zodat ABF kan checken) uitgeschakeld, omdat er een bug is die maakt dat bij klikken op het kaartje de kaart van heel Vlaanderen getoond wordt i.p.v. de kaart met de wijken van de geselecteerde gemeente.

**Comment by joostschouppe** [comment]
Opmerking Redactiegroep: we willen deze nieuwe feature toch graag meer onder de aandacht brengen. Dus graag de tegels met link naar het wijkniveau toch bovenaan bij de knoppen naar rapporten en databank.
Het viel ook op dat in sommige thema's er bovenaan een lege plek is indien drie knoppen, en bij andere een gekleurd leeg vlak

**Comment by KoenSnyers** [comment]
Ik heb de links overal bovenaan geplaatst, maar toch dezelfde kleur aangehouden (om er geen kleurboek van te maken). Door het thema-icoontje valt het wel voldoende op.
Ik heb er ook voor gezorgd dat er op elke dashboardpagina een gekleurd leeg vlak is, als er een oneven aantal tegels is bovenaan.

**Comment by joostschouppe** [comment]
In grote lijnen afgerond; de openstaande Dashboards naar individuele tickets verhuisd
