### ISSUE TITLE
Oppervlaktes en de nieuwe statsec

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#107]
Voor oppervlaktes in PinC hebben we binnenkort vier bronnen:
-	Geometrie oude statsec
-	Geometrie nieuwe statsec
-	Downloadable vanop statbel oude gemeenten
-	Downloadable vanop statbel nieuwe gemeenten

Tot nu toe hebben we twee reeksen onderwerpen:
-	Eentje met steeds de geometrische oppervlakte, ongeacht gebiedsniveau
-	Eentje met op subgemeentelijk niveau de statsec-gebaseerde oppervlakte, maar vanaf gemeenteniveau de statbel oppervlakte.

Taken:
- [ ] data van statbel checken, verzamelen en uitleggen
- [x] geometrische data herbekijken

**Comment by StefanJacques** [comment]
Mail gestuurd naar Kim Derwae (StatBel)
