### ISSUE TITLE
Rapport Kerncijfers op wijkniveau?

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#108]
Hoe kunnen we Kerncijfers uitbreiden naar lager-dan-gemeentelijk niveau? Is dit doenbaar binnen de bestaande omgevingsanalyse? Hoe moet dit eruit zien?

**Comment by joostschouppe** [comment]
Algemeen:
- toon rapport enkel indien minstens X inwoners. Indien te klein, via "kiezen op kaart" grotere selectie maken
- zowel statsec als wijk
- indien wijk en geen gg, doorverwijzen naar pagina over gg
- links naar andere rapporten: vervangen door link bovenliggende gemeente indien nodig
- overal vergelijken met gemeente (indien sectoren uit meerdere gemeenten, laagste gebied dat lukt)

hoofdstuk | commentaar
-- | --
Bevolking | bestaande presentatie vervangen door bevolkingsmutaties op statsec (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/131)?
Huishoudens | OK
Arbeidsmarkt | alternatieve presentatie met enkel werkloosheidscijfers
Economie | leeg laten
Detailhandel | enkel indien % tov inwoners, eventueel ook % tov alle handelspanden indien minstens 100 panden. Zeker geen % tov subsets van panden
Basisonderwijs  | OK
Secundair onderwijs | laten vallen laatste drie indicatoren
Wonen | alles vervalt, behalve sociale huurwoningen. Die houden en de rest vervangen door eigen kadasterdata

**Comment by joostschouppe** [comment]
Arbeidsmarkt: alles naar eigen verwerking
Wonen: ook eigen kadastergegevens hier zetten

**Comment by VickyVB** [comment]
Voor het thema arbeidsmarkt
Italic = niet beschikbaar op een lager dan gemeentelijk niveau
Bold = (suggestie) vervanging naar gegevens van VDAB 1/1 beschikbaar tot statsec

fig06 = Presentation {
	Selection {
[_Ind._vp1201_ksz_loontrekkend, 
Ind._vp1201_ksz_zelfstandige, 
Ind._vp1201_ksz_werkzoekend, 
Ind._vp1201_ksz_pensioen, 
Ind._vp1201_ksz_kinderbijslag, 
Ind._v1202_activiteitsgraad_t, 
Ind._v1202_werkzaamheidsgraad_t,_ 
Ind._v1321_wlhgraad_t_jg, **werkloosheidsgraad hebben we niet, maar misschien kan je hier % NWWZ t.o.v. 18-64 jarigen vp1301_ba**
Ind._vp1323_nwwz_min25_jg, **vp1303_wz_18_24**
Ind._vp1323_nwwz_55p_jg, **vp1303_wz_55_64**
Ind._vp1324_nwwz_laag_jg, **vp1304_wz_laag**
Ind._vp1326_nwwz_2jaarp_jg]; **vp1306_wz_zeerlang**
		MostRecentPeriod: 0;
		input_geo_sel;
		compare: input_compare;
		CompareShowGeoIndividual: toon_individueel;
        CompareShowGeoTotal: toon_totaal;
	};
	View: ProfileBar;
	ViewDimensions: [dim_geocompare, dim_variable, dim_period];
	LayoutClass: "profielstaaf";

**Comment by joostschouppe** [comment]
In ontwikkeling via https://provincies.incijfers.be/admin/jive/Report/Edit/omgevingsanalyse_steekkaart
Opgelet: zorg dat na aanpassing (indien nog niet klaar) dit enkel blijft werken op gemeenteniveau!
Ontwikkelversie omgevingsanalyse_steekkaart_test

Logica:
* inhoudsopgave conditioneel (staat klaar)
* alle weggevallen hoofdstukken samenvatten (staat klaar)
* algemene drempel op bevolking (of enkel sociale gegevens?) - todo

Nakijken links: doen vervallen indien niet mogelijk voor meerdere gebieden / gebieden van dat niveau

**Comment by joostschouppe** [comment]
## Aanpassing Wonen

Eventueel nog een extra % maken met woningen van voor 1946 op basis van eigen verwerking

Huidig | aangepast
-- | --
eengezinswoningen   (t.o.v. woongelegenheden) [%] | eengezinswoningen (t.o.v.   woongelegenheden) [%]
appartementen   (t.o.v. woongelegenheden) [%] | meergezinswoningen (t.o.v.   woongelegenheden) [%]
gesloten   bebouwing (t.o.v. eengezinswoningen) [%] | gesloten bouwvorm (t.o.v.   woongelegenheden in eengezinswoning) [%]
halfopen   bebouwing (t.o.v. eengezinswoningen) [%] | halfopen bouwvorm (t.o.v.   woongelegenheden in eengezinswoning) [%]
open bebouwing   (t.o.v. eengezinswoningen) [%] | open bouwvorm (t.o.v. woongelegenheden   in eengezinswoning) [%]
groter dan 104   m² (t.o.v. eengezinswoningen) [%] |  
gebouwen   opgericht voor 1946 (t.o.v. gebouwen) [%] | gebouwd vóór 1900 (t.o.v. woongelegenheden) [%]
gebouwen   opgericht na 2011 (t.o.v. gebouwen) [%] | gebouwd sinds 2011 (t.o.v.   woongelegenheden) [%]
cv of airco   (t.o.v. deel gebouwen) [%] |  
minstens 1   badkamer (t.o.v. deel gebouwen) [%] |  
minstens 1   garage (t.o.v. deel gebouwen) [%] |  
sociale   huurwoningen (t.o.v. particuliere huishoudens) [per 100] | OK
kandidaat-huurders   (t.o.v. particuliere huishoudens) [%] |  
huurders   (t.o.v. huishoudens met gekende eigendomstitel) [%] |  
eigenaars   (t.o.v. huishoudens met gekende eigendomstitel) [%] |

**Comment by joostschouppe** [comment]
@karolienbloemen : kan je voor Zorgaanbod eens kijken of in `omgevingsanalyse_steekkaart` enkele indicatoren ivm kinderopvang opgenomen kunnen worden? Zeker interessant hier aangezien @miekevanopstal die data tot op statsec heeft verzameld.

**Comment by karolienbloemen** [comment]
suggestie voor [zorgaanbod ](https://provincies.incijfers.be/jive?workspace_guid=25d3d319-a88c-4b44-be4e-a84a75fff34f), voor het luik kinderopvang: weliswaar pas nadat de noemer 0-2 jarigen beschikbaar is.

Deze grafiek kan ook toegevoegd worden aan het gemeentelijke rapport kerncijfers.

Voor het luik ouderenzorg zijn data tot gemeentelijk niveau beschikbaar, deze grafiek zit al in het gemeentelijk rapport kerncijfers.

**Comment by joostschouppe** [comment]
Hier is een bug ontstaan, [rapport met veel gebieden](https://provincies.incijfers.be/databank?var=v1111a_tot_bevolking&keepworkspace=true&geoitem_codes=gemeente_71002,gemeente_71004,gemeente_71011,gemeente_71016,gemeente_71017,gemeente_71020,gemeente_71022,gemeente_71034,gemeente_71037,gemeente_71045,gemeente_71053,gemeente_71057,gemeente_71066,gemeente_71067,gemeente_71069,gemeente_72003,gemeente_72004,gemeente_72018,gemeente_72020,gemeente_72021,gemeente_72043,gemeente_72030,gemeente_72037,gemeente_72038,gemeente_72039,gemeente_72042,gemeente_72041,gemeente_73001,gemeente_73006,gemeente_73009,gemeente_73022,gemeente_73028,gemeente_73066,gemeente_73083,gemeente_73098,gemeente_73107,gemeente_73109) geeft geen inhoud!

**Comment by davidcardinaels** [comment]
Ik heb de code met de bug even als commentaar gezet, dan werkt het rapport in ieder geval.
De oplossing heb ik nog niet gevonden.

**Comment by joostschouppe** [comment]
@karolienbloemen : lees ik je suggestie goed om Zorgaanbod te hernoemen tot Ouderenzorg, en een nieuw hoofdstuk Kinderopvang te maken?

**Comment by karolienbloemen** [comment]
voor het rapport kerncijfers (zowel gemeentelijk als buurt) zou ik het inderdaad opsplitsen, aangezien er voor kinderopvang toch ook een heel aantal interessante indicatoren zijn, die in het gemeentelijke en nadien in het kerncijferrapport op buurtniveau opgenomen kunnen worden. Voor ouderenzorg is enkel gemeentelijke info beschikbaar, dus niet bruikbaar in het buurtrapport kerncijfers.

**Comment by joostschouppe** [comment]
Zie ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/201#issuecomment-774967362

**Comment by joostschouppe** [comment]
Redactiegroep: gewoon ter info en nazicht.

**Comment by StefanJacques** [comment]
Knap werk !

- Moet de lijst van afkortingen mee variëren als je een lager dan gemeentelijk gebied selecteert ? Concreet moeten dan de ouderenzorg-afkortingen niet verschijnen ?

- Als je (bijvoorbeeld) vanuit een deelgemeente doorklikt naar het rapport 'bevolking en huishoudens' krijg ik een rapport voor deelgemeente-provincie-gewest, terwijl het buikgevoel zegt dat ik de deelgemeente wil vergelijken met gemeente-provincie (maar dit hangt samen met andere vragen van volgorde keuzegebieden, niet ? we zouden een stroom moeten uittekenen die volgorde van opvragen gebieden met vergelijkingsgebieden bepaalt: indien statsec/wijk/deelgem: gemeente+prov - indien gemeente: prov-vl)

nog een meer algemene opmerking (nu pas ontdekt)

1|
in de inleidende tekst lees je:
"Elke grafiek kan op dezelfde manier gelezen worden: het balkje geeft de waarde van het door jou gekozen referentiegebied weer, nl. Dendermonde, de bol toont de waarde van Baasrode (Dendermonde)."

telkens wordt mijn aandacht getrokken naar het referentiegebied ... terwijl daar in de eerste plaats het gekozen gebied zou moeten staan (denk ik)

beter aanpassen naar:
"Elke grafiek kan op dezelfde manier gelezen worden: de bol toont de waarde van het gekozen gebied Baasrode (Dendermonde), terwijl het balkje de waarde weergeeft van het door jou gekozen referentiegebied, nl. Dendermonde, ."

2|
als je twee gebieden selecteert, 
![image](https://user-images.githubusercontent.com/31841732/109468642-2e323b80-7a6d-11eb-8a62-bb96c8062b12.png)
krijg je vervolgens de mogelijkheid om een vergelijkingsgebied te selecteren
![image](https://user-images.githubusercontent.com/31841732/109468713-486c1980-7a6d-11eb-9ba9-7ac12291a135.png)
maar dit houdt geen steek, aangezien gebied 1 sowieso vergeleken wordt met gebied 2

**Comment by joostschouppe** [comment]
A) ga ik negeren
B) komt automatisch in orde
C) ok, aangepast
D) klinkt logisch, maar dit soort aansturing geeft bugs
