### ISSUE TITLE
Nalezen op voldoende doorlinken naar andere rapporten en dashboard

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#11]
doorverwijzingen naar andere steekkaarten/rapporten
(deel van to do bij aanmaak nieuw rapport is checken in oude rapporten of link relevant is)
Goede voorbeelden: rapport armoede, steekkaart kerncijfers

**Comment by Inejacobs** [comment]
[Rapport Ouderenzorg.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/3892323/Rapport.Ouderenzorg.pdf)

Joost, in bijlage het rapport ouderenzorg waarin ik 2 links verwerkt heb (naar andere rapporten). Doen we dit via voetnoten, een regel tekst, een hyperlink ... dat moet de redactiegroep maar bekijken.

Rapport Onderwijs en Armoede komen er eveneens aan.

**Comment by Inejacobs** [comment]
[Rapport Onderwijs.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/3895713/Rapport.Onderwijs.pdf)

**Comment by joostschouppe** [comment]
Ouderenzorg en Onderwijs aangepast.

**Comment by joostschouppe** [comment]
Ondertussen verder opgenomen door Vera
