### ISSUE TITLE
Ruimtelijke indicatoren (Landgebruiksbestand, Bodemafdekkingsbestand en Ruimteboekhouding)

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#110]
Valerie (LIM) heeft samen met GIS-expert Bavo (LIM) de verwerking gedaan van drie ruimtelijke bronnen. 

**GEBRUIK RUIMTE**
-  v(p)1591 : bron = Landgebruiksbestand (driejaarlijks , waarvan beschikbaar 2013 en 2016)
dit zijn 4 aparte lagen die VITO heeft samengevoegd naar 1 laag (onderverdeeld in ruimtebeslag en niet-ruimtebeslag of open ruimte)
-  v(p)1592: bron = Bodemafdekkingsbestand (driejaarlijks, waarvan beschikbaar 2012 en 2015) --> hier wordt verharding uit afgeleid.

**BESTEMMING RUIMTE**
-  v(p)4001: bron = Ruimteboekhouding (jaarlijks, waarvan beschikbaar 2014 en 2017)

De metadata hangen reeds achter de onderwerpen.
Deze staan in de **testversie** in de testmap onder het mapje Valerie, opgedeeld in 2 thema’s: landgebruik versus ruimteboekhouding (of bestemming van ruimte)
![image](https://user-images.githubusercontent.com/31841732/80114686-2455c700-8584-11ea-9367-6b3b402165ec.png)
 
VRAAG: wie wil er **controleur** van deze reeksen zijn ?

**Comment by StefanJacques** [comment]
Besproken op de _redactiegroep 30 april 2020_: controleur wordt OVL.

**Comment by valeriepirard** [comment]
1) data werden in de themaboom verplaatst naar Productie/INTERN/GeoStats

2) draft mail om te sturen vanuit D&A naar de collega's ruimte in elke provincie:
Beste, 
Graag laat ik je weten dat we vanuit Data & Analyse een aantal ruimtelijke indicatoren bijeengebracht hebben in provincies.incijfers.be. 
Het gaat om indicatoren uit 3 bronnen:
-	Landgebruiksbestand
-	Bodemafdekkingskaart
-	Ruimteboekhouding

Deze data werden verwerkt in samenwerking met de GIS-cel van de provincie Limburg.
Voor de verwerking en de publicatie van de data van het Landgebruiksbestand werd een overeenkomst afgesloten met het departement Omgeving Vlaanderen.
De afspraken omtrent verwerking en publicatie m.b.t. cijfers uit de Ruimteboekhouding werd per mail overeengekomen met Ruimte Vlaanderen.

Jullie kunnen alvast een aantal voorbeelden van cijfermateriaal bekijken via: https://provincies.incijfers.be//jive?workspace_guid=2f61708b-09f2-43c2-a0dd-b050545342ec     (via het pijltje rechts kan je tab per tab bekijken)

Het betreft een eerste basisset , een startpunt, en graag horen we jullie feedback:
-	welke cijfers zijn interessant voor jullie ?
-	welke trends of specifieke vaststellingen zijn er ?
-	andere vragen naar cijfers ?
-	andere opmerkingen, …?
Vriendelijke groeten

**Comment by miekevanopstal** [comment]
feedback van de directie Ruimte OVL:
"_cijferreeksen vormen voor ons (cel beleidsvoorbereiding) absoluut interessant basismateriaal om bepaalde zaken te situeren in zijn context, zaken te meten of de evolutie ervan in te schatten.
Ik denk dat dit ook bij lokale besturen het geval is. 
Een aandachtspunt bij de cijferreeksen is de definiëring van de weergegeven begrippen. Momenteel worden inzake “ruimte” heel veel begrippen dubbel of meer gebruikt waardoor het niet altijd duidelijk is welke info wordt weergegeven. Een goede begripsduiding kan dit verhelpen.
Indien we bijkomende cijferreeksen zouden wensen, dan laten wij dat in alle geval weten_."_

**Comment by Lievendr** [comment]
Commentaar van Ruimtelijke planning Antwerpen

•	De bronnen worden vermeld, maar de werkwijze bij verwerkte data is ook belangrijk om te kennen: welke bewerkingen werden gedaan, welke aannames werden gedaan,…
•	Voor gemeentelijk steunpunt is het handig om een aantal datasets te combineren, of snel te kunnen terugvinden, om snel zicht te krijgen op de situatie in een gemeente. Ik kreeg het idee n.a.v. je mailtje en ons DO van maandag en er is zo veel data beschikbaar dat ik nu nog niet kan zeggen welke cijfers of combinaties van gegevens interessant zijn. 
•	De tool werkt niet zo intuïtief (maar misschien is dit ook omdat je in een soort ‘demoversie’ terechtkomt). Het is echt wel wat zoeken waar nu de verschillende data staan. 
•	Ik vind het zeer interessante gegevens en zeker te gebruiken voor analyse ikv ruimtelijke projecten alleen weet ik niet zo goed hoe ze tot bepaalde percentages komen en wat daarin verzat zit
o	Dat moet zeker duidelijk zijn zodat je qeen appelen en peren ligt te vergelijken:
o	bv. wat zit er onder de verschillende categorieën van ruimtebeslag? 
o	Bv. wat zit er allemaal vervat in het begrip ‘verharding’ (bv. tuinen, terassen, …)?
•	Verder ingegaan op de concrete vragen: 
o	welke cijfers zijn interessant voor jullie ? alles met ruimtebeslag en verhardingen lijken me wel interessant
o	welke trends of specifieke vaststellingen zijn er ? moeilijk om nu hierop te antwoorden
o	andere vragen naar cijfers ?
	het is me niet duidelijk wat je wil aantonen met dataset ‘groene ruimte tov ruimtebeslag’: als je veel groen hebt en veel ruimtebeslag, ga je percentueel misschien op hetzelfde uitkomen dan een gebied met weinig groen en weinig ruimtebeslag
o	andere opmerkingen, …? kleuren van de verschillende categorieën werken niet intuitief (vb. landbouw = roze)

Met vriendelijke groeten,
Krista Bonny

**Comment by valeriepirard** [comment]
Feedback Ruimte Limburg: de indicatoren werden voorgesteld tijdens een overleg en interessant bevonden. Er werd een voorstel voor een bijkomende indicator gedaan (nl. "oppervlakte verharding binnen open ruimte"), deze werd ondertussen aangemaakt. Daarnaast heb ik een paar vaststellingen uit de cijfers voorbereid als input voor een persbericht. Ik wacht nog op hun input en aanvullingen hierop.

**Comment by VickyVB** [comment]
Feedback vanuit Vlaams-Brabant:

Ik ga beginnen met de ‘**andere opmerkingen**’: de website (of toch alleszins het deel waarnaar je linkt) is niet heel gebruiksvriendelijk. Ik zie niet goed hoe ik, als ik de gegevens van één gemeente heb, naar een andere kan gaan, of hoe ik van het algemene overzicht naar één gemeente kan gaan. Zoomen en navigeren gaat ook relatief traag, waardoor het niet zo vlot werkt. En ook belangrijk: als ik van de ene naar de andere tab ga, ben ik mijn zoomniveau kwijt.
Ik merk wel dat er een handleiding én een instructievideo staan, maar je wil die niet elke keer uitpluizen/bekijken vooraleer je begint; en dit soort website zou eigenlijk zichzelf moeten uitwijzen; als ik heel eerlijk ben.
 
Soit, ik wou daarmee beginnen, want dat betekent dat ik niet in detail elke tab heb bekeken – vooral ‘trends en vaststellingen’ zijn te arbeidsintensief om te identificeren vrees ik…
 
**De gegevens**:
-       Aandeel open ruimte in de oppervlakte: zéér interessant (tot op gemeenteniveau, lager niet meer)
-       Verharding: zéér interessant, op elk niveau
-       ‘Huizen en tuinen’ in m² lijkt me niet zo interessant. Komt deels overeen met ruimtebeslag, en door de absolute waarden is dit meer een effect van de grootte van de gebruikte afbakening
-       Dan is er een tab met ‘provincies in cijfers’ als naam, dat lijkt me eerder landgebruik te zijn? Op zich zeker interessant, maar nog meer om evoluties te zoeken. Bevat de site een mogelijkheid om verschillende jaren met elkaar te vergelijken?
-       Oppervlakte groen t.o.v. oppervlakte ruimtebeslag: is op zich wel interessant, maar is eigenlijk één specifieke analyse van het landgebruik (waar je dan nog eens moet uitleggen wat ‘groen’ exact betekent hier en waarom je voor de vergelijking van deze twee specifieke groepen een aparte kaart maakt). Misschien is het beter om gewoon het landgebruik in’t algemeen flexibel te laten gebruiken, zodat ieder voor zich, waar nodig, de nodige categorieën kan vergelijken?
-       Verharding komt dan een twee keer voor?
-       Verharding per functie is zeer interessant!
-       Bestemming is op zich interessant, maar vooral om evolutie doorheen een aantal jaren te analyseren. Alleen maar momentopnames (ook al zijn die er van verschillende jaren) is niet zo boeiend.
-       Ruimtebeslag in zachte bestemmingen vind ik een hele moeilijke. De achterliggende bedoeling is zeker goed, maar nu heb ik niet het gevoel dat het die goed weergeeft. Misschien opsplitsen per functie? Ruimtebeslag door huizen en tuinen en zachte bestemmingen, enzovoort?
-       Bestemming natuur en reservaat is interessant, maar enkel op hogere schaalniveaus. 
 
We hadden een tijdje geleden over de kaart van woningdichtheden per bouwblok die Filip maakte. Die is eventueel ook zeer interessant om toe te voegen (als onderdeel van een kaart van de woningdichtheid op elk schaalniveau, zelfs?). Dat zou een geweldige toevoeging zijn.
Aandeel (publiek) groen in harde bestemmingen, misschien is dat ook interessant…?

**Comment by joostschouppe** [comment]
* Joost belt nog ivm Ruimteboekhouding
* Valerie past "verharding" beginjaar aan, omdat het verschil tussen beide jaargangen meer aan foutenmarge dan effectieve wijziging is te wijten
* Voorstel (te bespreken op Redactiegroep): Valerie plaatst extern onder map "Bodembezetting".
* Eventueel aanpassen naam map "Bodembezetting"

**Comment by miekevanopstal** [comment]
OVL heeft gecontroleerd en opmerkingen doorgestuurd aan Valerie op 7/7.
Valerie heeft deze al verwerkt en aangepast.

**Comment by joostschouppe** [comment]
vraag: waarom niet "aandeel bos (t.o.v. totale oppervlakte)" in plaats van alleen "aandeel bos (t.o.v. totale oppervlakte open ruimte)"

**Comment by joostschouppe** [comment]
De cijfers zijn intussen allemaal gepubliceerd.
Werkgroep Landbouw hoeft dus geen ruimteboekhouding van landbouw meer te maken! @Tine-VB 
Opgelet: bestaand % vervangen door nieuwe versie; het aantal m2 staat NIET buiten in de nieuwe reeks
In de nieuwe reeks eindigt op 2017, in de oude op 2018?

**Comment by valeriepirard** [comment]
de nieuwe reeks ruimteboekhouding die ik heb ingeladen, slaat op toestand per 1/01/2017. 
De volgende jaren (1/01/2018, 1/01/2019 en 1/01/2020) staan wel op de planning om te verwerken

**Comment by Lievendr** [comment]
Ik zie in je presentatie dat de verharding zou opgesplitst worden door combinatie te maken met de landgebruikerskaart (11 cat ruimtebeslag – 7 cat openruimte)
Maar ik zie in de boomstructuur enkel verharding van de 11 cat ruimtebeslag. Is het de bedoeling dat de 7 cat openruimte daar nog bijkomen?
Ik vraag alvast aan de Ruimte-collega’s of dit gewenst is…

Daarnaast vraag ik me af of we niet moeten uniformiseren tussen m² - hectaren - km²: en daar een keuze in maken en of al die andere indicatoren van statbel erop moeten blijven staan (Landbouwenquetes,…) maar misschien is dit iets om voor te leggen op de Redactievergadering.

**Comment by valeriepirard** [comment]
_"Ik zie in je presentatie dat de verharding zou opgesplitst worden door combinatie te maken met de landgebruikerskaart (11 cat ruimtebeslag – 7 cat openruimte)
Maar ik zie in de boomstructuur enkel verharding van de 11 cat ruimtebeslag. Is het de bedoeling dat de 7 cat openruimte daar nog bijkomen?"_

De categorieën verharding binnen open ruimte heb ik eruit gezwierd, omdat dit in de praktijk niet bestaat.
Het betreft foutjes in de data n.a.v. het over mekaar leggen van 2 kaartlagen, namelijk de landgebruikskaart en de bodemafdekkingskaart. Het ging om 0,6% verharding binnen open ruimte.
GIS cel heeft dit verder geanalyseerd a.d.h.v. concrete voorbeelden: bv. een huis in een bos. De situatie op kaart is dan dat dit huis ingetekend is als ‘huizen en tuinen’ (ruimtebeslag dus) op de landgebruikskaart en het gebied daarrond (het bos) is open ruimte. 
Zie ook fragment uit het RURA2018: "14% van de totale oppervlakte in Vlaanderen is afgedekt of verhard (Departement Ruimte Vlaanderen, 2017). Deze afdekking bestaat vooral uit gebouwen, wegen, parkeerterreinen. De verharding situeert zich volledig binnen het ruimtebeslag." 
Ik had dit al aan Lieven laten weten via mail.
@joostschouppe 
@StefanJacques

**Comment by joostschouppe** [comment]
OK, dan mag deze dicht
