### ISSUE TITLE
Dashboard: er zijn te veel tegels die je op favoriet kunt zetten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#114]
Na te kijken bij welke tegels deze functie uitgezet moet worden

**Comment by KoenSnyers** [comment]
Ik zal dit bekijken bij het aanpassen van het dashboard.

**Comment by KoenSnyers** [comment]
Dit zou nu afgehandeld moeten zijn, aangezien ik de hoofdview van alle tegels in het dashboard heb aangepast.
