### ISSUE TITLE
Gesuggereerde wijzigingen sjabloon/intro

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#115]
- [x] laten vallen "dit verschijnt niet in pdf" (@StefanieWVL ) ?
- [x] wijzigen "het gekozen gebied" ipv "de gekozen gebieden", zodat zinnen steeds in enkelvoud geschreven kunnen worden (@VickyVB ) ?
- [x] verwijzing "interprovinciale werking D&A" naar OVER ipv naar contactpagina? (Detailhandel)? 
> contacpagina enkel nog contact; in rapporten verwijzen naar "over deze site"
- [x] verwijzing naar figuren in tekst in italic (staat al in sjabloon, moet nog uitgerold naar alle rapporten)
- [x] css: stijl van h5 aanpassen (staat al in sjabloon, geen extra werk)
- [x] De eerst p of div na twee figuren naast elkaar moet style="clear:both;" meekrijgen. (Enkel strikt noodzakelijk wanneer de twee figuren niet dezelfde hoogte hebben. Maar dat kan later altijd opduiken.) (reeds uitgerold door David :))

**Comment by davidcardinaels** [comment]
_De eerst p of div na twee figuren naast elkaar moet style="clear:both;" meekrijgen. (Enkel strikt noodzakelijk wanneer de twee figuren niet dezelfde hoogte hebben. Maar dat kan later altijd opduiken.)_

Dit is in orde voor de bestaande rapporten. Ook toegevoegd aan sjabloon.

**Comment by davidcardinaels** [comment]
@joostschouppe "dit verschijnt niet in pdf" vind ik nergens terug. Gaat dit over deze zin: "Deze waarschuwing wordt niet getoond in de PDF export."?
