### ISSUE TITLE
filmpjes voor PinC

### ISSUE THREAD

**Issue by dgees** [provinciesincijfers/PinC-taakopvolging#116]
In de nieuwsbrief van mei 2020 hebben we een toelichting gegeven over het aanmaken van gebruikersonderwerpen. Dit zit niet in de handleiding en moet aangevuld worden.

**Comment by miekevanopstal** [comment]
Hallo nog even melden dat zeneb bezig is om het filmpje te actualiseren.
Ze heeft het idee om meerdere filmpjes te maken: een basis en ook enkele korte filmpjes met meer gespecialiseerde taken (zoals bijvoorbeeld gebruikersonderwerpen).
Ze is een voorstel aan het uitwerken...

**Comment by ChrisMichelDS** [comment]
Voorstel van Zeneb:
Omdat het instructiefilmpje veel te lang is,  mijn voorstel om met deel filmpjes te werken 
Mijn vraag is of er een extra tegel in het dashboard kan gemaakt worden op dezelfde rij van ‘nieuws’ voor de instructiefilmpjes en de handleiding?

Deel 1: PinC – Presentaties maken (klaar)
Deel 2: Pinc en de Gebiedsindelingen (klaar)
Deel 3: PinC en thematische rapporten  (klaar)
Deel 4: Pinc en de Gebruikersonderwerpen

**Comment by joostschouppe** [comment]
Voorstel: als sub-dashboard van "over deze site"

**Comment by joostschouppe** [comment]
Chris verdeelt de links naar de nieuwe versies

**Comment by ChrisMichelDS** [comment]
De link naar de filmpjes op Alfresco:
https://share.vlaamsbrabant.be/share/page/site/socialeplanning/documentlibrary#filter=path%7C%2FProvincies%2520in%2520Cijfers%2FGebruik%2520handleidingen%2520tips%2FFilmpjes%7C&page=1

Afspraak is dat er ten minste 1 iemand per provincie dit bekijkt.

**Comment by VickyVB** [comment]
Opmerkingen bij het filmpje **gebruikersonderwerpen**

- algemeen:  zenuwslopend muziekje zeker na 5 min. Ik heb het geluid moeten uitzetten of ik ging mijn lottocijfers checken.
- algemeen: soms staat de taakbalk mee in de film, ik zou dit wegknippen het blijft niet eeuwig 14u27.
- 0:05 jouw gemeente ..., je beleid : 2x jouw of 2x je
- 0:44 je moet niet specifiek op het icoon klikken, maar kan ook gewoon op gebruikersonderwerpen klikken
- 1:30 (spijtig dat geen van de onderwerpen in beeld nog extern beschikbaar zijn)
- 2:04 v1102_geboorte is niet wat je net geselecteerd hebt, het is nog een eerdere selectie. Eigenlijk zou er v1111a_0_2 moeten staan.
- 2:22 Ik zou hier v1111a_0_2 invoegen " Je eerste gekozen onderwerp 0-2 jarigen (v1111a_0_2) staat in het formulevenster".
- 2:41 "de 2-3 jarigen", moet hier de "3-5 jarigen" zijn.
- 5:05 Via het eerste symbool bewaar je de link niet, maar kopieer je die. Je moet die dan wel ergens plakken om te bewaren.
-5:30 "Dit filmpje is een initiatief van provincie Oost-Vlaanderen" mag weg als het gepubliceerd wordt op PinC.
- Misschien ook nog melden de eigen aangemaakte gebruikersonderwerpen in je themaboom blijven tot je de cookies op je pc verwijdert.






-

**Comment by VickyVB** [comment]
Opmerkingen bij het filmpje **rapporten**

- Het geluid stond nog uit, geen muzikale opmerkingen dus :-).
- De taakbalk blijft wel storen.
- 1:00 Je selecteert een gebied niet door het in te vullen in de tekstvak zoals aangegeven wordt. Stel Aalst staat standaard ingesteld. Ik tik Leuven in, Leuven wordt niet automatisch geselecteerd. Je kiest een gebied door het aan te klikken. Het tekstvak wordt enkel gebruikt om je gewenst gebied snel te vinden in de lange lijst.
- _Misschien hier ook iets (kort) melden over het niveau dat gekozen moet worden. En vooral, vanuit het dashboard is het 2e tabblad ' kaart' wel interessant, daar kan ook wel iets over gezegd worden in een instructiefilmpje._
- 1:27 en 2:36 'exporteren' vind ik nogal technisch. Vervangen door: downloaden of zelfs downloaden als pdf.
- _In dit stuk mis ik de verwijzing naar de knop wijzig die je toch in de eerste plaats gebruikt om een (vergelijkings)gebied te kiezen. Nergens in het filmpje wordt naar deze levensnoodzakelijke knop verwezen._
- 1:30 'een rapport maken' dekt de lading niet echt. Ik verwacht dan dat ik zelfs indicatoren kan selecteren. Vervangen door ' een rapport opvragen voor een gebied'
- 1:41 Je moet niet op het +- teken klikken, dat + teken is om een bijkomend tabblad te openen. Je kan je rapport ook gewoon op het eerste tabblad maken. Indien je dit wel wil melden, moet klip vervangen worden door kli**k** 
- 1:50 "Maak een nieuw rapport vanaf de inhoudstafel en kies een onderwerp" maakt niet echt duidelijk wat je moet doen. Bovendien is een rapport niet echt een onderwerp en zou ik in instructiefilmpjes om het niet te verwarrend te maken wel een duidelijk onderscheid maken tussen onderwerpen, (eventueel) kubussen en rapporten. "Ga in de inhoudstafel naar 'Thematische rapporten' en selecteer daar het gewenste rapport."
- 2:01 "Typ de naam van één of meerdere gemeente**s** (gemeenten) ...  een overbodige gemeente" is omslachtig uitgelegd en onvolledig. Bovendien vind ik 'overbodige gemeente' een rare uitdrukking. Die zin zou ik helemaal weglaten. Hier zou ik ook aangeven dat je sommige rapporten op verschillende niveaus kan opvragen. Suggestie: Je kan nu één of meer gebieden kiezen. Eerst kies je het niveau. Alle rapporten zijn beschikbaar op voor gemeenten en provincies. Bovendien zijn er ook rapporten beschikbaar op het niveau van statistische sectoren, buurten of deelgemeenten. Vervolgens (nieuwe slide) vink je één of meer gebieden aan. Een gebied snel zoeken kan via het tekstvak. Tot slot (volgende slide) worden in het tabblad 'kies vergelijkingsgebieden' een aantal vergelijkingsgebieden voor het door jou gekozen gebied gesuggereerd. Je kan maximaal 2 van deze gebieden aanvinken om weer te geven in je rapport. 
- _Misschien leidt het ons hier te ver maar kan hier ook nog iets tussen van de implicaties van je keuze voor 1, 2 of meer gebieden. Bij 2 vergelijk je tussen de gebieden, bij meer dan 2 worden die samengeteld als één totaalgebied._
- 2:40 Vergeet ook hier niet te verwijzen naar de knop 'wijzig'. Dit is echt de belangrijkste knop wanneer het gaat om werken met rapporten!
- 3:05 "Dit filmpje is een initiatief van provincie Oost-Vlaanderen" mag weg als het gepubliceerd wordt op PinC.
- _Moet er in de inleiding ook niet kort iets over wat is een rapport? cijferoverzicht? en wat was de juiste definitie nu ook al weer?_

**Comment by miekevanopstal** [comment]
blijkbaar zijn er 2 issues over de filmpjes: https://github.com/provinciesincijfers/PinC-taakopvolging/issues/148

**Comment by joostschouppe** [comment]
Klopt, dit ticket is voor de filmpjes die al in opmaak waren toen ze hier besproken werden; 148 is specifiek voor het filmpje 'Assistent voor je eerste presentatie'. Gegeven de hoeveelheid opmerkingen per filmpje, was het wellicht beter geweest voor elk filmpje een afzonderlijk ticket te maken.

**Comment by joostschouppe** [comment]
Indien er nog filmpjes bijgemaakt worden, gelieve hier één ticket per filmpje voor bij te maken
