### ISSUE TITLE
Nakijken projectfiches

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#118]
In de projectfiches staat nog

_Voor de interprovinciale werking rond D&A:
DenAprovincies@vlaamsbrabant.be_

Best even allemaal nakijken

**Comment by StefanJacques** [comment]
Is aangepast naar deirdre.gees@data-en-analyse.be
in alle projectfiches (waar het nog verkeerd stond)
![image](https://user-images.githubusercontent.com/31841732/83116622-518a1d80-a0cc-11ea-89d7-15019bd7bec8.png)
