### ISSUE TITLE
Toevoegen gebiedsniveau 'toeristische regio' in provincies.incijfers

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#122]
Bij de verwerking "kubus Aankomsten en Overnachtingen" voor de Werkgroep Toerisme, duikt er een nieuw gebiedsniveau op. Kan dit gebiedsniveau toegevoegd worden in provincies.incijfers ?

De toeristische regio's:
Antwerpse   Kempen | TReg01
Brugse Ommeland | TReg02
Groene Gordel | TReg03
Hageland | TReg04
Haspengouw | TReg05
Hasselt en omgeving | TReg12
Kunststeden - Antwerpen | TReg06A
Kunststeden - Brugge | TReg06B
Kunststeden - Gent | TReg06G
Kunststeden - Leuven | TReg06L
Kunststeden - Mechelen | TReg06M
Kust | TReg07
Leiestreek -   Oost-Vlaanderen | TReg08O
Leiestreek -   West-Vlaanderen | TReg08W
Limburgse Kempen | TReg09
Maasland | TReg10
Meetjesland | TReg11
Randstedelijk gebied   Antw-Mechelen | TReg13
Scheldeland - Antwerpen | TReg14A
Scheldeland -   Oost-Vlaanderen | TReg14O
Vlaamse Ardennen | TReg15
Voeren | TReg16
Waasland | TReg17
Westhoek | TReg18

**Comment by joostschouppe** [comment]
Methodiek:
https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/54b5a5fa-e997-4c8c-927a-6ccc1bfecb5a 

Voorbeeld van aan te leveren sjabloon:
https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/d9821dfb-445c-4cc7-81b0-b36f428b03e5

Ik had toevallig net alle instructies aan @karolienbloemen bezorgd.

**Comment by karolienbloemen** [comment]
Zie issue #147 
Aanpassing Zeebrugge nog nodig (obv benadering postcodes)?

**Comment by joostschouppe** [comment]
> Aanpassing Zeebrugge nog nodig (obv benadering postcodes)?

Ja, dat heb ik nu niet meer mee kunnen nemen.

**Comment by karolienbloemen** [comment]
Gebiedsniveau's toerisme voorbereid; opgeladen op github
1/ Statsec_treg: aangepast: zeebrugge = NIS9 binnen postcode 8380 zeebrugge
- Controle gedaan via GIS: postcode en statsectoren op elkaar gelegd. Deze lijst van 25 statsectoren is identiek aan wat we eerder doorkregen van toerisme Vlaanderen.
- Gewijzigde lijnen tov vorige versie zijn geel gemarkeerd, louter ter info

2/ Statsec_treg_v3: nieuw gebiedsniveau: scheldeland en leiestreek in zijn geheel (zeebrugge ook in orde), obv statsectoren
- enkel intern op te nemen
- **VRAAG**: de codes van TREG_V3 zijn dezelfde als deze van TREG (behalve uiteraard die van Scheldeland en Leiestreek). Mag dat of geeft dat problemen in de databank? (laat maar weten, indien nodig pas ik aan met _v3 erachter)

3/ Gemeente_treg_gem: ongewijzigd
