### ISSUE TITLE
Planning Redactiegroep voorjaar 2021

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#123]
* Data inplannen. Voorstel: maandelijks, standaard kort; verlenging indien vorige keer niet rond geraakt

>  10/9 
 15/10
 19/11
 17/12 > met eindejaarsdrink!

* Waar staan we t.o.v. https://github.com/provinciesincijfers/PinC-taakopvolging/issues/61

**Comment by StefanJacques** [comment]
vergaderverzoeken voor najaar 2020 zijn verstuurd, Joost.
ik heb ook een vergaderzaal aangevraagd aan Lieve (VVP)

als we bericht hiervan hebben gekregen, staat het je vrij dit issue af te sluiten ;-)

**Comment by StefanJacques** [comment]
Voorstel: maandelijks
9h30 tot 12h30 verlenging indien vorige keer niet rond geraakt

donderdagen

21/01
18/02
18/03
22/04
20/05
donderdag 24/06 eventueel in Brussel ?
