### ISSUE TITLE
Provincies.incijfers.be (met hoofdletter) 

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#124]
In de meeste rapporten staat er bij de Leeswijzer een zin die niet met een hoofdletter begint: "provincies.incijfers.be is een product van de interprovinciale werking Data & Analyse." **Dit zou in alle rapporten moeten aangepast worden: "Provincies.incijfers.be is een product van..."**

**Comment by Tine-VB** [comment]
In de meeste rapporten staat er bij de Leeswijzer een zin die niet met een hoofdletter begint: "provincies.incijfers.be is een product van de interprovinciale werking Data & Analyse." Dit zou in alle rapporten moeten aangepast worden.

**Comment by davidcardinaels** [comment]
Aangepast in alle rapporten + sjabloon
