### ISSUE TITLE
Kiezen op kaart: enkel links laten zien die geen fouten geven!

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#126]
In kiezen op kaart kan je "cijfers economie opgelijst" proberen opvragen voor meerdere gebieden. Wat niet kan! Dus moeten we iets uitvinden om bepaalde links enkel te tonen indien dat GEEN fouten oplevert...

**Comment by joostschouppe** [comment]
Opgelost! (met dank aan Stephanie Soete om het nog eens op de agenda te zetten, en @ChrisMichelDS om me het licht te laten zien)

**Comment by StefanJacques** [comment]
Wat kan het leven mooi zijn !
