### ISSUE TITLE
Correcties n.a.v. "link naar view in Swing"

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#127]
We kunnen nu een link vanuit een rapport-presentatie naar "die presentatie in de viewer" toevoegen onder rapportgrafieken. Zie  https://github.com/provinciesincijfers/bugsinjive/issues/14

![afbeelding](https://user-images.githubusercontent.com/10122639/88388394-bb653180-cdb4-11ea-8542-d26fb5e6dfba.png)

Dit moet uitgerold naar alle Rapporten (rapport_[naam])

### 1) Zorgen dat bij introkaartjes en dergelijke geen link komt!

In PinC is ingesteld als [Report default](https://provincies.incijfers.be/admin/studio/AdminProps?sheet=report&class=) dat we dit tonen.
MAAR dan wordt dit nieuwe icoontje ook getoond voor grafieken waar je geen table of excel link wou laten zien. 

Oplossing: waar je dit tegenkomt in de layout-code:
      `<ShowTableLink>False</ShowTableLink>` en/of
      `<ShowExcelLink>False</ShowExcelLink>`
Dan moet dit aangevuld worden met:
      `<ShowViewerLink>False</ShowViewerLink>`

### 2) Intro aanpassen!
In sjabloon_rapport is de into reeds aangepast:
_Alle cijfers in dit rapport zijn ook raadpleegbaar via onze Databank. Met X open je de figuur als presentatie in de Databank, waar je er zelf op verder kunt werken. Wil je gewoon de cijfers zien die voor de kaarten, figuren en tabellen gebruikt worden, klik dan op  X of X voor een online- of Excel-tabel._ 

Deze instellingen aanpassen:
- via user interface: rapportentabel > Present settings > Base>  "Show Viewer link in reports "
- code: `<ShowViewerLink>True</ShowViewerLink>`

**Comment by joostschouppe** [comment]
Ook impact in "gebiedsinfo"
![afbeelding](https://user-images.githubusercontent.com/10122639/88668688-3bf09e80-d0e3-11ea-893b-5bd568664ed2.png)

**Comment by joostschouppe** [comment]
Wie hier mee bezig is, neem direct ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/115 mee

**Comment by joostschouppe** [comment]
Ook de introkaarten zijn kapot in de nieuwe versie. Blijkbaar kan het niet meer om een kaart van 1 gebied op te vragen met óók het vergelijkingsgebied. Dat hebben we niet nodig, dus dat kan gewoon geschrapt worden. Introkaart2 moet dus zo aangepast worden:

introkaart2 = Presentation {
	Selection {
		[Ind.v1111a_tot_bevolking];
		MostRecentPeriod: 1;
		input_geo;
		~~compare: item(input_compare,0);
        CompareShowGeoIndividual: true;
        CompareShowGeoTotal: false;~~
	};
	View: Map;
	ViewDimensions: [dim_geocompare, dim_variable, dim_period];
	LayoutClass: "introkaart";
}

**Comment by davidcardinaels** [comment]
Ik kreeg deze uitleg van Sander: 
De twee problemen zijn opgelost. 

Het probleem met de kaart werd veroorzaakt doordat het niet meer mogelijk is in Swing om een kaart te tonen in geval slechts 1 gebied is gekozen. Hiervoor is binnen de rapporten module een uitzondering voor ingebouwd. Nadeel is wel dat een tabel wordt getoond indien je vanuit het rapport doorklikt naar Swing Viewer.

**Comment by joostschouppe** [comment]
Dit lijkt me niet volledig te kloppen. Je kan op dit moment effectief een kaart van één gebied hebben, maar enkel indien je geen compare hebt aangeduid.

**Comment by davidcardinaels** [comment]
Alle aanpassingen zijn gedaan, ik sluit deze.
