### ISSUE TITLE
Bevolkingsmutaties op statsec niveau

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#131]
Van Filip: 

Het heeft even geduurd, maar ondertussen heb ik het mutatiebestand van het rijksregister kunnen verwerken (in combinatie met de bestanden op 01/01 en het bestand vorige woonplaats ) om de migraties te berekenen, in eerste instantie voor het jaar 2016.

Vicky heeft deze gegevens geheel volgens de regels van de kunst op PinC gezet onder **Project Demografie / Loop van de bevolking - rijksregister**

Hier staan de volgende gegevens in:

-bevolking op 01/01
-geboorten
-sterften
-immigratie (binnenland)
-emigratie (binnenland)
-immigratie (buitenland)
-emigratie (buitenland)
-bevolking op 31/12

Ook geheel volgens de regels van de kunst, is de bevolking op 31/12 dezelfde als de bevolking op 01/01+ geboorten + immigratie (binnenland) + immigratie (buitenland) – sterften – emigratie (binnenland) – emigratie (buitenland).

-verhuisbewegingen: dit zijn stroomdata (of een kruistabel tussen alle gemeenten). De Waalse gemeenten staan hier niet tussen, maar zijn wel inbegrepen bij de variabelen ‘emigratie (binnenland)’ en ‘immigratie (binnenland)’.

Kijk gerust eens na of al deze gegevens voor de gemeenten in jullie provincie (of elders) geloofwaardig zijn.

De zeer attente lezer zal merken dat er minder mensen zijn op 01/01 2016 (namelijk 202) en op 01/01/2017 (namelijk 156) dan de  rijksregistergegevens die Rudy op PinC heeft gezet. Dat komt omdat die personen in het ene jaar aanwezig zijn en het andere niet, zonder dat er mutaties zijn. Het is dus niet duidelijk wat er met hen gebeurde (en zijn dus weggelaten).

De attente lezer zal ook merken dat de gegevens over natuurlijke aangroei en binnenlandse migratie dicht bij de gegevens van statbel aanleunen, maar de internationale migratie minder. Dat komt hierdoor: de personen in de wachtregisters zijn hier gewoon meegenomen (statbel doet dat niet, en beschouwt iemand pas als externe immigrant als zij/hij wordt overgeheveld van het wachtregister naar het bevolkings- of vreemdelingenregister). Bovendien wordt iemand die administratief geschrapt wordt, maar later op het jaar terug opdaagt, hier niet als een externe migrant beschouwd (zoals statbel wel doet). Iemand die geschrapt wordt en heringeschreven op hetzelfde adres wordt hier als ‘niet-verhuisd’ beschouwd; iemand die heringeschreven wordt op een ander adres wordt wel als verhuizer/migrant beschouwd, maar dan wel intern. Er is dus voor gekozen de ‘echte’ migratie te bekijken. 

Wat met deze cijfers natuurlijk wel mogelijk is, is na te gaan in welk registers de verhuizers zijn ingeschreven (of welke nationaliteit ze hebben, hoe oud….). Ook gegevens op een lager niveau dan de gemeente zijn mogelijk.
Maar vooraleer we zover zijn: graag toch al eens deze cijfers nakijken!

**Comment by VickyVB** [comment]
Op de redactiegroep moet nog een controleur voor deze gegevens (1112) gevonden worden.

**Comment by StefanJacques** [comment]
Op de redactiegroep van 10-09-2020 wordt afgesproken dat Antwerpen controleur wordt: VB-AN.

**Comment by joostschouppe** [comment]
Worden gepubliceerd; de statbel gegevens worden INTERN gezet.
Te controleren: impact op rapporten, dashboard, connector

**Comment by StefanJacques** [comment]
te wijzigen onderwerpen in **tabellenrapport bevolking**
![image](https://user-images.githubusercontent.com/31841732/94145284-98b5ce80-fe72-11ea-882d-e8332c24c5d6.png)

![image](https://user-images.githubusercontent.com/31841732/94145425-d155a800-fe72-11ea-9492-04f3d71ffb04.png)

v1102_geboorte wordt _v1112_geboorte_
v1102_sterfte wordt _Ind.v1112_sterfte_,
v1102_nat_saldo wordt _Ind.v1112_natuurlijk_saldo_,
v1102_migsal_int wordt _Ind.v1112_mig_intra_gem_,
v1102_migsal_ext wordt _Ind.v1112_em_int_,
v1102_totsal wordt _Ind.v1112_aangroei_
**@VickyVB : kijk toch eens na of we hetzelfde bedoelen met de onderwerpen (dankjewel)**

Als je een lager dan gemeentelijk niveau opvraagt, verschijnt op dit moment de tekst onderaan:
"Je hebt dit tabellenrapport opgevraagd op een lager dan gemeentelijk niveau (statistische sector, wijk of deelgemeente) waardoor **de loop van de bevolking en** de bevolkingsvooruitzichten niet getoond worden omdat er geen cijfers beschikbaar zijn voor deze niveaus."

--> de **vetgedrukte woorden** worden verwijderd omdat ook deze onderwerpen nu beschikbaar zijn.

@davidcardinaels heeft de aanpassingen gedaan !

**Comment by VickyVB** [comment]
correctie: 
v1102_migsal_int wordt Ind.v1112_mig_saldo_b, (migratiesaldo met een andere Belgische gemeente)
v1102_migsal_ext wordt Ind.v1112_mig_saldo_int, (migratiesaldo met het buitenland)

**Comment by davidcardinaels** [comment]
Aangepast!

**Comment by joostschouppe** [comment]
Check rapporten. Ik heb deze stappen doorlopen
1) Export het Consistency Report "INDICATORS USED IN REPORTS"
2) Export deel van de indicatoren met de bevolkingsmutaties (filter in onderwerpcode op 1102)
3) Export deel van rapportentabel om enkel de relevante te checken (filter in report tabel op "echt" bij de zoektermen)
4) Koppel aan elkaar (verticaal zoeken in Excel)

Daaruit komt deze tabel:

onderwerpcode | onderwerpnaam | getroffen rapport
-- | -- | --
v1102_t_gem | gemiddelde officiële bevolking (voor   berekening promille loop van de bevolking) | rapport_economie
v1102_natsal | natuurlijk saldo | rapport_economie
vp1102_natsal | natuurlijk saldo (t.o.v. inwoners) | rapport_economie
v1102_migsal_tot | totaal migratiesaldo | rapport_economie
vp1102_migsal_tot | totaal migratiesaldo (t.o.v. inwoners) | rapport_economie
v1102_t_gem | gemiddelde officiële bevolking (voor berekening promille loop van de   bevolking) | rapport_armoede
v1102_t_gem | gemiddelde officiële bevolking (voor berekening promille loop van de   bevolking) | omgevingsanalyse_steekkaart
v1102_geboorte | geboorten | omgevingsanalyse_steekkaart
vp1102_geboorte | geboorten (t.o.v. inwoners) | omgevingsanalyse_steekkaart
v1102_sterfte | sterfte | omgevingsanalyse_steekkaart
vp1102_sterfte | sterfte (t.o.v. inwoners) | omgevingsanalyse_steekkaart
v1102_migsal_tot | totaal migratiesaldo | omgevingsanalyse_steekkaart
vp1102_migsal_tot | totaal migratiesaldo (t.o.v. inwoners) | omgevingsanalyse_steekkaart
v1102_migsal_int | intergemeentelijk migratiesaldo | omgevingsanalyse_steekkaart
vp1102_migsal_int | intergemeentelijk migratiesaldo (t.o.v. inwoners) | omgevingsanalyse_steekkaart
v1102_migsal_ext | internationaal migratiesaldo | omgevingsanalyse_steekkaart
vp1102_migsal_ext | internationaal migratiesaldo (t.o.v. inwoners) | omgevingsanalyse_steekkaart
v1102_geboorte | geboorten | tabellenrapport_klimaat
v1102_sterfte | sterfte | tabellenrapport_klimaat
v1102_natsal | natuurlijk saldo | tabellenrapport_klimaat
v1102_migsal_int | intergemeentelijk migratiesaldo | tabellenrapport_klimaat
v1102_migsal_ext | internationaal migratiesaldo | tabellenrapport_klimaat
v1102_totsal | totale aangroei | tabellenrapport_klimaat
v1102_t_gem | gemiddelde officiële bevolking (voor berekening promille loop van de   bevolking) | tabellenrapport_klimaat
vp1102_geboorte | geboorten (t.o.v. inwoners) | tabellenrapport_klimaat
vp1102_sterfte | sterfte (t.o.v. inwoners) | tabellenrapport_klimaat
vp1102_natsal | natuurlijk saldo (t.o.v. inwoners) | tabellenrapport_klimaat
vp1102_migsal_int | intergemeentelijk migratiesaldo (t.o.v. inwoners) | tabellenrapport_klimaat
vp1102_migsal_ext | internationaal migratiesaldo (t.o.v. inwoners) | tabellenrapport_klimaat
vp1102_totsal | totale aangroei (t.o.v. inwoners) | tabellenrapport_klimaat

En dus werk voor @VickyVB (rapport_economie), @StefanJacques (omgevingsanalyse_steekkaart, tabellenrapport_klimaat - als ik dit net juist in de lijst van verantwoordelijken heb aangevuld!). Rapport Armoede geeft ook een melding, maar dat is omdat vp3104_rmileefl_ip en vp3104_rmhleefl_ip (leefloners) de gemiddelde statbel bevolking (v1102_t_gem) gebruiken. Geen idee of dat de beste keuze is; alleszins is statbel op zich verdedigbaar omdat de data ook voor Brussel beschikbaar is

**Comment by joostschouppe** [comment]
# Check Dashboard

Methode: excel van hierboven uitgebreid met een export van de map INTERN>Dashboard
Verticaal zoeken in nieuw tabblad Dashboard naar relevante onderwerpen.


ItemCode | Check
-- | --
v1102_geboorte | geboorten
vp1102_geboorte | geboorten (t.o.v. inwoners)
v1102_sterfte | sterfte
vp1102_sterfte | sterfte (t.o.v. inwoners)
v1102_inwijkingen | inwijkingen
v1102_immig_ext | internationale inwijkingen
v1102_inw_int | intergemeentelijke inwijkingen
vp1102_inwijkingen | inwijkingen (t.o.v. inwoners)
vp1102_inw_int | intergemeentelijke inwijkingen (t.o.v. inwoners)
vp1102_immig_ext | internationale inwijkingen (t.o.v. inwoners)
v1102_uitwijkingen | uitwijkingen
v1102_emig_ext | internationale uitwijkingen
v1102_uitw_int | intergemeentelijke uitwijkingen
vp1102_uitwijkingen | uitwijkingen (t.o.v. inwoners)
vp1102_uitw_int | intergemeentelijke uitwijkingen (t.o.v. inwoners)
vp1102_emig_ext | internationale uitwijkingen (t.o.v. inwoners)
v1102_natsal | natuurlijk saldo
vp1102_natsal | natuurlijk saldo (t.o.v. inwoners)
v1102_migsal_tot | totaal migratiesaldo
v1102_migsal_ext | internationaal migratiesaldo
v1102_migsal_int | intergemeentelijk migratiesaldo
vp1102_migsal_tot | totaal migratiesaldo (t.o.v. inwoners)
vp1102_migsal_int | intergemeentelijk migratiesaldo (t.o.v. inwoners)
vp1102_migsal_ext | internationaal migratiesaldo (t.o.v. inwoners)

@VickyVB , kan jij de nodige vervangende onderwerpen in de map Dashboard zetten en een seintje aan @KoenSnyers geven als dit gebeurd is?
Koen, als ik mij goed herinner kan je in Dashboard niet zomaar de onderwerpcode die gebruikt wordt door een presentatie vervangen door een andere. Dus ik vermoed dat die helemaal vervangen moeten worden...

**Comment by joostschouppe** [comment]
@VickyVB : als ik mij goed herinner mochten al deze data EXTERN beschikbaar zijn op statistisch sectorniveau. Dat vereist dat ze [hier](https://provincies.incijfers.be/admin/studio/Table/DetailItemGrid?TableName=AccessGroupItem&ParentKey=AccessGroupCode&ParentCode=5&ParentTable=AccessGroup&ItemKey=V) toegevoegd worden. Ik heb gechecked door [deze presentatie](https://provincies.incijfers.be/jive?workspace_guid=abf9c736-dc1e-4321-9905-068eb430f2e3) zonder inloggen te raadplegen

**Comment by joostschouppe** [comment]
Minder dringend, maar betekent wel dat dit https://github.com/provinciesincijfers/PinC-taakopvolging/issues/84#issuecomment-668580835 nu kan gebeuren!

**Comment by VickyVB** [comment]
@joostschouppe Heb je donderdag (1/10) of vrijdag (2/10) even tijd om ons hierbij op weg te zetten?

**Comment by VickyVB** [comment]
Het rapport economie is aangepast.

**Comment by VickyVB** [comment]
@KoenSnyers 
De nieuwe onderwerpen (geboorte, sterfte, migratie van/naar een andere Belgische gemeente, migratie van/naar het buitenland en de som van beide, natuurlijk saldo, migratiesaldo met Belgische gemeente, migratiesaldo met het buitenland, totaal migratiesaldo) staan in de map van het dashboard. 
@demaesschalckfilip 
Moet er inhoudelijk iets aan het dashboard veranderen of mogen de nieuwe onderwerpen de oude één op één vervangen?

**Comment by demaesschalckfilip** [comment]
Ja, voor mij is dat oké (één op één vervangen)

**Comment by StefanJacques** [comment]
ook aangepast:
omgevingsanalyse_steekkaart
tabellenrapport_klimaat

**Comment by VickyVB** [comment]
Voor de leefloon gegevens moeten we inderdaad bij de Statbel gegevens blijven. v1102_t_gem mag dus blijven bestaan. (eigenlijk zou dat ook de v1101_t_gem kunnen heten ;-) )

Het rapport armoede is dus ook in orde.

**Comment by KoenSnyers** [comment]
@demaesschalckfilip @VickyVB 

Ik heb de nieuwe onderwerpen over de loop van de bevolking vervangen in het dashboard en online gezet.
Ik merk wel dat in de online versie de eerste vier tegels van de verhuisbewegingen (totale immigratie, aantal en promille; totale emigratie, aantal en promille) niet verschijnen omdat er ontbrekende waarden voor de provincies zijn, zo lijkt het.
Kan dit gecheckt worden?

**Comment by demaesschalckfilip** [comment]
Ja dat klopt, omdat totale immigratie en emigratie niet optelbaar zijn (daar zit namelijk ook migratie naar andere Vlaamse gemeenten bij). Ik zal die cijfers voor de provincies en het gewest apart (hard) inlezen, zodat ze op dat niveau ook beschikbaar zijn.

**Comment by VickyVB** [comment]
Kubus1112_loop geeft een overzicht van het type beweging (geboorte, sterfte, migraties, geen verhuis) naar leeftijd, geslacht, nationaliteit, geboortenationaliteit en herkomstnationaliteit.
Momenteel is de kubus opgeladen voor 2019, maar ook de voorgaande jaren zullen aangevuld worden.
Het is de bedoeling dat deze kubus als dusdanig INTERN blijft staan. Voor degenen die ermee aan de slag willen is er een (eveneens interne) infofiche aan gekoppeld.

**Comment by demaesschalckfilip** [comment]
Deze kubus is nu volledig: alle gegevens vanaf 1990 staan er in

**Comment by joostschouppe** [comment]
Volledig afgerond

**Comment by demaesschalckfilip** [comment]
We hebben een nieuwe kubus aangemaakt over de bevolkingsloop, waarin de bevolking op 01/01 staat en alle saldi (natuurlijk, buitenland, Brussel, Vlaanderen, Wallonië, andere sectoren in de gemeente). De optelling van dit alles geeft dan de bevolking op 31/12 (of 01/01 van het volgend jaar). Erg handig, ook om extern te zetten (gemakkelijker te begrijpen dan de kubus die er al in zit, en vooral: alles is optelbaar). Eén probleempje nog: de bevolking op 01/01 zou moeten verborgen worden bij waarden kleiner dan 5, bij de saldi is dat niet nodig (en niet wenselijk). Voorlopig hebben we echter geen manier gevonden om dat te doen in een kubus. Als iemand hier een oplossing voor weet: zeer welkom. Ten slotte nog: ik heb de leeftijdsklassen 25-49 jaar (die, zeker voor migratiegegevens, nogal groot was) opgesplitst in 25-34 en 35-49. Hiermee zit ik aan het maximaal aantal combinaties (net geen 100.000). Moest er iemand nog suggesties hebben voor een andere indeling (van leeftijd of andere variabelen), laat het gerust weten. Moest het over een groter aantal klassen gaan dan nu, geef dan meteen mee welke andere variabelen je zou willen vereenvoudigen. Bij de cijfers voor 2020 kunnen we daar dan rekening mee houden.

**Comment by joostschouppe** [comment]
Redactiegroep: deze kubus komt extern nadat bevolking eruit is gehaald

**Comment by valeriepirard** [comment]
@demaesschalckfilip
zoals ook reeds per mail doorgegeven:
de vragen die ik tot nu toe kreeg over migraties (en opgelost heb met Statbel cijfers) gingen over 20-29-jarigen, 30-39-jarigen, 40-49-jarigen en 50-59- jarigen,hoofdzakelijk op provinciaal en ook gemeentelijk niveau .
Nationaliteit mag wat mij betreft vereenvoudigd (Belg, EU, niet-EU). 
Dus, moest ik die cijfers voor de 10-jaren leeftijdsklassen via de kubus RR kunnen terugvinden, zou dat fijn zijn.
Zie maar wat mogelijk is.

**Comment by demaesschalckfilip** [comment]
De huidige indeling bevat eigenlijk niet veel meer klassen dan de 10-jarige klassen. Vanuit migratie-oogpunt lijken ze echter logischer, gezien ze vertrekken vanuit levensfasen (met bijbehorende migratiepatronen).
Op deze link zien we alvast dat 18-24 jarigen een heel ander migratiepatroon vertonen dan de 25-34 jarigen: https://provincies.incijfers.be/jive?workspace_guid=7e196ca9-5076-4165-8af8-09dcac355af0
Is er een specifieke reden waarom het 10-jarige klassen moeten zijn?
