### ISSUE TITLE
opkuis themaboom & beschrijvingen conform handleiding

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/PinC-taakopvolging#132]
bij opmaak indicatoren/themaboom bouwjaren kadaster kwam ik enkele inconsistenties tegen : afspraken in de handleiding die niet overeenkomen met realiteit.
1. aantal onderwerpen: 
handleiding zegt: We zetten de percentages in een submap indien er meer dan 12 onderwerpen in totaal in de hoofdmap zouden terechtkomen.
dit wordt verre van consequent toegepast
2. beschrijving van de indicator:
handleiding zegt: 'eindigt bij een berekend onderwerp met [percentage], [ratio], [promille], .....
in veel gevallen staat dit niet in de beschrijving. vaak ook aan het begin van de omschrijving. 
mijn voorkeur gaat uit naar het begin van de omschrijving. dan weet je als gebruiker direct dat het om een pc, ratio, promille gaat.

**Comment by HildeC** [comment]
nog een inconsistentie vastgesteld bij beschrijving van formules voor percentages
soms staat er bij de beschrijving van percentages *100. vraag is of dat nodig is? als je zegt dat het een percentage is, en je geeft een teller en een noemer op, dan weet je eigenlijk wel dat je nog *100 moet doen.
in stuk socio economische positie staat nu bv: 
voor werkenden: teller tov noemer *100
voor werkzoekenden: teller tov noemer *100 ¨percentage]


voor promille zou ik het dan wel weer laten staan, omdat dat er nog eens extra de aandacht op vestigd dat het geen percentage is.

**Comment by StefanJacques** [comment]
wordt aangepakt in
#181 Grondige controle  #themaboom / indicatorentabel
