### ISSUE TITLE
Melden van foute/bizarre detailviews dashboard

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#133]
In de nieuwe versie zijn er meer detailviews mogelijk – met name alle presentaties die mogelijk zijn met de data in de Databank.

Da’s fijn – maar wat minder fijn is, is dat we “er de onzin niet meer uit kunnen halen”. Bijvoorbeeld deze treemap is bizar (en sein ik in als bug).

We kunnen proberen de bizarre dingen eruit te halen, maar Swing kan bijvoorbeeld onmogelijk weten dat je geen stapelgrafiek mag maken met “inwoners 0-65 jaar” en “inwoners 18-65 jaar”.

Dus er gaan issues blijven opduiken. Ik heb daarom aan ABF gevraagd om voorlopig de oude interface voor detailviews terug te krijgen. Dat kan, maar:
-	Er is eerst nog een kleine bug die opgelost moet worden
-	We moeten alle detailviews dan weer instellen
-	Als er een andere oplossing komt (wellicht iets als “alle presentaties uit Jive, behalve indien ingesteld dat dit niet mag”), dan gaan wel wellicht opnieuw alles moeten instellen

Aangezien er nu al klachten kwamen over bizarre detailviews, zou ik er voor opteren om dit toch te doen.

**Comment by StefanJacques** [comment]
Collega's Limburg willen de huidige detailviews van het dashboard toch maar aanhouden, in de hoop dat ABF in een volgende release wél de mogelijkheid voorziet om presentatievormen aan- en uit te vinken.
Het dashboard laten terugdraaien naar een vorige versie lijkt ons niet opportuun wegens risico dat er dan weer vanalles onbedoeld gewijzigd wordt plus alle detailviews opnieuw ingesteld moeten worden.
In het huidige dashboard is de eerste detailview steeds een relevante tabel/grafiek ... het is pas als je als gebruiker een andere voorstellingswijze kiest dat er inderdaad "nietszeggende" grafieken zouden kunnen getoond worden.

**Comment by StefanieWVL** [comment]
Hoi Joost,

Kan je wat voorbeelden geven van die klachten over die detailviews? Van wie kwamen die? (Mag ook donderdag op de redactiegroep hoor)

Dit om een betere afweging te kunnen maken, want zoals ik het nu zie, moeten we kiezen tussen 2 niet ideale werelden ... ;-)

**Comment by StefanJacques** [comment]
Afgesproken op redactiegroep van 10-09-2020: we laten het zoals het is (en hopen er op dat ABF de meest problematische gevallen wegwerkt tegen de volgende release).

De redactiegroep moet consequent de probleemgevallen doorgeven via dit issue.

**Comment by StefanJacques** [comment]
PROBLEEMGEVAL 1 (reeds gesignaleerd aan ABF op 14-09-2020

**evolutiegrafieken**
https://provincies.incijfers.be/dashboard/dashboard/bevolking/

Als je een tijdreeks opvraagt – ga specifiek naar onderstaande figuur
 
![image](https://user-images.githubusercontent.com/31841732/93057270-ec077000-f66d-11ea-8307-6c9406f29171.png)


Dan krijg je als detailview te zien:
 
![image](https://user-images.githubusercontent.com/31841732/93057288-f1fd5100-f66d-11ea-9f8d-714e9978eeba.png)


**Deze is oké !**

Maar wat hier -volgens ons- NIET kan, zijn alle presentatievormen die een optelsom tot 100 % voorstellen, nl.

•	gestapelde staaf
•	taartdiagram
•	tree map

![image](https://user-images.githubusercontent.com/31841732/93057318-fcb7e600-f66d-11ea-91c6-2857f69bc317.png)

 
![image](https://user-images.githubusercontent.com/31841732/93057328-017c9a00-f66e-11ea-9ddb-a0140a798746.png)


![image](https://user-images.githubusercontent.com/31841732/93057347-09d4d500-f66e-11ea-804f-691134706974.png)

**Comment by StefanJacques** [comment]
Antwoord ABF:
Stefan,
 
Ik denk dat dit lastig is op te vangen. Omdat voor dit onderwerp het periodetype lopend is opgegeven, is het mogelijk om over de perioden op te tellen. Swing past hierop de presentatiemogelijkheden aan, en maakt het dus mogelijk om soortgelijke figuren te maken. Doorgaans wordt voor dit soort datatypen (% en gemiddelden) **stand als periode type** opgegeven en voorkom je dit dus.

**Comment by StefanJacques** [comment]
Ik heb vervolgens het geboortecijfer, sterftecijfer en natuurlijk saldo (t.o.v. 1.000 inwoners) een veranderd van "pending" (lopend) naar STOCK (stand)

![image](https://user-images.githubusercontent.com/31841732/93186567-1117e380-f73f-11ea-819f-74378515d877.png)

en oké, nu worden WEL ZINNIGE GRAFIEKEN getoond

![image](https://user-images.githubusercontent.com/31841732/93186976-8b486800-f73f-11ea-8a89-280ab5b3581a.png)

**Comment by StefanJacques** [comment]
Redactiegroepleden,
ik zal het periodetype van de relatieve "loop van de bevolking"-cijfers aanpassen van Pending naar Stock, waarna dit probleem alvast opgelost zal zijn.

**Comment by StefanJacques** [comment]
PROBLEEMGEVAL 2 (gesignaleerd aan ABF op 15-09-2020)

staafgrafieken met x percentage-onderwerpen (die samen géén 100 % zijn)
https://provincies.incijfers.be/dashboard/dashboard/nationaliteit-en-herkomst/

deze percentages mogen NIET opgeteld worden:
![image](https://user-images.githubusercontent.com/31841732/93194131-0877db00-f748-11ea-8fa7-527f81c7ee5a.png)

Maar als je de detailview vraagt, zijn er 3 presentatievormen die niet zouden mogen:

De gestapelde staaf
![image](https://user-images.githubusercontent.com/31841732/93194164-10d01600-f748-11ea-993a-f8bf960a1512.png)

De taart
![image](https://user-images.githubusercontent.com/31841732/93194180-162d6080-f748-11ea-93ce-39632cc08c03.png)

En de tree map
![image](https://user-images.githubusercontent.com/31841732/93194198-1c234180-f748-11ea-8e82-9e6dc26fae7f.png)

**Het probleem is dat er in andere gevallen staven WEL mogen opgeteld worden**
Kijk naar volgende grafiek (zijn weliswaar geen percentages -zoals hierboven- maar toch ook x onderwerpen voorgesteld als staven
https://provincies.incijfers.be/dashadmin/preview/dashboard/huishoudens/
![image](https://user-images.githubusercontent.com/31841732/93194319-3ceb9700-f748-11ea-8153-185fc3ac1db8.png)

Hier mogen al deze detailpresentatievormen WEL.
![image](https://user-images.githubusercontent.com/31841732/93194382-4f65d080-f748-11ea-9199-01d87c24c046.png)

**Comment by StefanJacques** [comment]
Antwoord ABF op 16-09-2020
Stefan,
Bedankt voor de melding. We gaan er naar kijken.
**Dit probleem lijkt mij alleen op te lossen door per detailview bepaalde presentatievormen uit te schakelen.** De huidige detailview is een soort mini Swing Viewer, en de eindverantwoording ligt dus bij de gebruiker om zinnige presentaties te maken.

**Comment by StefanieWVL** [comment]
> Redactiegroepleden,
> ik zal het periodetype van de **relatieve** "loop van de bevolking"-cijfers aanpassen van Pending naar Stock, waarna dit probleem alvast opgelost zal zijn.

Goeimorgen

Vraagje: is het dan aangewezen dat elk voor zijn eigen onderwerpen checkt of "%" en "gemiddelde"- onderwerpen steeds als "stock" aangeduid staan (zoals ABF voorstelt voor dat datatype?).

**Comment by StefanJacques** [comment]
> > Redactiegroepleden,
> > ik zal het periodetype van de **relatieve** "loop van de bevolking"-cijfers aanpassen van Pending naar Stock, waarna dit probleem alvast opgelost zal zijn.
> 
> Goeimorgen
> 
> Vraagje: is het dan aangewezen dat elk voor zijn eigen onderwerpen checkt of "%" en "gemiddelde"- onderwerpen steeds als "stock" aangeduid staan (zoals ABF voorstelt voor dat datatype?).

Dag Stefanie,
Als de redactiegroep er zich in kan vinden dat -in mijn geval voor de loop van de bevolking- de absolute cijfers periodetype 'lopend/pending" krijgt en de relatieve cijfers (in promille) periodetype "stand/stock" dan is de volgende stap inderdaad dat eenieder het periodetype van zijn onderwerpen aanpast en oplaadt.

Ik had er bij ABF op gewezen dat wij -bij voorgaande redenering- wel een "probleem" gaan hebben met wat we invullen bij "referentieperiode of -moment" in de metadatafiche (loop van het referentiejaar wordt dus bij absolute cijfers vertaald naar periodetype "PENDING" terwijl we dat dan bij relatieve cijfers moeten zetten op "STOCK" omwille van juiste presentatievormen in het dashboard en de viewer).
Daarop kregen we het compliment dat wij veruit de enige gebruikers zijn die zo gedetailleerd en nauwgezet onze informatiefiches (metadatafiches) aanvullen. Maar dat voor de visualisatie in Swing het dus beter is om het periodetype in de Studio "los te koppelen" van wat er in de metadatafiche omschreven wordt bij "referentieperiode of -moment". 

Kunnen we nog volgen ?

Alvast in bijlage alle "data types" Percentage die momenteel "pending" zijn en die dus als period type "stock" zouden moeten krijgen ten behoeve van de visualisatie in dashboard/viewer.

Ik wil graag in bulk veranderen ... als jullie akkoord gaan.
Bij fundamentele opmerkingen agenderen we toch beter op de volgende redactiegroep (maar ik denk -eerlijk gezegd- dat we hierin geen keuze hebben ???)

[Indicators (pending moet stock worden).xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5236942/Indicators.pending.moet.stock.worden.xlsx)

**Comment by StefanJacques** [comment]
Onderwerpen die een _datatype 'percentage' of 'mean'_ hadden én een periodtype 'pending' zijn allemaal **gewijzigd naar periodtype 'stock'**.
