### ISSUE TITLE
Indicatorenlijst Toerisme (provincies in cijfers)

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#135]
Link naar de voorgestelde onderwerpen / indicatoren Toerisme: https://docs.google.com/spreadsheets/d/1077WVq2sKmT4sNVbdNZpJkHIaoMTBZPgN-b0m8Vd6Tw/edit#gid=1877781061

**Comment by StefanJacques** [comment]
data op gemeentelijk niveau komen INTERN te staan
data op niveau "toeristische regio" EXTERN

**Comment by joostschouppe** [comment]
De redactiegroep is op zich akkoord met deze verwerking - Joost bekijkt nog verder met @karolienbloemen ivm waarom niet op gemeentelijk niveau
