### ISSUE TITLE
Metadatafiches: jaartal/periode van enkele speciale indicatoren

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#136]
Een serieuze doordenker! Bij enkele indicatoren, zoals die over het tandartsbezoek en de kansarmoede-index, is het niet duidelijk wat er moet vermeld worden op de metadatafiche onder de rubriek 'Referentieperiode of -moment'. Graag bespreking hiervan, en een consistente conclusie :-).

**Tandartsbezoek (v5003_gezondheidszorg_ct), geen tandartsbezoek (v5003_gezondheidszorg_gtb) en preventie tandarts (v5002_preventie_tandarts)**
Eigenlijk gaat het om de groep mensen die rechthebbend is in de ziekteverzekering op 31/12. Daarvan gaat men kijken welke tandartsbezoeken ze dat jaar en de twee jaren ervoor gehad hebben. Het gaat hier dus niet over het aantal bezoeken in de loop van een referentiejaar (of - jaren), zo kan dat dus niet aangegeven worden. Het gaat over de kenmerken van die personen op 31/12, dus moet er eigenlijk als referentiejaar het jaar nadien worden aangegeven. Er zou dus eigenlijk moeten staan: 31/12 van het jaar voorafgaand aan het referentiejaar, en het referentiejaar in de databank zou dus eigenlijk jaar x+1 moeten zijn. Maar in IMA-atlas staat er jaar x, dus dit zou het wel verwarrend maken. Blijven we hier consequent onze "31/12/jaar x-1 = 1/1/jaar x"-regel volgen?

**Kansarmoede-index:**
-	Het gaat over geboorten, dus dat lijkt “lopend”
-	Maar het gaat over “kinderen die geboren zijn in een bepaald jaar en woonachtig zijn op een bepaalde plaats op een bepaald moment”, dus toch eerder een momentopname
-	En vervolgens worden die momentopnames tot een “lopend gemiddelde” gecombineerd, waar niet echt een specifieke omschrijving voor bestaat binnen Swing denk ik

**Comment by joostschouppe** [comment]
Zie ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/133#issuecomment-692561592
Wellicht best pragmatisch aanpakken: grafiektypes zijn correcter indien we dit als _stock_ beschouwen
