### ISSUE TITLE
jaartal(len) NIET in Viewer tonen, WEL aanwezig in Studio - hoe best documenteren ?

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#137]
Je kan manueel in de Studio bepalen vanaf welk jaar je start met het tonen van data in de Viewer.

1.
Hoe moeten we documenteren zodat het duidelijk is dat er meer data in de Studio aanwezig zijn dan dat er getoond worden ?
(Eventueel op alfresco in het uploadbestand een info-tabblad maken en daarin vermelden?)
Kan de redactiegroep een afspraak maken hierover en verspreiden?

2.
Wat gebeurt er in vervolgens in de connector? Gaan die niet getoonde data dan wel of niet mee? En kan een centrumstad bv deze dan toch op zichtbaar plaatsen (=niet gewenst)??

**Comment by joostschouppe** [comment]
Bij 1) - welk probleem moet er precies opgelost worden? In theorie is het alvast mogelijk om semi-automatisch een lijst te genereren van onderwerpen waar dit het geval is.
Bij 2) - de Connector maakt van onze onderwerpen "beschermde onderwerpen" aan klant-kant. Dat betekent dat ze geen enkel veld van het onderwerp kunnen aanpassen in hun Swing Studio. Ze kunnen wel een kopie van het onderwerp maken door een nieuw onderwerp te maken en als formule eenvoudig te verwijzen naar het oorspronkelijke onderwerp. Op die manier kan echter NIET de beschikbare periode (of de drempelwaarde, of afronding,...) overruled worden. Zie ook https://github.com/provinciesincijfers/bugsinjive/issues/81
