### ISSUE TITLE
Kleine aanpassing(en) in alle rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#138]
- [ ] figuren moeten ONDER de teksten staan
(best dat elke verantwoordelijke dit eens voor zijn rapport nakijkt en aanpast - of doorgeeft aan David)
- [x] op regel 599 was nog sprake van "Provincies in Cijfers", terwijl het merk "provincies.incijfers.be" is.
- [x] paginanummering in PDF: Setting_PdfPageNumbers = true toevoegen. In sjabloon_rapport op regel 17
- [x] v1101_m wordt gebruikt tweemaal gebruikt om aantallen gebieden te kunnen berekenen. Da's gevaarlijk - in sjabloon reeds vervangen door v1111a_tot_bevolking
- [x] op regels 596-606 zat er een fout in het sjabloon met de paragrafen
- [x] op regel 666 `<a name ="inhoud">` vervangen door `<a id="inhoud">`
- [x] vervang deze stukjes;
```
if count=1 then
        gekozen_gebied = name(item(input_geo,0))
    else if count=2 then 
        gekozen_gebied = show(input_geo, " en ")
    else if count>2 then
        gekozen_gebied = "de gekozen gebieden"
end if

if count=1 OR count = 2 then
        gekozen_gebied_12veel = name(item(input_geo,0))
    else if count>2 then
        gekozen_gebied_12veel = "de gekozen gebieden"
end if
```

door

```
if count=1 then
        gekozen_gebied = input_geo
        gekozen_gebied_12veel = input_geo
    else if count=2 then 
        gekozen_gebied = show(input_geo, " en ")
        gekozen_gebied_12veel = name(item(input_geo,0))
    else if count>2 then
        gekozen_gebied = "de gekozen gebieden"
        gekozen_gebied_12veel = "de gekozen gebieden"
end if
```

**Comment by StefanJacques** [comment]
paginanummering in PDF: Setting_PdfPageNumbers = true toevoegen. In sjabloon_rapport op regel 17
@David - wil je dit alvast toepassen (op vraag van oa. Mieke OVL) in het rapport Buurtgericht Zorg

**Comment by davidcardinaels** [comment]
Toegepast is rapport Buurtgerichte Zorg.

**Comment by davidcardinaels** [comment]
@StefanJacques Is het eerste punt al doorgegeven aan de verantwoordelijken?

**Comment by joostschouppe** [comment]
Ik stuur nu een mail daarover, David. Ik sluit hier af, en vraag om te heropenen moest er een rapport nog niet in orde zijn.
