### ISSUE TITLE
Rapport Landbouw

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#139]
In november zou Landbouw klaar zijn met een voorstel van rapport. Heeft iemand interesse om dit rapport te programmeren?
Project-trekkers zijn Jona en @Tine-VB.

**Comment by VickyVB** [comment]
Lieven wil het rapport Landbouw programmeren

**Comment by Tine-VB** [comment]
Openstaande vragen bij rapport landbouw:
* "10 jaar geleden": nemen we dan 11 jaar of 10 jaar? Dus 2008-2018 of 2009-2018

**Comment by joostschouppe** [comment]
Tine, vraag je anders per mail aan de redactiegroep om het rapport na te kijken in zijn huidige vorm? Dus de Drive link van het rapport rondsturen. Volgens mij moet van je lijstje enkel vraag 2 expliciet voorgelegd worden. Want:
1. dit kan eenvoudig aangepast worden als 171 nog niet afgehandeld zou zijn
2. inderdaad na te vragen
3. kan tijdens het programmeren mee geëxperimenteerd worden
4. Meerdere gemeenten: zie https://github.com/provinciesincijfers/PinC-taakopvolging#taakverdeling-rapporten en https://github.com/provinciesincijfers/PinC-taakopvolging/issues/175 > **graag geen nieuwe uitzonderingen** op het aansturen van de rapporten. Dit kan opgevangen worden door van een aantal stukken te zeggen: "toon dit deel enkel indien er slechts één gemeente gekozen is"

**Comment by joostschouppe** [comment]
Rapport is gepubliceerd
