### ISSUE TITLE
project Kadaster

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#140]
- re-run en controle bestaande gegevens
- uitbreiding met cijfers over bouwjaren: https://provincies.incijfers.be/jive?workspace_guid=87f26661-f681-4727-8b78-dc0b1dcaf68c - controle gevraagd!
- kubus woongelegenheden (functie, bewoning, bouwjaar, wijziging, bouwvorm) - feedback welkom! https://provincies.incijfers.be/admin/jive?var=kubus2210_woongelegenheden - moet nog afgestemd worden in Kadaster-werkgroep
- tabel beschikbaar om gezinshoofd aan meest waarschijnlijke eigendom toe te kennen
- analysewerk: de toekenning van inwoners is NIET exact; met name of ze eigenaar/huurder zijn zou in theorie beter kunnen door ingreep aan kant CEVI. De vraag is of dit problematisch is. Dat kunnen we analyseren: is er een sterk verband tussen demografische kenmerken en de huurder/eigenaar-vraag? Wellicht wel. In complexe situaties (meerdere eigendommen met eenzelfde adres) worden mensen ad random toegekend - als de groep die ad random toegekend wordt groot is, en vaak uit mensen bestaat die divers zijn op demgrafische kenmerken, dan kan dit tot systematische fouten leiden.

**Comment by StefanJacques** [comment]
Op de redactiegroep van 10-09-2020 wordt afgesproken:

- @ChrisMichelDS zal naar de data kijken maar eerst even met Joost of Karolien het script nog eens overlopen. 
- Joost heeft een draft kubus woongelegenheden gemaakt en vraagt nazicht. 
er is een tabel beschikbaar: ‘dit gezinshoofd, zit in dat eigendom’. 
- Input over welke indicatoren eerst opgenomen moeten worden, is welkom.

**Comment by StefanieWVL** [comment]
Ter info:
We hebben in onze eigen kubussen kadaster en rijksregister gekruist en kunnen hier het volgende uit halen voor de referentiepersonen:
- huidig woningtype
- vorig woningtype (om verhuisgeneigdheid te bekijken
- volgend woningtype (om te zien naar welk woningtype mensen verhuizen)

En voor elke referentiepersoon kennen we dus ook de leeftijd, de gezinssamenstelling, het geslacht, nationaliteit. Vooral de kruising tussen woningtype en leeftijd en gezinssamenstelling lijkt me interessant. En dit in combinatie met de verhuisbewegingen (bv. om te zien of er bij ouderen vaker van woningtype veranderd wordt en op welke leeftijd ze voornamelijk verhuizen in het kader van kwetsbaarheid/preventie)
