### ISSUE TITLE
PinC planning 2021

### ISSUE THREAD

**Issue by dgees** [provinciesincijfers/PinC-taakopvolging#142]
Graag binnen de redactie een bespreking over wat haalbaar is om binnen PinC te realiseren in 2021. 
Vandaar de vraag om:
- een korte svz op te maken m.b.t. planning 2020
- op te lijsten wat in planning 2021 moet komen en welke provinciale projecten er misschien nog komen tussen fietsen

Zie: 
https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/5ee48f87-c8a4-4aff-b2b3-dd15a59e9913

en

https://share.vlaamsbrabant.be/share/page/site/socialeplanning/documentlibrary#filter=path%7C%2FAlgemeen%2FBeleidsdocumenten%2FPlanning%2520en%2520evaluatie%2F2020%2520planning%2520en%2520jaarverslag%7C&page=1

**Comment by joostschouppe** [comment]
Zie ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/61

**Comment by joostschouppe** [comment]
Uit de prioriteitenlijst:

Thema | Subthema | versterken?
-- | -- | --
Wonen | Kadaster-verwerking | interprovinciaal?
Communicatie | Werkgroep   communicatieplan | Stephanie P
Rapporten | Rapport   buurtgerichte zorg | afgehandeld
Rapporten | Rapport   demografie | afgehandeld
overeenkomsten | nieuwe   overeenkomst KSZ | Stephanie P
Rapporten | Rapport   kerncijfers obv buurt/wijk | interprovinciaal?
Wonen | Wonen   - rapport (uitbreiding nr IGS) | versterken?
Rapporten | ELZ/VIVEL |  
overeenkomsten | nieuwe   overeenkomst Wonen Vlaanderen |  
Communicatie | Promoten   D&A bij partners | Stephanie P
Gebiedsniveaus | Wijkniveau | provinciaal
overeenkomsten | nieuwe   overeenkomst RSZ |  
Mobiliteit | bijkomende   indicatoren | interprovinciaal?
Ruimte | ruimtelijke   indicatoren | interprovinciaal?
Economie | Economische   data + rapport arbeidsmarkt |

**Comment by joostschouppe** [comment]
Nog toe te voegen:
* Opleidingstraject
