### ISSUE TITLE
26 november - Trefdag Digitaal Vlaanderen  #TDV2020

### ISSUE THREAD

**Issue by zenebben** [provinciesincijfers/PinC-taakopvolging#144]
Vraag van Deirdre: de AIV beurs gaat digitaal door: willen we een virtuele stand bemannen? En hoever willen we gaan m.b.t. de digitale mogelijkheden?

**Comment by zenebben** [comment]
Beste collega’s 
Virtueel evenementen hosten zal meer en meer deel uitmaken van de toekomst. Het beste aan’ online’ evenementen is de mogelijkheid om veel meer mensen te bereiken dan enkel die in de eigen omgeving en dus ook een publiek bereiken die we misschien anders nooit zullen bereiken. Fysieke evenementen zijn uiteraard beter voor de contacten, maar anderzijds heeft een digitaal evenement ook zijn voordelen: 

•	Voor bezoekers is een digitaal evenement minder gedoe. Ze hoeven zich geen zorgen te maken over reistijd, files en parkeerkosten …
•	Een bijkomend voordeel van een online evenement is de hoeveelheid interactie die mogelijk is met de bezoekers. Omdat iedereen gelijke aandacht krijgt, is er genoeg ruimte om vragen te beantwoorden
•	Ik lees dat, zodra het evenement is aangemaakt de configuratie 1 jaar beschikbaar blijft. De configuratie kan binnen dat jaar zo vaak als gewenst worden hergebruikt zonder extra kosten. Dat is toch ook mooi meegenomen, maar vraagt in de praktijk wellicht wel nazorg en opvolging
•	Tot 250 gratis bezoekersticket. Deelnemers zijn geregistreerde gebruikersaccounts die na aanmelding toegang krijgen tot één evenement.

Omdat het de eerste keer is dat we digitaal zouden gaan en dus in een experimentele fase zitten, lijkt mij het volgend pakketje meer dan voldoende: 

Basisstand: 
•	Een billboard met bedrijfslogo en url, en een communicatiemodule waarmee de bezoeker rechtstreeks contact kan opnemen op basis van Teams Live. Je ziet de avatars van de bezoekers in de ruimte, en kan ze ook zelf aanspreken. Bezoekers kunnen hun gegevens droppen zodat we ze later kunnen contacteren
Kostprijs: basisformule kost €500. Niet-commerciële organisaties betalen €250
Extra’s:

•	Een introfilmpje van max. 90 seconden op je billboard. Bezoekers die voorbijkomen zien deze animatie en kunnen je meteen aanspreken. De kost is hiervoor op te splitsen: voor de productie zorg je zelf, of je doet een beroep op onze partner Sylvester Events. De plaatsingskost is €250.

Of  een Podcast kan ook. Al heb ik een voorkeur voor een introfilmpje door een professional. Kan snel gaan, maar zal wellicht wel wat kosten

•	Podcast opnemen. Podcasts zijn de ideale manier om de bezoekers te informeren over je bedrijf. Veel professionals luisteren naar podcasts, omdat je deze kan combineren met woon-werk verkeer of sportactiviteiten. Alle podcasts worden verzameld in een bibliotheek. Deze zullen later ook nog beschikbaar zijn via de website van de Trefdag Digitaal Vlaanderen. De kost is hiervoor op te splitsen: voor de productie zorg je zelf, of je doet een beroep op onze partner Sylvester Events. De plaatsing in de bibliotheek: €250. 
•	
Conclusie: ik denk dat we de boot best niet missen. Enkel een billboard lijkt mij niet voldoende en minder aantrekkelijk om de virtuele bezoekers binnen te loodsen.
groeten
Zeneb

**Comment by joostschouppe** [comment]
Besproken op IPWG:
- we gaan een stand nemen
- Hilde checkt of WV intern een filmpje over de D&A-werking kan laten maken

**Comment by zenebben** [comment]
Goed idee!
