### ISSUE TITLE
PinC - ppt voor instructiefilmpje 'Assistent voor je eerste presentatie'

### ISSUE THREAD

**Issue by zenebben** [provinciesincijfers/PinC-taakopvolging#148]
Hallo iedereen
willen jullie de PowerPointpresentatie  eens bekijken voor het filmpje over het gebruik van 'assistent voor je eerste presentatie'. Na jullie opmerkingen / aanpassingen kan het doorgestuurd worden naar mijn collega van de dienst communicatie. Merci

**Comment by miekevanopstal** [comment]
hierbij de ppt

[instructievideo_met_ tekst_databank_02102020_opmerkingen_aangepast.pptx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5318917/instructievideo_met_.tekst_databank_02102020_opmerkingen_aangepast.pptx)

**Comment by StefanieWVL** [comment]
Hallo

Hier enkele suggesties:
- slide 6 en 7 vertellen quasi hetzelfde > 1 slide?
- slide 9: Toevoegen "Je kan ook meerdere jaren selecteren"?
- Slide 22: zinsbouw " ... of een nieuwe presentatie beginnen"
- Algemene suggestie: checken of er na elke zin steeds een punt staat (nu soms wel en soms ook niet)

Groetjes

Stefanie

**Comment by zenebben** [comment]
- Slide 6 en 7 idd aangepast naar 1
- Slide 9: meerdere jaren selecteren. Was ook een opmerking van Mieke. Maar als je assistent gebruikt dan kan je maar 1 jaar selecteren en dan verspringt het naar de volgende stap. Vandaar dat ik "meerdere" er niet heb ingezet. Tenzij ikzelf fout ben natuurlijk, maar mij lukt dat niet . De meerdere jaren kunnen wel 'begin een nieuwe presentatie'. Up to jullie 
- Zinsbouw aangepast
- check puntjes indeed

groetjes
Zeneb

**Comment by zenebben** [comment]
De presentatie met de vragen voor aanpassingen zet ik er nu nog niet terug op, anders is dat moeilijk te volgen voor de rest. De eindversie met al de gevraagde aanpassingen zal ik eind deze week terug in GitHub zetten

**Comment by StefanieWVL** [comment]
Hey Zeneb

Alvast bedankt voor de aanpassingen. Ik bekeek het nog eens, en mij lukt het wel om in de assistent meerdere jaren te selecteren. Dit ter info. Je ziet maar wat de rest ervan zegt.

Groetjes

**Comment by zenebben** [comment]
oké dan pas ik dat aan

**Comment by joostschouppe** [comment]
We wachten op een nieuwe versie van @zenebben

**Comment by zenebben** [comment]
als er geen andere opmerkingen meer zijn dan neem ik aan dat ik de presentatie kan doorgeven voor het ineensteken van het filmpje? Graag bevestiging. 
merci
Zeneb

**Comment by StefanJacques** [comment]
In navolging van gisteren op de redactiegroep besproken in [issue](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/150), wil ik er graag voor zorgen dat bovenstaande vraag van Zeneb terechtkomt bij de Redactiegroep. Ik heb daarom de Redactiegroep geassigneerd, zodat jullie mee op de hoogte blijven van dit issue. 
**Bevestigen jullie (of geef nog opmerkingen door).**
ter info @joostschouppe

**Comment by VickyVB** [comment]
Is dit niet quasi de instructievideo die nu al online staat? Ik zou daar het eerste deel over de wizard gewoon behouden (wel moderniseren naar de huidige look en feel), het lijkt me net iets sneller te gaan dan de ppt en een wizard is nu toch net bedoeld om niet te veel bijkomende instructie te vereisen. 
Mocht er toch nog meer over gezegd moeten worden, kan hier misschien de zoekfunctie even onder de aandacht gebracht worden.

Vanaf 'hoe kan je een presentatie aanpassen?' 
- slide 14 of 1:07 : Je klikt in principe niet op de vinkjes (die zijn er meestal niet) maar op de onderwerpen. het vinkje geeft dan aan of je onderwerp geselecteerd is
- slide 15-16: Goed dat er iets wordt toegevoegd over de verschillende gebiedsniveaus en mogelijkheid om gebieden uit te splitsen!
- slide 21 zou ik weglaten. Daarentegen zou ik hier wel iets toevoegen over het tweede tabblad van het schilderspalet (gebied) waar je bijvoorbeeld een favoriet gebied kan aanduiden op kaart.
- slide 22 gaat toch over twee zeer verschillende zaken, met name een andere presentatievorm of een bewerking op het hele tabblad. Ontdubbelen of allebei weglaten?
- slide 23 Nakijken of deze lijst nog up to date is. Ik dacht dat de treemap er ondertussen ook bijgekomen is en misschien nog andere presentatievormen. Verder inderdaad benadrukken dat de mogelijkheden afhankelijk zijn van je eerdere selecties.
- slide 25 Net als in het filmpje misschien verwijzen naar alle mogelijkheden en niet enkel wijzen op excel dat lijkt ook wat in slide 26 staat ivm url.

Tot slot, moet je ook niet kort aangeven dat er nog aanpassingen mogelijk zijn met al die andere symbolen: bv. transformaties, totalen, kantelen, wijzig indeling?

**Comment by miekevanopstal** [comment]
@Vicky

Is dit niet quasi de instructievideo die nu al online staat? 
-	**_Quasi niet neen. De opzet is wel dezelfde.  Om zo’n instructievideo te maken moet je wel van ‘0’ vertrekken en dus volledig herbeginnen. M.a.w. er worden opnieuw 2 powerpoint presentaties gemaakt:_** 
•	**_ééntje met printscreens uit PinC én met tekst. Een soort stappenplan voor mijn collega die de instructievideo gaat maken (wat nu is opgeladen in Github). Je moet het dus door zijn bril zien
•	en ééntje zonder tekst om te gebruiken voor de montage zelf van de instructievideo._**  

Mocht er toch nog meer over gezegd moeten worden, kan hier misschien de zoekfunctie even onder de aandacht gebracht worden. 
- **_aangepast. Zie hiervoor slide 5_**


slide 14 of 1:07 : Je klikt in principe niet op de vinkjes (die zijn er meestal niet) maar op de onderwerpen. het vinkje geeft dan aan of je onderwerp geselecteerd is
-	**_Klopt inderdaad. Maar wat hier staat zijn de handelingen voor de collega die het filmpje gaat maken. M.a.w  hij moet weten wat hij moet doen. In dat geval dus 'de onderwerpen aanvinken' en de bijhorende tekst erbij zetten om het filmpje te maken (= slide 13)_**

slide 15-16: Goed dat er iets wordt toegevoegd over de verschillende gebiedsniveaus en mogelijkheid om gebieden uit te splitsen
-	**_ok_**

slide 21 zou ik weglaten.
-	**_de slide zou ik niet weglaten want het is het resultaat  van de vorige slide wanneer je op 'ok' klikt. Het resultaat is dat je ziet dat de titel is gewijzigd (= slide 20)_**


Daarentegen zou ik hier wel iets toevoegen over het tweede tabblad van het schilderspalet (gebied) waar je bijvoorbeeld een favoriet gebied kan aanduiden op kaart. 
-	**_Ik heb mijn bedenkingen hierbij. Bedoeling van de instructievideo is om uit te leggen hoe de assistent te gebruiken voor ‘je’ eerste presentatie. M.a.w. de gebruiker zal vooral een beginnen zijn. Een favoriet gebied aanduiden op zich geen probleem. Maar iemand die nog niet goed weet hoe PinC te gebruiken heeft zal ook niet meteen doorhebben wat het nut is van een favoriet gebied. Is natuurlijk wel uit te leggen in een opleiding, maar in het filmpje heb ik wel mijn twijfels. Maar goed, ik heb de slides aangemaakt van 21 tem 24. Er zijn er natuurlijk wel 4 bij._** 

slide 22 gaat toch over twee zeer verschillende zaken, met name een andere presentatievorm of een bewerking op het hele tabblad. Ontdubbelen of allebei weglaten? 
-	**_ik heb ze weggelaten_**

slide 23 Nakijken of deze lijst nog up to date is. Ik dacht dat de treemap er ondertussen ook bijgekomen is en misschien nog andere presentatievormen. Verder inderdaad benadrukken dat de mogelijkheden afhankelijk zijn van je eerdere selecties.
- **_indien er een nieuwe versie bestaat, graag doorsturen. Ik heb deze niet_** 

slide 25 Net als in het filmpje misschien verwijzen naar alle mogelijkheden en niet enkel wijzen op excel dat lijkt ook wat in slide 26 staat ivm url.
-	**_aangepast_**

Tot slot, moet je ook niet kort aangeven dat er nog aanpassingen mogelijk zijn met al die andere symbolen: bv. transformaties, totalen, kantelen, wijzig indeling
-	**_Het filmpje is bedoeld voor beginners ‘assistent voor je eerste presentatie’ . Dit wordt te ingewikkeld en bovendien ook veel te lang. Dat soort toepassing is voor gebruikers die het gebruik van de tool in de vingers hebben. Vandaar dat het hier niet opgenomen is._** 
[instructievideo_met_ tekst_databank_opmerkingen_aangepast_GitHub_21102020.pptx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5429357/instructievideo_met_.tekst_databank_opmerkingen_aangepast_GitHub_21102020.pptx)

**Comment by miekevanopstal** [comment]
Collega's ik heb gisteren met Zeneb samengezeten nav een aantal vragen op de IPWG over de filmpjes.
**Vraag 1: stand van zaken van de verschillende filmpjes:**
- rapporten: gemonteerd en af
- gebruikersonderwerken: gemonteerd en af
- basisprincipes: in de fase dat de opmerkingen aangepast zijn en een laatste check net voor montage
- voorlopig geen andere filmpjes in de maak. Zijn nog andere filmpjes gewenst? 

**Vraag 2: kunnen we een overzicht krijgen van hoe de filmpjes tot stand komen (werkwijze) en welke stappen ze doorlopen met timing?**
zie hiervoor document als bijlage: [PinC Filmpjes_Procesflow.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5429476/PinC.Filmpjes_Procesflow.docx)

**Vraag 3: Kan de laatste dia "dit filmpje is een product van de provincie Oost-Vlaanderen" weggelaten worden?** Zoals eerder vermeld, was dit een expliciet voorwaarde van de communicatiedienst van OVL  bij het monteren van het allereerste 
filmpje. Dit is toen zo meegedeeld aan de IPWG en dat was toen geen probleem. We kunnen nog eens proberen bij onze communicatiedienst om deze dia te laten schrappen. Zeneb heeft die alvast uit de voorbereiding gehaald. Lukt dit niet, voegen we aan de dia toe "Provincies.incijfers.be is een product van "alle logo's" (zoals overeengekomen op de IPWG van 24/9/2020)

**Vraag 4: Kunnen we eventueel zelf de filmpje monteren, los van de communicatiedienst?** Zo kunnen we flexibeler inspelen op de wijzigingen in PinC en meer up to date blijven met de filmpjes.
Zeneb bevraagt onze communicatiedienst met welke tool de filmpjes worden gemaakt en of we daar eventueel ook toegang zouden kunnen toe krijgen.

**Comment by KoenSnyers** [comment]
Inhoudelijk heb ik geen aanvullingen/opmerkingen meer, ook niet bij de andere filmpjes. 
Wel is het belangrijk om een dia 'provincies.incijfers.be is een product van (alle logo's)' als dia op te nemen, liefst ter vervanging van de dia dat het filmpje een product is van O-Vl.

**Comment by zenebben** [comment]
Kan er iemand mij een nieuwe versie sturen van de mogelijke presentatievormen aub? Zie opmerking Vicky slide 23. Bedankt.

**Comment by miekevanopstal** [comment]
Collega's
Indien er geen opmerkingen meer zijn, zou Zeneb de presentatie aan de communicatiedienst willen bezorgen (**donderdag 12/11/20**) om deze te monteren. Daarmee zitten we aan stap 7 (zie hiervoor: [PinC.Filmpjes_Procesflow (1).docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5509357/PinC.Filmpjes_Procesflow.1.docx)).
Hierna zijn er geen wijzigingen meer mogelijk.
We voorzien wel nog een nieuw overzicht van de presentatievormen en proberen de laatste dia met dit is een product van de provincie Oost-Vlaanderen eruit te krijgen.

**Comment by miekevanopstal** [comment]
![Presentatiemogelijkheden i SWING](https://user-images.githubusercontent.com/56152293/98523301-0c226c80-2276-11eb-9878-19aa04ea6b92.PNG)

**Comment by SofieWVl** [comment]
Presentatievormen zijn, zoals al gezegd is dit afhankelijk van je selectie.  Voor een beginnende gebruiker lijkt het me vooral belangrijk te tonen dat het mogelijk is de presentatievorm aan te passen en waar dat dan kan. Dat komt nu duidelijk naar voor.

Voor West-Vlaanderen ok, geen aanvullende opmerkingen meer bij dit filmpje.

**Comment by zenebben** [comment]
[instructievideo_met_ tekst_databank_12112020_opmerkingen_aangepast.pptx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5536127/instructievideo_met_.tekst_databank_12112020_opmerkingen_aangepast.pptx)

Nog eens de allerlaatste versie voor jullie.
ik heb er een dia aan toegevoegd met de logo's van de provincies

**Comment by miekevanopstal** [comment]
Zeneb
ik ben niet meer mee?
Zou jij dit donderdag niet bezorgen aan communicatie?
Ik had de indruk dat er geen wijzigingen meer konden worden doorgegeven.
Ik begrijp jouw vraag naar nieuwe mogelijke opmerkingen niet?
Of mis ik iets?

Met vriendelijke groeten

D&A OVL- Mieke Van Opstal
09 267 75 03 | mieke.van.opstal@oost-vlaanderen.be<mailto:mieke.van.opstal@oost-vlaanderen.be>
D&A<http://www.oost-vlaanderen.be/dataenanalyse> | provincies.incijfers<https://provincies.incijfers.be/dashboard>| maandelijkse nieuwsbrief<http://eepurl.com/glyCFz>.
[logo enkle]


Van: zenebben <notifications@github.com>
Verzonden: vrijdag 13 november 2020 11:15
Aan: provinciesincijfers/PinC-taakopvolging <PinC-taakopvolging@noreply.github.com>
CC: Van Opstal Mieke <mieke.van.opstal@oost-vlaanderen.be>; Comment <comment@noreply.github.com>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] PinC - ppt voor instructiefilmpje 'Assistent voor je eerste presentatie' (#148)


instructievideo_met_ tekst_databank_12112020_opmerkingen_aangepast.pptx<https://secure-web.cisco.com/1MpIirQWKtMLaAfxz0u3Rv9g3RMgNMk-KBbjk5K8a6vSYz-c6CLyDH76iSu-n4WplHl6zU_R_zD8_XHTmquzi-LVKIp7i-YkG11Oety3X1Rxr6KTc8bLiyfr6DLwAWvtoUL4e9ykNM0DR1OPI7XKAPrN4nP1LHrqziqrzI37FgRLs-WvXLev5Yaqa8JDa2q3h8I7e-hzaCexzFHwZ24YOyj81h7M-3B1GpI9a1yo-uiqnKj23ZaloroP5GFCZZ13vKVZFvBPrdrYvgiFP6Bt-Ii0ry7oiLm6GkBs72t6otngrjdS3KCYPQBrHvEVdNEV0P5i4q4DBQdreLFPvNBu8Kw/https%3A%2F%2Fgithub.com%2Fprovinciesincijfers%2FPinC-taakopvolging%2Ffiles%2F5536127%2Finstructievideo_met_.tekst_databank_12112020_opmerkingen_aangepast.pptx>

Nog eens de allerlaatste versie voor jullie.
ik heb er een dia aan toegevoegd met de logo's van de provincies

**Comment by zenebben** [comment]
De laatste versie met logo is louter ter info. 
groeten
Zeneb

**Comment by joostschouppe** [comment]
@zenebben : zijn er ondertussen al versies finaal? Alleszins, laat het weten als je hulp nodig hebt voor effectieve publicatie; of als ze ergens online staan

**Comment by zenebben** [comment]
Hallo iedereen
het instructiefilmpje eerste presentatie staat op alfresco: 

https://share.vlaamsbrabant.be/share/page/site/socialeplanning/documentlibrary#filter=path%7C%2FProvincies%2520in%2520Cijfers%2FGebruik%2520handleidingen%2520tips%2FFilmpjes%7C&page=1

ik kan het precies hier niet uploaden want 'we don't support that file type".
Bekijken jullie het even? 
Feedback graag tegen woensdag 16 december voor detailaanpassingen. Kan ik nog doorgeven dan aan mijn collega van communicatie. De eindversie wordt dan weer op alfresco gezet om te publiceren.

groeten
Zeneb

**Comment by Lievendr** [comment]
Zeneb
Na 1:57 wordt het schilderpalet niet omcirkelt, maar de wereldbol…

**Comment by SofieWVl** [comment]
Beetje 'wachtrij vibe' door het muziekje (stond rap op mute). 
Verder prima.

**Comment by joostschouppe** [comment]
Twee filmpjes zijn gepubliceerd op YouTube en zonder cookie toegevoegd aan https://provincies.incijfers.be/dashadmin/preview/gebruik-van-de-website . Eerdere afspraak was om een knop te voorzien bij "over de website" die hiernaar doorverwijst.
Vraag: wat met huidig algemeen introfilmpje?

**Comment by joostschouppe** [comment]
Voorlopig:
- landingspagina databank
- in themaboom
- oude video gaat weg
- blokje bij op "over deze site"

**Comment by joostschouppe** [comment]
De instructiefilmpjes staan nu klaar voor publicatie (morgen staan ze zichtbaar). Maar dit ticket kan nog niet toe, aangezien "assistent voor je eerste presentatie" nog niet beschikbaar is!

**Comment by joostschouppe** [comment]
Net nog de assistent voor je eerste presentatie klaargezet voor publicatie vanavond. Merci @zenebben !
