### ISSUE TITLE
betere duiding beperking van alle cijfers

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#149]
Voorstel:
op de pagina https://provincies.incijfers.be/dashboard/over-provincies-incijfers-be/

_We gebruiken data uit een selectie aan bronnen. Maar elke bron heeft zijn beperkingen. Zelfs een bevolkingsaantal mist bijvoorbeeld de daklozen. Bij elke bron kan je daarom een uitgebreide metadatafiche raadplegen. Heb je toch nog ~~twijfels~~ vragen bij interpretatie? Contacteer ons!_

**Comment by StefanieWVL** [comment]
Heb je toch nog **vragen** bij interpretatie?

**Comment by joostschouppe** [comment]
Plaatsen op:
* https://provincies.incijfers.be/dashboard/over-provincies-incijfers-be/
* https://provincies.incijfers.be/dashboard/dashboard/bronnen-2/
* landingspagina Databank

Contactgegevens van metadatafiches: iets toevoegen om het uitnodigender te maken om vragen te stellen

**Comment by KoenSnyers** [comment]
@joostschouppe 
Joost, is het de bedoeling dat ik dat tekstje ergens opneem op die twee pagina's?

**Comment by joostschouppe** [comment]
Graag :)

**Comment by KoenSnyers** [comment]
@joostschouppe 

Ik heb de tekst (in wat aangepaste vorm) toegevoegd op de pagina Over de site en bovenaan op de pagina Bronnen.
Op de pagina Over de site heb ik ook wat blokken herschikt (omdat ik het blok links bovenaan nu hoger werd).
Ik heb op deze pagina ook nog de inschrijflink voor de nieuwsbrief aangepast (dat was nog de oude link naar Mailchimp).
