### ISSUE TITLE
nakijken gebruik oppervlaktes als noemer

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#151]
Bebouwingsgraad gebruikt v9900_oppervl, niet v9900_statsec_oppervl_m2. Dat is wellicht fout:

In beide zit de oppervlakte van de oude en de nieuwe statsec, steeds volgens onze eigen verwerking op de GIS-lagen (sterk vereenvoudigde voor de oude, lichtjes vereenvoudigde voor de nieuwe)
In v9900_oppervl zit ook de oppervlakte van de gemeenten (versie van voor de fusies van 2018-2019) zoals statbel die verdeelt. Dit om exact dezelfde cijfers te kunnen bekomen.
Voor data die we zelf in GIS verwerken, gebruiken we daarom v9900_statsec_oppervl_m2, zodat de sommen zouden kloppen. Voor data die statbel ook publiceert, gebruiken we v9900_oppervl, zodat de cijfers overeen zouden komen. Op subgemeentelijk niveau heeft dat natuurlijk geen impact.

Mogelijke oplossingen:
* nakijken waar beide onderwerpen als noemer gebruikt worden
* toch verwijderen gemeente-oppervlaktes statbel

**Comment by Tanja-OVL** [comment]
de indicator ‘totale oppervlakte’ per gemeente in PinC is nog de oppervlakte tot 2017. Vanaf 2018 zijn de oppervlakten van de gemeenten echter veranderd door een andere berekening:
Zie bericht op website Statbel: ‘Tot en met 2017 werd de berekening van de totale oppervlakte gebaseerd op de bestanden uit de kadastrale legger van de FOD Financiën. De gegevens in die databank werden oorspronkelijk gedefinieerd tijdens de Napoleontische tijd (toen het Kadaster werd opgericht).
Vanaf de resultaten van 2018 zijn de totale oppervlakten afkomstig van de databank CADGIS van de FOD Financiën. De gegevens in die databank zijn gebaseerd op de meest recente meettechnieken. De totale oppervlakten zijn sindsdien ook in lijn met internationale conventies en de richtlijnen van Eurostat, het Europese statistiekbureau. Om die reden werd de oppervlakte van de kuststrook tot aan de laagwaterlijn meegerekend bij de tien kustgemeenten. Deze nieuwe berekeningsmethode heeft enkel een invloed op de totale en de niet-gekadastreerde oppervlakten.’ https://statbel.fgov.be/nl/themas/bouwen-wonen/bodembezetting-volgens-het-kadasterregister 

Hierdoor is de oppervlakte per gemeente verschillend van de som van de oppervlakten van de stat sectoren in die gemeente.
Als je bepaalde indicatoren zelf berekent, bv. ruimtebeslag per ha, dan levert dit ook andere resultaten dan wat je in PinC krijgt. 

Het is aan te raden om de nieuwe oppervlaktes van Statbel per gemeente in PinC te steken (v9900_oppervl). Als je per provincie kijkt, dan wijkt de totale (nieuwe) oppervlakte max 5 ha af van de oppervlakte van de statsec (bv. Oost-Vlaanderen: 300706 ha (Statbel vanaf 2018) tgo 300712,24 PinC (tgo nu in PinC Statbel tot 2017: 298223,89ha)). Andere optie is om de gemeente-opp van statbel volledig te verwijderen.

**Comment by Tanja-OVL** [comment]
sorry, afwijking op niveau van de provincie is max 6 ha

**Comment by joostschouppe** [comment]
Zie ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/159 en https://github.com/provinciesincijfers/PinC-taakopvolging/issues/174

**Comment by joostschouppe** [comment]
Ter herhaling, er zijn TWEE reeksen met oppervlakten:
- in beide zit op niveau statsec de in GIS berekende oppervlakten van zowel de oude als de nieuwe statistische sectoren
- in v9900_oppervl zit BIJKOMEND ook de officiële oppervlakte van de OUDE gemeenten

* Omdat oppervlakte nu tijdsonafhankelijk is gedefinieerd, blijven die verouderde officiële oppervlakten gebruikt worden in sommige situaties.
* Voor berekeningen die wel zelf in GIS doen, moeten we werken met `v9900_statsec_oppervl_m2` (waar énkel data op statsec is ingeladen). Voor GRB-bebouwingsgraad heb ik dit nu gecorrigeerd.
* Voor ruimtebeslag is dit wel in orde, [zoals hier blijkt](https://provincies.incijfers.be/jive?workspace_guid=bb7598a8-7940-4d86-b6ef-d441e2bded78). Let wel, hier hebben we dus `v9900_statsec_oppervl_m2` gebruikt (die op zichzelf niet in de themaboom staat). Als je dus zelf berekeningen doet op gemeenteniveau met de data die je gemakkelijk in Swing ziet, dan gaat het fout.

We zouden er vanuit moeten kunnen gaan dat de oppervlaktes die Statbel publiceert steeds dezelfde zijn. En die zouden we moeten kunnen berekenen op basis van hun bestand met de statistische sectoren. Complicerende factor is dat de geometrie van de sectoren (en dus hun oppervlakte) nu elk jaar wijzigt. Als we de cijfers per provincie van de kadastrale statistieken naast de attribuut-info van de statsec-shapefiles zetten (opgeteld per provincie), dan komen we dicht in de buurt, maar niet helemaal! Het wordt nog erger: als we zelf de oppervlakte berekenen (in ArcMap) dan komen we nog een ander getal uit. En dat is zo ongeveer het nieuwe getal dat we zélf gebruiken - immers doen we zelf oppervlakteberekeningen voor allerlei versnijdingen van statsec, en dat moet natuurlijk tot 100% tellen. De vraag is dus maar hoe Statbel aan andere oppervlaktes voor hetzelfde geometrisch object komt als wij. Dat is niet eens zo moeilijk, want als ik het in QGIS bereken, dan krijg ik nog een heel andere oppervlakte!

  | OUD | NIEUW | STATBEL kad | DOWNLOAD 2019 attribuut | DOWNLOAD 2019 BEREKEND in ArcMap | DOWNLOAD 2020 attribuut
-- | -- | -- | -- | -- | -- | --
Antwerpen (Prov.) | 286739 | 287617 | 287612 | 287612 | 287617 | 287612
Brussels Hoofdstedelijk Gewest | 16138 | 16242 | 16242 | 16242 | 16242 | 16242
Limburg | 242214 | 242745 | 242742 | 242741 | 242745 | 242741
Oost-Vlaanderen | 298224 | 300712 | 300706 | 300707 | 300712 | 300706
Vlaams-Brabant | 210615 | 211838 | 211836 | 211834 | 211838 | 211835
West-Vlaanderen | 314434 | 319662 | 319658 | 319657 | 319662 | 319657

Met andere woorden, _it's a right mess_.
Misschien kunnen we maar beter géén uitspraken doen over _de ultieme oppervlakte_ van gebieden. In de plaats werken we met een oppervlakte per verwerkingstype:
- voor alles wat we zelf in GIS verwerken, gebruiken we steeds dezelfde versie van de statsec. Dus daar kunnen we alles zelf berekenen
- voor datareeksen die van elders komen en waar er met een oppervlakte gewerkt wordt, halen we gewoon de oppervlakte daar mee af

**Comment by joostschouppe** [comment]
Data van de oude gemeenten gedelete.
Vraag i.v.m. gekke verschillen in oppervlakte gesteld aan een GIS'er

**Comment by joostschouppe** [comment]
Todo:
* wegwerken dubbele reeks oppervlaktes die nu hetzelfde bevatten
* afspraak maken: gebruik "onze geografische oppervlakte" tenzij je zelf liever bij de externe bron hun oppervlakte meeneemt

**Comment by joostschouppe** [comment]
## Metadata eerste stap

De oppervlakte is gebaseerd op de statistische sectoren 2020, zoals die van op statbel gedownload kunnen worden (https://statbel.fgov.be/nl/open-data/statistische-sectoren-2020). Deze zijn geprojecteerd in Lambert72. We berekenen de oppervlakte van de sectoren zelf in ArcMap in vierkante meter met twee cijfers na de komma.

Deze oppervlakten kunnen licht afwijken van andere verwerkingsmethoden. De huidige verwerking zorgt ervoor dat eigen verwerkingen van oppervlaktes in GIS volgens dezelfde methode verwerkt zijn. Wanneer externe bronnen een andere methode kiezen om oppervlaktes te berekenen, dan gebruiken we daar ook hun gepubliceerde totale oppervlakte als noemer. Dit impliceert dat wie zelf percentages berekent op basis van cijfers uit verschillende bronnen, kleine verschillen zal kunnen vaststellen met wat in de Databank verschijnt.

## Aanpassing indicatoren

Was | Name | Wordt
-- | -- | --
v9900_oppervl | oppervlakte (in m²) | v9900_opp_m2
v9900_opp | oppervlakte (in km²) | v9900_opp_km2
v9900_opp_ha | oppervlakte (in ha) | v9900_opp_ha
v9900_statsec_oppervl_m2 | oppervlakte (in m²) | v9900_opp_m2
v9900_statsec_oppervl | oppervlakte (in ha) | v9900_opp_ha
v9900_statsec_oppervl_km2 | oppervlakte (in km²) | v9900_opp_km2

## Verder verloop
* aanapssingen in Swing Studio: [aanpassing oppervlakte.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/7686557/aanpassing.oppervlakte.xlsx) (twee tabbladen in volgorde)
* dan aanpassingen in themaboom
* dubbelcheck in rapporten (geen impact verwacht)
* aanpassen metadata / aanmaak fiche
* script en uploadfile pushen naar github gebiedsniveaus

**Comment by joostschouppe** [comment]
Ook gelinked aan https://github.com/provinciesincijfers/PinC-taakopvolging/issues/174
