### ISSUE TITLE
Brandweercijfers

### ISSUE THREAD

**Issue by Lievendr** [provinciesincijfers/PinC-taakopvolging#154]
Naar aanleiding van Dashboard Stad Antwerpen zijn centrumsteden geïnteresseerd om Brandweercijfers te publiceren via connector. (Ook Stad Genk zou cijfers hebben...)
Eerste vergadering werd nagegaan of en waar er cijfers te vinden zijn. Er zou sinds vorig jaar een Netwerk Databeheer Brandweer zijn? daarnaast werd de vraag naar mij gesteld of we die cijfers dan via Connector willen publiceren op Swing? Ik heb geantwoord dat als die dat gebiedsdekkend zijn dit kan, maar dat ik dit nog dien voor te leggen op Redactieraad (of IPWG?)

**Comment by joostschouppe** [comment]
* kan indien gebiedsdekkend & beschikbaar  gemeenteniveau
* kan via ons als puur "doorsluisluik" als de centrumsteden het harde werk doen
* wij zetten details enkel INTERN
* wij zijn misschien wel geïnteresseerd in kerncijfers en cijfers relevant voor klimaat-adaptie (heidebranden, ondergelopen kelders)

**Comment by Lievendr** [comment]
Er wordt vrij veel verzameld via het Netwerk Brandweer. (uur van oproep, welke interventie, welke middelen, welke kosten,...) 
(Dit netwerk zijn concreet 2 collega's van Joris Voets (kenniscentrum Vlaamse steden)). 
Maar op deze data dienen nog wel wat bewerkingen rond te gebeuren.  Zo wordt de postcode van interventie genoteerd binnen de brandweerzone zodat de gemeente eruit gehaald kan worden...
Naast bewerkingen moet er vooral ook nog afgestemd worden met het Netwerk Brandweer, omdat die zelf nog maar pas sinds 1 jaar bestaan en nu een beetje de kaas van hun brood dreigen gegeten te worden, als wij met hun dashboard zouden afkomen terwijl zij niks hebben...Joris gaat met die 2 collega's samenzitten om te zien wat mogelijk is.
Daarna gaat Joris Voets dit alles agenderen op de volgende OBMI om verder uit te klaren hoe ze verder willen gaan. @dgees
Ikzelf heb het standpunt van de provincies meegedeeld waar ze allen begrip voor hadden (zie bedenkingen hierboven via Joost)  
Aanwezig: Joris Voets (kenniscentrum), Isabelle Vanderheyden (Genk), Jerry Ruys (Antwerpen) Annelies Van Steenberge (Gent)
