### ISSUE TITLE
veiligheidsrapport

### ISSUE THREAD

**Issue by Lievendr** [provinciesincijfers/PinC-taakopvolging#155]
criminaliteitscijfers blijken na controle van veiligheidsrapport erg verwarrend te zijn. Onderscheid tussen strafrechtelijke inbreuken en criminele figuren is in boomstructuur door elkaar gehaald en ook in rapport verkeerdelijk naast elkaar gezet. Afgesproken met Ine dat er 2 metadatafiche worden aangemaakt (strafrechtelijke vs criminele figuren) en dat rapport herwerkt gaat worden door eerst de strafrechtelijke cijfers te bespreken en vervolgens de criminele figuren.

Concreet zou mijns inziens rapport moeten verwijderd worden en ook de cijfers (gedeeltelijk) verwijderen. (Bij strafrechtelijke cijfers ontbreken een aantal gegevens...de link met detail (criminele figuren) klopt niet...

**Comment by joostschouppe** [comment]
Dit probleem was wel ongeveer opgepikt tijdens controle en nazicht metadata. Bij het nalezen van het rapport hebben we dit over het hoofd gezien. Rapport wordt herwerkt, themaboom heringedeeld, dashboard was al OK.

**Comment by Inejacobs** [comment]
Rapport Veiligheid is herwerkt en is bezorgd aan Lieven en Chris. Na feedback kan David de aanpassingen doorvoeren. Er is in de herwerkte versie een duidelijke opsplitsing gemaakt tussen strafrechtelijke inbreuken enerzijds en criminele figuren anderzijds. In de tekst staan sommige delen ook bold om dit verschil nogmaals te benadrukken.

**Comment by joostschouppe** [comment]
@Lievendr @ChrisMichelDS : hebben jullie Ine/David al feedback bezorgd?

**Comment by Lievendr** [comment]
Ja, hebben we beiden gedaan; in overleg. Ine ging rekening houden met onze bedenkingen. eindresultaat wel nog niet gezien.

**Comment by Inejacobs** [comment]
Rapport was opnieuw geprogrammeerd doch met nog enkele fouten. Ik heb dit doorgegeven aan David. Sinds eind vorige week is het rapport klaar. 1 bemerking is wel niet opgelost: Bij het selecteren van 2 provincies blijft in de 2e paragraaf, eerste regel onder 1.1 het woord 'gemeente' staan, terwijl we 2 prov vergelijken. Ik weet niet of dit kan dynamisch gemaakt worden.

**Comment by davidcardinaels** [comment]
Die bemerking is wel opgelost.

**Comment by Inejacobs** [comment]
![image](https://user-images.githubusercontent.com/57390456/98554393-f1192200-22a0-11eb-8487-60185ee9bf67.png)

Ik zie nog steeds 'gemeente' staan als ik 2 provincies selecteer in de JIVE? Maar misschien ligt het aan mijn PC?..

**Comment by joostschouppe** [comment]
@Inejacobs , heb je wel in de admin/jive versie gekeken? Enkel daar zijn correcties onmiddellijk zichtbaar, zie https://provincies.incijfers.be/admin/jive/report/?id=rapport_veiligheid&input_geo=provincie_70000 waar dit probleem toch verholpen is volgens mij

@davidcardinaels volg jij deze https://github.com/provinciesincijfers/PinC-taakopvolging/issues/155#issuecomment-709370728 in omgekeerde zin om het rapport te ont-ont-publiceren? Indien nodig gee je onderdeeltjes maar door.

**Comment by Inejacobs** [comment]
Ja, het was voor mij later op die dag zichtbaar (vertraging?). In orde dus!

**Comment by davidcardinaels** [comment]
Ik heb het rapport overal opnieuw toegevoegd.

@KoenSnyers kan jij het rapport nog toevoegen aan dashboard?
