### ISSUE TITLE
Dashboard policy - rol van projectgroepen

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#157]
Zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/95#issuecomment-690912006 : "harmonistatie afgerond, check zeker voor je eigen tegels". Deze vraag is niet doorgestroomd naar de projectgroepen. 

Concrete vraag van Landbouw nadat ze de aanpassingen ontdekten:
- Aantal dieren moet terug opgesplitst worden in drie aparte grafieken (koeien, varkens, runderen) omdat de aantallen sterk kunnen verschillen. Vroeger stond er een evolutie (2008-2018) per diersoort. Kan er nu eventueel voor een grafiek gekozen worden die het huidige aantal en dat van 10 jaar geleden aangeeft (nu dus 2008 en 2018)? Ik weet niet precies welke standaard er nu is, maar het zou kunnen dat hiervoor dan geopteerd wordt.
- Aantal biobedrijven, hoeveproducenten en zorgboerderijen: liefst apart houden van elkaar, aangezien ze niet met elkaar zijn verbonden (drie kleine grafiekjes?) en zo mogelijk terug een vergelijking met de provincie.

Algemene vraag: 
- hoe zorgen we dat de vraag zoals via comment hierboven gesteld goed doorstroomt naar iedereen?
- moeten we explicteren wat de rol van projectgroep-verantwoordelijken (aan kant d&a en inhoudelijke groep) is?

**Comment by joostschouppe** [comment]
Aanpassing procedure Dashboard: "De eindredacteur stuurt een persoonlijk bericht naar de tegel-verantwoordelijke bij elke signifcante aanpassing"
Koen en Tine stemmen verder af in verband met de tegel van Landbouw

**Comment by KoenSnyers** [comment]
@Tine-VB 
Wat de aanpassingen in het dashboard landbouw betreft:

- ik voegde de onderdelen legkippen & slachtkuikens, runderen en varkens samen in één grafiek omdat ik drie grafieken hiervoor in het licht van de harmonisatie van het dashboard overkill vond; misschien is het wel beter als ik er drie horizontale staven naast elkaar van maak, dus stel ik voor om dat te doen.
- één cijfertje voor het aantal biologische landbouwbedrijven, hoeveproducenten en zorgboerderijen (wat samen biologische landbouw en verbreding is) telkens in een apart grafiekje opnemen, lijkt me weinig zinvol; ook heeft het weinig zin om het aantal (absoluut cijfer) van de gemeente in de vorm van een grafiek (met staven naast elkaar) te vergelijken met het aantal in de provincie; dat heeft alleen maar zin als ik er drie aparte tegels van maak zoals de eerste tegel op het dashboard bevolking (die alleen maar cijfers weergeeft).

@joostschouppe 
Ik heb bij de harmonisatie van het dashboard de themaverantwoordelijken niet expliciet op de hoogte gebracht, omdat de harmonisatie een opdracht was vanuit de redactiegroep en er sowieso aan de vijf procincies zou gevraagd worden om alles nog eens te checken.
Als er in de toekomst aan themadashboards aanpassingen gedaan worden of moeten gebeuren, zal ik de themavrantwoordelijke zeker wel betrekken.

**Comment by KoenSnyers** [comment]
@joostschouppe @Tine-VB 

Thema landbouw is aangepast na overleg met Jona en Tine.
Bij volgende inhoudelijke aanpassingen door mezelf als eindredacteur zal ik steeds terugkoppelen naar de themaverantwoordelijke vanuit Data & Analyse. Indien nodig, zullen de aanpassingen gebeuren in overleg met de inhoudelijke projectgroep.
