### ISSUE TITLE
Vervolledigen uitdovende onderwerpen

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#158]
In dit bestand aanduiden wat er moet gebeuren (tabblad indicators):  https://docs.google.com/spreadsheets/d/1YQKLJNHwgEyjLBdPdHrPtouddWs9GLsa9s6KCHMSvSA/edit?usp=sharing 
- nog uitdovend laten of uitgedoofd maken (kolom H);
- datum sinds wanneer het uitdovend is toevoegen (kolom I);

Ter info: alles rond policy in één bestand gezet: https://github.com/provinciesincijfers/JiveDocumentation/blob/master/levensloop_onderwerpen.md

**Comment by StefanJacques** [comment]
Wat doen we met steekkaart_demografie, ook uitdovend (en volgens mij extern in provincies.incijfers niet meer te raadplegen..

**Comment by joostschouppe** [comment]
@SofieWVl @ChrisMichelDS zorgen jullie dat dit ingevuld geraakt tegen de volgende redactiegroep?

**Comment by StefanieWVL** [comment]
WVL OK
