### ISSUE TITLE
Buurtgerichte zorg - een nieuw type rapport?

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#160]
Al onze _rapporten_ en _cijfers opgelijst_ gaan **over** hun naam. Het rapport economie geeft economische cijfers, detailhandel gaat over detailhandel, wonen over wonen, ouderenzorg over ouderenzorg.
 
Je zou dus kunnen verwachten dat het rapport buurtgerichte zorg **over** buurtgerichte zorg gaat. Maar dat klopt niet: eigenlijk is het een omgevingsanalyse **voor** mensen die rond buurtgerichte zorg werken. 
(bij ouderenzorg is het een beetje van de twee; daar heb je vooral cijfers over die zorg, maar ook een beetje omgevingsanalyse)
 
Mij lijkt het misschien niet slecht om dat onderscheid in de naamgeving direct duidelijk te maken; dus bijvoorbeeld Rapport voor Buurgerichte zorg, of Omgevingsanalyse buurtgerichte zorg. Ik legde dit reeds voor aan @KoenSnyers en @HildeC en zij leken enthousiast over **Omgevingsanalyse buurtgerichte zorg**

**Comment by VickyVB** [comment]
Ik ben enthousiast over rapport voor buur**t**gerichte zorg.

**Comment by dgees** [comment]
Als het eigenlijk dient voor een omgevingsanalyse, komen we dan niet terug op de 'kerncijfers' discussie? Is het dan het rapport kerncijfers voor buurtgerichte zorg?

**Comment by StefanieWVL** [comment]
Ik kan je hierin volgen Joost en als we, zoals Tine zegt, het woord rapport moeten gebruiken als het om een rapport gaat, dan komen we bij Vicky's voorkeur uit: Rapport voor Buurtgerichte Zorg (smiley)

**Comment by Lievendr** [comment]
semantische discussies...i love it. Het is een rapport, want je klikt op rapporten. en het gaat over buurtgerichte zorg. Dus hou het simpel en noem het Buurtgerichte zorg. Prachtig werk trouwens,

**Comment by demaesschalckfilip** [comment]
Ik ben het ook eens met Joost: rapport wonen gaat over wonen, rapport onderwijs gaat over onderwijs, maar rapport buurtgerichte zorg gaat (als enige) niet over buurtgerichte zorg, maar is bedoeld voor buurtgerichte zorg. Dus wordt het: rapport **voor** buurtgerichte zorg. Dat lijkt me eigenlijk bijzonder logisch (of rapport kerncijfers voor buurtgerichte zorg, dat kan natuurlijk ook)

**Comment by Lievendr** [comment]
los van discussie: samenvattende grafiek voor Antwerpen draait in de soep. wellicht te veel sectoren...

**Comment by joostschouppe** [comment]
> Het is een rapport, want je klikt op rapporten

Uiteraard zijn het ook rapporten, maar het zijn geen Rapporten! Want anders zouden Steekkaarten en "cijfers opgelijst" ook Rapporten zijn.

**Comment by Lievendr** [comment]
ook steden zoals Gent is samenvatting een probleem door teveel aan info. alle taarten vallen op elkaar.

**Comment by KoenSnyers** [comment]
Dankjewel voor deze semantische discussie, collega's.
Hierna lijkt dit mij uiteindelijk de meest relevante naam voor dit rapport:
"Rapport kerncijfers voor buurtgerichte zorg".

Akkoord, @HildeC en @joostschouppe?

Wat de problemen met de stad Antwerpen en Gent betreft (samenvattende grafiek die in de soep loopt), dankjewel om dit op te merken, @Lievendr.
Hoe losse we dit op, @HildeC, @davidcardinaels en @joostschouppe?

**Comment by davidcardinaels** [comment]
Als tijdelijke oplossing heb ik de samenvattende grafiek voor Antwerpen en Gent vervangen door een melding.

**Comment by KoenSnyers** [comment]
> 
> 
> Als tijdelijke oplossing heb ik de samenvattende grafiek voor Antwerpen en Gent vervangen door een melding.

Bedankt, David.

**Comment by davidcardinaels** [comment]
Naast de melding komt er nu ook een grafiek op deelgemeenteniveau. Is iedereen akkoord met deze oplossing?

**Comment by KoenSnyers** [comment]
> 
> 
> Naast de melding komt er nu ook een grafiek op deelgemeenteniveau. Is iedereen akkoord met deze oplossing?



> 
> 
> Naast de melding komt er nu ook een grafiek op deelgemeenteniveau. Is iedereen akkoord met deze oplossing?

Voor mij is dit prima, @davidcardinaels ...

**Comment by KoenSnyers** [comment]
> 
> 
> Dankjewel voor deze semantische discussie, collega's.
> Hierna lijkt dit mij uiteindelijk de meest relevante naam voor dit rapport:
> "Rapport kerncijfers voor buurtgerichte zorg".
> 
> Akkoord, @HildeC en @joostschouppe?
> 
> Wat de problemen met de stad Antwerpen en Gent betreft (samenvattende grafiek die in de soep loopt), dankjewel om dit op te merken, @Lievendr.
> Hoe losse we dit op, @HildeC, @davidcardinaels en @joostschouppe?

Hallo @HildeC en @joostschouppe,

Kunnen we de knoop doorhakken over de rapportnaam die ik voorstelde na de semantische discussie erover hier?
Mijn voorkeur gaat uit naar 'Rapport kerncijfers voor buurtgerichte zorg'.
Graag jullie fiat, dan kan @davidcardinaels dat in het rapport en op alle plaatsen in PinC aanpassen. Ik heb het al aangepast in die zin in limburg.incijfers.be.
Ik wacht hierop om een mail naar alle Limburgse lokale besturen te sturen over het rapport ...

(ter info aan @karolienbloemen)

**Comment by davidcardinaels** [comment]
Ik ging ervan uit dat het voorstel van Koen het wel zou halen, dus ik heb de titel overal al aangepast naar 'Rapport kerncijfers voor buurtgerichte zorg'.

**Comment by KoenSnyers** [comment]
> 
> 
> Ik ging ervan uit dat het voorstel van Koen het wel zou halen, dus ik heb de titel overal al aangepast naar 'Rapport kerncijfers voor buurtgerichte zorg'.

Voor mij is dat helemaal prima! Bedankt.

**Comment by joostschouppe** [comment]
Akkoord met beide oplossingen
