### ISSUE TITLE
buurtgerichte zorg - en de keuze voor samenvattende taartkaart

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#162]
Er is nog discussie over de meerwaarde van MapBenchmarkPie

We verkennen de mogelijkheden via:
https://provincies.incijfers.be/admin/jive/Report?id=rapport_bgz_samenvattendegrafiek&openinputs=true

Vragen bij ABF - lay-out issues:
- kan je de centrale kleur laten vallen > neen
- kan je de overlap van taarten verminderen > niet echt
- interactieve versie lay out gaat in de knoop
- "tussenschotten" vallen weg

**Comment by Tine-VB** [comment]
Argument PRO: geeft visueel in één oogopslag weer waar de zwaartepunten over alle indicatoren heen liggen. 
Argumenten TEGEN:
* er wordt geen weging toegepast op de indicatoren, terwijl sommige indicatoren voor een thema zwaarder doorwegen dan andere. Je kan ze eigenlijk enkel gebruiken als alle indicatoren binnen een thema min of meer ‘gelijkwaardig’ zijn, maar hoe vaak komt dat voor en hoe bepaal je dat?
* voor de inkleuring van de middelste bol is de keuze van de indicatoren en een eventuele weging ten opzichte van elkaar nog belangrijker. In de legende staat dat de middelste bol een ‘inkleuring over de verschillende indicatoren heen’ geeft. Hoe dat juist wordt bepaald wordt niet aangegeven. 
* de interpretatie is niet zo eenvoudig, omdat een taartdiagram normaal gezien het aandeel weergeeft dat de verschillende categorieën hebben ten opzichte van het geheel, terwijl hier elk ‘stukje’ van de taart even groot is maar je moet kijken naar de kleurtjes voor interpretatie. 
* de kaart is vaak nogal onoverzichtelijk, zeker als er veel ruimtelijke eenheden zijn, taarten overlappen
* je moet al erg goed kijken om precies te zien welke indicator welke kleur heeft gekregen als je meer in detail naar een buurt wilt kijken (zeker als er 12 indicatoren worden gebruikt zoals bij Rapport BGZ)

**Comment by HildeC** [comment]
samenvatting van de bespreking met collega's:

op zich is een samenvatting op het eind van een rapport een goede zaak. laat toe om in 1 oogopslag de wijken te vergelijken.
we hebben wel een aantal verbetervoorstellen
de bol in het midden van de diagram moet weg. dit suggereert een samenvattende maat/indicator, terwijl er geen info is over hoe die samenvattende maat berekend wordt, en de vraag stelt of dit statistisch correct is?
lijntjes op de diagram zouden een betere aanduiding geven over welke indicator het gaat.

**Comment by joostschouppe** [comment]
Enkele oplossingen aangevuld in https://provincies.incijfers.be/admin/jive/Report?id=rapport_bgz_samenvattendegrafiek&openinputs=true
Helaas vrij veel technische issues.
Voorlopig is het niét mogelijk om de centrale bol te laten vallen.

**Comment by KoenSnyers** [comment]
Ik zet graag even wat inhoudelijke en methodologische informatie bij de profieltaarten op een rij ...

1
De twaalf indicatoren zijn geselecteerd omdat ze iets zeggen over maatschappelijke kwetsbaarheid, omdat ze in dezelfde richting te interpreteren zijn (des te hoger de score van de indicator, des te meer indicatie van maatschappelijke kwetsbaarheid) en omdat ze op wijkniveau beschikbaar zijn in de databank.
Idealiter breng je maatschappelijke kwetsbaarheid in kaart zoals ik dat in Limburg deed in ons cijferdossier armoede, waarin ik armoede bekijk als maatschappelijke kwetsbaarheid op vijf domeinen: inkomen, arbeid, gezin, wonen en onderwijs. Per domein zijn daarin vijf indicatoren weerhouden. Hierin is er geen gewicht toegekend aan de individuele indicatoren (ze wegen allemaal even zwaar) en elk domein telt voor 5/25ste (of 1/5de) mee om de globale armoedescore te bepalen.
Zie deze link voor het cijferdossier armoede van Limburg: https://limburg.incijfers.be/dossiers/armoede.
Binnen het bestek van het rapport buurtgerichte zorg zijn we niet in de mogelijkheid om zo gedetailleerd en evenwichtig te gaan qua indicatoren over verschillende domeinen heen, gewoon omdat heel wat indicatoren niet op een lager dan gemeentelijk niveau beschikbaar zijn. Of er een weging moet zijn om het verhaal te objectiveren, kan makkelijk weerlegd worden door te zeggen: eender welke weging je hanteert, is subjectief ...
Doel is vooral om op basis van twaalf beschikbare indicatoren te kunnen zien in welke wijken de maatschappelijke kwetsbaarheid vergeleken met de gemeente het hoogst is. Dat is iets dat voor een gemeente heel handig en waardevol is, naast de gedetailleerde informatie voor alle indicatoren apart uiteraard.
Meer evenwicht trachten te bereiken door de drie deelindicatoren van werkloosheid eruit te laten, daar is iets voor te zeggen, al laat je net de meest kwetsbare groepen werkzoekenden buiten beschouwing als je alleen maar het globale percentage werkzoekenden overhoudt.

2
Alle indicatoren zijn omgezet in z-scores. Dat wil zeggen dat ze gestandaardiseerd zijn. Dat heeft als voordeel dat ze statistisch gezien onderling met elkaar te vergelijken zijn, wat dan weer een voorwaarde is om ze in een synthesemaat te kunnen opnemen. De middelste bol is een gemiddelde standaardscore, berekend als niet-gewogen gemiddelde van de standaardscores van de twaalf indicatoren (of van de indicatoren waarvoor cijfers beschikbaar zijn in elke wijk). Deze werkwijze is statistisch gezien dus helemaal correct. In de toelichting staat bovendien vermeld dat de middelste bol minder relevant is voor de wijken waar er voor weinig indicatoren cijfers beschikbaar zijn (omwille van te lage aantallen).

Mijn voorstel:
Behoud van de profieltaarten (uit mijn contact met samenlevingsopbouw blijkt dat gemeenten dat echt een meerwaarde vinden), eventueel met minder indicatoren (hoewel, dan laat je de meest kwetsbare werkzoekenden buiten beschouwing), plus eventueel met verduidelijking van de methodologie erbij (zie mijn puntje 2).
Zeker niet kiezen voor de kaart met staafjesgrafiek, want dan ga je (omdat je percentage van verschillende indicatoren naast elkaar zet) statistisch gezien appelen met peren vergelijken en kan je uit de kaart niks afleiden over in welke wijken de maatschappelijke kwetsbaarheid het hoogst is.

**Comment by joostschouppe** [comment]
@KoenSnyers : hier mis je een fundamenteel bezwaar van sommige mensen:

>  De middelste bol is een gemiddelde standaardscore, berekend als niet-gewogen gemiddelde van de standaardscores van de twaalf indicatoren (of van de indicatoren waarvoor cijfers beschikbaar zijn in elke wijk). Deze werkwijze is statistisch gezien dus helemaal correct. 

Inhoudelijk zeg je daarmee dat elk van de indicatoren exact hetzelfde belang heeft in het eindresultaat, hier dus een soort van kwetsbaarheidsmaat. Maar dat is niet noodzakelijk het geval. Eigenlijk moet je ofwel aantonen dat het hier geen zin heeft om met gewichten te werken, of moet je een onderbouwde methodologie hebben om te beslissen hoeveel gewicht elk van de onderdelen heeft.

**Comment by KoenSnyers** [comment]
@joostschouppe; @karolienbloemen  

Ok, om te beginnen dit. Ik doe niet graag mee aan een opbod van argumenten pro en contra zonder dat er op tafel komt wat de onderliggende gevoelens, behoeften en wensen zijn van de persoon die heel veel argumenten contra op tafel ligt. Ik discussieer niet graag op basis van argumenten alleen, veel belangrijker is om te weten wat de onderliggende gevoelens, behoeften en wensen zijn. Hier even op een rij wat voor mij feiten, gevoelens, behoeften en wensen zijn.
De feiten: vanuit Limburg en vanuit West-Vlaanderen, als inhoudelijke makers van dit rapport, was deze profieltaart relevant genoeg om op te nemen; bij de feedback die er op het rapport kwam, is er maar van één persoon inhoudelijke kritiek op de profieltaart gekomen; Hilde en ik zijn zo vrij geweest om die als eindredacteurs van het rapport naast ons neer te leggen.
Mijn gevoel bij dit gebeuren: het voelt niet fijn dat dit nu opnieuw op tafel komt, nadat het rapport finaal goedgekeurd werd voor publicatie; als projecten toegewezen worden aan twee trekkende provincies om ze uit te voeren, dan ligt de eindverantwoordelijkheid voor het doorvoeren van aanpassingen bij die twee provincies; als er dan maar één provincie bezwaren heeft bij een wezenlijk onderdeel ervan, voelt het aan als omzeilen van de manier van werken om projecten met vijf provincies samen tot een goed einde te brengen, wanneer dit achteraf opnieuw op tafel komt.
Mijn behoefte rond de werking aan projecten in het algemeen: dat trekkende provincies effectief de eindverantwoordelijkheid krijgen om, nadat er feedback komt op een product, al dan niet aanpassingen te doen, rekening houdend met hoeveel provincies ergens bezwaren tegen hebben, zonder dat daar achteraf op teruggekomen hoeft te worden.
Mijn wens wat de profieltaarten betreft: behoud van de profieltaarten (uit mijn contact met samenlevingsopbouw blijkt dat gemeenten dat echt een meerwaarde vinden), eventueel met minder indicatoren (hoewel, dan laat je de meest kwetsbare werkzoekenden buiten beschouwing), plus eventueel met verduidelijking van de methodologie erbij (zie mijn puntje 2 uit mijn vorige reactie); en weet je, als de profieltaart eruit moet, dan zou ik dat heel jammer vinden en een gemiste kans om gemeenten in één opslag aan te reiken in welke wijken er de hoogste graad van maatschappelijke kwetsbaarheid is, binnen de methodologische beperkingen die er zijn; vanuit Limburg zal ik in elk geval dankbaar gebruik blijven maken van de profieltaart om synthesematen voor bepaalde domeinen in kaart te brengen in onze zeer gesmaakte cijferdossiers. 

Ik kom graag nog even terug op jouw vraag naar argumentatie rond het wegen van de indicatoren of niet. Ik antwoord met wedervragen.
Wat is te verkiezen: elke indicator even zwaar laten wegen en dus als aanname hanteren dat elke indicator min of meer een even grote kans op maatschappelijke kwetsbaarheid met zich meebrengt OFWEL op basis van een 'onderbouwde methodologie' gaan bepalen dat de ene indicator zwaarder weegt in functie van kwetsbaarheid dan een andere? 
Indien je zou kiezen voor een 'onderbouwde methodologie', voor welke soort weging ga je dan kiezen? Ga je kiezen voor weging op basis van het aantal mensen dat scoort op elke indicator in heel Vlaanderen? Dat is een mogelijkheid, maar het is niet omdat er minder leefloners zijn dan er werkzoekenden zijn dat je kan zeggen dat wie een leefloon krijgt, minder kwetsbaar is dan wie werkzoekend is, zelfs integendeel. Een andere mogelijkheid is dat je zelf een inschatting gaat maken van wat zwaarder en minder zwaar wegende factoren zijn en op basis daarvan een wegingsfactor gaat toekennen aan elke indicator. Is dat beter dan? Houdt dit niet evenzeer een aanname in die zowaar nog subjectiever is dan wanneer je ervoor kiest dat elke indicator even zwaar weegt?

Enfin, ik laat het hierbij en wens de redactiegroep er morgen alle succes mee om de knoop door te hakken.

**Comment by Tine-VB** [comment]
Wel, dan kan ik hier even de bal terug kaatsen bij dit stukje: _Mijn gevoel bij dit gebeuren: het voelt niet fijn dat dit nu opnieuw op tafel komt, nadat het rapport finaal goedgekeurd werd voor publicatie; als projecten toegewezen worden aan twee trekkende provincies om ze uit te voeren, dan ligt de eindverantwoordelijkheid voor het doorvoeren van aanpassingen bij die twee provincies; als er dan maar één provincie bezwaren heeft bij een wezenlijk onderdeel ervan, voelt het aan als omzeilen van de manier van werken om projecten met vijf provincies samen tot een goed einde te brengen, wanneer dit achteraf opnieuw op tafel komt._
De vraag om dit grafiektype aan te kopen bij ABF is reeds eerder interprovinciaal besproken, en ik (samen met enkele andere mensen van onze provincie en andere provincies) heb toen reeds duidelijk gezegd dat ik dit geen goede voorstellingswijze vind. Bij mijn weten is er toen besloten dat we dus deze grafiek niet zouden aankopen en niet zouden toepassen. Ik heb er dus ook geen goed gevoel bij dat deze grafiek nu opeens toch verschijnt in een rapport, en dat deze hele discussie nu opnieuw op tafel komt. De afspraak die hierover gemaakt werd, wordt hier niet enkel omzeild, maar gewoon genegeerd. 
Om verder enkele puntjes op de i te zetten: het gaat hier niet om de mening van 1 persoon van 1 provincie. Ik heb de reactie hierboven geschreven na bespreking intern, en dus namens de medewerkers van onze provincie. Tijdens de discussie die we eerder over deze grafiek hadden, stond ik niet alleen. Dat andere mensen niet opgemerkt hebben dat deze grafiek toch gebruikt werd, daar kan ik niets aan doen. Ik heb de opmerking meteen meegegeven, voor publicatie van het rapport. Achteraf hebben dan enkele mensen opgemerkt dat we deze grafiek eigenlijk niet mogen gebruiken, omdat ze niet inbegrepen is in onze licentie.
Verder heb ik hier helemaal geen nood aan het uiten van wensen en gevoelens, ik werk liever met duidelijke argumenten. 
Als besloten wordt om, ondanks eerdere afspraken, toch dit grafiektype te gaan gebruiken, dan zou ik voor dit rapport zeker de indicatoren over kwetsbare werklozen (waar als noemer de werklozen gebruikt wordt), verwijderen. Deze kunnen een heel vertekend beeld geven in gemeenten met weinig werklozen bijvoorbeeld. En het verwijderen van enkele indicatoren kan zeker geen kwaad om de leesbaarheid van de kaart te vergroten. En je vermijd hier ook dat werklozen een heel grote rol spelen in de samengestelde kleur van de middelste bol. Want los van de vraag of je moet wegen of niet: door de keuze van je indicatoren maak je sowieso een (ongegronde) weging voor de inkleuring van deze.

**Comment by KoenSnyers** [comment]
@Tine-VB @karolienbloemen 

Dankjewel dat je je gevoelens, behoeften en wensen hier duidelijk benoemt. Er is immers zoveel meer dan feiten, meningen en argumenten, die al te vaak verdoezelen wat de onderliggende gevoelens, behoeften en wensen zijn. Je kan bij tegengestelde meningen blijven kijken naar argumenten van beide partijen, maar pas als je weet wat de behoeften en wensen van beide partijen zijn, kan je kijken hoe die met elkaar verzoend kunnen worden tot iets dat voor alle partijen goed voelt. Dus, ik heb geleerd om mijn eigen gevoelens, behoeften en wensen steeds meer in te brengen en te polsen naar die van de ander, om tot iets te komen waar beiden zich kunnen in vinden. En dat zal ik blijven doen, in alle omstandigheden.

In elk geval, je verhaal maakt duidelijk dat onze behoeften in feite gelijklopend zijn: met name dat er niet teruggekomen wordt op eerder gemaakte afspraken. Alleen gaat het er jou vooral om dat we gebruik maken van een grafiektype dat jullie niet zien zitten en dat niet voor de vijf provincies werd aangekocht. Voor mij gaat het erom dat een rapport goedgekeurd wordt en dat daar achteraf op teruggekomen wordt.

Ik geef toe, ik ben, toen ik deze samenvattende grafiek aanmaakte, uit het oog verloren dat dat type in feite niet gebruikt mocht of kon worden in een product voor de vijf provincies. Maar niemand heeft daar op dat moment iets over gezegd ... Ook in die feedback die er kwam voor het rapport online kwam, is dat niet ter sprake gekomen.

Maar goed, blijft het gegeven dat er weerstand is bij jullie voor dit grafiektype. Ik kan die weerstand niet wegnemen door argumenten in te brengen, maar ik geef graag nog even mee wat de essentie is bij het gebruik van dit grafiektype:
1/ doel: een synthesemaat creëren op basis van een set van indicatoren, die samen een indicatie geven van een bepaald fenomeen (in dit geval: maatschappelijke kwetsbaarheid)
2/ een zo evenwichtig mogelijke selectie van indicatoren maken, waarbij je kiest voor weging van de indicatoren of niet (in dit geval: de 12 beschikbare indicatoren werden geselecteerd, zonder weging; omdat er hier niet, zoals in mijn Limburgs cijferdossier armoede, gewerkt kan worden met vijf indicatoren voor elk van vijf domeinen, kan ik begrijpen dat de twaalf indicatoren waarvan vier rond werkloosheid als onevenwichtig ervaren worden; dit kan opgelost worden door de drie deelindicatoren van werkloosheid weg te laten of door er twee van te weerhouden (bv. laaggeschoold en langdurig werkzoekend) en de de andere twee weg te laten)
3/ dit grafiektype vergt verder volgende manier van gebruiken: je moet gebruikmaken van indicatoren die in dezelfde richting te interpreteren zijn (of de waardering van indicatoren die omgekeerd te interpreteren zijn, in Swing omschakelen, al is dat niet mogelijk als je de indicator in een rapport gebruikt omdat hij dan de waarde ook omkeert bij los gebruik); je moet de indicatoren omzetten naar z-scores (alleen op een gestandaardiseerde manier zijn indicatoren onderling te vergelijken), zodat de bol in het midden een gemiddelde z-score weergeeft; je kan gewichten meegeven aan aparte indicatoren en/of aan subdomeinen, waardoor de bol in het midden een gewogen gemiddelde z-score weergeeft); omdat dit enige kennis van zaken vergt, stelt ABF dit grafiektype trouwens alleen maar open voor intern gebruik (een externe gebruiker kan dus niks fout doen).

Tot slot: mijn wens is dat het grafiektype behouden blijft (eventueel mits aanpassingen in indicatoren, eventuele weging geven aan subdomeinen, plus eventuele verduidelijking in de tekst), maar als er fundamenteel bezwaar is tegen de aankoop van dit grafiektype voor de vijf provincies omdat het niet als waardevol genoeg gezien wordt, zet ik die wens aan de kant. 
En zoals ik hierboven al zei: ik blijf voor limburg.incijfers.be dankbaar gebruikmaken van dit grafiektype om inzichtelijke synthesematen te creëren rond bepaalde domeinen in onze cijferdossiers. Ik nodig je van harte uit om het Limburgs cijferdossier armoede eens grondig door te nemen (https://limburg.incijfers.be/dossiers/armoede), zodat je kan zien wat er mogelijk is met dit grafiektype.

Aan de redactiegroep om de beslissing te nemen. Ik hoor het wel.

**Comment by Tine-VB** [comment]
Zelfde voor mij: ik leg me zeker neer bij de beslissing van de redactiegroep. Een belangrijke meerwaarde vind ik inderdaad dat het een synthesemaat is, en dat is waar lokale besturen / leken vaak naar vragen: in 1 oogopslag kunnen zien waar er bijvoorbeeld kwetsbaarheid/armoede is. Ik heb de mogelijkheden bekeken, ook enkele Nederlandse voorbeelden die Stefan mij had bezorgd. De voorbeelden waar er per buurt een totaalgrafiek wordt gemaakt (zonder kaart), zodat direct opvalt op welk vlak de problemen zich stellen, kan ik wel smaken. Maar ik blijf vooral de inkleuring van de middelste bol, en de moeilijkheid om daar juiste indicatoren en eventueel een weging voor te bepalen, een groot struikelblok vinden om de grafiek te gebruiken.

**Comment by joostschouppe** [comment]
Na bespreking in Redactiegroep: we hebben hier verschillende communicatieve steken laten vallen. Dit lijkt me een goede aanleiding om enkel processen nog eens te bekijken en enkele afspraken wat scherper te stellen. Wellicht iets om verder op te nemen in de werkgroep Kwaliteit en de IPWG.
In uitvoering van de originele afspraak en met een duidelijke meerderheid die niet overtuigd is van de profieltaart (in zijn huidige vorm) komen we dus terug op de latere afspraak dat dit rapport goedgekeurd was inclusief profieltaart. Het voorstel voor een alternatief is inmiddels aangemaakt in https://provincies.incijfers.be/admin/jive/report/?id=rapport_bgz_samenvattendegrafiek&openinputs=true (bovenaan het rapport) en wordt op zijn minst voorlopig zo overgenomen in het rapport. Wie bezwaren heeft, is nog steeds uitgenodigd om in rapport_bgz_samenvattendegrafiek alternatieve voorstellen klaar te zetten. In dat geval staat het je vrij dit ticket te heropenen.

De beslissing over de zin en onzin van de profieltaart is hiermee nog niet gevallen. Er zijn zeer goede argumenten zowel voor als tegen. Wellicht is het zinvol om na te denken over onder welke voorwaarden dit soort grafiek aanvaardbaar kan zijn. Dat kan gaan over methodologie ("maak een onderbouwde methode om tot een centrale bol te komen"), duiding ("leg uit dat die bol maar een hulpmiddeltje is en niet pretendeert een harde waarheid te vatten") of visualisatie ("verberg de centrale kleur", en "zorg ervoor dat bollen minder vaak overlappen"). Wie dit wil doen kan hierover een nieuw ticket openen.
