### ISSUE TITLE
Uitdovende rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#163]
Wat doen we met steekkaart_demografie, ook uitdovend (en volgens mij extern in provincies.incijfers niet meer te raadplegen)?

_Originally posted by @StefanJacques in https://github.com/provinciesincijfers/PinC-taakopvolging/issues/158#issuecomment-712101835_

Voorstel:
Inhoud vervangen door doorverwijzing naar opvolger. Non-actie leidt tot rapporten die "kapot getoond" kunnen worden (zeldzaam, maar kan wel).
Is het in die gevallen nodig om een backup te nemen? Zo ja, waar? (wetende dat er nu al veel te veel rommel in de rapportenbak zit)

Niet enkel _steekkaart_demografie_, maar bijvoorbeeld ook _kansarmoede_

Naar analogie met rapport_detailhandel_2019

**Comment by joostschouppe** [comment]
Verder uit te werken en uit te schrijven in Draaiboek rapporten.
-    eerst inhoud wissen en doorverwijzen > maar wel op zo'n manier dat externe links blijven werken
-    verwijzingen in themaboom, andere rapporten en dashboards, kiezen op kaart, gebiedsinfo >>> aanvullen in draaiboek rapporten, omgekeerde van checklist publicatie

**Comment by Emilien-Dupont** [comment]
Procedure voor het verwijderen van rapporten is uitgewerkt in het [Draaiboek rapporten](https://github.com/provinciesincijfers/JiveDocumentation/blob/master/07.%20Rapporten/Draaiboek-rapporten.md).
