### ISSUE TITLE
Goedkeuring dashboard Ruimte

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#164]

**Comment by StefanJacques** [comment]
testversie: https://provincies.incijfers.be/dashadmin/preview/dashboard/ruimte

**Comment by Lievendr** [comment]
Suggestie: vraag is of door opsplitsing open ruimte - ruimtebeslag te behouden in Figuur 2 en 3 iedereen doorheeft dat de verschillende categorieën (%bos, % braak,... enerzijds) en (% tuinen&huizen, %transport,...anderzijds) de totale oppervlakte inhouden? M.a.w. waarom geen 1 Figuur (taart gemeente vs taart provincie) met alle categorieën; met eventueel in de titel "de categorieën Open ruimte én Ruimtebeslag"?

**Comment by joostschouppe** [comment]
-Detailopmerking: ik zou volgorde akkerland, grasland, bos, ... aanhouden ipv akkerland, bos, grasland, aangezien het erop lijkt (de metadata is niet zo erg duidelijk op dat vlak) dat ze met grasland landbouwgrond met gras bedoelen (doorgaans weide). Bos zit wat vreemd tussen twee types landbouw
-de splitsing tussen open ruimte en ruimtebeslag lijkt me onvermijdelijk (wegens aantal categorieën)
dat erop te wijzen dat woningen kleiner worden, maar dat is enigszins misleidend. Dan zou ik dat gegeven eerder uit EPB halen.

##Algemene opmerkingen
- de bron "bodemafdekkingskaart" lijkt me een foute naam ("| provincies.incijfers.be" ontbreekt; bij alle drie de bronnen lijkt het me zinvol om de organisatie die dit aanlevert te vermelden)
- "groene ruimte" is gigantisch groot; "onbebouwde ruimte" lijkt me een betere term (zoals ook in de metadata geformuleerd)
- evolutie van oppervlakte van gebouwen zou ik niet uit GRB halen, omdat dat ook de tuinhuisjes en de industrie omvat. Nu lijkt 
- bij ruimteboekhouding soms toch bizar - Buizingen-Bos heeft geen bos, maar wel 70% beschermde gebieden; Hallerbos heeft 70% bos, maar slechts 14% beschermde gebieden. Nochtans is in beide gevallen (bij mijn weten) zowat al het beschermd gebied bos en vice versa. https://provincies.incijfers.be/jive?workspace_guid=4ec0f343-36b8-45fc-9061-7a25d8349d55

**Comment by KoenSnyers** [comment]
> 
> 
> Suggestie: vraag is of door opsplitsing open ruimte - ruimtebeslag te behouden in Figuur 2 en 3 iedereen doorheeft dat de verschillende categorieën (%bos, % braak,... enerzijds) en (% tuinen&huizen, %transport,...anderzijds) de totale oppervlakte inhouden? M.a.w. waarom geen 1 Figuur (taart gemeente vs taart provincie) met alle categorieën; met eventueel in de titel "de categorieën Open ruimte én Ruimtebeslag"?

Ik begrijp je opmerking, Lieven. Toch lijkt het me opportuun om het zo te behouden, omdat we op deze manier de categorieën van open ruimte en ruimtebeslag in twee aparte grafieken samen houden. Bovendien staat er bij bij elke grafiek vermeld: percentage tov totale oppervlakte. Wat we expliciet vermelden, daarvan mogen we uitgaan dat mensen het ook zien/lezen.

**Comment by Lievendr** [comment]
We hebben het in onze databank wel voorzien, juist ook om de intergemeentelijke vergelijkingen (hoeveel % is nu tuin in vergelijk met...) makkelijker te maken. Ikzelf had het niet direct door; maar ik ben dan ook geen expert :-)

**Comment by valeriepirard** [comment]
•de bron "bodemafdekkingskaart" lijkt me een foute naam ("| provincies.incijfers.be" ontbreekt; bij alle drie de bronnen lijkt het me zinvol om de organisatie die dit aanlevert te vermelden)
Eigenaar van de Bodemafdekkingskaart is Agentschap Informatie Vlaanderen, maar deze is vrij te downloaden

**Comment by KoenSnyers** [comment]
> 
> 
> -Detailopmerking: ik zou volgorde akkerland, grasland, bos, ... aanhouden ipv akkerland, bos, grasland, aangezien het erop lijkt (de metadata is niet zo erg duidelijk op dat vlak) dat ze met grasland landbouwgrond met gras bedoelen (doorgaans weide). Bos zit wat vreemd tussen twee types landbouw
> -de splitsing tussen open ruimte en ruimtebeslag lijkt me onvermijdelijk (wegens aantal categorieën)
> dat erop te wijzen dat woningen kleiner worden, maar dat is enigszins misleidend. Dan zou ik dat gegeven eerder uit EPB halen.
> 
> ##Algemene opmerkingen
> 
>     * de bron "bodemafdekkingskaart" lijkt me een foute naam ("| provincies.incijfers.be" ontbreekt; bij alle drie de bronnen lijkt het me zinvol om de organisatie die dit aanlevert te vermelden)
> 
>     * "groene ruimte" is gigantisch groot; "onbebouwde ruimte" lijkt me een betere term (zoals ook in de metadata geformuleerd)
> 
>     * evolutie van oppervlakte van gebouwen zou ik niet uit GRB halen, omdat dat ook de tuinhuisjes en de industrie omvat. Nu lijkt
> 
>     * bij ruimteboekhouding soms toch bizar - Buizingen-Bos heeft geen bos, maar wel 70% beschermde gebieden; Hallerbos heeft 70% bos, maar slechts 14% beschermde gebieden. Nochtans is in beide gevallen (bij mijn weten) zowat al het beschermd gebied bos en vice versa. https://provincies.incijfers.be/jive?workspace_guid=4ec0f343-36b8-45fc-9061-7a25d8349d55

De volgorde van de categorieën open ruimte en ruimtebeslag had ik aangepast naar volgorde van voorkomen, maar ik had me daarbij gebaseerd op de volgorde van voorkomen in Limburg (in mijn cijferdossier over de ruimtelijke indicatoren); nu heb ik de volgorde opnieuw aangepast, naar volgorde van voorkomen in het Vlaamse gewest. Op die manier is de volgorde: akkerland, grasland, bos, ...

Je opmerking over de bronvermelding: dit moet in de databank aangepast worden. @valeriepirard, kan jij dit doen?

Ik wijzigde de term 'groene ruimte' zoals in de metadata in 'groene (of onbebouwde) ruimte'.

Bronvermelding: @valeriepirard, pas jij aan in de databank waar nodig? Dashboard haalt de bron immers gewoon op uit de databank.

De opmerking over de ruimteboekhouding: ik heb nu uitgeschakeld dat iets uit dit dashboard in de detailview op een lager dan gemeentelijk niveau wordt weergegeven. Uitsplitsen naar lager niveau lijkt me binnen het bestek van dit dashboard niet zo opportuun.

**Comment by valeriepirard** [comment]
Hallo, ik stel voor om de evolutie van de gemiddelde oppervlakte van gebouwen te vervangen door het % verharding per type ruimtebeslag: https://provincies.incijfers.be/jive?workspace_guid=4ec0f343-36b8-45fc-9061-7a25d8349d55
Deze ligt toch meer in de lijn van de rest van de indicatoren aangaan gebruik of bestemming van grond.

**Comment by valeriepirard** [comment]
Juiste link: https://provincies.incijfers.be/jive?workspace_guid=a5de731f-2f59-4e94-a277-c4bbc840df09

**Comment by KoenSnyers** [comment]
> 
> 
> Hallo, ik stel voor om de evolutie van de gemiddelde oppervlakte van gebouwen te vervangen door het % verharding per type ruimtebeslag: https://provincies.incijfers.be/jive?workspace_guid=4ec0f343-36b8-45fc-9061-7a25d8349d55
> Deze ligt toch meer in de lijn van de rest van de indicatoren aangaan gebruik of bestemming van grond.

Ik heb het aangepast zoals je voorstelt, @valeriepirard.

**Comment by joostschouppe** [comment]
> De opmerking over de ruimteboekhouding: ik heb nu uitgeschakeld dat iets uit dit dashboard in de detailview op een lager dan gemeentelijk niveau wordt weergegeven. Uitsplitsen naar lager niveau lijkt me binnen het bestek van dit dashboard niet zo opportuun.

Dat lijkt me voor dit thema (en in het algemeen) net wel een enorme meerwaarde. Het issue met bos vs beschermde gebieden is puur iets lastigs bij interpretatie van de data - dus ofwel iets om in de metadata iets over te zeggen ofwel iets om ion de verwerking nog eens te bekijken

**Comment by KoenSnyers** [comment]
> 
> 
> > De opmerking over de ruimteboekhouding: ik heb nu uitgeschakeld dat iets uit dit dashboard in de detailview op een lager dan gemeentelijk niveau wordt weergegeven. Uitsplitsen naar lager niveau lijkt me binnen het bestek van dit dashboard niet zo opportuun.
> 
> Dat lijkt me voor dit thema (en in het algemeen) net wel een enorme meerwaarde. Het issue met bos vs beschermde gebieden is puur iets lastigs bij interpretatie van de data - dus ofwel iets om in de metadata iets over te zeggen ofwel iets om ion de verwerking nog eens te bekijken

Joost, ik volg hier de policy in het draaiboek van het dashboard en ik citeer:
"Rapportering op lager dan gemeentelijk niveau gebeurt enkel via een sub-dashboard (bij thema’s waar het mogelijk is): “tegel” toevoegen ‘naar deelgemeente, wijk of statistische sector’. Voor elke “tegel” de optie uitsplitsen naar kleiner niveau per tegel uitschakelen."

Ik zie wel dat de nieuwe versie van het dashboard tegels bij verder klikken naar detailview vaak sowieso uitsplitst naar een lager niveau (bv. bij bevolking, huishoudens en nationaliteit & herkomst), maar dat vind ik zelf heel erg verwarrend voor de gebruiker.
Ik zou dat zelfs liever uitschakelen en opteren om, zoals het draaiboek van het dashboard het zegt, subdashboards op lager dan gemeentelijk niveau te maken.

**Comment by KoenSnyers** [comment]
Ik heb het dashboard ruimte online geplaatst, na aanpassingen op basis van een aantal opmerkingen.

**Comment by joostschouppe** [comment]
In orde!
