### ISSUE TITLE
Vraag vanuit centrumsteden - leefloners op statsec

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#165]
Antwerpen beheert leefloners vanuit pod mi (vb v3104_rmileefl_ip)
Vlaams-Brabant beheert leefloners vanuit ksz (vb v1201_ksz_n33)

Is het bij een van beide bronnen mogelijk om dit op statsec niveau te verzamelen?
(voor ksz zit dat misschien mee in onze aanvraag-in-opmaak?)

(ook cc @rudymarynissen)

**Comment by VickyVB** [comment]
Inderdaad hoe ik nu KSZ aflaad (van de website KSZ - lokale statistieken) is gemeente het laagste geografische niveau. In onze aanvraag vragen we wel de nomenclatuur (met onder meer de leefloners ) op statistische sector niveau.  

Los daarvan zijn er natuurlijk wel verschillen in de definitie van de leefloner bij de nomenclatuur van KSZ (belangrijkste arbeidsmarktpositie op de laatste dag van het jaar) en de gegevens van de POD MI.

**Comment by joostschouppe** [comment]
In de webtoepassing is het inderdaad wel een paar uur werk om het er uit te pleuren.
Zal ik een vrijwilliger zoeken om dat te doen?
Wel lastig met de waarden 1-3, die maken dat je niet correct kan aggregeren naar wijk en deelgemeente. Maar dat zouden we misschien kunnen oplossen door een random waarde tussen 1 en 3 in te vullen waarbij de totalen van de gemeente wel nog kloppen. (lijkt me een leuk scriptje om te bouwen :)) Uiteraard wel nog altijd gewoon alle gemeenten inlezen ook.

**Comment by VickyVB** [comment]
Zouden we dan niet gewoon de KSZ aanvraag doen?
 Ik denk dat je voor de meeste statistische sectoren met een waarde tussen 1 en 3 gaat zitten. Bovendien moet je dan voor elk van de 319 gemeenten per jaar een export doen ... dat lijkt me heel veel werk en heel veel kans op fouten.
Bovendien tel je bij de ksz dus niet simpelweg het personen die door het jaar heen leefloon kregen, maar mensen die op de laatste dag van het jaar leefloon kregen en dat niet combineren met 'een positie dichter bij de arbeidsmarkt', werk of werkloosheid. (Ik probeer deze week even na te gaan of dat überhaupt mogelijk is.)

**Comment by joostschouppe** [comment]
Je kan iets van een 400-500 statsec per keer afhalen, dus een stuk of 25 exports per jaar, geen 319
Maar je inhoudelijke argumenten lijken me doorslaggevend

**Comment by joostschouppe** [comment]
Zie voor gelijkaardige vragen ook:
https://github.com/provinciesincijfers/data-wishlist/issues
https://github.com/provinciesincijfers/connectorbeheer/issues

**Comment by joostschouppe** [comment]
We nemen dit mee in de KSZ aanvraag
