### ISSUE TITLE
"rapport" gebiedsinfo niet meer actueel

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#167]
er schijnen mogelijke links NIET getoond te worden voor boven-gemeentelijke indelingen

**Comment by joostschouppe** [comment]
Redelijk wat toegevoegd.
Nieuw issue:  Rapport bevolking en huishoudens en Rapport nationaliteit en herkomst werken niet voor een provincie + gebied onbekend. Dat was even zoeken! Zat fout in het sjabloon. De presentatie test_brussel werkte op een onderwerp dat niet beschikbaar is voor gebied onbekend. Dus even v9999_altijdiets aangemaakt om dit op te lossen.

**Comment by StefanJacques** [comment]
#joost=klasbak !
