### ISSUE TITLE
generieke aanpassingen in alle rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#168]
1. het is blijkbaar mogelijk om een parameter aan te maken die rechtstreeks het aantal gebieden in een lijst opvraagt. Nu gebeurt dit steeds door eerst een presentatie aan te maken. Vb:

```
input_geo_desc_gemeente = Descendants(input_geo, Geo.gemeente)
aant_gemeenten = ListCount(input_geo_desc_gemeente)
```

Dat kan in alle rapporten wel minstens één presentatie overbodig maken

2. in alle rapporten de presentatie "test_brussel" doen verwijzen naar onderwerp `v9999_altijdiets` ipv de oppervlakte. Zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/167#issuecomment-722528015

**Comment by davidcardinaels** [comment]
Punt 2 is in orde

**Comment by joostschouppe** [comment]
Punt 1 nog concreet uit te werken, ik vraag even na bij Edward

**Comment by davidcardinaels** [comment]
Punt 1 volgens Edward voorlopig enkel mogelijk via presentatie
