### ISSUE TITLE
rapport armoede, opmerkingen Ine

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#17]
Ik heb 2 downloads gedaan (eentje met 2 gemeentes in vgl met de prov en het VLGEW; zowel 2 O-VL als Limburgse gemeentes, en eentje met enkel de gemeente Aalst in vgl met de prov en het VLGEW.)
 
Voor beide rapporten stel ik vast:
De inhoudstafel wordt over 2 bladzijden gesplitst. Dit oogt mooier op 1 blad.
Figuur 2: titel en figuur staan op een verschillend blad.
Na 3.6 staat er geen spatie voor Werkloosheid
 
Voor het rapport met 2 gemeentes stel ik vast:
P12 is volledig blanco

- [x] P34 Laatste grafiek geeft #not valid# aan

**Comment by davidcardinaels** [comment]
Alle opmerkingen zijn in orde.
