### ISSUE TITLE
jaartal Kind & Gezin - check momentopnames van data

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#170]
Er is een gesprek gaande ivm het jaartal van de data van Kind & Gezin.
Het meest recente cijfer betreft een snapshot zoals 31/12/2019. Bij Kind & Gezin staan ze erop dat alle hergebruikers dit benoemen als het cijfer voor "2019", om verwarring te vermijden. In PinC beschouwen we 31/12/2019=1/1/2020=2020. In het statistisch landschap bestaan beide benaderingen. K&G zonder meer volgen zou voor verwarring aan onze kant zorgen.

Er is nog geen oplossing, maar voorlopig proberen we dit zo goed mogelijk te duiden.

## Rapporten
Automatisch verschijnt een voetnoot: 

> ! Jaartal 2020 in PinC = Momentopname 31/12/2019 = 2019 op K&G-website

Dit verschijnt echter potentieel meerdere keren bij dezelfde grafiek.
Dan kunnen we dit beter uitzetten voor het rapport. Dat kan met de code `<ShowFootNote>False</ShowFootNote>`
Dan vervangen door een tekstje als:
Opgelet: de cijfers over kinderopvangplaatsen van 2020 zijn van 31/12/2019; Kind & Gezin ziet dat als cijfers van 2019.

## Databank
Voorlopig verschijnt enkel de voetnoot zoals hierboven
We proberen nog:
- toevoegen aan onderwerp naam
- toevoegen aan onderwerp beschrijving
- toevoegen aan themaboom beschrijving
- toevoegen aan individuele datavelden

## Dashboard
Opgelet: de cijfers over kinderopvangplaatsen van 2020 zijn van 31/12/2019; Kind & Gezin ziet dat als cijfers van 2019.

## Andere to do's

* Nagaan hoeveel bronnen daadwerkelijk snapshots van 31/12-1/1 zijn: bron, exacte datum snapshot, ons jaar, bron jaar
* Motivatie/uitleg schrijven van waarom we deze keuze gemaakt hebben

**Comment by VickyVB** [comment]
Hierbij, voor Vlaams-Brabant,  een overzicht van de referentiemomenten die we in PinC gebruiken vs die de bron in kwestie gebruikt.
[overzicht referentiemoment bron vs PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5567671/overzicht.referentiemoment.bron.vs.PinC.xlsx)

**Comment by Inejacobs** [comment]
Hierbij een overzicht van referentiemomenten voor de domeinen Veiligheid en Landbouw LIM. Alsook de dienstencheques.

[0verzicht.referentiemoment.bron.vs.PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5590005/0verzicht.referentiemoment.bron.vs.PinC.xlsx)

**Comment by valeriepirard** [comment]
Hierbij een overzicht voor de onderwerpen ruimte/EPB/bebouwing/VSV

[Limburg_VP_referentiemoment.bron.vs.PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5590461/Limburg_VP_referentiemoment.bron.vs.PinC.xlsx)

**Comment by karolienbloemen** [comment]
Hierbij overzicht voor ouderenzorg:
[KB_referentiemoment.bron.vs.PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5602413/KB_referentiemoment.bron.vs.PinC.xlsx)

**Comment by Lievendr** [comment]
overzicht vanuit Antwerpen
[KB_referentiemoment.bron.vs.PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5607071/KB_referentiemoment.bron.vs.PinC.xlsx)

**Comment by miekevanopstal** [comment]
overzicht vanuit OVL
[overzicht referentiemoment bron vs PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5621162/overzicht.referentiemoment.bron.vs.PinC.xlsx)
en in & lijst: 
[overzicht referentiemoment bron vs PinC_samen.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5621220/overzicht.referentiemoment.bron.vs.PinC_samen.xlsx)

**Comment by StefanJacques** [comment]
[overzicht_referentiemoment_bron-PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5673198/overzicht_referentiemoment_bron-PinC.xlsx)

in bijgevoegd bestand ook nog eens de verantwoordelijke provincie bijgevoegd
@SofieWVl @StefanieWVL : aan jullie om dit bestand nog aan te vullen en hier terug neer te zetten

**Comment by StefanieWVL** [comment]
WVL ook aangevuld

[overzicht_referentiemoment_bron-PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5679292/overzicht_referentiemoment_bron-PinC.xlsx)

**Comment by miekevanopstal** [comment]
Collega's
Er was ook een probleem met de kansarmoede-index. Ik had die ook ingeladen in PinC op jaartal X+1. 
Na overleg beschouwen we de kansarmoede-index als een "lopend" onderwerp :-) en heb ik dit aangepast naar het zelfde jaartal als K&G. 
Ik heb gezien dat deze wijzigingen niet doorgevoerd worden bij connectoren (denk ik) of door ABF? Bij denderleeuw.incijfers.be staat de kansarmoede-index 2019 en 2020 nu met hetzelfde cijfer (2020 zou geschrapt moeten worden).
![image](https://user-images.githubusercontent.com/56152293/106623931-68471500-6575-11eb-9b95-539a1d54af9d.png)

De voetnoten, aanpassingen in de titel,...  die bij ons wijzen op een afwijkend jaartal, zijn in de afgeleide websites niet langer zichtbaar...
Een probleem? Te melden? of de boom in?

**Comment by joostschouppe** [comment]
Ik geef het door aan ABF. Geen idee hoe vaak ze de gemeente.incijfers.be websites updaten!

**Comment by miekevanopstal** [comment]
OK- bedankt Joost!

Met vriendelijke groeten

D&A OVL- Mieke Van Opstal
09 267 75 03 | mieke.van.opstal@oost-vlaanderen.be<mailto:mieke.van.opstal@oost-vlaanderen.be>
D&A<http://www.oost-vlaanderen.be/dataenanalyse> | provincies.incijfers<https://provincies.incijfers.be/dashboard>| maandelijkse nieuwsbrief.<https://provincies.incijfers.be/dashboard/nieuws/>
[logo enkle]


Van: Joost <notifications@github.com>
Verzonden: woensdag 3 februari 2021 14:23
Aan: provinciesincijfers/PinC-taakopvolging <PinC-taakopvolging@noreply.github.com>
CC: Van Opstal Mieke <mieke.van.opstal@oost-vlaanderen.be>; Comment <comment@noreply.github.com>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] jaartal Kind & Gezin - check momentopnames van data (#170)


Ik geef het door aan ABF. Geen idee hoe vaak ze de gemeente.incijfers.be websites updaten!

**Comment by joostschouppe** [comment]
Voorstel: tekstje toevoegen aan tegel Bronnen, inclusief stukje "metadata"
Huidig:
> In provincies.incijfers.be gebruiken we data uit verschillende bronnen. Elke bron heeft haar beperkingen. Om een voorbeeld te geven: in het aantal inwoners van een gemeente zitten de daklozen niet vervat. Daarom is het belangrijk dat je in de databank de uitgebreide metadatafiche raadpleegt die bij elke databron hoort. Die metadatafiche geeft tekst en uitleg bij de cijfers, hoe ze verzameld en berekend worden, wat ze in kaart brengen, ... Heb je toch nog vragen? Neem dan contact met ons op.

Voorstel:
> In provincies.incijfers.be gebruiken we data uit verschillende bronnen. Elke bron heeft haar inhoudelijke en technische beperkingen. Om een voorbeeld te geven: in het aantal inwoners van een gemeente zitten de daklozen niet vervat. Sommige data is gebaseerd op een allesomvattende registratie. Andere data komt uit bevragingen met een foutenmarge of modellen met assumpties. 
> Doordat we diverse bronnen samenbrengen, moeten we harmoniseren. Heel wat bronnen zijn gebaseerd op snapshots genomen rond nieuwjaar. In de ene helft van de gevallen wordt dit beschouwd als 31 december, in de andere helft als 1 januari. Wij hebben de keuze gemaakt om deze steeds weer te geven alsof het om 1 januari gaat. Bij de oorspronkelijke bronnen kan het daarom zijn dat je een ander jaartal ziet voor dezelfde data.
> Daarom is het belangrijk dat je de uitgebreide metadatafiches raadpleegt die bij elke databron hoort. Die metadatafiche geeft tekst en uitleg bij de cijfers, hoe ze verzameld en berekend worden, wat ze in kaart brengen, ... Heb je toch nog vragen? Neem dan contact met ons op.

* Dit tekstje staat nu al zo op de Bronnen-pagina, waardoor mensen zouden kunnen verwachten dat ze door te klikken op de metadatafiche komen...
* Er zijn ook enkele "interessante" gevallen: snapshot juli, snapshot mei, snapshot februari. Deze worden nu steeds aan het jaar zelf toegekend.

**Comment by StefanieWVL** [comment]
IMA-preventie aangevuld

[overzicht_referentiemoment_bron-PinC (1).xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/6090452/overzicht_referentiemoment_bron-PinC.1.xlsx)

**Comment by SofieWVl** [comment]
IMA aangevuld: 
[overzicht_referentiemoment_bron-PinC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/6100550/overzicht_referentiemoment_bron-PinC.xlsx)
loop van het jaar data
