### ISSUE TITLE
standaard maximum lengte voor evolutiegrafieken in rapporten, indien "laatste tien jaar"

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#171]
Wellicht best om dan te zeggen 2010-2020 ipv 2011-2020. Eigenlijk is dat dus 11 jaar ipv 10 jaar.
Misschien al afsgesproken, na te kijken in documentatie!

**Comment by Tine-VB** [comment]
Voor het dashboard is in het draaiboek vastgelegd dat een standaard evolutie over 11 jaar gaat:
 Afwijking mogelijk mits motivatie (bv. beperkte beschikbaarheid voor aantal jaren (technisch krijg je dan een blanco)/beleidsrelevantie/…).
 let op: bij keuze voor een begin- en een eindjaar moet er -10 ingesteld worden als period-index voor het beginjaar, tenzij er nog geen tijdreeks van 11 jaar beschikbaar is (dan moet jaarlijks bij actualisatie een andere period-index ingesteld worden, tot er een tijdreeks van 11 jaar beschikbaar is).
Best dat we dan voor rapporten dezelfde afspraak aanhouden.

**Comment by joostschouppe** [comment]
Algemene regel: jaar + 1 (vb 6 jaar, 11 jaar, 21 jaar)

**Comment by joostschouppe** [comment]
Opgenomen in sjabloon
