### ISSUE TITLE
Tekst boven of onder figuren/grafieken/rapporten binnen een rapport?

### ISSUE THREAD

**Issue by ChrisMichelDS** [provinciesincijfers/PinC-taakopvolging#172]
Bij het opmaken van het rapport ELZ is (opnieuw) de vraag naar boven gekomen of tekst best onder of boven figuren/grafieken/rapporten komt te staan binnen een rapport? Kunnen we binnen de redactieraad hier tot een duidelijk standpunt komen?

**Comment by joostschouppe** [comment]
Bedankt Chris, beter dit once and for all beslissen.
Dit is reeds eerder afgesproken en opgenomen in het draaiboek rapporten, al vind ik niet direct iets terug over het beslissingsproces.

Ik zie weinig meerwaarde van dit te bespreken tijdens de vergadering. In de plaats stel ik voor dat iedereen binnen diens provincie ten rade gaat en een standpunt brengt. Dat standpunt kan naast "eerst tekst dan figuur", "eerst figuur dan tekst", "maakt niet uit als het maar altijd hetzelfde is" of "maakt niet uit". Ik agendeer het enkel op voorwaarde dat alle provincies hier hun voorkeur hebben neergezet én dat dit niet voldoende is om direct een beslissing te nemen.

**Graag hieronder je voorstel, eventueel ook je argumenten.**

**Mijn voorstel: "eerst tekst dan figuur"**
Argumentatie: er zijn ongetwijfeld fantastische argumenten te verzinnen voor "tekst eerst", net als voor "figuur eerst". Nu is het doorgaans (altijd?) geschreven met de logica "tekst eerst". En dus:
* Heb je veel praktisch uitvoerend werk. Niet alleen moet je de tekst in de meeste gevallen verzetten, je gaat ook alle tekst moeten nalezen op consistentie in de nieuwe positie
* Moet je dit afstemmen met de werkgroepen. Ook werkgroep-rapporten zijn zo geschreven, dus dan moeten die hier ook nog eens over gaan; en staan ze hopelijk niet op hun achterste poten
* Be je je best aan het doen voor een hypothetische gebruiker, ten nadele van een werkelijke gebruiker. Gebruikers van PinC zijn dit op dit moment zo gewoon. Dit nu veranderen zou zijn "onze zeker bestaande gebruikers benadelen ten opzichte van een hypothetische klant waar we van denken (maar niet weten) wat zij gewoon zijn"

Ik kan mij persoonlijk niet voorstellen dat de argumenten voor "figuur eerst" zoveel sterker zijn dan die voor "tekst eerst" om deze aanpassingen te verantwoorden.

**Comment by StefanJacques** [comment]
collega's D&A van provincie Limburg zijn **akkoord** met: **"eerst tekst dan figuur"**

**Comment by Tine-VB** [comment]
In Vlaams-Brabant zetten wij ook altijd eerst de tekst en dan de figuur in rapporten (buiten PinC bedoel ik). Dit is natuurlijk een gewoonte. Ik ben het eens met Joost dat dit aanpassen in al bestaande rapporten meer moeite kost dan dat er een eventueel voordeel zou zijn voor de lezer (als dat er dus al is).

**Comment by Lievendr** [comment]
Antwerpen is ook akkoord met argumenten van Joost als algemene lijn.

**Comment by StefanieWVL** [comment]
WVl : akkoord

**Comment by joostschouppe** [comment]
Ik beschouw dit als afgesloten, maar ga dit pas sluiten eens de methodologie uitgelegd in  https://github.com/provinciesincijfers/PinC-taakopvolging/issues/177#issuecomment-736621138 klaar staat voor "draaiboek rapporten"
