### ISSUE TITLE
Naam, data type en eenheid bij onderwerpen per oppervlakte

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#174]
Voor onderwerpen per oppervlakte worden verschillende naamgevingen, datatypes en eenheden gebruikt. Hierover moeten betere afspraken gemaakt worden (en toevoegen aan doc basis swingbeheer).
Enkele voorbeelden: 

Indicator code | Name | Data type | Unit | Formula
-- | -- | -- | -- | --
vp2207_nbw_prim_ander_opp | andere residentiële gebouwen, energieverbruik per m² | Mean | kwh_vierkante_m | v2207_nbw_prim_ander/v2207_nbw_opp_ander
vp2207_nbw_prim_app_opp | appartementen, energieverbruik per m² | Mean | kwh_vierkante_m | v2207_nbw_prim_app/v2207_nbw_opp_app
vp2207_nbw_prim_gesl_opp | gesloten eengezinswoningen, energieverbruik per m² | Mean | kwh_vierkante_m | v2207_nbw_prim_gesl/v2207_nbw_opp_gesl
vp2207_nbw_prim_hopen_opp | halfopen eengezinswoningen, energieverbruik per m² | Mean | kwh_vierkante_m | v2207_nbw_prim_hopen/v2207_nbw_opp_hopen
vp2207_nbw_prim_open_opp | vrijstaande eengezinswoningen, energieverbruik per m² | Mean | kwh_vierkante_m | v2207_nbw_prim_open/v2207_nbw_opp_open
vp2207_nbw_prim_ander_opp_t5 | andere residentiële gebouwen, energieverbruik per m² (laatste 5 jaar) | Mean | kwh_vierkante_m | v2207_nbw_prim_ander_t5/v2207_nbw_opp_ander_t5
vp2207_nbw_prim_app_opp_t5 | appartementen, energieverbruik per m² (laatste 5 jaar) | Mean | kwh_vierkante_m | v2207_nbw_prim_app_t5/v2207_nbw_opp_app_t5
vp2207_nbw_prim_gesl_opp_t5 | gesloten eengezinswoningen, energieverbruik per m² (laatste 5 jaar) | Mean | kwh_vierkante_m | v2207_nbw_prim_gesl_t5/v2207_nbw_opp_gesl_t5
vp2207_nbw_prim_hopen_opp_t5 | halfopen eengezinswoningen, energieverbruik per m² (laatste 5 jaar) | Mean | kwh_vierkante_m | v2207_nbw_prim_hopen_t5/v2207_nbw_opp_hopen_t5
vp2207_nbw_prim_open_opp_t5 | vrijstaande eengezinswoningen, energieverbruik per m² (laatste 5 jaar) | Mean | kwh_vierkante_m | v2207_nbw_prim_open_t5/v2207_nbw_opp_open_t5
v9900_opp | oppervlakte (in km²) | Numeric | vierkante_kilometer | v9900_oppervl / 1000000
vp2503_pvinstallatie_plus10kw_vermogen_km2 | PV-installaties groter dan 10 kW - geïnstalleerd vermogen (per km²) | Mean | mw_vierkante_km | v2503_pvinstallatie_plus10kw_vermogen/v9900_opp
v9900_statsec_oppervl_km2 | oppervlakte (in km²) | Numeric | vierkante_kilometer | v9900_statsec_oppervl_m2/1000000
vp2703_bedr_mestvarkens_2000_opp | varkensbedrijven   vanaf 2.000 mestvarkens (t.o.v. oppervlakte) | Mean | per_vierkante_km | v2703_bedr_mestvarkens_2000/v9900_opp * 100
vp2703_bedr_zeugen_750_opp | varkensbedrijven   vanaf 750 zeugen (t.o.v. oppervlakte) | Mean | per_vierkante_km | v2703_bedr_zeugen_750/v9900_opp * 100
vp2703_bedr_pluimvee_40000_opp | pluimveebedrijven   vanaf 40.000 dieren (t.o.v. oppervlakte) | Mean | per_vierkante_km | v2703_bedr_pluimvee_40000 / v9900_opp * 100
v1101_bevdicht | bevolkingsdichtheid | Mean | per_vierkante_km | v1101_t / v9900_oppervl * 1000000
vp1111a_bevdicht | bevolkingsdichtheid | Mean | per_vierkante_km | v1111a_tot_bevolking / v9900_oppervl * 1000000

**Comment by Tine-VB** [comment]
Dus de op te lossen vragen zijn:
1. Mag "per km²" "per m²" in de naam staan?
2. Willen we als datatype "Mean"? Er staat dan een 
![image](https://user-images.githubusercontent.com/61458346/100353825-6a2dae80-2fef-11eb-9cf2-00b99ffd2c25.png) in de themaboom. Moet dit niet eerder een ratioteken zijn?
3. moeten we bij dichtheden niet eerder "_aantal_ per km²" (of per m²) in de legende zetten?

**Comment by Tine-VB** [comment]
Bij de varkens en de kippen moet het trouwens per 100 km² zijn. Dat maakt het nog even ingewikkelder :-)

**Comment by joostschouppe** [comment]
Aanvulling, closes https://github.com/provinciesincijfers/PinC-taakopvolging/issues/159

Moeten we uniformiseren tussen m² - hectaren - km²: en daar een keuze in maken en of al die andere indicatoren van statbel erop moeten blijven staan (Landbouwenquetes,…)
Zie ook #110 (comment)

Alle noemers op onze eigen oppervlaktes zetten > zie ook https://provincies.incijfers.be/jive?workspace_guid=ed930175-3690-40f1-8f6b-96aad1c3b7b1 en https://mailings.economie.fgov.be/l/103100/uasuffbrwkfpopsndfjfjarlvh6dxuu7z52u2la7qlnjxli7n4fa/2s5eaznrjtyxz7cf3alvycyei4

Suggestie van Tine: hier ook een metadatafiche over voorzien

**Comment by joostschouppe** [comment]
Concreet voorstel (uitgewerkt door @Tine-VB):

Er zijn drie soorten oppervlaktevariabelen:
1.	De dichtheden: zie de eerste vier variabelen hieronder, die geven de verspreiding over de oppervlakte van het gebied (bijvoorbeeld een gemeente)
2.	De variabelen die per oppervlakte worden berekend: zoals energieverbruik per m², die m² slaat hier op de woning, niet op het gebied.
3.	Oppervlakte zelf: oppervlakte van een gebied (bijvoorbeeld gemeente), of oppervlakte ruimtebeslag…

![afbeelding](https://user-images.githubusercontent.com/10122639/200866040-c01d6c83-cd5f-44d1-aadd-2c770c90ebd7.png)

1.	**Dichtheden**: we volgen het voorbeeld van de varkensbedrijven… en ook inwoners per ha ruimtebeslag
-	Datatype: Percentage (sum)
-	Unit: ratio (want “per km²” is geen eenheid)
-	Naam: … per km² of … per 100 km² of … per ha

Dus: Geen haakjes rond per km² in de naam (zoals bij PV-installaties >10 kW - geïnstalleerd vermogen (per km²)) en niet (t.o.v. oppervlakte) (zoals bij knooppunten recreatief fietsnetwerk). Datatype is GEEN mean hier. Vermijden dat per km² er twee keer staat (zie bv bedrijven met landbouwproducten) door als eenheid voor ratio te kiezen.

2.	**Variabelen berekend per oppervlakte** (van iets anders dan een gebied): 
-	Datatype: Mean (want gaat bijvoorbeeld over gemiddeld energieverbruik per m² van een appartement)
-	Unit: bijvoorbeeld kwh_vierkante_m (wordt dus kWh/m² in PinC), hier consequent in zijn, want soms staat er in PinC MW per km², dat moet dan ook worden: MW/km².
-	Naam: ik zou hier de per m² ook behouden (beter zou zijn per vierkante meter, maar dan wordt het te lang), al staat er dan wel 2 keer m² in als je het opvraagt in PinC

3.	**oppervlakte zelf (of oppervlakte in de teller):** deze volgen de algemene regels, kan bijvoorbeeld een mean zijn bij gemiddelde oppervlakte van gebouwen, met als eenheid m². Bij de indicatoren hierboven staat er wel twee keer km² of m² in PinC, maar dat komt omdat er in de themaboom een onderscheid moet worden gemaakt, daar zie ik niet direct een oplossing voor:

**Comment by joostschouppe** [comment]
Redactiegroep 14/11/2022: de redactieleden bekijken dit en laten weten of ze akkoord zijn met het voorstel

**Comment by Lievendr** [comment]
kan me zeker vinden in voorstel van Tine. Misschien nog eens samen nadenken om dubbele vermeldingen in naam te vermijden?

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/12: akkoord

**Comment by joostschouppe** [comment]
Wordt geïmplementeerd via https://github.com/provinciesincijfers/JiveDocumentation/issues/22
