### ISSUE TITLE
Data landbouw: formule-onderwerpen nakijken

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#176]
Bij de data van landbouw blijken er een aantal formule-onderwerpen hard opgeladen te zijn, bijvoorbeeld een aantal samentellingen van dieren, de som van de GPBV-bedrijven... 
Na te kijken en aan te passen. 
Landbouwwerkgroep erop wijzen, zodat dit bij nieuwe oploads niet opnieuw gebeurt.

**Comment by joostschouppe** [comment]
ondertussen in orde
