### ISSUE TITLE
draaiboek voor data en metadata

### ISSUE THREAD

**Issue by StefanieWVL** [provinciesincijfers/PinC-taakopvolging#177]
In het verslag van de werkgroep kwaliteit 2019-2020 las ik het volgende: 

**In de marge**
Tijdens het overleg van november 2019 met de werkgroep kwaliteit, kwam het opvolgingsbestand taakverdeling aan bod. _Er werden afspraken gemaakt om hierin steeds actualisatie en controle op data aan te vullen._ Inmiddels loopt er ook een oefening met ABF om dit binnen swing zelf op te kunnen volgen. Dit moet nog verder uitgewerkt en geïmplementeerd worden: planning 2021.

Aangezien ik dit zelf over het hoofd zag bij een actualisatie, ben ik zo vrij geweest dit aan te vullen in het draaiboek voor controle data en metadata:

Volgende zin werd toegevoegd:
Vul aan in het [opvolgingsbestand](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/5ee48f87-c8a4-4aff-b2b3-dd15a59e9913) taakverdeling de datum van laatste upload en de datum van laatste check.

**Vraagje voor de redactiegroep**: is het zinvol om in Github een issue open te laten staan (per opvolgingsdocument) zodat eventuele aanpassingen aan de betreffende documenten steeds via hetzelfde kanaal gecommuniceerd worden? Concreet bv draaiboek controle, dit issue niet sluiten en alle toekomstige aanpassingen komen dan in dit issue te staan? Of is er een efficiëntere manier?

**Comment by joostschouppe** [comment]
Stefanie,
Ik zou de volgorde denk ik omdraaien.
Mijn idee is om deze "draaiboeken" naar Github over te zetten. Dan kan je op elk moment dit doen:
https://github.com/provinciesincijfers/PinC-taakopvolging/blame/master/README.md (om te zien wat wanneer waarom is aangepast/toegevoegd).
Die wijzigingen zouden steeds naar aanleiding moeten zijn van een Issue, met een gesuggereerde wijziging. Dat issue kan dan afgesloten worden met een verwijzing naar een wijziging (vb https://github.com/provinciesincijfers/PinC-taakopvolging/commit/e8703de2819d6e0d6e131e289a77d65cd06e1fd7), en omgekeerd kan bij die wijziging verwezen worden naar het issue.
Om dan een kanaal te hebben per document, zouden we eventueel een label kunnen hebben per document. Een overzicht van de relevante recente afgesloten Issues kan je dan zo krijgen: https://github.com/provinciesincijfers/PinC-taakopvolging/issues?q=is%3Aclosed+label%3ARG-beheersafspraken
Als we die pure afsprakenbestanden in een eigen repository steken, dan kan je die hele repository "wacthen" om van alle wijzigingen automatisch bericht te krijgen.

**Comment by StefanieWVL** [comment]
precies wat ik ook dacht 👍 :-)
