### ISSUE TITLE
Fout in "cijfers bevolking opgelijst"

### ISSUE THREAD

**Issue by StefanieWVL** [provinciesincijfers/PinC-taakopvolging#179]
Hoi,

Ik denk dat er een foutje geslopen is in het rapport "cijfers bevolking opgelijst". Het betreft de evolutie van de cijfers die de loop van de bevolking weergeven. Er staat namelijk als index 2010, maar volgens mij werd 2009 als indexjaar gebruikt. Naar analogie met de andere evolutiecijfers is de titel "index 2010" correct maar dienen de cijfers herrekend te worden, denk ik.

Ik kan niet onmiddellijk vinden wie hiervoor de verantwoordelijke en de checker zijn, dus ik smijt het maar op Github ;-)

https://provincies.incijfers.be/jive?workspace_guid=5d89811a-bf65-42f3-9148-7c3d24470db6

**Comment by StefanieWVL** [comment]
Opgelost! Met dank aan Stefan en David

**Comment by StefanieWVL** [comment]
Dag Stefan en David

Tenzij ik hier iets helemaal verkeerd doe, maar volgens mij loopt er iets fout met de berekening van **alle** evolutiecijfers in het rapport "bevolking opgelijst". Wanneer ik zelf de indexen bereken bekom ik andere waarden dan degene uit de rapporten. Ik heb meerdere jaren gecombineerd, maar ik kan de waarden uit het rapport niet reconstrueren. Ik kan dus ook niet onmiddellijk zeggen waar het precies fout loopt. 

bv. voor Aalst aantal inwoners: 87603 (2020) / 81254 (2011) > Index 107,8 . In het rapport staat Index 114,9

https://provincies.incijfers.be/jive?workspace_guid=91e6e49a-6076-4a40-902d-1d77287022bc

https://provincies.incijfers.be/jive/report?openinputs=true&id=tabellenrapport_bevolking

Het viel me plots op toen ik voor deelgemeente Sint-Joris (in Beernem) Indexen boven de 5.000 zag verschijnen ... .

Willen jullie dit eens bekijken a.u.b.? 

Dank je wel!

**Comment by davidcardinaels** [comment]
Ik heb de baseperiods terug op 2010 en 2011 gezet en nu kloppen de indexen weer. 
BasePeriod: -9; lijkt me niet te werken. Stefan, waar ben je die code tegengekomen?

Ik zoek nog even uit hoe we die basisperiode variabel kunnen maken maar voorlopig is het weer in orde (idem voor tabellenrapport huishoudens)

**Comment by davidcardinaels** [comment]
De indexen zijn nu variabel en ze kloppen!
