### ISSUE TITLE
Grondige controle themaboom / indicatorentabel

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#181]
Vooraleer ik kan starten met een grondige controle van de onderwerpen in de themaboom, moeten er nog een paar knoopjes doorgehakt worden:
- EUR of €
- 1.000 of 1000
- '65-... jaar' of '65+' of '65-plus' of '65-plussers': in de naam wordt redelijk consequent 65-... jaar gebruikt, maar in de beschrijving niet (voorbeeldje: ‘gebruikers dienstencheques 65-... jaar (t.o.v. 65-plussers)’), en niet iedereen is even enthousiast over 65-... jaar, dus als het aangepast moet worden...
- 18-64-jarigen of 18-64 jaar: voorstel: het eerste (met streepje) als het op zich staat, het tweede (zonder streepje) als het ergens achter staan (bijvoorbeeld bij ‘beroepsbevolking 18-64 jaar’)
- aandeel/aantal mogen niet in de onderwerpnaam, maar gemiddelde wel? Soms moet dat wel, om het onderscheid te maken, zoals bij ‘gemiddeld inkomen’ en ‘mediaan inkomen’, maar bijvoorbeeld bij ‘gemiddeld E-peil van appartementen’ of ‘gemiddelde huurprijs’ of ‘gemiddelde temperatuur zomer’ of ‘gemiddelde oppervlakte van appartementen’ of ‘gemiddelde wachttijd’ of ‘gemiddelde huishoudensgrootte’? Kan je daar niet zeggen: het teken van gemiddelde staat ervoor, net zoals bij aantal en aandeel?

En verder nog deze vragen:
- worden ook bronnen / eenheden / datatypes nagekeken? Zie bijvoorbeeld https://github.com/provinciesincijfers/PinC-taakopvolging/issues/174, maar als ik in de indicatorenlijst kijk, dan zie ik dat ‘mean’ en ‘ratio’ in het algemeen door elkaar worden gebruikt. Bij de eenheden en de bronnen dreigt het ook een rommeltje te worden. Hoort dit bij mijn ‘nakijktaak’ of doe ik enkel de onderwerpnamen en beschrijvingen?
- mag ik aanpassingen doen zonder eerst te vragen aan de verantwoordelijke? En moet ik de wijzigingen bijhouden in een lijstje? Of is dat niet nodig?

**Comment by Tine-VB** [comment]
Het documentje met 'te controleren dingen' vinden jullie op Alfresco: https://share.vlaamsbrabant.be/share/s/6pwJgzqcTdWyjnADg1Q4rA
Aanvullingen zijn welkom.

**Comment by StefanJacques** [comment]
Choose your battles ...

... maar ik ben alvast van **volgende schrijfwijzen** voorstander
•	**1.000** (met stip !!!)
•	'**65-... jaar** (zeker niet '65+' of '65-plus') als het alleen staat én "**t.o.v. 65-plussers**" als het "t.o.v." is --> volgens mij staat dat nu al quasi-overal
•	18-64-jarigen of 18-64 jaar   --> naar analogie met hierboven **x-y jaar** zou ik **overal** gebruiken behalve als je t.o.v. gebruikt, dan wordt het **t.o.v. 18-64-jarigen**, t.o.v. 0-2_jarigen, ... --> volgens mij staat dat nu al quasi-overal

Tot zover mijn prioriteiten


Hier zegt mijn gevoel
•	**EUR** of € --> lichte voorkeur voor EUR
•	aandeel/aantal mogen niet in de onderwerpnaam, **maar gemiddelde wel**? bij aandeel een aantal lijkt het me evident om ze niet in bewoordingen op te nemen; echter als het er op lijkt dat 'gemiddelde' vaker WEL dan niet nodig is in de onderwerpnaam om instant-verduidelijking te geven, mag je van mij ALTIJD GEMIDDELDE toevoegen

**Comment by Tine-VB** [comment]
@StefanJacques: 'gebruikers 65-... jaar (t.o.v. 65-plussers)' vind ik echt geen zicht. Dan liever 'gebruikers 65-... jaar (t.o.v. bevolking 65-... jaar)'. Maar wat is er zo tegen 65+ of 65-plus? Ik vraag maar, hé :-).
En helaas, er zijn er toch nog te verbeteren heb ik al gezien...
Als het teken van gemiddelde (net als bij aantal en aandeel) consequent gebruikt wordt, is het misschien bijna nooit nodig om in de onderwerp verduidelijking te geven, en kan het dus bijna overal weggelaten worden? Ik zal eens een paar voorbeeldjes uitwerken tegen de redactiegroep.

**Comment by Tine-VB** [comment]
Nog enkele extra knoopjes, door Stefan aangegeven:
* naam van de submappen met percentages: relatieve cijfers, percentages of aandelen?(Stefan heeft voorkeur voor relatieve cijfers)
* [percentage], [promille], [ratio], [projecties]: achteraan de beschrijving of vooraan? Bij lange beschrijvingen heeft vooraan de voorkeur, dus overal toepassen?
* standaard afronding op 0,1 bij relatieve cijfers, uitgezonderd 0,01 bij promille? Uitzonderingen mogelijk op basis van de grootte van de indicatoren.

**Comment by karolienbloemen** [comment]
wat de eenheden betreft, werden ook ihkv het dashboard afspraken gemaakt met redactiegroep, deze zijn opgenomen in het [draaiboek dashboard](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/fc948cfe-7c03-4b95-8573-acac1bc26cd2).
Mijn voorkeur is om overal dezelfde afspraken aan te houden:
bv 1.000 (met punt)
euro (voluit)

**Comment by Tine-VB** [comment]
Goeie tip Karolien. Dit zijn de afspraken uit dat draaiboek:
o	De eenheid wordt steeds voluit geschreven, zonder hoofdletters, en geen symbolen.
- percentage (niet: %)
- promille (niet: °/°°)
- per 10.000
- euro (niet: €) 
- 1.000 euro
- ratio
- index
o	Bij percentage, promille… wordt steeds “(t.o.v. noemer)” vermeld.

**Comment by joostschouppe** [comment]
Afspraken Redactiegroep:
- EUR of €  -> €
- 1.000 of 1000 -> 1.000
- '65-... jaar' of '65+' of '65-plus' of '65-plussers': -> 65+ (in naam en 'in t.o.v.', in beschrijving "65 jaar en ouder")
- 18-64-jarigen of 18-64 jaar: voorstel: 
      - altijd "18-64 jaar", behalve bij "t.o.v." indien er geen kenmerk bij staat, dan "18-64-jarigen"
      - begin het onderwerp met het "kenmerk", vb "mannen 18-64 jaar" "vrouwen 18-64 jaar"
- woord "gemiddelde" enkel gebruiken in onderwerpnaam indien nodig voor leesbaarheid (vb "gemiddelde temperatuur" wél, maar gewoon "E-peil appartementen"
- naam van de submappen met allerlei verhoudingen: "percentages" indien alleen percentages, anders "relatieve cijfers" 
- [percentage], [promille], [ratio], [projecties]: vooraan de beschrijving
- standaard afronding op 0,1 bij relatieve cijfers, uitgezonderd 0,01 bij promille. Uitzonderingen mogelijk op basis van de grootte van de indicatoren.
- Bij percentage, promille… wordt steeds “(t.o.v. noemer)” vermeld (ter herhaling, reeds afgesproken)
- kortere versies zijn toegestaan in naam van onderwerp in Databank, omwille van beperkt aantal tekens. In Dashboard wordt alles voluit geschreven omwille van de leesbaarheid
- Tine kijkt ook gebruik mean/ratio na (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/174)
- Tine past gewoon aan voor zover het gewoon om uitvoeren van deze regels gaat.

**Comment by Tine-VB** [comment]
Enkele bijkomende vragen:
* bij meer dan 12 onderwerpen moet er een aparte map zijn voor de percentages. Geldt ook het omgekeerde: bij minder dan 12 onderwerpen MAG ER GEEN APARTE MAP gemaakt worden? Of maakt dat niet uit?
* bij de bevolkingscijfers staat nu bijvoorbeeld als naam:
'50-64 jaar'
'80-... jaar'
'0-2 jaar (t.o.v. inwoners)'
'60-... jaar (t.o.v. inwoners)'
Voor alle duidelijk: maak ik daar dan van
'50-64-jarigen' of 'inwoners 50-64 jaar'
'80+' of '80+ jaar' of 'inwoners 80+' ('80+jarigen' is geen zicht zeker?)
'0-2 jarigen (t.o.v. inwoners)' of 'inwoners 0-2 jaar (t.o.v. inwoners)'
'60+ (t.o.v. inwoners)' of 'inwoners 60+ (t.o.v. inwoners)
Of laat ik het staan zoals het er staat?

**Comment by joostschouppe** [comment]
Redactiegroep:
- vraag 1: "maakt niet uit"
- vraag 2: laat maar staan zoals het stond dan

**Comment by Tine-VB** [comment]
Behalve dan dat ik de -... verander in + uiteraard :-)

**Comment by joostschouppe** [comment]
Eigenlijk was vraag 2 ons niet duidelijk. Nu ik dit aan het aanpassen ben in Basis Swingbeheer snap ik het pas. voor vraag 2 bedoel je dus eigenlijk: "moet ik specifiek in de case bevolking het schrijven als 'leeftijdsgroep in de stijl van leeftijdsgroep zonder duiding' of 'kenmerk met leeftijdsgroep in stijl van leeftijdsgroep met duiding". Euh... ik zou zeggen, leeftijdsgroep zonder duiding zoals het nu staat

**Comment by joostschouppe** [comment]
Dit alles is (nu pas) aangepast in [basis swingbeheer](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/3c11a4a0-4e2d-49d8-8763-20d7c4f4201f#newVersionUpload)
