### ISSUE TITLE
Update en uniformisering data Veiligheid conform website FEDPOL

### ISSUE THREAD

**Issue by Inejacobs** [provinciesincijfers/PinC-taakopvolging#183]
Data voor de 19 onderwerpen die op de website van FEDPOL staan, zijn opgeladen in Swing. Dit voor de jaren 2011-2019.
Ik wacht nog op de detaildata van drugs, misdrijven tegen lichamelijke integriteit en IFG Econ alsook op àlle data van de jaren 2008 tem 2010 die **niet** op de website staan. @ChrisMichelDS jij mag de check al doen voor deze data. Alfresco laat het helaas afweten dus per uitzondering post ik hier de uploadfile en brondata.

Wat is er veranderd: we hebben de 3 niet te lokaliseren gemeenten Noordzee, Eurostar en Airport toegevoegd aan
Noordzee + Airport        >            99991 (Vlaanderen, gemeente onbekend)
Eurostar             >            99992 (Brussel gemeente onbekend)

Daarnaast hebben we alle provincies hard ingelezen en Noordzee bij W-Vla gezet, Airport bij Vla-Br en Eurostar bij 4000 BXL.
De data komen nu overeen met [http://www.stat.policefederale.be/criminaliteitsstatistieken/interactief/tabel-per-hoofdcategorie-misdrijven/]  

[Update VH 2511.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5665115/Update.VH.2511.xlsx)
[20201208_CF en SI update vanaf 2011 via website.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5665116/20201208_CF.en.SI.update.vanaf.2011.via.website.xlsx)

**Comment by joostschouppe** [comment]
@valeriepirard ik denk dat dit nu in orde is. Sluit jij af indien OK?

**Comment by valeriepirard** [comment]
In orde. We krijgen nu jaarlijks de criminaliteitsdata via mail in bulk door. 2020 is opgeladen en gecheckt.
