### ISSUE TITLE
Uitbreiding themaboom ruimte

### ISSUE THREAD

**Issue by valeriepirard** [provinciesincijfers/PinC-taakopvolging#186]
VITO heeft inzake **(toegankelijk) buurtgroen** diverse indicatoren berekend o.b.v. het Landgebruiksbestand (o.a.).
Deze zijn in bulk beschikbaar (ook absolute aantallen) op gemeentelijk niveau. Het gaat om:
•	% van de gemeente die ingenomen wordt door woongroen, buurtgroen en wijkgroen
•	(%) van de inwoners dat binnen een bepaalde afstand van woongroen (150m), buurtgroen (400m) en wijkgroen (800m) woont.
•	(%) van de totale oppervlakte van de gemeente die ingenomen wordt door stadsdeelgroen, stadsgroen en stadsbos.
•	Aandeel (%) van de inwoners dat binnen een bepaalde afstand van (1600m), stadsgroen (3200m) en stadsbos (5000m) woont.
De definities van de groentypologieën zijn hier na te lezen: 
https://gemeente-stadsmonitor.vlaanderen.be/groen-in-de-buurt
https://gemeente-stadsmonitor.vlaanderen.be/groen-in-de-stad-gemeente

De technische fiche beschrijft hoe deze indicatoren tot stand kwamen: https://gemeente-stadsmonitor.vlaanderen.be/sites/gemeente-en-stadsmonitor/files/technische_fiche_groentypes_stadsmonitor_jan2019.pdf

Voorstel: toevoegen in PinC
Meerwaarde: de reeds bestaande indicator in PinC ("groene of onbebouwde ruimte") maakt geen onderscheid tussen toegankelijk groen en niet-toegankelijk groen

**Comment by joostschouppe** [comment]
Opmerking: reeds deels ingeladen in reeks 2504
