### ISSUE TITLE
gebruik van locaties (xy-coördinaten) in themaboom/rapporten

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#189]
gebruik van xy-coördinaten in provincies.incijfers ?

op dit moment halfjaarlijkse update van de laadpalen (voor elektrische voertuigen) ten behoeve van het gemeentelijke klimaatrapport
https://provincies.incijfers.be/jive?workspace_guid=b5f58624-e521-45d1-833d-8f108b3319b9

in de toekomst mogelijks ook de windmolens
(ook in het gemeentelijk klimaatrapport)

zijn er nog andere interessante locatie-gegevens ?
moet er uitbreiding van het maximaal aantal op te laden locaties aan ABF gevraagd worden ?

**Comment by joostschouppe** [comment]
Er is een handleiding beschikbaar: https://swing.eu/handleiding/Objectenmodule/index.html
Je kan verschillende parameters optellen vanuit objecten
Je kan een object aanklikbaar maken en daar dan een mini rapportje over opvragen
Indien de handleiding van ABF niet uitgebreid genoeg is, dan kunnen we hier https://github.com/provinciesincijfers/JiveDocumentation aanvullen

**Comment by miekevanopstal** [comment]
Kinderopvanggegevens zijn zeker ook interessant.
Scholen?

**Comment by joostschouppe** [comment]
We moeten er wel over waken dat we niet te veel Swing gebruiken als GIS toepassing. Het is enkel de moeite om dit extra beheer binnen Swing te doen indien dit een duidelijke meerwaarde geeft. Stefan zag het daarom meer als een uitbreiding voor een rapport en niet voor de themaboom. De interprovinciale databeheerders onderzoeken de mogelijkheden om POI kaarten vanuit andere toepassingen te integreren.
Wie een concrete case heeft, mag gerust bij mij aankloppen om het samen te onderzoeken en uit te werken!
