### ISSUE TITLE
Uitbreiding themaboom Bevolking

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#191]
Kan de gemiddelde leeftijd en eventueel ook mediaan leeftijd toegevoegd worden?

**Comment by joostschouppe** [comment]
Voor gemiddelde leeftijd gewoon "som van alle leeftijden" per statsec nodig
voor mediaan-leeftijd: op welk gebiedsniveaus gewenst?

**Comment by VickyVB** [comment]
We willen vooral de gemiddelde leeftijd. 
De mediaan enkel wanneer er voor het rijksregister al een bestaande routine is die variabelen op elk niveau apart (statsec, wijk, gemeente ,...) berekent en inlaadt.

**Comment by joostschouppe** [comment]
We doen enkel gemiddelde

**Comment by joostschouppe** [comment]
Ik kan hier @rudymarynissen niet assigneren, dus ik heb Lieven er aan gehangen om verder op te volgen.

**Comment by joostschouppe** [comment]
Onderwerpen in de beta ingelezen: 

Indicator   code
--
v1111a_gemiddelde_leeftijd
v1111a_mediaan_leeftijd
v1118a_aantal_nationaliteiten
v1117a_aantal_geb_nat
v1116a_aantal_herk_nat

**Comment by VickyVB** [comment]
Merci, we gaan ermee aan de slag.

**Comment by joostschouppe** [comment]
Goegekeurd en gecontroleerd; @rudymarynissen mag dit extern zetten (Redactiegroep 25/2/2021)
