### ISSUE TITLE
Uitbreiding themaboom Onderwijs - volwassenenonderwijs

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#192]
We willen een dataset van de inschrijvingen in het volwassenenonderwijs (2014-2019) toevoegen met een indeling naar:
-  leeftijdsklasse, 
- geslacht, 
- nationaliteit, 
- onderwijstype 
- (64) leergebieden. 
Dit alles zowel naar vestigingsplaats als naar woonplaats.
Deze gegevens komen van dataloep.

In het opvolgingsdocument is hier nog geen code voor voorzien: gebruiken we 2371 (woonplaats) en 2372 (vestigingsplaats)?

Wie wil controleren?

**Comment by HanneODB-VLBR** [comment]
[Voorstel thema volwassenenonderwijs in PINC.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5830847/Voorstel.thema.volwassenenonderwijs.in.PINC.xlsx)
Hierbij het overzicht van de voorgestelde indicatoren.

**Comment by joostschouppe** [comment]
De code 2371/2372 lijkt logisch. Vul maar aan in [het document](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/5ee48f87-c8a4-4aff-b2b3-dd15a59e9913) om de code te reserveren

**Comment by joostschouppe** [comment]
@HanneODB-VLBR : nog feedback bij het gebruik van de instructiedocumenten die je tijdens deze oefening hebt gebruikt?

**Comment by HanneODB-VLBR** [comment]
@joostschouppe ik heb de feedback bij de issues van de handleidingen zelf geplaatst. Maar ik weet niet zeker of dat de juiste plek was, want ik kan je niet assignen. Alleszins hier:
https://github.com/provinciesincijfers/JiveDocumentation/issues/10#issue-803677807

**Comment by joostschouppe** [comment]
Ha merci, ik volg het daar verder op!
