### ISSUE TITLE
Themaboom Arbeidsmarkt: RSZ kubus

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#193]
De RSZ gegevens (4de kwartaal 2016-2de kwartaal 2019) zijn geleverd . Het betreft hier voor het 2de en 4de kwartaal de volgende gegevens:
- werkplaats (gemeente)
- instelling RSZ/RSZPPO
- NACE 5 digits (_let wel: we mogen op gemeentelijk niveau maar gegevens tot op NACE 3 digits verspreiden_)
- grootteklasse van de vestiging
- geslacht van de werknemer
- type werknemer (ambtenaar, bediende, arbeider)
- arbeidsregime (voltijds, deeltijds, speciaal, disponibiliteit)
- aantal vestigingen
- aantal werknemers

Momenteel ben ik samen met POM Limburg deze eerste levering aan het nakijken. (We vonden al enkele foutjes)
We willen daarna ASAP enkele kubussen toevoegen aan PinC.

Wensen? Bedenkingen? Verzuchtingen?

**Comment by VickyVB** [comment]
2 kubussen zijn ingeladen (2017-2019) en geven voor de werkplaats (gemeente)
- LOONTREKKENDE TEWERKSTELLING kruist nace5 (extern max nace3), vestigingsgrootte (9 klassen), geslacht(m/v) en arbeidsregime (voltijds, deeltijds, speciaal, disponibiliteit) https://provincies.incijfers.be/admin/jive/?var=kubus1403_rsz_eff
- VESTIGINGEN kruist nace5 (extern max nace3) en vestigingsgrootte https://provincies.incijfers.be/admin/jive/?var=kubus1403_rsz_ve 
Op de werkgroep economie van 23/2 wordt bekeken welke platte onderwerpen men hierbij nog wil opnemen in de themaboom en plaatsen we deze kubussen extern. Ook opmerkingen vanuit D&A nog steeds welkom.

**Comment by Lievendr** [comment]
Vicky, alvast heel bruikbaar om voor verankeringsstudie op NACE-5 de beschutte en sociale werkplaatsen in kaart te brengen. Topjob!

**Comment by joostschouppe** [comment]
* lukt het nu om voorbij de 100.000 combinaties te gaan Vicky? (ze kwam op ongeveer 150.000 combinaties uit)
* Bij RSVZ data mogen we maar tot op NACE 2 publiceren. Bij RSZ mag tot NACE 3. In principe kan dat niet, omdat je per kubusdimensieniveau rechten instelt. Je kan dus niet zeggen nace3 mag WEL in die kubus, maar NIET in die andere kubus. MAAR wat we wellicht kunnen is iets maken als nace3_publiek en nace3_afgeschermd. Kubus RSVZ moet dan ingelezen worden op nace3_afgeschermd. Die dimensie kan aggregeren naar nace2. Nace3_publiek aggregeert OOK naar nace2. Om RSZ en RSVZ samen te kunnen zien op nace3 (indien gewenst), moeten we nog een aggregatietabel nace3_publiek NAAR nace3_afgeschermd voorzien (en niet omgekeerd!)
