### ISSUE TITLE
Themarapport Veiligheid 

### ISSUE THREAD

**Issue by mehtap19** [provinciesincijfers/PinC-taakopvolging#194]
In onze themaboom verwijzen we via link naar de dynamische themarapporten. 

Is het mogelijk om het themarapport[ Veiligheid 
](https://provincies.incijfers.be/jive/report/?id=rapport_veiligheid&input_geo=gemeente_41002) op te splitsen? We zouden namelijk graag het onderdeel veiligheid in het verkeer apart onder het thema mobiliteit willen opnemen gezien het gaat om specifieke en gedetailleerde info mbt verkeersongevallen en -slachtoffers. 

Zo kunnen we de betreffende gegevens meer onder de aandacht brengen. 

Thnx

**Comment by joostschouppe** [comment]
Hoi Mehtap,
We gaan dit voorlopig niet doen, omdat het rapport verkeersveiligheid dat op die manier ontstaat te kort zou zijn. Als we naar een rapport mobiliteit zouden gaan, dan kunnen we dit wel weer in overweging nemen.

**Comment by HanneODB-VLBR** [comment]
Graag zou ik dit issue heropenen, omdat verkeersveiligheid intussen wel degelijk in een breder rapport 'mobiliteit' werd opgenomen. Dus in principe kan verkeersveiligheid uit het rapport 'veiligheid' worden gehaald. Hetzelfde geldt voor de themaboom: daar staat verkeersveiligheid nu zowel onder 'veiligheid' als onder 'mobiliteit', onder 'veiligheid' kan het dus in principe verwijderd worden.

**Comment by joostschouppe** [comment]
Dan wordt Veiligheid dus eerder een thema Criminaliteit, juist?

**Comment by Tine-VB** [comment]
Ofwel blijft het thema 'Veiligheid' heten zoals het heet, en komt verkeersveiligheid zowel hieronder als onder mobiliteit te staan. Eventueel kan het dan uit het rapport Veiligheid, dat dan inderdaad hernoemd zou moeten worden naar 'Criminaliteit'.

**Comment by joostschouppe** [comment]
Redactiegroep 16/2/2023:
- voorkeur om het bij het huidige te houden. De leden vragen dit na binnen eigen team.
- mogelijk alternatief: thema Veiligheid wordt Criminaliteit over heel de lijn. Probleem: dit wordt dan nogal mager: voorstel om de tegel dan te laten vallen
Dit issue gaat weer dicht en kan heropend worden als er vanuit de teams een concreet voorstel komt.
