### ISSUE TITLE
Afvalcijfers OVAM

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#196]
Naar aanleiding van de [vraag van centrumsteden](https://github.com/provinciesincijfers/data-wishlist/issues/8) en de interesse vanuit werkgroep klimaat(adaptatie) hebben we contact opgenomen met Wim Raes (Team Onderzoek & Monitoring) van OVAM.

We krijgen data van 2013 tot en met 2019, op gemeentelijk niveau.

-	Restafval
-	Verpakkingsglas
-	Papier en karton
-	Pmd 
-	Metalen gemengd/kroonkurken (excl. pmd)
-	Kunststoffen gemengd/piepschuim (excl. pmd)
-	Gft
-	Groenafval
-	Textiel
-	Bouw- en sloopafval
-	Houtafval
-	Autobanden
-	Vlakglas
-	AEEA
-	Dierlijk afval
-	Geneesmiddelen
-	Kga
-	Plantaardige en dierlijke oliën en vetten
**= Totaal selectief ingezameld afval**

**Totaal restafval**

**EINDTOTAAL huishoudelijk afval**

- Jolien De Boodt (stad Sint-Niklaas) volgt mee op
- vraag om in de connector centrumsteden op te nemen
- beslissen wat we extern zetten

OVAM
- vraag om aparte vermelding in de themaboom te krijgen --> voorstel = voorlopig onder AFVAL, later als er ook RIOLERING bijkomt onder MILIEU > AFVAL
-  vraag om disclaimer op te laten nemen: in de metadatafiche / waarschuwing in de themaboom (cf. K&G) 
- een aantal fracties hebben ze niet op gemeentelijk niveau (autobanden, geneesmiddelen, ...) duidelijk vermelden in de metadatafiche

**Comment by joostschouppe** [comment]
Opmerking tijdens redactiegroep: we zijn benieuwd naar meer metadata om te zien hoe precies omgegaan wordt met data die soms-wel-soms-niet op gemeenteniveeau kan bevraagd worden.

**Comment by StefanJacques** [comment]
data 2013-2019 zijn opgeladen _(volgende upload in december 2021: cijfers loop 2020)_
**beschrijving** van de onderwerpen goedgekeurd door OVAM
**metadatafiche** aangeleverd door OVAM, bekeken door Tine (waarvoor dank) en aanpassingen aanvaard door OVAM
alle onderwerpen komen in de **connector** naar de centrumsteden (@joostschouppe)
alle onderwerpen mogen **extern** geplaatst worden: voorstel voorlopig onder klimaat --> afval

enkele cijfers:
https://provincies.incijfers.be/jive?workspace_guid=9b116faf-8cc6-4b63-93f7-13731a039df7

de metadatafiche:
[v2511_ovam.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/6248571/v2511_ovam.pdf)

**Comment by SofieWVl** [comment]
Interessant! 
2 kleine opmerkingen bij de metadatafiche:
- AEEA bij eerste vermelding ook voluit schrijven (als leek heb ik de afkorting toch even moeten opzoeken)
- onder externe referenties, 1ste regel:  'als ook', moet 'alsook' zijn, vermoed ik

**Comment by veravandestraat** [comment]
Eens met de opmerking van Sofie over AEEA!

Wel confronterend om te zien die hoeveelheid afval per inwoner... Zet maar snel online, dat de mensen zich maar wat bewuster worden van hoeveel afval ze produceren ;)

**Comment by StefanJacques** [comment]
nieuwe cijfers OVAM 2021 staan INTERN (en worden op dit moment gecontroleerd door OVAM zelf en OBMI)

er zijn 2 nieuwe onderwerpen (afvalgroepen) toegevoegd: 
- batterijen
- matrassen

Contactpersoon bij OVAM schreef over de metadatafiche: 
_Ik heb ook even de fiche opnieuw bekeken. Deze is nog actueel. Alleen bij ‘Externe referenties’ heb ik wat wijzigingen aangebracht (zie tracked-changes).
Ter info. De hoeveelheden textiel per gemeente tellen niet op tot het Vlaamse totaal gerapporteerd op onze website. Dit komt omdat wij bijkomende informatie gebruiken om tot betere cijfers te komen op Vlaams niveau. Hetzelfde geldt voor afgedankte batterijen._

Ik heb deze "ter info" mee opgenomen in onze metadatafiche.

**Comment by joostschouppe** [comment]
Redactiegroep 19/2/2023: in orde.
Navragen of Vlaanderen kan toegevoegd worden
