### ISSUE TITLE
Herwerking rapport wonen

### ISSUE THREAD

**Issue by LoreDJ** [provinciesincijfers/PinC-taakopvolging#197]
[Een voorstel tot herwerking van het rapport wonen.](https://docs.google.com/spreadsheets/d/1IDMZfCRio4P2BqbWhB4HzlfxyrE4vUa4_kT9cNvfB28/edit?usp=sharing)

Nagekeken door:
- [x] Antwerpen
- [x] Limburg
- [x] Oost-Vlaanderen
- [x] West-Vlaanderen
- [x] Vlaams-Brabant
(zet een vinkje als je provincie het nagekeken heeft)

**Comment by LoreDJ** [comment]
[voorstel inhoudstafel wonen.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5905004/voorstel.inhoudstafel.wonen.xlsx)

Een voorstel tot herwerking van het rapport wonen.

**Comment by demaesschalckfilip** [comment]
@LoreDJ 
Hier enkele kleine opmerkingen (ik heb een kolom "opmerkingen" toegevoegd).
[voorstel_inhoudstafel_wonen_opm_filip.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5910705/voorstel_inhoudstafel_wonen_opm_filip.xlsx)

**Comment by joostschouppe** [comment]
Ik heb het voorstel in een google drive bestand gezet dat iedereen kan editeren, zodat we hier niet met telkens nieuwe bijlages zitten

**Comment by karolienbloemen** [comment]
Ik voegde enkele suggesties toe in de google drive.

**Comment by joostschouppe** [comment]
Het lijkt me wel nuttig om enkele cijfers uit de EPB data-verwerking toe te voegen. Enkele aspecten:
- waar wordt er nog gebouwd, op lager-dan gemeentelijk niveau. DIt zou eventueel ook op basis van Kadaster kunnen trouwens, wellicht echter met nog wat meer vertraging
- wat voor woningen worden er gebouwd (epb-dossiers naar type woning)
- hoe evolueert de grootte van de nieuwe woningen (naar type)
- hoe evolueert het E-peil
- hoe evolueert het verwacht energieverbruik per woning van de nieuwe woningen
https://provincies.incijfers.be/jive?workspace_guid=17bf2b70-9fa5-495f-9892-6b5c8c3da291

**Comment by joostschouppe** [comment]
Redactiegroep: graag nakijken!

**Comment by demaesschalckfilip** [comment]
Ik vind dat een prima plan, Joost. Misschien is het wel logisch om die variabelen (aantal nieuwbouw, wat voor nieuwbouw - type en grootte) onder het thema wonen te zetten? De laatste twee zou ik niet in het rapport wonen opnemen, omdat dat nogal sterk afhankelijk is van wat door de overheid is vastgelegd.

**Comment by Lievendr** [comment]
Commentaar van Wonen Antwerpen
Deel 1:
1.1: kan ook de bevolkingsdichtheid tov de bebouwde ruimte gegeven worden? Dit staat nu onder het stukje “Ruimte”
1.2: ik zou ook de bevolkingsprognoses aantallen & percentage 0-17 jarigen, 18-64 jarigen en 65+’ers weergeven. Dit toont ook aan wie er in de toekomst moet gehuisvest worden
1.6: is het voor woonstabiliteit mogelijk om een 5 jarig gemiddelde te gebruiken ipv cijfer laatste jaar

Deel 2:
2.1: kunnen er ook cijfers uit het thema ruimte toegevoegd worden: landgebruik/ruimtebeslag/verharding huizen & tuinen? (wel bedenking: hoe zit het met zonevreemde bewoning, opletten dat de cijfers zuiver genoeg zijn)
Voor percentages appartementen, 1-gezinswoningen: kan er ook zicht op de tijdsevoluties gegeven worden?

Bij huurders & eigenaars: kan er ook opgesplitst worden tussen private huurders & sociale huurders? Ik vermoed dat er ook een update komt wanneer het kadaster-rapport af is, waarbij de highlights uit dat rapport weergegeven worden?
Bij sociale huisvesting: kunnen er ook cijfers van het bindend sociaal objectief weergegeven worden (en geïntegreerd worden in PinC).

**Comment by LoreDJ** [comment]
Het rapport is geprogrammeerd door David. Het kan nagelezen worden en dan na goedkeuring gepubliceerd worden.

**Comment by Tine-VB** [comment]
> Het rapport is geprogrammeerd door David. Het kan nagelezen worden en dan na goedkeuring gepubliceerd worden.

Waar kan ik het terugvinden?

**Comment by joostschouppe** [comment]
Volgens het draaiboek zou dit gecommuniceerd moeten geweest zijn met deze testlink: https://provincies.incijfers.be/admin/jive/report/?id=rapport_wonen_nieuw&openinputs=true

**Comment by Lievendr** [comment]
bij opvragen rapport
[*Something went wrong with Function Period, at line 2175 column 112. No period members found *]

**Comment by Lievendr** [comment]
kaart 7 en 10 niet leesbaar bij gemeenten met veel wijken; bij opvraag 2 en meerdere gemeenten;
kaart 8: kapot bij opvraag provincie(s);
grafiek 16 en 17: leeg bij meerdere gemeenten en provincies;

**Comment by StefanJacques** [comment]
![image](https://user-images.githubusercontent.com/31841732/132845733-b123c26e-fab1-4e23-94f4-79aecf60c2cd.png)

klopt de beschrijving in deze grafiek
appartementen, energieverbruik (t.o.v. woningen, laatste 5 jaar) ?

**Comment by LoreDJ** [comment]
Klopt Stefan, ook Tine en ikzelf hadden al opgemerkt dat dit niet klopt. ik vermoed dat het de indicatornaam is die fout is. bij de data zie ik dat Joost hiervoor verantwoordelijk is, maar hij is nu een maand met verlof. Misschien kunnen de controleurs, met name Vlaams-Brabant, dit es checken en aanpassen?

**Comment by karolienbloemen** [comment]
![afbeelding](https://user-images.githubusercontent.com/53050277/132851937-b9d3ee85-c291-4c65-a219-eacd98de699b.png)
Bij een rapport met 2 gemeenten wordt hier het rapport huishoudens opgelijst van Aalst geopend ipv de gekozen gemeenten (bij 1 gemeente werkt het wel correct)

**Comment by Tine-VB** [comment]
> Klopt Stefan, ook Tine en ikzelf hadden al opgemerkt dat dit niet klopt. ik vermoed dat het de indicatornaam is die fout is. bij de data zie ik dat Joost hiervoor verantwoordelijk is, maar hij is nu een maand met verlof. Misschien kunnen de controleurs, met name Vlaams-Brabant, dit es checken en aanpassen?

**Comment by Tine-VB** [comment]
Ik ben een beetje heel erg aan het knoeien in Github, maar @LoreDJ ik wou dus zeggen: ik denk dat er de verkeerde indicator is gekozen in de grafiek, het moet die zijn met t5 achteraan, terwijl er in de tabel gekozen is voor de andere.
![image](https://user-images.githubusercontent.com/61458346/132855961-803f5f8d-3efd-453c-86d5-ae24ef5af162.png)

**Comment by davidcardinaels** [comment]
Ivm opmerking Karolien: dit komt omdat "Cijfers huishoudens opgelijst" enkel voor 1 gemeente opgevraagd kan worden. 
Ik heb het zo aangepast dat er bij meerdere gemeenten, na openen van de link, een keuzescherm komt om een gemeente te kiezen.

**Comment by davidcardinaels** [comment]
Ivm opmerking Tine: indicator vp2207_nbw_prim_app_wng wordt nergens in het rapport gebruikt. Ik had de naam van de t5 zojuist al aangepast obv de opmerking in het document van Lore.

**Comment by davidcardinaels** [comment]
Opmerking [*Something went wrong with Function Period, at line 2175 column 112. No period members found *]: dit is omdat er in die tabel 2 verschillende meest recente periodes zijn. Dit verdwijnt als de nieuwe cijfers er zijn. Als het rapport al eerder gepubliceerd moet worden dan zet ik dit tijdelijk vast op 2020 en dan is de foutmelding ook weg.

**Comment by Tine-VB** [comment]
> Ivm opmerking Tine: indicator vp2207_nbw_prim_app_wng wordt nergens in het rapport gebruikt. Ik had de naam van de t5 zojuist al aangepast obv de opmerking in het document van Lore.

Ha, vandaar, ik ging in de indicatorentabel kijken en zag dat het daar goed stond, maar ik wist niet dat jij het al had aangepast :-). Prima dan.

**Comment by davidcardinaels** [comment]
Opmerking kaart 7 en 10: dit is logisch bij dat soort kaarten, daarom is er ook een zoomfunctie.

**Comment by davidcardinaels** [comment]
Opmerking kaart 8: ook in de databank werkt dit kaartje niet bij opvraag provincie(s). Ik heb de code zo aangepast dat dit kaartje + bijhorende tekst wegvalt bij opvraag provincie(s). Dat lijkt me de enige fatsoenlijke optie.

**Comment by davidcardinaels** [comment]
opmerking grafiek 16 en 17: klopt, dit komt omdat het mediaanprijzen zijn en die mogen niet opgeteld worden. Laat ik hier bij 3 of meer gemeenten/provincies de grafieken wegvallen of zetten we hier beter een opmerking bij?

**Comment by Lievendr** [comment]
@David: kaart 7 en 10. Misschien bij vermelden dat kan ingezoomd worden als taarten overlappen? ik had alvast die reflex niet.
grafiek 16 en 17: klopt inderdaad dat mediaanprijzen niet kunnen berekend worden. ik zou dat dan ook melden in de stijl van bijvoorbeeld " U vroeg 3 gemeenten op waarvan we de mediaan niet kunnen berekenen" en grafiek niet tonen. Of kan een tabel met de gemeenten en de mediaanprijzen van het recentste jaar?

**Comment by davidcardinaels** [comment]
Ik heb de meldingen toegevoegd. Een tabel heb ik niet in de plaats gezet aangezien er tot 300 gemeenten geselecteerd kunnen worden.

**Comment by LoreDJ** [comment]
alle opmerkingen zijn verwerkt, waarvoor dank David.
Het rapport mag online gezet worden, kijk jij hiervoor David? 

Aan Oost-Vlaanderen: ik hoor dat jullie de volgende nieuwsbrief opmaken, het nieuwe rapport kan daar dan in opgenomen worden, indien op tijd gepubliceerd. :-)

**Comment by davidcardinaels** [comment]
Het rapport staat online.

**Comment by LoreDJ** [comment]
Dankjewel!
