### ISSUE TITLE
Zichtbaarheid metadata

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#199]
In de meeste gevallen kan je in de Databank (ook) op de bron klikken om de metadatafiche te krijgen.
![afbeelding](https://user-images.githubusercontent.com/10122639/106297699-46871e80-6253-11eb-988c-f3a4b10f590f.png)

Indien er meerdere bronnen zijn, dan bundelen we die in een HTML bestandje, zodat je kunt doorklikken naar de juiste. Niet erg handig; en in de toekomst gaan we dat anders doen.

Maar dus nu waren nog niet alle bronnen aanklikbaar. Ik heb alvast van alle bronnen die nog niet aanklikbaar waren nagegaan of er slechts één pdf bij hoorde. Waar dat het geval was, heb ik die aangevuld. 

Voor de andere bronnen zou er dus een HTML tussen moeten zitten om die te bundelen. Hier alvast het lijstje van bronnen met bijhorende metadatafiches:

Data source code | fiches
-- | --
ksz_webtoepassing | v1201_KSZ_webtoepassing_SEP.pdf,v1201_tewerkstelling_herkomst.pdf
statbel_fisc_ink | v1203_fiscale_inkomens_statbel.pdf,v1203_bpa0_hypothecair.pdf
kadaster | v2203_verkoop_onroerend_goed.pdf,v2201_gebouwenpark.pdf
vazg_sociale_bescherming | v3504_zorgbudget_zwaarzorgbeh.pdf,v3502_zorgbu_ou.pdf,v3402_zorgbudget_pmeh.pdf
landgebruiksbestand | v1591_landgebruik.pdf
ruimteboekhouding | v4001_ruimteboekhoudingRSV_landbouw.pdf,v4001_ruimteboekhouding.pdf
rsvz | v1205_rsvz_zelfstandigen.pdf,v1403_activiteiten_nace.pdf
vdab | v1300_vdab.pdf,v1350_schoolverlaters.pdf
dg_pmeh | v3502_thab.pdf,v3401_DGPH_it_ivt.pdf,v3401_DGPH_erkenning_parka.pdf
fluvius | v2502_premies.pdf,v2504_openbare_verlichting.pdf
rsz | v1204_rsz.pdf,v1403_activiteiten_nace.pdf
bodemafdekkingskaart | v1592_verharding.pdf
rsz_rsvz | v1403_activiteiten_nace.pdf
rva | v1321_werkloosheidsdruk.pdf,v1207_tijdelijkewerkloosheid.pdf

Dat moet dus in een html (copy paste van de html's hier https://provincies.incijfers.be/Admin/Studio/File?type=info). De naam van de html (gewoon [broncode].html) moet vervolgens bij [DataSource](https://provincies.incijfers.be/Admin/Studio/Table?tableName=DataSource) in het veld More Information ingevuld worden.

**Comment by davidcardinaels** [comment]
Dit is in orde. Ik heb geen v1350_schoolverlaters.pdf gevonden dus iemand zou dat bestand misschien opnieuw moeten inladen?
Er zijn ook 28 onderwerpen gekoppeld aan die v1350_schoolverlaters.pdf. Joost, weet jij wie de verantwoordelijke is?

**Comment by joostschouppe** [comment]
David, als je een onderwerp van de reeks 1350 opvraagt in de admin, dan zie je bij vrij tekstveld VB_OV staan. In de praktijk @VickyVB . Vicky - je metadatafiche voor de reeks 1350 is verdwenen of van naam veranderd!
