### ISSUE TITLE
Opkuis standaardstijlen van grafieken

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#20]
Dit is het deel "achter het oogje". 

Werkbestand:
https://docs.google.com/document/d/1fZx0oM3WqNUuiHpgUu469cieXX0uBzwZuoPn1Kd9kDQ/edit#

Sjabloon/handleiding:
https://provincies.incijfers.be/admin/jive/Report/Edit/sjabloon_grafiekstijl
- oplijsten afspraken
- alles naar generieke instellingen
- voorbeelden van het voorstel dat we willen
- in een afzonderlijk document: voorbeelden om bepaalde keuzes te illustreren

Opmerking: De keuzes die hier gemaakt kunnen worden, zijn NIET documenteerbaar binnen de code. Er bestaat ook GEEN codeboek van welke code wat doet.

**Comment by joostschouppe** [comment]
Zie ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/10

**Comment by StefanJacques** [comment]
https://docs.google.com/document/d/1fZx0oM3WqNUuiHpgUu469cieXX0uBzwZuoPn1Kd9kDQ/edit#

**Comment by joostschouppe** [comment]
Aanpassing nav redactiegroep:
ABF aandringen > schaalverdeling z-scores ook in legenda

voorlopig uitrollen indien het interactief kan

z-score provincie of vlaanderen?
> gebaseerd op user input

vergelijkingsgebieden met stippellijnen

labelkleurtjes

tabel niet gedrongen
andere kleuren bij kleurentabel

Standaard GEEN gebroken assen. Wanneer dit toch nuttig is, maak gebruik van LayoutClass: "gebroken_as"; 
> + expliciet in de tekst zetten!

Standaard werken met index

hoogte 450

layout bronnen van tabellen heel anders dan van grafieken

**Comment by VickyVB** [comment]
De vergelijkingsgebieden gingen we niet met stippellijnen doen. Stippellijnen zijn voor prognoses en worden daarenboven onduidelijk bij meer jaren, en puntmarkers en figuren van max 400 breed.

**Comment by VickyVB** [comment]
Wat is de breedte van een figuur wanneer je niet voor 2 kolommen indeling gaat? 800?

**Comment by StefanJacques** [comment]
in het [rapport ](https://provincies.incijfers.be/admin/jive/Report/Edit/sjabloon_grafiekstijl) staat:

- We gebruiken volgende standaardmaten voor grafieken: **breedte**: 400 (of 750) en **hoogte**: 450
- LayoutClass: **liggende_staaf** (zie bij "5. Afwijken van de standaardbreedte")

nog doen @joostschouppe : titel van niveau 3 (1.1.1) groter maken

**Comment by VickyVB** [comment]
niveau 3 dat is dus de <h5>

**Comment by joostschouppe** [comment]
Voorstel: meeting met de mensen die al rapporten hebben ontwikkeld rond:
- evaluatie van huidig gebruik
- lacunes
- schrappen / eenvoudiger model?
