### ISSUE TITLE
Check Brussel in rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#201]
Er is geen alternatief voor "Brussel moet selecteerbaar zijn in rapporten".
Maar werkt het altijd goed?
Controleer of alles goed gaat indien je énkel een Brusselse gemeente hebt gekozen, én Brussel+een Vlaamse gemeente
Lijst de problemen hier op en dan lossen we ze samen in bulk op

| rapportcode   | verantwoordelijke  | gewenst | status |
|---|---|---|---|
|omgevingsanalyse_steekkaart | Stefan | niets tonen | done |
|rapport_demografie | Filip | voor Brussel niets tonen | done |
|rapport_natioherkomst | Lore | voor Brussel niets tonen  | done |
|rapport_detailhandel | Joost | Brussel OK of af te vangen | done |
|rapport_onderwijs | Vicky | geen aanpassing nodig | / |
|rapport_wonen | West-Vlaanderen |  aanpassing nodig, zie onder | done |
|rapport_klimaat  | Stefan | voor Brussel niets tonen  | done |
|rapport_veiligheid | Ine | aanpassingen nodig, zie onder  | done |
|rapport_armoede | Tine | aanpassingen nodig: zie hieronder | done |
|rapport_ouderenzorg | Karolien | aanpassingen nodig: zie onder | done |
|rapport_bgz | Koen | geen aanpassing nodig | /  |
|rapport_landbouw | Lieven (in opmaak!) | voor brussel niets tonen | done |
|rapport_elz | Hilde | geen aanpassing nodig | / |
|||
|||
|steekkaart_demografie | Stefan (UITDOVEND) |
|steekkaart_economie | Vicky | geen aanpassing nodig (uitdovend?) | / |
|tabellenrapport_bevolking | Stefan | voor brussel niets tonen | done |
|tabellenrapport_klimaat | Stefan | voor brussel niets tonen  | done |
|tabellenrapport_huishoudens | Stefan | voor brussel niets tonen | done |
|tabellenrapport_diversiteit | Lore | / | /  |
|rapport_economie (tabellen) | Vicky | opm in de tekst toevoegen? | done |

**Comment by StefanJacques** [comment]
RAPPORT KLIMAAT vermeldt in de leeswijzer bij opvragen van een Brusselse gemeente:
_Je koos een combinatie met Brussel of een Brusselse gemeente. Omdat deze website wordt beheerd door de Vlaamse provincies, beschikken we niet over alle informatie om dit rapport op te vullen._

**opvragen 2 gemeenten**
Als je Vlaamse gemeente + Brusselse opvraagt, krijg je ook die tekst, e worden alle gemeentegrafieken getoond voor de Vlaamse gemeente en krijg je een lege grafiek voor de Brusselse.
Ik zou er precies voor kiezen om ook dit rapport NIET MOGELIJK TE MAKEN.

**opvragen meerdere gemeenten met 1 gemeente uit Brussel**
hier gaat het ook fout: je beseft als lezer niet dat in de meeste grafieken de Brusselse gemeente niet in de optelsom zit van de data + de kaartjes tonen enkel het BHG

![image](https://user-images.githubusercontent.com/31841732/107024607-8b0d3f80-67a8-11eb-95f1-70b54fe6138a.png)

Conclusie lijkt me: maak opvragen van rapport Klimaat onmogelijk als er een Brusselse gemeente wordt opgevraagd ?

**Comment by StefanJacques** [comment]
opvragen 1 Brusselse gemeente of combinatie met een Brusselse gemeente

**NIET TONEN in rapport kerncijfers**
- bevolking
- huishoudens
- arbeidsmarkt (gedeelte NWWZ)
- wonen (gedeelte kadaster & RR)
- klimaat
- landbouw (onderwerpen 1 en 5)
- criminaliteit
- veiligheid (onderwerpen 1, 8 tot 10)
- armoede: laatste twee onderwerpen
- zorgaanbod

**cijfers bevolking opgelijst
cijfers huishoudens opgelijst
cijfers klimaat opgelijst**
deze tabellenrapporten NIET TONEN en melden:
**Je koos een combinatie met Brussel of een Brusselse gemeente. Omdat deze website wordt beheerd door de Vlaamse provincies, beschikken we niet over informatie om dit rapport op te vullen.**

**Comment by joostschouppe** [comment]
Ouderenzorg: samenvattende grafiek gaat de mist in als je BXL en een andere "provincie" vergelijkt:
(dus wellicht gaat er nog wel meer mis)
![afbeelding](https://user-images.githubusercontent.com/10122639/107387433-1b26ee00-6af5-11eb-8014-af31309d8394.png)

**Comment by Inejacobs** [comment]
Bij het rapport Veiligheid situeren zich de problemen enkel omdat er geen BXL gemeenten in het rijksregister zitten dus bij de grafieken en tabellen per 1000 inwoners. Die komen voor doorheen het hele rapport bij vrijwel elk type misdrijf.

**Comment by Inejacobs** [comment]
Rapport ouderen: Mantelzorg tabel bij vergelijken van 2 gemeenten waaronder 1 Brusselse
![image](https://user-images.githubusercontent.com/57390456/107495935-fed88f00-6b90-11eb-89e2-251fa13ebe39.png)

**Comment by Inejacobs** [comment]
Idem bij vergelijken van 2 prov
![image](https://user-images.githubusercontent.com/57390456/107496074-2a5b7980-6b91-11eb-80b6-b4530301aca6.png)

**Comment by Inejacobs** [comment]
Eveneens uit het rapport ouderen:
![image](https://user-images.githubusercontent.com/57390456/107496139-3e9f7680-6b91-11eb-9597-225b2b041f91.png)

**Comment by joostschouppe** [comment]
Vraag:
Kijk voor jouw rapport na of het uberhaupt zinvol is om te tonen voor Brussel. Indien WEL, zijn er problemen die opgelost worden, zo ja, welke?

**Comment by ChrisMichelDS** [comment]
Voor rapporten BGZ en ELZ is voor de keuze brussel / bruzel (elz) een
scenario ingebouwd en een combinatie van deze met een andere gemeente/elz
is niet mogelijk.

Op di 16 feb. 2021 om 10:49 schreef Joost <notifications@github.com>:

**Comment by VickyVB** [comment]
- Het **rapport Onderwijs** is OK zo (we hebben cijfers voor Brussel).
- Voor het **rapport Bevolking en huishoudens** wordt er niets getoond wanneer je enkel een Brusselse gemeente kiest (OK). Wanneer je echter een Vlaamse en Brusselse gemeente kiest, krijg je net als bij het rapport Klimaat telkens lege grafieken voor de Brusselse gemeente. Ook hier misschien beter helemaal niets tonen. Dit moet dus nog aangepast worden.
- **Steekkaart Economie** heeft geen aanpassing nodig. Deze gaat er op korte termijn ook uit.
- **Cijfers economie opgelijst** heeft wel een heel aantal missings. Ik zou dit wel tonen, maar misschien wel een opmerking in de inleiding toevoegen.

**Comment by Tine-VB** [comment]
Bij het rapport armoede
* staat het Brussels Hoofdstedelijk Gewest steeds dubbel in tabellen en in grafieken: 
![image](https://user-images.githubusercontent.com/61458346/108723755-e79c8880-7524-11eb-9e1b-c7d57fde89c7.png)
![image](https://user-images.githubusercontent.com/61458346/108723856-fd11b280-7524-11eb-8f08-1a994a86c3b5.png)
* Bij keuze voor de 'provincie' Brussels Hoofdstedelijk Gewest staat het er telkens twee keer, maar daarvan is 1 keer het vergelijkingsgebied en dat kan ik niet uitzetten.
* wordt er niets gegeven voor 2.1 Gezinstypes, 2.2 herkomst en 2.6 Werkloosheidsgraad. Bij 2.3 Betalingsmoeilijkheden ontbreken gegevens over betalingsproblemen met elektriciteit. 
* is er geen noemer in Tabel 10: kandidaat-huurders (t.o.v. particuliere huishoudens). Kandidaat-huurders per domiciliegemeente is wel ingevuld.

VOORSTEL: aanpassen van dubbele cijfers voor Brussels Hoofdstedelijk Gewest. Rapport behouden voor Brusselse gemeenten, maar bij hoofdstukken (of grafieken) die wegvallen zinnetje zetten: 'deze cijfers zijn niet beschikbaar voor Brussel'. Als er een combinatie wordt gekozen met een Vlaamse gemeente, dan zou ik hetzelfde doen. Ik zou dus die tabellen en grafieken niet tonen met enkel de Vlaamse gemeente.

PS het viel me op dat bij keuze voor Anderlecht en Aarschot, ik automatisch het vergelijkingsgebied kreeg van de 'Centrale gemeenten, zeer goed uitgerust'. Ik kan dat niet uitzetten bij vergelijkingsgebieden.

**Comment by StefanieWVL** [comment]
Voor rapport wonen:

![image](https://user-images.githubusercontent.com/50832281/110486143-a8596480-80ec-11eb-845f-198c5fd180e6.png)

Hier mag komen: Voor Brussel beschikken we niet over een eigen dataset met Rijksregistergegevens. Deze hebben we nog om de kadastergegevens te kunnen verrijken en zo het aantal huurders en eigenaars te berekenen. Daarom blijft dit hoofdstuk verder leeg.

**Comment by StefanieWVL** [comment]
Voor rapport wonen: 

![image](https://user-images.githubusercontent.com/50832281/110486495-fd957600-80ec-11eb-9596-0707458b88e5.png)

De vier onderste indicatoren zouden uit de grafiek moeten verdwijnen.

**Comment by StefanieWVL** [comment]
Voor rapport wonen met keuzen Vlaamse+Brusselse gemeente

- Hier worden wel de grafieken getoond voor de Vlaamse gemeente in de hoofdstukken "inwoners en huishoudens", "eigenaars/huurders" en "sociale huisvesting" maar zonder de grafieken voor Brussel. In het rapport waar je enkel een Brusselse gemeente selecteert blijven deze 3 hoofdstukken leeg (zie supra).
- je kan geen vergelijkingsgebied selecteren. Kies je als bijkomende gemeente Aalst dan wordt er automatisch vergeleken met "Centrale gemeenten; grote of regionale stad". Kies je voor Aalter dan wordt er vergeleken met: "Andere gemeenten; buiten stadsgewest; zeer goed uitgerust"
- ook hier zijn de laatste 4 indicatoren voor de samenvattende grafiek niet ingevuld

**Comment by joostschouppe** [comment]
Twee algemene problemen gedetecteerd door Tine:
* staat het Brussels Hoofdstedelijk Gewest steeds dubbel in tabellen en in grafieken:
* Bij keuze voor de 'provincie' Brussels Hoofdstedelijk Gewest staat het er telkens twee keer, maar daarvan is 1 keer het vergelijkingsgebied en dat kan ik niet uitzetten.
Voorstel: niet aanpassen (sop-kolen afweging)

**Comment by joostschouppe** [comment]
We zetten dit op de lijst van "kleine dingen om misschien op termijn in het sjabloon te verbeteren"

**Comment by joostschouppe** [comment]
Rapport Detailhandel:
Was grotendeels in orde, _Handelsaanbod per 1.000 inwoners_ en _Samenvattende grafiek_ nog aangepast

**Comment by joostschouppe** [comment]
Aanpassingen wonen:
- samenvattende grafiek (bolstaaf) anders ingevuld naar gelang situatie
- "inwoners en huishoudens": was reeds in orde voor "enkel brussel", nu ook voor "combinatie met Brussel"
- huurders/eigenaars en sociale huisvesting aangepast

**Comment by Emilien-Dupont** [comment]
Aanpassingen armoede:
- 2.1 Gezinstypes aangepast
- 2.2 Herkomst aangepast
- 2.3 Betalingsmoeilijkheden elektriciteit aangepast
- 2.4 kandidaat huurders tov particuliere huishoudens wordt niet getoond wanneer (combi met) brussel
- 2.6 werkloosheid aangepast
- samenvattende grafiek aangepast naargelang situatie

**Comment by Emilien-Dupont** [comment]
Aanpassingen Ouderenzorg en Veiligheid:
- het hele rapport vervalt wanneer (combinatie met) Brussel

**Comment by Emilien-Dupont** [comment]
Aanpassing Rapport Economie: waarschuwing wanneer je een brusselse gemeente kiest.

**Comment by joostschouppe** [comment]
Luik 1 leek me eerst vrij eenvoudig technisch op te lossen (zie https://provincies.incijfers.be/admin/jive/Report/Edit/test_brussel) , maar dat werkt blijkbaar niet. Ik vraag na bij Edward.
Luik 2 is toegevoegd aan https://github.com/provinciesincijfers/PinC-taakopvolging/issues/328

**Comment by joostschouppe** [comment]
Redactiegroep ivm luik 1: maak een intern gebied beschikbaar in rapporten dat Brussel+Vlaanderen optelt

**Comment by joostschouppe** [comment]
Gebiedsniveau "België" is toegevoegd als "only selectable in reports" 
![afbeelding](https://user-images.githubusercontent.com/10122639/211274709-2de69a07-2e9b-4605-a409-c5a50baab7e1.png)

Daarmee kan je nu wel de gewenste tabel zien (zie onder), maar die verschijnt nog niet standaard. Ik heb het ingeschoten bij Edward.
![afbeelding](https://user-images.githubusercontent.com/10122639/211276443-ab6a5361-0d1a-4d74-a13d-1ac6d1fc4c1b.png)
