### ISSUE TITLE
procedure inladen nieuwe data

### ISSUE THREAD

**Issue by Lievendr** [provinciesincijfers/PinC-taakopvolging#203]
Gebruiken we eerst standaard de beta-versie om recentste data up te daten ?

**Pro**: 
1. we vermijden dat toch al iets gepubliceerd wordt, vooraleer het gecontroleerd is;  want in verleden al (vaak) gebeurt dat een controleur om allerlei redenen afwezig is, de data toch al meegenomen zijn bij publicatie…
2. een extra zelfcontrole voor inputter om zelf eigen fouten te verbeteren.

**Contra**: 
Standaard naar beta is gewoon veel meer werk voor wie de data inleest, en er kunnen ook weer nieuwe fouten ontstaan op die manier.

Beter scenario? 
Afspraak met controleur maken vooraleer een bestaand onderwerp actualiseert.  Je stemt af met de controleur; zodat dit snel na opladen kan gecontroleerd worden. Als dat niet lukt, dan kan er eventueel van de beta gebruik gemaakt worden; of kan je het eindjaar manueel aanpassen. 
Vraag is of dit niet te ver afstaat van de realiteit: word je niet pas verwittigt als de cijfers er al op staan?

Standpunt Joost
In theorie hebben we de beta gewoon ter beschikking voor als het nodig is; met name complexere gevallen. Als je zegt “ik kan het niet snel nakijken, dus als je het nu al wil inladen, doe het dan in de beta”, dan lijkt me dat wel OK. Maar het is niet zo dat we standaard alles eerst nog eens in de beta moeten doen.

**Comment by joostschouppe** [comment]
Op termijn: automatiseren van data-validatie kan bij updates veel problemen vermijden
Voorstel: *bel* met controleur om af te stemmen wanneer de controle kan gebeuren. Inlader kan dan kiezen om gewone later te gebruiken of de beta-versie te gebruiken.

**Comment by joostschouppe** [comment]
Aangepast in procedure elkaar controleren
