### ISSUE TITLE
Afwijkende bronnen betreffende 31/12/X

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#208]
Drie bronnen hebben volgens [de inventarisatie](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/170#issuecomment-743185885) bij de bron de datum 31/12/X en staan bij ons op jaar X. Wat dus tegen onze afspraken ingaat.
* Criminaliteit: informatie verkeerd ingevuld, dit is een LOOP, geen SNAPSHOT. Dit staat wel juist in de indicatoren
* Fluvius/VEA - PV-installaties
* IMA-preventie

@StefanieWVL, @SofieWVl en @StefanJacques : dubbelchecken jullie of de info correct is, en zetten jullie recht / geven jullie aan of dit rechtgezet kan worden?

**Comment by SofieWVl** [comment]
IMA: inventarisatie aangepast, is loop van het jaar data

**Comment by joostschouppe** [comment]
@StefanJacques bekijk jij nog eens die PC installaties en sluit je af indien OK?
