### ISSUE TITLE
Themaboom leeftijdscategorieën onder nationaliteit en herkomst en positie in huishouden

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#209]
Afstemmen detail per leeftijdscategorie tussen de verschillende mappen: huidige nationaliteit (detail van 0-24 jaar), geboortenationaliteit (detail voor 18-64 jaar en voor 0-24 jaar) en herkomst (detail voor 0-24 jaar). 
Bij positie in huishouden: waarom alleen opsplitsing van de alleenwonenden voor 18-64 en 75+?

**Comment by joostschouppe** [comment]
Mogelijkheden:
- alles qua leeftijd weg (kan niet echt want de herkomst 0-24 jaar staat in kerncijfers - overigens énkel in kerncijfers)
- overal 0-24 én 18-64 jaar
- overal een leeftijdsdekkende indeling, liefst zonder overlap?

**Comment by Tine-VB** [comment]
Rudy gaf al aan dat die tweede laatste niet kunnen bij herkomst, omdat er teveel onzekerheid is bij oudere leeftijdsgroepen. Bij 0-24 is er veel kans dat de kinderen nog bij de ouders wonen, en dus weet je wie dat zijn.

**Comment by joostschouppe** [comment]
Vraag Redactiegroep, voor de leeftijden:
- 0-24 jaar hebben we omdat dit een subset is waarvoor bijna de hele geschiedenis van hoge kwaliteit is (wat betreft herkomst in het bijzonder). 
- 18-64 jaar hebben we op vraag van Limburg (denken we), maar wordt nergens anders in de themaboom gebruikt, en staat ook niet in rapporten
voorstel: 18-64 jarigen INTERN zetten. Het kan nog steeds berekend worden via de kubussen

Voor gezpos: als ik de vraag goed begrijp is dat "waarom staan de 65-74 jarigen hier niet tussen" in het stuk van de themaboom Bevolking>inwoners naar gezinspositie? Dat is bij deze opgelost; dit onderwerp bestond al voor het deel rond HUISHOUDENS.

**Comment by joostschouppe** [comment]
18-64 jarigen onzichtbaar gezet op die plaats
