### ISSUE TITLE
gebruik BTW-data

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#210]
Bij landbouw worden cijfers gebruikt van de btw-aangiften, tot op provinciaal niveau. Op werkgroep landbouw van Statistiek Vlaanderen is nu het volgende naar boven gekomen:
"sedert enkele jaren bestaat immers de mogelijkheid dat ondernemingen die 1 geheel vormen op fiscaal vlak een gezamenlijke BTW-aangifte indienen (ipv elk apart). Dit zorg voor administratieve vereenvoudiging vanuit de kant van de onderneming maar zorgt voor extra problemen inzake het toewijzen van de BTW-data aan een bepaalde onderneming om zo de geografische dimensie te bepalen. Wat bijvoorbeeld met een onderneming die deels in Vlaanderen ligt en deels in Wallonië en die samen een aangifte indienen als BTW-eenheid. Het ventileren van de cijfers naar provinciaal niveau maakt dit probleem alleen maar groter. Vanuit de NBB en de FOD Economie heeft men hiervoor een werkgroep opgericht om dit probleem statistisch aan te pakken. "

De vraag is dus: **worden er in PinC nog andere btw-cijfers gebruikt? En is het interessant om aan te sluiten of verdere informatie op te vragen bij deze werkgroep van NBB / FOD Economie?** 

Voor de huidige gegevens in PinC bij landbouw zullen we alvast de metadatafiche moeten aanpassen.

**Comment by HanneODB-VLBR** [comment]
Voor de data inzake fiscale statistieken hebben we alleszins geen BTW-cijfers opgevraagd. Ik zie wel dat de FOD economie in de statistieken die ze zelf publiceert obv BTW-aangiften, toch een onderscheid maakt tussen provincies (https://bestat.statbel.fgov.be/bestat/crosstable.xhtml?view=da0898ae-e335-4b3c-b147-c7029abc861a). In de metadatafiche hierbij (https://statbel.fgov.be/sites/default/files/files/metadata/T8.STAT_DTST_822.CTAC_ORG_1.DIFF_LVL_1.NL.pdf) zie ik ook niet meteen iets staan over mogelijke 'cross-regionale' aangiften en hoe daar dan mee wordt omgegaan...

**Comment by Tine-VB** [comment]
Vandaar waarschijnlijk dat ze er nu een werkgroep rond hebben opgericht :-)

**Comment by joostschouppe** [comment]
Vraag redactiegroep: gebruikt er nog iemand data met als bron BTW-aangiften? Want dan moet de metadata aangepast

**Comment by joostschouppe** [comment]
Er is niemand die deze data gebruikt.
@VickyVB ben jij geïnteresseerd om dit verder op te volgen, of eventueel de werkgroep economie? Anders sluit je deze maar af.

**Comment by VickyVB** [comment]
Vanuit mezelf/de WG economie is er niet direct interesse in deze cijfers/werkgroep. Mijn voorstel is dus enkel de bewuste infofiche bij Landbouw aan te passen.
