### ISSUE TITLE
dashboard toerisme

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#211]
het thema toerisme is volop in ontwikkeling, zo ook het bijhorende [dashboard](https://provincies.incijfers.be/dashadmin/preview/dashboard/toerisme). 
Graag eventuele feedback op deze voorzet.
Specifiek voor dit dashboard werd reeds het vergelijkingsgebied toeristische regio toegevoegd.
Hierbij nog de vraag of het in orde is om ook het keuzegebied toeristische regio (enkel in dit dashboard toerisme) mogelijk te maken (enkel dan kunnen de tegels overnachtingen naar herkomst opgenomen worden).

**Comment by Tine-VB** [comment]
Kleine opmerking bij de indicatoren: het woordje 'Aantal' moet nog weg uit de beschrijvingen van overnachtingen en aankomsten. En een suuuuuuuuper klein detail nog bij de lengte van het recreatief fietsnetwerk: (_in_ km)
Bij de detailview van dit aantal km en aantal knooppunten is een grafiek met vergelijking van de gemeente en de provincie niet echt de beste keuze... Maar ik weet niet direct een andere optie... Moeilijk om dit relatief te zetten.

**Comment by KoenSnyers** [comment]
@Tine-VB 

Het woordje 'Aantal' bij overnachtingen en aankomsten (bij mouse over) moet verwijderd worden in de databank (daar kan ik in het dashboard niks aan veranderen). @karolienbloemen, pas jij dat aan?

Bij lengte fietsroutenetwerk heb ik er 'in kilometer' van gemaakt. Wat de detailview betreft: vergelijking tussen twee gebieden van verschillend niveau heeft in een visuele grafiek inderdaad geen zin, maar in het dashboard kunnen we sinds vorig jaar niet meer aanpassen per detailview welke presentatievormen getoond moeten worden (standaard toont Mosaic alle mogelijke presentatievormen voor de geselecteerde cijfers).

**Comment by karolienbloemen** [comment]
beschrijvingen zijn aangepast.

**Comment by joostschouppe** [comment]
Opmerkingen redactiegroep:
Waarom niet:
- absoluut aantal overnachtingen gekozen gebied
EN
- relatief aantal overnachtingen gekozen gebied samen met vergelijkingsgebied
Of indien relatieve cijfers niet kunnen, eventueel een soort index?

Absoluut aantal overnachtingen op kaart best NIET met chloropleth kaartje; eventueel "bol in kaart"
Waarom geen detail over de herkomst van de gasten /  types logies?

**Comment by KoenSnyers** [comment]
Voor de toeristische sector is de evolutie van het aantal overnachtingen en aankomsten van belang, niet een relatief cijfer. Vandaar dat er ook geen relatief cijfer van overnachtingen en aankomsten in de databank.
Wil men een index van de evolutie, dan kan dat in de databank. Een evolutie-index wordt nergens anders in het dashboard toegepast.

Het aantal overnachtingen op kaart is inderdaad beter met een bol per gebied. Ik wist niet dat dit opnieuw mogelijk was in het dashboard. Wel dus, ik heb het zo aangepast.

Er zit een detail over de overnachtingen naar herkomst in het dashboard, alleen verschijnt dit alleen als je bovenaan provincie of toeristische regio (dit laatste zodra dit mogelijk is) als gebied kiest.
Overnachtingen naar logiestype vinden de mensen uit de toeristische sector niet relevant om in het dashboard op te nemen.
