### ISSUE TITLE
rapport gebiedsafbakeningen vaccinatiecentra

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#213]
[Gebiedsafbakening vaccinatiecentra](https://provincies.incijfers.be/admin/jive/Report/Edit/vaccinatiecentra) in opmaak, voorlopig enkel via admin.
Hier worden nog enkele tabbladen/links aan toegevoegd, bv naar volgende cijfers van gemeenten uit het gebied, uit [bevolkingskubus ](https://provincies.incijfers.be/jive?workspace_guid=95f8e566-1fab-429b-b529-6d9765bf67ea) en [verhoogde tegemoetkomingen](https://provincies.incijfers.be/jive?workspace_guid=777c91b7-7ba6-4782-a31e-7764e8921748).

Suggesties zijn welkom.
Wanneer klaar, kan de link misschien toegevoegd in het 'toelichtingsdocument' van Tine?
Is het daarnaast mogelijk en wenselijk om vanuit bovenstaande pagina naar dit 'toelichtingsdocument' te verwijzen?

**Comment by Tine-VB** [comment]
Opgelet: Antwerpen wordt opgesplitst.

**Comment by Tine-VB** [comment]
Als voorbereiding: 
* leeftijdsgroep 85+ toevoegen aan de map Geslacht en leeftijd / Leeftijd / Alternatieve leeftijdsindelingen / Ouderen
* in de bevolkingskubussen bij leeftijd een niveau extra creëren met de leeftijdsgroepen 0-17, 18-64, 65-84, 85+. Eventueel wordt de leeftijdsgroep van de volwassen bevolking nog verder opgesplitst, ik heb een mail gestuurd naar VIVEL om te vragen of er na de 65-plusser nog 'naar beneden' zal worden gewerkt per leeftijdsklasse (bijvoorbeeld na de 65-plussers dan de 55-plussers aan de beurt zullen komen).
* het zou ook handig zijn bij type huishouden de indeling alleenwonend, collectief huishouden en 'alle anderen' te kunnen kiezen.

Voorstel basistabellen op statistisch sectorniveau
* Leeftijd&Huishouden: op basis van de kubus "bevolking naar leeftijd, geslacht, positie in huishouden, type huishouden": bevolking naar leeftijd (zie klassen hierboven) en naar gezinspositie, dus alleenwonend, collectief huishouden, alle andere huishoudens (of verdere indeling als deze samenvoeging niet mogelijk/wenselijk is in de kubus). Ik zou hier enkel excl. wachtregister nemen. 
* Herkomst: op basis van de kubus "bevolking naar herkomst, ltf, gesl, wachtregister, nationaliteit": bevolking naar herkomstnationaliteit in 14 landengroepen, opsplitsing wachtregister ja/nee.
* Verhoogde tegemoetkoming: (zoals al eerder opgemaakt) https://provincies.incijfers.be/jive?workspace_guid=bb9c9822-59da-424e-8e7d-aa40d9c48056

Maar... zie mail, ik weet niet of het zin heeft om dan nog verder te werken? We kunnen ze ook gewoon leren om met de databank te werken. Punt. ???

**Comment by karolienbloemen** [comment]
Aangezien het framewerk voor de vaccinatieregio's intussen klaarstaat, zou ik het ook aanbieden. Wie dat wenst of nodig heeft, kan dan toch vlot ook cijfers voor die individuele gebieden opvragen.

Best wel dan bovenaan op de pagina vermelden: 
De cijfertabellen openen zich voor gemeenten horende tot het vaccinatiecentrum/de vaccinatieregio(?), en kunnen binnen de databank ook opgevraagd worden tot het kleinschaligere niveau statistische sector, of op het ruimere gebiedsniveau eerstelijnszone. (+ kort zeggen hoe)

Verder bouwend op het voorstel van Tine: 
- 1 tabel voor leeftijd/huishouden (waarom hier zonder wachtregister?), [voorbeeld](https://provincies.incijfers.be/jive?workspace_guid=378a66eb-886e-4f62-829c-755e92be9c32)
- 1 voor herkomst, [voorbeeld](https://provincies.incijfers.be/jive?workspace_guid=4ff5575d-d603-47b2-9921-d387dae015b1)
- 1 voor VT, [voorbeeld ](https://provincies.incijfers.be/jive?workspace_guid=50b15838-d16c-4fbd-8ecd-a3db6ac5ba0e)

Ik zou de tabellen wel openen op het niveau gemeente ipv statistische sector, dan blijft het overzichtelijk wat wordt opgevraagd. (we willen ze ook niet platgooien met cijfers).

**Comment by joostschouppe** [comment]
Ik zou het ook afwerken, maar enkel verspreiden via Vivel en directe contacten

**Comment by Tine-VB** [comment]
Vivel/VAZG zijn er net niet voor te vinden om het te verspreiden....


> Ik zou de tabellen wel openen op het niveau gemeente ipv statistische sector, dan blijft het overzichtelijk wat wordt opgevraagd. (we willen ze ook niet platgooien met cijfers).

De vraag was expliciet om gegevens op niveau statistische sector te voorzien. Ook op het overleg waar ik die korte presentatie heb gegeven is dat nog eens duidelijk herhaald door enkele populatiemanagers. Dat vinden ze net de grote meerwaarde aan wat wij bieden. Uiteraard willen we ze niet overdonderen met cijfers. Ik vind het daarom nog altijd het belangrijkste dat we ze leren opzoeken in de databank, vooral in de kubussen, zodat ze gericht kunnen gaan kijken naar de bevolking in hun regio (bijvoorbeeld welke herkomstnationaliteiten zijn er, in detail). Het is de bedoeling dat ze dit eerst in kaart brengen en dan (zelf)organisaties, brugfiguren enz. gaan aanspreken om te proberen de vaccinatiebereidheid bij 'moeilijke' doelgroepen te verhogen. 

> * 1 tabel voor leeftijd/huishouden (waarom hier zonder wachtregister?),

Zonder wachtregister: als je dit wachtregister er bij neemt en je hebt een asielcentrum in je gebied, dan wordt het aantal in een collectief huishouden daar wel erg groot. Ik probeer hier te denken vanuit het perspectief en de taak van de populatiemanagers. De mensen in een asielcentrum zullen sowieso wel op een andere manier benaderd worden om de vaccinatiegraad daar te verhogen. Voor de tweede tabel vind ik het misschien wel interessant om ze mee te nemen, omdat je daar expliciet gaat kijken welke herkomstnationaliteiten aanwezig zijn. Als je dan bijvoorbeeld een organisatie of brugfiguur van die herkomstgroep gaat aanspreken, is het ook interessant om te weten welke nationaliteiten er vooral in het asielcentrum aanwezig zijn. Maar dit is sowieso een nogal variabele groep natuurlijk, dus eigenlijk kan je ze er hier ook uitlaten. Dus conclusie: eerder bij beide eruit laten dan bij beide erin.

> * leeftijdsgroep 85+ toevoegen aan de map Geslacht en leeftijd / Leeftijd / Alternatieve leeftijdsindelingen / Ouderen
> * in de bevolkingskubussen bij leeftijd een niveau extra creëren met de leeftijdsgroepen 0-17, 18-64, 65-84, 85+. Eventueel wordt de leeftijdsgroep van de volwassen bevolking nog verder opgesplitst, ik heb een mail gestuurd naar VIVEL om te vragen of er na de 65-plusser nog 'naar beneden' zal worden gewerkt per leeftijdsklasse (bijvoorbeeld na de 65-plussers dan de 55-plussers aan de beurt zullen komen).
> * het zou ook handig zijn bij type huishouden de indeling alleenwonend, collectief huishouden en 'alle anderen' te kunnen kiezen.

Als we het de populatiemanagers gemakkelijk willen maken, dan lijken mij dit aanpassingen die we voor hen kunnen doen. In mijn ogen belangrijker dan de basisrapporten die we zouden klaarzetten. Rudy gaf mij al aan dat hij momenteel geen tijd heeft om hier mee bezig te zijn. Iemand die dit ziet zitten? @VickyVB @StefanJacques ?

**Comment by joostschouppe** [comment]
Voor verspreiding, gebruik enkel deze URL: https://provincies.incijfers.be/databank?report=vaccinatiecentra
De presentaties worden in dezelfde pagina geopend, waardoor het tabblad met dit rapportje behouden blijft.
Het rapport kerncijfers wordt wel in een nieuw tabblad geopend.

**Comment by Lievendr** [comment]
Misschien hier niet op zijn plaats, maar waar dan wel? KNAP WERK!

**Comment by Tine-VB** [comment]
Het document dat kort weergeeft aan de populatiemanagers hoe ze met PinC aan de slag kunnen, vinden jullie op Alfresco: https://share.vlaamsbrabant.be/share/s/DvX5JWNASVeFGTxdH1EQ-Q.

**Comment by joostschouppe** [comment]
Volgens mij is dit afgerond. Heropen gerust als er nog issues zouden zijn.
