### ISSUE TITLE
Nut van het gebruik van datatype pending?

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#214]
Stefan had al aangegeven dat er in het dashboard detailviews mogelijk werden die niet zouden mogen indien bij relatieve cijfers gekozen werd voor pending. Hij heeft toen een hele reeks indicatoren op stock gezet in plaats van pending (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/133). - Ik wist dit niet, dus ik heb bij het controleren van de indicatorentabel een hele reeks van deze variabelen terug op pending gezet. En heb dat achteraf dan weer terug rechtgezet, op basis van de lijst die Stefan had opgemaakt. -
Ondertussen hebben we er ook al voor gekozen om bij relatieve cijfers waarbij de noemer een stock-indicator is, ook van het relatief cijfer een stock-indicator te maken.
Nu blijkt nog dat je geen stock-indicator en pending-indicator samen in een staafdiagram kan zetten. En verder dat je, wanneer je jaartallen zou willen optellen, dat je dan het gemiddelde van die jaartallen krijgt bij pending, in plaats van de som.

Mijn vraag is dus: heeft het zin om die pending nog te gebruiken? Is het niet eenvoudiger om overal stock te zetten? Of heeft het toch nog bepaalde voordelen / eigenschappen om het wel te doen? Heeft ABF ergens gedocumenteerd wat de gevolgen zijn van een keuze voor het ene of het andere? Of is dat iets wat we proefondervindelijk moeten vaststellen?

**Comment by joostschouppe** [comment]
> Nu blijkt nog dat je geen stock-indicator en pending-indicator samen in een staafdiagram kan zetten. 

Kan je een voorbeeld geven? Want [dat lijkt toch wél te kunnen](https://provincies.incijfers.be/jive?workspace_guid=baa41843-fb13-4c52-b3d4-6e990fe0e985)? Hoe dan ook zijn dit soort beperkingen bedoeld om mensen "tegen zichzelf te beschermen" wat betreft weergaves die niet zinvol zijn. Mij lijkt het dan interessanter om aan ABF te vragen die beperkingen aan te passen, eerder dan de metadata bewust fout te maken.

> En verder dat je, wanneer je jaartallen zou willen optellen, dat je dan het gemiddelde van die jaartallen krijgt bij pending, in plaats van de som.

Dat lijkt me logisch: als je op 1 januari 2021 100 mensen hebt, en op 1 januari 2022 120 mensen, dan is de som van die jaren toch zeker niet 220! Daarentegen als je 100 verhuisbewegingen hebt in 2021 en 120 verhuisbewegingen in 2022, dan heb je effectief 220 verhuisbewegingen in heel die periode.

**Comment by Tine-VB** [comment]
@demaesschalckfilip of @VickyVB jullie hadden zo'n voorbeeld van staafdiagram?

> Dat lijkt me logisch: als je op 1 januari 2021 100 mensen hebt, en op 1 januari 2022 120 mensen, dan is de som van die jaren toch zeker niet 220! Daarentegen als je 100 verhuisbewegingen hebt in 2021 en 120 verhuisbewegingen in 2022, dan heb je effectief 220 verhuisbewegingen in heel die periode.
@demaesschalckfilip : jij dacht dat het net andersom was? Want zo lijkt het inderdaad wel heeeeeeel logisch :-)

**Comment by joostschouppe** [comment]
Concreet voorbeeld: deze grafiek was opgenomen in rapport Landbouw:

![afbeelding](https://user-images.githubusercontent.com/10122639/113697819-02415000-96d4-11eb-891e-fc2419535491.png)

Maar dat kan nu niet meer, omdat de BTW-gegevens als een loop zijn aangegeven en de gegevens ivm omzet als een stand. Je kan nog altijd grafieken maken, maar niet meer deze. Test zelf:
https://provincies.incijfers.be/jive?workspace_guid=8ba7f6bf-e375-4841-9135-79f0057cf487

Opties;
- alles is stand, loop zetten we enkel in de metadatafiche en niet als eigenschap van het onderwerp
- we vragen aan ABF om toch stapelstaven mogelijk te maken
- we gebruiken een ander grafiektype
- we maken een of andere uitzondering om de BTW cijfers toch als stand te definiëren

**Comment by Tine-VB** [comment]
Er zijn nog 122 indicatoren die een percentage zijn en toch als type pending hebben meegekregen (vooral over loop van de bevolking). Ik zal deze alvast vervangen.

**Comment by joostschouppe** [comment]
Te bespreken op redactiegroep: voorstel **we zeggen: het is enkel lopend/pending indien je de cijfers zinvol kunt optellen over meerdere jaren (dit sluit ook percentages uit, wat positief is)**

**Comment by joostschouppe** [comment]
De redactiegroepleden kijken na of dit voorstel van regel voor "hun" data de keuze vergemakkelijkt

**Comment by StefanJacques** [comment]
Voor de **indicatoren Limburg** heb ik ook nog voor deze "gemiddelden" het periodetype op "Stock" gezet:
vp2501_emissie_phh | CO₂-emissie door huishoudens (t.o.v.   huishoudens)
vp1209_dc_uur_gebruik | gepresteerde uren dienstencheques per gebruiker
vp1209_dc_uur_65p_gem | gepresteerde uren dienstencheques per gebruiker 65+ jaar
vp1209_dc_uur_80p_gem | gepresteerde uren dienstencheques per gebruiker 80+ jaar
vp1209_dc_uur_25_64_gem | gepresteerde uren dienstencheques per gebruiker 25-64 jaar
vp1209_dc_uur_0_24_gem | gepresteerde uren dienstencheques per gebruiker 0-24 jaar
v2511_restafval_doelstelling | (doelstelling 2022) huishoudelijk restafval per inwoner

[pending_Limburg.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/6403279/pending_Limburg.xlsx)

**Comment by veravandestraat** [comment]
Ik heb de **indicatoren voor Oost-Vlaanderen** nagekeken en ik zie geen problemen. De enige twee onderwerpen waar ik over twijfel zijn uitdovend, dus ik weet niet of daar eventueel nog een aanpassing voor nodig is.
Het gaat om:
- v3132_gebtot_ku geboorten kind en gezin (gemiddelde over 3 jaar)
- v3132_gebka_ku geboorten in kansarme gezinnen (gemiddelde over 3 jaar)

**Comment by VickyVB** [comment]
De indicatoren van Vlaams-Brabant zijn nagekeken en zeer minimaal aangepast.

**Comment by StefanieWVL** [comment]
idem voor WVL
