### ISSUE TITLE
Titels huishoudenstypes in kubussen

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#215]
Graag aan de types huishoudens telkens 'lid van' toevoegen, om duidelijk te maken dat het niet over een aantal gaat per type huishouden, maar dat het gaat om de bevolking die woont in een bepaald type huishouden.
https://provincies.incijfers.be/jive?workspace_guid=116dd61b-5a92-4bf0-9246-06a744698820

**Comment by joostschouppe** [comment]
Nu aangepast naar "gezinslid van ... "
Mogelijk alternatief gewoon "lid van ..."
Voorstel om stukje "(+ mogelijk inwonende ander)" te laten vallen, eventueel wel in de Beschrijving laten staan

**Comment by rudymarynissen** [comment]
Is aangepast zoals hierboven gevraagd, maar ben het niet eens met het verplaatsen van '+ mogelijk inwonende andere personen' naar de beschrijving die enkel verschijnt bij 'mouseover'. Het betreft een niet onaanzienlijk aantal personen/gezinnen. Zie: 
[https://provincies.incijfers.be/jive?workspace_guid=8ce8282f-5df0-4e6c-ae4e-49bbed0ba022].

**Comment by Tine-VB** [comment]
De beschrijving wordt maar zelden bekeken, dus eens met Rudy.

**Comment by joostschouppe** [comment]
Het is zo afgesproken in de redactiegroep; als je dat opnieuw wil agenderen kan je dit ticket heropenen.
