### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#217]
dkdkdlskdkdkdkdkdk
**vet**
* test test
*

**Comment by NiekePeeters** [comment]
test

**Comment by rudymarynissen** [comment]
Mooi issue!

**Comment by NiekePeeters** [comment]
Kunnen we dit issue afsluiten collega's?

**Comment by Emilien-Dupont** [comment]
niet relevant

**Comment by Emilien-Dupont** [comment]
#212

**Comment by NiekePeeters** [comment]
@joostschouppe  kunnen we een issue ook definitief verwijderen?
Of enkel via close dichtdoen?

**Comment by joostschouppe** [comment]
Dat doet me hier denken aan https://www.reddit.com/r/pics/comments/92dd8/test_post_please_ignore/ , wat ooit de hoogst genoteerde post was op Reddit.

Maar goed. Euh, je kan misschien beter testen in JiveDocumentation ofzo, waar er geen twintig mensen potentieel ingeschreven zijn e-mail meldingen? :D

En nope, een Issue permanent deleten is niet vanzelfsprekend. Dit issue gaat de zoekfunctie van de tracker permanent vervuilen, tenzij iemand dit eens doorploegt: https://docs.github.com/en/github/managing-your-work-on-github/deleting-an-issue

**Comment by Emilien-Dupont** [comment]
Sorry, ging per abuis. Had het issue aangemaakt om eens te tonen en mijn hand zei 'klik' en mijn hoofd zei 'neeeeeee'.
