### ISSUE TITLE
link naar rapport nationaliteit en herkomst ontbreekt in rapport ELZ

### ISSUE THREAD

**Issue by StefanieWVL** [provinciesincijfers/PinC-taakopvolging#221]

**Comment by StefanieWVL** [comment]
Dit is ondertussen in orde (link toegevoegd). Ook nog 2 kleine schrijffoutjes er uit gehaald. 
Maar **nog een kleinigheid** bij de samenvattende grafiek: er staat in de tekst "in tabel 21" terwijl dit tabel 20 moet zijn. Ik dacht, easy peasy, pas ik gauw even aan maar blijkbaar zit hier een "code" (lijn 3928). Ik zie het niet ... Kan iemand dit aanpassen? (en mij uitleggen hoe het moet?)

**Comment by joostschouppe** [comment]
Wat er in het rapport gebeurt, is dat de telling van de tabellen automatisch gebeurt. Op die manier blijft de nummering altijd chronologisch, ongeacht of hoofdstukken automatisch wegvallen, ongeacht of je je hele rapport van volgorde verandert. Telkens je onderstaande code gebruikt, wordt gekeken naar "wat is het nummer van de vorige keer dat ik deze code zag, en voeg er eentje aan toe". 

`<div class="teller_tabel">tekst in de titel</div>`

In de tekst kan je helaas niet verwijzen naar "het nummer van de onderstaande tabel" maar moet je zorgen dat je op dezelfde manier telt als voor de tabellen zelf. Je moet dus zorgen dat je OFWEL alle tabellen vermeldt met nummer in de tekst met deze code:

`<span class="teller_tabeltekst" style="text-transform: capitalize;"></span>`

OFWEL, als je dat niet doet, kan je hetzelfde doen, maar dan onzichtbaar (opacity=ondoorzichtbaarheid=0):

`<span class="teller_tabeltekst" style="opacity: 0;"></span>`

Dat moet hier ergens misgelopen zijn. Rond regel 3813 waren er enkele "dummy tellers" gedefinieerd, en blijkbaar eentje te veel. Ik heb er eentje weggelaten, en nu lijkt het OK te zijn.
