### ISSUE TITLE
Cijfers woonpremies Wonen Vlaanderen

### ISSUE THREAD

**Issue by SofieWVl** [provinciesincijfers/PinC-taakopvolging#224]
Na meerdere overlegmomenten tussen Hilde en Wonen Vlaanderen, en in het licht van het vernieuwde rapport Wonen dat in opmaak is, hebben we een aantal cijfers rond **woonpremies** klaar staan om gepubliceerd te worden:

**Huursubsidie**: aantal aanvragen, aantal goedkeuringen, aantal weigeringen, bedrag
**Renovatiepremie**: aantal aanvragen, aantal goedkeuringen, aantal weigeringen, bedrag
**Vlaamse Aanpassingspremie:** aantal aanvragen, aantal goedkeuringen, aantal weigeringen, bedrag
**Vlaamse Verzekering Gewaarborgd Wonen:** aantal aanvragen, aantal goedkeuringen, aantal weigeringen

Is data op gemeenteniveau en vanaf 2015 tot 2019. In juni verwachten we de cijfers 2020.

We wachten nog op de finale "go" van Wonen Vlaanderen (op de metadatafiche) en het akkoord van de redactiegroepsleden.
De reeksen kunnen in PinC geraadpleegd worden via: admin only\Wonen\Premies
Tine is al eens door de  data en metadatafiche gegaan.

In juni zouden we de indicatorenlijst nog willen aanvullen met:
- reden aanvraag huursubsidie
- weigeringsgrond huursubsidie
En eens de datasets verder aangezuiverd zijn voegen we ook nog de huurpremiecijfers toe.

De opmerkingen van Tine rond de naamgeving en metadata zijn intussen [ingepast ](https://provincies.incijfers.be/jive?workspace_guid=2588fe6b-54aa-4376-b5b6-401ec4d99144)

**Comment by Tine-VB** [comment]
Ik keek enkel de metadatafiche na :-), dus nog een bijkomende opmerking:
De bedragen, dat is telkens het totaalbedrag dat werd uitgekeerd in de loop van het jaar? Dat zou ik dan ook duidelijker vermelden. Als indicatornaam zou ik dan nemen: totaal uitgekeerd bedrag VAP, totaal uitgekeerd bedrag aan huurpremies… Ook in de beschrijving en in de metadata nog best aanvullen. Kan er ook telkens een gemiddeld bedrag afgeleid worden uit het aantal premies en het totaal bedrag? Dat is dan eigenlijk ook nuttig om als indicator toe te voegen.

De percentages goedkeuringen heb je ondertussen verwijderd? Ik had nog een paar opmerkingen op de beschrijvingen klaar staan :-). Ik kijk ook nog de cijfers na.

**Comment by karolienbloemen** [comment]
Mooi! Fijn dat deze cijfers beschikbaar komen.
Ik heb een inhoudelijke vraag: de renovatiepremie kon gedurende een aantal jaren in twee aanvragen worden aangevraagd (inmiddels is dit een uitdovend systeem en kan je terug maar 1x aanvragen): hoe is dit in de cijfers opgenomen? Worden in die periode de eerste en tweede aanvraag afzonderlijk meegeteld in het aantal aanvragen (dus mogelijks 2 per woning) of toch als 1 aanvraag? En wat met het bedrag? 
Zoals Tine aangeeft: gemiddeld bedrag is ook interessant (indien mogelijk, rekening houdend met bovenstaande bij berekening).

**Comment by SofieWVl** [comment]
> De bedragen, dat is telkens het totaalbedrag dat werd uitgekeerd in de loop van het jaar? Dat zou ik dan ook duidelijker vermelden. Als indicatornaam zou ik dan nemen: totaal uitgekeerd bedrag VAP, totaal uitgekeerd bedrag aan huurpremies… Ook in de beschrijving en in de metadata nog best aanvullen._  
 **-> Klopt, is het totale premiebedrag uitbetaald in de loop van het jaar. Ik pas het aan naar je voorstel zodat dat duidelijker is.** 
_Kan er ook telkens een gemiddeld bedrag afgeleid worden uit het aantal premies en het totaal bedrag? Dat is dan eigenlijk ook nuttig om als indicator toe te voegen._
 -**>Door de beperkingen van de data kunnen we (nog) geen goede gemiddelde indicatoren opnemen**
_> De percentages goedkeuringen heb je ondertussen verwijderd? Ik had nog een paar opmerkingen op de beschrijvingen klaar staan :-). Ik kijk ook nog de cijfers na._
 **-> Klopt, de slaagpercentages zijn door Wonen Vlaanderen niet gefiatteerd. Deze percentages hadden we in Swing berekend** (goedkeuringen van jaar x / goedkeuringen + weigeringen van jaar x *100)  **Het leek hen niet wenselijk deze op te nemen, doordat goedkeuringen en weigeringen telkens over dossiers gaan die zowel in het gerapporteerde jaar als in voorgaande jaren gestart kunnen zijn.  Dezelfde opmerking geldt voor berekening van gemiddelden.**

**Comment by SofieWVl** [comment]
@karolienbloemen : ik heb jouw vraag over hoe de renovatiepremiecijfers meegeteld worden in het systeem met 2 aanvragen ingestuurd bij Wonen Vlaanderen. Als daar duidelijkheid over is, laat ik het hier weten.

**Comment by SofieWVl** [comment]
@karolienbloemen:  de aanvragen in het oude premiestelsel (2015-feb 2019) worden als 2 aanvragen meegeteld. De bedragen worden geteld bij het jaar van uitbetalen, dus in de praktijk zal deze bedragen ook in verschillende jaren in de cijfers zitten.

We hebben het finale fiat van Wonen-Vlaanderen en zullen dus publiceren.
