### ISSUE TITLE
Nieuwe open data rond wonen

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#226]
Nieuwe of uitgebreide open data over dit thema:
*  [huurcontracten](https://www.geo.be/catalog/details/84d5f470-51ca-11eb-8a67-3448ed25ad7c?l=nl)
* [verkoopsprijzen](https://www.geo.be/catalog/details/89209670-51ca-11eb-beeb-3448ed25ad7c?l=nl)
* [kadastraal inkomen](https://www.geo.be/catalog/details/8894f840-51ca-11eb-bfa6-3448ed25ad7c?l=nl)

[Overzicht](https://www.geo.be/catalogs/1/resources?l=nl&sort=changedate&hitsperpage=12&from=1&serviceview=no&servicedownload=no&servicediscovery=no&servicetransformation=no&dataset=yes&series=no&papermap=no)

Iets voor @karolienbloemen , @SofieWVl , @HildeC , @StefanieWVL ?

**Comment by Emilien-Dupont** [comment]
@Lievendr polst bij Rudy

**Comment by Lievendr** [comment]
de gegevens waarvan sprake zijn te oppervlakkig en vooral onvolledig volgens Rudy.
