### ISSUE TITLE
naamgeving rapporten in admin PinC

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#23]
Structureren van de rapportcode opdat dit wat overzichtelijk blijft: vb sjabloon_, rapport_, demo_, vb_, test_
Dit documenteren in afsprakenbestand rapporten

**Comment by joostschouppe** [comment]
Toegevoegd aan https://github.com/provinciesincijfers/PinC-taakopvolging/issues/27
