### ISSUE TITLE
Aanpassing rapport buurtgerichte zorg

### ISSUE THREAD

**Issue by LoreDJ** [provinciesincijfers/PinC-taakopvolging#230]
Er zouden 2 dingen moeten aangepast worden in het rapport Buurtgerichte zorg die nu niet kloppen.

- het eerste gaat over de seskenmerken bij lln. omschrijving van indicatorleerlingen is nu dat dat leerlingen zijn die scoren op 1 van de 3 kenmerken, maar dat klopt niet helemaal: enkel de kenmerken schooltoelage en laagopgeleide moeder zijn hier van belang, thuistaal dus niet. dat zal aangepast moeten worden in de tekst.

- een tweede foutje gaat over de kenmerken in het secundair onderwijs: nu zijn de aandelen voor gans het secundair, terwijl er gesproken wordt over het **gewoon** onderwijs. daar moeten dus andere indicatoren (enkel voor het gewoon onderwijs) geselecteerd worden.

**Comment by HildeC** [comment]
aanpassing voor eerste fout:
laatste zin paragraaf 2 moet worden: wanneer een leerling scoort op het kenmerk 'schooltoelage' en/of 'laaggeschoolde moeder', dan spreekt men van een indicatorleerling.
zin boven de tabel moet worden: in gemeente XXXX zijn er  XXX% indicatorleerlingen.

**Comment by LoreDJ** [comment]
Wat betreft de tweede aanpassing:
* _basisonderwijs_:
- cijfers en beschrijvende tekst kloppen. 
- In de titel van tabel 21 zou wel nog moeten duidelijk gemaakt worden dat het gaat over gewoon onderwijs, dus dat wordt dan: SES-kenmerken **gewoon** basisonderwijs, % t.o.v. alle leerlingen **G**BO, naar woonplaats (2019)
- de indicatoren in tabel 21: daar zou ook moeten bij staan dat het gewoon onderwijs is en dat de noemer GBO is. Dat is ook niet duidelijk in de huidige themaboom, daar wordt nergens de vermelding gemaakt dat dit cijfers zijn voor het gewoon onderwijs.

* _secundair onderwijs_:
- tekst is ok
- titel van tabel 22 moet worden: SES-kenmerken **gewoon voltijds** secundair onderwijs, % t.o.v. alle leerlingen GVSO, naar woonplaats (2019)
- wat betreft de gebruikte indicatoren: nu zijn niet die indicatoren gebruikt die gaan over het **gewoon voltijds sec ond** zoals de tekst vermeldt. in de themaboom heb je eerst de algemene cijfers en daarna een extra luik over het gewoon voltijds secundair onderwijs. wat is hier precies het verschil tussen? seskenmerken zijn toch alleen maar beschikbaar voor het gewoon onderwijs? is het verschil dan het voltijds regime? opnieuw is dit hier niet duidelijk in de namen van de indicatoren in de themaboom en wordt dit best verduidelijkt/aangepast.
- concreet betekent dit voor tabel 22 dat volgende indicatoren vervangen moeten worden:
- vp2301_gvso_rkopleidingmoeder_1 in plaats van vp2301_so_rkopleidingmoeder_1
- vp2301_gvso_rktoelage_1 in plaats van vp2301_so_rktoelage_1
- vp 2301_gvso_rktaal_1 in plaats van vp 2301_so_rktaal_1

@VickyVB : ik heb jou hier toegevoegd omdat jij verantwoordelijk bent voor de onderwijsdata :-)

**Comment by davidcardinaels** [comment]
Alle aanpassingen aan de code zijn in orde. De benaming van de noemers wordt automatisch aangepast wanneer dit aangepast wordt in de indicatorentabel.

Moet het percentage leerlingen die thuis geen Nederlands spreken nog getoond worden in de tekst en tabel aangezien enkel de andere 2 kenmerken van belang zijn?

**Comment by LoreDJ** [comment]
Ja, ik zou ook de kolom met leerlingen die thuis geen Nederlands spreken laten staan.
In het begin van het hoofdstuk wordt verteld over de SES kenmerken bij leerlingen, daar hoort ook de thuistaal bij.

Dus in de tekst moet dit wel nog aangevuld worden:
"Op basis van wetenschappelijk onderzoek is gezocht naar een set van stabiele en robuuste indicatoren die de samenhang van onderwijskansen voor jongeren en hun sociaal milieu goed vatten. **Het betreft lage opleiding van de moeder, schooltoelage en thuistaal niet Nederlands.** Deze informatie is enkel beschikbaar voor de leerlingen in het gewoon onderwijs.

**Comment by davidcardinaels** [comment]
Tekst is aangepast!
