### ISSUE TITLE
Vlaamse gemeentelijke demografische vooruitzichten 2021-2040

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#232]
ter kennisgeving
geplande nieuwe upload van de cijfers op
https://statistieken.vlaanderen.be/QvAJAXZfc/notoolbar.htm?document=SVR%2FSV-Demografie-ProjectiesBevolking-20180226.qvw&host=QVS%40cwv100154&anonymous=true

VRAAG / SUGGESTIE
er wordt ingezoomd op een **"nieuwe" leeftijdscategorie: 67-plussers**
https://www.statistiekvlaanderen.be/nl/bevolkingsvooruitzichten-67-plussers

Nemen wij deze leeftijdsgroep ook mee op in provincies.incijfers ?

**Comment by Lievendr** [comment]
is dat niet de nieuwe pensioenleeftijd in 2026?

**Comment by veravandestraat** [comment]
Ik vond het inderdaad raar dat ze bij de presentatie niks gezegd hebben over waarom ze voor de categorie 67-plussers gegaan zijn!

**Comment by joostschouppe** [comment]
Lijkt me goed, maar moeten dan andere leeftijdsindelingen ook aangepast?

**Comment by StefanJacques** [comment]
@joostschouppe 

bij de huishoudensprojecties (v1123_a) bestaan deze onderwerpen NIET meer in de nieuwe versie:
v1123_a_4pers
v1123_a_5pers_p
en de relatieve cijfers
vp1123_a_4pers
vp1123_a_5pers_p

NIEUW in de plaats
**huishoudens met 4 personen en meer**
v1123_a_4pers_p en vp1123_a_4pers_p

gevolgen voor de connector ?

**Comment by joostschouppe** [comment]
Zie https://github.com/provinciesincijfers/JiveDocumentation/blob/master/01.%20Algemeen%20databeheer/Levensloop%20onderwerpen.md#databeheer-pinc voor de onderwerpen die verdwijnen. De nieuwe onderwerpen mogen hier: 
![afbeelding](https://user-images.githubusercontent.com/10122639/120605513-6b341280-c44e-11eb-9d9d-798d52807a49.png)

**Comment by joostschouppe** [comment]
Staat klaar voor publicatie en voor de connector
