### ISSUE TITLE
leefloon PODMI en/of KSZ

### ISSUE THREAD

**Issue by Lievendr** [provinciesincijfers/PinC-taakopvolging#233]
ik ben de leeflooncijfers aan het verzamelen bij PODMI. er zijn nog onvolledigheden die ik dien op te vragen.
Doen we hier met verder of beperken we ons tot data uit KSZ? De twee bronnen geven twee verschillende resultaten. 
1. PODMI gaat over het jaar zelf, KSZ over het vorige jaar...
2. PODMI maakt onderscheid tussen leefloon en equivalent leefloon
3. PODMI wordt berekend op maandgemiddelde en opgedeeld naar geslacht leeftijd en huishoudtype
4. PODMI-cijfers zijn referentie in de sector
5. PODMI: wij berekenen via maandgemiddelden...zijn anders dan jaargemiddelde die ook op website staan...
....

https://provincies.incijfers.be/jive?workspace_guid=60aefdc6-535e-4655-ab1e-72c82ce7d747

**Comment by joostschouppe** [comment]
Leefloon staat 2 keer op PinC en er zitten grote verschillen op de aantallen. Vicky geeft aan dat dit ook 2 verschillende dingen zijn. KSZ is om op lager dan gemeenteniveau te gaan en ook de nomenclatuur is toegevoegd aan deze data.  

Wij werken met maandgemiddelden, anderen met jaargemiddelde. Onze aanpak is goed maar misschien moeten we ook inspelen op die jaargemiddelden. Het staat wel uitgelegd in de metadatafiches maar mensen lezen die nog steeds te weinig.  

Vicky raadt aan om de PODMI data te gebruiken.  

Ook opnieuw het issue dat wij een ‘ander’ jaartal gebruiken soms dan de originele bron (het K&G probleem). Voorstel dat we dat toch telkens verduidelijken in voetnoten.  

Ondertussen:
- de cijfers zijn inmiddels ingeladen
- ook de relatieve cijfers inmiddels in orde
