### ISSUE TITLE
Bron-info duidelijker in rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#235]
Hoe kunnen we in Rapporten de metadatafiches meer in de verf zetten? Enkele opties:
- nog meer toelichting over de bronnen, en in die toelichting een link naar de fiche zetten
- een afsluitend hoofdstukje met een overzicht van de gebruikte bronnen
- in de leeswijzer vermelden dat je in tabellen kunt doorklikken, en anders via "open in jive" + 'klik op de bron' de fiche kunt opvragen
- nog iets anders?

**Comment by StefanieWVL** [comment]
Een afsluitend hoofdtukje met overzicht van bronnen waar je kan doorlinken lijkt me het meest zichtbaar, netjes en beknopt (geen bijkomende tekst voor de lezer voor wie dit niet boeit). Leeswijzer is al vrij lang, daar zal de boodschap mss verloren gaan? Idem voor eerste voorstel: nog meer toelichting over bronnen. 
Nog iets anders? Daar moet ik nog eens over nadenken ;-)

**Comment by joostschouppe** [comment]
Gerelateerd: best ook metadatafiches toevoegen in themaboom (zie redactiegroep juni)

**Comment by joostschouppe** [comment]
Voorbeeld aangemaakt in sjabloon_rapport_vertrekproject, uit te rollen naar alle rapporten

**Comment by Emilien-Dupont** [comment]
Onder bronnen: als je hier klikt vind je info over .... 
en dan linken naar metadata opsommen
uit te werken

**Comment by davidcardinaels** [comment]
Hoofdstukje bronnenoverzicht is toegevoegd aan alle echte rapporten.

**Comment by Emilien-Dupont** [comment]
In de omgevingsanalyse staan alle bronnen alfabetisch opgelijst omdat de lijst met bronnen erg lang was. Passen we dit ook toe voor de andere rapporten? 
Geert heeft een Python-scriptje gemaakt om bronnenlijsten te sorteren dat hiervoor gebruikt kan worden. Bij een korte lijst kan het uiteraard ook handmatig.

**Comment by joostschouppe** [comment]
Redactiegroep 25/5/2023
* goed idee om deze lijsten overal alfabetisch te maken
* ook nodig om aan te duiden wanneer bronnen afwijken in jaartal ten opzichte van de bron. Om dit gemakkelijk te kunnen doen moet het veld Reference Date van de DataSources ingevuld worden met iets als "Momentopname: 31/12 van het jaar voorafgaand aan het referentiejaar (bv. 2012 als jaartal in de databank betekent 31/12/2011)" voor de bronnen waar we afwijken van wat de oorspronkelijke bron doet. Graag dus iedereen dit even nakijken voor de eigen bronnen. (er was een oude lijst van deze bronnen, maar die is niet meer actueel). Deze disclaimer voegen we 1 keer toe, bovenaan, en laten we niet telkens opnieuw terugkomen in de bronnenlijst.  
* @davidcardinaels: zie jij het zitten om de alfabetisering te doen van de bronnenlijstjes in rapporten? Geert kan je op weg zetten met zijn script om dat wat gemakkelijker te maken.

**Comment by StefanieWVL** [comment]
Voor onderwerpen WVL enkel afwijking voor bron VMWS > bron hanteert 31/12/X > PINC 1/1/X+1

**Comment by davidcardinaels** [comment]
Alfabetisering is in orde.
