### ISSUE TITLE
Cijfers Groeipakket

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#236]
Ik heb van Mieke een mail doorgestuurd gekregen over nieuwe cijfers van Opgroeien, namelijk [Groeipakket op lokaal niveau](https://www.opgroeien.be/cijfers-en-publicaties/groeipakket/lokale-cijfers) met de vraag of die cijfers misschien interessant zijn voor PinC

**Comment by Emilien-Dupont** [comment]
Naar volgend jaar toe kan het interessant zijn om de cijfers op te nemen.
