### ISSUE TITLE
linken naar andere websites in rapporten

### ISSUE THREAD

**Issue by StefanieWVL** [provinciesincijfers/PinC-taakopvolging#238]
In het rapport wonen komt een luikje over het E-peil van de woningen. Interessant voor de lezer zou zijn om de wettelijke normen mee te geven... maar deze wijzigen regelmatig. Dus als 'harde tekst' schrijven is niet echt een optie. We zouden kunnen doorverwijzen naar deze pagina https://www.vlaanderen.be/e-peil maar als die URL ooit veranderd is het ook kapot in ons rapport. Een andere optie zou kunnen zijn om in de tekst gewoon te vermelden "Voor meer informatie omtrent het E-peil kan je terecht op de website Vlaanderen.be?

Misschien van de gelegenheid gebruik maken om hier een vaste afspraak over te maken? Doen we het of doen we het niet?

**Comment by joostschouppe** [comment]
De E-eis voor nieuwbouw zit ook in de databank van de EPB. Dit is informatie die verschilt volgens het aanvraagjaar (een huis waarvoor je de vergunning aanvraagt in jaar X moet voldoen aan de regels van jaar X, maar het komt pas in de databank als het afgewerkt is). Wij publiceren nu data op basis van afwerkingsjaar, omdat die data direct ongeveer definitief en volledig is. Maar je kan voor dit specifieke thema ook rekenen met aanvraagjaar. Je krijgt dan een tabelletje als dit, of de grafiek eronder:

&nbsp; | 35 | 36 | 40 | 45 | 50 | 54 | 60 | 70 | 80 | 100
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2006 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 12136
2007 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 19057
2008 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 23714
2009 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 25699
2010 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 23957 | 0
2011 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 6 | 28308 | 0
2012 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 23459 | 3 | 2
2013 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 38104 | 0 | 0
2014 | 0 | 0 | 0 | 0 | 0 | 9789 | 9861 | 21 | 0 | 0
2015 | 0 | 0 | 0 | 0 | 1 | 15840 | 14549 | 8 | 0 | 0
2016 | 0 | 0 | 0 | 4902 | 9659 | 5 | 1 | 2 | 0 | 0
2017 | 0 | 0 | 1 | 4676 | 8564 | 0 | 1 | 1 | 1 | 0
2018 | 0 | 280 | 3104 | 0 | 2 | 0 | 1 | 0 | 0 | 0
2019 | 0 | 34 | 479 | 0 | 0 | 0 | 0 | 0 | 0 | 0

![afbeelding](https://user-images.githubusercontent.com/10122639/121309929-10ddfa80-c903-11eb-9081-b2299b6352bb.png)

That said: heel PinC zit vol links naar externe websites - [een van de langetermijnsissues](https://github.com/provinciesincijfers/bugsinjive/issues/90) bij ABF is om hier automatisch op te kunnen controleren.

**Comment by joostschouppe** [comment]
Extern linken is OK. Gebruik beschrijvende links. 
Aan te vullen in draaiboek rapporten.
