### ISSUE TITLE
Nieuwe data Wonen-Vlaanderen:  Bindend Sociaal Objectief en premies

### ISSUE THREAD

**Issue by SofieWVl** [provinciesincijfers/PinC-taakopvolging#243]
Na een nieuw overleg met Wonen Vlaanderen is besloten nog een  aantal indicatoren voor de **woonpremies** toe te voegen, met name:
-	aantal aanvragen, goedkeuringen, weigeringen  afgezet  t.o.v. 1.000 inwoners voor huursubsidies, verzekering gewaarborgd wonen, Vlaamse aanpassingspremie en renovatiepremie
-	aanvraagredenen huursubsidie: aantal en  reden aanvraag huursubsidie afgezet t.o.v. totaal aantal aangevraagde huursubsidies
[Hier ](https://provincies.incijfers.be/jive?workspace_guid=1e1e78fc-c483-4a9d-994b-85e43a40c849) een voorbeeldje in de admin.  Bovenstaande indicatoren willen we graag mee extern plaatsen, met de actualisatie van de data voor 2020 (richtdatum is 12/07).

Verder is er nog heel wat data die moet opgeschoond of gebundeld worden, waarvoor we verdere input van Wonen Vlaanderen afwachten. Zitten nog in de pijplijn: weigeringsgronden huursubsidies,  data rond huurpremies (aantallen en stopzettingsreden), gemiddelden voor VAP en reno, huursubsidies en nieuwe rechthebbenden huurpremie. 
Wonen Vlaanderen onderzoekt ook mogelijkheden om premiedata tot op statistisch sectorniveau en  data rond woningkwaliteit aan te leveren

Verder hebben  we ook data rond het[ **Bindend Sociaal Objectief (BSO**)](https://provincies.incijfers.be/admin/jive/?var=v2202_bso_toestand2007,%20v2202_bso_gerealiseerd,%20v2202_bso_gepland,%20v2202_bso_ger_en_gep,%20v2202_bso_verschil_ger_en_gep,%20vp2202_bso_ger_en_gep) toegevoegd. Het Bindend Sociaal Objectief legt aan de gemeente op hoeveel sociale huurwoningen zij op haar grondgebied moet realiseren tegen 2025.  We zouden deze data graag deze week al extern willen zetten, het komt ook in het vernieuwd rapport Wonen. In de themaboom vind je het onder Wonen/Sociaal wonen/Bindend Sociaal Objectief. Staat nu nog in de interne map.  

Indien bezwaar of opmerkingen horen we dat graag.

**Comment by joostschouppe** [comment]
Helemaal OK voor de Redactiegroep
