### ISSUE TITLE
afronding "Toerisme" fase 1: plaats in themaboom, verantwoordelijken Dashboard

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#244]
het valt me op dat het (nieuwe) thema Toerisme onderaan bengelt in zowel de themaboom als de tegels op het dashboard.
moet dat anders ? of toch in orde zo ?

ook hier toevoegen:
https://github.com/provinciesincijfers/PinC-taakopvolging#volgorde-themaboom
https://github.com/provinciesincijfers/PinC-taakopvolging#taakverdeling-dashboard

**Comment by karolienbloemen** [comment]
Wie heeft interesse om de controle van het dashboard toerisme op zich te nemen?
Bij de opmaak werd dit opgenomen door mezelf, Koen en Joost, alsook door de mensen van de werkgroep toerisme. Maar nu het is afgewerkt, lijkt het me beter als iemand van D&A uit een andere provincie dit mee opneemt.

**Comment by Emilien-Dupont** [comment]
@Lievendr controleert

**Comment by Lievendr** [comment]
@stefan
"Meer over dit thema in de databank"-knop werkt niet

**Comment by StefanJacques** [comment]
@Lievendr 
in orde gebracht door @KoenSnyers
