### ISSUE TITLE
"cijfers klimaat opgelijst" EXTERN toevoegen aan themaboom en rapporten op dashboard

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#246]
Naar analogie met cijfers bevolking opgelijst en cijfers huishoudens opgelijst is nu ook
cijfers klimaat opgelijst afgewerkt: https://provincies.incijfers.be/admin/jive?report=tabellenrapport_klimaat

we plaatsen het bij in de themaboom en op het dashboard (onder rapporten en onder de tegel klimaat)

**Comment by KoenSnyers** [comment]
Toegevoegd aan dashboard (op rapportenpagina en in thema).

**Comment by davidcardinaels** [comment]
Allemaal in orde.
