### ISSUE TITLE
Kubussen zonder Brussel

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#247]
In welke kubussen op gemeenteniveau moeten we brekende missings op gemeenteniveau inlezen? Gelieve per kubus een excel aan te leveren volgens het format dat [hier](https://github.com/provinciesincijfers/JiveDocumentation/blob/master/02.%20Data%20defini%C3%ABren/kubussen/brussel-invullen) uitgelegd wordt. Als het even kan mag je ook zelf het SPSS script gebruiken :)

Nagekeken en hieronder aangevuld door:
- [x] LI
- [x] OV
- [x] VB
- [x] AN
- [x] WV

Dit is getest op de kubussen van Klimaat, en dit heeft het gewenste effect, ook in afgeleide onderwerpen.

**Comment by Lievendr** [comment]
kubussen Bevolking worden aangepast bij volgende upload; geen andere kubussen voor Antwerpen

**Comment by StefanJacques** [comment]
Automatiseren ?

input zou zijn:
-	Jaartal
-	Gebiedsniveau(s)
-	Gebruikte dimensieniveaus (qua inlezen), items/itemcodes
-	Onderwerpcode

Lijkt iets om in Python te doen.
Misschien wel een fijn projectje voor Chris, Emilien of Joost om dat eens als leer-case te nemen.

**Comment by joostschouppe** [comment]
@StefanJacques bezorg jij de nodige input voor een testcase?

**Comment by StefanJacques** [comment]
[input testcase.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/6732904/input.testcase.xlsx)

bedoel je dit ?

**Comment by veravandestraat** [comment]
Geen kubussen voor Oost-Vlaanderen

**Comment by SofieWVl** [comment]
Ook voor West-Vlaanderen zijn er geen kubussen.

**Comment by VickyVB** [comment]
Hierbij een overzicht van de Vlaams-Brabantse kubussen.
De overgrote meerderheid bevatten gegevens voor het BHG. In die van de fiscale inkomsten van gemeenten zijn de missings voor BHG reeds verwerkt. 
Blijven over de 3 bevolkingsloop kubussen. Wanneer de RR verwerking 2021 klaar is, moeten deze allen opnieuw opgeladen worden. De -99999 voor BHG zullen dan opgenomen worden in de verwerking.

[kubussen_vb.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/7141788/kubussen_vb.xlsx)

**Comment by StefanJacques** [comment]
> Geen kubussen voor Oost-Vlaanderen (tenzij Tanja, Chris en ik niet op de hoogte zijn van een kubus die Mieke altijd opgeladen heeft..)

Dag Vera,
er is één kubus waar jullie verantwoordelijk voor zijn:
**kubus3504_zorgverzekering** | zorgverzekering | [kubus] lopende dossiers in de   zorgverzekering naar geslacht, zorgsetting en leeftijd | v3504_zorgverzekering.pdf | aantal | vlazog | **OV_LI**

**Comment by veravandestraat** [comment]
> > Geen kubussen voor Oost-Vlaanderen (tenzij Tanja, Chris en ik niet op de hoogte zijn van een kubus die Mieke altijd opgeladen heeft..)
> 
> Dag Vera,
> er is één kubus waar jullie verantwoordelijk voor zijn:
> **kubus3504_zorgverzekering** | zorgverzekering | [kubus] lopende dossiers in de zorgverzekering naar geslacht, zorgsetting en leeftijd | v3504_zorgverzekering.pdf | aantal | vlazog | **OV_LI**

Ik had dat intussen ook ontdekt, maar we hebben cijfers voor Brussel dus voor dit issue is die kubus niet van belang. Ik moet de update van de meest recente cijfers wel nog doen. Ik was daar in de vakantie mee bezig geweest maar ik had wat problemen met de kubus-upload.

**Comment by StefanJacques** [comment]
[KUBUSSEN Limburg.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/7215566/KUBUSSEN.Limburg.xlsx)

kubus verkeersslachtoffers wordt nog bekeken.
kubussen toerisme bij een volgende actualisatie in orde gebracht
niet nodig voor 2 interne kubussen (handelspanden tijdens corona en oude bevolkingsprojecties Statistiek Vlaanderen)
