### ISSUE TITLE
Wijkdashboards Onderwijs

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#250]
Basisonderwijs: voorstel afkloppen en doorgeven aan Koen
Secundair Onderwijs: voorstel afkloppen en doorgeven aan Koen

**Comment by VickyVB** [comment]
Voorstel voor basisonderwijs en secundair onderwijs is doorgegeven.

**Comment by KoenSnyers** [comment]
De wijkdashboards basisonderwijs en secundair onderwijs staan online na nazicht/aanpassingen.
