### ISSUE TITLE
Wijkdashboard Ruimte

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#251]
Voorstel te maken

**Comment by joostschouppe** [comment]
Eerste versie beschikbaar via https://provincies.incijfers.be/dashadmin/preview/dashboard/ruimte-wijkniveau . 
Opmerkingen:
- formulering intro is een beetje anders omdat de noemer hier de totale opp is, en die gaat niet vaak heel klein zijn. Een bollenkaart van een totale (groene) oppervlakte is een beetje gek - we gebruiken bollenkaarten net omdat een kleurenkaart "gevaarlijk" is voor grotere gebieden met weinig van de noemer. Maar hier is de noemer exact de grootte van het gebied.
- inhoudelijk is het een bijna volledige kopie van het gewone dashboard, m.u.v. verhardingsgraad binnen de klasses. Dit gaf weinig verschil tussen de wijken
- Dit is een sub-dashboard van Ruimte - daar kan evengoed naar verwezen worden vanuit een zelfgemaakte knop, maar ze verzwaart de lijst thema's in de CategoryTree en is geen extra onzichtbare knop op de startpagina.
- @veravandestraat @ChrisMichelDS : omdat OV als controleur op de onderwerpen staat en Chris op het Dashboard Ruimte, bekijken jullie dit ook eens, vooral inhoudelijk?
- @KoenSnyers : ik heb al een en ander proper gezet, maar zeker nog niet alles.

**Comment by KoenSnyers** [comment]
@joostschouppe 
Joost, jammer dat je dit als een subdashboard aanmaakte.
De afspraak was van niet op die manier te werken en de wijkdashboards gewoon als hoofdthema in de themaboom te zetten (en op onzichtbaar op de startpagina).
Ik stel voor dat ik de map in de themaboom verplaats en dan het dashboard opnieuw aanmaak volgens jouw voorstel.
Ok voor jou?

**Comment by joostschouppe** [comment]
Ik dacht dat dat geen afspraak was, maar gewoon een pragmatische keuze voor de bestaande dashboards. Het heeft kleine voordelen om het als subdashboard te doen - omdat de andere wijkdashboards reeds gemaakt waren als "volwaardig dashboard" vond ik het de moeite niet om je die allemaal te laten maken als subdashboard. Maar om nu een minder goede oplossing als policy te gaan kiezen vind ik een beetje raar.

**Comment by KoenSnyers** [comment]
@joostschouppe joost
Ok, we hanteren voor wijkdashboards vanaf nu de werkwijze dat ze in de themaboom als submap van het thema geplaatst worden.
Ik kijk jouw voorstel na en doe wat kleine aanpassingen.

**Comment by KoenSnyers** [comment]
Het wijkdashboard ruimte is wat mij betreft helemaal klaar:
https://provincies.incijfers.be/dashadmin/preview/dashboard/ruimte---wijkniveau.
Indien ok, zet ik het online.

**Comment by joostschouppe** [comment]
Ja, zet maar online. We horen het wel als @veravandestraat of @ChrisMichelDS nog opmerkingen zouden hebben

**Comment by KoenSnyers** [comment]
Staat online.

**Comment by veravandestraat** [comment]
Geen opmerkingen van mijn kant. Mooi werk!
