### ISSUE TITLE
Wijkindeling: licentie

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#252]
De vraag:
Op provincies.incijfers.be bieden we data voor uw gemeente aan volgens de wijkindeling die medewerkers van de gemeente ons bezorgden. Wij verzamelen deze wijkindelingen niet enkel in dit kader. Andere dataleveranciers kunnen ook van die wijkindeling gebruik maken. Bijvoorbeeld Kind & Gezin en het Intermutualistisch Agentschap willen op deze manier data aanbieden. Op die manier dragen we er toe bij dat er minder verwarring is over geschikte wijkindelingen voor uw gemeente. Daarom willen we de wijkindeling nu toevoegen aan Geopunt.be onder de Vlaamse modellicentie gratis hergebruik (https://overheid.vlaanderen.be/modellicentie-gratis-hergebruik). Mocht u hier vragen bij hebben, laat het ons dan weten.

Het antwoord:
- centrumsteden: volledig in orde
- WV: in orde, bevestigd door @HildeC 
- OV: geen bijkomende wijken
- AN: @Lievendr nam contact op met **Sint-Katelijne-Waver**
- LI: in orde, bevestigd door @karolienbloemen 
- VB: in orde bevestigd door @HanneODB-VLBR

**Comment by HildeC** [comment]
alle gemeenten met een wijkindeling in WVL werden aangeschreven, ook deze die nu mee in de update zitten. 
Moet ik nog actie ondernemen voor Roeselare en Kortrijk? of die je dit op OBMI?

**Comment by HanneODB-VLBR** [comment]
Ik heb dit tekstje steeds meegestuurd in bijlage, met in het mailtje de vraag om dit te lezen en te reageren als er opmerkingen waren. Van niemand opmerkingen ontvangen, voor VB in orde dus.

**Comment by joostschouppe** [comment]
Bedank Hanne, Hilde!
Hilde, je moet verder niets doen - ik heb gisteren een reminder gestuurd naar de vijf ontbrekende centrumsteden en al vier goedkeuringen binnengekregen ondertussen. Dus enkel Sint-Katelijne-Waver en Roeselare staan nog open!

**Comment by HildeC** [comment]
👍

**Comment by Lievendr** [comment]
Net mail verstuurd naar dienst Ruimte in St-Katelijne-Waver

**Comment by karolienbloemen** [comment]
Dit werd door Koen doorgegeven aan de gemeenten (waar van toepassing via RIMO). Van enkele gemeenten een 'dank voor de info' ontvangen. Wordt vanaf nu standaard gemeld aan de gemeenten.

**Comment by HanneODB-VLBR** [comment]
[Draaiboek wijkgrenzen definiëren_v4.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/7116192/Draaiboek.wijkgrenzen.definieren_v4.docx)
We stelden een draaiboek op met een methode om tot gemeentegedragingen wijkindelingen te komen. Graag legden we dit draaiboek voor aan de redactiegroep, niet de eerstvolgende maar wel die van 18/10 zodat Joost zeker ook aanwezig kan zijn.

**Comment by Lievendr** [comment]
Overleg gehad met VVSG werkgroep [giscoördinatoren] op 1 oktober. 
[gemeentewijkenPinC_VVSG.pptx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/7267660/gemeentewijkenPinC_VVSG.pptx)

belangrijkste bedenkingen: 
1. meerdere gissers staan negatief tegenover statsec. Ze zijn verouderd en geven geen realistisch beeld van wijken; 
2. voortbouwend op 1: noem ze dan ook geen wijken maar "statsec-gebieden"; 
3. sommigen zijn zelfs zeer negatief en gaan "zeker niet" die wijken aanpassen;
4. sommigen willen zelfs hun wijkindeling in PINC en beseffen niet dat daar er geen atomaire gegevens voor zijn;
5. ze zijn vragende partij om statsec aan te passen aan hun noden - zijn niet op de hoogte van werkgroep binnen het statistisch landschap. 
==> beseffend dat je enkel negatieve commentaren hoort, moeten we ons bewust zijn dat gis-coördinatoren soms te gespecialiseerd/gedetailleerd bezig zijn om als doelgroep aan te spreken

**Comment by veravandestraat** [comment]
Wij hadden vorige week een overleg n.a.v. een vraag vanuit Wetteren voor een wijkindeling. De reactie overlapt grotendeels met wat Lieven hierboven schrijft. De afsluiter was: 'contacteer ons zeker zodra het mogelijk is om van de statistische sectoren af te wijken en onze eigen wijkindeling op te nemen'.

**Comment by HanneODB-VLBR** [comment]
De feedback over de niet-aangepaste statistische sectoren heb ik ook een paar keer gekregen. Aan die mensen liet ik weten dat er momenteel bij Statbel een werkgroep lopende is die zich buigt over de aanpassing hiervan (wie daar nog meer info over wil of er zelf mee in wil zetelen, kan je in contact brengen met Joost, want hij zit ook in deze werkgroep en weet er meer over). Echter, hierop kunnen we niet wachten, want het kan nog jaren duren voor daar echt iets uit de bus komt! Ik vroeg aan deze mensen steeds:
- of ze toch op basis van de huidige sectoren een indeling wilden maken, voor de eerstkomende jaren. Ik beloof hierbij dat ik hen meteen een seintje zal geven als de aangepaste sectoren er zijn, zodat ze dan meteen ook hun wijkindeling kunnen herzien indien gewenst
- als ze dit toch echt niet de moeite vinden, vraag ik hen om op zijn minst namen toe te kennen aan de door ons voorgestelde wijken, zodat er op zijn minst al een naam staat ipv een code.

**Comment by Lievendr** [comment]
Blijkbaar circuleert dezelfde vraag via Arvastat. Ik krijg nu bericht via VVSG om de vraag van PInc af te stemmen op die van Arvastat.
[uitleg naar geinteresseerde gemeentebesturen.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/7277816/uitleg.naar.geinteresseerde.gemeentebesturen.pdf

**Comment by HildeC** [comment]
- de opmerking ivm stat sectoren krijg ik ook wel, maar ik pareer dat van in t begin: stat sectoren zijn niet ideaal, maar het is beste wat we hebben :-)

- wat de oefening ivm hertekening betreft: dit kadert in een samenwerkingsaanvraag tussen de Be statistiekverantwoordelijken (statbel, stat vlaanderen, stat wallonie en stat brussel. Joost en ik participeren aan het overleg. we zitten in een fase van inventariseren van problemen. vanuit statbel wil men niet naar een herwerking van de stat sectoren, zal eerder een alternatief worden. maar het vordert traag, dus de eerste jaren moet je er nog niet veel van verwachten.

- volgende week staat er overleg met VDAB op de agenda. een van de puntjes is het hergebruik van vdab van onze wijkenkaart,

**Comment by joostschouppe** [comment]
Gepubliceerd via https://metadata.vlaanderen.be/srv/dut/catalog.search#/metadata/73354ce0-7940-447c-8fec-b4f672abb837
Komt toe op https://www.geopunt.be/catalogus/datasetfolder/73354ce0-7940-447c-8fec-b4f672abb837
