### ISSUE TITLE
cijfers huisartsen op stat.sec. niveau

### ISSUE THREAD

**Issue by SofieWVl** [provinciesincijfers/PinC-taakopvolging#254]
Hilde is al een tijdje bezig met het traject om cijfers van de zorgberoepen (apothekers, huisartsen, kinesisten)  uit de sociale kaart provinciebreed zuiver te krijgen voor opname PinC.  

De cijfers voor het **aantal huisartsen** zijn aangezuiverd en staan klaar om gepubliceerd te worden. Bron is de sociale kaart en de data werd door Hilde ook naast de gegevens uit Locatus gelegd. 

Dit staat nu nog in de admin onder Gezondheid\Aanbod eerstelijnsgezondheidzorg. Vraag aan de redactiegroep om extern te mogen publiceren. Opmerkingen zijn welkom.
Vlaams-Brabant heeft de data en metadatafiche al aan een controle onderworpen.

**Comment by SofieWVl** [comment]
Na input van Filip hebben we beslist deze indicatoren nog even intern te houden.  Binnenkort verwachten we een nieuwe versie van de sociale kaart, wat een correcter beeld van de huisartsen zou moeten geven.

**Comment by StefanieWVL** [comment]
zie #444
