### ISSUE TITLE
codes op kaart

### ISSUE THREAD

**Issue by Lievendr** [provinciesincijfers/PinC-taakopvolging#259]
Vroeger kreeg je op kaart de naam van de gebied alsook de code te zien.
Nu krijg je enkel nog de naam. (of bij Nis7-wijken enkel de code)
Kan er een bijkomende optie naast  
1. toon naam indien mogelijk 
2. toon waarden indien mogelijk 
een derde optie: toon gebiedscode indien mogelijk toegevoegd worden?

Daarnaast moet misschien ook de kaartlaag WIJKEN toegevoegd worden, nu we meer werk willen maken van gemeentegedragen wijken?

**Comment by Emilien-Dupont** [comment]
Wens voor abf: Toon extra mogelijk label voor codes 'Toon codes indien mogelijk'

**Comment by joostschouppe** [comment]
Wat Sander zegt kan niet: https://provincies.incijfers.be/jive?workspace_guid=aa139ff7-bdff-441c-8ee4-d4027fa94aad

**Comment by joostschouppe** [comment]
Uit te testen: een tekstveld als numeriek weergeven en dan eens proberen

**Comment by joostschouppe** [comment]
De door Sander gesuggereerde workaround werkt enkel indien je codes ook effectief numeriek ZIJN (wat bij ons zeer vaak niet het geval is).
