### ISSUE TITLE
Inhoudelijk de intro bekijken

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#26]
Tekst herbekijken
Wanneer het klaar is doorgeven om dit in alle rapporten te harmoniseren - @StefanieWVL

**Comment by karolienbloemen** [comment]
input ontvangen op de intro bij rapport ouderenzorg, mee te nemen in dit issue:
Bij de alinea "het huidige rapport vergelijkt [gemeente] met de door u gekozen vergelijkingsgebieden [provincie] (bekijk op kaart) en [Gewest] (bekijk op kaart)." : ik vraag me af of dit geen verwarring creëert. Kan me provincie ook aanpassen? Wat is de meerwaarde van dit op kaart te zien? Misschien combineren met gegevens in de provincie en Gewest?

**Comment by Lievendr** [comment]
Ik kan natuurlijk niet in het hoofd van Stefanie kijken…om introductie aan te passen.
Mij baserend op het ouderenzorgrapport, kan ik best leven met de intro. Alleen had ik wat vragen bij de opmerking die ook Karolien gepost heeft (de opmerking komt trouwens van mij :-))
Ik vind het bekijken op kaart van de gekozen vergelijkingsgebieden weinig meerwaarde hebben en dus vooral ballast. (vooral als het Vlaams gewest en provincie is)
Ik zou dat dus schrappen en opteren voor de eerste optie zoals die in het sjabloon staat. “Het vergelijkingsgebied is … en …”.

**Comment by joostschouppe** [comment]
De opmerking van Karolien was een copy-paste bij jouw opmerking ivm rapport ouderenzorg. Ik heb het sjabloon nu zo aangepast dat de links enkel verschijnen indien het NIET gaat om provincie of vlaanderen
