### ISSUE TITLE
gebiedsniveau referentieregio's

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/PinC-taakopvolging#263]
kunnen we de Vlaamse referentieregio's al als gebiedsniveau toevoegen aan PinC? in arvastat zijn ze al opgenomen. Limburg is daar wel als 1 regio opgenomen. ik weet niet hoe het staat met verdere onderverdeling van Limburg

**Comment by joostschouppe** [comment]
We nemen dit op als Limburg rond is. Dit zou nog enkele maanden duren.

**Comment by joostschouppe** [comment]
Deze zijn inmiddels opgenomen; mag toe eens vermeld op Redactiegroep
