### ISSUE TITLE
Dashboard filmpjes

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#269]
tonen als eindjaar bij export?
Testen op snelheid
Exporteren als filmpje?
Oproep pagina-beheerders
Beheersregel verzinnen (max 1 per pagina?)

**Comment by KoenSnyers** [comment]
@joostschouppe
Die knop 'enable play tile' lijkt er niet tussen te staan in de general settings van een tegel ...
Dus volgens mij is die feature nog niet operationeel. Of kijk ik ergens overheen?

**Comment by joostschouppe** [comment]
Amai, the devil is in the details.
De functie is alleen beschikbaar voor "viewer tegels". Daar had ik precies nog niet van gehoord. Dat betekent blijkbaar een Preselectie (die we aanmaken in de rest van Studio) in de themaboom voor Dashboard zetten en daar een derde type tegel mee maken:

![afbeelding](https://user-images.githubusercontent.com/10122639/144254051-42458893-0d9a-43c2-b3fb-41b130e2e88a.png)

Ik heb een oude bestaande preselectie opgevist, en daar een voorbeeldje mee gemaakt. De layout is niet goed, ik zie niet direct hoe dat te fixen. Het werkt wel, maar énkel in de live versie. Je kan dus NIET testen in de testomgeving.

Voorbeeld via https://provincies.incijfers.be/dashboard/dashboard/speeltuin/

**Comment by KoenSnyers** [comment]
Een swing viewer tile, daar had ik ook nog nooit van gehoord.
Dat lijkt me allemaal heel omslachtig.
Ik zou die optie van dat filmpje dan toch maar niet gebruiken in het dashboard hoor.
Als we preselecties uit de Studio moeten gaan aanmaken om in het dashboard te zetten, waar  zijn we dan mee bezig?

**Comment by joostschouppe** [comment]
Bijkomend issue: bij export van de tegel blijft er een groot "play" knopje op de grafiek staan. Ingeseind bij ABF.

**Comment by joostschouppe** [comment]
Ideeen mogen bezorgd worden aan Joost
