### ISSUE TITLE
rapport buurtgerichte zorg

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/PinC-taakopvolging#270]
Ik heb zopas het rapport buurtgerichte zorg voor Wervik opgevraagd.
https://provincies.incijfers.be/jive?workspace_guid=fc0a1e07-8efb-4867-bf1c-6d9fa5470073

en er zijn momenteel 2 problemen met het rapport.
1.	De data verhoogde tegemoetkoming is geactualiseerd op gemeenteniveau, maar niet op stat sectorniveau. In overleg met Joost gaan we hiervoor wachten op de connector met IMA. 
in het rapport worden voor VT geen cijfers weergegeven. Kan dan ingesteld worden dat het (in afwachting van update) de cijfers van 2018 zijn die hier getoond worden en niet de meest recente? 
ik weet niet of het kan, en of dat veel werk is?
2.	Bij eenoudergezinnen wordt bij het rapport op stat sectorniveau, de info getoond op niveau van alle gemeenten in Vl, en niet voor de stat sectoren. Ik weet niet wat hiervan de oorzaak is. Kun je dat ook eens bekijken? Als je het rapport opvraagt op wijkniveau, dan krijg je wel de wijken van Wervik

David, kan jij dat eens bekijken aub?

**Comment by joostschouppe** [comment]
- Voor vraag 1: OK, aangepast. Opgelet: op het moment dat VT terug gewoon up to date is, moet dit manueel terug goed gezet worden. Kan WV dat ergens bijhouden? Ik heb bovenaan in de code een opmerking gezet van wat er precies moet gebeuren
- Vraag 2: nou. De schuldige hier is vp1115a_w_s_v1 . Die is niet toegevoegd aan "dit mag op statsec getoond worden". De indicator is niet meer aangeraakt sinds november 2020, wat me doet vermoeden dat het rapport NOOIT volledig correct gewerkt heeft voor wie niet ingelogd is. Ik denk dat die tussen de mazen van mijn controle is gevallen omdat het niet EXTERN staat. Afijn, dus zowel [dit](https://github.com/provinciesincijfers/JiveDocumentation/blob/master/05.%20Themaboom%20-%20Toegang%20beheren/Toegangs-%20en%20gebruikersgroepen.md#themaboom-en-toegangsgroepen) als [dit](https://github.com/provinciesincijfers/JiveDocumentation/raw/master/09.%20Controle/Checklist%20grondige%20controle%20databank.docx) hebben gefaald... Ik heb alvast [hier nog een extra vermelding gedaan](https://github.com/provinciesincijfers/JiveDocumentation/commit/cd9ef4612168b16f724797219cf50499dbdda9e5#diff-4be04c8e97db2701a028f60b1976da98104aff62fa467f172868781a847f5061). Het valt natuurlijk minder op omdat het rapport by default op wijkniveau wordt getoond. De fout zelf is rechtgezet.
