### ISSUE TITLE
Tegel Dashboard-voor-beginners?

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#274]
- uitspitten waarom dat we "over deze site" weggezwierd hebben uit Dashboard
- eventueel deze toch weer toevoegen als tegel
- of toch iets nieuws specifiek over "eerste stapjes in pinc"
- zie ook [issue #111](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/111#issuecomment-690915306)

**Comment by joostschouppe** [comment]
Eerste volwaardige draft staat klaar op https://provincies.incijfers.be/dashadmin/preview/dashboard/ontwikkelplaats--gebruik-van-de-website-
* waar de uitleg te lang wordt, staat die achter "meer info" (even op klikken)
* bij die langere uitleg staan soms screenshots,vb bij "stel je eigen streek samen". Die heb ik om wat tijd te winnen op imgur.com gezet; het kan zijn dat die door je provinciaal netwerk geblokkeerd worden (da's toch in Limburg het geval)

**Comment by Tine-VB** [comment]
Heel tof, Joost! Zoals gewoonlijk heb ik toch nog een paar pietluttigheden gevonden:
![image](https://user-images.githubusercontent.com/61458346/178980889-5a4b3279-5247-4fab-8fca-d90cd055f424.png)
Kunt ipv junt
![image](https://user-images.githubusercontent.com/61458346/178980941-c185803b-b2df-4175-ab7e-2c1d98dd8902.png)
Bij het begin van een zin mag provincies.incijfers.be uiteraard wel met hoofdletter. En als tweede zin: De databank is ontwikkeld... (want wie is 'ze'?).
![image](https://user-images.githubusercontent.com/61458346/178981096-ed3007eb-a386-4515-9a29-4f0110c7097f.png)
... waar voldoende data-aanbod is _OP DIT NIVEAU_,...
![image](https://user-images.githubusercontent.com/61458346/178982241-74651c18-d6b5-4e45-809f-2a7292668b84.png)
De klassieke Rapporten geven een ruime selectie indicatoren over een bepaald thema _VOOR EEN BEPAALD GEBIED (EEN OF MEER GEMEENTE(N) OF PROVINCIES)_ met verduidelijkende figuren, tekst en uitleg.

_DE RAPPORTEN MET_ 'Cijfers opgelijst' geven een tabel met cijfers voor je gebied en relevante vergelijkin_G_sgebieden

De Rapporten Kerncijfers verzamelen indicatoren in functie van een bepaald beleidsdomein: Klopt niet. Ik zou schrijven:
_Het rapport Kerncijfers geeft een beknopt overzicht van de meest relevante cijfers voor een gemeente over een aantal thema's heen. Het rapport Kerncijfers voor buurtgerichte zorg geeft informatie over de wijken of statistische sectoren binnen een gekozen gemeente, in functie van een buurt- of wijkgericht beleid. Het rapport Kerncijfers voor Eerstelijnszones geeft zorg- en welzijnsgerelateerde informatie over de gemeenten binnen een gekozen eerstelijnszone._

![image](https://user-images.githubusercontent.com/61458346/178984022-76f89a9b-f2da-4aef-ad89-ea1abbf786f8.png)
Als je achteraf het rapport nog aanpast met de Wijzig-knop, dan _WORDT DE_ url niet aangepast.
Of stel je rapport samen via Kiezen op Kaart en hou _DE_ url van je ....

![image](https://user-images.githubusercontent.com/61458346/178984390-c0dbb06d-5719-47f0-af09-ca97d9d2f197.png)
Spatie tussen link en kan. Met die laatste link kan je zelf de figuur op maat aanpassen...

![image](https://user-images.githubusercontent.com/61458346/178984756-e0f9c1e1-6b74-45fa-88e3-3f8b7bff5e0e.png)
Punt achter alle zinnen.
Je gebruikt hier 'Region', moet dit niet 'Mijn regio' zijn (analoog aan info hierboven)?

Ik heb ook beknopte handleiding gemaakt in powerpoint. Ik vind die persoonlijk handiger dan het filmpje, en minder uitgebreid dan de uitgebreide handleiding. Ik verwijs wel in de powerpoint naar de uitgebreide handleiding. Eventueel te bespreken of we deze niet zouden toevoegen (of een nog aangepaste versie natuurlijk). 
https://vlbr.sharepoint.com/:p:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Communicatie/Vorming%20en%20opleiding/Opleidingen%20PinC%20eindgebruikers/Handleiding_PinC_20220420.pptx?d=w1420629ac6894b689403eb5da7cb30f5&csf=1&web=1&e=Ds5sYJ

**Comment by joostschouppe** [comment]
Correcties doorgevoerd
Bij "Soorten Rapporten" wil ik het kort houden; maar ik heb wat extra uitleg over de "kerncijfers" bij "meer info" gezet. Kunnen we in enkele woorden zeggen wat die Kerncijfer-Rapporten onderscheid van de klassieke Rapporten?
Die PPT is wel goed, maar moeten we niet wat opletten met te veel parallelle documentatie?

**Comment by joostschouppe** [comment]
Afspraak redactiegroep 20/9/2022:
Joost stuurt door naar iedereen alvorens te publiceren

**Comment by LoreDJ** [comment]
een heel handig overzicht!
2 kleine tikfoutjes en opmerkingen:
* bij wijkdashboards: data te **ontsluiten**
* de blauwe tegel bij databank: punt aan het einde van de zin
* tekst in de blauwe tegel bij dashboard is groot, terwijl dit niet zo is bij de andere blauwe tegels.
* bij uitleg over wijkdashboards evt toevoegen bij de eerste zin: Je vindt een eventuele blauwe knop steeds bovenaan de pagina **("Check het thema op wijkniveau")**.

**Comment by Tine-VB** [comment]
Van mij ook nog enkele opmerkingen:

Over alle thema's en rapporten heen krijg je nu cijfers over dit gebied. Of: **Als je nu een thema of rapport selecteert, krijg je cijfers over dit gebied.**

Ik zou de tekst volledig boven de schermafdruk zetten (ook bij alle andere items, het tekstje onderaan gaat anders wat verloren denk ik) en de volgorde aanpassen: Klik op het potlood om de gebiedsselectie te openen. Kies je gemeente in de lijst en **klik op Sluiten** om verder te gaan. Je kan **ook** _(daarnaast = ook)_ kiezen voor een provincie als basisgebied.
Standaard vergelijken we met de provincie**, maar je kan ook vergelijken met het arrondissement, het gewest of een andere gemeente.**
![image](https://user-images.githubusercontent.com/61458346/194860368-7f6ff72e-1555-47fc-ad37-a21379b3ace6.png)

Over heel de site vind je **'download' en 'deel' knoppen.**

Bij provincies.incijfers.be proberen we zoveel **mogelijk** _(zonder e)_ data te **ontsluiten** ...

**Comment by Tine-VB** [comment]
Rudy belt mij met nog een opmerking over dit stukje: 
![image](https://user-images.githubusercontent.com/61458346/194879082-43322064-79ea-4e87-9c44-78df911bece7.png)
Het lijkt nog redelijk Chinees, dus misschien achter '... dan wordt de URL niet aangepast.' het zinnetje: 'Daarvoor moet je terug naar de home page van het dashboard gaan, daar de gemeente wijzigen en dan terug het rapport openen.'

**Comment by joostschouppe** [comment]
Alle aanpassingen gedaan. Ik heb dat laatste proberen vertalen van Chinees naar Nederlands. Het blijft moeilijk om dit uit te leggen. Het issue is gelijkaardig aan wanneer je een deellink maakt en daar achteraf op verderwerkt. Mensen zien dan een speciale URL vanboven staan en denken dat die magisch blijft. Maar die blijft gewoon staan, en je moet dus opnieuw een permanente URL maken om de huidige sessie op te slaan. Geen idee hoe je dat uitgelegd krijgt. Misschien moeten we dat zinnetje met "opgelet" gewoon laten vallen.

**Comment by veravandestraat** [comment]
Mooi gedaan!

Vermoedelijk iets waar al heel wat prutswerk aan vooraf is gegaan, maar ik vind het wat jammer dat dit de enige tegel is waar je moet scrollen: 
<img width="437" alt="image" src="https://user-images.githubusercontent.com/61196697/196197518-73c5ee00-95b6-45aa-b630-b491ccb6c2dd.png">
Is dat te verhelpen door iets minder ver in te springen met de bullets (zodat vergelijkingsgebieden nog net op de regel past)?

**Comment by joostschouppe** [comment]
@veravandestraat kan je eens checken of dat ook hier gebeurt? https://provincies.incijfers.be/dashboard/dashboard/ontwikkelplaats--gebruik-van-de-website-/ Bij mij gebeurt het alleszins in geen van de twee omgevingen

**Comment by veravandestraat** [comment]
Hetzelfde:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/61196697/196201531-4d1b0454-2b66-4dcc-8f9c-7af696bb9cb5.png">

**Comment by joostschouppe** [comment]
Gevonden! Ik heb een paar woorden strategisch weggeknipt en nu ziet het er in mijn chrome ook goed uit.

**Comment by JoLocquet** [comment]
Ik von inspiratie voor opbouw van informatie voor beginners bij [geopunt](https://www.geopunt.be/over-geopunt/): @joostschouppe je kent dit site ook ;)

**Comment by joostschouppe** [comment]
Yes, als 291 eindelijk rond is, moet deze nieuwe pagina misschien nog eens bijgewerkt worden (net als de handleiding trouwens).

Voor nu klaargezet voor publicatie:
- knop op de eerste rij van Dashboard
- met een lelijk icoon. @GeertBonte kan jij eens nagaan of er destijds een geschikt icoon hiervoor is ontworpen in West-Vlaanderen?
- link gezet in de Handleiding
- rechtstreekse verwijzing naar de filmpjes verwijderd uit de Themaboom van de Databank
- bij "over de website" het deel instructiefilmpjes verwijderd, en stukje i.v.m. "hulp" herschreven, met link naar de nieuwe pagina

**Comment by JoLocquet** [comment]
Suggestie: elke tegel beginnen met een vraag zoals bij "wat is PinC.be?"
Bestaat er richtlijn voor gebruik van Hoofdletter en "..."? 
Rapportentegel = blauw/blauw is moeilijk leesbaar
Op basis van aantal clicks lijkt me lijkt me uitleg over de gebiedsindeling en Brussel nuttig om mee te geven aan de eindgebruiker
Eventueel een nieuwe gebruiker van PinC (intern bij de Provincie) vragen naar de gebruikservaring?

**Comment by EmielGrimonprez** [comment]
Mooi overzicht over het gebruik van PinC! 

Nog een kleine aanvulling van Zeneb: in de tegel 'Rapporten gebruiken' is de link [rapportentegel](https://provincies.incijfers.be/dashboard/rapporten) niet zo goed leesbaar tegenover de blauwe achtergrond van de tegel. 

![image](https://user-images.githubusercontent.com/115799836/196697079-82c5fc4a-5232-4d72-9de3-8d46e4a7acf9.png)
