### ISSUE TITLE
Indicatornummers in PinC

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#277]
Graag even verifiëren wat nu weer juist de correcte aanpak is voor het toekennen van nummers aan nieuwe indicatoren in PinC. Concrete aanleiding is het opladen van de mobiliteitsindicatoren uit de gemeentemonitor. Het opvolgbestand is voornamelijk zo geordend dat de nummers thematisch worden toegekend, in dat geval zouden deze indicatoren 2107 moeten krijgen (21 wegens thema mobiliteit, 07 wegens nieuw subthema gemeentemonitor). MAAR bijvoorbeeld censusdata krijgen ook een eigen nummer (nummer 90). Is het in dat geval beter om de gemeentemonitor meteen een eigen 'hoofdthemanummer' toe te kennen, ervan uitgaande dat er potentieel nog meer indicatoren van deze bron zullen worden opgenomen? In dat geval zouden de mobiliteitsindicatoren bijvoorbeeld 9101 kunnen zijn (91 voor thema 'gemeentemonitor', 01 voor subthema 'mobiliteit'...).

**Comment by Emilien-Dupont** [comment]
Hej Hanne,

Indien je zeker bent dat alles van de gemeentemonitor onder 'mobiliteit' zal komen, kan je deze volgens mij wel onder 21xx zetten. Anders zou ik er een apart themanummer van maken. Mogelijks is dit de reden waarom censusdata een eigen nummer kreeg omdat dit over verschillende thema's gaat.
Als je vermoed dat dit complexer gaat worden, zou ik 211X gebruiken voor deze data, zie bv erfgoed. 

De documentatie hieromtrent vind je [hier](https://github.com/provinciesincijfers/JiveDocumentation/blob/master/03.%20Onderwerpentabel/Informatie%20over%20de%20belangrijkste%20velden.md).

Ik zou het sowieso eerst nog wel op de redactiegroep laten passeren, evtl via mail als het dringend is.

**Comment by HanneODB-VLBR** [comment]
Dag Emilien

Ik ben niet zeker dat alles van de gemeentemonitor onder mobiliteit zal komen => de gemeentemonitor heeft uiteenlopende thema's (armoede, cultuur & vrije tijd, demografie, economie, klimaat/milieu/natuur, lokaal bestuur, mobiliteit, onderwijs & vorming, ruimte, samenleven, werk, wonen & woonomgeving, zorg & gezondheid). Momenteel is er volgens mij nog geen sprake om indicatoren uit deze andere thema's over te nemen op PinC, maar het lijkt me altijd wel mogelijk in de toekomst. Dus dan pak ik misschien toch best een thema voor de gemeentemonitor afzonderlijk? En welk dan best? => de thematische nummering loopt tot 50, en dan wordt er een sprong gemaakt naar 90 voor de census. Waarom is dat precies? Neem ik dan 91? Of meteen best 100? Wat betreft je vraag over dringendheid: tja, het is niet superdringend in de zin dat er niemand onmiddellijk op zit te wachten denk ik, maar ik ben er nu mee bezig en zou er graag aan verder werken. Wanneer is de eerstvolgende redactiegroepvergadering?

**Comment by Emilien-Dupont** [comment]
Dan lijkt mij op het eerste zicht het beste om een nieuw nummer te nemen. 

@StefanJacques @StefanieWVL @veravandestraat @Lievendr @VickyVB 
Kunnen jullie jullie licht hier op schijnen?

**Comment by Emilien-Dupont** [comment]
(van Stefan)
Je kan twee richtingen uit, die allebei even goed zijn … dus laat de meerderheid maar beslissen 😉
•	Als elke themaverantwoordelijke zijn gemeentemonitordata verwerkt voor PinC, kan ieder gerust een nieuw nummerke in zijn rubriek aanmaken
•	Als we op termijn in bulk gemeentemonitordata afladen, zou je kunnen samenbrengen in een nieuwe rubriek “80”

Alleszins, wat je ook kiest, door de verschillende opzoekmogelijkheden in de studio kan je op termijn gemakkelijk de gemeentemonitoronderwerpen bij elkaar brengen (source=gemeentemonitor) als ze toch onder verschillende rubrieknummers zouden zitten.

Waarom er die sprong is naar “90” heeft geen grote betekenis, hoor 😊

Groetjes
Stefan

@Hanne – ondertussen kan je toch al gemakkelijk INTERN werken met een door jou gekozen nummerset (en bij consensus nog snel veranderen in wat iedereen wil, toch ???)

**Comment by Tine-VB** [comment]
Samenbrengen van de data onder 1 nummer is hier misschien toch makkelijker, aangezien het over een specifiek type data gaat, namelijk uit een survey. Anderzijds kan je ze ook makkelijk bijeen brengen, zoals Stefan aangeeft. En we krijgen dan op de duur nogal veel basisnummers? Als we naar 100 gaan, betekent dit dan dat het een 5-nummerige code wordt?

**Comment by HanneODB-VLBR** [comment]
Ik merk dat er geen eenduidige meningen zijn en er dus ook geen echte richtlijn is hierrond... Maar Stefaan en Tine lijken precies toch ook een lichte voorkeur te hebben voor 2107, thema mobiliteit met subthema gemeentemonitor. Dus dat is de optie waar ik voor zal gaan. Zoals Stefan aangeeft, kan natuurlijk altijd nog aangepast worden indien echt nodig....

**Comment by joostschouppe** [comment]
De unieke codes dienen in de eerste plaats voor ons eigen gemak. En het gemak is bundelen in functie van verwerkingsprocessen. Wellicht gaan verwerkingsprocessen van de gemeentemonitor bevragingen steeds heel dicht bij elkaar blijven, ook als we meer dan enkel mobiliteit zouden overnemen. Vandaar een voorkeur om een nieuwe hoofdreeks 91XX te gebruiken voor data die uit de gemeentemonitor komen. Als dit te veel opkuiswerk zou betekenen, dan hoeft het niet per sé. Maar het later aanpassen is uitgesloten. Toekomstgericht lijkt het me beter om de aanpassing dus wél te doen.

**Comment by HanneODB-VLBR** [comment]
Oké. Ik had ze intussen inderdaad wel al ingeladen onder een andere code (2170)
Wat is de meest handige manier om deze zo efficiënt en foutloos mogelijk te veranderen naar een nieuwe code?
-Is er een manier om binnen PinC in bulk alle 2170 in deze indicatoren te vervangen door de nieuwe cijfercode?
-Eventueel: alles opnieuw opladen met nieuwe code, vervolgens alle 2170 verwijderen uit PinC en dan de nieuwe terug op de juiste plek in de themaboom zetten
-Eventueel: alles één voor één handmatig vervangen (persoonlijk mijn minst favoriete optie, maar als t niet anders kan so be it...)

**Comment by HanneODB-VLBR** [comment]
Aangepast
