### ISSUE TITLE
Kleine verbeteringen in leeswijzer rapporten

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#278]
Op vraag van Stefan zouden we een aantal kleine tekstuele verbeteringen aanbrengen in de leeswijzer voor rapporten.
@StefanJacques  @Tine-VB.

@davidcardinaels: kan jij dit na goedkeuring redactiegroep uitrollen?

![aanpassingen_leeswijzer](https://user-images.githubusercontent.com/77432663/148533926-25d179ad-1aea-49d4-a89a-a6f3eb0b63bb.png)

**Comment by davidcardinaels** [comment]
Ik breng het na goedkeuring in orde.

**Comment by joostschouppe** [comment]
Goedgekeurd op redactiegroep
