### ISSUE TITLE
Jaartal cijfers MoWa

### ISSUE THREAD

**Issue by Tanja-OVL** [provinciesincijfers/PinC-taakopvolging#279]
Mail Birgit Van Laar van MoWa Vlaanderen: "Een kleine bemerking daarbij: het jaartal zou beter verwijzen naar 2020 i.p.v. 2021 (de cijfers zijn inderdaad genomen op 1/1/2021, maar zijn bedoeld als afsluiter voor 2020). Zou je dat kunnen aanpassen aub?"

**Comment by veravandestraat** [comment]
#205

**Comment by joostschouppe** [comment]
Wat heb je hier mee gedaan?

Zoals je bij "bronnen" op Dashboard kunt lezen, kunnen we op die vraag niet ingaan:

*Doordat we diverse bronnen samenbrengen, moeten we harmoniseren. Heel wat bronnen zijn gebaseerd op een momentopname rond nieuwjaar. In de helft van de gevallen beschouwen die bronnen dat als 31 december, in de andere helft als 1 januari. Wij hebben de keuze gemaakt om deze steeds weer te geven alsof het om 1 januari gaat. Daarom kan het zijn dat je bij de oorspronkelijke bronnen een ander jaartal ziet voor dezelfde data.*

**Comment by Tanja-OVL** [comment]
Dag Joost

Hopelijk een fijn verlof gehad?
Ik heb dit issue 279 gesloten omdat we het onder issue 205 hebben geplaatst (Vera vond het daar beter passen) en daar staat het open. Het zou op de volgende redactieraad komen.
Ik heb er anders nog niks mee gedaan, alleen gemeld aan MoWa dat we dit steeds op dezelfde manier willen doen en dat we aan 1/1/2021 altijd het jaar 2021 geven. Ik denk niet dat ze er een groot probleem van gaan maken...
Ik heb ondertussen hun cijfers op 1/1/2022 ontvangen en zal ze binnenkort klaarzetten om op te laden.

Groeten
Tanja

Van: Joost ***@***.***>
Verzonden: maandag 24 januari 2022 9:51
Aan: provinciesincijfers/PinC-taakopvolging ***@***.***>
CC: Termote Tanja ***@***.***>; State change ***@***.***>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] Jaartal cijfers MoWa (Issue #279)


Wat heb je hier mee gedaan?

Zoals je bij "bronnen" op Dashboard kunt lezen, kunnen we op die vraag niet ingaan:

Doordat we diverse bronnen samenbrengen, moeten we harmoniseren. Heel wat bronnen zijn gebaseerd op een momentopname rond nieuwjaar. In de helft van de gevallen beschouwen die bronnen dat als 31 december, in de andere helft als 1 januari. Wij hebben de keuze gemaakt om deze steeds weer te geven alsof het om 1 januari gaat. Daarom kan het zijn dat je bij de oorspronkelijke bronnen een ander jaartal ziet voor dezelfde data.

—
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fsecure%2dweb.cisco.com%2f1%2di42I50a2i%5ftqTlBO7X%2dD2H5VmTpKke%2dHKoQjso9CD1jouoQmoqbx6FBktEVXa34ho9w033WShGSRjwguqOpoa0WT8VybYxm9N2Xa5gzJHsxkv48Mgpa50q5dcDfGhU9u%2dBU4mn2QXzG0ZQBPWfCJkJpjQNl%2dvxC8RJ4O73%2d0NcQwroB78WWWahMN8SApOQxdteNBUX37O95CqTclMu5OiZH2lFV4%5fZU%2d51cP2NLIC21QsI0IC2m2NA%2d1RPI9w62GDZO2R5OreGmz9BoU5xvlpCiBxGHD7OMDoYK1qwqDOycQzq%2duE4nKJyKra%2dnmkk9%2fhttps%253A%252F%252Fgithub.com%252Fprovinciesincijfers%252FPinC%2dtaakopvolging%252Fissues%252F279%2523issuecomment%2d1019856618&umid=d428a2a9-9eeb-4977-8e86-aaec648e83e6&auth=1dca850097f80205f58678954875a011e5c11307-48257666cc046298adc7cbe5bd145f43390e82eb>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fsecure%2dweb.cisco.com%2f15Lg44RED0cM4z8ZQ44x%2dZquMUrqXJPLU3rFhV60vmCNRLkkc80Wku%5fjoRiedcoyKJpA4lSp7qw6wxav8D8EfWzG1SHjusL%2dJY8nYc889YUHmQxmyZ3u4LtYYo9DoXFopNm0hwDIMXE%2dQsB3THe4CrHbnw4%2d3alFTWOtCl8VyxA31IpgX%2dsAfCWMj8j5Drlsts0U52y0yoW4Po8D16ho1%2dmO1pXqn76eACQD075rRQ%5fVCGmv3RiL5De9lw5otT%2dns2OhzefI6GMxybmwB6fUTW%2dKGJ9XUUtL9xrP4UGDLONZQFnkeoeP5v1LB7CD8GQvL%2fhttps%253A%252F%252Fgithub.com%252Fnotifications%252Funsubscribe%2dauth%252FAR4AJ5WZWCJV366QGUPDKU3UXUHHVANCNFSM5L3J2X2Q&umid=d428a2a9-9eeb-4977-8e86-aaec648e83e6&auth=1dca850097f80205f58678954875a011e5c11307-5f7843566218480cbd74c67bb0bf6fd119b3bedd>.
Triage notifications on the go with GitHub Mobile for iOS<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fapps.apple.com%2fapp%2fapple%2dstore%2fid1477376905%3fct%3dnotification%2demail%26mt%3d8%26pt%3d524675&umid=d428a2a9-9eeb-4977-8e86-aaec648e83e6&auth=1dca850097f80205f58678954875a011e5c11307-fbfdff4429c91b598cb8331b77342678d13855f1> or Android<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fplay.google.com%2fstore%2fapps%2fdetails%3fid%3dcom.github.android%26referrer%3dutm%5fcampaign%253Dnotification%2demail%2526utm%5fmedium%253Demail%2526utm%5fsource%253Dgithub&umid=d428a2a9-9eeb-4977-8e86-aaec648e83e6&auth=1dca850097f80205f58678954875a011e5c11307-f29e94d6ffa14d12c8d87f7134978b1651a180c3>.

**Comment by joostschouppe** [comment]
Ha, dat had ik niet gezien. Verdere opvolging via #205
