### ISSUE TITLE
Controleren of hele presentaties kunnen vervallen tijdens laden van rapport

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#28]
Overbodige presentaties volledig laten vallen
Presentaties die enkel in bepaalde gevallen nuttig zijn in conditionele sectie steken, ook in deel swingcode

- [x] Kerncijfers
- [ ] Demografie
- [ ] Armoede
- [ ] Wonen
- [ ] Onderwijs
- [x] Economie steekkaart
- [x] Ouderenzorg
- [x] Veiligheid
- [ ] Klimaat
- [ ] Detailhandel

**Comment by davidcardinaels** [comment]
Ik heb alle overbodige presentaties verwijderd. Als ik bij ouderenzorg test dan merk ik wel geen verschil tussen de versie met presentaties in conditionele secties en de versie zonder.
Ik dacht ook dat Edward ooit zei dat alle presentaties sowieso worden ingeladen, of ze nu gebruikt worden of niet.

**Comment by joostschouppe** [comment]
Hoe bedoel je dat je geen verschil merkt bij ouderenzorg? In laadsnelheid?
Wat @EdwardABF mij heeft uitgelegd, is als volgt:
- als je een presentatie oproept in de code, dan wordt ze sowieso geladen, zelfs al toon je ze niet in het rapport
- als je een presentatie enkel oproept onder bepaalde condities, dan wordt ze enkel geladen indien de conditie van toepassing is. Dat is eigenlijk logisch, aangezien je binnen die condities situaties kunt hebben die helemaal niet kunnen (bijvoorbeeld "toon iets over het tweede gebied" als er slechts één gebied is)
Als je effectief in alle rapporten die hebt nagekeken, dan mag je deze taak afsluiten hé
