### ISSUE TITLE
Woongelegenheid naar recentste wijziging 2015-2020

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#280]
Ik kreeg onderstaande vraag van Frederika Torfs (Klimaat OVL):

_Ik heb een vraagje ivm een parameter die ik terugvind in het rapport wonen van provincies in cijfers. Daar staat een parameter in rond “Woongelegenheid naar recentste wijziging (gebouwd of grondig verbouwd)” en dit per periode._ 

_Wat ons interesseert is deze parameter voor de periode 2015-2020 (en niet 2011-2020). Dat komt immers overeen met de eisen uit de Vlaams renovatiestrategie (Om de ambitieuze doelstellingen uit de Klimaatstrategie te realiseren moeten bestaande woongebouwen uiterlijk in 2050 een vergelijkbaar energieprestatieniveau halen als nieuwbouwwoningen met vergunningsaanvraag in 2015)._ 

_Is dat iets dat uit provincies in cijfers kan gehaald worden? Of hebben jullie dit enkel voor 2011-2020?_

Chris denkt op basis van de code dat het mogelijk is om deze indicator aan te maken. Als het een eis is uit de Vlaamse renovatiestrategie lijkt het me een interessante indicator voor gemeenten, maar wat denken jullie (en de kadasterwerkgroep)?

**Comment by joostschouppe** [comment]
We zetten het enkel in de map Klimaat

**Comment by joostschouppe** [comment]
Extern gezet (klimaat + beschikbaar op statsec) en voorzien van voetnoot ivm de opmerking hier
