### ISSUE TITLE
[percentage] vanvoor of vanachter?

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#283]
Volgens [de regeltjes](https://github.com/provinciesincijfers/JiveDocumentation/blob/master/03.%20Onderwerpentabel/Informatie%20over%20de%20belangrijkste%20velden.md#beschrijving) ziet een Beschrijving (Description) er zo uit:

`ENQUETE - Het aantal blabla gedeeld door het aantal blieblie [percentage]
`
De regels zijn:
* _In het geval van enquête, prognose, of model komt dit vooraan in drukletters._ 
* _De beschrijving eindigt bij een berekend onderwerp met [percentage], [promille], [ratio], … . Het type komt m.a.w. tussen de vierkante haakjes._

In de praktijk is echter [percentage] etc VANVOOR gezet en is de regel ivm modellen en enquetes NOG NIET DOORGEVOERD.

De huidige situatie is deze:

  | Niks vanachter | Wel iets vanachter
-- | -- | --
Niets vanvoor | 1452 | 656
Wel iets vanvoor | 6396 | 1

Ongeveer alle gevallen waar er achteraan iets staat, is het dit: [bevolkingsvooruitzichten SV 2021-2040]

De afspraken zoals ze nu bestaan, [lijken grotendeels hier afgesproken](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/220#issuecomment-806801369). We hebben [eerder ook ooit afgesproken]( https://github.com/provinciesincijfers/PinC-taakopvolging/issues/181#issuecomment-747320841) om [percentage] etc VOORAAN te zetten. 
Wellicht is er iets mis gegaan tijdens de omzetting van Alfresco naar JiveDocumentation; de regels hebben net in die periode vaak ter discussie gestaan. Met wat er in deze gelinkte tickets staat, en met wat verdere concretisering zou de regel als volgt aangepast moeten worden in JiveDocumentation: 

* _In het geval van enquête, prognose, of model komt dit vooraan in drukletters._ 
* _Bij een berekend onderwerp begint de beschrijving met [percentage], [promille], [ratio], … . Het type komt m.a.w. tussen de vierkante haakjes. Indien er een melding ivm enquête, prognose etc. is dan staat die op de eerste plaats. Je krijgt dan dus iets als ENQUETE [percentage] Omschrijving_

Er vanuit gaande dat dit een bevestiging is van wat eerder afgesproken is, graag jullie feedback: "akkoord" of "wil ik het toch nog even over hebben"

**Comment by Tine-VB** [comment]
Volgens mij was de laatste definitieve afspraak dat het percentage tussen haken ervoor zou komen, zodat het conform is met alle beschrijvingen. Enquête of prognose gingen we dan op een andere manier aangeven (ik heb dat, denk ik, bij mijn grote controle inderdaad achteraan gezet, maar toen waren er nog geen enquêtegegevens en over modellen was ook nog niets afgesproken. Ik dacht dat het voorstel was: ENQUÊTE [percentage] blablabla. Maar dat zit al ver.

**Comment by Tine-VB** [comment]
Akkoord (natuurlijk)

**Comment by HildeC** [comment]
akkoord

**Comment by Lievendr** [comment]
akkoord

**Comment by veravandestraat** [comment]
akkoord

**Comment by StefanJacques** [comment]
Limburg gaat akkoord
