### ISSUE TITLE
bronnenpagina op het dashboard actualiseren

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#287]
https://provincies.incijfers.be/dashboard/dashboard/bronnen-2/

- zijn alle bronnen nog steeds weergegeven op deze pagina ?
- werken alle hyperlinks nog ?
vb. kapotte link: https://omgeving.vlaanderen.be/energie-klimaat-en-milieu
--> nu aangepast naar https://omgeving.vlaanderen.be/klimaat-en-milieu

**Comment by KoenSnyers** [comment]
Bronnenpagina is nagekeken, alle links zijn gecheckt, plus waar nodig zijn benaming en/of logo aangepast.
Wat ik niet heb gedaan, is gecheckt of alle bronnen erop staan, omdat dat beter gebeurt door de themaverantwoordelijken, lijkt me.

**Comment by veravandestraat** [comment]
Monumentenwacht Vlaanderen staat er nog niet op. @KoenSnyers ik vraag @Tanja-OVL om je een logo en de link naar de website te bezorgen.

**Comment by StefanJacques** [comment]
In bijgevoegd Excel-bestand vind je de vergelijking die david maakte tussen "Sources" en "bronnen op dashboard"
Ik heb er zelf in kolom E de verantwoordelijke provincie bijgezet.

TO DO
iedere provincie vult in kolom F de hyperlink toe naar de bron (of vult **"niet nodig"** in kolom E aan, als er geen LOGO van de dataleverancier nodig is) en zorg ook voor het LOGO.

Vink aan als je taak er op zit
- [ ] Antwerpen
- [ ] Limburg
- [ ] Oost-Vlaanderen
- [ ] Vlaams-Brabant
- [ ] West-Vlaanderen

Dan kan Koen alles samenbrengen op https://provincies.incijfers.be/dashboard/dashboard/bronnen

[Bronnen_dashboard.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/12766512/Bronnen_dashboard.xlsx)

**Comment by Lievendr** [comment]
Bronnen bijgevuld en excel op Teams gezet;

https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Redactiegroep%20PinC/[Bronnen_dashboard.xlsx](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Redactiegroep%20PinC/Bronnen_dashboard.xlsx?d=wc8682e53fe684b88be13f5dc6431f04f&csf=1&web=1&e=lc5klg)?d=wc8682e53fe684b88be13f5dc6431f04f&csf=1&web=1&e=lc5klg

**Comment by Lievendr** [comment]
excel staat nu ook op Teams

https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Redactiegroep%20PinC/Bronnen_dashboard.xlsx?d=wc8682e53fe684b88be13f5dc6431f04f&csf=1&web=1&e=oedQkS

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
We zetten de bronnen in alfabetische volgorde

**Comment by StefanieWVL** [comment]
Akkoord met de voorstellen tot aanpassingen

Andere vragen:
- veel gebruikte afkortingen zou ik wel vermelden
- voor mij mag het de korte versie zijn, kadaster en rijksregister, de rest is wel gekend. Maar belangrijkste is toch het consequent zijn. 
- Idem: korte versie ok maar toch indien lange versie > voor beiden dan

**Comment by Emilien-Dupont** [comment]
Redactiegroep 23/11
Tegen 1/12 klopt iedereen het af.

**Comment by dgees** [comment]
Agentschap Zorg & Gezondheid en dept. WVG zijn nu samen Departement Zorg
https://www.vlaanderen.be/departement-zorg/over-ons/huisstijl-departement-zorg

**Comment by dgees** [comment]
VMSW vervangen door 'Wonen in Vlaanderen'

**Comment by dgees** [comment]
https://overheid.vlaanderen.be/communicatie/huisstijl-en-merkbeleid/overzicht-niveaus-en-kleuren-per-entiteit
Hier kunnen we een check doen of alle logo's van Vlaamse entiteiten nog kloppen.

**Comment by Emilien-Dupont** [comment]
Na feedback Deirdre:
We passen de verouderde namen aan in de Datasourcestabel, metadatafiches en ook checken in rapporten wanneer het hardcoded staat. 
AZG: LIM, WVG: IP, VMSW: WVL
Moet ook aangepast worden in de bronnenpagina op het dashboard.

**Comment by StefanJacques** [comment]
Als de Redactiegroep de aanpassingen nakijkt op
[https://provincies.incijfers.be/dashboard/dashboard/bronnen](url)
kunnen we dit ticket afsluiten.

**Comment by veravandestraat** [comment]
- [ ] Antwerpen
- [ ] Limburg
- [ ] Vlaams-Brabant
- [ ] Oost-Vlaanderen
- [ ] West-Vlaanderen

**Comment by dgees** [comment]
ABB, Digitaal Vlaanderen en Dierenwelzijn wijken nog af van de andere Vlaamse logo's. Bij Digitaal Vlaanderen moet ook het woordje 'Agentschap' verwijderd worden. 

logo voor ABB én DV (volgens huisstijlsite Vlaanderen)
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/61278349/65214bae-4fb6-4bac-afe4-7e0d89253e59)

logo voor dierenwelzijn (hebben ze zelf nog niet eens op hun huisstijl site gezet)
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/61278349/92abee2b-a6b8-473f-a55c-6c45c8222821)

Steunpunt Werk en INBO wijken ook wat af maar die wijken zelf af op hun eigen websites dus daar vind ik de logo keuze op PinC prima.

**Comment by KoenSnyers** [comment]
Voorgestelde aanpassingen zijn doorgevoerd, @dgees.
