### ISSUE TITLE
lay out van links is niet goed op metadatafiche gebiedsniveaus

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#288]
De informatiefiche over gebiedsniveaus wordt in de user interface niet goed getoond ([stand alone](https://provincies.incijfers.be/info/9900_gebiedsniveaus.html), [in studio](https://provincies.incijfers.be/admin/studio/File?type=info)). 

![afbeelding](https://user-images.githubusercontent.com/10122639/162010082-c626c358-899b-46b3-a3cf-82b7e66d0369.png)

De ipo_dynamic.css wordt blijkbaar overruled door de standaard CSS.

**Comment by GeertBonte** [comment]
Probleem opgelost.

**Comment by GeertBonte** [comment]
Opgelost door dit toe te voegen aan ipo_dynamic.css:

```
.jqmWindow a:not(a.sp-cancel):not(a.disabled) {
	text-decoration: underline;
}
```
