### ISSUE TITLE
Issue met kubusdimensieniveaus rond huishoudens

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#292]
In de kubussen met auto’s per gezin zoals deze https://provincies.incijfers.be/jive?workspace_guid=19883402-4403-4401-8834-bb1d6af6d24d wordt er gesproken over gezinstype maar staat in de dimensieniveauitems “lid van gezin blabla”, wat de termen zijn voor individuen. Maar kan niet zomaar aangepast worden: eerst nakijken welke kubussen die niveaus ook gebruiken. Daarnaast opletten:  hhtype (lipro 8, een individu-benaming) wordt nu geaggregeerd naar hhtype_6k en hhtype_alleen_collect (huishoudensbenamingen), da's niet logisch!

**Comment by joostschouppe** [comment]
Autobezit is gekoppeld aan `hhtype`. Dat behoort tot de Dimension type_huishouden. Daarnaast hebben we ook `hhpos`.

`type_huishouden` lijkt voor huishoudens gemaakt, `hhpos` voor inwoners van huishoudens
Maar enkele van `type_huishouden` zijn geschreven als "type", andere als "inwoner van type"

De DimensionLevels die hier bij horen:

DimensionLevel | DL Name | Inhoud | Dimension
-- | -- | -- | --
hhtype | type huishouden (LIPRO 8 klassen) | geschreven als "inwoner van gezin van type" | type_huishouden
hhtype_6k | type huishouden (LIPRO 6 klassen) | geschreven als "gezin van type" | type_huishouden
hhtype_alleen_collect | type huishouden (alleen/gezin/collectief) | geschreven als "inwoner van gezin van type" | type_huishouden
hhtype2 | type huishouden | geschreven als "gezin van type" | type_huishouden
hhpos | positie in huishouden (LIPRO 12 klassen) | geschreven als "inwoner van gezin van type" | positie_in_huishouden
hhpos_simp | positie in huishouden (LIPRO 9 klassen) | geschreven als "inwoner van gezin van type" | positie_in_huishouden

De aggregaties:

Van |   | naar
-- | -- | --
hhtype | > | hhtype_6k
hhtype | > | alleen_collect
hhpos | > | hhpos_simp

Via **Consistency check** > _Dimensions used by indicators_ kunnen we kijken welke kubussen dit alles echt gebruiken

Eigenlijk wordt dit vooral gebruikt voor `kubus1114_lft_gesl_hhpos_hhtype`, waar BEIDE nodig zijn. Met andere woorden: beide zijn nuttig en beide tellen eigenlijk inwoners! De terminologie moet dus anders: in alle gevallen gaat het om "inwoners". In het ene geval om "inwoners volgens gezinspositie", in het andere "inwoners volgens gezinstype"

Voor een ontwikkelkubus kadaster (ping @demaesschalckfilip ) en die van het autobezit werken we WEL op niveau van echte huishoudens. Er is dus een NIEUWE Dimension met bijhorende DimensionLevels nodig!

Dus heb ik volgende aanpassingen gedaan:
- `hhtype2` bestaat enkel voor de kubus kadaster, en mag dus eigenlijk weg of vervangen worden door een "echte" huishoudensindeling. Voorlopig is het goed dat die NIET geaggregeerd wordt naar andere dimensionlevels van niet-echte huishoudenstypes.
- **beschrijving** toegevoegd aan Dimension _type_huishouden_ en _positie_in_huishouden_ om duidelijk te maken dat het altijd om inwoners gaat
- naamgeving van de DimensionLevels van `type_huishouden` aangepast met "inwoner van" om dit duidelijk te maken
- ontbrekende dimensie-aggregatie `hhtype_6k` > `hhtype_alleen_collect` toegevoegd (niet echt nodig, maar maakt het logisch consistent)
- nieuwe Dimension aangemaakt die écht voor huishoudens is bedoeld, met bijhorende DimensionLevels en aggregaties

@VickyVB om in te stappen op de nieuwe dimensie die echt bedoeld is om huishoudens te tellen, kan je gewoon je oude uploadfiles nemen, het kolomhoofd dat `hhtype` of iets dergelijks bevat vervangen door `echt_hhtype` (of variatie op thema) en de bestaande data vervangen door de nieuwe data.

**Comment by VickyVB** [comment]
Merci! De wagenbezitkubussen zijn aangepast.
