### ISSUE TITLE
Nieuwe release: metadata aanpassingen

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#293]
Er komt een I-icoontje in de databank!
![afbeelding](https://user-images.githubusercontent.com/10122639/157480813-ef115062-9276-4ca5-8727-38acc4d47dd5.png)!
Misschien kunnen we nu al overstappen naar nieuwe metadatasysteem, maar wel enkele nieuwe issues; zie het [document over Metadata & opvolging](https://docs.google.com/document/d/1EN3ZxigfXtgKtxq1Lmfj2MWvaZZOVGJ3kQRCKfbfGFw/edit)
Alles kan getest worden in de accept-versie:
[Databank](https://accept-provincies.incijfers.be/databank?workspace_guid=153f162f-08de-49d4-85a9-ee022e64448a)
[Dashboard](https://accept-provincies.incijfers.be/dashboard/speeltuin/)

## Nieuwe afspraken aan onze kant
* Volledig afschaffen eigen fiches, enkel nog indien een bijlage nodig is, kan dit in een bestand
* Weergave in Dashboard volledig via parameters

(dit ticket is enkel voor opmerkingen nav aanpassingen bij ABF bij release van maart 2022. Algemene opvolging via #65 en het reedsgelinkte Drive document)

**Comment by joostschouppe** [comment]
We hebben geanalyseerd in hoeverre de nieuwe versie die eind deze maand komt, reeds gebruikt kan worden om de overstap te maken naar het nieuwe model metadata. Er is eigenlijk maar één groot bezwaar op dit moment. 
In de user interface in Databank zijn er nog geen aliassen mogelijk, dus verschijnt "vergelijkbaarheid in de tijd" en "beperkingen op de data" met een stomme heading:
![afbeelding](https://user-images.githubusercontent.com/10122639/158172108-25b177fe-10a3-40f7-9524-2ba517fbb60a.png)

Opties: 
* voorlopig deze velden geheel verbergen; 
* voorlopig deze lelijke titels negeren (en in het tekstveld zelf de titel van het veld aanvullen)
* lancering uitstellen

Nadat hierover beslist is moet dit aangevuld worden in de handleiding en enkele afspraken ivm vormgeving afgetoetst worden.

**Comment by Lievendr** [comment]
tja meningen, smaken... het is mottig om het met Joost te zeggen, maar oogt amateuristisch. Weglaten is ook geen optie. Blijft over: uitstellen. Beter goed dan ongelukkig.

**Comment by veravandestraat** [comment]
Ik volg Lieven.
(al is het alleen al omdat het text met een x is)

**Comment by StefanieWVL** [comment]
Ik volg Lieven en Vera

**Comment by joostschouppe** [comment]
Nog suggesties voor ABF
* instelbaarheid volgorde van de velden
* naam aanpasbaar maken van de velden... (of "meer info" naar "Inhoudelijke informatie" of iets dergelijks)
* broninfo vanvoor zetten in het lijstje in Viewer (dus eerst Bron, dan Onderwerp dan Gebiedsniveau)

**Comment by joostschouppe** [comment]
Tijdens uitrol URLs met woord Jive vernieuwen; zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/296

**Comment by joostschouppe** [comment]
Vedere opvolging via https://github.com/provinciesincijfers/PinC-taakopvolging/issues/318
