### ISSUE TITLE
EPC data via https://www.energiesparen.be/energiekaart

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#295]
En er staan wellicht nog wel interessante dingen op.

Op het eerste zich is de data niet exporteerbaar.

cc @demaesschalckfilip

**Comment by joostschouppe** [comment]
De collega's van Klimaat zijn hier ondertussen al achteraan aan het gaan.

**Comment by joostschouppe** [comment]
We zoeken nog iemand die de EPC data wil afhalen van de energiekaart. DIt moet noodzakelijk beperkt blijven, omdat het heel omslachtig is.

Daarnaast graag advies over het volgende. Blijkbaar maakt VEKA een inschatting van het gehele woningpark op basis van EPB, EPC en kadaster. Twee vragen:
- weten we met de info hieronder inhoudelijk genoeg om er op verder te gaan?
- wie heeft zin om een scriptje te maken dat de nodige data uit de API afhaalt?

Info:
Voor gegevens over enkel het bestaande woningenpark verwijzen we graag door naar de Energiekaart, waar de gegevens van de EPC-databank raadpleegbaar zijn per gemeente. Wanneer u daar filtert op bouwjaar VOOR 2006, krijgt u enkel de gegevens van woningen en appartementen die dateren van voor het in voege gaan van de EPB-eisen. Deze gegevens zijn niet beschikbaar op statistische sector-niveau. 
 
Voor een gewogen gemiddelde van EPB en EPC is er inderdaad een API labelverdeling woningpark beschikbaar tot op gemeente-niveau. Ook hier geen gegevens op niveau van de statische sector.
Deze API geeft een schatting van de energieprestatie van de volledige woningvoorraad op basis van een gewogen gemiddelde van EPB- en EPC-cijfers. Bij de EPC-cijfers gebruiken we enkel die woningen en appartementen die gebouwd zijn voor 2006. Voor woningen en appartementen gebouwd na 2006 gebruiken we de EPB-cijfers (nieuwbouw). Voor kleinere gemeentes is oplettendheid geboden gezien het kleinere aantal EPC's en EPB-aangiftes dat daar beschikbaar is. Is het aantal te klein, dan wordt de labelverdeling sowieso niet meegegeven.
Deze labelverdelingen worden jaarlijks ge-updatet. Dit kan pas gebeuren in het najaar, aangezien de nodige update-gegevens van het kadaster dan pas beschikbaar zijn. De meest recente labelverdeling die we nu hebben, is dus die van referentiedatum 1 januari 2021. Binnen een paar weken kunnen we dan terug updaten voor referentiedatum 1 januari 2022.
 
De API is vrij beschikbaar. De inputparameters zijn:
locatie = Vlaanderen, de naam van de provincie of de naam van de gemeente
type = Vlaanderen, provincie of gemeente
referentiejaar = jaartal waarvoor de labelverdeling gewenst is.Zijn momenteel beschikbaar: 2019, 202, 2021 Wordt het referentiejaar niet meegeven, dan wordt meest recente referentiejaar meegegeven
typologie = typologie waarvoor de labelverdeling gewenst is. Keuze uit: appartement, open, halfopen, gesloten, alle woningen (geheel van open, halfopen en gesloten) en alle types (geheel van alle woningen en appartement). Wordt typologie niet meegeven, dan wordt lijst meegegeven van alle beschikbare typologieën.
 
Hier wat voorbeelden:
- labelverdeling Vlaanderen, referentiemoment 1 januari 2019, alle types: https://energie.api.vlaanderen.be/labels-api/v1/api/epc-label?locatie=Vlaanderen&type=Vlaanderen&referentiejaar=2019&typologie=ALLE%20TYPES
- labelverdeling Bekkevoort, referentiemoment 1 januari 2021, enkel de eengezinswoningen:https://energie.api.vlaanderen.be/labels-api/v1/api/epc-label?locatie=Bekkevoort&type=gemeente&referentiejaar=2021&typologie=ALLE%20WONINGEN
- labelverdeling provincie Antwerpen, meest recente referentiemoment (dan referentiejaar niet meegeven), enkel de appartementen: https://energie.api.vlaanderen.be/labels-api/v1/api/epc-label?locatie=Antwerpen&type=provincie&typologie=APPARTEMENT 
 
Om te weten welke hoofdgemeenten beschikbaar zijn, is er deze API ontwikkeld: https://energie.api.vlaanderen.be/labels-api/v1/api/locatieInfos/ . Deze laat toe om op basis van de eerste letters te achterhalen welke gemeenten een labelverdeling beschikbaar hebben. Bijv:
https://energie.api.vlaanderen.be/labels-api/v1/api/locatieInfos/sint geeft lijst van gemeentes die starten met sint
https://energie.api.vlaanderen.be/labels-api/v1/api/locatieInfos/aar geeft lijst van gemeenste die starten met aar. Etc.

**Comment by StefanJacques** [comment]
louter ter info
ik heb bovenstaande vraag besproken met de 2 trekkers van het rapport Klimaat en Energie.

Hun antwoorden:
_Kim Rienckens (Klimaat, OVL)_
In het rapport zit EPC onder de sector huishoudens Nathalie (WVL). Kris (ANT) is wel veel meer vertrouwd met dit soort data.
_Nele Vandenreyt (Klimaat, LIM):_
Bij de afspraken voor uitbreiding van het rapport was het ook de tandem Kris (ANT) en Nathalie (WVL) die inhoud en data rond huishoudens samen gingen uitzoeken, maar inderdaad eindverantwoordelijke Nathalie.

**Comment by joostschouppe** [comment]
Redactiegroep:
- Joost blijft vragen om deftige data toegang
- Filip probeert de data uit de webtoepassing te halen
- gemodelleerde data is interessant. Joost brieft @GeertBonte over wat er precies moet gebeuren

**Comment by GeertBonte** [comment]
Ik ben bezig met het schrijven van een Python-script om alle data geautomatiseerd af te halen en te bundelen in een Excel-bestand. De eerste testen zijn veelbelovend.

**Comment by GeertBonte** [comment]
Mission accomplished. Met succes alle data afgehaald met Python.

**Comment by StefanJacques** [comment]
schitterend Geert !!!

**Comment by Lievendr** [comment]
inderdaad...great job!

**Comment by demaesschalckfilip** [comment]
Ik heb ondertussen, middels een record aantal kliks, alle EPC-data afgehaald van 2012 t/m 2022: voor appartementen en eengezinswoningen (onderverdeeld naar vrijstaand, halfopen, open), telkens onderverdeeld naar verkoop/verhuur. Ik zal een reeks variabelen maken en in eerste instantie intern zetten. Daar blijkt al een nummer voor: 2206 (EPB is 2207). De data van Geert zijn, begrijp ik, een mengeling van EPB en EPC, dus dat wordt dan een ander nummer (2213 is nog vrij, maar eigenlijk ook 2205: daar staat woonpremies bij, maar die blijken het nummer 2211 te krijgen)?

**Comment by joostschouppe** [comment]
Lijkt ;e het handigste als je hiervoor inderdaad 2205 voor inpikt. 
@GeertBonte: als de geplande 2205 in werkelijkheid nog iets anders is dan de gerealiseerde 2211, dan kan je de reservering best verzetten naar 2212

**Comment by GeertBonte** [comment]
Geen idee waarom woonpremies staat bij 2205, maar woonpremies zijn 2211, dus 2205 is vrij.

**Comment by demaesschalckfilip** [comment]
Ik heb de verwerking van de EPC-data op PinC gezet: onder intern/thematische indeling/wonen/EPC (@joostschouppe ik heb met aggregation indicators gewerkt en niet meer met formules). Ik heb meteen ook een infofiche aangemaakt. Ik heb de checker voorlopig op 'IP' gezet, maar als er (andere) kandidaten zijn: meld je gerust. Ik stel voor de EPC-gegevens in de externe boom onder "wonen" te zetten, en dan "Energieprestatie". Daaronder komt dan het huidige "E-peil nieuwbouw" enerzijds en het "EPC" anderzijds. Ik zou die voor de duidelijkheid hernoemen naar respectievelijk "EPB (nieuwbouwwoningen)" en "EPC (bestaande woningen)".  Daar kan op termijn dan een derde kopje bij wat een combinatie is van beide (het extrapolatie-model).  Goed te keuren op de volgende redactiegroep?

**Comment by demaesschalckfilip** [comment]
Ik heb nog wat aanpassingen doorgevoerd (aandelen van de verschillende EPC-labels i.p.v. aantallen).  Ik heb daarnaast ook nog een hoofding in de themaboom toegevoegd: ‘extrapolatie naar alle appartementen en eengezinswoningen’. Hier staat de data die Geert heeft afgehaald. Deze zou ik wel pas extern zetten als er nog een aantal zaken zijn opgehelderd/aangevuld:

(1) het is niet duidelijk of het gaat om gegevens op het begin of het einde van het jaar (of ergens in de loop van het jaar); ik heb voorlopig 2022 niet opgeladen (voor de EPC’s zelf ook niet omdat dat nog niet volledig was: het ging er om het aantal EPC’s op het moment van consultatie)
(2) @GeertBonte : er zijn nu (niet-aggregeerbare) data op gemeente- en provincieniveau, maar kan je ook afhalen op gewestniveau? Zijn er nog andere niveau’s mogelijk?

Ik zou de source/infofiche van de EPC gebruiken (zoals ze nu in PinC staat), maar er een aantal zaken aan toevoegen. Hierbij het voorstel van de uitgebreide infofiche (toevoegingen in het geel).

Dit alles kan (al dan niet goed)gekeurd worden op de redactiegroep
[v2206_epc_v2.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/10208123/v2206_epc_v2.docx)

**Comment by Emilien-Dupont** [comment]
Stefan doet de controle.
Beslissing Redactiegroep 15/12: EPC extern zetten onder 'Wonen'.
Extrapolatie later toevoegen (na opheldering (1) en (2))

**Comment by joostschouppe** [comment]
Redactiegroep 19/1/2023
Nog toe te voegen: aandeel woningen met een EPC/EPB
Dilemma: lichtjes foute extrapolatie naar bovengemeentelijke gebiedsniveaus al of niet toestaan. Dit wordt eerst algemeen bekeken.

**Comment by StefanJacques** [comment]
Oké voor mij, Filip.
De nieuwe onderwerpen ook eens bekeken: zien er goed uit.

het enige dat ik niet goed weet is of we het totaal eerst plaatsen en dan de details (of dat het niet uitmaakt):
<img width="957" alt="image" src="https://user-images.githubusercontent.com/31841732/214070052-f6db2b73-f7fe-4caa-b9b5-eb9df625a9f9.png">

metadatafiche v2205_epc.pdf is ook in orde

plaats jij de onderwerpen ook EXTERN bij klimaat - of moet ik dat doen ?

dankjewel

**Comment by demaesschalckfilip** [comment]
Terechte vraag: ik heb dit percentage achteraan gezet omdat het een 'afgeleide' variabele is (gebaseerd op de absolute waarden die erboven staan); de percentages van labels heb ik bovenaan gezet, omdat ze de kern uitmaken van de extrapolatie. Maar andere volgorde is voor mij ook oké hoor.

**Comment by joostschouppe** [comment]
Lijkt me inmiddels afgerond

**Comment by demaesschalckfilip** [comment]
De extrapolaties zijn ondertussen niet meer beschikbaar, en herhaaldelijke vragen aan VEKA blijven onbeantwoord. Er is tegelijkertijd de vraag van klimaat of deze cijfers niet op een lager ruimtelijk niveau kunnen ter beschikking worden gesteld (dan de gemeente).  Het lijkt me dat er best een overleg kan worden opgestart met VEKA. Ik acht mezelf daar minder geschikt voor. Ik deed (samen met Geert) het louter afhalen en verwerken van data. Voor bronnen en inhoudelijke issues is dat minder het geval.

**Comment by demaesschalckfilip** [comment]
Ik krijg -toeval of niet- zonet antwoord van VEKA op mijn vraag van februari (!):

"Geachte,
 
Als antwoord op uw bericht van 27.02.2025 12:04 geven wij graag het volgende mee:
 
Onze excuses voor het late antwoord. 
 
De API's zijn gemigreerd e hebben nu deze url: [https://api.veka.azure.vlaanderen.be/sophie/datadiensten/v1/gebouweenheden/epc-labels](https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.veka.azure.vlaanderen.be%2Fsophie%2Fdatadiensten%2Fv1%2Fgebouweenheden%2Fepc-labels&data=05%7C02%7Cfilip.demaesschalck%40vlaamsbrabant.be%7Cad3e45ad696043a77d3908dda1d11e55%7Cabeeed50ea7b4008b0e5d27f624bf85e%7C0%7C0%7C638844641726087369%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=74BskUUmFeLVrM844MOH5CLohFRJkdSiLdsOECmZzsM%3D&reserved=0):

 
Voor een api key voor toegang kan u contact opnemen met VEKA, Aansluitingen [aansluitingen.veka@vlaanderen.be](mailto:aansluitingen.veka@vlaanderen.be)
 
 
Met vriendelijke groeten,
 
Vlaams Energie- en Klimaatagentschap
Postadres: Koning Albert II-laan 15 bus 460, 1210 Brussel"

**Comment by demaesschalckfilip** [comment]
Dus het probleem van de extrapolaties is alvast opgelost (als we een api key krijgen).

**Comment by GeertBonte** [comment]
API-key aangevraagd via [aansluitingen.veka@vlaanderen.be](mailto:aansluitingen.veka@vlaanderen.be) op 2025-06-06. Nog geen antwoord ontvangen. :(
