### ISSUE TITLE
MOBILITEIT - Data parkeerplaatsen voor personen met een handicap in PinC

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#298]
We ontvingen de vraag van Robin Julien van de organisatie 'On Wheels' om de data over parkeerplaatsen voor personen met een handicap mee te ontsluiten via PinC. Ze beschikken voor alle provincies over de data op atomair niveau. Indien de data aan de kwaliteitseisen voor PinC voldoet, denken we wel dat dit mogelijk moet zijn, dit zou passen onder het thema mobiliteit. We hebben hem gezegd dat we dit zouden bespreken op de redactiegroep. 
Informatie die voorlopig nog ontbreekt:
- Hoe dekkend zijn de data (i.e. kunnen er 'missing' in zitten en hoeveel zouden dit er dan (kunnen) zijn)?
- Hoe vaak worden de data geüpdated?
We hebben deze vragen aan Robin voorgelegd, van zodra we hierover van hem meer info ontvangen, wordt dit topic geüpdated.

**Comment by HanneODB-VLBR** [comment]
Geen antwoord meer ontvangen van Robin op onze vragen. Op 19/4 reminder gestuurd, met de vraag of hij nog steeds geïnteresseerd is om deze data op te nemen in PinC.

**Comment by HanneODB-VLBR** [comment]
Volgende antwoorden gekregen van Robin op onze vragen: 

Q: Zijn deze data gebiedsdekkend, in de zin van: kan het zijn dat er parkeerplaatsen ontbreken en indien ja, hebben jullie zicht op hoe groot het aantal ‘missings’ zou kunnen zijn?
A: We hebben 18 000 aangepaste parkeerplaatsen in onze app zitten, maar we hebben geen data beschikbaar hoeveel parkeerplaatsen er precies zijn in Vlaanderen. Hebben jullie daar cijfers over? Ik weet dat provincie West-Vlaanderen
samen met Inter al hun parkeerplaatsen heeft staan in een database en kunnen deze ook delen. Ze wordt ook elk jaar
geactualiseerd.

Q: Hoe vaak worden de data geactualiseerd?
A: De oudste data is van 2017. Gebruikers van onze app kunnen zelf ook aangeven of een parkeerplaats niet meer bestaat
of een nieuwe parkeerplaats toevoegen. We kunnen een lijst maken van alle parkeerplaatsen in de app met de datum
van opmeting. In Vlaams Brabant willen we ook kijken hoe we met de gemeentes kunnen samenwerken om de data
up to date te houden. We doen ook jaarlijks temabuildings en opmetingen met bedrijven en vrijwilligers om data toe
te voegen aan de app en bestaande data na te kijken. Wij zouden op termijn graag een dataset hebben van alle parkeerplaatsen per provincie die dan ook om te zoveel tijd geactualiseerd wordt. Het zou dus een goede stap zijn om eens de data van de Provincies, gemeentes en ons samen te brengen. 

Q: Je gaf in je eerste mailtje aan dat je samenwerkt met de dienst Mobiliteit van de provincie Vlaams-Brabant => mag ik vragen wie precies je contactpersoon is, zodat wij hier intern ook met elkaar kunnen afstemmen?
A: Onze contactpersoon is Karl Thiry van de Mobiliteitscentrale.

**Comment by joostschouppe** [comment]
Dit lijkt me voorlopig niet richting PinC te gaan. Maar heropen gerust als er nieuws is

**Comment by HanneODB-VLBR** [comment]
Er wordt dit jaar een actualisering van de cijfers opgenomen in het actieplan, dus de cijfers zullen niet voor meteen zijn, maar de mobiliteitscentrale is er wel nog mee bezig.
"Beste Hanne,

Sorry dat het antwoord even op zich liet wachten. Ik zal met Robin afspreken om dit jaar in hun actieplan een actualisering van de gegevens op te nemen. Het opmeten van parkeerplaatsen kan in samenspraak met de gemeentes up to date worden gezet. Als die data vollediger zijn, kunnen we nagaan hoe die in de cijfers van provincie worden geïntegreerd. Ik contacteer Robin hiervoor.

Met vriendelijke groeten, 

 

Karl Thiry
Coördinator Mobiliteitscentrale
"
