### ISSUE TITLE
Alternatieve jaartallen voor onderwijsdata

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#300]
In de nieuwe versie (voorlopig nog onder accept-provincies.incijfers.be) kan je nu bij _Data > Period Levels > Jaar_ alternatieve namen instellen:
![afbeelding](https://user-images.githubusercontent.com/10122639/161953936-ca18af91-e895-490e-a076-db8820e5df4a.png)

Bij Data > Indicators kan je dan instellen dat een bepaalde indicator de alternatieve naam moet gebruiken:

![afbeelding](https://user-images.githubusercontent.com/10122639/161954181-cf5a1f15-8565-407f-91ea-7f40fdf6f6ed.png)

Dus voor Stock heb je de gewone naam en één alternatieve naam. Je kan dus niet alternatieve weergaves blijven verzinnen (zoals bijvoorbeeld de vaste opnamedatum ofzo).

Dit vertaalt zich dan mooi door in Viewer en Dashboard:

![afbeelding](https://user-images.githubusercontent.com/10122639/161954421-bc015c81-bd81-4f81-895a-b682c0c245d3.png)

[online voorbeeld](https://accept-provincies.incijfers.be/admin/jive/?var=v2301_lln_basis&period=2019,2020)

Enige potentieel nadeel is dat je dan in de presentatie zelf iets anders ziet dan in de periode selectie:
![afbeelding](https://user-images.githubusercontent.com/10122639/161954512-ce0df31a-7f2f-434f-b525-8bf5bab0aad3.png)
[Dat probleem kan je wél oplossen in Dashboard](https://github.com/provinciesincijfers/connectorbeheer/issues/84#issuecomment-1074058116) (als je daar periodeselecties zou toestaan).

Als je onderwerpen mét en zonder deze alternatieve naam combineert, krijg je de variant met de "gewone" naam in de weergave.

**Voorstel**: we gebruiken deze functionaliteit om de onduidelijkheid mbt jaartal van onderwijsdata weg te werken (zoals in het voorbeeld). Zie verdere context in [deze vraag van Stad Gent](https://github.com/provinciesincijfers/connectorbeheer/issues/84).
We hadden reeds gedacht om bijvoorbeeld "1/1/2020" te gebruiken voor dit soort functionaliteit, maar het probleem is dat er verschillende snapshot-momenten zijn, en dat dit dus geen volledige oplossing kan bieden. Onderwijs is meer een uitzondering dan dit soort cijfers, aangezien het niet over een bepaald kalenderjaar gaat, maar om een schooljaar.

**Comment by Lievendr** [comment]
prima

**Comment by veravandestraat** [comment]
Akkoord

**Comment by VickyVB** [comment]
akkoord

**Comment by joostschouppe** [comment]
Redactiegroep: iedereen akkoord.
Uitrol pending dat het technisch werkt

**Comment by joostschouppe** [comment]
Inmiddels uitgevoerd. Blijkbaar moest de functie nog door ABF aangezet worden (zie ticket 112253).
@VickyVB : ik heb in de Indicator tabel gewoon alles van mvg_onderwijs op `Use alternative period names=1` gezet. Als je onderwerpen toevoegt, ga je dat vinkje nog zelf moeten aanzetten. Als er uitzonderingen zijn waar je bij onderwijs NIET spreekt over een schooljaar, dan moet dat vinkje terug uit!
