### ISSUE TITLE
OOV opcentiemen op oproerende voorheffing

### ISSUE THREAD

**Issue by Lievendr** [provinciesincijfers/PinC-taakopvolging#302]
Dag Lieven,

Zoals besproken wou ik wat input geven omtrent de OOV (opcentiemen op onroerende voorheffing) die als cijfer in PinC zitten.
Voor elke gemeente kan ik dit cijfer opvragen en de historiek bekijken. Echter stel ik me de vraag of dit niet meer genuanceerd moet worden weergegeven. Zie voorbeeld gemeente Gistel in bijlage.
Mijn vraag is tweeledig:

A)	Correctie 2018

In 2018 werd de basisheffing van het Vlaamse gewest verhoogd van 2,5% naar 3,97% door de vernieuwde taakstelling en de gewijzigde financiering van de provincies (decreet van 18 november 2016). De gemeenten moesten een correctie doorvoeren aan hun opcentiemen zodat de opbrengst voor de gemeenten niet verhoogd tegenover het voorgaande aanslagjaar, tenzij ze hier bewust voor kiezen en dit duidelijk communiceren.

Suggestie: Dit zorgt voor een sprong in de meeste curves wanneer je de historiek van een gemeente opvraagt. Moeten we dit als opmerking (met sterretje ofzo?) meegeven wanneer je zo een grafiek maakt?

B)	Differentiatie in opcentiemen sinds 2019

Sinds het aanslagjaar 2019 kunnen gemeenten de opcentiemen binnen hun grondgebied laten variëren volgens bepaalde criteria. Op dit ogenblik zijn er drie gemeenten die al gebruik maken van deze regeling: Gistel, Sint-Pieters-Leeuw en Zwijndrecht (Vlaamse overheid, 2021).
Gistel legde een differentiatie in opcentiemen vast voor twee jaren (aanslagjaar 2020 en 2021) met een onderscheid tussen onbebouwde percelen, bebouwde percelen met een bescheiden KI (lager of gelijk aan 745) en bebouwde percelen met een hoger KI. De opcentiemen voor de gemeente zijn 1.070, voor de tweede categorie met bescheiden KI wordt deze verlaagd naar 745 opcentiemen. Dit is een sociale maatregel ter ondersteuning van een doelgroep die het minder breed heeft. De stad Gistel wil hiermee een jaarlijks terugkerende stimulans geven aan inwoners die eigenaar zijn van een sociale woning.
•	onbebouwde percelen (ongeacht het KI): 1070 opcentiemen.
•	bebouwde percelen met een niet geïndexeerd KI lager dan of gelijk aan 745: 1.000 opcentiemen.
•	bebouwde percelen met een niet geïndexeerd KI hoger dan 745: 1.070 opcentiemen.
Sint-Pieters-Leeuw kiest voor een differentiatie van opcentiemen om een gunstig investeringsklimaat voor bedrijven te organiseren en legt deze voor de aanslagjaren 2020 tot en met 2025 vast. De ‘bedrijfsbelasting’ op basis van oppervlakte heeft men afgeschaft en budget-neutraal ingekanteld in de onroerende voorheffing omdat deze te aanvoelde als ‘onbillijk’ en ‘aangiftegevoelig’ maar ook veel administratie met zich meebracht voor bedrijven en de gemeente. De opcentiemen voor industriële kadastrale inkomens werden verhoogt tot 740. Deze verhoging is echter lager dan de vroegere bedrijfsbelasting waardoor dit in het voordeel van de ondernemers valt. De niet-industriële ondernemers zoals detailhandel, landbouwers en gewone zelfstandigen in hoofd- of bijberoep profiteren nog het meeste van deze regeling want voor hen valt de bedrijfsbelasting weg en genieten ze van het zelfde tarief in opcentiemen als de gewone burger.
•	gewone gebouwde en ongebouwde kadastrale inkomens (codes 1F en 2F): 566,75 opcentiemen.
•	gebouwde en ongebouwde belastbare kadastrale inkomens "nijverheid" en "materieel en outillage" (codes 3F, 4F, 5F en 6F): 740 opcentiemen.
Zwijndrecht legt een differentiatie in de opcentiemen vast voor de aanslagjaren 2021 tot en met 2025 met als doel het meerjarenplan financieel in evenwicht te krijgen. De gemeente Zwijndrecht heeft geen bedrijfsbelasting gevestigd om dezelfde redenen waarom Sint-Pieters-Leeuw deze afschafte: onbillijk, aangiftegevoelig en administratieve last. De gemeenten heeft een zware kostenverhoging voor brandweerbijdrage aan brandweerzone Antwerpen omdat ze veel nijverheidsbedrijven op haar grondgebied heeft liggen en niet langer een compensatie krijgt voor de gederfde opcentiemen inzake materieel en outillage. Daarom werd besloten om de opcentiemen te verhogen voor de categorieën ‘nijverheid’ en ‘materiaal en outillage’.
•	gewone gebouwde en ongebouwde kadastrale inkomens (codes 1 (F, K, L, P) en 2 (F, K, L, P)): 913 opcentiemen.
•	gebouwde en ongebouwde belastbare kadastrale inkomens “nijverheid” en “materieel en outillage” (codes 3 (F, K, L, P), 4 (F, K, L, P), 5 (F, K, L, P) en 6 (F, K, L, P)): 950 opcentiemen.
Suggestie: Enkele gemeenten hebben dus de voorbije jaren niet langer 1 getal voor de OOV, maar wel 2 getallen die aan specifieke voorwaarden zijn gebonden. Moet dit als opmerking weergegeven worden voor de gemeenten? Of kunnen zelfs beide niveaus van opcentiemen weergegeven worden?
Nu zijn het nog maar 3 gemeenten van de 300 die hiermee aan de slag zijn, maar dat kunnen er meer worden. Zeker indien ons project GODO succesvol blijk.

Steeds bereid om hier samen over na te denken.
Dank om dit te bekijken!

Met vriendelijke groeten,
Senne Van Hoof
[fiscaliteit_OOV_2008_2022_evolutie_versie_09feb22.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/8521496/fiscaliteit_OOV_2008_2022_evolutie_versie_09feb22.xlsx)

**Comment by HanneODB-VLBR** [comment]
Gemaakte aanpassingen in het licht van deze vraag:
-De info over de tijdsbreuk in 2018 stond reeds in de metadatafiche. Voetnoot toegevoegd met verkorte versie van deze info, en verwijzing naar metadatafiche.
-Info over gedifferentieerde tarieven toegevoegd in metadatafiche, met verkorte uitleg over waar de drie gemeenten op inzetten.
