### ISSUE TITLE
z-scores beter toelichten in Rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#303]
## Concept:
- het gaat over de standaardkaarten gebaseerd op z-scores
- licht dit type kaart toe bij het eerste gebruik in het rapport
- zet bij eerste gebruik een korte populariserende versie
- gebruik een voetnoot voor een wat uitgebreidere toelichting. Niet al te technisch, wie een volledige technische uitleg wil, kan met de technische termen zelf aan de slag

## Let wel:
- gebruiken we altijd vergelijking met een vergelijkingsgebied? Of soms ook met "alle gebieden van het niveau"? In het sjabloon is het `Transformation: ZScoreParent;` met `compare: input_compare_first;`. Gebruik van "input_compare" komt ook voor, maar dit is fout, omdat dan met het LAATSTE vergelijkingsgebied wordt vergeleken, terwijl in de tekst wellicht over het EERSTE vergelijkingsgebied wordt gesproken.
- als vergeleken met "vergelijkinsgebied", benoemen we dan dit vgl-gebied?
- komt de tekst nog wel overeen met de kaart? Nakijken in alle rapporten, met name in wonen werd iets gesignaleerd
- de samenvattende grafiek heeft reeds een standaardtekst. Indien er geen z-kaarten zijn, dan moet die tekst wellicht naar de voetnoot verwijzen:

## Draft tekst:

De inkleuring van "veel lager" tot "veel hoger" is gebaseerd op z-scores, die een maat geven van hoeveel `een gebied` afwijkt van het gemiddelde in het `vergelijkingsgebied` (zie voetnoot). 

**Voetnoot**:
Een z-score geeft weer hoeveel standaardafwijkingen de waarde van een `gebied` afwijkt van de waarde in `het vergelijkingsgebied`. Een standaardafwijking is een maat voor hoeveel een willekeurig gebied doorgaans afwijkt van "de standaard" (het gemiddelde). Er is dus een minder grote absolute afwijking van het gemiddelde nodig wanneer alle `gebieden` gelijkaardige cijfers hebben, dan wanneer de cijfers van de `gebieden` ver uit elkaar liggen.

De inkleuring volgt steeds deze schaalverdeling:
* z-score kleiner dan -1,50: veel lager dan `het vergelijkingsgebied` (donkerblauw)
* z-score van -1,50 tot -0,50: lager dan `het vergelijkingsgebied` (blauw)
* z-score van -0,50 tot 0,50: gemiddeld (grijs) 
* z-score van 0,50 tot 1,50: hoger dan `het vergelijkingsgebied` (oranje)
* z-score hoger dan 1,50: veel hoger dan `het vergelijkingsgebied` (donkeroranje)

**Comment by VickyVB** [comment]
aanvulling nav opmerkingen rapport AM/detailhandel:
- Aanvullen onder de betreffende figuren: _"Klik op het tabelicoontje om z-score en waarde van de getoonde gebieden te zien."_
- Kunnen we voor de z-score kaarten showdata niet op true zetten? Dan krijg je (bij een beperkt vergelijkingsgebied) wel de echte waarden op kaart te zien.
- Ivm de standaardtekst voor de profielstaven. Die ziet er zo uit _Deze laatste figuur toont aan de hand van profielstaven in welke mate het percentage van enkele kenmerken in Aarschot (gekleurde bol) afwijkt van het percentage van het vergelijkingsgebied (provincie, grijze staaf). Scoort het gebied gemiddeld in vergelijking met het vergelijkingsgebied dan kleurt de bol grijs. Een blauwe bol wijst op een lager percentage en een oranje gekleurde bol op een hoger percentage dan het gemiddelde._ Het gaat echter vaak niet om percentages, maar ook promille, ratio, ... Het woord percentage hier vervangen door waarde?

**Comment by joostschouppe** [comment]
In verband met wens om "z-scores - grenzen weergeven in de legende" bij dit soort kaartjes toe te passen (swing issue 87181):

> Joost, de wens is besproken en besloten om dit niet in te bouwen. De voornaamste reden is dat er alternatieve oplossingen zijn. Zoals het tonen van een extra kaart met de achterliggende waarden naast de kaart met z-scores. Of om enkel voor de z-scores een interactieve kaart te gebruiken en de rest niet. Daarnaast is het mogelijk om middels de icoontjes onder de grafiek de achterliggende waarden te downloaden als Excel of als tabel te tonen.

**Comment by Emilien-Dupont** [comment]
**Standaardtekst** (zie hierboven)
De inkleuring van "veel lager" tot "veel hoger" is gebaseerd op z-scores, die een maat geven van hoeveel `een gebied` afwijkt van het gemiddelde in het `vergelijkingsgebied` (zie voetnoot). 
Toevoeging: De echte waarden van de getoonde gebieden zie je op de kaart weergegeven / wanneer je de cursor over de kaart beweegt. (afhankelijk of je showdate op true zet of niet en of je kaart interactief is). (anders kan het wat verwarrend zijn)
Eventuele toevoeging onder figuur: Klik op het tabelicoontje om z-score en waarde van de getoonde gebieden te zien.

**Voetnoot**
Een z-score geeft weer hoeveel standaardafwijkingen de waarde van een `gebied` afwijkt van de waarde in `het vergelijkingsgebied`. Een standaardafwijking is een maat voor hoeveel een willekeurig gebied doorgaans afwijkt van "de standaard" (het gemiddelde). Er is dus een minder grote absolute afwijking van het gemiddelde nodig wanneer alle `gebieden` gelijkaardige cijfers hebben, dan wanneer de cijfers van de `gebieden` ver uit elkaar liggen.

De inkleuring volgt steeds deze schaalverdeling:
* z-score kleiner dan -1,50: veel lager dan `het vergelijkingsgebied` (donkerblauw)
* z-score van -1,50 tot -0,50: lager dan `het vergelijkingsgebied` (blauw)
* z-score van -0,50 tot 0,50: gemiddeld (grijs) 
* z-score van 0,50 tot 1,50: hoger dan `het vergelijkingsgebied` (oranje)
* z-score hoger dan 1,50: veel hoger dan `het vergelijkingsgebied` (donkeroranje)

**Daaropvolgende z-kaarten**
- (z-scores) in titel
- Expliciete vermelding van hoe `een gebied` afwijkt van de waarde (:grey_exclamation: NIET van gebieden in het vergelijkingsgebied) in het `vergelijkingsgebied` is in prinicpe enkel nodig wanneer je met een ander gebied vergelijkt (bv gewest ipv provincie) of je gebiedsniveau verandert (bv wijk ipv gemeente). 

**Standaardtekst samenvattende figuur**
Deze laatste figuur toont aan de hand van profielstaven in welke mate de waarde van enkele kenmerken in `een gebied` (gekleurde bol) afwijkt van de waarde van het vergelijkingsgebied (`het vergelijkingsgebied`, grijze staaf). 
Scoort het gebied gemiddeld in vergelijking met het vergelijkingsgebied dan kleurt de bol grijs. Een blauwe bol wijst op een lagere waarde en een oranje gekleurde bol op een hogere waarde dan het gemiddelde.

&rarr; Opgelet: deze tekst in de rapporten wijkt in meer of mindere mate af van de standaardtekst.
TODO: in sjabloon_grafiekstijl toevoegen 

**Bijkomend**
Afspraak: We berekenen z-scores op basis van de gebieden die je op de kaart ziet (Transformation: ZScoreParent; doorgaans provincie, op basis van een opgesplitste input_compare_first) NIET op basis van alle gebieden van heel Vlaanderen+Brussel 
&rarr; Dit is nog niet in orde voor de rapporten armoede en landbouw

Afspraak: We gebruik de oranje-blauw kleurenschaal enkel voor z-kaarten.
&rarr; in Rapport onderwijs zijn er een aantal niet-z-kaarten met de oranje-blauwe kleurenschaal

**Comment by joostschouppe** [comment]
Voorstel wordt op deze manier uitgerold (nav Redactiegroep)
