### ISSUE TITLE
data LAC (behandelde dossiers) 

### ISSUE THREAD

**Issue by mehtap19** [provinciesincijfers/PinC-taakopvolging#307]
@joostschouppe In de databank VREG (rapport) staan cijfers voor 2020. Via de connector zien we enkel cijfers voor 2017. Hebben jullie zicht op wanneer er een update doorgevoerd wordt naar de connector? Merci!

**Comment by joostschouppe** [comment]
Bijkomend: ook actieve budgetmeters worden gepubliceerd door Fluvius. Technisch gezien kan dit ook op niveau statsec, maar wordt rap te kleine aantallen. Daarom heb ik suggestie gedaan om die op wijk- of deelgemeente te publiceren. Dat werd niet onmiddellijk afgeschoten, maar zal wel wat opvolging (en gedragenheid) vereisen.

**Comment by GeertBonte** [comment]
Een update met de stand van zaken: binnenkort worden de cijfers geactualiseerd.

Ik had een tijd geleden al alle op dat moment beschikbare data afgehaald via de QlikView-site (voor alle 300 gemeenten één per één alle data voor 2011-2020 geëxporteerd naar aparte Excel-bestanden) en daarna met Python de data die we nodig hebben eruit gehaald en samengezet in één Excel-bestand. Die data heb ik vervolgens vergeleken met wat momenteel in PinC zit (2012-2017). Daarbij vond ik maar een klein aantal minieme verschillen, niets verontrustends.

Voor de toekomst zal het niet meer nodig zijn om telkens handmatig 300 bestanden te exporteren uit QlikView. Van onze contactpersoon bij Statistiek Vlaanderen kunnen we voortaan een Excel-bestand krijgen met de benodigde cijfers. Inmiddels zijn ook de data voor 2021 beschikbaar via QlikView, maar we hebben dezelfde gegevens ondertussen ook van onze contactpersoon gekregen in een Excel-bestand, dus ik hoefde gelukkig niet opnieuw 300 bestanden te exporteren.

De voorbereidingen voor de upload en de aanpassingen aan de metadatafiche zijn zo goed als klaar. Er veranderen wel enkele zaken:

1. Er wordt een nieuwe indicator toegevoegd: v3123_lac_zittingen met het aantal LAC-zittingen voor elektriciteit.

2. De data voor alle jaren zullen opnieuw geüpload worden en komen nu in PinC onder hetzelfde jaartal als de bron. Voorheen werden de data gepubliceerd bij jaar X+1, maar dat was ten onrechte. Het aantal LAC-dossiers is immers niet de toestand op 31 december (wat dan in PinC bij het volgende jaar zou komen), maar het aantal dossiers in de loop van het jaar (dus in PinC gewoon bij hetzelfde jaar als de bron). Voor het aantal actieve budgetmeters geeft de bron nu twee cijfers: een met de toestand op 1 januari en een met de toestand op 31 december. Voorheen werd het cijfer van 31 december gebruikt, maar voortaan zullen we het cijfer met het aantal op 1 januari overnemen (dus ook in PinC hetzelfde jaar als de bron).

**Comment by GeertBonte** [comment]
De geactualiseerde cijfers zijn vanaf vandaag beschikbaar in PinC.
