### ISSUE TITLE
Cijfers personen met een handicap

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#309]
Vraag van @Tine-VB 
Ik was even wat cijfers aan het opzoeken over personen met een handicap. Het zou handig zijn als er, naast de afzonderlijke categorieën, ook een totaal voor de drie types uitkeringen zou toegevoegd worden: enkel IT, enkel IVT en IT + IVT. Vroeger konden we daar nog zelf een indicator van maken in de databank, maar nu dat niet meer gaat…
 
Ik weet niet of jij daarover kunt beslissen, daarom zet ik Joost en Emilien even in cc: kunnen bij Gezondheid en handicap / personen met een handicap een paar indicatoren herhaald worden? Die staan nu wat verspreid in de databank. Bijvoorbeeld:
•	IT/IVT
•	Socio-economische positie: personen met tegemoetkoming aan personen met een handicap (evt ook volledig arbeidsongeschikten?). (Vicky?)

Toevoeging @VickyVB 
Ivm de KSZ data: dat ZOU interessant zijn wanneer we de gegevens van de globale populatie hebben  (mogelijk binnenkort, wie zal het zeggen).

De nomenclatuur (zoals die nu opgenomen is in PinC) hoort hier niet thuis gezien het dus gaat om een momentopname die de socio-economische positie die het dichtst bij de arbeidsmarkt weergeeft. Net zoals de cijfers van werkloosheid hier sterk verschillen van de cijfers van de VDAB, gaan deze cijfers de populatie ook niet volledig omschrijven en dat suggereer je natuurlijk wel door ze onder handicap te zetten.

**Comment by veravandestraat** [comment]
@Tine-VB 

<img width="344" alt="image" src="https://user-images.githubusercontent.com/61196697/171154888-f20d9897-7d0d-4ad5-9eb0-38188bbf393f.png">

**Comment by Emilien-Dupont** [comment]
Besproken binnen de werkgroep Themaboom en goedgekeurd door de Redactiegroep:
Cijfers personen met een handicap: IT en IVT komen ook onder Gezondheid en Handicap > Personen met een handicap. Omgekeerd doen we dit niet: personen erkend door DG komen niet onder tegemoetkomingen.

**Comment by Tine-VB** [comment]
Ik zou dan wel twee mapjes maken:

1. Erkenningen door DG Personen met een handicap
2. Tegemoetkomingen

Want nu staan 'Naar leeftijdsklasse' en 'Tegemoetkomingen' op eenzelfde niveau.
