### ISSUE TITLE
rapporten in PDF: lege ruimte

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#310]
Bij export van rapporten naar PDF, is er vaak enorm veel verloren ruimte onder figuren. Met behulp van de helpdesk (melding 107827) is dat weggewerkt in de beta. Vergelijk de live versie bv met een export via https://beta-provincies.incijfers.be/admin/jive/report/?id=rapport_landbouw

![image](https://user-images.githubusercontent.com/10122639/170220378-6634f2d0-71e1-471b-bada-98ec5965c867.png)

Bij deze aanpassing heb ik de css wat verbeterd: die gaat lettergrootte nu meer in relatieve termen dan in absolute instellen, wat voor de toegankelijkheid beter zou zijn. Een klein zij-effect van de aanpassing is dat de tekst wat groter is dan voorheen in de PDF.

**Concrete vragen:**
- OK dat de tekst wat groter wordt?
- Ziet het er goed uit in jullie rapporten? Check via https://beta-provincies.incijfers.be/admin/jive/report/?id=[rapportcode] . Het kan zijn dat er wat "harde pagebreaks" in je rapport zijn ingebouwd die nu misschien ongewenste effecten hebben.

Wil je zien wat er exact verandert in de CSS? Plak dan [de nieuwe](https://beta-provincies.incijfers.be/admin/report/style/ipo_dynamic.css) en [de huidige](https://provincies.incijfers.be/report/style/ipo_dynamic.css) even in een tool als [text-compare](https://text-compare.com/nl/)

**Comment by StefanJacques** [comment]
Bij cijfers (bevolking) opgelijst lijkt het lettertype net KLEINER geworden in de BETA:

BETAVERSIE deze keer LINKS:
![image](https://user-images.githubusercontent.com/31841732/171010030-ac0e8d56-315e-4156-9790-813def2ca09d.png)

**Comment by StefanJacques** [comment]
en een derde soort rapport (kerncijfers) is opvallend mooier RECHTS (BETA) dan in de huidige versie:
![image](https://user-images.githubusercontent.com/31841732/171011245-6b00bc2a-b010-4b91-8c2a-0a138639d856.png)

! er is nog 1 witte bladzijde achteraan te veel

**Comment by Tine-VB** [comment]
Op het scherm ziet het lettertype er een stuk groter uit, maar als je effectief exporteert naar pdf zie maar een klein verschil. Zeker goed.
Er zijn inderdaad wat minder gaten, maar in het rapport landbouw verschuift er niet zoveel, omdat het meestal gewoon op hetzelfde blad blijft (zoals ook het voorbeeld van Stefan hierboven eigenlijk. 
![image](https://user-images.githubusercontent.com/61458346/171175706-ea84382e-f4d8-4704-8c9b-9ac9ceb37dad.png)
Hier bijvoorbeeld wel:
![image](https://user-images.githubusercontent.com/61458346/171175928-16618b3e-07a6-4c90-9e97-0d6c5b740128.png)
Maar omgekeerd komen deze kaarten in de beta versie allemaal op een apart blad te staan:
![image](https://user-images.githubusercontent.com/61458346/171176162-f697f780-faec-4738-a483-19d143cbb0d9.png)
De tabellen zien er veel overzichtelijker uit alleszins. Dus ik ben voor.
![image](https://user-images.githubusercontent.com/61458346/171176646-7c75486c-cde4-4923-9c24-6e0a0e56271e.png)

**Comment by joostschouppe** [comment]
@StefanJacques : gek dat dit nu pas boven water komt, maar da's een typisch gevolg van een klein foutje VOORALEER dat stuk begint. In de paragraaf erboven stond ergens: `<b>#write(data(verzameltabel_deel2,7,2))#<b>` ipv `<b>#write(data(verzameltabel_deel2,7,2))#</b>`

**Comment by joostschouppe** [comment]
Er even van uitgaande dat dit in orde is, sluit ik af. Als er toch nog issues opduiken, laat maar weten (en heropen dit Issue als het Een Groot Probleem betreft)
