### ISSUE TITLE
Aanpassing sjabloon: slimmere introkaart

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#311]
De werkgroep Detailhandel stoorde zich aan dit kaartje in de intro van rapporten:

![afbeelding](https://user-images.githubusercontent.com/10122639/169262288-772c5890-fd7d-4b1e-8964-f33c00f453c7.png)

Het lijkt wel alsof er een stuk "afgeknipt" is van de kaart.
De reden hiervoor is simpel: Swing gaat bij kaarten steeds uitzoomen op een manier dat alle gekozen gebieden nét op de kaart passen. Er is geen manier om in te stellen dat je je kaart meer uitgezoomed wilt zien. Maar dat was buiten het creatieve genie van Edward gerekend. Hij verzon deze workaround:
- geef twee van onze "gebieden onbekend" elk een middelpunt, elk op een uithoek van Vlaanderen
- indien je een niet lokale gebiedsindeling (uitrustingsgraad, fo_gem) selecteert als vergelijkingsgebied, voeg deze gebieden toe aan de kaart-selectie
- bouw je introkaart aan de hand van de gewoonlijke "vergelijkingsgebied uitgesplitst naar gemeente" + deze twee gebieden
- succes!

![afbeelding](https://user-images.githubusercontent.com/10122639/169262453-7d722618-2c07-496f-ac00-5c6cbd0948a4.png)

Ik heb ook het grijs wat zwaarder gemaakt, om deze kaart wat leesbaarder te maken.

Dit heeft nog een interessant neven-effect: door deze workaround kun je nu ook in de viewer een kaartje met gemeenten forceren dat [uitgezoomed is voor heel Vlaanderen](https://accept-provincies.incijfers.be/databank?workspace_guid=af0b0295-b5dd-472d-8bd4-a6f66663aea3). 

Vooraleer we dit uitrollen: zijn er mogelijk nog negatieve zijdelingse effecten?

## Uitrol
- kopieer coördinaten van gebieden onbekend van [accept](https://accept-provincies.incijfers.be/admin/studio/Table/DetailGrid?TableName=GeoItem&ParentKey=GeoLevelCode&ParentCode=66&ParentTable=GeoLevel) naar [echte versie](https://provincies.incijfers.be/admin/studio/Table/DetailGrid?TableName=GeoItem&ParentKey=GeoLevelCode&ParentCode=66&ParentTable=GeoLevel)
- kopieer code van [accept sjabloon](https://accept-provincies.incijfers.be/admin/jive/Report/Edit/sjabloon_rapport_vertrekproject) naar gewone sjablonen en rol uit naar alle rapporten

**Comment by Lievendr** [comment]
Topjob Joost!

**Comment by StefanJacques** [comment]
rol maar uit !

**Comment by davidcardinaels** [comment]
Dit is aangepast in alle echte rapporten.
