### ISSUE TITLE
Rapport mobiliteit

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#312]
Graag zou ik van start willen gaan met een eerste basisrapport mobiliteit, op basis van de gegevens die we al hebben. Dit rapport kan later herwerkt/uitgebreid worden naarmate er meer data in dit thema worden verzameld.

Een eerste outline voor dit rapport is hier te vinden: https://vlbr.sharepoint.com/:w:/r/teams/DA-Interprovincialeprojecten/Gedeelde%20documenten/Mobiliteit/Outline%20rapport%20mobiliteit.docx?d=w7855234c426145438a7c39a89f52bc8c&csf=1&web=1&e=EueVqu

Dit voorstel zal ook worden geagendeerd op de eerstvolgende werkgroep mobiliteit, op 3 juni.

**Comment by HanneODB-VLBR** [comment]
Hanne en Lieven werken samen aan dit rapport:
Hanne: schreef deze zomer de hoofdstukken 'verplaatsingsgedrag' en 'verkeersveiligheid'
Lieven: schreef deze zomer het hoofdstuk 'verplaatsingspotentieel'
Op 15 september komen Hanne & Lieven samen om alles te overlopen, en worden de hoofdstukken samengevoegd tot één rapport. Daarna wordt het rapport voorgelegd aan de werkgroep mobiliteit.

**Comment by Lievendr** [comment]
In overleg stoten Hanne en ik op een aantal praktische keuzes. Vooraleer voor te leggen aan werkgroep: hoe publiceren we enquêtegegevens in een rapport?
Standaard staat daar ook een voetnoot bij die telkens getoond wordt. Voorstel is om die uit te zetten en slechts eenmaal in eindnoot te vermelden. Anders wordt die teveel herhaalt.
In bijkomende link 3 opties:
1. met betrouwbaarheidsinterval. Nadeel is dat je als gebruiker niet precies het exacte % ziet; en vraag is ook hoe interpreteert een gebruiker dit?
2. met % erbij; maar dan krijg je ook betrouwbaarheidsinterval erbij: slordig?
3. betrouwbaarheidsinterval uit, eindnoot geeft aan dat men rekening moet houden met betrouwbaarheid.
https://provincies.incijfers.be/databank?workspace_guid=b78f26b4-f45d-4f2b-9467-004b6d9fe00b

**Comment by HildeC** [comment]
heb het eens samen met Lore bekeken. akkoord om voor de derde optie te gaan, maar de uitleg over de betrouwbaarheidsintervallen zou in de inleiding of de leeswijzer moeten staan, en we zouden 1 keer in de tekst de werking van betrouwbaarheidsintervallen uitleggen aan de hand van een voorbeeld.

**Comment by Tine-VB** [comment]
Indien toch gekozen wordt voor optie 3, zouden we er iets bijzetten als 'Klik op het tabelicoontje onderaan de grafiek om het betrouwbaarheidsinterval te zien'. Hier een voorbeeldje hoe dat zou kunnen uit het rapport arbeidsmarkt van Vicky: 
![image](https://user-images.githubusercontent.com/61458346/191022843-f587d02d-6fd5-46ba-b873-6cb58bd6ac3f.png)

**Comment by joostschouppe** [comment]
Redactiegroep is fan van optie 1

**Comment by joostschouppe** [comment]
Afspraak redactiegroep 20/9/2022: 
Probleem betrouwbaarheidsintervallen: we tonen de grafiek zonder de labels met de exacte cijfers van de betrouwbaarheidsintervallen (optie 1 in discussie per mail). Je kan dan hooveren over de figuur om de cijfers te zien.

We beschouwen dit als een algemene afspraak en zetten een voorbeeld in sjabloon_grafiekstijl

**Comment by Lievendr** [comment]
Tegel bronnen: moet daar ook iets komen van ABB (GSM: Gemeente en Stadmonitor)? Anderzijds gaan gebruikers misschien denken dat er alles van GSM op staat? Wat doen we hiermee...

**Comment by Lievendr** [comment]
Stavaza 03/02: 
Dashboard is aangemaakt en is voorgelegd ter controle aan Koen.  
Mobiliteitsindicatoren zijn opgenomen in kernrapport, wordt al gepubliceerd
Eerste draft rapport nagelezen door Stefan en Vera. Waarvoor dank. Aanpassingen zijn en worden eerstdaags doorgevoerd. 
Nadenken over nut/strategie persbericht provinciaal - interprovinciaal

**Comment by Lievendr** [comment]
Koen heeft dashboardvoorstel bekeken en waar nodig aangepast. Waarvoor oprechte dank.
ter goedkeuring
https://provincies.incijfers.be/dashadmin/preview/dashboard/mobiliteit

**Comment by veravandestraat** [comment]
Mooi dashboard!
De kleinere lettergrootte bij de lange grafiektitels stoort mij een klein beetje, maar daar valt waarschijnlijk niet veel aan te doen.

**Comment by HanneODB-VLBR** [comment]
Knap dashboard, goed gedaan Lieven & Koen! Ik zou enkel nog 'verkeersmodi' veranderen naar 'vervoersmodi', zodat het in lijn is met de naam van het subthema in de databank.

**Comment by joostschouppe** [comment]
Redactiegroep 16/2/2023:
- Lieven contacteert werkgroep ivm publicatiedatum (op tijd voor nieuwsbrief februari of ten laatste maart)
- ontbreken van foutenmarge in Dashboard wordt niet als problematisch ervaren. Joost onderzoekt mogelijkheid om die via een omweg toch te tonen, maar dit is niet essentieel.
- nog enkele kleine issues in rapport met export naar PDF, worden nog opgelost
