### ISSUE TITLE
Bronnenrijkdom

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#316]
Het feit dat bronnen (bv. Statbel, mvg_onderwijs, steunpunt_werk, ...) zijn die heel breed gaan, gaat bij het nieuwe infosysteem mogelijk voor onduidelijkheden zorgen. Moeten deze bronnen gesplitst worden? Zijn er regeltjes? Timing?
bv. 'Statbel' is verbonden met 
- v1101_bevolking_statbel (LI en WV), 
- v1102_loopbevolking_statbel (LI), 
- v1103_migraties_nationaliteit (LI), 
- v1401_omzet_investeringen(AN ECO), 
- v1402_btwplichtige_ondernemingen(AN ECO), 
- v1402_faillissementen(AN ECO), 
- v1501_bodembezetting (WV ECO), 
- v2101_personenwagens (WV ECO), 
- v2101_personenwagens_brandstof (LI KLI), 
- v2101_wagenbezit (VB), 
- v2107_bereikbaarheid (VB), 
- v2203_verkoop_onroerend_goed (WV), 
- v2390_onderwijsniveau (VB), 
- v2603_verblijfstoeristische vraag (LI TOE), 
- v2802_verkeersongevallen_gewonden (LI),
- 9900_gebiedsniveaus (IP).
(Daarnaast zijn er nog de bronnen statbel_abc, statbel_bouwvergunning, statbel_dep_Inv, statbel_fisc_ink, statbel_geo, statbel_meitelling, statbel_combi)

**Comment by joostschouppe** [comment]
Verdere opvolging via https://github.com/provinciesincijfers/PinC-taakopvolging/issues/318

**Comment by joostschouppe** [comment]
Huidige "regel": “Naam van de bron - naam van de verwerking | provincies.incijfers.be”

**Comment by Tine-VB** [comment]
Meest efficiënt lijkt mij dat jij (of Emilien) met iedereen even de bronnen overloopt waarvoor hij/zij verantwoordelijk is. Zo kan iedereen de inhoudelijke kennis over de bron inbrengen, maar blijft toch ook de uniformiteit gegarandeerd.

**Comment by joostschouppe** [comment]
Deze DataSources zullen gewist worden op 18/10, er zijn immers geen onderwerpen aan gekoppeld:

Data source code | Name | Info Url | Description
-- | -- | -- | --
sv_vos | Statistiek Vlaanderen - Vlaamse Openbare Statistieken \|   provincies.incijfers.be |   |  
provincies_sa_pv | Provincie Oost-Vlaanderen, Antwerpen, Vlaams-Brabant en EOS \|   provincies.incijfers.be | v2503_SA_zonnepanelen.pdf | Afhankelijk van waar de gemeente gelegen is: Provincie Oost-Vlaanderen,   Provincie Antwerpen, Provincie Vlaams-Brabant, EOS (waarbij EOS alle   gemeenten van de provincie West-Vlaanderen bedient).
provincies_sa_gs | Provincies Oost-Vlaanderen, West-Vlaanderen en Antwerpen \|   provincies.incijfers.be | v2503_SA_groene_stroom.pdf | Afhankelijk van waar de gemeente gelegen is: Provincie Oost-Vlaanderen,   Provincie West-Vlaanderen en Provincie Antwerpen.
statbel_combi | Statbel - statistische sectoren/officiële oppervlakte gemeenten \|   provincies.incijfers.be |   |  
dep_omgeving_fluvius | Fluvius via Departement Omgeving \| provincies.incijfers.be | v2501_energie_CO2_inventaris.pdf |  
uitgedoofd | OPGELET: verouderde data \| provincies.incijfers.be |   | Je zou deze data niet meer mogen zien. Is dat toch het geval, laat dit   dan weten aan info@provincies.incijfers.be . We wijzen je dan de weg naar de   correcte opvolger van deze reeks. Bezorg ons de link en/of een screenshot van   waar je deze reeks precies zag.
vea_dep_omgeving | Vlaams Energie- en Klimaatagentschap (VEKA) en Departement Omgeving\|   provincies.incijfers.be | v2503_hernieuwbare_elektriciteitsproductie.pdf |  
monumentenwacht | Monumentenwacht Vlaanderen vzw | v2911_objecten_abonnees_monumentenwacht.pdf | Objecten en abonnees Monumentenwacht
dna_rijksregister | dna_rijksregister |   |

**Comment by joostschouppe** [comment]
[Overzicht van de bronnen volgens wat er nog moet gebeuren
](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Redactiegroep%20PinC/Kwaliteitscontrole/Controlebestanden/DataSources-HTMLs.xlsx?d=wd0b91ed95d174b768d07c4d4e379fc0a&csf=1&web=1&e=Yyc0wy
)
(Redactiegroep PinC > Kwaliteitscontrole > Controlebestanden)

## Opties voor de Naam van de Bron:

1. We houden de toevoeging, zowel in de CODE als in de NAME, maar we korten de NAME in. (Maar bij sommige bronnen kunnen we dat waarschijnlijk niet zomaar inkorten, omdat de bron zelf een specifieke verwijzing vraagt) Dit kan eventueel dan via SHORT NAME, maar dan moet die in het vervolg gebruikt worden bij figuren en rapporten. Of gewoon rechtstreeks in de NAME. Hier bijvoorbeeld iets als ‘Vlaams Ministerie Onderwijs en Vorming – Hoger onderwijs’

2. We gebruiken de toevoeging enkel in de CODE en niet in de NAME: dus dan zou het bij Statbel terug overal gewoon Statbel worden, in plaats van Statbel – ABC, Statbel – Fiscale inkomens enzovoort. Via de CODE (statbel_abc, statbel_fisc-ink…) wordt dan wel de juiste metadatafiche toegekend aan deze data, en je kan in de DESCRIPTION wel beschrijven over welke data dit precies gaat (als dat niet duidelijk genoeg zou blijken uit de broncode).
(dit laatste is vooral mooier in figuren, MAAR heeft ook nadelen)

## Voorstel instructies voor aanpassing:
- kijk na waarom er lege records zijn. Soms zijn dit testonderwerpen, meestal zijn het vergetelheden
Er zijn dan twee mogelijkheden:

Bronnen splitsen zelf
* je maakt een nieuwe bron aan (via ADD) in de tabel van de datasources: https://provincies.incijfers.be/admin/studio/Table?tableName=DataSource. Bijvoorbeeld met als code 'dep_onderwijs_hoger_onderwijs' en als name 'Departement Onderwijs en Vorming van de Vlaamse Gemeenschap - Hoger onderwijs' (of liefst iets korters). 
* Daar zet je in de kolom INFO URL de bijhorende metadatafiche, dus in het voorbeeld 'v2311_ho.pdf'. 
* Dan exporteer je in de indicatorentabel alle indicatoren die een andere bron moeten hebben, in het voorbeeld dus alles met 2311 als indicator code. Hou enkel de kolom met indicator code, more info en source over
* Je past de bron aan en je laadt die terug op. 
Als je een DataSource code aanpast binnen Studio, dan worden de geassocieerde onderwerpen automatisch mee aangepast.

**Comment by joostschouppe** [comment]
Opmerking: het gebruik van Short Name in rapporten is wel degelijk instelbaar in rapporten via "Labels". Maar dat werkt niet! ABF volgt het op via Melding 115214

**Comment by Tine-VB** [comment]
_elke aparte metadatafiche moet gekoppeld zijn aan een aparte bron. Is dit nog niet het geval, dan moet de bron gesplitst worden, en wordt het (deel)thema of de specifieke verwerking toegevoegd aan de naam, volgens de afgesproken regel: “Naam van de bron - naam van de verwerking of het (deel)thema | provincies.incijfers.be”_
Soms is het ook een optie om de metadatafiches samen te voegen natuurlijk...

**Comment by joostschouppe** [comment]
Goed punt; ik heb dit nog aan de tekst toegevoegd:

> Af en toe zijn er meerdere fiches voor één enkele verwerking. Dan is het wellicht beter deze samen te voegen! Heel uitegreide metadata kan eventueel nog in een bijlage toegevoegd worden.

**Comment by HanneODB-VLBR** [comment]
'Short name' mag blijkbaar maximaal 50 karakters zijn. Met de toevoeging '| provincies.incijfers.be' zit je snel over deze max, en het is niet altijd evident om dan nog een goede afkorting te vinden (bv. 'ABB Gemeente- en stadsmonitor | provincies.incijfers.be' is al te lang). Is er eventueel een mogelijkheid dit veld langer te maken?

**Comment by HanneODB-VLBR** [comment]
Voorlopig heb ik er 'ABB Gem. en stadsmonitor | provincies.incijfers.be' en 'ABB Lok. Best. VL | provincies.incijfers.be' van gemaakt maar vind het zelf toch suboptimaal, zeker als deze short name bij figuren en rapporten gebruikt gaat worden...

**Comment by joostschouppe** [comment]
De instructies zeggen: Voeg ook een "short name" toe met enkel de naam van de bron-ogranisatie, vb. "Dep. Onderwijs en Vorming | provincies.incijfers.be"

Dus dit zou twee keer gewoon "ABB | provincies.incijfers.be" worden.

Ik zou het nu gewoon zo uitrollen, we kunnen altijd achteraf nog bulk-wijzigingen in de naamgeving doen.

**Comment by joostschouppe** [comment]
Redactiegroep 14/11/2022: doe verder volgens instructies hierboven. Eventueel kunnen bulk-aanpassingen achteraf. Maar blijf het melden als er rare dingen zijn of als er cases te complex zijn

**Comment by joostschouppe** [comment]
Opmerking: als de HTMLs verdwijnen, dan gaan ook sommige [URLs naar de metadata](https://provincies.incijfers.be/admin/studio/Table?tableName=UrlLink) in de themaboom verdwijnen

**Comment by veravandestraat** [comment]
Ik heb DataSource ANB opgesplitst voor alle indicatoren die extern staan, maar ik zie dat er nog een aantal indicatoren aan ANB gekoppeld zijn die vorig jaar niet opnieuw opgeladen werden (v2530_opp_hab_rbb, v2530_opp_hab_eur, v2530_opp_ohab, vp2530_opp_hab_rbb_tovot, vp2530_opp_hab_eur_tovot, vp2530_opp_ohab_tovot). Zet ik die op uitdovend met bron empty, zodat ANB als DataSource geschrapt kan worden?

**Comment by joostschouppe** [comment]
Vera, hebben die indicatoren ooit extern gestaan? Indien niet, dan mag je ze gewoon deleten

**Comment by Emilien-Dupont** [comment]
Zou voor Vl-Br in orde moeten zijn.
Lim: in orde, behalve VMM in cijfers
O-Vl: in orde
W-Vl: bijna in orde
A'pen: in orde

**Comment by Lievendr** [comment]
nagekeken. lijkt ok

**Comment by GeertBonte** [comment]
W-Vl: in orde

**Comment by joostschouppe** [comment]
Redactiegroep 25/5/2023
Naar aanleiding van de opmerking van Hilde deed ik een check op bronnen die niet van de vorm "bronorganisatie - thema" waren. De meeste zijn nu opgelost, de andere zijn doorgespeeld naar de verantwoordelijken
