### ISSUE TITLE
Project-issue: Overstap naar het nieuwe metadatasysteem

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#318]
Projectfiche:
https://docs.google.com/document/d/1EN3ZxigfXtgKtxq1Lmfj2MWvaZZOVGJ3kQRCKfbfGFw/edit#heading=h.6a6tzh9xxf5f

Algemeen: we briefen regelmatig naargelang het nieuwe systeem vorm krijgt. Naar aanleiding van de vorige nieuwe release https://github.com/provinciesincijfers/PinC-taakopvolging/issues/293 kon dit getest worden. Maar daar werden enkele bezwaren geopperd tegen hoe het er nu zou uitzien. Dit nemen we ondertussen terug op. 

De voorlopige afspraken daaromtrent staan [in dit deel van het eerder vermelde document](https://docs.google.com/document/d/1EN3ZxigfXtgKtxq1Lmfj2MWvaZZOVGJ3kQRCKfbfGFw/edit#heading=h.lkt14nkxxox)

Gebruik dit ticket om mogelijke verdere issues/nodige afspraken ivm deze overstap te melden.

**Comment by joostschouppe** [comment]
Afspraak redactiegroep 20/9/2022:

In het nieuwe metadatasysteem (zie beta) zie je bij de infofiche bij ‘Bronnen’ de ingevulde velden van bij de DataSources. Maar, de volgorde en de namen van de velden kunnen we niet veranderen. Dit is vrij vervelend voor de velden ‘Beperkingen’ en ‘Eigen verwerkingen’, deze noemen nu ‘Vrij Textveld 1’ en ‘Vrij Textveld 2’. Er is ook geen standalone pagina. Dus ofwel maken we een omweg waarbij we de velden zelf kunnen benoemen, ofwel gebruiken we het nieuwe systeem en zetten we die velden bij de Algemene beschrijving.  

We laten het nog even voor wat het is en dringen aan bij abf om het op te lossen.

**Comment by joostschouppe** [comment]
Nieuw, vereenvoudigde fiche gemaakt: https://docs.google.com/document/d/14pLpnH3lvmBt7qiYVBJhXryIazPTJT6pQBWOh8VJN1I/edit?usp=sharing

**Comment by joostschouppe** [comment]
Redactiegroep 14/11/2022: Joost roept beperkt groepje samen om keuze ivm timing overstap te maken en eventueel volgend gresprek met ABF hierover voor te bereiden

**Comment by Emilien-Dupont** [comment]
Instructies voor de omschakeling staat op [teams](https://vlbr.sharepoint.com/:f:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/General/metadata?csf=1&web=1&e=WJbiIb). Wordt overlopen tijdens de open office van 12/03

**Comment by Emilien-Dupont** [comment]
## Belangrijkste afspraken
- deadline is 01/06 om alle bestaande metadatafiches om te zetten in de **bèta**
- iedereen gaat de hergebruiksvoorwaarden na. indien de bron dit niet ter beschikking stelt, vul dan 'Geen informatie begschikbaar bij de bron' in. 
- nu zetten we in de voetnoot iets als het jaartal afwijkt van de bron. Als je nog op andere dingen komt die hierin komen, geef dit dan aan in het document. 

de instructies staan  [hier](https://vlbr.sharepoint.com/:f:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/General/metadata?csf=1&web=1&e=WJbiIb).

## Te bespreken in de redactiegroep
**Welke informatie mag getoond worden bij ‘onderwerpen’ van de metadata?** 

Als je aanvinkt dat de nieuwe metadata getoond mag worden, staan er default al een aantal zaken aangevinkt die getoond mogen worden bij de metadata van de indicator, vanuit zowel de indicatorentabel (nu onder de tab ‘Eigenschappen’ en ‘Beschikbaarheid’) als uit de datasource tabel (nu: de metadatafiche, onder tab Informatie). Dit komt dan onder een rubriek ‘Onderwerpen’ en ‘Bronnen’.  

Onder informatie vanuit de indicatorentabel staan er al een heel aantal zaken aangevinkt met een aantal verschilpunten ten opzichte van de oude metadata. Er moet nog uitgeklaard worden of we alle info vanuit de onderwerpentabel dat we in bij de oude metadata zagen, ook in het nieuwe systeem willen zien. 

_Oude metadata_ 
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/77432663/e2eb8889-2467-4918-b3f6-073b689374e2)

 

_Nieuwe metadata_
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/77432663/cfb394f2-c85f-4fd3-89f0-9cfe56444f7a)

 

_De verschilpunten_ 

- Periodetype: enkel aangevinkt in nieuwe metadata: afvinken 
- Aggregeer gebieden: enkel aangevinkt in nieuwe metadata: afvinken 
- Aggregeer perioden: enkel aangevinkt in nieuwe metadata: afvinken 
- Meer informatie: in de nieuwe linkt dit door naar het veld Meer informatie, waar nu de PDF van de metadata zit. In het oude systeem is dit een tab met daarin de pdf.  --> afvinken. 
- Afronding: enkel in oude metadata --> aanvinken 
- Interpolatie: enkel in de oude metadata --> mag afgevinkt blijven 
- Laatste wijziging: enkel in de oude metadata --> afgevinkt houden 

 

**Welke informatie mag getoond worden in het Dashboard?** 

Mosaic Detailview (ook Stories!). Hier staat het nieuwe metadatasysteem al aangevinkt. Nu zie je:  

- Beschrijving onderwerp: uit indicatorentabel 
- Korte bronnaam: uit bronnentabel. Dit afvinken? 
- Staat ook aangevinkt: beschrijving bron (maar nog niet ingevuld). Dit moet nog afgevinkt worden 
- More information: een link naar de pdf van de metadata. Dit zal vervallen. 

Nog aan te vinken: 
- Voetnoot 
- Lange naam of source data owner. Bv: VDAB - Vacatures | provincies.incijfers.be versus Vlaamse Dienst voor Arbeidsbemiddeling en Beroepsopleiding (VDAB). (edit: Lange naam kan je niet aanvinken?)

**Comment by HanneODB-VLBR** [comment]
Bij Vlaams-Brabant hebben we niet meer voldoende tijd om dit intern te bespreken. Is het eventueel mogelijk dit topic te verdagen naar de volgende redactiegroep aub?

**Comment by Emilien-Dupont** [comment]
Redactie 19/03/24:
Tegen de volgende redactie doet iedere provincie een voorstel voor de Viewer (indicatoren) en de Mosaic Detailview (uit bronnen- en indicatorentabel)

**Comment by Lievendr** [comment]
Metadatafiche
Beschrijving onderwerp: uit indicatorentabel OK
Korte bronnaam: afvinken OK
Beschrijving bron: afvinken OK
Voetnoot
Lange naam of source data owner. **VDAB - Vacatures | provincies.incijfers.be** en NIET Vlaamse Dienst voor Arbeidsbemiddeling en Beroepsopleiding (VDAB).

**Comment by Tine-VB** [comment]
VlBr: akkoord met wijzigingen zoals voorgesteld door Emilien voor nieuwe metadatafiche. 

MAAR:

- Beschikbaarheid: Dit is wel interessant, maar het lijstje met Beschikbaarheid is bij de meeste variabelen een heel lange lijst: kan dit op een bepaalde manier korter gemaakt worden? In het voorbeeld van Emilien hierboven is dit nu net een uitzonderlijke variabele, omdat die enkel tot op gemeente beschikbaar is. Meestal staan er alle gebiedsniveaus, inclusief die van gemeente indeling t.e.m. 2018... Voorbeeld:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/61458346/0936057b-33b7-469d-b9d1-cec5969f64f0)

- Thema's: voor ons als beheerders is dit heel nuttig, maar voor gewone gebruikers is dat niet interessant (productie intern, connectoren...), en het is ook vaak een lange lijst. Voorbeeld:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/61458346/186966c6-9eda-48a9-84ab-cf48ec9c72b8)

Zowel Beschikbaarheid als Thema's zouden we toch laten staan als het niet kan verkort worden. Het staat gelukkig wel achteraan

**Comment by Tine-VB** [comment]
VlBr: Dashboard

- Akkoord om de lange naam te gebruiken en de korte naam weg te laten. Maar moet er een titeltje staan als 'Korte naam' of 'Lange naam'? Hopelijk kan dat weg?
- Andere wijzigingen ook OK.
- Maar kan er daar ook doorgeklikt worden naar de metadata? En: goed bekijken wat we dan in voetnoot zetten.

**Comment by Emilien-Dupont** [comment]
De lange naam kan je niet aanvinken, deze staat niet in de lijst van aanvink mogelijkheden. Dat heb ik, samen met de titel 'korte naam' ingeseind bij ABF. Hopelijk wordt dit wel mogelijk want de korte naam geeft in sommige gevallen niet genoeg info. 
Er kan niet doorgeklikt worden naar de metadata, omdat dit nu verwijst naar de pdf file. De link naar de pdf file verschijnt overigens ook niet bij alle tegels.

**Comment by GeertBonte** [comment]
Voor iedereen die worstelt met de omzetting van (delen van) de metadatafiches naar HTML:

Ik heb een Python-script gemaakt waarmee Word-bestanden gemakkelijk te converteren zijn naar HTML. Ik heb het script losgelaten op alle Word-metadatafiches die op Teams staan. Het resultaat vinden jullie in deze map:

[D&A - Interpr. werking > Uploadfiles PinC > 00 Metadatafiches PinC > fiches geconverteerd naar html](https://vlbr.sharepoint.com/:f:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Uploadfiles%20PinC/00%20Metadatafiches%20PinC/fiches%20geconverteerd%20naar%20html?csf=1&web=1&e=HNnYgA)

Zoek in deze map naar de HTML-versie van metadatafiche(s) die je nodig hebt en open het HTML-bestand in een teksteditor. Vervolgens kun je de nodige fragmenten selecteren, kopiëren en plakken in je eigen HTML-document of in een veld van de bronnentabel dat HTML accepteert.

Let op: als je dit kopieert naar een veld in de bronnentabel (bijvoorbeeld het Description-veld), dan moet je eerst alle regeleinden verwijderen, zeker bij opsommingen of tabellen. Anders krijg je ongewenste blanco regels. Als je dit kopieert naar je eigen HTML-bestand, dan mag je dit letterlijk overnemen en moet je geen regeleinden verwijderen.

**Comment by GeertBonte** [comment]
Ter info: ik leg momenteel ook de laatste hand aan een ander Python-script, waarmee het mogelijk zal zijn om periodiek en op een geautomatiseerde manier alle links te checken die we gebruiken in onze metadata: zowel links in de velden van de bronnentabel als links in de HTML-bestanden. Nu stellen we immers vaak per toeval vast dat een of andere link in een of andere metadatafiche niet meer werkt, of we worden daarop geattendeerd door een welwillende gebruiker. Wanneer dat straks automatisch en op regelmatige tijdstippen gecontroleerd kan worden met een script, zullen we veel sneller gealarmeerd worden wanneer een link niet meer blijkt te werken (of omgeleid wordt naar een andere pagina) en zullen we dus veel sneller kunnen ingrijpen.

**Comment by Emilien-Dupont** [comment]
RG 18/04
Oke om beschikbaarheid en thema's op te nemen + korte bronnaam (lange naam gaat niet, naar wensenlijst bij abf).
Emilien voegt de checks van de URL's in bronnen toe aan de periodieke checks.

**Comment by Emilien-Dupont** [comment]
RG 23/045/24:
Tine en Emilien zullen vooral kijken of het eenvormig is en of de code werkt.

Emilien vraagt aan ABF of er witruimte/witregels mogelijk zijn tussen de velden.  

Geert maakte een script in css zodat de stijl in het HTML bestand wat overeenkomt met de stijl in het nieuwe metadatasysteem. Dit controleren Tine en Emilien ook nog achteraf voor alle fiches. 

Onder bronbestanden staat 'voor meer informatie', maar dat is wat dubbelzinnig omdat we onderaan iets gelijkaardigs hebben. Dat moeten we misschien anders formuleren.  

Voor de fiches die de laatste maanden nog werden aangepast, moeten de verantwoordelijken zeker controelren of de aanpassingen ook in het nieuwe metadatasysteem toegevoegd werden. Emilien neemt dit mee in haar reminder.

**Comment by Emilien-Dupont** [comment]
Ter info: uitdovende bronnen (RG)

**Comment by Emilien-Dupont** [comment]
Onder Information files (https://provincies.incijfers.be/admin/studio/File?type=info) staan nog een heleboel oude metadatafiches, te herkennen aan de pdf extensie en aan de indicatorcode aan het begin van de bestandsnaam. Mogen deze verwijderd worden?
