### ISSUE TITLE
Welke data in PINC voor energieverbruik huishoudens?

### ISSUE THREAD

**Issue by StefanieWVL** [provinciesincijfers/PinC-taakopvolging#319]
Er zijn 2 bronnen die data ter beschikking stellen i.v.m. energieverbruik van huishoudens: VEKA (rapport klimaat) en Fluvius (ook beschikbaar op stat sec).

Welke van de 2 geniet de voorkeur voor PINC?

**Comment by joostschouppe** [comment]
Zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/156#issuecomment-1205009114
