### ISSUE TITLE
foutje in rapport demografie

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#32]
Als je een rapport demografie – deelgemeente opvraagt, dan staan er bij de inleiding verkeerde kaarten
Bv middelkerke  of anzegem

De eerste kaart geeft geen situering binnen de provincie, en de tweede kaart toon niet de gemeente.

Voor het deelgemeenterapport is het misschien interessanter om op een eerste kaart de gemeenten te situeren, en op een tweede kaart de deelgemeente binnen de gemeente.

**Comment by joostschouppe** [comment]
Er gaat iets mis in de code. Ingeseind bij ABF, melding 82421

**Comment by davidcardinaels** [comment]
Na antwoord van ABF is dit aangepast in de steekkaart demografie en toegevoegd aan het sjabloon.

**Comment by joostschouppe** [comment]
@davidcardinaels : toen ik gisteren het sjabloon voor twee gemeenten opvroeg, liep het vast. Ik heb het aangepast opdat het wel zou werken, zonder goed na te denken of het de meest optimale oplossing is nu. Check alleszins eens wat er in demografie gebeurt.
