### ISSUE TITLE
Verdere fine-tuning Description

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#320]
1. Huidig: _Percentages, promilles, ratio's, … worden omgeschreven met (t.o.v. inwoners, …)._
Voorstel: 
- deze regel enkel behouden voor **percentages**.
- vastleggen dat we doen wat we nu al doen voor **promille**:
[promille] geboorten in de loop van een jaar per 1.000 inwoners
[promille] zorgbudgetten voor personen met een handicap van 45-64 jaar per 1.000 inwoners van 45-64 jaar
- voor ratio is het wat afhankelijk van de indicator, maar is het meestal zoals bij promille:
[ratio] bevolkingsdichtheid: aantal inwoners per km²
[ratio] CO₂-uitstoot (in ton) in de sector 'transport' per inwoner
[ratio] gevallen van diefstal en afpersing per 1.000 inwoners
[ratio] spanningsratio - WZW
[ratio] PV-installaties kleiner dan (of gelijk aan) 10 kW per 100 huishoudens

2. Regel ivm 75+ en varianten.
Zeg niet 75+, 75-plus, 75-plussers, 75 jaar en ouder maar zeg **75-plussers**
("75 jaar en ouder" komt ook voor)

3. Huidige regel: "De **beschrijving begint bij een berekend onderwerp** met [percentage], [promille], [ratio], … . Het type komt m.a.w. tussen de vierkante haakjes."
Momenteel in gebruik: - De **beschrijving begint** met [aantal], [percentage], [promille], [ratio], … . Het type komt m.a.w. tussen de vierkante haakjes.

4. Nieuwe regel: "Als je de eenheid meegeeft in de Description, schrijf dit dan tussen ronde haakjes"

**Comment by joostschouppe** [comment]
[Een overzicht van hoe de handleiding er na de aanpassing uit zou zien](https://github.com/provinciesincijfers/PinC-taakopvolging/files/9459807/Aanpassingen.github.beschrijvingen.docx)

**Comment by joostschouppe** [comment]
Goedgekeurd door redactiegroep.

**Comment by Tine-VB** [comment]
Ik doe nog enkele aanpassingen op basis van deze afspraken (o.a. aan namen van oppervlaktes).

**Comment by joostschouppe** [comment]
Afspraak redactiegroep 20/9/2022: we voegen de aanpassingen door in JiveDocumentation zoals in bijlage van Tine voorgesteld
