### ISSUE TITLE
Unit voor 'vast' percentage dat niet in PinC werd berekend

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#321]
Klein 'issuetje' om even af te kloppen op de redactiegroep:

Wanneer je een 'vast' percentage inlaadt dat niet wordt berekend in PinC, moet dit dan met 'percentage' of met 'aantal' worden gelabeled?

Voorbeeldje: tarieven algemene personenbelasting, dit zijn de percentages op basis waarvan je APB wordt berekend.

**Comment by joostschouppe** [comment]
Of het cijfer berekend wordt binnen Swing of niet lijkt me hier geen impact te hebben. Het enige bijzondere aan dit soort onderwerp is dat je ofwel een aggregatieonderwerp moet instellen, ofwel het onderwerp op "niet aggregeren" moet zetten.
