### ISSUE TITLE
Check inhoudsopgave rapporten

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#324]
Naar aanleiding van onderstaande opmerking van @GeertBonte op Rapport Opvang baby's en peuters lopen we best eens de inhoudsopgave van alle rapporten na:

_Tenslotte bij de Inhoudsopgave: het laatste kopje in de inhoudsopgave is **Bronnenoverzicht**. Dat kopje komt in het rapport echter niet voor. De link gaat naar het kopje **Gedetailleerde info over de gebruikte cijfers**. Alle andere kopjes in de inhoudsopgave stemmen overeen met de bijbehorende kopjes in het rapport, behalve dit ene kopje. Ik heb al gemerkt dat dat ook in andere rapporten vaak zo is, maar niet altijd. Het lijkt me onlogisch om in het rapport en in de inhoudsopgave verschillende kopjes te gebruiken._

**Comment by joostschouppe** [comment]
Voorstel: we passen beide aan naar "Meer informatie over de cijfers en bronnen"

**Comment by joostschouppe** [comment]
Wordt opgelost via #328
