### ISSUE TITLE
Rapport Klimaat en energie - aanpassingen + voorstel naamsverandering

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#325]
**Tijdlijn**

Aanpassingen aan het rapport te volgen in:  https://drive.google.com/drive/folders/1bP1WsZ6ZQLuiQ60InQ6koVnPSykaxQ96

aanstaande vrijdag 30/09 - herwerkte versie klaar [INTERN --> nodig voor werkgroep Klimaat]
maandag 03/10 en dinsdag 04/10: mogelijkheid om opmerkingen door te geven 
donderdag 06/10 en vrijdag 07/10: laatste aanpassingen door David

maandag 10/10: [EXTERN] publiceren
donderdag 13/10: aankondigen op Klimaatdag VVSG
dinsdag 18/10: Nieuwsbrief PinC

**Comment by StefanJacques** [comment]
deadline gehaald
geactualiseerd en uitgebreid rapport te vinden op: https://provincies.incijfers.be/databank/report?openinputs=true&id=rapport_klimaat

opmerkingen/suggesties van D&A (bij het nalezen van de draft) werden goedgekeurd of indien de suggestie niet werd gevolgd uitgelegd in een bestand dat tijdens een Open Office-moment (D&A + klimaat) in het najaar zal besproken en geduid worden.

ik zoek voor dat Open  Office-moment nog een datum.

**Comment by joostschouppe** [comment]
Bij Grafiek 20 - Evolutie dominant vervoersmiddel voor woon-werkverkeer, % t.o.v. repondenten (2017 en 2020) staan de labeltjes nog aan, die moeten uit

**Comment by davidcardinaels** [comment]
Grafiek 20 in orde

**Comment by StefanJacques** [comment]
Door uitgebreider cijfermateriaal  (oa. EPC + EPB, gemeentelijke gebouwen en installaties (2021) in de CO2-inventaris, de warmtenetten, ...) en rekening houdend met een aantal suggesties vanuit de bevraging in 2023 over het rapport Klimaat en Energie, heeft de "werkgroep Klimaat - mitigatie" de afgelopen maanden zitten sleutelen aan de inhoud van het rapport.

De nieuwe structuur zal er als volgt uitzien (in vet gewijzigde onderdelen):
1.      Globale CO2-cijfers 
 **2.      Gemeentelijke gebouwen en  installaties/voorzieningen**  
3.      Huishoudens 
         1.      Totale CO2-uitstoot door huishoudens 
         2.      Energieverbruik woningen 
         3.      Energieprestaties woningen 
.                       E-peil nieuwbouwwoningen 
.                       **Energieprestatiecertificaten (EPC’s)**  
         4.      Renovatie en premies 
         5.      Het woningbestand 
         6.      Andere factoren die een invloed hebben  
4.      Mobiliteit 
**5.      Lokale energieproductie-afname** 
            1.      Hernieuwbare elektriciteit 
            2.      Duurzame warmte 
                       Warmtekrachtkoppeling  
                       **Warmtepompen, warmtepompboilers en zonneboilers.**   
                       Warmtezonering 
                       **Warmtenetten** 
6.      Landbouw 
7.      Industrie en tertiaire sector 
8.      Andere nuttige cijfers
9.      Kerncijfers klimaat

**Comment by Emilien-Dupont** [comment]
Redactie 19/03/24:
Akkoord
