### ISSUE TITLE
Helderdere naamgeving indicatoren

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#326]
Afspraak redactiegroep 20/9/2022:
Als je in de Databank grafieken maakt en ziet zonder themaboom, weet je soms niet dat het over een selectie gaat. Bv: ‘huurprijzen’, maar dit is enkel van sociale woningen.  

Er is een regel dat een naam uniek moet zijn. Afspraak: als het niet duidelijk is bij welk thema een indicator hoort, moet je het in de naam vermelden. Behalve als het dan te lang wordt – je mag de regels breken wanneer de onderwerpnaam dan te lang wordt. Afspraak: de naam moet duidelijk zijn zonder themaboom. Joost en Emilien doen een algemene check.

Stap 1: welke namen zijn niet uniek en staan extern
Stap 2: alles overlopen... 
Stap 3: algemene regel opnemen in JiveDocumentation

**Comment by joostschouppe** [comment]
Voor stap 1: er zijn drie types
([verwerking](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/_layouts/15/Doc.aspx?sourcedoc=%7BB2EA9C7C-6CFF-408B-B0C9-424D97F517D7%7D&file=check%20dubbele%20namen.xlsx&action=default&mobileredirect=true&cid=10101d32-6637-4ac5-9279-dac63926e510))

1. We maken twee keer hetzelfde cijfer aan

Het gaat hier enkel om v1114a_alleenw en v1115a_alleenw. Voorstel: een van de twee intern zetten (vb 1114), en dus overal in de themaboom waar 1115 voorkomt dat veranderen door 1114. Vervolgens best 1115 op uitdovend zetten en niet meer opnieuw aanmaken. Is dat OK @rudymarynissen ?

2. Echte issues:

Er is effectief een heel verschillend onderwerp dat toch dezelfde naam heeft. Deze moeten goed nagekeken worden.

onderwerpcode | naam
-- | --
v2201_woning_totaal | woongelegenheden
v2210_woonvoorraad | woongelegenheden
vp2201_eengezins | eengezinswoningen (t.o.v. woongelegenheden)
vp2210_wv_eengezinswoningen | eengezinswoningen (t.o.v. woongelegenheden)
v2201_gebouw_totaal | gebouwen
v2208_gebouwen | gebouwen
v2712_grasland_1 | oppervlakte grasland
v1591_opp_or_grasland | oppervlakte grasland
vp2712_grasland_1 | oppervlakte grasland (t.o.v. totale oppervlakte)
vp1591_grasland | oppervlakte grasland (t.o.v. totale oppervlakte)

3. Naamgeving issue:

Een heel aantal onderwerpen hebben dezelfde naam als aantal en als percentage. Is dit in strijd met de regels? En willen we dat zo houden?

onderwerpcode | naam
-- | --
v2603_aankomst_belg | aankomsten door Belgen
vp2603_aankomst_belg | aankomsten door Belgen
v2603_aankomst_buitenland | aankomsten door niet-Belgen
vp2603_aankomst_buitenland | aankomsten door niet-Belgen
v2302_aso_indicator | indicatorleerlingen ASO - VP
vp2302_aso_indicator | indicatorleerlingen ASO - VP
v2301_bso_indicator | indicatorleerlingen BSO - WP
v2302_buso_meisjes | meisjes in het BuSO - VP
vp2302_buso_meisjes | meisjes in het BuSO - VP
v2301_buso_meisjes | meisjes in het BuSO - WP
vp2301_buso_meisjes | meisjes in het BuSO - WP
v2603_overnachting_belg | overnachtingen door Belgen
v2603_overnachting_buitenland | overnachtingen door niet-Belgen
vp2603_overnachting_buitenland | overnachtingen door niet-Belgen
v2603_overnachting_type_bb | overnachtingen in BenB
v2603_overnachting_type_hotel | overnachtingen in hotel
vp2603_overnachting_type_hotel | overnachtingen in hotel
v2603_overnachting_type_o | overnachtingen in overige type logies
vp2603_overnachting_type_o | overnachtingen in overige type logies

**Comment by joostschouppe** [comment]
Voor stap 2:

De enige issues die ik heb kunnen vinden zitten allemaal onder het thema Wonen, verantwoordelijkheid West-Vlaanderen. @GeertBonte, kijk je eens of je dit opgelost krijgt?

ItemCode | naam | cat2 | cat3 | cat4
-- | -- | -- | -- | --
v2201_geb_kl104m | tot 104 m² | Woningen en gebouwen | Officiële statistiek | Gebouwen naar oppervlakte
v2201_geb_gr104m | groter dan 104 m² | Woningen en gebouwen | Officiële statistiek | Gebouwen naar oppervlakte
vp2201_geb_kl104m | tot 104 m² (t.o.v. gebouwen voor eengezinswoningen) | Woningen en gebouwen | Officiële statistiek | Gebouwen naar oppervlakte
vp2201_geb_gr104m | groter dan 104 m² (t.o.v. gebouwen voor eengezinswoningen) | Woningen en gebouwen | Officiële statistiek | Gebouwen naar oppervlakte
v2201_geb_cv | cv of airco | Woningen en gebouwen | Officiële statistiek | Gebouwen naar gerieflijkheden
v2201_geb_badk | minstens 1 badkamer | Woningen en gebouwen | Officiële statistiek | Gebouwen naar gerieflijkheden
v2201_geb_garage | minstens 1 garage | Woningen en gebouwen | Officiële statistiek | Gebouwen naar gerieflijkheden
vp2201_geb_cv | cv of airco (t.o.v. deel gebouwen) | Woningen en gebouwen | Officiële statistiek | Gebouwen naar gerieflijkheden
vp2201_geb_badk | minstens 1 badkamer (t.o.v. deel gebouwen) | Woningen en gebouwen | Officiële statistiek | Gebouwen naar gerieflijkheden
vp2201_geb_garage | minstens 1 garage (t.o.v. deel gebouwen) | Woningen en gebouwen | Officiële statistiek | Gebouwen naar gerieflijkheden
v2202_gemiddelde_huurprijs | gemiddelde huurprijs | Sociaal wonen | Sociale huurders bij SHM | Gemiddelde huurprijs
v2202_wachttijd | gemiddelde wachttijd | Sociaal wonen | Kandidaat-huurders bij SHM (naar   domicilie)
v2211_ar_hs_dakloos | was dakloos | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_garage | geen woning maar garage | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_gesloopt | gesloopte woning | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_huurdersvk | huurder SVK-woning | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_ni | niet ingevuld | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_onaangep | onaangepaste woning | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_onges | ongeschikte/onbewoonbare woning | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_onv | onveilige/ongezonde woning | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_overbew | overbewoonde woning | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_tkw | te kleine woning | Premies | Huursubsidie | Aanvraagreden
v2211_ar_hs_camping | verlaat een camping | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_dakloos | aanvrager was dakloos (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_garage | geen woning maar garage (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_gesloopt | gesloopte woning (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_huurdersvk | huurder SVK-woning (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_ni | niet ingevuld (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_onaangep | onaangepaste woning (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_onges | ongeschikte/onbewoonbare woning (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_onv | onveilige/ongezonde woning (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_overbew | overbewoonde woning (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_tkw | te kleine woning (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden
vp2211_ar_hs_camping | verlaat een camping (t.o.v. aanvragen) | Premies | Huursubsidie | Aanvraagreden

**Comment by Tine-VB** [comment]
_Een heel aantal onderwerpen hebben dezelfde naam als aantal en als percentage. Is dit in strijd met de regels? En willen we dat zo houden?_
Bij de percentages zou er altijd (t.o.v. ...) moeten bijstaan.

**Comment by HildeC** [comment]
bij woningen en gebouwen:
we hebben officiele statistiek (V2201)
en we hebben eigen verwerking.  (v2210)
in de redenering bij eigen verwerking hebben we naar terminologie kadaster gekeken, daar spreken ze van wooneenheden, en we hebben voor de eigen verwerking Woongelegenheid gecreëerd. dus tot zover zat verschil goed.
Maar: statbel spreekt bij de verwerking van de gegevens kadaster ook ineens van woongelegenheid, en niet van wooneenheid. geen idee of er een verschil zit tussen wooneenheid kadaster en woongelegenheid statbel. er zit wel een verschil tussen woongelegenheid kadaster en woongelegenheid eigen verwerking.
ik was voorstander om bij data over woningen en gebouwen enkel 1 officieel cijfer te geven (net zoals bij bevolking ) en voor de rest de eigen verwerking. maar op moment dat we begonnen zijn met eigen verwerking hadden we nog geen tijdsreeks, vandaar dat de collega's WVL ervoor geopteerd hebben om de twee naast elkaar te zetten.

hoe we het kunnen oplossen:
terminologie van statbel conform kadaster trekken en daar van wooneenheden spreken. (maar ik weet niet of dat 100% klopt)
statistiek van de woningen van statbel niet meer opnemen. maar dan missen we wel tijdsreeksen

**Comment by HildeC** [comment]
ik heb navraag gedaan bij statbel hoe ze van woonenheden (teleenheid) naar woongelegenheden (officiële statistiek) gaan

Statbel doet niet zelf de aggregatie.   
Het aantal wooneenheden is één van de termen van de constructiecode die het Kadaster per gebouw bijhoudt.
De som van alle deze wooneenheden leidt tot het aantal woongelegenheden. 
 
Vakantieverblijven (kadastrale aard 503) wordt ingedeeld bij “alle andere gebouwen” en daarvan wordt ook het aantal wooneenheden in rekening gebracht bij de woongelegenheden.

mbt de naamgeving van de indicatoren stel ik voor om in de officiële statistiek van wooneenheden te spreken, en in de eigen verwerking van woongelegenheden . de metadatafiches van officiele statistiek moet dus ook aangepast worden.

akkoord?

**Comment by rudymarynissen** [comment]
Akkoord,
groetjes,
rudy

Van: HildeCoudenys ***@***.***>
Verzonden: maandag 5 december 2022 14:10
Aan: provinciesincijfers/PinC-taakopvolging ***@***.***>
CC: MARYNISSEN Rudy ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] Helderdere naamgeving indicatoren (Issue #326)


ik heb navraag gedaan bij statbel hoe ze van woonenheden (teleenheid) naar woongelegenheden (officiële statistiek) gaan

Statbel doet niet zelf de aggregatie.
Het aantal wooneenheden is één van de termen van de constructiecode die het Kadaster per gebouw bijhoudt.
De som van alle deze wooneenheden leidt tot het aantal woongelegenheden.

Vakantieverblijven (kadastrale aard 503) wordt ingedeeld bij “alle andere gebouwen” en daarvan wordt ook het aantal wooneenheden in rekening gebracht bij de woongelegenheden.

mbt de naamgeving van de indicatoren stel ik voor om in de officiële statistiek van wooneenheden te spreken, en in de eigen verwerking van woongelegenheden . de metadatafiches van officiele statistiek moet dus ook aangepast worden.

akkoord?

—
Reply to this email directly, view it on GitHub<https://protect-de.mimecast.com/s/88gBC46A5rsR0XIOtbk9?domain=github.com>, or unsubscribe<https://protect-de.mimecast.com/s/WEk1C57B6vswjBtOA8x8?domain=github.com>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Disclaimer: Op deze e-mail is de wet van 13 juni 2005 over het vertrouwelijke karakter van elektronische communicatie van toepassing. De tekst van het relevante artikel 124 kun je op onze website consulteren. http://www.provincieantwerpen.be/over-deze-website.html

**Comment by demaesschalckfilip** [comment]
Ook akkoord!

**Comment by HildeC** [comment]
de term woongelegenheid werd vervangen door wooneenheid.

we zijn ondertussen nog op een ander probleem gestoten.
de statistiek van het gebouwenpark die we gebruiken om over 'woningen' te spreken maakt gebruik van de term 'gebouw' (v2201).
in het kader van ruimtebeslag wordt ook de term 'gebouw' gebruikt (v2208).
zelfde term, andere inhoud. vraag van Joost om dit op te lossen
we hebben in v2201 de term 'gebouw' vervangen door 'woongebouw' (is bestaand woord volgens groene boekje, de term 'gebouw om in te wonen' leek ons te lang).

de vraag waar we nu nog mee zitten: alle onderverdelingen van gebouw (bouwjaar, grootte, uitrustingsniveau): moeten we daar steeds de term 'woongebouw' gebruiken? of spreekt het voor zich dat het over woongebouwen gaat.
voorlopig hebben we geen andere gebouwen met bouwjaar (bv industrie) , ook geen andere gebouwen naar opp of uitrustingsniveau.

dus de vraag is: veranderen we nu al systematisch het woord 'gebouw' door woongebouw of doen we dat pas als er over andere inhouden ook bouwjaar, opp bij komen?

**Comment by valeriepirard** [comment]
'gebouw' van de v2208 slaat op alle soorten gebouwen (uit GRB). Het gaat om alle gebouwen die de grond afdekken, los van hun functie. Dus hier zou ik de term 'gebouw' behouden.
Als je wil dat de betekenis duidelijk is, los van de themaboom, zou ik inderdaad nu al consequent 'woongebouw' gebruiken voor de onderwerpen uit de officiële statistiek van het kadaster.

**Comment by StefanJacques** [comment]
opgelost voor alle LI(TOE) indicatoren startend met vp -->  werden aangevuld met (t.o.v. ...) - zoals het moet ;-)
@karolienbloemen 

<html>
<body>


onderwerpcode | naam | verantwoordelijke
-- | -- | --
v2603_aankomst_belg | aankomsten door Belgen | LI(TOE)_WV(TOE)
vp2603_aankomst_belg | aankomsten door Belgen **(t.o.v. totaal aankomsten)**  | LI(TOE)_WV(TOE)


</body>
</html>

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/12: we gebruiken term 'woongebouw'.
Iedereen kijkt na of (t.o.v.) gebruikt wordt bij percentages.
