### ISSUE TITLE
Onbebouwde percelen (vermoedens-ROP)

### ISSUE THREAD

**Issue by valeriepirard** [provinciesincijfers/PinC-taakopvolging#329]
#Redactiegroep
Ik heb nieuwe cijfers klaargezet over onbebouwde percelen, ter bevestiging voor de Redactiegroep.

Data: de data komen uit het vermoedens-ROP, statistieken op gemeentelijk niveau hierover werden ons aangeleverd door het Vlaams departement Omgeving. Geen eigen verwerkingen.

Infofiche: inhoudelijk opgesteld door mezelf, vormelijke controle is gebeurd door Tine.

De cijfers staan momenteel onder ‘**Intern’>’Ruimte/Geostats’>Ruimte>’Onbebouwde percelen’.** 
Voorstel is om ze extern te plaatsen onder het domein 'RUIMTE'.
Zonder tegenbericht van jullie zullen ze met de update van 14/10 worden gepubliceerd.

**Comment by joostschouppe** [comment]
Redactiegroep:
Op zich geen probleem, maar worden er updates voorzien aan de kant van de bron?

**Comment by valeriepirard** [comment]
De bron zegt jaarlijks updates te voorzien ja.
