### ISSUE TITLE
Aangepast standaard kleurenschema voor PinC?

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#330]
We kregen al wel vaker opmerkingen dat onze standaard blauwtintenkaart niet zo heel leesbaar is. Tijdens de laatste redactiegroep liet ik min of meer toevallig dit kaartje zien. Dat kleurenschema werd goed onthaald.

![](https://imgur.com/BkoiKs0.png) 

Maar past dat binnen PinC? Probeer het uit door op https://provincies.incijfers.be/admin/jive/ [deze workspace](https://github.com/provinciesincijfers/PinC-taakopvolging/files/9744051/kleuren.zip) te openen.
Het kleurenschema zelf heet voorlopig TESTblauw.

**Comment by Tine-VB** [comment]
De kaarten in PinC hebben normaal 5 klassen, dus de witte mag er dan uit? Verder vinden wij (D&A VlBr) dit een beter kleurenpallet. Dus OK!

**Comment by joostschouppe** [comment]
Ik heb gewoon de zes klassen meegenomen, Swing maakt er dan zelf iets van dat twee tot ??? klassen kan hebben. De bleekste klasse is niet wit, maar wel bijna.

**Comment by StefanJacques** [comment]
collega's Limburg willen ook verder met deze kleuren

**Comment by joostschouppe** [comment]
Redactiegroep:
- arcering nog proberen duidelijker te maken
- deze kleuren overnemen

**Comment by joostschouppe** [comment]
Dit is inmiddels uitgerold. Er is nog een bug: de nieuwe, zwaardere arcering is per ongeluk ook van toepassing op interactieve kaarten type "taart in kaart". Dit wordt deze week nog gefixed.

Een inhoudelijk issue, zie de laatste presentatie hier:
https://provincies.incijfers.be/databank?workspace_guid=d61b1582-2927-4cba-8db5-8362a3d334eb
Als je een dataset hebt waar Brussel NIET in zit, maar je denkt "dan gooi ik er Brussel toch uit", dan krijg je een wit vlak voor Brussel. Het verschil tussen "geen data" en "heel kleine aantallen" wordt hier wel heel klein.

Maar zelfs als je “expliciet lege” gebieden meeneemt, kan je nog altijd gemeenten er toch willen uitgooien. Check bijvoorbeeld de eerste presentatie : zoek de ene gemeente die niet op de kaart staat.

Enkele opties:
* Tweede kaart: vanzelfsprekende oplossing; zet toch overal de achtergrondkaart aan (en niet enkel subgemeentelijk)
   Twee nadelen: 
   -	omwille van de transparantie worden de kleuren nogal dof
   -	de kaart is een beetje raar als je heel Vlaanderen ziet; zonder grensgebieden maar mét Wallonië
* Derde kaart: ook met achtergrondkaart, maar minder transparant gezet.
   -	Kleuren duidelijk beter
   -	Maar de instelling hiervoor is voor ALLE kaarten; dus ook bij subgemeentelijke kaarten ga je de achtergrond niet goed zien
* Vierde kaart: “zonder de zesde kleur”, zoals Tine al had gesuggereerd. Toch een pak minder leesbaar IMHO (heel erg afhankelijk van het scherm waarop je kijkt trouwens)
* Vijfde kaart: de bleekste kleur wat grijzer gezet. Iets beter, maar toch ook minder leesbaar dan het origineel

Ik zie niet direct een goeie optie. Iemand anders wel?

**Comment by Tine-VB** [comment]
Is het standaard 6 klassen? Ik vind 5 klassen meestal wel genoeg, dus als we dat als standaard kunnen nemen, dan zou ik toch gaan voor de vierde kaart. Dan kunnen de kleuren nog wat uit elkaar gelegd worden, zodat de lichtste kleur nog donkerder kan. En anders zou ik voor de 5e kaart gaan, maar dan de lichtste kleur toch nog een ietsje donkerder zetten.

**Comment by joostschouppe** [comment]
Standaard is 5 klassen.
Hoe stel je voor de kleuren verder uit elkaar te leggen als de lichtste kleur nog minder licht wordt?

**Comment by joostschouppe** [comment]
Dat is een screenshot uit QGIS, Tine. De voorbeelden uit mijn comment van gisteren hebben allemaal vijf klassen, behalve dan die ene waar ik jouw voorstel uitprobeerde binnen Swing (de vierde kaart)

**Comment by Tine-VB** [comment]
> Dat is een screenshot uit QGIS, Tine. De voorbeelden uit mijn comment van gisteren hebben allemaal vijf klassen, behalve dan die ene waar ik jouw voorstel uitprobeerde binnen Swing (de vierde kaart)

Ha, dan liggen ze dus al verder uit elkaar dan op die QGIS-kaart natuurlijk.

**Comment by joostschouppe** [comment]
@StefanJacques : die grijze "geen waarde" is gearceerd, het is enkel in de legenda dat het op elkaar lijkt. Hoogst bizar ook dat hier een verschil met "ontbreekt" getoond wordt (ook gearceerd, maar donkerder) want alle Special Values bij Layout (viewer) staan hetzelfde ingesteld. Ik sein het in.

**Comment by Tine-VB** [comment]
Na enkele misverstanden over 5 en 6 klassen en dergelijke... ik ga ook voor optie 5, dus het minder wit zetten van de lichtste kleur. Eventueel iets minder grijs nog, al is de 'Geen waarde' nu dezelfde kleur bij mij als 'Ontbreekt'

**Comment by Lievendr** [comment]
wellicht een domme suggestie; maar waarom gebruiken we niet in de lijn van onze z-scores kaarten dat kleurenpalet? Toch veel duidelijker? en ligt in de lijn van onze "huisstijl"...
https://provincies.incijfers.be/databank?workspace_guid=a9d139ca-0beb-4588-b13b-d79cfcdda528

**Comment by Tine-VB** [comment]
Omdat we zeker een duidelijk zichtbaar onderscheid willen houden tussen een kaart met de 'gewone' waarden en eentje met de z-scores?

**Comment by Lievendr** [comment]
raar argument..
z-scores staat toch in de titel?

**Comment by joostschouppe** [comment]
Het was een zeer bewuste keuze van de redactiegroep om de divergerende kleurenschalen enkel te gebruiken in combinatie met z-scores.

**Comment by Tine-VB** [comment]
Moet het eigenlijk blauw zijn? Of mag het ook vies-bruin of vies-geel zijn? https://provincies.incijfers.be/databank?workspace_guid=d479372f-cc05-404f-b699-e2d0ff0c71ba

**Comment by joostschouppe** [comment]
Blauw past bij de huisstijl, vandaar

**Comment by joostschouppe** [comment]
Redactiegroep 10/11/2022: Filip doet een poging om een blauwer wit te maken

**Comment by demaesschalckfilip** [comment]
Bij deze een nieuwe poging: links de oude kleuren, rechts de nieuwe (Aalst is wit):
https://provincies.incijfers.be/databank?workspace_guid=b2d5b78c-27a8-45b7-98e1-2e97d7d82f5f

**Comment by joostschouppe** [comment]
Redactiegroep 19/01/2023: we nemen dit voorstel op

**Comment by VickyVB** [comment]
De coloribus disputandum est ... nog eens over het kleurenschema:
**het grijs (gemiddelde) van de z-score kaart ligt heel dicht bij het gearceerde (ontbreekt)**. 
In de kaart van het hoger onderwijs op vestigingsplaats is er in de meerderheid van de gemeenten geen hoger onderwijs. De reguliere z-score kaart ziet er dan zo uit: 
![image](https://user-images.githubusercontent.com/50832398/220854466-6dd137b0-1ce9-4a06-8c34-30a838097664.png)
Wanneer ik de gemiddelden roos kleur ipv grijs krijg je deze kaart:
![image](https://user-images.githubusercontent.com/50832398/220854729-3ddcc4c1-10dd-4365-8b7c-7f59e9ff116b.png)
Misschien de arcering wat wijder uit elkaar zetten?

**Comment by joostschouppe** [comment]
De standaardkleuren zijn aangepast
Voor het verzoekje van Vicky: ik heb net issue 118785 aangemaakt (zucht). Je kunt in Admin wel vanalles instellen qua layout van onbekende waarden, maar bij dit type kaart wordt dat gewoon volstrekt genegeerd door de Viewer. Dus momenteel kan ik er niks aan doen.

**Comment by joostschouppe** [comment]
De bug zou opgelost zijn in de nieuwe versie, maar zit nog steeds in de accept.
Alleszins is het wél zo dat je [hier ](https://provincies.incijfers.be/admin/studio/AdminProps?openItem=GroupSpecialValues) bij "Special values brush" de layout van ALLE onbekende types op de kaart kunt aanpassen. In de legende verschijnen meerdere inkleuringen, maar niet op de kaart. Ik heb het daar op "diagonal (backward)" gezet, en dat ziet er zo uit:
![afbeelding](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/10122639/ed1f2388-094c-4993-abe2-481964ceaa43)
![afbeelding](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/10122639/c77c6e0a-99f6-4c51-8947-0a22ba664209)

Dat lijkt me wel OK?

**Comment by joostschouppe** [comment]
Geen verdere opmerkingen meer gekregen
