### ISSUE TITLE
Taal moeder-kind

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#333]
In het kader van het rapport Opvang baby's en peuters #228 werd een indicator taal moeder-kind toegevoegd aan de themaboom. Oorspronkelijk werd een onderscheid gemaakt tussen Nederlands, Frans en anderstalig. Op vraag van Opgroeien werd dat uitgebreid naar: 
- Nederlands
- Frans
- Engels/Duits
- Russisch/Pools/Roemeens
- Spaans/Portugees
- Turks/Arabisch/Berbers
- andere taal

Metadatafiche werd aangepast en gecontroleerd door Tine.

Oké voor redactiegroep?

**Comment by StefanJacques** [comment]
akkoord

**Comment by Lievendr** [comment]
prima

**Comment by demaesschalckfilip** [comment]
prima

**Comment by joostschouppe** [comment]
Redactiegroep: in orde

**Comment by GeertBonte** [comment]
prima

**Comment by joostschouppe** [comment]
@veravandestraat: de verantwoordelijken zijn nog niet aangeduid voor de reeks 3604. Ik denk dat het OV_VB moet zijn, pas maar aan indien ik het fout heb
