### ISSUE TITLE
Afsluitende pagina rapporten met contactinformatie

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#335]
Na lezen van Rapport Opvang baby's en peuters gaf Zeneb de opmerking dat ze in de rapporten eigenlijk een afsluitende pagina mist om duidelijk te maken wie het rapport heeft opgemaakt, waarin de interprovinciale werking gekaderd wordt en bij wie een lezer terecht kan met eventuele vragen. Vooral in PDF-versie mist contactinformatie.

**Comment by StefanJacques** [comment]
Dat lijkt ons niet nodig, want in elk rapport staat op de eerste **(titel)pagina** de zin
‘Voorliggend rapport is een realisatie van de vijf Vlaamse Provincies. De [interprovinciale werking Data & Analyse](https://provincies.incijfers.be/databank?report=project_d_en_a&keepworkspace=true) stelde de inhoud samen en verzamelde de data.'

In die zin wordt verwezen naar de contactpagina van de vijf werkingen van Data & Analyse.

In de **leeswijzer** staat er vervolgens ook:
Provincies.incijfers.be is een product van de [interprovinciale werking Data & Analyse](https://provincies.incijfers.be/dashboard/over-provincies-incijfers-be). Zij helpen je graag verder bij vragen over het gebruik van de tool, maar ook bij bredere vragen rond het gebruik van omgevingsdata bij lokale besturen.

**Comment by joostschouppe** [comment]
Redactiegroep 10/11/2022: we vinden dit niet nodig
