### ISSUE TITLE
Check formule-onderwerpen met data

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#336]
Er zijn heel wat formule-onderwerpen die toch data bevatten. Dat kan af en toe de bedoeling zijn, maar het is wel altijd een beetje risicovol. Swing verkiest ingelezen data boven berekende data, dus als je een hele reeks jaren update, dan zal dat geen effect hebben op de periode dat er cijfers zijn ingelezen in de formule-onderwerpen. Af en toe gebeurt het per ongeluk, doordat we van een vroeger ingelezen onderwerp later een formule-onderwerp maken. Vandaar dus de vraag om deze lijst snel te checken:

https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Redactiegroep%20PinC/Kwaliteitscontrole/Controlebestanden/check%20formule%20and%20data.xlsx?d=wf80135ae22e04592943dba6e78c7d1c7&csf=1&web=1&e=KoqJWH

De opties om in te vullen in de gele kolom staan in het kolomhoofd. Als je in bulk data wil verwijderen, zet het dan gewoon op "te fixen", en dan kijken we eens hoe dat het gemakkelijkste lukt. Om zelf te fixen: vanuit de Indicator tabel in Swing kan je doorklikken naar "Data" (een van de eerste kolommen), waar je gemakkelijk ingelezen data kunt wissen.

**Comment by joostschouppe** [comment]
Redactiegroep 14/11/2022:
* dit wordt nagekeken per provincie

**Comment by veravandestraat** [comment]
probleem bij v3504_mt, v3504_rz, v3504_zv, v3504_zv_65_79, v3504_zv_65p, v3504_zv_80p: 
voor 2004 en 2007 zijn enkel de totalen ingelezen, dus die had ik laten staan, maar ik zie dat die hard ingelezen cijfers voor 2004 en 2007 niet verschijnen in PinC. 
2005 werkt wel en 2006 ontbreekt. Ik vraag me af of het niet beter is om vanaf 2008 te starten?

**Comment by joostschouppe** [comment]
Het ziet ernaar uit dat ABF de manier waarop met formule + ingelezen data heeft gewijzigd zonder overleg. Ik volg het op via melding 116367.

**Comment by joostschouppe** [comment]
Bijkomende vraag voor wie het al nakeek: wat betekent "geen probleem"? Als het inlezen van het cijfer geen nut heeft, dan kan je de data beter wissen. Als de data nodig is, dan moet ze blijven staan. Betekent "geen probleem" dat de data nuttig is?

**Comment by Emilien-Dupont** [comment]
De 'geen problemen' zijn opgehelderd

**Comment by joostschouppe** [comment]
@veravandestraat: heb je het issue van je post hierboven al opgelost? Indien nee, dan bespreken we het op de redactiegroep, indien ja, dan mag je dit ticket sluiten.

**Comment by veravandestraat** [comment]
Is opgelost
