### ISSUE TITLE
Plaats contactgegevens interprovinciale werkgroepen

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#339]
1. De interprovinciale werking Economie en de interprovinciale werking Detailhandel zijn (op het eerste zicht) de enige thematische werkgroepen waarvan de contactpagina in de themaboom staat:
![image](https://user-images.githubusercontent.com/61458346/200577043-be896bf0-3b0f-468b-b56f-916a85bf86b0.png)
![image](https://user-images.githubusercontent.com/61458346/200577119-9ae76a8b-2305-4a4c-b655-8e239401e30c.png)
Is dat wel wenselijk / nodig? Moeten we dat dan bij alle werkgroepen doen, of is het zo OK?

2. De contactpagina's van de interprovinciale thematische werkgroepen zijn niet zo makkelijk te bereiken, enkel via de verwijzing in rapporten en metadatafiches. Zou het een idee zijn om de url's naar de contactpagina's van deze werkgroepen op te nemen in een lijstje onder dit stukje, met als toegevoegde zin zoiets: "Heel wat rapporten en data op provincies.incijfers.be komen tot stand via de interprovinciale samenwerking van de inhoudelijke diensten van de provincies. Meer info en contactgegevens voor die projecten vind je hier:"
![image](https://user-images.githubusercontent.com/61458346/200577732-cd28ece5-9834-4ae7-bc21-c86ec05d3af5.png)
Of zien jullie nog andere mogelijkheden om deze contactpagina's makkelijker beschikbaar te maken?

**Comment by joostschouppe** [comment]
Redactiegroep 10/11/2022:
- Laten zoals het is: enkel toevoegen indien gewenst door themagroep
- Naam wijzigen: Contactpagina
