### ISSUE TITLE
aanmaak gecumuleerde energie- en renovatiepremies voor rapport Klimaat en energie

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#340]
ter kennisgeving en goedkeuring op de Redactiegroep van 15/12/22

voor de tekst in het rapport Klimaat en Energie hebben we gecumuleerde onderwerpen aangemaakt van de premies (naar analogie met bv. de reeks v2207_ energieverbruik nieuwbouwwoningen) omdat het vaak gaat over kleine aantallen op gemeentelijk niveau.

reeks v2502_premie_xxx_**t5** en vp2502_premie_xxx_**t5**

de onderwerpen hebben ook een plaats gekregen in de externe themaboom

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/12: Goedgekeurd
