### ISSUE TITLE
werkingsgebieden woonmaatschappijen toevoegen?

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#341]
Vraag om als gebiedsniveau toe te voegen kwam binnen via @Tine-VB 
Het is gebiedsdekkend. Info via
https://www.vmsw.be/Home/Ik-ben-professioneel/Woonmaatschappijen/Werkingsgebieden

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/12:
- W-Vl: Vraag Limburg als 1 werkingsgebied: woonmaatschappijen gaan hier samensmelten vanaf 01/01/2023.
Goedgekeurd.

**Comment by joostschouppe** [comment]
Wordt opgevolgd via https://github.com/provinciesincijfers/gebiedsniveaus/issues/48
