### ISSUE TITLE
IGS'en toevoegen als half gebiedsniveau

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#342]
Vraag kwam binnen via @Tine-VB 
Niet gebiedsdekkend; kan dus enkel in logica zoals streken en klimaat-intercommunales.
~~Mogelijk op dit kaartje te baseren? https://www.vlaanderen.be/cjm/nl/cultuur/bovenlokale-cultuur/subsidies/werkingssubsidie-voor-intergemeentelijke-samenwerkingsverbanden~~
* Meer info: https://www.vlaanderen.be/lokaal-woonbeleid/subsidies-voor-intergemeentelijke-samenwerkingsprojecten-lokaal-woonbeleid/subsidies-voor-intergemeentelijke-samenwerkingsprojecten-2020-2025
* Tabel met gemeenten op eerste tabblad van https://assets.vlaanderen.be/raw/upload/v1663059617/Overzicht_gesubsidieerde_aanvullende_activiteiten_en_eigen_voorstellen_2020-2025_qlqysl.xlsx

**Comment by StefanJacques** [comment]
akkoord

**Comment by Lievendr** [comment]
in Antwerpen zouden die wel gebiedsdekkend zijn. wij zijn dus zeker voor :-)

**Comment by Lievendr** [comment]
https://www.vlaanderen.be/lokaal-woonbeleid/subsidies-voor-intergemeentelijke-samenwerkingsprojecten-lokaal-woonbeleid/subsidies-voor-intergemeentelijke-samenwerkingsprojecten-2020-2025

**Comment by Tine-VB** [comment]
> https://www.vlaanderen.be/lokaal-woonbeleid/subsidies-voor-intergemeentelijke-samenwerkingsprojecten-lokaal-woonbeleid/subsidies-voor-intergemeentelijke-samenwerkingsprojecten-2020-2025

Inderdaad, die van Joost zijn de IGS-sen van cultuur :-) Daar hebben we voorlopig nog geen vraag naar gekregen...

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/12
- Opnemen zoals streekplatformen en klimaatintercommunales

**Comment by joostschouppe** [comment]
Aangemaakt door @davidcardinaels , klaargezet in themaboom bij "Gebiedsindelingen" en opgenomen in het logboek.
