### ISSUE TITLE
Toekomstige data wishlist voor mobiliteit

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#344]
In de loop van 2022 werden verschillende nieuwe datasets toegevoegd aan PinC. Hier nog wishlist voor gegevens voorjaar 2023:

-Knooppuntwaarde & voorzieningen (Joost): bijna klaar voor publicatie
- Aantal motors in omloop van Statbel: https://statbel.fgov.be/nl/themas/mobiliteit/verkeer/inschrijving-motorvoertuigen#figures. Net als speed pedelecs en wagens naar brandstof op inschrijvingsplaats ipv op adres eigenaar
- Aantal inwoners binnen aanvaardbare afstand van oprit FSW: analyse bezig door Joost
- Aantal km FSW zit erin. Eventueel ook aantal km busroute? (via open webmap VLBR). Of aantal bushaltes per statsec (ook via open webmap VLBR), naar analogie van laadpalendata? Geeft natuurlijk geen inzicht over hoe vaak er bussen passeren, maar kan nuttige proxy zijn...
- Piste NMBS data: ik nam contact op met bedrijf dat druktebarometer bouwde: deze blijkt gebaseerd te zijn op de input van de conducteur over hoe druk het is in het verleden, dat gecombineerd met het type trein, welk traject enzoverder... Zij hebben ook nooit data gekregen rond tickets geboekt via mobile app, of aan het station of abonnementen. Die data zouden er op zich wel moeten zijn, maar zijn zelfs voor internal purposes nog niet beschikbaar.
- Piste aantal gereden km wagens: Carpass, GOCA en MOW zijn uitgesloten als piste. Nog navragen bij mobil werkgroep of ze nog andere leads hebben. Alle ideeën hierover welkom.
- Enquête FOD mobiliteit: zou toch wel handig zijn als we daar ook 'extern' van gebruik mogen maken. Nog eens navragen of dat intussen nog niet mag. @joostschouppe zou jij hier eventueel je contactpersoon nog eens over willen aanspreken? Ik dacht dat je dat onlangs nog wel eens had gedaan... Maar mss zijn ze nu ikv ontwikkelingen mbt 'open data' toch al wat flexibeler?
- De lang gevreesde piste om proximus / telenet eens aan te spreken. Ze blijken wel een hele service te hebben rond het beschikbaar stellen van locatie- en mobil data. Maar dat gaat sowieso geld kosten, dus misschien beter te bekijken ikv een gebundelde aanvraag...: https://www.proximus.be/en/id_cl_analytics/companies-and-public-sector/it-services/iot/proximus-analytics.html
- Wie nog meer ideeën of mobil-wensen heeft: deze zijn zeker welkom, hoe haalbaarder hoe liever!

**Comment by JoLocquet** [comment]
Voor deelmobiliteit ga ik na wat er kan via j[aarrapport autodelen]([https://www.autodelen.net/wp-content/uploads/2022/01/Jaarrapport-autodelen-2021_gepubliceerd-op-20-januari-2022.pdf](https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.autodelen.net%2Fwp-content%2Fuploads%2F2022%2F01%2FJaarrapport-autodelen-2021_gepubliceerd-op-20-januari-2022.pdf&data=05%7C01%7Channe.opdebeeck%40vlaamsbrabant.be%7C4f06223d74c0463c551808dad4680ba2%7Cabeeed50ea7b4008b0e5d27f624bf85e%7C0%7C0%7C638055841436845054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N%2FlzuDFUY%2BjojtM6oXQL5jZD%2BCy2LKTNH9ql6wQFpzg%3D&reserved=0))

**Comment by JoLocquet** [comment]
Voorstel om aantal elektrische laadpunten op te nemen in PinC. Dit is een streefcijfer per gemeente. Deze tabel is beschikbaar via: https://www.vvsg.be/kennisitem/vvsg/e-mobiliteit. 

"De Vlaamse overheid stelde een studiebureau aan om de centrumsteden te begeleiden bij het opstellen van hun potentieel kaarten. Voor de andere steden en gemeenten werd een behoefteanalyse opgemaakt, die resulteerde in een streefcijfer per gemeente om zo met alle gemeenten samen te komen tot de doelstelling van 35.000 laadpunten tegen 2025. De behoefteanalyse gebeurde op basis van verschillende relevante parameters, zoals aantal inwoners, aantal voertuigen, bevolkingsdichtheid, bebouwing, inkomen."

[streefcijfer laadpunten.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/10234671/streefcijfer.laadpunten.xlsx)

**Comment by Emilien-Dupont** [comment]
Beslissing Redactiegroep 15/12
- Aantal deelwagens: 60 à 70% van de gemeenten heeft geen deelwagens + slechts 1 momentopname beschikbaar (opname oktober 2022). We wachten tot we meer jaargangen hebben om betrouwbaarheid na te gaan.
- Elektrische laadpunten: beleidsinformatie. Kan, maar moet op zijn minst gecombineerd worden met het aantal effectieve laadpunten (ook te bespreken op IPWG.) Zou ook eerder vallen onder thema 'Klimaat'. 

Ter info:
Mogelijke nieuwe datareeksen dienen eerst op de Redactiegroep te passeren waar de leden al dan niet hun goedkeuring kunnen geven. Pas daarna worden de mogelijkheden verder ondergezocht. Zie [documentatie](https://github.com/provinciesincijfers/JiveDocumentation/tree/master/01.%20Algemeen%20databeheer)

**Comment by HanneODB-VLBR** [comment]
Graag zou ik de opname van de volgende cijferreeksen onder het thema 'mobiliteit' op PinC willen voorleggen ter goedkeuring aan de redactiegroep:

1) Aantal bedrijfswagens per statistische sector. Statbel beschikt over deze cijfers maar publiceert ze niet (ze worden enkel  gebruikt voor de correctie van de cijfers over wagenbezit bij huishoudens), dus deze moeten worden opgevraagd. Statbel genereert deze aantallen op basis van de jaarlijkse bestanden van de fiscale gegevens (Belcotax).

2) Aantal motors in omloop per gemeente. Deze kunnen gewoon worden afgeladen van de Statbel website: https://statbel.fgov.be/nl/themas/mobiliteit/verkeer/inschrijving-motorvoertuigen#figures. Net als speed pedelecs en wagens naar brandstof staan deze geregistreerd op inschrijvingsplaats ipv op adres eigenaar. Over 'motorbezit' hebben we reeds enquêtedata op PinC gepubliceerd (obv de GSM), maar nog geen registratiedata.

3) Aantal km busroute, naar analogie met aantal kilometer fietssnelweg op PinC.  De busroutes kunnen voor alle provincies worden bekomen via de open webmap van provincie VLBR en, volgens dezelfde methode als bij de fietssnelwegen werd gebruikt, worden doorgedrukt op de kaart van de gemeenten (of op de kaart van de statistische sectoren, als dat relevanter zou zijn). De data geven een basisidee van de mate waarin gebieden 'gecovered' worden door busvervoer. Het is misschien niet de allerbeste indicator, maar kan gebruikt worden bij het algemeen in kaart brengen van het bereik van openbaar vervoer en De Lijn heeft verder amper bruikbare data ter beschikking.

Ingeval van goedkeuring mag meteen ook een controleur worden aangeduid :-)

**Comment by joostschouppe** [comment]
Redactiegroep 19/1/2023: in orde

**Comment by HanneODB-VLBR** [comment]
_Enquête FOD mobiliteit: zou toch wel handig zijn als we daar ook 'extern' van gebruik mogen maken. Nog eens navragen of dat intussen nog niet mag. @joostschouppe zou jij hier eventueel je contactpersoon nog eens over willen aanspreken? Ik dacht dat je dat onlangs nog wel eens had gedaan... Maar mss zijn ze nu ikv ontwikkelingen mbt 'open data' toch al wat flexibeler?_
=> Net nog eens naar Peter Andries gebeld om te vragen hoe het hiermee staat: 

- Hun juridische dienst is bezig met aanpassingen aan de wetgeving maar hij verwacht daar geen doorbraak de eerstkomende maanden
- Hij zal ons wel nog de file met de data van de meest recente afname bezorgen. Die mogen we intern zetten. Lokale besturen en andere stakeholders mogen er gebruik van maken voor hun interne analyses, zolang ze deze niet publiceren
- We mogen de lokale besturen wel proactief laten weten dat we die data intern hebben staan en dat ze ze mogen opvragen
- Peter zou ons iets laten weten als er meer zicht is op die wetswijziging, we spraken af dat ik hem in het najaar sowieso opnieuw zal bellen als we tegen dan nog niets van hem hebben gehoord.

**Comment by HanneODB-VLBR** [comment]
Update data bedrijfswagens: aanvraag werd gedaan bij statbel, maar datakwaliteit moet eerst nog gecheckt worden bij een expertengroep én daarna wil Statbel de data eerst zelf publiceren omdat ze er zelf strategisch mee willen 'uitpakken'. Maar daarna krijgen wij ze ook. Zou normaal gezien wel voor dit jaar zijn, maar buiten dat is het nog niet concreet wanneer precies.

**Comment by HanneODB-VLBR** [comment]
Statbel heeft XY data vrijgegeven van verkeersongevallen met per ongeval categorisering op verschillende dimensies (jaargangen 2017 - 2022). De ruwe data bevinden zich hier: [https://statbel.fgov.be/nl/open-data/geolocalisatie-van-de-verkeersongevallen-2017-2022](https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstatbel.fgov.be%2Fnl%2Fopen-data%2Fgeolocalisatie-van-de-verkeersongevallen-2017-2022&data=05%7C01%7Channe.opdebeeck%40vlaamsbrabant.be%7C6b7a2117c7114181c2a208db98d6010f%7Cabeeed50ea7b4008b0e5d27f624bf85e%7C0%7C0%7C638271817155631299%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6GL6dM5kXqQ%2F%2BYT%2BK%2BWMUsnpxgMgjN75WNQPE%2Fn14qw%3D&reserved=0)

Mijn voorstel is om deze coördinaten door te drukken op een kaart van de statistische sectoren, om zo een kubus van het aantal verkeersongevallen op statsecniveau te bekomen met de volgende dimensies:
-Weersomstandigheden
-Conditie wegdek
-Zichtbaarheid
-Wegtype
-Type verwondingen
-Type betrokken voertuig
-Locatie (combinatie van 'bebouwde kom'/'kruispunt')

Op basis van deze kubus kunnen dan een aantal 'platte' formule-onderwerpen worden afgeleid.

Deze indicatoren zouden de huidige indicatoren ivm verkeersveiligheid vervangen, omdat ze overlappen maar meer uitgebreid en fijnmaziger zijn (i.c. huidige indicatoren zijn op gemeenteniveau en gaan enkel over type verwondingen en type betrokken voertuig). De oude indicatoren kunnen eventueel wel op intern blijven staan m.o.o het rapport verkeersveiligheid (of, dat kan eventueel op termijn ook worden herwerkt...).

Graag leg ik dit voorstel ter goedkeuring voor op de eerstvolgende redactiegroep.

**Comment by HanneODB-VLBR** [comment]
Daarbij aansluitend zouden we ook het kaartje met ongevalslocaties, zoals voorzien door Statbel, willen embedden in het mobiliteitsrapport (cf. kaartje met routes van Anyways). Het gaat om het volgende kaartje: https://statbel.fgov.be/nl/themas/mobiliteit/verkeer/verkeersongevallen#panel-15

**Comment by valeriepirard** [comment]
ok, ziet er goed uit. Zou wel handiger zijn moest de gekozen gemeente in het rapport zelf openen in het kaartje.

**Comment by HanneODB-VLBR** [comment]
> ok, ziet er goed uit. Zou wel handiger zijn moest de gekozen gemeente in het rapport zelf openen in het kaartje.

Inderdaad... In de alpha versie ga ik dat normaal gezien wel kunnen realiseren denk ik, daar heb ik ook al het voorbeeldje van de Anyways kaart die opent in de gekozen gemeente.

**Comment by Emilien-Dupont** [comment]
RG 19/09:
Statbel xy data: oke om op te nemen. Lieven bekijkt met Hanne wie dit op zich neemt. Valerie als controleur?
Kaartje embedden: akkoord.

**Comment by emdockx** [comment]
Ter info: de provincie Antwerpen heeft ook een dashboard verkeersongevallen:

https://provincieantwerpen.maps.arcgis.com/apps/dashboards/98e5f6f12fae45a6b9bd6ad5a651e06b

https://www.provincieantwerpen.be/lokale-besturen/gemeenten-in-beweging/begeleiding/verkeersveiligheid/aanbod-verkeersveiligheid/dashboard-verkeersongevallen.html

**Comment by HanneODB-VLBR** [comment]
> > Daarbij aansluitend zouden we ook het kaartje met ongevalslocaties, zoals voorzien door Statbel, willen embedden in het mobiliteitsrapport (cf. kaartje met routes van Anyways). Het gaat om het volgende kaartje: https://statbel.fgov.be/nl/themas/mobiliteit/verkeer/verkeersongevallen#panel-15
> 
> Ik heb het kaartje intussen al eens toegevoegd aan het rapport in de Beta, daar kan je zien hoe het eruit ziet (wel in een oude versie van het rapport want de meest recente staat niet op de Beta, maar het gaat uiteindelijk om het kaartje). Je kan het zien door vanuit de Beta admin de test versie te lanceren en dan te kijken onder Admin > Hanne > Mobiliteit > Rapport mobiliteit 2022 edited. Wel best pas vanaf morgen (31/8) te proberen want de Beta is precies heel traag in zijn aanpassingen... Het enige wat ik persoonlijk wat 'ambetant' is, is dat je eerst de pop-up met algemene informatie moet wegklikken, maar vanuit het standpunt van Statbel wel te begrijpen want zo dwingen ze de gebruiker wel naar hun metadata te kijken.
> 
> Ik heb van Statbel ook een iframe link gekregen om hun heatmap te embedden (https://experience.arcgis.com/experience/8941c83bd7cd4ee48553252213d2a8e9) maar die vind ik persoonlijk minder relevant omdat ze standaard meerdere jaartallen omvat en in 'looks' gelijkaardig is aan onze eigen choropleth kaartjes...

**Hulp gevraagd...!** @Emilien-Dupont @GeertBonte of andere rapporten 'whizzkids'... Ik krijg het Iframe van Statbel toch niet tegoei... Er staat momenteel een pop-up op het kaartje die je moet wegklikken -wat sowieso al vervelend is - maar daardoor word je bij het openen van het rapport automatisch meteen naar dat kaartje gestuurd ipv op de startpagina te blijven. Weten jullie misschien hoe ik dat kan oplossen? Ook: ik heb dezelfde code gebruikt als bij het Anyways-iframe, maar toch blijft het kaartje zich, in tegenstelling tot het Anyways-kaartje, openen voor heel België ipv de geselecteerde regio. Als iemand kan vinden hoe dat kan worden gefixed.... indien niet dan vrees ik dat we het iframe gaan moeten wegnemen en enkel nog verwijzen naar het kaartje op de website van Statbel zelf... Merci alvast!

Rapportcode: rapport_mobiliteit
Kaartje statbel: Locaties letselongevallen
Kaartje Anyways: Simulatie pendelroutes per vervoersmiddel volgens de Anyways Mobility data explorer

**Comment by GeertBonte** [comment]
> **Hulp gevraagd...!** @Emilien-Dupont @GeertBonte of andere rapporten 'whizzkids'... Ik krijg het Iframe van Statbel toch niet tegoei... Er staat momenteel een pop-up op het kaartje die je moet wegklikken -wat sowieso al vervelend is - maar daardoor word je bij het openen van het rapport automatisch meteen naar dat kaartje gestuurd ipv op de startpagina te blijven. Weten jullie misschien hoe ik dat kan oplossen? Ook: ik heb dezelfde code gebruikt als bij het Anyways-iframe, maar toch blijft het kaartje zich, in tegenstelling tot het Anyways-kaartje, openen voor heel België ipv de geselecteerde regio. Als iemand kan vinden hoe dat kan worden gefixed.... indien niet dan vrees ik dat we het iframe gaan moeten wegnemen en enkel nog verwijzen naar het kaartje op de website van Statbel zelf... Merci alvast!
> 
> Rapportcode: rapport_mobiliteit
> Kaartje statbel: Locaties letselongevallen
> Kaartje Anyways: Simulatie pendelroutes per vervoersmiddel volgens de Anyways Mobility data explorer

Ik heb er eens naar gekeken, maar ik vrees dat er weinig aan te doen valt. Bij de Statbel-kaart krijg je altijd de pop-up en word je automatisch naar die plaats in het document gestuurd, en daar kunnen we niets aan veranderen. Op die manier lukt het overigens ook niet om het rapport te downloaden als PDF. Ik denk daarom dat het beter is om het iframe weg te laten en te vervangen door een link naar de website van Statbel.

De reden waarom je gans België te zien krijgt is volgens mij deze: de Statbel-kaart en de Anyways-kaart zijn verschillende toepassingen, die op een verschillende manier werken. De Anyways-kaart zoomt in op de geografische coördinaten die je meegeeft in de URL, de Statbel-kaart doet dat jammer genoeg niet, en ik denk ook niet dat je daar iets aan kunt doen.

Bv. bij de Anyways-kaart: https://www.anyways.eu/map/?view=trips#8.13/51.046/3.954
Hierin is 8.13 de zoom-factor (als je dat getal aanpast, wordt er meer of minder ingezoomd), is 51.0461 de oosterlengte en is 3.954 de noorderbreedte.

Bij de Statbel-kaart: https://experience.arcgis.com/experience/bee9481fcc8b4c7eb78c278b10f1add9#8.13/51.046/3.954
Deze toepassing negeert alles wat na # staat: als het er nu staat of niet, dat verandert niets aan de kaart: je krijgt altijd een kaart van België te zien.
Misschien is er een andere manier om zoomfactor en coördinaten op te geven, maar zonder documentatie kunnen we dat moeilijk achterhalen.

**Comment by HanneODB-VLBR** [comment]
Dan zit er inderdaad niet veel anders op dan de iframe te verwijderen en enkel te linken naar de webpagina van Statbel zelf... Bedankt om het te bekijken, @GeertBonte , en voor je input!

**Comment by HanneODB-VLBR** [comment]
Er is een probleem met de update van de data over de fietssnelwegen. Vorig jaar werd, in samenspraak met de coördinator interprovinciale fietsdata (Hanne Van Dyck) een dataset uitgewerkt waarmee we per fietssnelweg en per gemeente een aantal kenmerken van de fietssnelwegen in kaart brengen (befietsbaarheid, autoluw karakter, verlichting, bewegwijzering). Sinds Hanne Van Dyck vertrokken is, werd er een nieuwe coördinator aangesteld: Camille De Herdt. Toen ik haar contacteerde voor de kwaliteitscontrole voor de update van deze data van dit jaar, stelde Camille dat er toch een probleem is met deze data en dan vooral de criteria 'autoluw karakter' en 'verlichting': de provinciale coördinatoren die dit registreren hanteren hiervoor geen gemeenschappelijke definitie. Hanne Van Dyck had hier destijds ook wel over gesproken, waardoor we registratieverschillen als beperking hebben opgenomen in de infofiche, maar zij had dit niet zo sterk geproblematiseerd als Camille. Ik heb aan Camille gevraagd om (1) nog eens bij de provinciale coördinatoren te polsen hoe groot de verschillen volgens hen zijn: volstaat het om hier bv. in voetnoot op te wijzen, of is het beter dat we gewoon volledig afzien van de publicatie van deze data (en dus ook de data van 2022 eraf halen, want die is op dezelfde registratie gebaseerd) en (2) aan te dringen op het uitwerken van een gemeenschappelijke definitie voor deze kenmerken, zodat we vanaf 2024 een nieuwe doorstart kunnen maken. Omdat ik hierover niets meer van Camille heb gehoord, stuurde ik haar het nog eens een berichtje met vraag voor een stavaza... en ontving een out of office waarin staat dat ze langdurig afwezig is. De vraag is dus wat hiermee nu te doen. Alles voor de zekerheid van PinC halen tot we meer duidelijkheid hebben (maar, kan allicht lang duren)? Of de dataset toch publiceren mits vermelding in voetnoot + infofiche aangaande de beperkingen? Graag advies van redactiegroep.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
Iedereen polst binnen de GIS-cel van de eigen provincie naar de kwaliteit van de data en koppelen dan terug. 
2022 laten we er voorlopig nog opstaan.

**Comment by HanneODB-VLBR** [comment]
OK, bedankt. Ik heb alvast de coördinator voor Vlaams_Brabant gecontacteerd.

**Comment by HanneODB-VLBR** [comment]
> Redactiegroep 17/10: Iedereen polst binnen de GIS-cel van de eigen provincie naar de kwaliteit en foutenmarge van de data en koppelt dan terug in de volgende Redactie. 2022 laten we er voorlopig nog opstaan.

Ik vind het moeilijk om vanuit VLBR op te volgen in welke mate dit gebeurd is. Kan elke provincie hier aub aanvinken indien de vraag gesteld werd aan de verantwoordelijke? Dank!

- [ ] Vlaams-Brabant
- [ ] Antwerpen
- [ ] Limburg
- [ ] Oost-Vlaanderen
- [ ] West-Vlaanderen

**Comment by JoLocquet** [comment]
@HanneODB-VLBR op 09/11 heb ik overleg met Claudia de Pus (GIS - mobiliteit - OVL) om te bekijken wat de kwaliteit is van de FSW data op PinC.

**Comment by HanneODB-VLBR** [comment]
Op vraag van een lokaal bestuur (via Emilien) vroegen we bij de Lijn data op over toegankelijkheid van haltes openbaar vervoer. Deze week ontving ik op deelgemeenteniveau voor heel Vlaanderen de cijfers over (1) aantal haltes toegankelijk voor mensen met een motorische beperking, (2) aantal haltes toegankelijk voor mensen met een motorische beperking mits assistentie en (3) aantal haltes toegankelijk voor mensen met een visuele beperking. Graag akkoord van de redactiegroep voor opname van deze indicatoren in PinC onder het thema 'mobiliteit' (totaal aantal haltes werd ook meegegeven, dus percentages kunnen ook worden berekend) + aanduiden controleur.

**Comment by emdockx** [comment]
> aanduiden controleur

Ik wil wel kandidaat zijn om controleur te zijn.

**Comment by JoLocquet** [comment]
@HanneODB-VLBR Hieronder mijn feedback na overleg met Claudia De Pus - OVL - kwaliteit data FSW op PinC:
- Voor de dimensie befietsbaar en bewegwijzerd is er een kwaliteitswaardborg
- Voor autoluw is er nood aan uniforme definitie en kan een script daarna ontwikkeld worden. De kwaliteit van de gegevens voor deze dimensie kan snel  aangepakt worden. 
- Op dit ogenblik is er geen plan van aanpak voor de dimensie verlichting en lijkt het ons best om de publicatie ervan op PinC onhold te plaatsen.

**Comment by GeertBonte** [comment]
Hieronder het antwoord van Elise Vanden Broucke (verantwoordelijke West-Vlaanderen):

> Dit staat nog niet (helemaal) op punt, net zoals bij de andere provincies.
> Deze week gaan we interprovinciaal  overleg hebben hierover opdat we dit zo willen gepubliceerd zien.
> Ik hou je op de hoogte.

**Comment by HanneODB-VLBR** [comment]
Bedankt om het na te gaan, collega's. Voorlopig lijkt er dus alvast niemand te zijn die van mening is dat het offline moet gaan, maar mogelijks zijn er wel enkele aanpassingen maken inzake metadatafiche/te verbergen dimensies. Ik heb intussen ook begrepen dat zij morgen nog onderling overleg plegen hierover, dus ik zal nog afwachten wat daaruit komt en dan de knoop doorhakken.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 23/11:
we wachten het overleg af. Oke dat Emmanuel controleur is.

**Comment by HanneODB-VLBR** [comment]
Ik heb het overleg van de interprovinciale fietsstuurgroep vandaag zelf bijgewoond. De interprovinciale coördinator is gestopt met haar job. Vanaf januari zal er een nieuwe coördinator starten met een contract voor één jaar. Samen met deze coördinator wordt een werkgroep opgestart waarin beoogd wordt duidelijke afspraken te maken waardoor alle kenmerken van de fietssnelwegen op gelijkaardige wijze worden ingevuld. Wanneer dit op punt staat zal ik een 2024 versie maken van de data, dat als startpunt zal dienen voor een nieuwe tijdsreeks. Tot het zover is, mogen de data van 2022 wel blijven staan, maar die van 2023 ga ik niet publiceren. Dit thema staat dus voorlopig on hold.

**Comment by HanneODB-VLBR** [comment]
We ontvingen toestemming van de FOD Mobiliteit om een deel van de cijfers van de woon-werkenquête op gemeenteniveau extern te zetten. Gaat de redactiegroep hiermee akkoord?

**Comment by Emilien-Dupont** [comment]
Ja, oké om extern te plaatsen.
