### ISSUE TITLE
Hervorming ELZ 

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#345]
Context:
* alle ELZ behalve de vier bij stad Antwerpen kunnen gebouwd op basis van gemeente
* destijds hebben we ervoor gekozen om die te bundelen

Vraag vanuit ELZ's regio Antwerpen om hun regio toch uit te splitsen.
* In eerste instantie bij IMA neergelegd, maar wij mee uitgenodigd
* Vereist dat we ze kunnen bouwen op basis van statsec
* Lijst is aan ons bezorgd door Jerry Ruys
* Die lijst gaat nu gevalideerd worden door de ELZ-werking zelf

Technisch
* normaal gezien is het mogelijk om een gebiedsniveau te maken dat deels uit statsec gevoed wordt en deels uit gemeente. Maar we hebben geen weet van praktijkvoorbeelden
* probleem "gebied onbekend" van gesplitste gemeenten (in casu enkel Stad Antwerpen?). Handigste als je die niet geheel kwijt geraakt en course de route. Voor ons een optie om het eenvoudig toe te kennen aan de grootste ELZ. Anders kunnen er zaken mis gaan bij totalisering. Dit is vooral voor IMA mogelijk een issue, omdat zij geen "gebied onbekend" op gemeenteniveau hebben

Minimum oplossing PinC
* Deze extern zetten: https://provincies.incijfers.be/databank?report=elz_startproject
* Wel mits validatie en een korte handleiding om te totaliseren

Volledige oplossing PinC
* Gebiedsniveau ELZ zelf aanpassen
* Betekent dus ook dat het rapport lege stukken zou hebben in het Antwerpse
* wellicht kan alles van IMA binnenkort op statsec, dus Rapport ELZ wordt dan wel iets beter. Ongeveer de helft is onoplosbaar. Input vanuit ELZ-werking: liever een half rapport dan geen rapport

**Comment by joostschouppe** [comment]
Redactiegroep 20/4/2023
* OK om dit zo uit te voeren

**Comment by GeertBonte** [comment]
Het rapport ELZ is ondertussen aangepast. De gebiedsselectie is uitgebreid met het nieuwe gebiedsniveau "eerstelijnszone (omgeving Antwerpen), en het rapport wordt nu ook getoond voor de eerstelijnszones die uit één gemeente bestaan (Brugge, Gent en Leuven). Vroeger werd voor deze zones doorverwezen naar het rapport kerncijfers buurtgerichte zorg; nu wordt hetzelfde principe toegepast als voor de Antwerpse eerstelijnszones en wordt de zone uitgesplitst naar wijken.
