### ISSUE TITLE
LPZ 

### ISSUE THREAD

**Issue by JoLocquet** [provinciesincijfers/PinC-taakopvolging#348]
De samenstelling en de benaming van de LPZ is onderhevig aan verandering. In OVL zijn er verschillende gemeenten die de stap zetten naar structurele samenwerking en smelten samen. Dit is onder meer het geval bij Aalter en Knesselare. De benaming van de Lokale Politie Zone is in PinC Aalter - Knesselare. Ik heb dit aangepast

https://provincies.incijfers.be/admin/studio/Table/DetailGrid?TableName=GeoItem&ParentKey=GeoLevelCode&ParentCode=20&ParentTable=GeoLevel

De tabel op GitHub heb ik (nog) niet aangepast (Uploads are disabled)

https://github.com/provinciesincijfers/gebiedsniveaus/blob/master/data_voor_swing/gebiedsdefinities/politiezone.xlsx

**Comment by Emilien-Dupont** [comment]
aangepast
