### ISSUE TITLE
Documenteren in sjabloon_toplijstkaart

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#35]
Code die gebruikt wordt in rapport onderwijs in een sjabloon zetten. Type: toplijst maken en daar dan een kaartje van maken. Opmerking: toplijsten maken kan sinds de release van 1/7 volautomatisch. Zie hiervoor de release notes. Verwerk dit mee in het sjabloon.

**Comment by joostschouppe** [comment]
Ter inspiratie: https://provincies.incijfers.be/admin/jive/Report/Edit/sjabloon_top10
Voor deze zou ik ook een extra rapportje maken, vb sjabloon_top10kaart

**Comment by davidcardinaels** [comment]
Toegevoegd aan sjabloon + apart sjabloon.
