### ISSUE TITLE
Analyse: is het opportuun en mogelijk om officiële bevolking ipv rijksregister te gebruiken als noemer

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#357]
- maakt het werkelijk verschil?
- kunnen we overal zomaar over de juiste noemer beschikken?
- is het inhoudelijk even goed?

**Comment by demaesschalckfilip** [comment]
-De verschillen zijn meestal klein; op het niveau van statistische sectoren kunnen ze soms groter zijn.
-De rijksregisterdata laten ons toe bepaalde leeftijdsgroepen, herkomstgroepen... te gebruiken. Die hebben we niet ter beschikking van Statbel. Enig nadeel is de afwezigheid van Brussel, maar dat zou moeten opgelost worden in de toekomst. 
-Inhoudelijk zijn onze cijfers realistischer. Zo doet Statbel alsof asielzoekers er niet zijn, maar in het echt zijn die er wel.

**Comment by joostschouppe** [comment]
- Wat met cijfers waar de teller op statsec niveau is > we zouden al twee verschillende types moeten gebruiken binnen de toepassing
- Recentheid van de data bij huishoudens op statsec
- Enkel Brussel pleit in voordeel van statbel, maar dat wordt normaal gezien opgelost
