### ISSUE TITLE
Nakijken ongebruikte dimensies & dimensieniveaus

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#358]
Toevallig had ik het ConsistencyReport _Dimensions used by indicators_ nodig. Daarbij viel me op dat er nogal wat dimensies en dimensieniveaus niet in gebruik zijn. Omwille van de overzichtelijkheid werken we die best weg. Ik heb at random enkele cases nagekeken, en deze leken effectief allemaal niet in gebruik te zijn (ook niet via een aggregatie ofzo). Kijken jullie eens na of hier dingen tussen zitten die wel degelijk nog in gebruik zijn, of die jullie binnenkort in gebruik gaan stellen?

Ik stel voor dat deadline voor feedback één week na de volgende redactiegroep is (dus 23/2). Behoudens tegenbericht zullen we ze daarna eenvoudig deleten.

Dimension name | Dimension code | Dimlevel name | Dimlevel code
-- | -- | -- | --
None | None | sep_detail | sep_detail
Uitgaande pendel | pendeluit | pendeluit | pendeluit
burgerlijke_staat_adsei | burgerlijke_staat_adsei | burgerlijke_staat_adsei | burgerlijke_staat_adsei
leeftijd_cat_adsei | leeftijd_cat_adsei | UITDOVEND - leeftijd_cat_adsei | leeftijd_cat_adsei
Socio-economische positie (KSZ) | socio_economische_positie_ksz | socio-economische positie (indeling KSZ) | socio_economische_positie_ksz
Sectorindeling | v1403_nace_indelingen | landbouw/industrie/handel+diensten | v1403_nace3
Nationaliteit | nationaliteit | landcode Statistics Belgium | nationaliteit_landcode
Nationaliteit | nationaliteit | nationaliteit (detail) | nationaliteit_detail
Geboortenationaliteit | geboortenationaliteit | geboortenationaliteit landcode | geboorte_nationaliteit_landcode
Herkomstnationaliteit | herkomstnationaliteit | herkomstnationaliteit landcode | herkomst_nationaliteit_landcode
Inkomende pendel | pendelin | pendelin | pendelin
Type | v1403_wkn_zn | zelfstandigen detail | v1403_hoed_aard
Type | v1403_wkn_zn | zelfstandigen basisindeling | v1403_hoed_aard_simp
Type | v1403_wkn_zn | werknemers | v1403_wkn
Hoofdsector | v1200_hoofdsector | hoofdsector | v1200_hoofdsector
Statuut | v1200_statuut | statuut | v1200_statuut
Nationaliteit | detailnationaliteit | individuele huidige nationaliteiten | detailnationaliteit_detail
Herkomstnationaliteit | detailhnationaliteit | individuele herkomstnationaliteiten | detailhnationaliteit_detail
Geboortenationaliteit | detailgnationaliteit | individuele geboortenationaliteiten | detailgnationaliteit_detail
Huidige nationaliteit | nationaliteiten2 | nationaliteiten (detail) | nationaliteiten2_detail
Huidige nationaliteit | nationaliteiten2 | nationaliteit (14 landengroepen) | nationaliteiten2_14_groepen
Nationaliteit | nationaliteit | landcode Statistics Belgium | nationaliteit_landcode
Nationaliteit | nationaliteit | nationaliteit (detail) | nationaliteit_detail
Geboortenationaliteit | geboortenationaliteit | geboortenationaliteit landcode | geboorte_nationaliteit_landcode
Geboortenationaliteit | geboortenationaliteit | geboortenationaliteit detail | geboorte_nationaliteit_detail
Herkomst | v1201_herkomst | v1201_herkomst | v1201_herkomst
Saldo | v1112_saldo | saldo | v1112_saldo
type huishouden (LIPRO 5 klassen) | echte_huishoudensindeling | type huishouden (LIPRO 8 klassen) | echt_hhtype
type huishouden (LIPRO 5 klassen) | echte_huishoudensindeling | type huishouden (LIPRO 6 klassen) | echt_hhtype_6k
type huishouden (LIPRO 5 klassen) | echte_huishoudensindeling | type huishouden (alleen/gezin/collectief) | echt_hhtype_alleen_collect
Type locatie openbaar vervoer en   snelwegen | v2107_typeloc_ov | Type locatie openbaar vervoer en snelwegen | v2107_typeloc_ov
Type locatie voorzieningen en oprit   snelwegen | v2107_typeloc_voorz | Type locatie voorzieningen en oprit snelwegen | v2107_typeloc_voorz
Kleine buffer van 200, 500 of 1000 m | v2107_bufferklein | Kleine buffer van 200, 500 of 1000 m | v2107_bufferklein
Grote buffer van 5, 10, 20 of 25 km | v2107_buffergroot | Grote buffer van 5, 10, 20 of 25 km | v2107_buffergroot
hh_type | hh_type | hh_type | hh_type
hh_wagens | hh_wagens | hh_wagens | hh_wagens
Sectorindeling | v1403_nace_indelingen | vereenvoudigde nace2 (OV-WV) | v1403_nace_vereenvoudigd
kubus3504_zorgverzekering | kubus3504_zorgverzekering | kubus3504_zorgverzekering | kubus3504_zorgverzekering
Socio-economische positie (KSZ) | socio_economische_positie_ksz | socio-economische positie | nomenclatuur_1
Sectorindeling | v1403_nace_indelingen | sectoren (indeling Limburg) | v1403_thematisch1
Eengezin/meergezin | v2210_eengezin_meergezin | None | None
nat_herkomst | nat_herkomst | None | None
onderwijstype | v2371_onderwijstype | None | None
Autovrij | v2120_autovrij | None | None
kubus2210_koppeling_hh | kubus2210_koppeling_hh | None | None
Indicatoren | indicatoren | None | None
kubus2371 | kubus2371 | None | None
nat_geboorte | nat_geboorte | None | None
kubus3505_zorgaanbod_woongelegenheden | kubus3505_zorgaanbod_woongelegenheden | None | None
Bouwvorm | v2210_bouwvorm | None | None

**Comment by StefanJacques** [comment]
Limburg heeft zijn kubussen nagekeken: geen enkele van de hierboven genoemde dimensies komen voor in de nog werkende kubussen.
DUS: de hierboven opgesomde dimensiecodes worden niet (meer) door ons gebruikt en mogen verwijderd worden.

**Comment by demaesschalckfilip** [comment]
Idem voor Vlaams-Brabant: deze dimensiecodes mogen weg.

**Comment by rudymarynissen** [comment]
Oké om te verwijderen wat gerelateerd is aan nationaliteiten in de lijst van Joost.

**Comment by Lievendr** [comment]
pendelin en pendeluit en socioeconomische positie Ksz mogen  ook weg

**Comment by joostschouppe** [comment]
Afgehandeld!
