### ISSUE TITLE
Randvoorwaarden onderzoeken gebruik "Mijn regio" in Dashboard

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#36]
Ziet er super interessant uit.
Aan te zetten via Mosaic Settings > Region and period > Enable My Region for the base region

Maar:
- gaat mis bij het doorklikken naar rapporten (de groep heeft een onzin-gebiedscode die resulteert in alweer een rapport van Aalst) > abf melding 82370
- gaat mis bij cijfers die deels ontbreken (vb gemeente van Vlaanderen + gemeente van Brussel). Niet aggregeerbare cijfers worden wel correct niet getoond. Dit is een data-beheerprobleem. Als data ontbreken die in het echt wel bestaan (Brussel heeft inwoners, wij hebben gewoon de data niet), dan moet je een "brekende ontbrekende waarde" inladen. Best is -99999, zie [alfresco](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/24aa375c-5eaf-4329-bc1b-89407a13c3ee). Essentieel is vooral bevolking. Komt in orde bij volgende update

**Comment by joostschouppe** [comment]
Openstaand issue opgelost door Edward op 18/6/2021

**Comment by joostschouppe** [comment]
Bij uitrol toch nog gemerkt:
- [ ] bevolking heeft niet de nodige [missing value -99999](https://github.com/provinciesincijfers/JiveDocumentation/blob/master/01.%20Algemeen%20databeheer/Missing%20values.md#ontbrekende-gegevens). Opgenomen met @rudymarynissen 
- [ ] [niet alle rapporten kunnen meerdere gebieden slikken](https://github.com/provinciesincijfers/PinC-taakopvolging/#taakverdeling-rapporten). Weinig aan te doen.
- [ ] de waarschuwing voor Brussel faalt! Voorbeeld https://provincies.incijfers.be/jive/jivereportcontents.ashx?report=dashboard_brussel&input_geo=gemeente_41002,gemeente_21001&input_compare=provincie_40000 . Ik los het op
- [ ] andere fouten in aggregeerbaarheid van data komen naar boven, bv ivm ruimteboekhouding (@davidcardinaels lost die van de ruimteboekhouding op)

**Comment by davidcardinaels** [comment]
Ruimteboekhouding is in orde.

**Comment by joostschouppe** [comment]
Melding ABF: als je meerdere gemeenten selecteert, dan verschijnt in de DetailView in de titel de naam van de eerste gemeente, niet de naam van de groep:
![afbeelding](https://user-images.githubusercontent.com/10122639/123095113-fd1bb380-d42d-11eb-92bc-098883c8ca72.png)

**Comment by Emilien-Dupont** [comment]
Wanneer je bij het dashboard 'Bevolking' gemeenten uit meerdere provincies selecteert, krijg je de verkeerde gegevens voorgeschoteld wanneer je klikt op de grafiektegel 'Bevolkingsdichtheid'.

![image](https://user-images.githubusercontent.com/77432663/123098498-7d8fe380-d431-11eb-8a45-07b0b7c6b7b8.png)

**Comment by joostschouppe** [comment]
In detailview wordt soms enkel totaal, soms enkel gemeenten, soms alles getoond
