### ISSUE TITLE
Omlijning favoriet gebied

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#361]
We hebben als afspraak dat in rapporten het favoriet gebied omlijnd wordt in een donkere kleur (zie https://provincies.incijfers.be/admin/jive/report/?id=sjabloon_grafiekstijl).
Dit wordt geregeld op template niveau en mag dus niet zelf aangepast worden. **Enkel voor de introductiekaarten** wordt dit expliciet achter het oogje geregeld. 
Voor geen enkele andere figuur mag dit aangepast worden. 

In een aantal rapporten wordt hiervan afgeweken met een oranje kleur, wat dus in principe niet volgens de afspraken is. 

Zorg er dus voor dat je achter het oogje de volgende code hebt staan onder \<PropertyGroup> \<Class>introkaart</Class>:

\<FavoritePen>
  \<Color>rgb(0, 0, 0)</Color>
        \<Width>2</Width>
        \<Style>Solid</Style>
      \</FavoritePen>

en **niet**
\<FavoritePen>
        \<Color>rgb(255, 69, 0)</Color>
        \<Width>2</Width>
        \<Style>Solid</Style>
      \</FavoritePen>

**Comment by joostschouppe** [comment]
Voorstel van Vicky: pas het sjabloon aan om de Swing-standaard-weergavestijl in oranje te gebruiken ipv het huidige zwart voor alle kaarten behalve de introkaarten. (dit zou dus een aanpassing op Template>Report niveau zijn denk ik)
