### ISSUE TITLE
Lange links (over 2 of meer regels) in PDF-export van rapporten

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#368]
Wanneer een voetnoottekst in een rapport een lange link naar een externe webpagina bevat, die over twee of meer regels gesplitst wordt, doet zich een probleem voor wanneer je het rapport downloadt als PDF.

De volledige regel gedraagt zich dan als een externe link, ook de eventuele tekst die aan de eigenlijke link voorafgaat, en ook het voetnootnummer aan het begin van de regel. Dat heeft vooral het vervelende gevolg dat je niet meer op het voetnootnummer kunt klikken om terug te keren naar de plaats in de tekst waar de bijbehorende voetnootverwijzing staat. Wanneer je op het voetnootnummer klikt, wordt ten onrechte de externe webpagina geopend.

Zie als voorbeeld voetnoot 26 in het Report _rapport_adaptatiemaatregelen_.

![voetnoot_link](https://user-images.githubusercontent.com/101627698/225261770-ff3e38b7-e9b7-492f-8f41-88d7c05f1d47.png)

Hoe het probleem zich precies manifesteert, is echter afhankelijk van de PDF-viewer die je gebruikt om het PDF-bestand te bekijken. Open je het PDF-bestand in Edge, dan werkt de link met het voetnootnummer wél correct (maar de andere tekst op de regel gedraagt zich nog altijd ten onrechte als een link naar de externe webpagina). Open je het PDF-bestand in Chrome, Firefox of Acrobat Reader, dan werkt de link met het voetnootnummer niet correct. Maar hoe dan ook is hier duidelijk iets mis met het PDF-bestand zelf.

N.B.: het probleem doet zich niet voor in de online versie van het rapport, enkel in de PDF.

**Comment by joostschouppe** [comment]
Mensen kunnen natuurlijk die PDF gaan printen, maar dit soort URL's intypen is nogal extreem, niet? Is een betere oplossing niet gewoon om hier te werken met een "klik hier" link?

**Comment by GeertBonte** [comment]
Het is inderdaad (veel) beter om dit soort lange links te vermijden en te werken met een kortere tekst waarop je dan kunt klikken. Op die manier omzeil je de bug en maak je het rapport ook nog eens beter. :)

Maar het blijft een bug.

**Comment by joostschouppe** [comment]
Voorstel aanpassing: 
Binnen rapporten: vervang zowel lange als korte links door gewone tekst met de URL enkel in de html code. Bij voorkeur door gebruik van bestaande tekst, indien nodig door een "klik hier" link ofzo
Voor metadatafiches: enkel vervangen indien het langer wordt dan één regel

**Comment by joostschouppe** [comment]
Redactiegroep 23/3/2023 - bevestiging uitrol

**Comment by davidcardinaels** [comment]
Links zijn aangepast.

**Comment by Emilien-Dupont** [comment]
Toegevoegd aan de sjablonen
