### ISSUE TITLE
Publiek zetten "achter de schermen van de databank"

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#37]
Dus deze: https://provincies.incijfers.be/databank?report=achter_de_schermen

- [ ] bespreken op IPWG/Redactiegroep
- [ ] voorbeelden op Provincies in Cijfers ipv Antwerpen in Cijfers

**Comment by StefanJacques** [comment]
Help mij eens Joost: moet dit nog eerst ergens besproken worden ? Dacht dat dat al op de redactiegroep was gekomen, niet ?
