### ISSUE TITLE
Gebiedskeuze in rapporten: niet te lokaliseren/onbekend

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#371]
Momenteel is er niets dat een gebruiker belet om een rapport op te vragen voor een onzinnig gebied zoals de gemeente 'Niet te lokaliseren' of de provincie 'provincie onbekend (Vlaanderen)'. In die gevallen wordt nu een onzinnig rapport getoond, met bijvoorbeeld deze teksten in de leeswijzer:

> Momenteel zie je het rapport voor gemeente **Niet te lokaliseren - Vlaanderen**.
> Momenteel zie je het rapport voor gemeente **Aalst** en **Niet te lokaliseren**.
> Het huidige rapport vergelijkt **Niet te lokaliseren - Vlaanderen** met de door jou gekozen vergelijkingsgebieden **provincie onbekend (Vlaanderen)** en **het Vlaams Gewest**.

De rest van het rapport wordt gewoon getoond (met lege of nietszeggende tabellen, grafieken kaarten, zie bijvoorbeeld het [rapport arbeidsmarkt](https://provincies.incijfers.be/databank/report/?id=rapport_arbeidsmarkt&input_geo=gemeente_99991&input_compare=provincie_99991)).

Ik stel voor om daar iets aan te doen en het sjabloon vertrekproject (en alle bestaande rapporten) uit te breiden met een test op onbekende of niet te lokaliseren gebieden.

Om dit technisch te implementeren, is er een eenvoudige test waarmee je kunt vaststellen of een dergelijk gebied werd gekozen, namelijk door de oppervlakte van het gebied (`v9900_opp_m2`) op te vragen uit de databank. Bij echte gebieden krijg je altijd een getal; bij 'niet te lokaliseren'/'onbekend'-gebieden krijg je geen waarde (-).

Wanneer de gebruiker zo'n gebied kiest, zou volgende boodschap kunnen verschijnen en zou de rest van het rapport verborgen kunnen worden:

> We kunnen geen rapport weergeven voor **Niet te lokaliseren**. Klik op de "Wijzig"-knop om een ander gebied te kiezen. Je kunt ook een gebied samenstellen op kaart.

**Comment by GeertBonte** [comment]
> Het is denk ik ook mogelijk om de gebiedskeuze te beperken tot een lijst gebieden. Misschien is dat een betere optie? Dat betekent dan wel dat we die lijst zouden moeten beheren in alle rapporten.

Daar had ik ook al aan gedacht, maar in de praktijk blijkt dat onwerkbaar. Ik heb eens een en ander uitgeprobeerd. Als je bij input_geo een Subset gebruikt, dan wordt Level genegeerd en dan verschijnt overal het woord 'gemeente' voor de gemeentenaam. Je krijgt dan ook één lijst met daarin zowel gemeenten als provincies (en eventuele andere mogelijke gebiedsniveaus), en dat is allesbehalve wenselijk.

En voor rapporten die opvraagbaar zijn op wijk- of statistisch sectorniveau zul je een erg lange lijst nodig hebben. Voor zover ik zie, gaan we er op die manier helaas niet geraken. Maar misschien zie ik iets over het hoofd en is er toch een mogelijkheid. Iemand anders mag altijd eens een poging doen.

Dus de enige optie die ik zie is een test met een boodschap en een verzoek om een ander gebied te kiezen, zoals nu ook gedaan wordt voor rapporten die niet voor Brussel getoond kunnen worden.

Maar hoe dan ook is het geen prioritair probleem. Slechts weinig gebruikers zullen het in hun hoofd halen om een rapport op te vragen voor 'Niet te lokaliseren', tenzij (zoals ik) uit pure nieuwsgierigheid, om te zien wat er dan gebeurt...

**Comment by Emilien-Dupont** [comment]
Dit werd toegevoegd in het Sjabloon met afspraken onder hoofdstuk 28 en mag uitgerold worden.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/09/'23:
Akkoord, @davidcardinaels rolt uit.

**Comment by davidcardinaels** [comment]
Toegevoegd in alle rapporten.
