### ISSUE TITLE
Verwijzingen naar figuren cursief

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#372]
Volgens de [afspraken](https://provincies.incijfers.be/databank/report/?id=sjabloon_grafiekstijl) moeten verwijzingen naar grafieken, tabellen en kaarten in de tekst cursief staan. Zo‘n verwijzing plaats je bijvoorbeeld met `<span class="teller_grafiektekst"></span>`. Hiermeer wordt het woord ‘grafiek’ en het eerstvolgende grafieknummer gegenereerd. Om dit cursief te maken, moet je `<i><span class="teller_grafiektekst"></span></i>` gebruiken, het gevaar bestaat dat de `i`-tags soms vergeten worden (zie bv. de verwijzing naar grafiek 22 in het [rapport klimaatscenario's Brugge](https://provincies.incijfers.be/databank/report/?id=rapport_klimaatscenarios&input_geo=gemeente_31005,), onder kopje 1.4.2).

Daarom een voorstel om de CSS aan te passen zodat dergelijke verwijzingen automatisch cursief komen te staan. Dat kan door volgende code toe te voegen aan `ipo_dynamic.css`:

```
.teller_tabeltekst, .teller_kaarttekst, .teller_grafiektekst { font-style: italic; }
```

N.B.: dit maakt het gebruik van `<i>...</i>` overbodig, maar het is NIET nodig om dat in alle rapporten aan te passen. Het kan geen kwaad als de `i`-tags toch blijven staan, maar het is een fallback voor wanneer ze vergeten werden.

**Comment by Emilien-Dupont** [comment]
Geert, prima om zo uit te rollen. Kan je in de css de nieuwe functie kort duiden?

**Comment by GeertBonte** [comment]
Toegevoegd aan ipo_dynamic.css.

**Comment by Emilien-Dupont** [comment]
Toegevoegd aan sjabloon_grafiekstijl

**Comment by davidcardinaels** [comment]
Tags zijn overal verwijderd.
