### ISSUE TITLE
Verwijzingen naar figuren met hoofdletter

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#374]
Volgens de [afspraken](https://provincies.incijfers.be/databank/report/?id=sjabloon_grafiekstijl) gebruiken we `<span class="teller_grafiektekst"></span>` om in de tekst van rapporten te verwijzen naar grafieken. Dit genereert het woord ‘grafiek’ met een kleine letter, maar erg vaak wil je dit gebruiken aan het begin van een zin, en dan moet het met een hoofdletter.

Dat kan opgelost worden door een `style`-attribuut toe te voegen, bv.:

```
<span class="teller_grafiektekst" style="text-transform: capitalize"></span>
```

Maar dat maakt de code nogal lang, en het is misschien wat lastig te onthouden. Daarom een voorstel om de CSS aan te passen. Niet door drie nieuwe classes aan te maken (voor verwijzingen met hoofdletter naar tabellen, kaarten en grafieken), maar door één nieuwe class aan te maken die dan bijkomend in het `class`-attribuut vermeld kan worden. Je kunt immers meer dan één class-naam opgeven (telkens met een spatie ertussen), en alle opgegeven classes worden dan toegepast.

Wanneer volgende code toegevoegd wordt aan `ipo_dynamic.css`:

```
.hoofdletter { text-transform: capitalize; }
```

dan kun je eenvoudig dit gebruiken om verwijzingen met hoofdletter te genereren voor zowel tabellen, kaarten als grafieken:

```
<span class="teller_tabeltekst hoofdletter"></span>
<span class="teller_kaarttekst hoofdletter"></span>
<span class="teller_grafiektekst hoofdletter"></span>
```

Bovendien is zoiets ongetwijfeld gemakkelijker te onthouden.

**Comment by Emilien-Dupont** [comment]
Toegevoegd aan sjabloon_grafiekstijl.
Ter info op de Redactiegroep

**Comment by davidcardinaels** [comment]
Is overal aangepast.
