### ISSUE TITLE
Onzichtbare tellers

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#375]
In het [rapport afspraken](https://provincies.incijfers.be/databank/report/?id=sjabloon_grafiekstijl) wordt getoond hoe je een onzichtbare teller kunt invoegen (om de teller te laten oplopen zonder dat het tabel-, kaart- of grafieknummer in de tekst verschijnt):

```
<span class="teller_grafiektekst" style="opacity: 0;"></span>
```

Dit maakt de teller inderdaad onzichtbaar, maar heeft het nadeel dat de onzichtbare tekst wel nog altijd ruimte inneemt. Het gevolg is dat je dit dus niet kunt gebruiken aan het begin van een alinea of midden in een alinea. Als je dit op het einde van een alinea plaatst, valt het niet op, maar de alinea wordt wel een stukje langer. Dit kan dus resulteren in een onnodige extra regel aan het einde van de alinea.

Er zijn nog meer manieren om tekst onzichtbaar te maken met CSS, zoals `visibility: hidden` of `display: none`. Het eerste maakt de tekst onzichtbaar en laat wel ruimte (zoals `opacity: 0`); het tweede zorgt ervoor dat het element niet gerenderd wordt. Dat betekent dat de tekst niet gewoon onzichtbaar geplaatst wordt, maar dat de tekst helemaal niet geplaatst wordt. Die manier is voor onze tellers niet bruikbaar, aangezien de tellers dan ook niet oplopen.

Wat we eigenlijk willen, is een manier om de tekst onzichtbaar te maken <em>zonder</em> dat die onzichtbare tekst plaats inneemt. Dat kan door de breedte van het `span`-element ook nog op nul te zetten, maar dat werkt dan weer niet met inline elementen. Om dit te laten werken, moet het display type van het `span`-element op `inline-block` gezet worden. Samengevat wordt het dan dus dit:

```
<span class="teller_grafiektekst" style="display: inline-block; visibility: hidden; width: 0;"></span>
```

Dat is echter nogal lang en wellicht ook wat moeilijk te onthouden. Daarom een voorstel om dit op te lossen aan de hand van een nieuwe class. Eén class volstaat. Je kunt de class zowel bij tabellen, kaarten als grafieken gebruiken.

Wanneer volgende code toegevoegd wordt aan `ipo_dynamic.css`:

```
.verborgen { display: inline-block; visibility: hidden; width: 0; }
```

dan kun je eenvoudig dit gebruiken om onzichtbare verwijzingen te plaatsen voor zowel tabellen, kaarten als grafieken, ook midden in een alinea:

```
<span class="teller_tabeltekst verborgen"></span>
<span class="teller_kaarttekst verborgen"></span>
<span class="teller_grafiektekst verborgen"></span>
```

Bovendien is zoiets ongetwijfeld gemakkelijker te onthouden.

Als je dit midden in een alinea gebruikt, zorg dan dat er hoogstens één spatie staat net vóór of net achter het `span`-element. Typ je zowel een spatie ervoor als erna, dan zullen er ook twee spaties gerenderd worden in het rapport (wat niet de bedoeling is).

**Comment by Emilien-Dupont** [comment]
In orde om zo toe te voegen. Kan je ook hier in de css de nieuwe functie kort duiden?

**Comment by GeertBonte** [comment]
Toegevoegd aan ipo_dynamic.css.

**Comment by Emilien-Dupont** [comment]
Toegevoegd aan sjabloon_grafiekstijl.
Ter info op de Redactiegroep

**Comment by davidcardinaels** [comment]
@GeertBonte 
Dit lijkt niet goed te werken. Als ik dit ergens toevoeg dan krijg ik een hele regel witruimte. Zie rapport_natioherkomst.

**Comment by GeertBonte** [comment]
Vreemd, ik heb dit nochtans al gebruikt in enkele hoofdstukken van de omgevingsanalyse, waar het goed leek te werken. Maar geen nood, het is ondertussen opgelost. ik heb `line-height: 0;` toegevoegd in ipo_dynamic.css en daarmee is het probleem van de baan.

**Comment by davidcardinaels** [comment]
Is overal aangepast.
