### ISSUE TITLE
Herhaalde tellers

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#377]
In het [rapport afspraken](https://provincies.incijfers.be/databank/report/?id=sjabloon_grafiekstijl) wordt uitgelegd hoe de automatische tellers werken voor tabellen, kaarten en grafieken, bv. telkens wanneer je `<span class="teller_grafiektekst"></span>` gebruikt, krijg je het eerstvolgende grafieknummer. Omdat de teller oploopt telkens je de code zet, kun je niet twee keer verwijzen naar dezelfde grafiek.

Soms is het echter handig als je tóch twee keer naar dezelfde grafiek zou kunnen verwijzen. Je zou de tweede keer het grafieknummer hard in de tekst kunnen zetten, maar dat is eigenlijk geen goed idee. Immers: wanneer je grafieken gebruikt binnen conditionele secties, dan krijgen je grafieken een ander nummer van zodra er ergens een grafiek weggevallen is. Als je een grafieknummer hard in de tekst zou zetten, dan klopt het mogelijks niet meer.

Daarom een voorstel om dit op te lossen aan de hand van een nieuwe class. Je kunt de class zowel bij tabellen, kaarten als grafieken gebruiken en je kunt dit combineren met de class `hoofdletter` wanneer je verwijzing aan het begin van een zin staat (zie issue [https://github.com/provinciesincijfers/PinC-taakopvolging/issues/374](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/374)).

Wanneer volgende code toegevoegd wordt aan `ipo_dynamic.css`:

```
.teller_tabeltekst.herhaal   { counter-increment: tabelnumtekst 0; }
.teller_kaarttekst.herhaal   { counter-increment: kaartnumtekst 0; }
.teller_grafiektekst.herhaal { counter-increment: grafieknumtekst 0; }
```

dan kun je eenvoudig een tweede keer naar eenzelfde tabel, kaart of grafiek verwijzen met onderstaande code:

```
<span class="herhaal teller_tabeltekst"></span>
<span class="herhaal teller_kaarttekst"></span>
<span class="herhaal teller_grafiektekst"></span>
```

In de tekst verschijnt dan nogmaals hetzelfde nummer, zonder dat de teller oploopt. De teller begint pas weer op te lopen wanneer je een volgende keer `teller_tabeltekst` gebruikt (zonder `herhaal`).

Staat je verwijzing aan het begin van een zin, dan kun je dit combineren met de class `hoofdletter`, bv.:

```
<span class="herhaal teller_tabeltekst hoofdletter"></span>
<span class="herhaal teller_kaarttekst hoofdletter"></span>
<span class="herhaal teller_grafiektekst hoofdletter"></span>
```

Dit lijkt me een handige manier van werken, eenvoudig en makkelijk te onthouden.

N.B.: wanneer je, zoals in de voorbeelden hierboven, meerdere classes gebruikt binnen één `class`-attribuut, dan speelt de volgorde geen rol. Onderstaande stukjes code zullen drie keer hetzelfde resultaat opleveren:

```
<span class="herhaal teller_tabeltekst hoofdletter"></span>
<span class="teller_tabeltekst herhaal hoofdletter"></span>
<span class="hoofdletter herhaal teller_tabeltekst"></span>
```

**Comment by Emilien-Dupont** [comment]
Toegevoegd aan sjabloon_grafiekstijl
