### ISSUE TITLE
Call to action in rapporten

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#380]
Puntje van feedback op het rapport mobiliteit: op het einde 'call to action' toevoegen om suggesties door te geven. Momenteel wordt dit in nog geen enkel rapport gedaan. Moet dit worden opgenomen in rapport mobiliteit, en bij uitbreiding misschien ook andere rapporten? Of is dit het openen van de 'doos van pandora' (i.e. als er reacties komen, moet er ook wel op worden gereageerd + er zijn al verschillende andere manieren om contact op te nemen via de rapporten...

**Comment by joostschouppe** [comment]
Redactiegroep 20/4/2023
* Beter alternatief: rechtstreeks contact opnemen met effectieve gebruikers gemeentebesturen
* Voorkeur om het gewoon te houden bij de huidige contactgegevens
