### ISSUE TITLE
Legende lijngrafieken 1 gebied

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#382]
Voorstel om op te nemen in het sjabloon met afspraken:
Bij lijngrafieken waar slechts 1 gebied wordt getoond, laten we de legende weg omdat dit dubbelop is met de titel (hierin wordt het gebied al vermeld.
Dit geldt **enkel voor rapporten waar je max 1 gebied kan aanduiden** (rapporten buurtgerichte zorg, eerstelijnszones, opvang baby's en peuters, omgevingsanalyses)

**Comment by veravandestraat** [comment]
Eens.

Ik vermoed dat dat een officiële bevestiging is van iets dat in de praktijk al gebeurt :)?

<img width="223" alt="image" src="https://user-images.githubusercontent.com/61196697/229818126-d971befb-66d7-446e-846c-408e1544fd77.png">

**Comment by joostschouppe** [comment]
In andere rapporten kan dit eventueel ook als je bij de layoutclass een parameter invult en de keuze voor de layoutclass laat afhangen van het aantal gekozen gebieden.  Maar: sop en kolen?

**Comment by joostschouppe** [comment]
Redactiegroep 20/4/2023
* ok voor rapporten met één gebied, maar geen constructie met conditionele secties
