### ISSUE TITLE
Volgorde rapporten op dashboard rapporten

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#384]
Tijdens het overleg met de werkgroep Natuur werden er een aantal opmerkingen gemaakt/vragen gesteld over het dashboard rapporten:
- voor iemand die minder bekend is met klimaat is het niet duidelijk dat een rapport adaptatiemaatregelen over klimaatadaptatiemaatregelen gaat
- waarom staan de rapporten 'cijfers opgelijst' bij het thema en niet als afzonderlijke categorie, zodat je in een oogopslag kunt zien voor welke thema's er een rapport 'cijfers opgelijst' is?

Wat dat laatste punt betreft kunnen we misschien werken met dezelfde grijze balken als in de thematische dashboards om drie groepen van rapporten te maken:
 - cijfers opgelijst
 - gemeenterapporten
 - speciale gevallen: rapporten op wijkniveau en ELZ-niveau

**Comment by joostschouppe** [comment]
Redactiegroep 20/4/2023
* suggestie om met iconen te werken
* suggestie om kleinere blokjes te maken

**Comment by joostschouppe** [comment]
@KoenSnyers heeft alvast de zaak compacter gemaakt: https://provincies.incijfers.be/dashadmin/preview/dashboard/rapporten
Lijkt me veel beter!

**Comment by joostschouppe** [comment]
Ik heb nog wat geëxperimenteerd: https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/rapporten
Eerst wou ik met de compacte versie verder, en daar iconen toevoegen. Maar dat werd veel te druk. Ik heb dan in de plaats met scheidingsbalken per thema van de nieuwe Themaboom gewerkt. Dat was dan weer te zwaar. Dat heb ik proberen oplossen met witruimte.
- een ander icoontje voor de "cijfers opgelijst" lijkt me sowieso beter
- ik heb die ook systematisch wat smaller gemaakt (bediscussieerbaar)
- de iconen per rapport-thema overtuigden me niet, maar ik heb ze bij demografie laten staan ter illustratie
- nog een ander rapport-type icoon bij de "beleidsspecifieke" lijkt me nog wel handig

**Comment by StefanJacques** [comment]
> 

collega's klimaat akkoord voor
"rapport klimaatadaptatie"

**Comment by KoenSnyers** [comment]
@veravandestraat @joostschouppe @StefanJacques 

ik heb nog wat aanpassingen gedaan:

- om het chaotische met verschil in lettergrootte wat op te vangen, heb ik bij elke tegel de titel verwijderd en in het tekstvak de titel toegevoegd in dezelfde puntgrootte; dat het dan één, twee of drie regels zijn, is niet te vermijden en hangt af van de lengte van de titel uiteraard
- de themabalken er nog tussenvoegen geeft naar mijn gevoel een overload, ik heb het dus heel compact gehouden en voor de meeste rapporten voor een smalle rechthoek gekozen; zo krijgen we een compact overzicht, waarbij gebruikers bijna niet meer hoeven te scrollen om alle rapporten in één oogopslag te zien
- om het verschil tussen rapport en cijfers opgelijst visueel duidelijk te maken, heb ik voor cijfers opgelijst het icoontje gebruikt dat Joost had voorgesteld
- ik heb het rapport opvang baby's en peuters op dezelfde manier weergegeven als het rapport buurtgerichte zorg en het rapport eerstelijnszones, dus met 'opgelet' erbij

Case closed now, I hope ... :-)

**Comment by zenebben** [comment]
@joostschouppe @veravandestraat @StefanJacques 
Ik heb het dashboard rapporten ook eens bekeken en er is ondertussen al zoveel bijgekomen dat het een beetje chaotisch overkomt. Eigenlijk een over-load aan informatie en niet echt gestructureerd: je hebt cijfers, (kern)cijfers en de (thematische) rapporten, allemaal door elkaar. Eventueel in 3 blokken werken (al dan niet een kleur per blok )? of eventueel de thema's groeperen als dat kan? enfin, ik weet dat ik hier zomaar binnendring, maar ik sta er ook verder van af dan jullie waardoor het voor iemand als ik verwarrend overkomt.

**Comment by demaesschalckfilip** [comment]
Het vind het er prima uitzien. We moeten inderdaad nog wel eens nadenken over de volgorde (mogelijk gekoppeld aan de volgorde in de vernieuwde databank);  de rapporten en de cijfers lijken me ook gegroepeerd te kunnen worden. 

Toch nog een vraag: ik zie niet goed waar de 'opgelet' voor staat/dient. Het rapport bevolking, om er maar eentje te noemen, heeft ook cijfers op niveau statistische sectoren. Is dat een probleem? De drie rapporten/kerncijfers waarbij deze waarschuwing staat, vallen nu wel erg op.

**Comment by KoenSnyers** [comment]
Lieve mensen,

Het opdelen in thema's en/of in rapporten versus cijfers opgelijst: dat kan ik uiteraard doen, maar ik vraag me af welke meerwaarde het heeft. En als ik het doe, is er ongetwijfeld weer iemand die vindt dat het anders moet.
Mensen zien, zoals het er nu uitziet, zelfs op een klein laptopscherm haast in één oogopslag welke rapporten er allemaal zijn, grotendeels gerangschikt van links naar rechts en van boven naar onder in de volgorde van de hoofthema's op het dashboard.
Was het samengebalder en overzichtelijker maken niet het doel?

Wat die 'opgelet' betreft: die heb ik lang geleden voor het rapport buurtgerichte zorg en het rapport eerstelijnszones op vraag toegevoegd, en nu ook toegevoegd voor het rapport opvang baby's en peuters op vraag van Vera.
Maar het is inderdaad zo dat dit ook geldt voor bv. het rapport bevolking en huishoudens.
Wat mij betreft mag het bij elk rapport weggelaten worden, want vooraan in elk rapport krijgt de lezer wel de nodige instructies over gebieden en gebiedsindelingen ... 
Dus, ik heb de vrijheid genomen om die 'opgelet' weg te laten bij alle rapporten en heb de rapporten in de juiste volgorde toegevoegd aan het lijstje.

En dan stel ik voor dat we deze rapportenpagina voor nu even laten zoals ze is.  :-)

**Comment by joostschouppe** [comment]
Die waarschuwing was vooral om te zeggen: opgelet, dit rapport werkt anders dan de andere. Normaal gezien zeg je: "ik ben geïnteresseerd in dit gebied", en ligt de focus op dat gebied. In die twee oorspronkelijke rapporten is het niet het gebied zelf dat de meeste aandacht krijgt, maar zijn deelgebieden. Waar je dus ander een rapport zou kunnen opvragen voor 20 statsec samengenomen, krijg je in zo'n rapport eentje waar alle statsec van een gemeente afzonderlijk zichtbaar zijn. Omwille van de gebruiksvriendelijkheid hamer ik er steeds op dat de functionaliteit van de rapporten voorspelbaar en zo veel mogelijk hetzelfde moet zijn. Ondertussen zijn er vier rapporten die van de standaard afwijken, maar die wel alle vier ongeveer hetzelfde werken. Dus die vier op een of andere manier aanduiden lijkt me niet slecht.
Maar wel akkoord dat de oude aanduiding niet zo duidelijk was en het vooral heel veel ruimte geeft in vergelijking met andere rapporten.

**Comment by joostschouppe** [comment]
Redactiegroep 25/5
* de nieuwe versie is duidelijk beter
* toch blijft het een hele grote lijst zonder structuur. Een lijst die ook alleen maar langer gaat worden
* op vraag van de Redactiegroep [maakte ik nog deze poging](https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/rapporten) op basis van een eerder idee om de nieuwe thematische structuur hier te laten terugkomen. Nu wat compacter! Ook de vier inhoudelijk atypische rapporten samengezet. De tussentitels waren heel zwaar en zijn nu al in een lichter grijs gezet. Ik was nog altijd niet overtuigd en heb de onderste balken in bijna-wit met zwarte tekst gezet

**Comment by Tine-VB** [comment]
Geeft nu wel een duidelijker structuur, waarschijnlijk makkelijker om iets terug te vinden voor de occasionele gebruiker. Persoonlijk zou ik gaan voor de onderste balken, maar dan in een minder bijna-wit (ofte iets grijzer dus ;-) ), zodat je de balk nog beter ziet staan. Maar over smaken en kleuren...

**Comment by veravandestraat** [comment]
Ik ben voor deze poging!

Opmerking van @zenebben sluit een beetje aan bij wat Tine zegt: bijna-wit met zwarte tekst maakt dat je de balk bijna niet meer ziet staan en de tekst te veel gaat zweven. Onder het donkergrijs zie je heel duidelijk dat de rapporten bij dat blok horen, terwijl dat bij het bijna-wit minder het geval is.
Ik vind het persoonlijk ook wel mooier als de letters van de thematische structuur in het wit kunnen blijven staan, misschien nog één tintje lichter grijs ;)?

**Comment by HanneODB-VLBR** [comment]
Ziet er heel goed uit, ik ben er ook voorstander van om op deze manier meer structuur aan te bieden. Volgens mij gaat het nog overzichtelijker zijn als de 'titelbalken' naast elkaar komen te staan, ik weet niet of dat mogelijk is? (In dit voorbeeld: de balk 'Leefmilieu & klimaat' recht naast die van 'Demografie' en die van 'Samenleving & welzijn' recht naast die van ' Onderwijs'). Je creeërt dan wel extra witruimte (bijvoorbeeld onder 'Wonen en Ruimtegebruik') en de gebruiker gaat iets meer moeten scrollen, maar volgens mij ga je daarvoor toch een minder druk overzicht krijgen (en bovendien moet de gebruiker nu sowieso ook al scrollen, wil hij alles zien...).

**Comment by GeertBonte** [comment]
Enkele typografische opmerkingen. In de veronderstelling dat het mogelijk is om dit aan te passen, stel ik het volgende voor:

- probeer ervoor te zorgen dat de rapporttitels niet meer dan 2 regels innemen door alle rapporttitels in een kleiner lettertype te zetten
- om te vermijden dat het lettertype dan te klein wordt (zoals bij sommige rapporttitels nu), zou ik zowel de insprong als de ruimte tussen pictogram en tekst verkleinen waardoor er meer plaats is voor de tekst
- als dat niet mogelijk blijkt (omdat het lettertype dan te klein zou worden), behoud dan 3 regels voor lange rapporttitels, maar zet alle rapporttitels toch in een iets kleiner lettertype (voor alle titels dezelfde tekengrootte gebruiken, geen mix van grote en kleine titels zoals nu)
- de tekst van de themakoppen inspringen zodat ze aligneren met de rapporttitels (nu plakken ze tegen de rand van het kader aan en dat is niet mooi)

**Comment by GeertBonte** [comment]
Wat betreft de bijna-witte balken: dit kan er oké uitzien op jouw en mijn beeldscherm, maar gebruikers die dit bekijken op een scherm met een minder goed contrast zullen geen verschil meer zien tussen wit en bijna-wit. Daarom denk ik net als @Tine-VB dat het beter is om het bijna-wit toch iets donkerder te maken.

**Comment by Tine-VB** [comment]
Suggestie van de collega's: er eens een externe professionele consultant / layouter op los laten?

**Comment by Tine-VB** [comment]
Externe consultant bedoelden wij vooral voor de landingspagina, dus ik heb het hier eigenlijk in het verkeerde github item gezet.
Er werd trouwens feedback gevraagd, dus doen we allemaal onze best om daar tijd voor vrij te maken. Net zoals we dat ook doen bij de lancering van een nieuw rapport of wijzigingen aan andere producten.

**Comment by KoenSnyers** [comment]
Ziezo, de rapportenpagina is helemaal aangepast en staat online:
https://provincies.incijfers.be/dashboard/dashboard/rapporten.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/06:
- Beleidsrapporten helemaal onderaan. Filip wil dat graag, de rest heeft weinig uitgesproken mening 
- Niet lezen als bladzijden van links naar rechts maar van boven naar onder 
- Poging: niet in twee hoofd kolommen maar in volle breedte 
- Witte balken of grijze: voorkeur voor witte balken, proberen laag en breed 
- Plaatsing ELZ en BGZ rapporten: deze staan niet in een specifiek thema, dus ze mogen blijven staan 
- Insprong van de figuur verminderen? Tekst indien geen icoon niet laten plakken tegen linkerkant 
- Thema Mobiliteit toevoegen

**Comment by Lievendr** [comment]
Wij krijgen onlangs bericht van een hogeschool:
"Zoals je misschien weet ben ik momenteel het volledige ondersteuningspakket aan het updaten met veel verwijzingen naar provincies in cijfers. Ik merkte net op dat de website terug veranderde 😊 Staan er nog grote veranderingen op de planning na de zomer? Ik trek nl. printscreens van de tabellen e.d. maar moet toewerken naar een definitieve versie. Dan weet ik nog waar ik rekening mee kan houden in het uitwerken van de finale versie."

We willen ook onze landingspagina aanpassen.
We moeten dus bewust zijn van de implicaties. Concreet zijn mijn opleidingsfilmkes na twee maand al gedateerd... (ook al zijn het uiteraard details die veranderd zijn; voor ons doelpubliek kan dit verwarrend zijn, zoals docent hierboven toch wel aangeeft)...

dus graag, dashboardoverstijgend, ook dit in overweging nemen in grote aanpassingen...

**Comment by Tine-VB** [comment]
Concreet voor deze vraag: ik zou hem/haar alvast aanraden om linken te maken in plaats van print screens 😁

**Comment by StefanJacques** [comment]
> Goed te keuren door de redactiegroep:
> 
> https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/rapporten

bij goedkeuring zeker nog de schoonheidsfoutjes er uit halen:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/7c8cb597-5aa8-4392-8f7f-93a6d2ee12dc)

Het is me ook opgevallen dat volgorde van de thematische rapporten in de themaboom nog aangepast moet worden aan de nieuwe structuur van de themaboom.

![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/ee966dcf-d0a8-427e-86e8-bf09480dcd17)

**Comment by Tine-VB** [comment]
Inderdaad nog wat schoonheidsfoutjes: letten op de kleur van de balken, sommige zijn wit (demografie, leefmilieu en klimaat, overzichts- en beleidspecifieke rapporten). Ook nog eens kijken naar de hoofdletters (maar dat heb je waarschijnlijk al gedaan, Stefan?). Verder is dat OK voor Vlaams-Brabant.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/09/'23:
akkoord, mits de schoonheidsfoutjes eruit gehaald worden. Geert gaat na of de lettertypes niet even groot kunnen en het niet links uitgelijnd kan worden.

**Comment by KoenSnyers** [comment]
@Emilien-Dupont @StefanJacques 
Ik pas alles aan op de rapportenpagina zoals ik die een hele tijd geleden al had aangepast. Ik doe dat volgens het ontwerp in de betaversie en ik haal de schoonheidsfoutjes eruit. @GeertBonte: op die rapportenpagina zoals ze online staat, staan alle rapporten al in dezelfde lettergrootte (dat had ik bij een vorige aanpassingsronde al aangepast), dus bespaar je de moeite om dat nog uit te zoeken.

**Comment by KoenSnyers** [comment]
@Emilien-Dupont @StefanJacques 

De rapportenpagina is aangepast en staat online: 
https://provincies.incijfers.be/dashboard/dashboard/rapporten

**Comment by Emilien-Dupont** [comment]
De volgorde van de thematische rapporten in de themaboom en op de landingspagina werd aangepast
