### ISSUE TITLE
Opkuis themaboom

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#385]
De themaboom wordt te zwaar. [In dit bestand](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Redactiegroep%20PinC/Kwaliteitscontrole/Controlebestanden/themaboom%20opkuis.xlsx?d=w2b6d17e2a8f24eabad131017b59d9d9f&csf=1&web=1&e=KO5V8w) kan je eenvoudig zien waar er veel onderwerpen zijn.
De eenvoudigste plaatsen waar we winst kunnen halen:
- admin only: alles verwijderen wat ondertussen in orde is. Quick wins: onderwijs
- intern: zijn de projectmatige thema's altijd nog nodig? Is de "thematische indeling" nog nodig? Moet die zo ruim zijn?

Voorstel:
- eerst zelf kuisen
- dan eventueel grote kuis, na nemen van backup in Excel

**Comment by HanneODB-VLBR** [comment]
Ik heb 'mijn' 'admin only' leeggemaakt, alles dat daaronder stond mocht inderdaad weg. Ook het interne 'project mobiliteit' bevatte nog verschillende dubbels, die ik verwijderd heb. Het 'interne' project mobiliteit op zich is momenteel wel nog nodig voor de (interne) verspreiding van de FOD enquete woon-werkverkeer, maar vanaf we daar een go krijgen om extern te gaan zal dat ook niet meer nodig zijn...

**Comment by joostschouppe** [comment]
Redactiegroep 20/4/2023
* op te maken: welke onderwerpen in "thematische indelingen" staan niet extern; ook verantwoordelijke toevoegen
* we maken een nieuwe INTERN, waarnaar we alles verplaatsten dat behouden moet blijven, inclusief de projectmappen

**Comment by veravandestraat** [comment]
Ik heb onder Admin only de map van Mieke (met de oude indicatoren Natuur) verwijderd en in mijn eigen map alle indicatoren verwijderd die intussen extern staan.

**Comment by KoenSnyers** [comment]
@joostschouppe @StefanJacques 
Ik heb op het DB de bronnentegel naar boven gebracht.

**Comment by StefanJacques** [comment]
Demografie [Statbel] en Demografie [prognoses] @valeriepirard ook FPB
--> verhuisd naar INTERN2 (staan immers enkel INTERN)

van "Water" en "Milieu" een project gemaakt

van "Klimaat" een project gemaakt en voornamelijk de echte INTERNE onderwerpen en de onderwerpen die nog verder moeten onderzocht worden (verbruik statsec / E-peil) overgehouden

**Comment by Tine-VB** [comment]
Voor landbouw is alles wat enkel intern moet blijven staan (en dus niet extern staat) overgezet naar INTERN2. De rest is verwijderd.

**Comment by Tine-VB** [comment]
Voor Vlaams-Brabant zou dan alles in orde moeten zijn.

**Comment by StefanJacques** [comment]
> Onder Intern/Welvaart en armoede/Tegemoetkomingen/Ouderen/Zorgbudget voor ouderen met een zorgnood (vroeger THAB) vond ik THAB (niet meer geüpdatet), ik heb de map verplaatst naar Intern 2, maar ik weet niet of die data nog gebruikt wordt. Gedetailleerde data + kubus zorgbudget voor zwaar zorgbehoevenden verplaatst naar intern2

Karolien:
Nee, die gebruik ik idd niet meer, bestaat ook niet meer in die vorm. Dit heet nu zorgbudget voor ouderen met een zorgnood, ik denk dat Vera die wel opneemt? Mag m.i. intussen wel uitdoven/verwijderd worden.

**Comment by StefanieWVL** [comment]
Voor WVL in orde

**Comment by joostschouppe** [comment]
De opkuis is rond. Tijdens de finale opkuis nog dit:
- voor Project Demografie enkel nog de kwaliteitsmeting herkomst overgehouden
- de map met alles van EPB onder Project Wonen gezet
- de map Dashboard opgefrist met enkel hetgeen in Dashboard ook effectief gebruikt wordt
- volgorde: eerst Projecten, dan Thema's, dan technische mappen

Ik heb ook het bestand van hierboven er even aangevuld om het verschil te zien. Niet slecht, lang niet slecht!

![afbeelding](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/10122639/2406f8e0-0502-44ee-a012-fa27f69d8e8b)
