### ISSUE TITLE
Redesign landingspagina PinC Databank

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#386]
Wat moet er nog op staan? Wat mag weg? Hoe moet het er uit zien?
Drop je ideeën en voorbeelden hieronder.

**Comment by joostschouppe** [comment]
Voorbeeld Geel: https://geel.incijfers.be/jive

**Comment by joostschouppe** [comment]
Bekijk ook de relatie met https://provincies.incijfers.be/dashboard/dashboard/over-provincies-incijfers-be/ en https://provincies.incijfers.be/dashboard/dashboard/gebruik-van-de-website

**Comment by joostschouppe** [comment]
Redactiegroep 25/5
* iedereen verzamelt binnen team feedback over wat belangrijk is en/of hoe het eruit moet zien
* best integraal te bekijken met rol van pagina's ‘Over provincies in cijfers’ en ‘Gebruik van de website’

**Comment by Tine-VB** [comment]
Voorstel vanuit het team van Vlaams-Brabant:
[Startpagina PinC.pptx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/11849033/Startpagina.PinC.pptx)

**Comment by StefanieWVL** [comment]
Goed idee om zo met grote blokken op de startpagina te werken, maar 6 lijkt ons nog te veel. Naar de rapporten en naar het dashboard is misschien overbodig? Dat staat er al (bovenaan en in de themaboom).

**Comment by Tine-VB** [comment]
We kozen ervoor de drie grote 'onderdelen' van provincies.incijfers.be daar nog eens naast elkaar te zetten: databank, dashboard en rapporten.

**Comment by Tine-VB** [comment]
Is dit voorstel technisch mogelijk? Dat moet nog uitgezocht worden.

**Comment by veravandestraat** [comment]
OVL volgt WVL dat de verwijzing naar dashboard en rapporten niet noodzakelijk is. Indien het toch behouden blijft volgorde aanpassen, zodat de volgorde overeenkomt met de volgorde bovenaan, dus eerst dashboard dan databank dan rapporten. Suggestie om Start in de databank te veranderen in Naar de databank, zodat alle drie de tegels op dezelfde manier geformuleerd zijn.

Vraag om 'Hulp' te veranderen naar 'Heb je hulp nodig?'.

De meerwaarde van een tegel Data & Analyse wordt in vraag gesteld.

Bijkomende vraag gerelateerd aan de eerste opmerkingen: kan Rapporten toegevoegd worden aan balk bovenaan? Zodat de balk bovenaan zowel dashboard, databank als rapporten bevat.

**Comment by Tine-VB** [comment]
Enkele opmerkingen op de opmerkingen hierboven ;-).
- 'Start in de databank': graag behouden, want je bent al in de databank, dus het zou een beetje raar zijn om daar dan 'naar de databank' te zetten.
- De tegel Data & Analyse zou ik ook graag behouden. Zie ook slide 3 van de powerpoint. Ik zou graag de werking van Data & Analyse wat meer in de verf zetten en wat makkelijker 'bereikbaar' maken, en dus ook wat meer uitleg toevoegen aan de pagina met contactgegevens.
- Wat de drie producten/tegels betreft: het is inderdaad ook een oplossing om bovenaan rapporten toe te voegen, dan staan ze daar ook alle drie naast elkaar.

**Comment by HanneODB-VLBR** [comment]
Nog wat opmerkingen over de opmerkingen van de opmerkingen :-). Als we doen wat hierboven wordt gesuggereerd, staan onze inhoudelijke 'basisproducten' - databank, rapporten en dashboard - 'verstopt' in een klein balkje bovenaan, en komt de bijzaak - hulp nodig, nieuws, en info over data & analyse centraal op de pagina in grote tegels terecht. Ik zou dat niet doen. Als het aantal tegels beperkt moet worden, zou ik 'start in de databank', 'naar het dashboard' en 'naar de rapporten' in de tegels zetten en de rest in de balk bovenaan. Tot slot: zes tegels vind ik eigenlijk echt niet te veel, als ik kijk naar andere pagina's en bijvoorbeeld zelfs de landingspagina's van de provincies, dan staan daar nog veel meer tegels op. Maar goed, beperken tot drie tegels is wat mij betreft zeker ook ok.

**Comment by Lievendr** [comment]
Ik volg Hanne.
Vraag is of als je al in de databank komt/zit, naast effectief naar databank te gaan. nood hebt als gebruiker aan al die bijkomende tegels? Je kan ook enkel TERUG NAAR DASHBOARD-tegel maken, waar alles staat? Maar de link met Dashboard staat ook al bovenaan. 
"Nieuws" en "Data & Analyse" zijn dan misschien overbodig en niet op zijn plaats bij de databank-landingspagina.

**Comment by Tine-VB** [comment]
Als we "Nieuws" en "Data & Analyse" weglaten uit de startpagina van de databank, dan vind ik wel dat "Data & Analyse" een tegel zou moeten worden in het Dashboard ("Nieuws" staat daar al). Dat zou eigenlijk sowieso mogen...
Maar als we dat alles weglaten en overbodig vinden, waarom hebben we dan nog een landingspagina op de databank? 🤷‍♀️  Zelfs een "START" knop is niet nodig, want je kan gewoon een indicator beginnen aan te duiden in de themaboom links. Dus mijn conclusie: ofwel een leeg scherm, ofwel toch een tegeltje of 6 😜

**Comment by Lievendr** [comment]
idee van tegel D&A op dashboard volg ik.
We laten niet alles weg op landingspagina; maar pleidooi om enkel aan te bieden wat nuttig is als je databank wenst te gebruiken. Nieuws en D&A zijn dan minder relevant en kunnen er dus uit. Dit maakt dus nog steeds 4 tegels :-)
Maar kleuren en smaken verschillen, ik maak daar dus geen halszaak van.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
Oke om Geel te volgen, mits matuurdere icoontjes (WVL of VB kan dit uitwerken)

**Comment by StefanieWVL** [comment]
Aanvraag voor aanmaken icoontje contact is ingediend bij grafische dienst WVL

**Comment by Emilien-Dupont** [comment]
Redactiegroep 23/11
icoon moet nog aangepast worden. we wachten op de nieuwe viewer (release voorjaar) om verder te gaan met de landingspagina.

**Comment by StefanieWVL** [comment]
Hoi

Hier 3 voorstellen voor het icoontje contact.

[Icoontje_Contact.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/13485753/Icoontje_Contact.pdf)


Laat maar horen wat jullie ervan denken.

**Comment by Lievendr** [comment]
ik vind dat het middelste voorstel de lading het meeste dekt (manneke met microfoon).

**Comment by Emilien-Dupont** [comment]
Vul hier je voorkeur aan:

|Provincie| keuze|
|---|---|
| West-Vlaanderen | <ul><li>[ ] voorstel 1</li><li>[ ] voorstel 2</li> <li>[ ] voorstel 3 </li></ul> |
| Oost-Vlaanderen | <ul><li>[ ] voorstel 1</li><li>[ ] voorstel 2</li> <li>[ ] voorstel 3 </li></ul>
| Antwerpen | <ul><li>[ ] voorstel 1</li><li>[ ] voorstel 2</li> <li>[ ] voorstel 3 </li></ul>
| Vlaams-Brabant | <ul><li>[ ] voorstel 1</li><li>[ ] voorstel 2</li> <li>[ ] voorstel 3 </li></ul>
| Limburg | <ul><li>[ ] voorstel 1</li><li>[ ] voorstel 2</li> <li>[ ] voorstel 3 </li></ul>

**Comment by HanneODB-VLBR** [comment]
Vraag van VLBR: kan er niet worden gekozen voor het typische 'envelopje' dat e-mail indiceert?
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/74548582/620dd117-9186-4592-a805-4926901a1ecf)
De eerste twee voorgestelde iconen impliceren dat mensen ons kunnen telefoneren (wat niet echt het geval is), en het derde lijkt te sterk op het rapporten icoon.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 18/01/24:
Voorstander voor het voorstel van Hanne.
Stefanie vraagt aan de grafische dienst in WVL om een soortgelijk icoon te maken, in de stijl van de overige iconen.

**Comment by StefanieWVL** [comment]
Dag collega's

Hier de herwerkte icoontjes. Graag jullie feedback.

[Icoontje_Contact_2.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14328703/Icoontje_Contact_2.pdf)

[letter i_herwerkt.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14328706/letter.i_herwerkt.pdf)

**Comment by StefanieWVL** [comment]
Feedback van WVL zelf:

Icoontje contact is niet zo duidelijk. Kunnen ze geen combinatie maken met een envelop (voor mail) en een smartphone (ipv ouderwetse telefoon)?
Iets in de trant van dit: 
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/50832281/3d4c04f4-455a-4a83-998c-1e5922f47e68)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 20/02/24:
- Stefanie vraagt .png aan van i-icoon
- contact icoon voorstel WVL: voorstander eerste twee. Stefanie vraagt aan de grafische dienst om dit uit te werken in het blauw.

**Comment by StefanieWVL** [comment]
Dag collega's

Hier een aantal nieuwe voorstellen voor het contacticoontje.

[Icoontje_Contact_3.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14402502/Icoontje_Contact_3.pdf)

Laat maar weten wat jullie er van vinden en welke jullie voorkeur is.

**Comment by Emilien-Dupont** [comment]
Redactie:
icoon SDG en Contact (bovenste 2) zijn goed, mits aanpassing kleur blauw aan PinC-blauw.

**Comment by StefanieWVL** [comment]
Alle icoontjes werden aangepast zoals gevraagd en zijn nu in orde.

Hier een voorstel voor een icoontje "studies" waar we bv. de studie rond de uitrustingsgraad zouden zetten en ook een studie rond de kadasterdata (eigenaarsprofiel)
[240306_Icoontjes dashbord provincies in cijfers_studies.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14914400/240306_Icoontjes.dashbord.provincies.in.cijfers_studies.pdf)

Welk geniet jullie voorkeur?

**Comment by Lievendr** [comment]
het blauwe manneke "dat zijn gazet leest" :-)

**Comment by StefanieWVL** [comment]
> het blauwe manneke "dat zijn gazet leest" :-)

Er mankeert nog juist een koffie ;-)

**Comment by Emilien-Dupont** [comment]
Er is ook nog een icoon nodig voor Opleidingen (voor in het toekomstige dashboard). Nog te bekijken of er ook een icoon van in de voorstellen voor 'studies' hiervoor gebruikt kan worden.

**Comment by Tine-VB** [comment]
VLBR: blauw manneke met gazet voor de studies. Voor de opleidingen kan dat studentenhoedje wel.

**Comment by StefanieWVL** [comment]
Hier de voorstellen voor het icoontje opleiding

[240306_Icoontjes dashbord provincies in cijfers_opleiding_LR.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14988379/240306_Icoontjes.dashbord.provincies.in.cijfers_opleiding_LR.pdf)

**Comment by StefanieWVL** [comment]
Hier de nieuwe voorstellen voor de icoontjes studies en opleiding.

[240306_Icoontjes dashbord provincies in cijfers_studies_2.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/15040232/240306_Icoontjes.dashbord.provincies.in.cijfers_studies_2.pdf)

[240306_Icoontjes dashbord provincies in cijfers_opleiding_2.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/15040231/240306_Icoontjes.dashbord.provincies.in.cijfers_opleiding_2.pdf)

**Comment by Lievendr** [comment]
tweemaal derde optie :-)

**Comment by veravandestraat** [comment]
Eens met Lieven

**Comment by StefanJacques** [comment]
ook eens met Lieven en Vera

**Comment by Emilien-Dupont** [comment]
RG 23/05/24:
Derde opties zijn oke. Zeker de kleur en lijndikte nog eens controleren

**Comment by Emilien-Dupont** [comment]
In een poging om de landingspagina properder en minder rommelig te maken, heb ik hem gewoon weggelaten, zie de [bèta](https://beta-provincies.incijfers.be/admin/jive). ABF noemt hem 'kaal', ik noem hem 'minimalistisch strak' :).

Verder:
In de banner staat nu Dashboard | Rapporten | Databank | Over deze site | Contact
In 'Over deze site' staan nu nog twee tegels die eigenlijk dubbelop zijn:
- De contactgegevens zijn dubbelop is met de contactknop (die nu nog foutief verwijst naar een rapport maar binnenkort zal verwijzen naar [https://provincies.incijfers.be/dashboard/dashboard/contact](https://provincies.incijfers.be/dashboard/dashboard/contact). 
- Ook de tegel 'Wat heeft provincies.incijfers.be jou te bieden is dubbelop met de tegel ['Gebruik van de website'](https://provincies.incijfers.be/dashboard/dashboard/gebruik-van-de-website). 

Vandaar de volgende suggesties:
- Contactgevens en 'Wat heeft pinc jou te bieden' weghalen onder 'Over deze site'. De tegel ['Gebruik van de website'](https://provincies.incijfers.be/dashboard/dashboard/gebruik-van-de-website) zal dan nog aangevuld worden met informatie over de metadata.
- Onder 'Over deze site' zetten we dan onze hergebruiksvoorwaarden meer in de verf . 
Voorstel kan je zien op de [bèta versie](https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/over-provincies-incijfers-be). 

Bijkomende vraag:
Waar plaatsen we '[Achter de schermen van de databank](https://provincies.incijfers.be/databank/report/?id=achter_de_schermen)'?

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/09/24
Nieuwe landingspagina: 'Welkom bij Swing Viewer' veranderen naar: 'Welkom bij de Databank van de Vlaamse provincies'. Het deel met de blauwe knoppen behouden. 

Hergebruiksvoorwaarden nog licht herschrijven. 
Hergebruik van de data on der 'Bronnen' mag verwijzen naar de Hergebruiksvoorwaarden.

'Achter de schermen' mag in de algemene handleiding verwerkt worden.

**Comment by Emilien-Dupont** [comment]
- Herwerkte landingspagina: [https://beta-provincies.incijfers.be/admin/jive](https://beta-provincies.incijfers.be/admin/jive)
- Herwerkte hergebruiksvoorwaarden: [https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/over-provincies-incijfers-be](https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/over-provincies-incijfers-be)
- Hergebruik van de data onder Bronnen: [https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/bronnen](https://beta-provincies.incijfers.be/dashadmin/preview/dashboard/bronnen)
- Achter de schermen in de algemene inleiding: komt eraan.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
- herwerkte landingspagina: ok, extra 'de' nog verwijderen
- herwerkte hergebruiksvoorwaarden: nadenken hoe we dit in rapporten opnemen (wil je graag dit rapport of de data hieruit hergebruiken, klik dan hier op onze hergebruiksvoorwaarden), oke om hergebruiksvoorwaarden op te nemen mits ze ook goed staan in bronnentabel (Todo Emilien). Regel: altijd doorlinken naar de hergebruiksvoorwaarden.
- Achter de schermen in handleiding: ok.

**Comment by Emilien-Dupont** [comment]
Komende maandag zal de nieuwe landingspagina + hergebruiksvoorwaarden + herwerkte handleiding achter de schermen live staan. 

Aan handleiding Stories werd de rubriek 'Hergebruik van de data' toegevoegd met daaronder: 'Wil je onze dit rapport of onze data hergebruiken? Dat kan zeker! We wijzen je hierbij graag op onze [hergebruiksvoorwaarden](https://provincies.incijfers.be/dashboard/over-provincies-incijfers-be).'
