### ISSUE TITLE
Nakijken themaboom statsec en toegangsrechten statsec

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#388]
Ik heb nog eens de test gedaan of er consistentie is tussen wat we op statsec hebben, op dat niveau publiceren, toegankelijk maken en in het mapje “beschikbaar vanaf statistische sector” hebben staan. Dat bleek nodig! Op dit moment zijn er minstens 425 fouten.

In dit bestand https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/_layouts/15/doc2.aspx?action=edit&sourcedoc=%7B0348a1df-0a43-4316-b1c3-c3658a32c3d1%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1 kan je alles nakijken.

De belangrijkste filter is “type fout” (kolom I).
Er zijn drie opties, die je moet lezen als “het lijkt erop dat je dit moet doen”:
-	In themaboom statsec zetten (dus kopieer het onderwerp of een hele map van de hoofd-themaboom naar die op statsec)
-	De toegangsrechten aanpassen (dus voeg het onderwerp hier toe)
-	Uit themaboom statsec zwieren (want het heeft uberhaupt geen data op statsec)

Frequentieverdeling:

Verantwoordelijke | in themaboom statsec zetten | uit themaboom statsec zwieren | toegangsrechten aanpassen
-- | -- | -- | --
  | 2 |   | 13
AN_VB | 16 |   |  
IP_IP | 1 |   |  
IP_VB | 36 |   |  
LI_OV | 2 |   |  
LI_WV | 3 |   |  
OV_AN |   | 212 |  
OV_VB | 2 | 102 |  
VB(LAN)_WV(LAN) |   | 1 | 18
VB_AN | 1 | 15 | 2
VB_LI |   |   | 1
WV_OV | 10 |   |  
WV_VB | 21 |   |  
Eindtotaal | 94 | 331 | 34

Ik heb zelf al die met IP gedaan (euh… dat waren er wel wat) en die van kadaster.
Vera, ik zie ook nog een reeks van de 2532 zonder verantwoordelijke staan.

Er is ook een lijstje van gekende uitzonderingen (op het gelijknamige tabblad). Als je onderwerp heel speciaal is, kan je het daar dus toevoegen.
Doe verder geen aanpassingen in de excel zelf, maar geef gewoon een seintje als het in orde is. Na een update van de achterliggende gebruikte bestanden, zal deze excel zichzelf ook opkuisen.

Wat meer uitleg:
-	Gebruik Kolom C om je eigen werk te filteren
-	Kolom D: heeft de indicator uberhaupt data?
Er zijn 111 onderwerpen die geen data zouden hebben. Gelukkig slechts één dat extern staat (en dat blijkt dan nog een false positive te zijn). Maar deze gaan er liefst toch uit. Er zijn er ook een boel “gepland” bij, die kunnen wel blijven bestaan als ze er nog aankomen.

-	Kolom E zegt of een indicator data op statsec heeft.
-	Kolom F of een gastgebruiker deze data kan raadplegen.
Als er wél data is, maar je kan ze niét zien, dan is dat MISSCHIEN een keuze (maar het is vrij zeldzaam!)
Als er geen data is, maar ze staat wel in de toegangsgroep statsec, dan is dat voor beheer een beetje verwarrend, maar het kan op zich geen kwaad.

-	Kolom G zegt of ze in de themaboom bij Gebiedsniveaus staan. 
Als de data beschikbaar is en extern staat, dan moet het daar natuurlijk staan. Omgekeerd zijn er heel wat onderwerpen die wél in de themaboom statsec staan, maar helemaal geen data hebben op statsec! Dat gaat bijna uitsluitend over onderwijs-cijfers.

-	Kolom H zegt of het onderwerp uberhaupt extern staat. Natuurlijk hoeft het niet in de statsec map te staan als het niet extern staat.

**Comment by veravandestraat** [comment]
@EmielGrimonprez bekijk jij dit eens voor de indicatoren rond vroegtijdige schoolverlaters?

Verantwoordelijke is toegevoegd voor 2532 en ik heb de data extern gezet op statsec.

**Comment by VickyVB** [comment]
@veravandestraat @EmielGrimonprez 
Ik heb bij het herwerken van de onderwijsthemaboom, ten onrechte de dataloep en VSV-variabelen in de statsec themaboom gezwierd. Ik heb ze er ondertussen alle 330 uitgehaald dus dat is in orde.

**Comment by GeertBonte** [comment]
Voor West-Vlaanderen zijn de nodige aanpassingen uitgevoerd.

**Comment by Tine-VB** [comment]
VB(LAN)_WV(LAN) is in orde gezet.
Ik denk dat dan alles voor Vlaams-Brabant in orde zou moeten zijn.

**Comment by StefanJacques** [comment]
Limburg is normaal gezien ook in orde

**Comment by rudymarynissen** [comment]
Ook oké voor AN_VB
