### ISSUE TITLE
grafieken zonder link met data in PinC

### ISSUE THREAD

**Issue by demaesschalckfilip** [provinciesincijfers/PinC-taakopvolging#389]
In het nieuwe (nog te verschijnen) rapport detailhandel staan een aantal grafieken zonder link met data in PinC (het gaat om data over e-commerce die enkel op provinciaal, Vlaams of nationaal niveau beschikbaar zijn). De vraag was hoe daarmee om te gaan. Nu bleek dit ook in een aantal andere rapporten reeds het geval (bv. klimaat en energie, ouderenzorg). Daarom een voorstel tot minimale richtlijnen:
Voorstel 1: telkens expliciet vermelden (in de tekst en bij de bron) dat deze informatie niet in PinC staat,
Voorstel 2: de opmaak voldoende verschillend maken van de PinC-opmaak zodat duidelijk is dat het om een grafiek gaat die niet met PinC-data is gelinkt.

**Comment by karolienbloemen** [comment]
Ik ben gestart met een voorstel tot herwerken van het rapport ouderenzorg. Meer hierover volgt nog. Ik verwacht dat dit issue nadien niet meer van toepassing is voor dit rapport.

**Comment by joostschouppe** [comment]
Redactiegroep 25/5/2023
* Voorkeur om dit soort grafieken NIET in de huisstijl te zetten. We trekken dit door voor alle rapporten.  Dit kan op basis van de Excel hierboven.
* @Emilien-Dupont neemt dit op in het sjaboon.

**Comment by Emilien-Dupont** [comment]
Toegevoegd aan het sjabloon. Nog uit te rollen in rapporten waarin figuren met data zonder link met pinc zitten.

**Comment by davidcardinaels** [comment]
Wijkt grafiek 12.3 uit oa_hoofdstuk12_verdienen voldoende af van de huisstijl of moet deze ook aangepast worden?

**Comment by Emilien-Dupont** [comment]
Voor mij is het wel duidelijk zo

**Comment by davidcardinaels** [comment]
Dan is dit taakje in orde.
