### ISSUE TITLE
prognoses/voorlopige cijfers

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#39]
onder figuren met prognose-gegevens verschijnt automatisch de tekst "prognoses/voorlopige cijfers". 'Voorlopig' kan worden geïnterpreteerd als: deze cijferreeks zal nog aangepast worden. Niet helemaal correct dus. Kan dit aangepast naar "prognoses", of eventueel "prognoses/geschatte cijfers"?

**Comment by joostschouppe** [comment]
Ingeschoten bij ABF.

**Comment by joostschouppe** [comment]
Dit is niet mogelijk en is niet opgenomen als wens door ABF.
@Lievendr
