### ISSUE TITLE
Opfrissing en herwerking rapport kerncijfers

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#390]
Het [rapport kerncijfers](https://provincies.incijfers.be/databank/report/?id=omgevingsanalyse_steekkaart) is dringend aan een herwerking toe. Voor de grondige herwerking komen we in het najaar fysiek samen met de Redactiegroep. In het kerncijferrapport wordt al doorverwezen naar de Omgevingsanalyse voor meer duiding bij de cijfers. 

In de tussentijd willen we (1) nagaan of de thema's nog actueel zijn, en (2) of er nieuwe thema's toegevoegd moeten worden. Het gaat hierbij enkel om thema's die al over een rapport beschikken.

Als er indicatoren aangepast moeten worden binnen je thema, of als er een nieuw thema toegevoegd moet worden, geef dit dan door hieronder. 

Als je het hebt nagekeken voor jouw thema, mag je het aanvinken: 
- [x] Bevolking
- [x] Huishoudens
- [x] Arbeidsmarkt
- [x] Economie
- [x] Detailhandel
- [x] Basisonderwijs
- [x] Secundair onderwijs
- [x] Wonen
- [x] Klimaat
- [x] Landbouw
- [x] Criminaliteit
- [x] Verkeersveiligheid
- [x] Armoede
- [x] Ouderenzorg
- [x] Kinderopvang
- [x] Mobiliteit

(ik kan maar tien mensen assigneren, dus stuur gerust ook door binnen je team)

**Comment by HanneODB-VLBR** [comment]
Mobiliteit werd pas dit voorjaar toegevoegd, dus dit is nog actueel.

**Comment by StefanieWVL** [comment]
Was hier ook geen tweede vraag aangekoppeld namelijk hoe verhouden het rapport kerncijfers en de OA zich t.o.v. elkaar? (Hoe kunnen ze eventueel in elkaar geïntegreerd worden)?

**Comment by Emilien-Dupont** [comment]
Klopt, maar ik dacht dat we dat in het najaar in't echt gingen bespreken (beetje zoals bij de themaboom)

**Comment by StefanieWVL** [comment]
**Suggesties voor wonen:**
- bouwjaar > ook meest recente (= nieuwe) categorie opnemen m.n. gebouwd sinds 2021.
- VRAAG: toevoegen van "gebouwd/gewijzigd sinds ... "? concreet > 'gebouwd voor 1983 en geen wijzigingen', 'gebouwd en/of gewijzigd 2011-2020' en 'gebouwd en/of gewijzigd na 2021'.
- OF: bouwjaar vervangen door gebouwd en/of gewijzigd?

**Suggesties armoede:**
- toevoegen: onderconsumptie tandartsbezoek? of bij nieuw thema gezondheid?
> andere indicatoren die er nu staan hebben allen financiële link ...

**Nieuw thema: Gezondheid?**
indicatoren nu in rapport eerstelijnszones:

Gezondheidstoestand:
- chronische aandoeningen
- diabetes
- BEL-score
- Erkend persoon met handicap

Preventie:
- dekkingsgraad borstkankerscreening
- baarmoederhalskankerscreening
- darmkankerscreening
- preventieve mondzorg

Ik bekeek hiermee de thema's wonen en armoede. Maar ik kan de thema's hierboven niet afvinken omdat er nog andere indicatoren onder vallen die niet in het beheer van WVL zijn ...

**Indicatoren wonen, niet in beheer van WVL:**
- Opnemen energieprestatie?
- indicatoren premies, bouwvergunningen, ... zou ik persoonlijk niet opnemen

**Indicatoren armoede, niet in beheer WVL:**
toevoegen: achterstallig krediet en collectieve schuldvordering? Misschien ter vervanging van verhoogde tegemoetkoming jongeren en ouderen?  Om wat meer variatie hebben in de kernindicatoren?

**Comment by karolienbloemen** [comment]
Ouderenzorg mag zo behouden blijven. Ook in het rapport zelf dat momenteel herwerkt wordt, blijft deze grafiek zo behouden.

**Comment by Tine-VB** [comment]
Voorstel van de werkgroep landbouw:
1. Aantal bedrijven per km²
2. Verhouding beroepsmatige t.a.v. totaal aantal landbouwbedrijven. 
3. Afname (of toename?) percentage 2011-2021 van het aantal landbouwbedrijven.
4. Verhouding hoeveproducenten t.a.v. totaal aantal bedrijven.
5. Verhouding biologische landbouwbedrijven t.a.v. totaal aantal bedrijven.
6. opp. bestemming landbouw (t.o.v. totale opp. bestemmingen) 
7. geregistreerde oppervlakte landbouwgebruik (t.o.v. totale oppervlakte)
8. oppervlakte grasland geregistreerd binnen landbouw (t.o.v. totale oppervlakte)
9. oppervlakte akkerbouw (t.o.v. totale oppervlakte)
10. oppervlakte tuinbouw (t.o.v. totale oppervlakte)
11. Aantal runderen per km²
12. Aantal varkens per km²
13. Aantal kippen per km²

OPMERKINGEN:
- 3. is een afname/toename mogelijk in het kerncijferrapport?
- Het is begrijpelijk dat ze er cijfers over de dieren in willen (en niet enkel oppervlaktes), maar per km² is niet echt de beste indicator (vinden ze zelf ook eigenlijk).
- Dit is meer dan het maximum aantal indicatoren? Was dat 10?

**Comment by veravandestraat** [comment]
Voorstel voor kinderopvang:

- Opvangplaatsen B&P
- Opvangplaatsen B&P per 100 kinderen 0-2 jaar 
- Opvangplaatsen met inkomenstarief per 100 kinderen  
- Dringende opvangplaatsen 
- Opvanglocaties met pluskenmerk 
- Gebruik: % aanwezig in formele opvang 
- Opvangplaatsen BO 
- Opvangplaatsen BO per 100 kinderen 3-11 
- Opvangplaatsen BO met inkomenstarief per 100 kinderen

**Comment by Tine-VB** [comment]
Daar zitten een aantal absolute cijfers tussen. Is het niet eigen aan het kerncijferrapport dat er enkel relatieve cijfers mogen inzitten (zie ook landbouw probleem met de dieren)?

**Comment by veravandestraat** [comment]
> Daar zitten een aantal absolute cijfers tussen. Is het niet eigen aan het kerncijferrapport dat er enkel relatieve cijfers mogen inzitten? Zie ook landbouw: ik heb daar moeten kiezen voor runderen, varkens en kippen per km² ipv gewoon het absoluut aantal.

Oeps, zo te zien wel ja. Ik bekijk het nog eens met Emilien en schrap de absolute aantallen.

**Comment by demaesschalckfilip** [comment]
Voorstel voor detailhandel:

handelspanden per 1.000 inwoners | vp_1601_pand
leegstaande handelspanden (t.o.v. handelspanden) | vp1601_pand_leeg
leegstaande handelspanden: voorheen winkel (t.o.v. handelspanden) | vp1601_pand_v_winkel
leegstaande handelspanden: aanvangs- en frictieleegstand (incl. verbouw) (t.o.v. leegstand) | vp1601_pand_frictie_b
winkels per 1.000 inwoners | vp1601_pand_winkel_inwoner
WVO: winkels per 1.000 inwoners | vp1601_wvo_gevuld_inwoner
winkels: formule (t.o.v. winkels) | vp1601_pand_formulewinkel
winkels: dagelijkse goederen (t.o.v. winkels) | vp1601_pand_ff_dg
horecazaken per 1.000 inwoners | vp1601_pand_ffgroep_6_inw
WVO horeca per 1.000 inwoners | vp1601_wvo_horeca_inwoner

**Comment by valeriepirard** [comment]
Voorstel kerncijfers ‘Ruimte’ (nieuw)

Oppervlakte ruimtebeslag (t.o.v. totale oppervlakte) 
Oppervlakte open ruimte (t.o.v. totale oppervlakte) 
Oppervlakte niet-bebouwde of groene ruimte (t.o.v. totale oppervlakte) 
Oppervlakte niet-bebouwde of groene ruimte (t.o.v. oppervlakte ruimtebeslag) 
Oppervlakte verharding (t.o.v. totale oppervlakte) 
Oppervlakte verharding binnen ruimtebeslag (t.o.v. oppervlakte ruimtebeslag) 
Oppervlakte verharding in openruimtebestemmingen (t.o.v. totale oppervlakte bestemd voor open ruimte)_Nog aan te maken (staat op GIS-planning)_ 
Oppervlakte gebouwen (t.o.v. totale oppervlakte) 
Oppervlakte bebouwde percelen (t.o.v. totale oppervlakte) 
Oppervlakte toegankelijk wijkgroen (t.o.v. totale oppervlakte) 
Aantal inwoners in nabijheid van toegankelijk wijkgroen (t.o.v. totaal aantal inwoners)

**Comment by Emilien-Dupont** [comment]
RG 19/09:
Gezondheid nemen we erbij.
Iedereen bekijkt nog eens welke indicatorcodes bij welke indicatoren horen, zodat er zeker geen misverstanden ontstaan.
Stefan bekijkt dit met David en maakt dan iets in de beta (na 13/10) met de hoofdstructuur van de beta

**Comment by demaesschalckfilip** [comment]
Voorstel voor bevolking en voor huishoudens: 

0-17 jaar (t.o.v. inwoners) - vp1111a_0_17
65+ jaar (t.o.v. inwoners) - vp1111a_65_of_ouder
Gemiddelde leeftijd - v1111a_gemiddelde_leeftijd
levensverwachting - v1112_lv_t
Natuurlijke aangroei per 1.000 inwoners - vp1112_natuurlijk_saldo
migratiesaldo met een andere Belgische gemeente per1.000 inwoners - vp1112_mig_saldo_b
migratiesaldo met het buitenland per 1.000 inwoners - vp1112_mig_saldo_int
ander adres dan vorig jaar (t.o.v. inwoners) - vp1113a_verhuisd
Niet-Belgische huidige nationaliteit (t.o.v. inwoners) - vp1118a_niet_belg_nat
niet-Belgische herkomst (t.o.v. inwoners) - vp1116a_niet_belg_herk
0-24 jaar totaal niet-Belgische herkomst (t.o.v. 0-24 jaar) - vp1116a_nt_bel_herk_0_24

gemiddelde huishoudensgrootte - v1115a_gezinsgrootte
alleenwonend (t.o.v. private huishoudens) - vp1115a_alleenw
alleenwonend 65+ jaar (t.o.v. totaal 65+ jaar) - vp1115a_alleenw_65p
meerpersoonshuishoudens met minstens 1 minderjarig (LIPRO) kind (t.o.v. private huishoudens) - vp1115a_hh_minst_1_mind_k
eenoudergezin met min. 1 minderjarig (LIPRO) kind (t.o.v. huish. met min. 1 minderj. (LIPRO) kind) - vp1115a_eenoudergezin_kind_min18

Ik zou wel hier en daar de naam van de variabele aanpassen/vereenvoudigen, zeker bij huishoudens.

**Comment by demaesschalckfilip** [comment]
Voorstel voor basisonderwijs en secundair onderwijs:

Leerlingen basisonderwijs met een laag opgeleide moeder (t.o.v. lln BO) – WP - vp2301_rkopleidingmoeder_1
Leerlingen basisonderwijs die een schooltoelage ontvangen (t.o.v. lln BO) – WP - vp2301_rktoelage_1
Leerlingen basisonderwijs die thuis geen Nederlands spreken (t.o.v. lln BO) – WP - vp2301_rktaal_1
Indicatorleerlingen basisonderwijs (t.o.v. lln BO) – WP - vp2301_indicator_basis
uitstroom lln basisonderwijs (t.o.v. lln die hier wonen) - vp2303_bo_uitstroom
instroom lln basisonderwijs (t.o.v. lln die hier naar school gaan) - vp2303_bo_instroom

leerlingen BuSO - WP (t.o.v. leerlingen secundair onderwijs) - vp2301_buso_lln
leerlingen GSO A-stroom (t.o.v. lln 1ste graad) – WP - vp2301_gsoa_lln
leerlingen ASO - WP (t.o.v. leerlingen 2e+3e graad) - vp2301_aso_lln
leerlingen secundair onderwijs met een laag opgeleide moeder (t.o.v. lln SO) – WP - vp2301_so_rkopleidingmoeder_1
leerlingen secundair onderwijs die een schooltoeslag ontvangen (t.o.v. lln SO) – WP - vp2301_so_rktoelage_1
leerlingen secundair onderwijs die thuis geen Nederlands spreken (t.o.v. lln SO) – WP - vp2301_so_rktaal_1
leerlingen secundair onderwijs met twee jaar of meer schoolse vertraging (t.o.v. lln SO) – WP - vp2301_so_sv_2plus
vroegtijdige schoolverlaters (t.o.v. schoolverlaters) – WP - vp2360_vsv_w
uitstroom lln secundair onderwijs (t.o.v. lln die hier wonen) - vp2303_so_uitstroom
instroom lln secundair onderwijs (t.o.v. lln die hier naar school gaan) - vp2303_so_instroom

Eventueel kunnen deze indicatoren samengevoegd worden onder de titel 'leerplichtonderwijs' (het aantal indicatoren is teruggebracht tot 16 - evenveel als er waren bij enkel secundair onderwijs), om dan een nieuw thema 'hoger onderwijs' toe te voegen.

**Comment by VickyVB** [comment]
Arbeidsmarkt
% inwoners op beroepsactieve leeftijd (15-64): vp1111a_15_64
Activiteitsgraad: v1202_activiteitsgraad_t
Werkzaamheidsgraad: vp1202_werkzaamheidsgraad_20_64
Werkzoekendengraad: vp1321_wzgraad
Spanningsratio: vp1341_wzw
Jobratio: v1403_jobratio_15_bijberoep
Loontrekkendengraad: vp1204_lt_graad
Ondernemersgraad: v1202_ondernemersgraad
+verwijzing naar het dashboard arbeidsmarkt (ipv werken)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
op korte termijn:
- we passen de namen aan in de omgevingsanalyse zodat deze overeenkomen met de themaboom
- we passen het rapport kerncijfers aan zodat deze dezelfde structuur heeft als de themaboom

lange termijn:
- we passen de volgorde aan van de thema's in de omgevinsganalyse zodat deze overeenkomen met de themaboom

**Comment by VickyVB** [comment]
**Economische activiteit**
Oprichtingsratio: vp1402_oprichtingsratio
Stopzettingsratio: vp1402_uittredingsratio
Investeringsintensiteit: vp1401_quote
Vestigingen minder dan 50 werknemers (t.o.v. alle vestigingen met personeel): vp1204_ve_max50
Vestigingen 200 of meer werknemers (t.o.v. alle vestigingen met personeel): vp1204_ve_min200
Vestigingen in bouw en industrie (t.o.v. alle vestigingen met personeel): vp1204_ve_bouwindustrie
Vestigingen in commerciële diensten (t.o.v. alle vestigingen met personeel): vp1204_ve_com_diensten
Vestigingen in niet-commerciële diensten (t.o.v. alle vestigingen met personeel): vp1204_ve_ntcom_diensten

**Comment by StefanJacques** [comment]
> **Economische activiteit** Oprichtingsratio: vp1402_oprichtingsratio Stopzettingsratio: vp1402_uittredingsratio Investeringsintensiteit: vp1401_quote Vestigingen minder dan 50 werknemers (t.o.v. alle vestigingen met personeel): vp1204_ve_max50 Vestigingen 200 of meer werknemers (t.o.v. alle vestigingen met personeel): vp1204_ve_min200 Vestigingen in bouw en industrie (t.o.v. alle vestigingen met personeel): vp1204_ve_bouwindustrie Vestigingen in commerciële diensten (t.o.v. alle vestigingen met personeel): vp1204_ve_com_diensten Vestigingen in niet-commerciële diensten (t.o.v. alle vestigingen met personeel): vp1204_ve_ntcom_diensten

@VickyVB
zouden we deze mee opnemen ? Investeringsintensiteit: vp1401_quote
is enkel vanaf arr.niveau en dus niet zichtbaar in het rapport ?

**Comment by StefanJacques** [comment]
> Daar zitten een aantal absolute cijfers tussen. Is het niet eigen aan het kerncijferrapport dat er enkel relatieve cijfers mogen inzitten? Zie ook landbouw: ik heb daar moeten kiezen voor runderen, varkens en kippen per km² ipv gewoon het absoluut aantal.

zouden we die runderen, varkens en kippen per km² ook niet best achterwege laten ?
de provinciale staven zijn -zeker- voor varkens en kippen véél te groot, waardoor de andere indicatoren in de profielstaafgrafiek verloren gaan.
https://provincies.incijfers.be/databank?workspace_guid=807cec53-8063-4ba2-a6e4-28e823267e56

**Comment by VickyVB** [comment]
Nee inderdaad, de investeringsintensteit mag eruit.

**Comment by Tine-VB** [comment]
> @Tine-VB zouden we die runderen, varkens en kippen per km² ook niet best achterwege laten ? de provinciale staven zijn -zeker- voor varkens en kippen véél te groot, waardoor de andere indicatoren in de profielstaafgrafiek verloren gaan. https://provincies.incijfers.be/databank?workspace_guid=807cec53-8063-4ba2-a6e4-28e823267e56

Ja, doe maar Stefan. Het is wel spijtig dat er dan weer niets van de dieren inzit. Als je een andere manier weet om het relatief voor te stellen?

**Comment by StefanJacques** [comment]
@Tine-VB 

enige mogelijkheid, die ik bedenk,  is het opsplitsen van
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/e1edf717-7847-4f18-92a1-0d8da38a97b3)

en

https://provincies.incijfers.be/databank?workspace_guid=3fc3938f-b3aa-4337-aa8b-2e6e6e13b6dd

hierdoor komen de bovenste indicatoren alleszins goed tot hun recht ... en belichten we ook de dieren ?

**Comment by StefanJacques** [comment]
> Voorstel voor detailhandel:
> 
> handelspanden per 1.000 inwoners | vp_1601_pand leegstaande handelspanden (t.o.v. handelspanden) | vp1601_pand_leeg leegstaande handelspanden: voorheen winkel (t.o.v. handelspanden) | vp1601_pand_v_winkel leegstaande handelspanden: aanvangs- en frictieleegstand (incl. verbouw) (t.o.v. leegstand) | vp1601_pand_frictie_b winkels per 1.000 inwoners | vp1601_pand_winkel_inwoner WVO: winkels per 1.000 inwoners | vp1601_wvo_gevuld_inwoner winkels: formule (t.o.v. winkels) | vp1601_pand_formulewinkel winkels: dagelijkse goederen (t.o.v. winkels) | vp1601_pand_ff_dg horecazaken per 1.000 inwoners | vp1601_pand_ffgroep_6_inw WVO horeca per 1.000 inwoners | vp1601_wvo_horeca_inwoner

@demaesschalckfilip 
ook hier passen
WVO: winkels per 1.000 inwoners | vp1601_wvo_gevuld_inwoner 
WVO horeca per 1.000 inwoners | vp1601_wvo_horeca_inwoner 
niet in het rijtje

--> zie onderste twee indicatoren als we ze zouden toevoegen aan "kerncijfers"
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/34b6d8af-24f5-4ba3-ada5-b679243f53a5)


dus ook best weglaten ?

**Comment by Tine-VB** [comment]
> enige mogelijkheid, die ik bedenk, is het opsplitsen 
> hierdoor komen de bovenste indicatoren alleszins goed tot hun recht ... en belichten we ook de dieren ?

Als dat mag... dan vind ik dat OK :-)

**Comment by StefanJacques** [comment]
Voorstel van [aangepast kerncijfers rapport](https://provincies.incijfers.be/admin/jive/Report/Edit/rgdidlklhijghf) mag gecontroleerd worden.

- Inhoudstafel afgestemd op themaboom
- voorgestelde indicatoren opgenomen
- teksten onder grafieken eenvormig gemaakt
- in online versie worden de subthema's per hoofdthema samengehouden - in de pdf-versie verschijnt subthema per bladzijde

**Gelieve eigen thema's nog eens na te kijken.**
Als er geen opmerkingen meer zijn, plaatsen we deze versie online.

**Comment by StefanJacques** [comment]
Nog verder te bekijken:

1
Eventueel kunnen deze _(basisonderwijs - secundair onderwijs)_ indicatoren samengevoegd worden onder de titel 'leerplichtonderwijs' (het aantal indicatoren is teruggebracht tot 16 - evenveel als er waren bij enkel secundair onderwijs), om dan een nieuw thema 'hoger onderwijs' toe te voegen.
Kunnen we doen als het rapport "Hoger Onderwijs" en bijhorende indicatoren zijn toegevoegd.

2
https://github.com/provinciesincijfers/PinC-taakopvolging/issues/390#issuecomment-1724936623
gelieve door **verantwoordelijke armoede** (opnieuw) te bekijken

3
https://github.com/provinciesincijfers/PinC-taakopvolging/issues/390#issuecomment-1589063376
gelieve door **verantwoordelijken armoede/wonen** te bekijken

**Comment by StefanJacques** [comment]
**@StefanieWVL : vul jij de onderwerpcodes aan ? dankjewel !**

Nieuw thema: Gezondheid?
indicatoren nu in rapport eerstelijnszones:

Gezondheidstoestand:
chronische aandoeningen
diabetes
BEL-score
Erkend persoon met handicap

Preventie:
dekkingsgraad borstkankerscreening
baarmoederhalskankerscreening
darmkankerscreening
preventieve mondzorg

zal zijn plaats nog krijgen tussen
Armoede
en
Kinderopvang

**Comment by JoLocquet** [comment]
@StefanJacques @Tine-VB zou inderdaad jammer zijn mochten 'aantal dieren' niet in het kerncijferrapport opgenomen kunnen worden

**Comment by StefanieWVL** [comment]
@StefanJacques 

Dag Stefan

Ik heb de onderwerpcodes aangevuld zoals gevraagd (zie hoger). 

Voor het thema wonen had ik graag nog het onderwerp "gebouwd na 2011" toegevoegd gezien > vp2201_geb_na2011

Merci!

**Comment by dgees** [comment]
waarom staat er bij sommige vette koppen een jaartal en bij andere niet?

**Comment by dgees** [comment]
**OPGELET: op provincies.incijfers.be worden gegevens van rond de jaarwissel steeds op het meest recente jaar gezet. Zowel momentopnames van 31/12/2019 als van 1/1/2020 worden weergegeven als "2020". Op andere plaatsen waar je de gegevens van Kind & Gezin kunt aantreffen, zal dit meestal weergegeven worden als 2019.**

Krijgt dit ook niet best eens een update van de jaartallen?

**Comment by dgees** [comment]
Gezelschapsdieren en Toerisme, vrije tijd, erfgoed eventueel toe te voegen?

**Comment by Tine-VB** [comment]
> **OPGELET: op provincies.incijfers.be worden gegevens van rond de jaarwissel steeds op het meest recente jaar gezet. Zowel momentopnames van 31/12/2019 als van 1/1/2020 worden weergegeven als "2020". Op andere plaatsen waar je de gegevens van Kind & Gezin kunt aantreffen, zal dit meestal weergegeven worden als 2019.**
> 
> Krijgt dit ook niet best eens een update van de jaartallen? En is het hier nog Kind en Gezin of Opgroeien dat we moeten vermelden?

Off topic, maar ook de voetnoot hierover mag wel wat duidelijker :-): 
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/61458346/179369d7-f0db-413d-9e5b-c11098bb28cd)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 23/11:
het mag extern geplaatst worden.
