### ISSUE TITLE
herwerking thema ouderenzorg

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#391]
Het rapport ouderenzorg is toe aan een actualisatie. Ik maakte een aanzet obv het huidige rapport. Graag verzamel ik jullie feedback hierop, het makkelijkst in het [document ](https://vlbr.sharepoint.com/:b:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Ruwe%20data/Agentschap%20Zorg%20%26%20Gezondheid/Ouderenzorg/2023%20herwerking%20thema%20ouderenzorg/20230517_Rapport%20ouderenzorg.pdf?csf=1&web=1&e=iedYMZ) zelf denk ik? (teams>ruwe en verwerkte data>agentschap zorg en gezondheid>ouderenzorg>2023_herwerking...).

Ik doe ook graag enkele voorstellen naar vereenvoudiging van onderwerpen: zie de [tabel ](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Ruwe%20data/Agentschap%20Zorg%20%26%20Gezondheid/Ouderenzorg/2023%20herwerking%20thema%20ouderenzorg/Item%20usage_01-05-2022_15-05-2023_onderwerpen%20ouderen.xlsx?d=w0d8f2b5984064b97a32bb4469971d4d9&csf=1&web=1&e=GZA5nJ) op dezelfde locatie in teams. In kolom E het aantal keer dat een item is opgevraagd; in kolom F is aangegeven welke onderwerpen in het rapport gebruikt worden; kolom G bevat enkele opmerkingen en vragen van mijn kant, alsook welke m.i. uitdovend gemaakt mogen worden. Graag verzamel ik eventuele bemerkingen van jullie in kolom H.

Vul je hieronder aan wanneer je het hebt doorgenomen en feedback hebt gegeven?

**Comment by karolienbloemen** [comment]
Dank voor de feedback - deze is intussen verwerkt (nieuwe versie van de pdf met alle verzamelde aanpassingen is op teams te vinden.

Had ook al iemand naar de tabel kunnen kijken met hierin enkele voorstellen rond de onderwerpen (bv kubussen ouderenzorgaanbod worden uitdovend aangezien die blijkbaar niet (meer) gebruikt worden....). Zie hierboven voor de link naar deze tabel in teams. Graag in kolom H feedback of akkoord.

**Comment by davidcardinaels** [comment]
De nieuwe versie van het rapport mag nagekeken worden: 
https://provincies.incijfers.be/admin/jive?report=rapport_ouderenzorg_herwerking.

**Comment by Tine-VB** [comment]
- Voor grafiek 1 zou ik voorstellen om ofwel een vergelijking te maken met provincie/gewest (https://provincies.incijfers.be/databank?workspace_guid=be3deae7-9c9a-4577-9904-644c4f737251) ofwel de absolute cijfers weer te geven (https://provincies.incijfers.be/databank?workspace_guid=6ca8974e-c4a8-4f69-8b56-1db1c5a27924). Uit de huidige grafiek kan je niet veel afleiden, vind ik.
- Bij tabel 6 eventueel ook de absolute cijfers zetten (opsplitsing thuiszorg - residentiële zorg)? Of dit kan eventueel al opgesplitst worden in grafiek 3, maar deze indicatoren zitten op dit moment niet in de databank. Ook aangeven bij Tabel 6 dat het hier gaat over alle zwaar zorgbehoevenden en niet enkel de ouderen.
- Bij 1.4 staat deze zin: "De toename van het zorggebruik met hoge(re) leeftijd, en de toename van het aantal ouderen, impliceren een sterke toename van het aantal zwaar zorgbehoevende ouderen in Aalst." Dat klopt eigenlijk niet met het beeld op de grafiek (voor Aalst): bij mantel- en thuiszorg neemt het aantal zwaar zorgbehoevenden af en zelfs bij residentiële zorg is het stabiel sinds 2019. Dus misschien best een beetje anders formuleren? 
- Grafiek 6: ik zou de titel als volgt aanpassen: Gepresteerde uren dienstencheques per gebruiker van 65 of 80 jaar en ouder, en per inwoner van 65 of 80 jaar en ouder (2020), in plaats van met haakjes te werken.
- Bij de woonzorgcentra kan je misschien toch bekijken in welke mate de programmatie gehaald wordt of niet. Of anders toch zeker ook een kaartje of cijfer geven van de plaatsen per 80-plussers. In WZC zitten bijna geen bewoners die jonger zijn dan 80. Dus om een inschatting te maken of de huidige situatie de nood al dekt of niet, is dit wel belangrijk. Ik dacht ook aan een link erbij naar de pagina van de erkenningskalender, zodat lokale besturen kunnen opzoeken of er nog bijkomende plaatsen gepland zijn en tegen wanneer, maar die vind ik helaas niet meer terug...
- Bij 3.1 zou ik deze zin weglaten (staat daar zo wat verloren bij): Betaalbaarheid van de zorg blijft een belangrijk aandachtspunt.
- 4. Huisvesting van doelgroepen, kan dat niet hernoemd worden naar 'Sociale huisvesting voor ouderen'? Eventueel ook percentages huurders en kandidaat-huurders van 60+toevoegen?

PS ik heb enkel inhoudelijk nagekeken, geen combinaties van vergelijkingsgebieden e.d. getest.

**Comment by Tine-VB** [comment]
Nog een kleintje: onder 1.1 opent het rapport in hetzelfde tabblad.

**Comment by karolienbloemen** [comment]
Feedback van Tine wordt verwerkt in het rapport, vervolgens klaar om online het oude rapport ouderenzorg te vervangen.

Wat de onderwerpen betreft: obv feedback zullen een aantal oude reeksen in dit thema uitdovend worden (het betreft vooral onderwerpen die enkel intern stonden en al lange tijd niet meer werden opgevraagd): 
- tegemoetkoming hulp aan bejaarden (v3502_thab ...)
- 2 interne kubussen zorgaanbod woongelegenheden en gebouwen
- rvt in woonzorgcentra (v3505_rvt ...)
- thuiszorg: een aantal interne detailonderwerpen (v3506_dgz_u_m) [de kubus blijft intern beschikbaar]
- zorgzwaarte naar leeftijd (o.a. v3504_tv_gz_a_65_74)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10
Het rapport zal deze vrijdag gepubliceerd worden.
