### ISSUE TITLE
Gebruik van vet in rapporten

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#394]
### Kerncijfers en gebieden

In het [sjabloon afspraken](https://provincies.incijfers.be/databank/report/?id=sjabloon_grafiekstijl) staat het volgende:

> We zetten dynamisch bevraagde kerncijfers (met eenheid %) en de naam van de gebieden in het rapport systematisch in vet.

Bij een snelle check van verschillende rapporten blijkt dat dit niet altijd correct toegepast wordt en dat het op verschillende manieren geïnterpreteerd wordt.

In de meeste rapporten staan de kerncijfers (inclusief het %-teken), de gekozen gebieden en de vergelijkingsgebieden inderdaad vet, maar niet altijd: bv. in het [rapport landbouw](https://provincies.incijfers.be/databank/report/?id=rapport_landbouw) staan de cijfers niet vet; in het [rapport klimaat](https://provincies.incijfers.be/databank/report/?id=rapport_klimaat) staat het gekozen gebied vet maar het vergelijkingsgebied niet altijd.

Verder staan volgende zaken in sommige rapporten vet, in andere niet:

* jaartallen (bv. vet in [rapport wonen](https://provincies.incijfers.be/databank/report/?id=rapport_wonen), niet vet in andere rapporten)
* eenheden (bv. euro, ha, km², MWh, ton, ...) bij de kerncijfers (bv. meestal vet in [rapport klimaat](https://provincies.incijfers.be/databank/report/?id=rapport_klimaat), niet vet in [rapport klimaatadaptatie](https://provincies.incijfers.be/databank/report/?id=rapport_adaptatiemaatregelen))

Omwille van de uniformiteit zou duidelijker vastgelegd moeten worden wat wel en niet vet moet. Eenmaal we over duidelijke afspraken beschikken, kunnen de bestaande rapporten waar nodig aangepast worden.

### Kernwoorden

Daarnaast wordt vet soms ook gebruikt om bepaalde begrippen of kernwoorden te benadrukken, maar daarover zijn er geen afspraken. Soms worden dergelijke begrippen en kernwoorden niet vet, maar cursief geplaatst (bv. [rapport arbeidsmarkt](https://provincies.incijfers.be/databank/report?id=rapport_arbeidsmarkt)). Dan springen ze echter veel minder goed in het oog.

In de managementssamenvatting voor de omgevingsanalyse, die momenteel geprogrammeerd wordt, staan heel veel kerncijfers dicht op elkaar en wordt er dus veelvuldig gebruik gemaakt van vet. Tegelijkertijd bevat deze tekst ook heel wat kernwoorden. Op die manier ontstaat er een overvloed aan vette tekst, waardoor de kernwoorden ook niet meer echt opvallen. Daarom een voorstel om in dit specifieke geval de kernwoorden niet enkel vet maar ook in kleur te zetten, bijvoorbeeld in hetzelfde blauw dat ook voor het logo van Provincies in Cijfers gebruikt wordt.

Voorbeeld:

![voorbeeld_vet_kleur](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/101627698/9df92297-844b-426f-ba9f-d418919308e6)

**Comment by StefanieWVL** [comment]
misschien de lijn dan doortrekken en kernwoorden steeds ook in kleur zetten? Hoe minder specifieke gevallen, hoe liever ;-)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/06:

Vet wordt niet consequent toegepast. Als het wel toegepast wordt, kan het wel heel veel vet worden. Verduidelijken wat exact wel en niet in vet moet. Suggestie om kernwoorden of “belangrijke opmerkingen” vet en met een kleur kijken. 

Is het überhaupt nodig om de gebieden en de cijfers in vet te zetten?  

Tegen volgende keer even nadenken over wat we nu eigenlijk best in vet zetten. Elke provincie bekijkt de eigen rapporten.  

% schrijven we (tegen de spellingregels) vast aan het cijfer (toe te voegen in sjabloon) 

De aangepaste kleur is misschien niet nodig in gewone rapporten, maar wel in de managementsamenvatting van de omgevingsanalyse. De kleur blauw wijkt voldoende af van de kleur van linken.

**Comment by GeertBonte** [comment]
> % schrijven we (tegen de spellingregels) vast aan het cijfer

Een kleine toelichting: https://www.vlaanderen.be/team-taaladvies/taaladviezen/procentteken-spatie

**Comment by davidcardinaels** [comment]
% vast aan het cijfer is nu in orde in alle rapporten.

**Comment by StefanieWVL** [comment]
Voor rapport wonen
[Vet in rapport wonen.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/12519699/Vet.in.rapport.wonen.docx)

**Comment by StefanJacques** [comment]
Limburg stelt voor:

- akkoord om gebieden in de leeswijzer in het vet te zetten (zie voorstel Stefanie)
- minimalistisch gebruik van vet in de teksten (dus zeker geen aantallen en eenheden meer in het vet, dat leidt de aandacht alleen maar af van de inhoud) of bv. als in de titel van een paragraaf een indicator wordt vermeld, moet die niet meer in het vet worden getoond in de paragraaf zelf
- in een rapport met 2 gemeenten mogen die 2 gemeenten WEL in het vet

**Comment by demaesschalckfilip** [comment]
Vlaams-Brabant stelt voor: er staat niets meer standaard in het vet. Alleen dingen die we willen benadrukken kunnen in het vet gezet worden.

**Comment by StefanieWVL** [comment]
> Voor rapport wonen [Vet in rapport wonen.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/12519699/Vet.in.rapport.wonen.docx)

WVL volgt Vlaams-Brabant en Limburg met geen/minimalistisch gebruik van vet (m.u.v. leeswijzer). Bijlage is enkel voorstel voor leidraad als er toch voor gekozen zou worden om dingen in het vet te zetten.

**Comment by Emilien-Dupont** [comment]
RG 19/09/'23:
minimalistisch gebruik van vet, enkel wanneer iets benadrukt moet worden. De verantwoordelijke(n) van het rapport bepaalt/bepalen wat in het vet moet. Behalve in de leeswijzer. Kleurtjes zijn niet meer nodig.
Iedereen bekijkt dit voor hun eigen rapport.

**Comment by Lievendr** [comment]
Rapport Landbouw is ontvet.

**Comment by Lievendr** [comment]
Rapport Mobiliteit is ontvet

**Comment by Emilien-Dupont** [comment]
Rapport opvang is ontvet en ook het sjabloon werd aangepast

**Comment by VickyVB** [comment]
Rapport bevolking en huishoudens,
Rapport onderwijs,
Rapport arbeidsmarkt en
Rapport detailhandel zijn ontvet.
Moeten de rapporten uit de omgevingsanalyse ook (individueel) ontvet worden of gebeurt dit samen?

**Comment by GeertBonte** [comment]
> Moeten de rapporten uit de omgevingsanalyse ook (individueel) ontvet worden of gebeurt dit samen?

Ik denk dat alle hoofdstukken van de omgevingsanalyse best in één keer ontvet worden. Als je ze individueel doet en sommige hoofdstukken zijn al aangepast en andere nog niet, dan kan het voor de gebruiker wat vreemd zijn, of op zijn minst een slordige indruk maken.

**Comment by GeertBonte** [comment]
Rapport kerncijfers voor buurtgerichte zorg,
Rapport kerncijfers voor eerstelijnszones,
Rapport nationaliteit en herkomst en
Rapport wonen zijn ontvet.

**Comment by davidcardinaels** [comment]
Rapport klimaat,
Rapport klimaatscenario's,
Rapport klimaatadaptatie,
Rapport veiligheid,
Rapport ouderenzorg,
Rapport ruimte en
omgevingsanalyse zijn ontvet.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
Geert stuurt de West-Vlaamse versie door van de omgevingsanalyse om na te gaan of er zaken niet terug 'vet' moeten worden die we willen benadrukken.

**Comment by Lievendr** [comment]
Blijkt geen probleem te zijn. Enkel gemeente/provincie en cijfers stonden in vet. (alvast in Landbouw en Werk).

**Comment by Emilien-Dupont** [comment]
Idem voor Natuur

**Comment by Emilien-Dupont** [comment]
Redactiegroep 23/11
Tegen de volgende redactiegroep  bekijkt iedereen het eigen hoofdstuk uit de omgevingsanalyse.

**Comment by GeertBonte** [comment]
Hoofdstukken 1, 2, 4 en 12 waren oké, ik heb niets moeten aanpassen.
