### ISSUE TITLE
Combinatie natuurbeheerplannen met andere GIS-lagen

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#396]
In overleg met leefmilieu Antwerpen werd gevraagd of het mogelijk is om een aantal indicatoren toe te voegen onder thema Natuur waarbij een combinatie gemaakt wordt tussen de natuurbeheerplannen en de onderstaande GIS-lagen om % opp. te bepalen dat beheerd wordt in een beheerplan:
- groene gewestplanbestemming (ruimteboekhouding)
- VEN
- speciale beschermingszones Natura 2000
- openbare bossen
- eigendommen openbare besturen met groene bestemming (momenteel nog niet opgenomen in PinC)

Indien OK voor redactiegroep zou de verwerking gevraagd worden aan GIS Antwerpen.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 15/06: geen bezwaren
