### ISSUE TITLE
streekplatformen: rapport en startrapport

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/PinC-taakopvolging#398]
in de themaboom bij gebiedsindelingen staat een (start)rapport voor de streekplatformen. deze zijn ooit opgemaakt in het kader van het versterkt streekbeleid.
dit bestaat niet meer, dus de namen van de streekplatformen zijn achterhaald.
ik kreeg de vraag van collega's streekwerkers of 

- we de namen kunnen aanpassen
- en ook de gebieden opnieuw kunnen samenstellen.

voor WVL wil men graag de referentieregio's als gebiedsindeling (maar wel met de naam 'streekwerking') , alsook eentje voor alle kustgemeenten. 

het lijkt me wenselijk dat voor elke provincie de naamgeving en de afbakening van het gebied (welke gemeenten horen samen) eerst herbekeken wordt. 
kunnen jullie dat eens bekijken aub, en de indeling voor de eigen provincie toevoegen?

**Comment by joostschouppe** [comment]
Als de streekplatformen niet meer bestaan, moet dat ding dan niet gewoon weg?
En is je vraag dan niet gewoon voor een nieuw startrapportje?
Wie een startrapport wil voor een bestaande gebiedsindeling, heeft die dan niet gewoon nog niet het knopje "informatie over" op een specifiek gebied ontdekt?

**Comment by Tine-VB** [comment]
Met dat 'knopje' bedoelen jullie toch gewoon rechtermuisklik, hé? Want anders ken ik dat 'knopje' ook niet, hoor.
