### ISSUE TITLE
Aanpassen korte bron-naam: PinC ipv provincies.incijfers.be

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#402]
Dit voorstel kwam van... Vicky, denk ik?
Voordeel is niet alleen dat de korte naam van de bron dan ook effectief korter is, maar ook dat we op die manier de afkorting PinC wat meer in voege doen gaan

**Comment by Tine-VB** [comment]
Ik ben persoonlijk niet zo'n voorstander: provincies.incijfers.be geeft meteen ook de webpagina weer. Ik probeer in communicatie net altijd de volledige naam te gebruiken, en niet PinC. Dat gebruik ik eigenlijk enkel in interne verslaggeving.

**Comment by Tine-VB** [comment]
Er blijkt een probleem te zijn dat de korte bronnaam te weinig karakters telt om sommige bronnen correct weer te geven (zie bezwaren vanuit Steunpunt Werk). Als dan de oplossing is om PinC te gebruiken ga ik hiermee wel akkoord. Als PinC zo wat meer in voege komt dan PIC is dat ook mooi meegenomen ;-). Maar verder pleit ik ervoor om in communicatie zoveel mogelijk voluit provincies.incijfers.be te gebruiken. Puntje te bespreken op de werkgroep communicatie?

**Comment by Emilien-Dupont** [comment]
RG 19/09/'23:
als er genoeg plaats is, mag het voluit geschreven worden, anders mag er PinC gebruikt worden. 
Emilien polst bij Richard of de domeinnaam pinc.be aangekocht kan worden (net zoals de 'provincie.incijfers.be'. We kunnen dit waarschijnlijk zelf ook aankopen, maar het zou makkelijker zijn moest het in de licentie kunnen.
