### ISSUE TITLE
gelabelde kleuteropvang

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#405]
Net als bij opvang voor baby's en peuters bestonden er binnen de buitenschoolse kinderopvang tot vorig jaar drie categorieën van opvang:
- gezinsopvang
- groepsopvang
- groepsopvang samenwerking

Sinds 2022 (2023 in onze data) is groepsopvang vervangen door gelabelde kleuteropvang. 
Op mijn vraag om kleuteropvang te verduidelijken krijg ik vanuit Opgroeien de volgende reactie: 'Kleuteropvang richt zich bij voorrang tot kinderen die naar de kleuterschool gaan, maar staat ook open voor kinderen uit de basisschool. Bestaande initiatieven zijn gewoon overgezet. Die gingen ook ruimer dan enkel kleuters.'

Als ik de tijdsreeks bekijk lijkt het puur een naamswijziging en dat leid ik ook af uit 'bestaande initiatieven zijn gewoon overgezet'. Om de historiek niet te verliezen zou dat mogelijk een reden zijn om enkel de naam te wijzigen van groepsopvang naar kleuteropvang, maar [op de website van Opgroeien](https://www.opgroeien.be/kennis/cijfers-en-onderzoek/kinderopvang-schoolkinderen/cijfers-op-maat) zelf stopt de tijdsreeks van groepsopvang en wordt er in 2022 een nieuwe indicator kleuteropvang gelanceerd. 

Het lijkt me ook wat vreemd om met terugwerkende kracht de groepsopvang uit 2014 plots kleuteropvang te noemen, terwijl dat een term was die toen nog niet gebruikt werd. Ik vermoed daarom dat we best de bron volgen en een nieuwe indicator kleuteropvang toevoegen, maar wilde dit graag ter goedkeuring voorleggen aan de redactiegroep.

**Comment by Emilien-Dupont** [comment]
RG 19/09/'23
Bij Opgroeien nagaan of het ook al een inhoudelijke verandering inhoudt en nagaan waarom ze zelf voor een andere indicator kiezen (Vera). 
Als het inhoudelijk verandert, dan twee aparte reeksen. 
Voorkeur om de bron te volgen.

**Comment by veravandestraat** [comment]
Reactie Opgroeien:
Sinds 2021 is er een nieuw decreet buitenschoolse opvang en activiteiten van kracht gegaan, waarbij de regierol verschoven wordt van het Vlaamse niveau naar het lokale niveau.
Voor de buitenschoolse opvangvoorzieningen impliceert dit dat zij vanaf 1/1/2022 automatisch overgaan naar gelabelde kleuteropvang: de groepsopvang en **gezinsopvang met een erkenning of attest van toezicht** (IBO, BOKDV; LODIB, ZOO, ZBO) gaan allemaal automatisch over naar gelabelde kleuteropvang. Alleen voor vakantieopvang gebeurt geen automatische omschakeling.  

Meer info: [https://www.opgroeien.be/over-opgroeien/projecten/buitenschoolse-opvang-en-activiteiten/wat-betekent-boa-voor-partners](https://secure-web.cisco.com/1pGu54N-CHKn16Mkp9x76gZaedi2FwCLzV2A_zC708meEhop_MK3LuDFfjtDnPZBsmJSkvKZ_JyC0taoY1T-4XBQh7QNl_10leDWrs4BfmWtf1kqrIl9E-S1InKz1Vpm84L-3P-ezuGJH-ZF94muUoWjSPK9GMIP0jY6QGHToD4s6VyqRuIR8F93gytnSVPhxy5537s6ICq2n6ap3kS85fMucDp1IIxBYWQXZdCqqnZH1bnX44TAMCDNXDiSkID2Aee-4LkTO66fzOCTq4c10xS4VgHV1nVvZblMzBk-Ec4nQ0ayJBIZzLNRRhbQf1Q-Y/https%3A%2F%2Fwww.opgroeien.be%2Fover-opgroeien%2Fprojecten%2Fbuitenschoolse-opvang-en-activiteiten%2Fwat-betekent-boa-voor-partners)

In de praktijk betekent het dat op dit moment groepsopvang grotendeels maar niet volledig overgezet is naar gelabelde kleuteropvang. Vakantieopvang krijgt enkel een kwaliteitslabel kleuteropvang indien ze dit aanvragen en de aanvraag goedgekeurd wordt. Het is echter ook een deel van gezinsopvang dat (op termijn) zal veranderen in gelabelde kleuteropvang. Vasthouden aan de oude indicatoren is dus niet mogelijk. Ik heb een indicator gelabelde kleuteropvang en bijbehorende ratio en percentage toegevoegd aan de themaboom.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
We volgen Opgroeien en maken een nieuwe indeling. De oude laten we staan. In de metadatafiche geven we meer duiding.
