### ISSUE TITLE
Groenaanbod op statistische sectorniveau

### ISSUE THREAD

**Issue by Tanja-OVL** [provinciesincijfers/PinC-taakopvolging#406]
Oppervlakte buurtgroen, wijkgroen, stadsdeelgroen, stadsgroen en stadsbos werd per statistische sector ingeladen in PinC voor de jaren 2013, 2016 en 2019. Staat momenteel nog onder Intern > Thema buurtgroen. 
Nieuwe metadatafiche, (reeds nagekeken door Tine) is gebaseerd op de fiche die Valerie maakte voor de data op gemeenteniveau.
•	er werden nieuwe indicatoren aangemaakt: v2540_buurtgroen_opp_statsec, enz
•	oppervlakte werd uitgedrukt in m² (ipv in are op gemeenteniveau (cijfers ABB))
•	voor de berekening van het percentage ten opzichte van de totale oppervlakte werd gebruik gemaakt van v9900_opp_m2.

zie ook https://github.com/provinciesincijfers/data-wishlist/issues/55

Valerie zou deze data willen controleren.
Kan redactiegroep akkoord gaan om deze cijfers, na controle, extern te plaatsen?

**Comment by demaesschalckfilip** [comment]
Als ik het goed begrijp, is het verschil tussen de categorieën (buurtgroen, wijkgroen, stadsdeelgroen, stadsgroen, stadsbos) louter de totale oppervlakte van de 'groeneenheid' (is dat dan het 'groengebied' of de 'groencluster' of is dat hetzelfde?), en behoren de grotere categorieën automatisch tot de kleinere: zo is stadsbos ook stadsgroen, stadsdeelgroen, wijkgroen en buurtgroen, maar is buurtgroen geen van de andere categorieën. Ik zou dat ook in de infofiche schrijven.

**Comment by Emilien-Dupont** [comment]
RG 19/09/'23:
Vraag tot verheldering + check of de data geloofwaardig zijn op statsec niveau (Valerie)

**Comment by Tanja-OVL** [comment]
Vraag is gekomen van lokale besturen, willen data over groen in de buurt in kader van buurtwerking.
Ik zal metadatafiche herbekijken en aanvullen waar mogelijk.

**Comment by Tanja-OVL** [comment]
Fiche aangepast, onder meer met opmerkingen Filip. 
Zowel op gemeenteniveau (reeds vroeger ingeladen reeksen) als op statsec niveau zijn er soms grote verschillen vast te stellen tussen de 3 jaren (2013, 2016, 2019). De mogelijke redenen die VITO hiervoor opgeeft, heb ik ook bijgevoegd in de metadatafiche.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
Tine leest nog eens na, en dan mag het extern geplaatst worden

**Comment by veravandestraat** [comment]
Ik kreeg van een collega volgende vraag:
_Ik ben voor de opmaak van het hitteplan van Lokeren op zoek naar een optelsom van alle toegankelijk groen in Lokeren per statistische sector (buurtgroen, wijkgroen, stadsdeelgroen, stadsbos enz). Ik vind dit “Intern” terug maar enkel apart per statistische sector en niet opgeteld. Ik heb echter de optelsom nodig. Zouden jullie dat kunnen voorzien in PinC?_

Is het mogelijk om die cijfers op te tellen? En zo ja, kan dat voorzien worden in PinC?

**Comment by demaesschalckfilip** [comment]
Het verschil tussen de categorieën (buurtgroen, wijkgroen, stadsdeelgroen, stadsgroen, stadsbos) is louter de totale oppervlakte, en de grotere categorieën behoren automatisch tot de kleinere: zo is stadsbos ook stadsgroen, stadsdeelgroen, wijkgroen en buurtgroen, maar is buurtgroen geen van de andere categorieën. Dat zou ook in de infofiche moeten staan, maar die blijkt nog niet vervangen. Buurtgroen is dus al een optelsom.  Zie de comment hierboven van 7 augustus. 

Overigens kan je deze cijfers wel vinden op gemeenteniveau op PinC? Percentueel staan ze extern: https://provincies.incijfers.be/databank?workspace_guid=25601fc4-d03d-4019-9265-b45f084dcb41. In absolute cijfers blijken ze intern te staan: https://provincies.incijfers.be/databank?workspace_guid=93dab86e-2b28-4ee7-a74d-643c267c34ea

**Comment by Tanja-OVL** [comment]
Infofiche is wel reeds vervangen voor wat betreft de data op statsec-niveau. Daar staat ook de uitleg in zoals Filip hierboven meegeeft.

**Comment by Tanja-OVL** [comment]
@Valerie: werd deze data ondertussen gecontroleerd?

**Comment by veravandestraat** [comment]
Ik had de infofiche bekeken, maar ik haalde het er niet uit. Ik zie nu dat ik er overgelezen heb (of dat ik het op de vroege morgen niet begreep):  _De geselecteerde clusters met een hoger functieniveau zijn dus steeds een deelverzameling van de geselecteerde clusters van een lager functieniveau. Opgelet, door de toegepaste methode bestaat het groentype ‘stadsbos’ niet enkel uit bos, maar uit verschillende types groene ruimte._

Misschien moeten we het nog iets concreter opschrijven?
Voorstel: Opgelet, door de toegepaste methode bestaat het groentype ‘stadsbos’ dus niet enkel uit bos, maar ook uit buurtgroen, wijkgroen en stadsdeelgroen.

**Comment by Tine-VB** [comment]
Ik ging die fiche nog eens nalezen, sorry, nog niet gebeurd. Zal ik dat eerst nog doen voor er een nieuwe versie online wordt gezet?

**Comment by Tanja-OVL** [comment]
graag!

**Comment by valeriepirard** [comment]
> @valerie: werd deze data ondertussen gecontroleerd?

Tanja, ziet er ok uit. Ik merk wel dat waar de oppervlaktes "0" zijn er bij jou "geen waarde" is ingevuld. In de datareeks van de Gemeente- en Stadsmonitor staan die op "0".
