### ISSUE TITLE
Rapporten opvragen met URL-parameters - rapport kerncijfers

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#407]
Er is een probleem bij het rapport [kerncijfers](https://provincies.incijfers.be/databank/report/?id=omgevingsanalyse_steekkaart) (omgevingsanalyse_steekkaart) voor wat betreft het opgeven van een vergelijkingsgebied via een URL-parameter.

### Inleiding

In **Achter de schermen van de Databank** wordt in het stukje **Rapporten opvragen met URL parameters** uitgelegd hoe je URL-parameters kunt gebruiken om een gebied en een vergelijkingsgebied op te geven. Er staat o.a. het volgende:

> In Rapporten kan je enkel de gebieden en vergelijkingsgebieden instellen. Binnen provincies.incijfers.be gebruiken we "input_geo" voor de gebiedsselectie, en "input_compare" voor de gebiedsvergelijking.

Een voorbeeld van hoe dit werkt: volgende URL brengt je naar het rapport wonen voor de gemeente Brugge, met als vergelijkingsgebied de provincie West-vlaanderen:

[`https://provincies.incijfers.be/databank/report/?id=rapport_wonen&input_geo=gemeente_31005,&input_compare=provincie_30000`](https://provincies.incijfers.be/databank/report/?id=rapport_wonen&input_geo=gemeente_31005,&input_compare=provincie_30000)

Hierin worden volgende parameters gebruikt om het gebied (Brugge) en het vergelijkingsgebied (West-Vlaanderen) op te geven:

`input_geo=gemeente_31005`\
`input_compare=provincie_30000`

*Het is belangrijk te beseffen dat de namen van de gebruikte parameters in de URL (`input_geo` en `input_compare`) overeenstemmen met de namen van de variabelen die in het rapport gebruikt worden.* Bovenstaande URL werkt dus alleen maar omdat er in het rapport het volgende staat:

```
#
input_geo = input { ... }
input_compare = input { ... }
#
```

In theorie zou je hier ook andere namen kunnen kiezen, maar we hebben afgesproken dat we bij de rapporten op PinC *altijd* deze namen gebruiken. Zo’n afspraak is van belang om ervoor te zorgen dat dezelfde URL-parameters gebruikt kunnen worden bij *alle* rapporten.

### Rapport kerncijfers

Bij de [kerncijfers](https://provincies.incijfers.be/databank/report/?id=omgevingsanalyse_steekkaart) (omgevingsanalyse_steekkaart) blijkt echter `input_compare_sel` gebruikt te zijn in plaats van `input_compare`:

```
#
input_geo = input { ... }
input_compare_sel = input { ... }
#
```

Daardoor werkt het opgeven van het vergelijkingsgebied via de URL niet zoals verwacht. Wie ‘Achter de schermen’ gelezen heeft en denkt het vergelijkingsgebied (zoals voor alle andere rapporten) te kunnen opgeven met `&input_compare=...` is eraan voor de moeite. Dit zal bij de kerncijfers niet werken omdat er geen input-variabele is met die naam.

Als je in de URL een parameter opgeeft die niet herkend wordt, dan wordt die door de software genegeerd. Je krijgt verder geen foutmelding, maar het gevolg is dat het standaardvergelijkingsgebied gebruikt zal worden in plaats van het vergelijkingsgebied dat je in de URL hebt opgegeven.

Om voor de kerncijfers een vergelijkingsgebied te kunnen opgeven via een URL-parameter, moet je dus voor dit rapport uitzonderlijk `&input_compare_sel=` gebruiken! Als je dat niet weet, dan kun je voor dit rapport het vergelijkingsgebied niet opgeven via de URL. In de praktijk weet uiteraard geen enkele gebruiker dat, want je moet in de broncode kijken om te zien welke variabele er gebruikt werd. Gebruikers die al vertrouwd zijn met URL-parameters, zullen `&input_compare=` gebruiken en teleurgesteld zijn dat dit niet werkt.

Ook programmeurs van andere rapporten, die vanuit hun eigen rapport naar het rapport kerncijfers willen linken met behoud van vergelijkingsgebied, zullen dat dus niet op de gebruikelijke manier kunnen doen en zullen zich wellicht afvragen waarom dat niet werkt.

- [x] **Wil de programmeur van het rapport kerncijfers dit aanpassen, zodat dit terug werkt zoals verwacht? Het rapport moet opvraagbaar zijn met `&input_compare=` en het gewenste vergelijkingsgebied in de URL.**

### Bijkomende nuttige info

Toen ik **Achter de schermen van de Databank** las, dacht ik aanvankelijk dat de URL-parameters ingebakken waren in de software en dus altijd werkten voor alle rapporten. Ik kwam er echter al snel achter dat dat *niet* het geval is, en dat de namen van die URL-parameters eigenlijk de namen zijn van de inputvariabelen die je in de programmacode van je rapport gebruikt hebt. Dus stel dat je in de code `abc = input { ... }` zou gebruiken (wat we uiteraard niet doen, dit is maar een voorbeeld), dan zou je de betreffende input (gebied, vergelijkingsgebied of iets anders) in de URL kunnen opgeven met `&abc=`.

Een rapport dat naast gebied en vergelijkingsgebied ook andere inputs gebruikt, is het rapport klimaat en energie (rapport_klimaat). Bij dat rapport kun je in de URL ook het referentiejaar opgeven (met `&input_year=`), en kun je daarnaast ook opgeven of je het rapport met of zonder CO₂-uitstoot op snelwegen wil zien (met `&input_snelwegen=`), bijvoorbeeld:

[`https://provincies.incijfers.be/databank/report/?id=rapport_klimaat&input_geo=gemeente_71022,&input_compare=provincie_70000&input_year=2012&input_snelwegen=fake_switch_2`](https://provincies.incijfers.be/databank/report/?id=rapport_klimaat&input_geo=gemeente_71022,&input_compare=provincie_70000&input_year=2012&input_snelwegen=fake_switch_2)

Hiermee wordt het rapport opgevraagd voor de gemeente Hasselt, met als vergelijkingsgebied de provincie Limburg, als referentiejaar 2012 en zonder CO₂-uitstoot op snelwegen.

Een doorsneegebruiker kan bovenstaande URL onmogelijk zelf samenstellen. Daar is immers *insider information* voor nodig: je moet weten dat de variabelen `input_year` en `input_snelwegen` gebruikt werden, en dat voor de snelwegen gebruik gemaakt werd van een fake gebiedsniveau met gebiedsniveaucode `fake_switch` en bijbehorende gebiedscodes `1` (met snelwegen) en `2` (zonder snelwegen)...

Ik denk dat het rapport klimaat en energie voorlopig het enige rapport is waarvoor een referentiejaar opgegeven kan worden. De programmeur heeft ervoor gekozen om daarbij `input_year` te gebruiken als naam van de inputvariabele.

- [x] **Wellicht is het een goed idee om dat in de afspraken op te nemen, zodat bij eventuele toekomstige rapporten altijd dezelfde variabele (en dus dezelfde URL-parameter) gebruikt wordt om een jaartal op te geven.**

**Comment by davidcardinaels** [comment]
@GeertBonte, wat werkt er niet goed aan het rapport kerncijfers? In het rapport kerncijfers wordt ook gebruik gemaakt van input_compare. Jouw URL werkt ook : https://provincies.incijfers.be/databank/report/?id=omgevingsanalyse_steekkaart&input_geo=gemeente_73001,&input_compare=provincie_70001.

**Comment by GeertBonte** [comment]
@davidcardinaels: met de provincie als vergelijkingsgebied *lijkt* het toevallig wel te werken, omdat de provincie het default vergelijkingsgebied is (wanneer het rapport opgevraagd wordt voor een gemeente).

In de broncode van het rapport staat het volgende:

```
if subgemeentelijk=true 
   then temp_compare = gemeente._99999
else if Equal(code(gebiedsniveau),"provincie") 
   then temp_compare = gewest._99999
else
   temp_compare = provincie._99999
end if

input_compare_sel = input
{
    Type: GeoItem;
    Caption: "Keuze vergelijkingsgebied";
    Instruction: "Kies vergelijkingsgebied";
    Subset: parents(input_geo);
    Default: temp_compare;
    Min: 1;
    Max: 1;
}
```

Zoals je in bovenstaande code ziet, wordt in dit rapport niet `input_compare = input { ... }` gebruikt, maar wel `input_compare_sel = input { ... }`.

De naam van de variabele die je gebruikt (hier dus `input_compare_sel`) is per definitie ook de naam van de querystringparameter die je in de URL moet gebruiken.

Als je een URL gebruikt met `&input_compare=provincie_70001`, dan zal dit door Swing volledig genegeerd worden, aangezien er in het rapport geen `input` staat die aan de variabele `input_compare` wordt toegewezen. In dat geval is `input_compare` geen geldige querystringparameter meer.

Als je ongeldige querystringparameters gebruikt, krijg je geen foutmelding, maar dit wordt gewoon genegeerd. Deze URL is dus gelijkwaardig met een URL zonder `&input_compare`, en in dat geval wordt het default vergelijkingsgebied getoond, hier dus de provincie Limburg.

Probeer het eens uit met een ander vergelijkingsgebied, bijvoorbeeld het gewest. Om het rapport kerncijfers op te vragen voor de gemeente Alken met als vergelijkingsgebied het Vlaams Gewest, zou je volgende URL moeten kunnen gebruiken:

https://provincies.incijfers.be/databank/report/?id=omgevingsanalyse_steekkaart&input_geo=gemeente_73001&input_compare=gewest_2000

Als je op bovenstaande URL klikt, zul je echter zien dat dit niet werkt. In plaats van het Vlaams Gewest krijg je de provincie Limburg als vergelijkingsgebied. Dat komt doordat de `&input_compare=` genegeerd wordt en je het default vergelijkingsgebied voorgeschoteld krijgt.

Met deze URL lukt het wél:

https://provincies.incijfers.be/databank/report/?id=omgevingsanalyse_steekkaart&input_geo=gemeente_73001&input_compare_sel=gewest_2000

Met deze URL krijg je nu inderdaad het Vlaams Gewest als vergelijkingsgebied. Dat komt doordat `&input_compare_sel=` herkend wordt, aangezien je in de broncode van het rapport `input_compare_sel = input { ... }` gebruikt hebt (in plaats van `input_compare = input { ... }`).

Voor zover ik kan zien is het rapport kerncijfers het enige rapport waar dat zo is. Gebruikers kunnen dat natuurlijk niet weten en verwachten dat ze, net als voor de andere rapporten, `&input_compare=` in de URL kunnen gebruiken om gelijk welk vergelijkingsgebied te kiezen, zoals uitgelegd staat in [Achter de schermen](https://provincies.incijfers.be/databank/report/?id=achter_de_schermen).

*N.B.:* verderop in het rapport gebruik wordt inderdaad `input_compare` gebruikt, maar dan als een ‘gewone’ variabele die volledig losstaat van de `input`:

```
if count=2 then
    input_geo_sel = item(input_geo, 0) 
    input_compare = item(input_geo, 1) 
else if vergelijkingsgebied_ok=1 then
    input_geo_sel = input_geo
    input_compare = input_compare_sel
else
    input_geo_sel = input_geo
    input_compare = gewest._2000
end if
```

Het probleem kan opgelost worden door in de broncode overal `input_compare` en `input_compare_sel` om te wisselen.

**Comment by davidcardinaels** [comment]
Bedankt voor de uitleg, @GeertBonte. Het rapport is aangepast.

**Comment by GeertBonte** [comment]
Dank je wel voor de aanpassing, @davidcardinaels.
