### ISSUE TITLE
Kandidaat-huurders bij SHM – niet te lokaliseren

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#408]
De bestanden met ruwe data die we ontvangen voor de kandidaat-huurders bij sociale huisvestingsmaatschappijen bevatten gegevens over de kandidaat-huurders naar domiciliegemeente. De meerderheid van de kandidaat-huurders hebben een Vlaamse of Brusselse domiciliegemeente, maar er zijn er ook enkelen uit Waalse gemeenten. Bovendien bevatten de bestanden ook nog een record 'Onbekend' met gegevens over kandidaat-huurders van wie de domiciliegemeente niet gekend is.

In voorgaande jaren gingen we hier als volgt mee om:

- de records met Waalse gemeenten werden genegeerd;
- de aantallen bij ‘Onbekend’ werden toegekend aan gebiedscode 99999 (‘Niet te lokaliseren’).
 
De gebiedscode 99999 betekende aanvankelijk ‘Niet te lokaliseren’. Sinds enige tijd is dat echter gewijzigd naar ‘Buiten Vlaanderen en Brussel’. – Zie issue [Wijzigen naam "gebied onbekend" · Issue #370 · provinciesincijfers/PinC-taakopvolging](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/370).
 
Momenteel hebben we in PinC volgende drie speciale gebiedscodes voor het gebiedsniveau ‘gemeente’:
 
- 99991: ‘Niet te lokaliseren – Vlaanderen’
- 99992: ‘Niet te lokaliseren – Brussel’
- 99999: ‘Buiten Vlaanderen en Brussel’

De cijfers die in de bestanden vermeld staan bij ‘Onbekend’ kunnen we niet toewijzen aan één van bovenstaande codes. Het gaat om kandidaat-huurders bij Vlaamse SHM’s, van wie de domiciliegemeente niet gekend is. We hebben dus geen idee of die mensen in Vlaanderen, in Brussel of daarbuiten (in Wallonië) gedomicilieerd zijn. De vlag ‘Niet te lokaliseren’ dekte nog enigszins de lading, maar ‘Buiten Vlaanderen en Brussel’ doet dat niet meer. Als we die aantallen niet willen negeren, zouden we ze dus opnieuw moeten kunnen toekennen aan een gebied ‘Niet te lokaliseren’, zoals vroeger het geval was.
 
Onder ‘Buiten Vlaanderen en Brussel’ kunnen nu we wel het totaal opnemen van alle kandidaat-huurders die in de bestanden bij een Waalse domiciliegemeente vermeld staan. Van die huurders weten we immers dat ze niet in Vlaanderen en ook niet in Brussel gedomicilieerd zijn.

Concreet hebben we dus eigenlijk niet drie, maar vier speciale gebiedscodes nodig. Ons (eerste) voorstel is het volgende:

- 99991: ‘Niet te lokaliseren – Vlaanderen’
- 99992: ‘Niet te lokaliseren – Brussel’
- 99993: ‘Buiten Vlaanderen en Brussel’
- 99999: ‘Niet te lokaliseren’

Met andere woorden: terug naar de toestand van vroeger, maar met een extra code 99993 voor ‘Buiten Vlaanderen en Brussel’.

Een tweede mogelijkheid (misschien beter en het minste werk om voor alle gebiedsniveaus aan te passen) is om de huidige toestand te behouden, maar met een extra code 99993 voor ‘Niet te lokaliseren’:

- 99991: ‘Niet te lokaliseren – Vlaanderen’
- 99992: ‘Niet te lokaliseren – Brussel’
- 99993: ‘Niet te lokaliseren’
- 99999: ‘Buiten Vlaanderen en Brussel’

Naar welk van deze twee mogelijkheden gaat de voorkeur van de redactieraad uit? Welk van deze mogelijkheden heeft de minste impact op andere datasets? Heeft het zin dit ook bij andere gebiedsniveaus aan te passen, of volstaat het dit enkel te doen voor het gebiedsniveau ‘gemeente’?

**Comment by HanneODB-VLBR** [comment]
De naamsverandering had onder meer te maken met stroomdata woon-werkverkeer, waarbij er heel wat mensen vanuit Wallonië in een Brusselse/Vlaamse gemeente gaan werken. Als je die onder 'gebied onbekend' plaatst, komt dat heel vreemd over:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/74548582/8e7e04dc-03d6-4acc-b116-58c5cfddfd6a)

Ik zou daarom eerder opteren voor de tweede optie, en een nieuwe 'niet te lokaliseren' toevoegen met nieuwe code.

**Comment by demaesschalckfilip** [comment]
Ik volg Hanne. Zowel bij onderwijs als bij migraties weten we dat het om Wallonie gaat. gebied onbekend is dan geen goede benaming.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/09:
Akoord met tweede mogelijkheid. Emilien neemt dit mee in de volgende verwerking van de gebiedsniveaus (december). Daarna kan iedereen kijken in welke missingscategorie hun data vallen.

**Comment by Emilien-Dupont** [comment]
Stefan had gevraagd of het mogelijk was om na te gaan voor welke onderwerpen de speciale gebiedscodes voor missings gebruikt worden (99991, 99992, 99999). Ik heb dit nagevraagd bij abf, en zij lieten weten dat er in de Studio geen (data)record wordt gemaakt per geoitem, maar alleen per geolevel. Dit wil zeggen dat als je de data van onbekende gebieden wilt bekijken, je het hele niveau waar deze gebieden in staan, moet exporteren. 

Je kan dit doen door:
https://provincies.incijfers.be/admin/studio/Table?tableName=GeoData 
https://provincies.incijfers.be/admin/studio/Table?tableName=GeoDataCube

te openen en te filtereren op de indicator die je wilt onderzoeken... of je kan in de uploadfiles zelf gaan kijken. Maar er is dus jammer genoeg geen shortcut.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/12:
Vanaf gemeenteniveau Niet te lokaliseren toevoegen

**Comment by Emilien-Dupont** [comment]
99993 - Niet te lokaliseren werd toegevoegd vanaf gemeenteniveau (08/02/24). Later zal deze code ook subgemeentelijk toegevoegd worden.
