### ISSUE TITLE
aanpassing werkingsgebieden woonmaatschappijen

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/PinC-taakopvolging#410]
in juni werden de laatste beslissingen ivm de werkingsgebieden woonmaatschappijen genomen. in Oost-Vlaanderen is er alvast een wijziging (Vlaamse Ardennen wordt 1 maatschappij)

De kaart is de indeling zoals op 23 juni goedgekeurd.
[Vorming_woonmaatschappijen_20230623_ntqpzt (1).pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/12521774/Vorming_woonmaatschappijen_20230623_ntqpzt.1.pdf)

Ik kreeg van Eric Tjampens (wonen OVL) ook de vraag om de namen van de woonmaatschappijen aan te passen in PinC.
Maar wat doen we met de naamgeving? Bv dender-midden heet nu Stek92
Waasland midden heet nu WoonST
Werkingsgebied Gent-zuid wordt Dimensa

Een vraagje om over te beslissen: houden we de bestaande namen van de gebiedsindeling, of geven we aan de gebiedsindeling de naam van de betreffende woonmaatschappij?
De namen van de woonmaatschappijen staan niet op de kaart met de werkingsgebieden. Als we opteren voor de namen van de woonmaatschappijen, dan moeten we wel nog een rondvraag doen in elke provincie.

**Comment by Tine-VB** [comment]
Op de website van Vlaanderen worden overal nog de werkingsgebieden gebruikt (bijv. https://www.vlaanderen.be/lokaal-woonbeleid/woonmaatschappijen), dus ik zou deze namen (zeker voorlopig) behouden. Voorstel van Filip: de namen van de woonmaatschappijen er aan toevoegen, als tekstvariabele, zoals ook de NIS-code aan een gebied is toegekend? Of zoals bij project detailhandel, daar heeft Filip een gegevenstype tekst aan toegekend: 'Inventarisatiedatum Locatus': https://provincies.incijfers.be/databank?workspace_guid=a35818a8-1fdd-41af-bd49-a4d229256f1d. Zou dit mogelijk zijn?

**Comment by GeertBonte** [comment]
Aangezien de meeste gebruikers veel meer vertrouwd zijn met de namen van de werkingsgebieden zoals ze nu in PinC zitten en zoals ze ook op de kaart staan, zou ik die in elk geval behouden. Het is inderdaad een prima idee om daarnaast een tekstvariabele te maken met de nieuwe namen van de woonmaatschappijen. Op die manier kun je ook altijd de naam van de maatschappij opzoeken als je de naam van het werkingsgebied kent.

Een andere mogelijkheid is de gebiedsnamen aanpassen naar de huidige gebiedsnaam met tussen haakjes de naam van de nieuwe woonmaatschappij. Bijvoorbeeld: "Gent-Zuid" wordt dan "Gent-Zuid (Dimensa)" – of misschien zelfs omgekeerd: "Dimensa (Gent-Zuid)", dus zoals we nu doen voor deelgemeenten, waar we de naam van de bijbehorende gemeente tussen haakjes vermelden, of voor statistische sectoren, waar we de sectorcode tussen haakjes zetten.

Daarnaast is er nóg een mogelijkheid: in Studio kan voor elk gebied zowel een naam als een korte naam opgegeven worden. We doen dit nu ook voor statistische sectoren en deelgemeenten, bv. korte naam: "Bosdorp", naam: "Bosdorp (46024A11-)", of korte naam: "Sint-Andries", naam: "Sint-Andries (Brugge)". We zouden iets gelijkaardigs kunnen doen voor de woonmaatschappijen, bv. korte naam: "Dimensa", naam; "Gent-Zuid (Dimensa)" – of omgekeerd. In een rapport kan de programmeur zowel de korte naam als de naam van een gebied opvragen. In een presentatie in de databank krijg je standaard de naam en kun je, voor zover ik weet, niet de korte naam opvragen.

Samengevat behoort dit allemaal tot de mogelijkheden:

1. een nieuwe tekstvariabele maken met de namen van de woonmaatschappijen
2. de huidige gebiedsnamen aanpassen: uitbreiden met tussen haakjes de namen van de woonmaatschappijen
3. de huidige gebiedsnamen aanpassen:
	- naam = zoals 2. hierboven
	- korte naam = naam van de woonmaatschappij

Of variaties op en combinaties van bovenstaande.

**Comment by karolienbloemen** [comment]
ik ben voorstander om als gebiedsniveau de huidige gebiedsnaam (werkingsgebied) behouden, dat is waar mensen vertrouwd mee zijn. Bovendien blijven het gebiedsniveau's die we opnemen in PinC (en niet organisaties). Het lijkt me wel een optie om de naam van de maatschappij op een of andere wijze toe te voegen zoals hierboven gesuggereerd.

**Comment by StefanieWVL** [comment]
voorstander om als gebiedsniveau de huidige gebiedsnaam (werkingsgebied) behouden, en de namen van de woonmaatschappijen er aan toevoegen, als tekstvariabele (zoals Filip voorstelt).

Ander puntje:
Wanneer je een gebiedsniveau wil kiezen dan staat er in de lijst 'woonmaatschappij'. Is dat niet verwarrend aangezien we er juist voor opteren om niet de namen van de woonmaatschappijen te gebruiken maar wel de werkingsgebieden? Zie printscreens. [woonmaatschappij VS werkingsgebied.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/12618773/woonmaatschappij.VS.werkingsgebied.docx)
Eventuele suggesties: 'werkingsgebied woonmaatschappijen', werkingsgebied sociale huisvesting, werkingsgebied SH, werkingsgebied WM

**Comment by GeertBonte** [comment]
Ja, als relatief nieuwkomer vind ik het inderdaad wat verwarrend dat het gebiedsniveau "woonmaatschappij" geen namen van woonmaatschappijen, maar namen van werkgebieden bevat. Dus ik steun het voorstel van @StefanieWVL om de naam van het gebiedsniveau te wijzigen.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/09/'23
Voorkeur voor 'werkingsgebied woonmaatschappijen' en het toevoegen van een tekstvariabele met de naam.
Emilien past de naam aan, Geert voegt de tekstvariabele toe. De namen staan op de website van Wonen Vlaanderen

**Comment by GeertBonte** [comment]
Hier de kaart met de namen van de woonmaatschappijen: https://assets.vlaanderen.be/image/upload/v1694178248/Woonmaatschappijen-in-kaart-def_ytxnpm.pdf

**Comment by Emilien-Dupont** [comment]
De naam werd aangepast naar 'werkingsgebied woonmaatschappijen' in PinC. De verandering van de namen van de onbekende gebieden zal gebeuren tijdens de algemene verwerking van de gebiedsniveaus in december

**Comment by GeertBonte** [comment]
Tekstvariabele is inmiddels toegevoegd (v2202_woonmaatschappij) en beschikbaar op niveau "werkingsgebied woonmaatschappijen" en niveau "gemeente".

https://provincies.incijfers.be/databank?workspace_guid=5ed7c8b6-b158-49f8-a307-f470fde884a5
