### ISSUE TITLE
Foute aggregaties

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#411]
Door aanpassingen en harmonisaties die gebeurden aan de gebiedsniveaus eind juni om andere problemen op te lossen, is er een nieuw probleem naar boven gekomen: swing aggregeert niet meer correct wanneer je gegevens op subgemeentelijk niveau en op gemeente2018 inleest, en niet op het niveau van gemeente.

Dit is naar boven gekomen door een probleem met het hoogste onderwijsniveau. Deze cijfers waren ingelezen op statsec, ggw7, deelgemeente en gemeente2018. De data op ggw7 en deelgemeenteniveau werden ingelezen als missing omdat de aggregatie vanuit statsec niet klopte door rare censurering op dit niveau. Voorheen verwachtten we dat de correcte aggregatie doorloopt vanaf gemeente2018 naar gemeente, provincie etc. maar dat gebeurde niet. In plaats kregen deze niveaus ook missings te zien.

Dus, heb je data die niet volledig correct is op statsec (waardoor statsec niet automatisch mag aggregeren naar de bovenliggende niveaus) zorg dat je dan zeker ook gemeente inleest, en niet enkel gemeente2018, naast de andere subgemeentelijke niveaus.

**Comment by Emilien-Dupont** [comment]
RG 19/09/'23
Nagaan voor eigen data.
Emilien vult aan in documentatie

**Comment by Emilien-Dupont** [comment]
toegevoegd aan de documentatie: https://github.com/provinciesincijfers/JiveDocumentation/blob/master/04.%20Data%20inlezen/Algemene%20principes%20data%20inlezen.md#op-welke-gebiedsniveaus-inladen

**Comment by Emilien-Dupont** [comment]
De aggregaties lopen ook in het honderd voor Brussel wanneer je de data enkel inleest op statsec-niveau. Op het niveau van de provinices wordt alles nog goed getoond, maar op het niveau van de gewesten krijg je geen cijfers meer te zien voor Brussel.
De data ook inlezen op gemeenteniveau, zou dit probleem moeten verhelpen.

**Comment by Tine-VB** [comment]
Waar zit het probleem van Brussel dan juist? ABF moet dan toch ergens iets 'misprutst' hebben? Kan dit inderdaad niet anders opgelost worden? Bij landbouw zijn er ook problemen hiermee. Zoals Filip zegt: dat zijn alles samen wel heel veel indicatoren.

**Comment by demaesschalckfilip** [comment]
Is hier al een oplossing voor gevonden door onze vrienden van ABF? Hierdoor zitten er ook fouten (ontbrekende waarden) in het rapport detailhandel, en dat verschijnt binnenkort.

**Comment by Emilien-Dupont** [comment]
Toevallig heb ik hier gisteren een reactie op gekregen van abf:

_Hoi Emilien,_

_Een verlate reactie maar helaas zonder goed nieuws._
_Ik heb geen makkelijke oplossing voor dit probleem._

_Zoals je aangeeft staan er zoveel gebiedsrelaties. Een aanpassing aan de een relatie gaat waarschijnlijk een fout geven bij een andere relatie._
_Wellicht moeten we eens kijken naar de relatietabel. Ingeval je die tabel zou kunnen vereenvoudigen, kun je daarna aanpassingen_ _doorvoeren waarvan je weet wat het resultaat is._
_Op dit moment door de vele relaties is het lastig te zien wat het resultaat is van een aanpassing in de relatietabel._

Dus er is geen oplossing langs hun kant, of toch geen oplossing waardoor heel mogelijks andere zaken kapot gaan (wat in het verleden al is gebeurd). 

Een noodoplossing is de data inlezen op gemeenteniveau, maar het kluwen van de relaties tussen de gebiedsniveaus ontwarren zal alleszins niet voor direct zijn

**Comment by demaesschalckfilip** [comment]
Wij stellen voor dit nog eens te bespreken op de redactiegroep. Dit is eigenlijk een groot probleem voor de meerderheid van onze gegevens. Ook in het kader van de aankomende fusies en herwerken statistische sectoren, zouden we een werkgroepje moeten oprichten om de gebiedsrelaties te bekijken. Wij stellen voor daarmee zo snel mogelijk te starten om het Brussel-probleem om te lossen, want dat op de lange baan schuiven is wat ons betreft geen optie.

**Comment by Emilien-Dupont** [comment]
RG 23/05/24
we starten een werkgroep op om de gebiedsniveaus en -relaties te vereenvoudigen.
werkgroepleden: Emilien, Filip, Stefan, Geert, Sarah
Emilien vraagt aan ABF of ze de gebiedsrelaties visueel kunnen voorstellen en hoe omgaan met archief gegevens bv. gemeente2018. Ook navragen waar het juist strop loopt: hoe veel gebiedsrelaties kan swing aan?

**Comment by Emilien-Dupont** [comment]
Het probleem van de ontbrekende gegevens voor het Brussels hoofdstedelijk gewest werden opgelost.
