### ISSUE TITLE
Swing Stories Onderwijsrapport

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#412]
De **Swing Stories variant van het onderwijsrapport** ([zie hier](https://provincies.incijfers.be/databank/report/?id=rapport_onderwijs)) kan je terugvinden in de beta bij de Dashboards (Mosaic > Start > Onderwijs > Open test version) of via de volgende [link](https://beta-provincies.incijfers.be/dashadmin/preview/onderwijs/). 

Niet het volledige rapport werd omgezet. Het gaat hierbij om de voorpagina, leeswijzer, inleiding, hoofdstuk 1 en de pagina met meer informatie over cijfers en bronnen. Hoofdstuk 2 en 3 werden buiten beschouwing gelaten omdat hier functionaliteiten gebruikt wroden die al in hoofdstuk 1 aan bod zijn gekomen.

Ga er gerust eens door, en laat in dit issue maar weten welke zaken jullie nog graag toegevoegd zouden zien, welke niet werken zoals ze zouden moeten werken etc. Moesten jullie nog een ander rapport in gedachten hebben met een ander opzet en met andere functionaliteiten, mogen jullie dat ook altijd meegeven. Dan gaan ze daar ook mee aan de slag.

<br>
<br>

Hieronder een **overzicht van de functionaliteiten die momenteel niet mogelijk zijn** in Swing Stories in vergelijking met het onderwijsrapport:

- Voorpagina
  - De voorpagina bestaat uit een pdf-bestand dat aan een Swing Stories wordt gehangen. Zo’n voorpagina komt beschikbaar als je het rapport in pdf-vorm download. De voorpagina van het onderwijsrapport bestaat uit dezelfde foto voor alle gemeenten. Het is niet mogelijk om hier variatie in aan te brengen.
 
- Inhoudsopgave
  - In Swing Stories staat de inhoudsopgave aan de linkerkant van het scherm. Deze inhoudsopgave wordt momenteel niet meegenomen als je een pdf van het rapport afdrukt. In de najaarsrelease van 2023 van Swing wordt de inhoudsopgave wel meegenomen in de af te drukken pdf. Deze inhoudsopgave bevat links waarmee je kunt navigeren naar een hoofdstuk of paragraaf
  - In Swing Stories kun je in de inhoudsopgave alleen werken met hoofdstukken en paragrafen. Subparagrafen zijn niet mogelijk. Voorlopig is er geen initiatief om dit wel mogelijk te gaan maken. 
 
 
- Inleiding
  - Het Swingrapport bevat een datum van waarop het rapport wordt gedownload. Momenteel is deze functionaliteit niet mogelijk in Swing Stories
 
 
- Gebiedsselectie
  - In het Swingrapport kun je 1 of meerdere gemeenten kiezen. Beide gekozen gemeenten worden getoond in de figuren/tabellen. Kies je meer dan 2 gemeenten, dan worden de gemeenten getotaliseerd weergegeven. Dit is niet mogelijk in Swing Stories. Je kiest hierbij 1 gebied. Hetzelfde geldt voor het vergelijkingsgebied, dat maar uit 1 gebied kan bestaan. Er is wel een mogelijkheid om via ‘mijn regio’ zelf meerdere gemeenten samen te nemen en te tonen. Daarnaast kun je een andere gemeente als vergelijkingsgebied kiezen. De vraag aan PinC is in hoeverre het gewenst is dat een gebruiker maximaal 2 gebieden en 2 vergelijkingsgebieden tegelijkertijd kan presenteren in een figuur/tabel?
  - Als je 1 gemeente kiest worden er 2 kaarten getoond in het Swingrapport in de leeswijzer. Als je meerdere gemeenten kiest wordt er 1 kaart getoond. Dit werkt via if-else statements dat momenteel niet mogelijk is in Swing Stories. In de voorjaarsrelease van 2024 wordt het mogelijk om delen van een rapport te verbergen afhankelijk van je gebiedskeuze.
 
 
- Top 10
  - In het Swingrapport zitten enkele opsommingen en kaarten van top 10 gemeenten. Dit is momenteel niet mogelijk in Swing Stories. --> De hoogste en laagste zullen in de komende najaarsrelease al oproepbaar zijn. De 2e hoogste, 3e etc. zit er nog niet in. Wordt toegevoegd als wens om in te bouwen
 
 
- Algemeen
  - In het Swingrapport zijn veel figuren en tabellen naast elkaar weergegeven. In Swing Stories is dit ook mogelijk maar de ruimte is beperkt door de inhoudsopgave aan de linkerkant. Het advies is om meer gebruik te maken van figuren over de gehele breedte. Hiermee los je ook layout-issues op zoals verticale labels onder staven
  - Onder een figuur in het Swingrapport zijn onderstaande knoppen ( ) te vinden. De functionaliteiten van deze knoppen zijn terug te vinden in de knoppen van een tegel. 
  - In een tabel in het Swingrapport zijn alle onderwerpen hyperlinks naar een metadatafiche. Deze metadata kun je laten terugkomen in de detailview van een tegel en/of in een knop ‘meer info’.

**Comment by GeertBonte** [comment]
Als ik het zo allemaal lees en bekijk, zijn er in Stories heel wat beperkingen die het momenteel in de praktijk niet mogelijk maken om alle rapporten zomaar te vervangen door Stories zonder grote toegevingen te doen. Vooral de beperkingen bij de gebiedsselectie (slechts één primair gebied en slechts één vergelijkingsgebied) zijn een stap achteruit. Ook het ontbreken van `if-then-else`-functionaliteit legt ons zeer grote beperkingen op. De huidige rapporten hangen aan elkaar van de `if-then-else`’s!

Ik heb de indruk dat ABF met Stories vooral een product heeft willen maken dat eenvoudiger en dus meer beheersbaar is. Daardoor zijn echter heel wat zaken die vandaag mogelijk zijn met rapporten, (nog) niet mogelijk met Stories. Stories kan misschien nog wat enkele extra functionaliteiten krijgen, maar ik vrees dat we er niet op zullen moeten rekenen dat dit product mettertijd alles zal kunnen wat we nu doen met rapporten.

Sorry dat ik wat negatief klink, maar ik hoop dat de rapporten nog geruime tijd zullen blijven werken (naast Stories), en dat we niet voor voldongen feiten geplaatst zullen worden.

Dit gezegd zijnde vind ik de Stories-variant van het onderwijsrapport er wel goed uitzien (als je niet naar de tekortkomingen kijkt). Het lettertype dat gebruikt wordt in tabellen, mag misschien toch iets groter (zeker voor relatief eenvoudige tabellen met weinig kolommen)

**Comment by Emilien-Dupont** [comment]
de feedback van de centrumsteden en de opvolging van hun vragen ivm verbeteringen aan abf worden bijgehouden in https://github.com/provinciesincijfers/swing-stories/issues
