### ISSUE TITLE
Foutje in rapport bevolking en huishoudens

### ISSUE THREAD

**Issue by emdockx** [provinciesincijfers/PinC-taakopvolging#413]
Hoofdstuk 2. Huishoudens
Deel 2.1 Het totaal aantal huishoudens

In de eerste paragraaf wordt verwezen naar een percentage maar de waarde ontbreekt hier (in de tekst staat x%):
https://provincies.incijfers.be/databank/report/?id=rapport_demografie&input_geo=provincie_10000,

**Comment by VickyVB** [comment]
Deze waarde ontbreekt ook in de databank voor het laatste jaar (2023).
https://provincies.incijfers.be/databank?workspace_guid=5c03e2d2-a12d-48dd-b5b7-58d3477d2dd3 
Het gaat om de variabele vp1114a_alleenw .

**Comment by Emilien-Dupont** [comment]
Dit zou in orde moeten zij (https://github.com/provinciesincijfers/data-wishlist/issues/60#issuecomment-1739329912)
