### ISSUE TITLE
Volgorde keuze gebiedsniveau

### ISSUE THREAD

**Issue by emdockx** [provinciesincijfers/PinC-taakopvolging#414]
Momenteel krijgen gebruikers in rapporten de keuze uit gebiedsniveaus gemeente, statistische sector, wijk, deelgemeente, provincie, ... (zie screenshot).

Zou het logischer/gebruiksvriendelijker zijn om de volgorde aan te passen naar: statistische sector, wijk, deelgemeente, gemeente, provincie, ... (dus in volgorde van aggregatie)?

![Screenshot 2023-09-19 at 10 21 26](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/71769598/2846384d-1b2e-4b17-92f6-f46430c78b01)

**Comment by VickyVB** [comment]
Doorgaans wil je een rapport van de volledige gemeente, en niet van één statistische sector. Het is dus logisch dat deze optie bovenaan staat als default.

**Comment by emdockx** [comment]
Ok, prima.
Bedankt voor de toelichting.
