### ISSUE TITLE
Verharding in openruimtebestemmingen

### ISSUE THREAD

**Issue by valeriepirard** [provinciesincijfers/PinC-taakopvolging#415]
Nieuwe indicator ruimte op vraag van verschillende IP collega's klimaat(adaptatie).
Op Vlaams niveau monitort men de verharding in openruimtebestemmingen. Eén van de BRV-doelstellingen is namelijk om tegen 2050 de verhardingsgraad in de bestemde open ruimte te verlagen met 20% ten opzichte van die in 2015. Vandaar wenselijk om ook lokaal op te volgen.
De indicator kwam tot stand via een overlay van de jaarlijkse bodemafdekkingskaart (JaarBAK) met de geodata achter de Ruimteboekhouding RSV (categorieën ‘Natuur’ (03), ‘Bos’ (05) en ‘Landbouw’ (06).
Momenteel zijn de 2022 data terug te vinden onder: INTERN/Admin Only/Valerie/JaarBAKxRuimteboekhouding
Bedoeling is om de voorgaande jaren ook te berekenen en extern te plaatsen onder "Wonen en ruimtegebruik"-->"Ruimtegebruik"-->"Verharding"
Vraag : Oost-Vlaanderen als controleur, aangezien de rest van de ruimtelijke indicatoren ook daar gecheckt worden.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10:
OVL akkoord om te controleren en de metadatafiche te bekijken. Mag onder Wonen en ruimtegebruik > ruimtegebruik uiteindelijk extern geplaatst worden.
Vera brengt dit nog op de werkgroep Natuur.
Graag duidelijk omkaderen in de metadatafiche, want het zijn absolute cijfers en in sommige gebieden is de verhardingsgraad al zeer laag.

**Comment by veravandestraat** [comment]
Feedback uit werkgroep Natuur: heel relevante indicator, maar dan vooral voor klimaat, niet zo zeer voor natuur.

**Comment by valeriepirard** [comment]
Ik heb ook de percentages toegevoegd:
aandeel verharding in openruimtebestemmingen
              aandeel verharding in bestemming bos
              aandeel verharding in bestemming natuur
              aandeel verharding in bestemming landbouw
Daarnaast: aangepaste metadatafiche (ter controle bij Tine): [link](https://vlbr.sharepoint.com/:w:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Uploadfiles%20PinC/00%20Metadatafiches%20PinC/fiches%201000-1999/v1592_verharding_JaarBAK.docx?d=w60ba28363d9448f79d2ef77909c6ced7&csf=1&web=1&e=l99qB1)
Voorstel is om alle verwerkingen/kruisingen die we doen met de JaarBAK te centraliseren in 1 fiche

**Comment by valeriepirard** [comment]
% algemene verharding staat er reeds bij: [hier](https://provincies.incijfers.be/databank?workspace_guid=86483971-daac-47bc-b2df-71fdec6426ca). 
Is afgestemd met Filip. Zijn suggestie vervalt.
