### ISSUE TITLE
Actualisering en uitbreiding cijfers Klimaatportaal (VMM)

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#416]
Alle cijfers in het VMM Klimaatportaal werden opnieuw opgeladen
(omwille van actualisaties in het thema "hitte"):
<img width="337" alt="image" src="https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/cb412652-efcc-40f2-8155-6d26687dfa13">

in één beweging werd ook het nieuwe subthema "grondwater" -met onderstaande indicatoren- toegevoegd:
<img width="372" alt="image" src="https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/cc2f6d65-6e11-41ff-8d98-8a3db48f0511">
https://provincies.incijfers.be/databank?workspace_guid=15953107-5ccb-4376-bb4d-aaa1ffa47804

**Comment by Emilien-Dupont** [comment]
Reactie van abf op weergave van modellen en scenario's: Dit is niet mogelijk. We hebben destijds een extra mogelijkheid toegevoegd om voorlopige data anders visueel weer te geven (provisional period). Daarnaast is de uitgebreide info popup geintroduceerd (staat uit bij jullie) waarbij extra info opgegeven kan worden. Hiervoor zijn onder andere bij de datasource tabel meerdere kolommen toevoegd om extra duiding te geven.

**Comment by HanneODB-VLBR** [comment]
Wat is die uitgebreide info popup precies? Kunnen we dat eventueel niet aanzetten? Kan dit misschien dienen als alternatief voor de voetnoot (die m.i. zodanig 'verstopt' zit dat mensen die info alsnog niet zien...)?

**Comment by Emilien-Dupont** [comment]
Die info popup zit in de nieuwe weergave van de metadata. Er waren nog een paar zaken die uitgeklaard moeten worden met abf vooraleer we kunnen overschakelen op het nieuwe systeem. Maar dat kan dan inderdaad zeker als alternatief dienen.
