### ISSUE TITLE
Chatfunctie verwijderen

### ISSUE THREAD

**Issue by Tine-VB** [provinciesincijfers/PinC-taakopvolging#418]
Voorstel: de chatfunctie uit PinC halen. 
Redenen: 
- de gebruikte software heeft als grote nadeel dat een vraag aan iemand persoonlijk wordt toegewezen. Het zou beter zijn dat vragen in 'een lijst' komen zodat je ze daar kan aanklikken om ze te beantwoorden. Zelfs als er nu meerdere mensen de chat bemannen, gebeurt het vaak dat een vraag gemist wordt, omdat je even niet op je bureau zit of gewoon even niet oplet of je een nieuwe vraag hebt binnengekregen. Het heeft dus ook niet veel zin om meer mensen op de chat te zetten, want dat betekent niet dat er meer kans is dat de vraag tijdig beantwoord kan worden.
- vragen zijn anoniem, dus als je iets te lang wacht met antwoorden, en iemand heeft de chat gesloten, dan kan je die niet meer bereiken. Je kan de vragen ook niet doorsturen naar een medewerker die er beter kan op antwoorden, zonder eerst het emailadres te vragen.
- er zijn genoeg andere manieren om snel een antwoord op een vraag te krijgen. De mails naar info@provincies.incijfers.be worden snel beantwoord, omdat ze bij meerdere mensen tegelijk terecht komen. Mensen kunnen ook contact opnemen met D&A van de eigen provincie. 
- bij een chatfunctie creëer je de verwachting dat je meteen een antwoord zal krijgen op je vraag. We kunnen dat duidelijk niet waarmaken, en maken zo geen goede indruk. 

Duid hier aan of jullie akkoord gaan om de chat af te sluiten:

Emilien:
- [ ] Ja
- [ ] Nee

D&A Antwerpen:
- [x] Ja
- [ ] Nee

D&A Limburg:
- [x] Ja
- [ ] Nee

D&A Oost-Vlaanderen:
- [x] Ja
- [ ] Nee

D&A Vlaams-Brabant
- [x] Ja
- [ ] Nee

D&A West-Vlaanderen
- [x] Ja
- [ ] Nee

**Comment by Emilien-Dupont** [comment]
Ter info: In [dit](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B4a7949e0-81b7-4f69-8dce-a0a9deaf482d%7D&wdOrigin=TEAMS-WEB.teamsSdk_ns.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1699541597900&web=1) vind je onder de tweede tab het aantal gestelde vragen via mail en via de chat

**Comment by StefanJacques** [comment]
> Ter info: In [dit](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B4a7949e0-81b7-4f69-8dce-a0a9deaf482d%7D&wdOrigin=TEAMS-WEB.teamsSdk_ns.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1699541597900&web=1) vind je onder de tweede tab het aantal gestelde vragen via mail en via de chat

wow ! Best veel vragen via de chat !

**Comment by Tine-VB** [comment]
Maar ook wel een aantal daarvan die we gemist hebben... Zoals je kan zien in de oplijsting in het eerste tabblad.

**Comment by Tine-VB** [comment]
Er staat wel niet bij of we op tijd geantwoord hebben of niet :-)

**Comment by Tine-VB** [comment]
Nog een linkje naar de chat gevonden vandaag: https://provincies.incijfers.be/dashboard/dashboard/gebruik-van-de-website helemaal onderaan bij Vragen.
