### ISSUE TITLE
Zorg dat betekenisloze mapnamen uit themaboom niet in titel verschijnen

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#42]
Dit soort grafiektitels zijn mottig:

![afbeelding](https://user-images.githubusercontent.com/10122639/61956760-11df3a80-afbe-11e9-8347-7fbe4dcbdc89.png)

Dat komt omdat Swing de laagste gemeenschappelijk map-naam meeneemt. Oplossing: 
als de naam van een map niet interessant is ("aantallen", "percentages", "hoofdindeling") of misleidend kan zijn ("ouderen" zonder dat je ziet dat het in context zorgaanbod is), zet dan het vinkje "zichtbaar in titel" uit in het beheer van de themaboom.

**Comment by StefanJacques** [comment]
Dag Joost,
ik heb in het EXTERNE gedeelte naar best vermogen "nietszeggende titels" uitgevinkt.

**Comment by joostschouppe** [comment]
Volledig afgewerkt door Stefan
