### ISSUE TITLE
verandering 'ruimteboekhouding' naar 'bestemming van ruimte'

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#421]
In de themaboom heb je nu een onderdeel 'Ruimteboekhouding' dat valt onder 'Ruimtegebruik'. 
Deze term is mogelijks niet zo duidelijk voor gebruikers. Daarom het voorstel om dit te vervangen door 'Bestemming van ruimte'. Ruimteboekhouding staat immers ook al vermeld als bron.

Alternatieve mogelijkheid (als Ruimteboekhouding moet behouden worden): Ruimteboekhouding (bestemming).

**Comment by Emilien-Dupont** [comment]
Redactiegroep 23/11
Alle rubrieken onder Ruimtegenruik moeten nog eens herbekeken worden.

**Comment by valeriepirard** [comment]
Naamgeving van de rubrieken is nu gebaseerd op de naamgeving die ook departement Omgeving hanteert. Bv. de indicatoren uit de landgebruikskaart, ga je daar ook terugvinden onder rubriek 'Landgebruik'.
Maar als bepaalde dingen veranderd moeten worden of duidelijker kunnen, altijd open voor suggesties :-)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/12
Suggesties mogen doorgegeven worden tot de volgende Redactiegroep (16/01)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 18/01/24:
Filip toetst maandag nog af met de collega's van Ruimtelijke planning en brieft op de volgende Redactie

**Comment by demaesschalckfilip** [comment]
Suggestie nieuwe indeling/naamgeving **Ruimtegebruik** in themaboom:

-**Bebouwde kadastrale percelen** (voorheen statistiek van de bodembezetting)
-**Onbebouwde kadastrale percelen** (voorheen onbebouwde percelen)
-**Bebouwde oppervlakte volgens Basiskaart Vlaanderen (GRB)** (voorheen bebouwing)
-**Landgebruik volgens de landgebruikskaart** (voorheen landgebruik)
	-**Landgebruikscategorieën** (voorheen landgebruik detail)
	-**Ruimtebeslag versus open ruimte**
		-**Ruimtebeslag**
		-**Open Ruimte**
	-**Niet-bebouwde ruimte**
        -**Groenaanbod**
                -**Eigen verwerking** (voorheen: groenaanbod eigen verwerkingen)
-**Verharding volgens de bodemafdekkingskaart** (voorheen: verharding)
	-**Verharding in ruimtebeslag** (voorheen Verharding per type ruimtebeslag)
	-**Verharding in openruimtebestemmingen**
-**Bestemming van ruimte**
        -**Bestemmingscategorieën**
	-**Harde en zachte bestemmingen** (voorheen Harde/zachte bestemmingen)
	-**Kruising bestemming van ruimte en ruimtebeslag**

Ik zou de infofiches van 'groenaanbod' en 'groenaanbod eigen verwerkingen' samenvoegen in één infofiche (hetzelfde basisbestand, maar ander niveau (hoewel verschillen): dit onderscheid zou duidelijker zijn in één infofiche).

**Comment by demaesschalckfilip** [comment]
Suggestie nieuwe indeling/naamgeving **Ruimtegebruik** in themaboom (de variabelen blijven onder hun (eventueel van naam gewijzigde) titels staan):


**Bebouwde kadastrale percelen** (voorheen statistiek van de bodembezetting)

**Onbebouwde kadastrale percelen** (voorheen onbebouwde percelen)

**Bebouwde oppervlakte volgens Basiskaart Vlaanderen (GRB)** (voorheen bebouwing)

**Landgebruik volgens de landgebruikskaart** (voorheen landgebruik)
- **Landgebruikscategorieën** (voorheen landgebruik detail)
- **Ruimtebeslag versus open ruimte**, daaronder de mappen:  **Ruimtebeslag** en **Open Ruimte**
- **Niet-bebouwde ruimte**
- **Groenaanbod**, daaronder de map:  **Eigen verwerking** (voorheen: groenaanbod eigen verwerkingen)

**Verharding volgens de bodemafdekkingskaart** (voorheen: verharding)
- **Verharding in ruimtebeslag** (voorheen Verharding per type ruimtebeslag)
- **Verharding in openruimtebestemmingen**

**Bestemming van ruimte**
- **Bestemmingscategorieën**
- **Harde en zachte bestemmingen** (voorheen Harde/zachte bestemmingen)
- **Kruising bestemming van ruimte en ruimtebeslag**


Verdere suggestie: de infofiches van ‘groenaanbod’ en ‘groenaanbod eigen verwerkingen’ samenvoegen in één infofiche (is hetzelfde basisbestand, maar een ander ruimtelijk niveau (hoewel er toch verschillen zijn): in één infofiche zou het onderscheid tussen beiden duidelijker zijn).

**Comment by valeriepirard** [comment]
Ik zal de aanpassingen doen in de themaboom.  Ruimtegebruik zal dan wel het enige thema zijn, waarin de bron vermeld wordt in de naam.

"Onbebouwde kadastrale percelen (voorheen onbebouwde percelen)" _de onbebouwde percelen die nu in de themaboom staan, komen niet uit het kadaster maar uit het vermoedensROP_

**Comment by demaesschalckfilip** [comment]
Klopt, maar ik dacht dat ze wel kadastrale percelen als eenheid gebruiken?

Wat de bron in de naamgeving betreft: dat wordt ook gedaan bij de bevolking: ‘totaal aantal inwoners volgens Rijksregister’, om het verschil met andere bevolkingscijfers te duiden. Het leek ons hier ook wel een goed idee om dat te doen, in een poging de verschillen tussen de variabelen te duiden/structureren. Bekijken we het op de eerstvolgende redactiegroep?

**Comment by valeriepirard** [comment]
Dat zijn 2 verschillende dingen.
Onbebouwde percelen o.b.v. het kadaster : akkerland, grasland, tuinen en parken, boomgaarden, bos, woeste gronden, recreatie, sport, gekadastreerde waters, gekadastreerde wegen, andere (n.e.g.). Deze indicator staat nog niet online op PinC (wel intern) Zie project Kadaster van Sarah : indicatoren in opbouw/landgebruik o.b.v. kadaster. 
Onbebouwde percelen o.b.v. vermoedensROP: dit zijn beschikbare onbebouwde terreinen die woningen of  aanverwante functies toelaten.

Ik vind het zinvol om te verwijzen naar de bron bij de ruimtelijke onderwerpen in de themaboom. Zeker omdat het vaak voorkomt dat eenzelfde onderwerp volgens verschillende bronnen berekend kan worden (bv. landgebruik volgens kadaster en landgebruik volgens landgebruikskaart).

**Comment by demaesschalckfilip** [comment]
Ok, dan stel ik voor, om verwarring te vermijden, 'onbebouwde percelen' (zoals het was). 'onbebouwde percelen volgens het vermoedensROP' bekt niet echt lekker.

**Comment by SarahMeire** [comment]
Voorstel om naast 'bebouwde kadastrale percelen' dan ook 'onbebouwde kadastrale percelen' toe te voegen in het kader van (een voorstel voor) **nieuwe indicatoren** - met in beide categorieën een onderscheid tussen de officiële statistiek van Statbel en de data uit onze eigen kadasterverwerking (zie ook issue [445](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/445)).

**Comment by Emilien-Dupont** [comment]
Redactie 19/03/24:
Akkoord met voorstel Sarah
