### ISSUE TITLE
aanpassing namen indicatoren verblijfstoeristische vraag

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#422]
Aan de werkgroep toerisme werd de vraag voorgelegd om de data verblijfstoeristische vraag (overnachtingen en aankomsten) ook tot op gemeentelijk niveau online te ontsluiten (eerder werd dit niet weerhouden waardoor deze data enkel tot toeristische regio en provincie beschikbaar zijn). De werkgroep toerisme kan hiermee akkoord gaan mits hierbij de huidige voetnoot ("exclusief directe verhuur voor de kust") onmiddellijk zichtbaar is bij de onderwerpen (zonder bijkomend te moeten klikken). 
Voorbeeld van onderwerpnaam wordt dan:  "overnachtingen door niet-Belgen (exclusief directe verhuur voor de kust)" Dit past binnen het maximum aantal mogelijke tekens.
Kan de redactiegroep hiermee akkoord gaan?

**Comment by StefanJacques** [comment]
Collega's,
als er geen bezwaren zijn, moet dit niet wachten tot de volgende redactiegroep - denk ik.
Vinken jullie aan indien akkoord:
- [ ] Antwerpen
- [ ] Limburg
- [ ] Oost-Vlaanderen
- [ ] Vlaams-Brabant
- [ ] West-Vlaanderen

**Comment by demaesschalckfilip** [comment]
Wat ik me afvraag: is de directe verhuur die **niet** aan de kust ligt dan wel inbegrepen? 
Voor het gratis gebruik van de woning door de eigenaar of derden (zie infofiche) lijkt me dat sowieso al niet het geval.

**Comment by karolienbloemen** [comment]
Het is voornamelijk een issue aan de kust: Westtoer zelf werkt niet met deze cijfers maar met eigen data die ze veel meer opvolgen; die wijken sterk af van deze bron. Het is juist daarom dat ze deze melding zichtbaar willen hebben om verwarringen te voorkomen. Voor andere provincies speelt dit veel minder, zij werken wel met deze data.

**Comment by Tine-VB** [comment]
Dan moet er dus eigenlijk staan: 'Exclusief directe verhuur'. En dan kan in de metadata een link gezet worden naar de cijfers van Westtoer, waar je voor de kust dan wel meer volledige cijfers kan vinden.

**Comment by Lievendr** [comment]
Het wordt er in ieder geval nog meer verwarrender op. twee databanken: Cijfers over verhuur Vlaanderen & cijfers van westtoer voor enkel de kust die soms wel en soms niet in cijfers Vlaanderen zitten?

**Comment by StefanieWVL** [comment]
Als ik de laatste post van Tine goed begrijp, is het dus eigenlijk "exclusief directe verhuur" (cfr. opm Filip) en moet die 'voor de kust' dus weg. In de metadatafiche zou dan wel duidelijk moeten staan dat de cijfers voor exclusieve verhuur door Westtoer wel geregistreerd  worden maar enkel voor de kust en op HUN website te consulteren zijn, en dus niet op PinC.
Dus: akkoord met aanpassen onderwerpnaam als de vermelding tussen haakjes juist is ,-))

**Comment by karolienbloemen** [comment]
Ik heb intussen ook bij de collega's toerisme opnieuw navraag gedaan opdat we het zeker juist vermelden, en de vermelding moet toch in zijn geheel blijven "exclusief directe verhuur voor de kust". Het is immers zo dat de data door statbel aan de kust anders worden verzameld dan in de andere regio's. We hebben dit zelf ook reeds langer in onze metadatafiche opgenomen : _"Specifiek voor de Kust en de kustgemeenten (incl. Zeebrugge) omvatten de cijfers van vakantiewoningen enkel de verhuur via een toeristisch verhuurkantoor en NIET de verhuur via eigenaar NOCH het gratis gebruik van de woning door de eigenaar of derden."_
Ook op de site van statbel staat dit zo vermeld: _"De cijfers voor deze categorie zijn gebaseerd op een steekproef getrokken op provincieniveau, uitgezonderd de kust, waar de cijfers geleverd worden door de verhuurkantoren."_

**Comment by HanneODB-VLBR** [comment]
We hebben dit binnen Vlaams-Brabant besproken en hebben hierbij nog de volgende vragen:
- De data van Statbel zijn gebaseerd op een steekproef, hoe wordt deze juist getrokken? Bv. Tweedeverblijvers of rechtstreekse verhuur: werden deze ook bereikt met de steekproef? Waarom zit de kust niet in deze steekproef vervat?
- Het basisregister Vlaams logiesaanbod wordt niet gebruikt, omdat er beperkingen op zouden zitten/er nog veel correcties op gebeuren. Wat zijn juist deze beperkingen? Kunnen erkende logies hier niet specifiek worden belicht? En als er nog correcties op gebeuren, kunnen ze deze niet aan ons doorgeven zodat wij dezelfde correcties kunnen hanteren? Filip gebruikt deze data wel voor het opstellen van de uitrustingsgraad.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/12/23:
De inhoud van de data is onduidelijk. Graag eerst uitklaren. Wordt verder besproken op de volgende Redactiegroep (16/01)

**Comment by karolienbloemen** [comment]
Antwoorden uit de werkgroep toerisme:
- ivm de steekproef: FOD bevraagt geen individuele eigenaars/uitbaters van vakantiewoningen aan de Kust die zitten niet in de steekproef. De cijfers vakantiewoningen Kust van FOD bekomen ze via toeristische verhuurkantoren vandaar dat dit een onderschatting is want niet iedereen verhuurt via een toeristisch verhuurkantoor. Daarom schat Westtoer het directe verhuur en het tweede verblijf gebruik in op basis van onderzoek.

- ivm beperkingen logiesaanbod (niet in PinC): 
Meerdere provincies geven beperkingen op, o.a. naar aanleiding van contacten, mailings… met de sector worden tekortkomingen vastgesteld. Enkel Westtoer bevraagt jaarlijks als enige provincie het logiesaanbod. op basis daarvan wordt ook elk jaar opnieuw vastgesteld dat het aanbod van Toerisme Vlaanderen niet correspondeert met de werkelijkheid.
	Het betreft enkel erkende en aangemelde logies, terwijl er meer logies actief zijn. Het is dus geen volledig beeld. Dit zou wel benoemd kunnen worden. De niet-aangemelde records bevat behoorlijk wat ‘rommel’, dubbele records, onvolledige records… (soms ook bij erkende en aangemelde logies)
	Langetermijn plaatsen op campings worden meegeteld terwijl dit niet als toeristische verhuur gezien wordt in de cijfers van FOD Economie
	Bij aanmelding van logies geeft de uitbater zelf de capaciteitsgegevens in binnen het gekozen logiestype. De uitbater moet ook zelf eventuele wijzigingen hierin melden. Ook stopzetting van de uitbating moet gemeld worden door de uitbater. In al deze stappen kunnen fouten gebeuren en een systematische / exhaustieve check hierop wordt niet gedaan.

	Uitbatingen die meermaals zijn opgenomen in de databank en dus dubbel/driedubbel in rekening worden gebracht.
	Uitbatingen die al lang gestopt zijn maar toch nog steeds in hun lijsten voorkomen.
	Uitbatingen die zich op diverse manieren willen promoten zoals voorzien in het decreet maar waarbij de product klasse verkeerd staat waardoor ze ook dubbel geteld worden.
	Uitbatingen die zich ooit hebben aangemeld maar nooit van start zijn gegaan maar hun gegevens niet hebben laten schrappen.
	Uitbatingen die ooit advies hebben aangevraagd en op die manier werden aangemeld maar nooit actief waren, wil TVL trouwens ook niet schrappen om historiek van de adviesaanvraag te kunnen bijhouden.
	Uitbaters die een vaste standplaats hebben op een terrein en zo al opgenomen zijn in die erkenning maar toch hun stacaravan direct willen verhuren en zich apart aanmelden om in orde te zijn met het logiesdecreet. Die standplaats wordt op die manier ook dubbel geteld.
	Het aanbod vakantiewoningen Kust is nog nooit gecontroleerd en zal vol staan van fouten. Wij halen het aanbod vakantiewoningen immers uit het kohier van tweede woningen van elke gemeente.
Omwille van al die redenen kunnen we vaststellen dat de kwaliteit van de lijst (zelfs van erkende) niet toereikend is om op te nemen in PinC.

**Comment by HanneODB-VLBR** [comment]
_"FOD bevraagt geen individuele eigenaars/uitbaters van vakantiewoningen aan de Kust die zitten niet in de steekproef."_ => dus, wil dit zeggen dat ze voor de niet-kustgemeenten wél in de steekproef zitten?

**Comment by karolienbloemen** [comment]
inderdaad, zie ook meer hierboven, zoals in de metadata opgenomen: "Specifiek voor de Kust en de kustgemeenten (incl. Zeebrugge) omvatten de cijfers van vakantiewoningen enkel de verhuur via een toeristisch verhuurkantoor en NIET de verhuur via eigenaar NOCH het gratis gebruik van de woning door de eigenaar of derden."

**Comment by Emilien-Dupont** [comment]
Redactiegroep 18/01/24:
- verblijfstoeristische vraag: oke om op te nemen mits duidelijke omschrijving in de metadatafiche
- databank logies aanbod: wordt niet opgenomen

**Comment by karolienbloemen** [comment]
Aangepast in PinC

**Comment by StefanJacques** [comment]
data verblijfstoeristische vraag (overnachtingen en aankomsten) staan tot op **gemeentelijk niveau** online
