### ISSUE TITLE
kust als streek in PinC

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/PinC-taakopvolging#425]
in WVL is er een sterke gebiedswerking. 
voor de meeste streken is de referentieregio het gebiedsniveau voor de streekwerking.
echter niet voor de kust.

vraag is of er,  naar analogie met centrumsteden en Vlaamse rand, een gebiedsniveau voor de kust kan gemaakt worden (op gemeenteniveau)

is natuurlijk enkel relevant voor WVL, maar is wel belangrijk voor WVL.

de toeristische regio kust die extern staat, is geen optie, omdat Brugge daar gesplitst is
het gebiedsniveau treg_gem zou wel kunnen gebruikt worden, maar dat staat enkel intern, en is enkel op te vragen mits login.

en niet enkel voor toeristische issues wil men in de kustgemeenten een vergelijking kunnen maken met de kust, of de kust in zijn geheel willen opvragen.

**Comment by GeertBonte** [comment]
#### Toelichting van het probleem:

Zowel in rapporten als in de database kun je een basisgebied vergelijken met een vergelijkingsgebied. Maar in PinC is er de bizarre situatie dat je een kustgemeente niet kunt vergelijken met de toeristische regio 'Kust'. Het lukt wél om andere gemeenten te vergelijken met de toeristische regio waartoe ze behoren. Dat is bizar aangezien de kust toch wel de belangrijkste toeristische regio van het land is, en dat je uitgerekend die regio niet als vergelijkingsgebied kunt gebruiken.

Als je een kustgemeente kiest en vervolgens kijkt welke mogelijke vergelijkingsgebieden er beschikbaar zijn, dan zul je zien dat daar niet de toeristische regio 'Kust' staat, maar wel de toeristische regio 'Niet te lokaliseren - Vlaanderen'. Uiteraard heeft het geen enkele zin om met die toeristische regio te vergelijken.

Dit fenomeen wordt veroorzaakt doordat toeristische regio's niet samengesteld zijn uit gemeenten, maar uit statistische sectoren. De reden daarvoor is dat het grondgebied van één gemeente, namelijk Brugge, verdeeld is over twee toeristische regio's: het noorden (deelgemeente Zeebrugge) hoort bij de toeristische regio 'Kust'; de rest van Brugge behoort is de regio 'Kunststeden - Brugge'. Het gevolg is dat die twee toeristische regio's in PinC geen oudergebied zijn van de gemeenten die ertoe behoren. Niet van de gemeente Brugge, maar ook niet van de andere kustgemeenten.

Om de getroffen gemeenten tóch te kunnen vergelijken met hun toeristische regio, werd eerder al een alternatieve gebiedsindeling gecreëerd, namelijk de 'toeristische regio (benaderd via gemeente)'. Bij die indeling zit Brugge in zijn geheel bij 'Kunststeden - Brugge (incl. Zeebrugge)', en zitten de andere kustgemeenten bij 'Kust (excl. Zeebrugge)'. Op die manier kunnen kustgemeenten dus wél vergeleken worden met hun toeristische regio, weliswaar door abstractie te maken van Zeebrugge. Erg is dat niet, want Zeebrugge stelt toeristisch gezien niet zoveel voor in vergelijking met de andere kustgemeenten.

Probleem opgelost, denk je dan? Neen, helaas niet, want die alternatieve gebiedsindeling is enkel intern beschikbaar, d.w.z. voor ingelogde gebruikers. Gebruikers die niet ingelogd zijn, kunnen daar geen gebruik van maken, en daarom kunnen we die indeling ook niet gebruiken in rapporten.

#### Voorgestelde oplossing: nieuw gebiedsniveau

Omdat we voor heel wat onderwerpen de kustgemeenten wél graag zouden kunnen vergelijken met het geheel van de kust, is er dus nood aan een bijkomende gebiedsindeling die extern beschikbaar is, en waarin alle kustgemeenten (eventueel met uitzondering van Brugge) één gebied vormen. De alternatieve indeling 'toeristische regio (benaderd via gemeente)' mag echter niet extern komen.

De enige mogelijkheid is dan nog om een nieuw gebiedsniveau in het leven te roepen dat extern beschikbaar is, met één gebied dat samengesteld is ult alle kustgemeenten. Dat gebied zal dan als vergelijkingsgebied gekozen kunnen worden wanneer je als basisgebied één of meerdere kustgemeenten gebruikt. Op die manier wordt het dan eindelijk mogelijk om een kustgemeente te vergelijken met het geheel van de kust.

Als we besluiten om zo'n extra gebiedsniveau in het leven te roepen, dan moeten we het nog over volgende zaken eens zien te raken:

* Beschouwen we Brugge wel of niet als een kustgemeente?
* Welke naam geven we aan het nieuwe gebiedsniveau? Voorstel: 'Kustgemeenten'.
* Welke naam geven we aan het nieuwe gebied? Voorstel: 'Kustgemeenten' of 'Kustgemeenten (excl. Brugge)'

Voor het antwoord op de eerste vraag moeten we misschien even polsen bij het Brugse gemeentebestuur. Ziet Brugge zichzelf als kustgemeente? Willen Brugse PinC-gebruikers Brugse cijfers kunnen vergelijken met de kust?

**Comment by HildeC** [comment]
een bijkomende reden om een gebiedsniveau kust te hebben, is dat wij gebiedswerking hebben in West-Vlaanderen, en de kust is een werkingsgebied. Mijn vraag naar een regio kust is dus ook ingegeven vanuit de vraag van enkele collega's. 
Ik heb hen de vraag al voorgelegd hoe dat gebied moet samengesteld zijn, met of zonder Brugge, en zij willen zonder Brugge..
dus wat mij betreft is eerste vraag beantwoord. 
en als we het gebied kustgemeenten (excl. Brugge) noemen, dan is het voor iedereen duidelijk wat daar in zit.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 18/01/24:
Nagaan binnen elke provincie / IPWG of het streek-niveau gebruikt mag worden. Dit wordt nu enkel gebruikt voor OVL, die overeenkmoen met de treg_gem (toeristische regio's obv gemeente).
Indien oke, gaat elke provincie na welke streken binnen elke provincie gebruikt worden (obv gemeenten). Mag dit obv treg_gem, geen opdeling/dus de hele provincie, of nog een alternatieve opdeling

**Comment by StefanJacques** [comment]
voor Limburg mag de streek gelijk zijn aan gans de provincie Limburg

**Comment by Tine-VB** [comment]
Voor Vlaams-Brabant graag de regionale landschappen: Noord-Hageland, Zuid-Hageland, Dijleland, Pajottenland & Zennevallei en Brabantse Kouters.
[VLBR regionale_landschappen.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14222593/VLBR.regionale_landschappen.xlsx)

**Comment by Lievendr** [comment]
Voor Antwerpen blijft het een moeilijk verhaal door Zwijndrecht...en stad Antwerpen.
We hebben de volgende streken:
Kempen
Voorkempen
Rupelstreek/zuidrand
Rivierenland
Dender en Waas (waarin Zwijndrecht ligt)
Stad Antwerpen
 
https://www.provincieantwerpen.be/aanbod/dese/deis/streekbeleid.html#:~:text=De%20provincie%20Antwerpen%20ondersteunt%20een,werkgelegenheid%20en%20economie%20te%20bevorderen.

**Comment by HildeC** [comment]
[streekwerking.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14277492/streekwerking.xlsx)
dit is het voorstel voor West-Vlaanderen.
en ik ben voorstander om dit gebiedsniveau 'streekwerking' of 'streekwerking provincie' te noemen.

**Comment by Tine-VB** [comment]
Ik zou dan gaan voor 'Streekwerking'. De regionale landschappen die in Vlaams-Brabant worden gebruikt zijn niet iets van de provincies.

**Comment by Emilien-Dupont** [comment]
Redactiegroep: 20/02:
- Voor streken met dezelfde naam gebruiken we - 'naam provincie'
- naam gebiedsniveau: streekwerking
- tijdens de volgende verwerking van de gebiedsniveaus zal dit niveau opgenomen worden
