### ISSUE TITLE
huishoudens met actieve budgetmeter gas

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#426]
vraag vanuit werkgroep klimaat - rapportage energiearmoede om gegevens uit gemeente- en stadsmonitor over huishoudens met actieve budgetmeter gas + afnemers gas op te laden in PinC.

kan de redactiegroep hiermee akkoord gaan ?
budgetmeters gas zijn in ongeveer dezelfde mate aanwezig in de gemeenten als budgetmeters elektriciteit (zie onderstaande XY-diagram)

_voorlopig opgeladen onder_ 
ADMIN ONLY/STEFAN/KLIMAAT EN ENERGIE/ AANSLUITINGSPUNTEN AARDGAS
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/9bf4ebd3-7346-4895-ab8a-a99b7e619390)

Voorstel _indicatoren_ vanuit Europa
2.7 | Households / persons connected to the electricity grid / total households or persons | Huishoudens / inwoners aangesloten op het elektriciteitsnet / totaal aantal huishoudens of inwoners
**vraag: welke noemer gebruiken ?** zie [hier](https://provincies.incijfers.be/databank?workspace_guid=1aea04ef-ac94-421a-a376-491797957d66)

2.8
_Huishoudens / inwoners met een gasaansluiting / totaal aantal huishoudens of inwoners_
= voorlopig opgeladen [v3123_afnemers_gas](https://provincies.incijfers.be/admin/jive?var=v3123_afnemers_gas)

is deze indicator ook interessant voor fossielvrij bouwen en wonen ?
opvolgen in welke mate aardgasaansluitingen zullen uitfaseren ?
(https://www.vlaanderen.be/nieuwe-verwarmingsinstallatie-kiezen/geen-aardgasaansluitingen-meer-bij-nieuwe-grote-projecten)

4.3
_Betalingsachterstand op energierekeningen / totale bevolking / huishoudens_
NIEUW:  **huishoudens met actieve budgetmeter gas per 1.000 afnemers**
als uitbreiding op huidige indicator "huishoudens met actieve budgetmeter elektriciteit per 1.000 afnemers "

indien akkoord:
verhouding tot onderwerpen onder
WELVAART EN ARMOEDE/BETALINGSPROBLEMEN/BUDGETMETERS ELEKTRICITEIT
+ wie laadt op?

**Comment by StefanieWVL** [comment]
Bij het aanmaken van de indicator "budgetmeters elek" hebben we destijds beslist om de budgetmeters gas niet als indicator op te nemen. reden: niet alle woningen hebben gasaansluiting en geeft dus geen totaalbeeld van huishoudens met betalingsproblemen energie (want in principe heeft elke woning wel een elektriciteitsaansluiting). Maar de insteek is hier nu wel anders denk ik, meer vanuit het oogpunt klimaat en niet vanuit kwetsbare gezinnen? Indien dit het geval is, geen bezwaar om ook deze indicator op te laden (WVL zou dit kunnen doen, we doen ook al budgetmeter elek en LAC, zelfde bron). Als noemer zou ik dan wel de "aansluitingen gas" nemen, naar analogie met de berekening van % budgetmeters gas. Lijkt mij de enige correcte noemer.
Maar is de insteek toch eerder armoede > advies om toch nog eens over te nadenken alvorens op te nemen als nieuwe indicator

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/12/'23
Wat is de definitie van 'afnemers elektriciteit'? Nagaan bij VREG + aanvullen in de metadatafiche alvorens we een noemer kiezen.

afnemers gas: redactiegroep gaat akkoord om budgetmeter gas op te nemen, samen met budget meter elektriciteit onder een onderdeel 'budgetmeters'. We nemen deze cijfers niet op uit de GSM maar wel van VREG

**Comment by JoLocquet** [comment]
@StefanJacques Lijkt me zeker een goede suggestie. Pas op 23/01/2024 start de werkgroep Fossielvrij wonen en bouwen. De indicator kan opgenomen worden in de inhoudstafel die we tegen 04/2024 uitwerken. Ik bezorg de suggestie aan Sam De Coster.

**Comment by StefanieWVL** [comment]
Hieronder het antwoord op de vraag waarom het aantal huishoudens kan afwijken van het aantal aansluitingspunten (omdat dus dus niet om het aantal aansluitingspunten gaat) ;-). Ik zal met deze nieuwe info de betreffende metadatafiche ook aanpassen/aanvullen waar nodig.

Onder vraag-ID 2901 vallen het aantal **actieve elektriciteitscontracten** voor huishoudelijke afnemers. Dit staat daarom niet gelijk met het aantal unieke huishoudens. 

Afwijkingen kunnen in de twee richtingen spelen:
•	Als er in één woning twee meters staan voor elektriciteit (bijvoorbeeld een dag/nacht en een exclusief nacht), worden er twee geteld, terwijl dat één huishouden zal zijn;
•	Als er in één woning twee meters staan (bijvoorbeeld een dag/nacht voor de woning en dag/nacht voor wat schrijnwerk in een achterbouw) worden er ook twee geteld;
•	Een tweede verblijf waar een residentieel contract is afgesloten, wordt ook meegeteld. Met domicilie houden we geen rekening.
•	Een woongelegenheid waar illegalen verblijven en een elektriciteitscontract hebben, wordt meegeteld onder deze vraag-ID maar zullen niet geteld worden als geregistreerd huishouden.
Maar ook in de andere richting:
•	Eén meter in een kangoeroewoning bedient mogelijks twee geregistreerde huishoudens.
•	Een huishouden waar een vennootschap gevestigd is en dit gezin het elektriciteitsverbruik inbrengt in de vennootschap en om die reden een niet-huishoudelijk contract aangaat, zullen wij niet mee meetellen onder deze vraag-ID.
•	Een bakker die woont in zijn bakkerij en een niet-residentieel contract aangaat met BTW-nummer van zijn zelfstandige activiteit en werkt met één meter, zullen wij ook niet mee meetellen
•	Appartementen waar één leveringscontract is afgesloten op naam van de syndicus en deze intern een verdere onderverdeling maakt, zal hier als één in zitten, terwijl daar misschien 20 huishoudens wonen (mogelijk is dit de verklaring voor de duidelijke afwijkingen in de kustgemeenten).

**Comment by Emilien-Dupont** [comment]
Redactiegroep 18/01/24:
Stefanie doet voorstel voor metadatafiche en nieuwe naam tegen de volgende Redactie. 
Ook gas zal bekeken worden, want hier zal waarschijnlijk hetzelfde spelen.

**Comment by StefanieWVL** [comment]
De metadatafiche en de omschrijvingen van de indicatoren zijn aangepast.
De metadatafiche  [v3123_Actieve energiecontracten en betalingsproblemen energiefactuur .docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14385056/v3123_Actieve.energiecontracten.en.betalingsproblemen.energiefactuur.docx) Ik zet deze ook op Teams.

Voorstel voor plaats nieuwe indicatoren in de themaboom:
- huishoudens met actieve budgetmeter gas 
- huishoudens met actieve budgetmeter gas per 1.000 afnemers gas

onder >Sameneleven en Welzijn> welvaart en armoede> betalingsproblemen> Betalingsproblemen energie (nu nog "Betalingsproblemen elektriciteit" > voorstel om naam te wijzigen)

-afnemers gas
onder> Klimaat en Energie > aansluitpunten aardgas.

-afnemers elektriciteit staat momenteel nergens in de themaboom (ook niet intern). Is dit nodig?

**Comment by HildeC** [comment]
ik zou de afnemers elektriciteit wel ook opnemen, en dan ook een indicator maken van huishoudens met actieve budgetmeter elektriciteit tov 1000 afnemers elektriciteit.  
dan zijn gas en elektriciteit conform.

**Comment by StefanieWVL** [comment]
Deze zitten er al in ;-)
