### ISSUE TITLE
As altijd vanaf 0 beginnen bij staafgrafieken

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/PinC-taakopvolging#427]
Tijdens een opleiding rond de klimaatrapporten deze voormiddag maakte een van onze interne collega's de (wat mij betreft) terechte opmerking hoe vertekenend en fout het is om een staafdiagram niet vanaf 0 te laten beginnen. De opmerking werd gemaakt naar aanleiding van grafiek 7 in het klimaatadaptatierapport, maar ik heb gezien dat bijvoorbeeld ook het rapport detailhandel, het rapport landbouw, het rapport ouderenzorg, het rapport mobiliteit en het rapport criminaliteit. Hij vroeg of het niet mogelijk was om in het geval van staafdiagrammen de as altijd van 0 te laten beginnen.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/12/23:
Tegen de volgende Redactiegroep gaat iedereen na welke staafdiagrammen niet vanaf 0 mogen beginnen in rapporten.
Daarna worden de lijn- en staafdiagrammen in de Databank en Rapporten automatisch standaard op 0 gezet. 
(to do: tabel hier toevoegen)

**Comment by veravandestraat** [comment]
In rapport opvang baby's en peuters beginnen alle grafieken bij 0 (en geen index, dus geen uitzonderingen op basis van de opmerking van Hilde hierboven).

**Comment by Emilien-Dupont** [comment]
Redactiegroep 18/01:
Filip checkt voor rapporten VLB. 
Emilien maakt een sjabloon voor de aanpassingen.

**Comment by Emilien-Dupont** [comment]
Standaard begint de y as van alle staafdiagrammen nu van 0. Het[ sjabloon](https://provincies.incijfers.be/admin/jive/Report/Edit/sjabloon_grafiekstijl) werd aangevuld met daarin instructies om de as toch gebroken te maken
