### ISSUE TITLE
Indicator v1204_abc_d1 staat twee keer in de themaboom

### ISSUE THREAD

**Issue by emdockx** [provinciesincijfers/PinC-taakopvolging#433]
De indicator v1204_abc_d1 staat twee keer in de themaboom onder hetzelfde thema. Zie onder [WERKEN EN ONDERNEMEN > Landbouw > AgroBusinessComplex > Investeringen > Arbeidsplaatsen > Loontrekkende tewerkstelling en vestigingen > Loontrekkende tewerkstelling > Loontrekkende tewerkstelling in ABC land- en tuinbouw](https://provincies.incijfers.be/databank?workspace_guid=48c596ce-8633-4604-b6fa-7073928d9fbc).

**Comment by VickyVB** [comment]
aangepast!
