### ISSUE TITLE
Nieuwe wijken in Beta

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#436]
Nieuwe wijken worden enkel in de alpha van PinC ingeladen, niet in de Beta. Dit is wat lastig voor het inladen van wijkdata in de Beta, omdat hij de nieuwe wijken in je databestand niet herkent. Je kan altijd de 'skip' optie nemen natuurlijk, maar daardoor schakel je een 'extra' controle door PinC zelf uit (i.e. als een geoitem niet wordt herkend is dit meestal een aanwijzing dat er iets mis is). Kan de Beta eventueel twee keer per jaar vernieuwd worden, vlak na de update van de wijken? In dat geval zou dit probleem zich niet meer stellen...

**Comment by Emilien-Dupont** [comment]
Ik heb gevraagd aan Richard of hij nu ofwel alle aanpassingen aan de gebiedsniveaus van de voorbije maanden ook kan doorvoeren in de beta, of dat het misschien makkelijker is om de beta in zijn geheel te vernieuwen, maar dan binnen een paar weken zodat er geen werk van andere collega's verloren gaat. Bij de volgende verwerking van de gebiedsniveaus zal ik duidelijk communiceren dat deze ook in de beta doorgevoerd moeten worden. 

Omdat we nooit op voorhand weten wanneer de gebiedsniveaus juist opgeladen kunnen worden, vind ik het nogal lastig om dan ook daar direct de vernieuwing van de beta aan vast te hangen. Dan kan het zijn dat collega's niet genoeg tijd hebben of op verlof zijn zodat er werk in de beta verloren kan gaan.
