### ISSUE TITLE
data warmtenetten VREG

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#437]
Sinds 2019 moeten warmtenetten in Vlaanderen zich melden bij de VREG. Op basis van deze meldingen heeft de VREG een warmtenetkaart opgesteld, zie [link](https://dashboard.vreg.be/report/Warmtenetkaart.html). Van zodra een nieuw warmtenet correct bij de VREG is gemeld, wordt het toegevoegd aan de kaart. Jaarlijks bevraagt de VREG de warmteleveranciers en netbeheerders over het aantal aansluitingen en de hoeveelheid warmte die zij hebben geleverd gedurende het afgelopen kalenderjaar.  

Voorstel **nieuwe indicatoren** in PinC:
**Warmtenetten**: totaal aantal warmtenetten 
**Huishoudelijke warmtenetten**: aantal warmtenetten met enkel huishoudelijke afnemers 
**Niet-huishoudelijke warmtenetten**: aantal warmtenetten met enkel niet-huishoudelijke afnemers 
**Gemengde warmtenetten**: aantal warmtenetten met zowel huishoudelijke als niet-huishoudelijke afnemers 
**Huishoudelijke aansluitingen**: aantal contracten afgesloten met huishoudelijke afnemers 
**Niet-huishoudelijke aansluitingen**: aantal contracten afgesloten met niet-huishoudelijke afnemers 

voorgestelde plaats binnen de themaboom:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/b2e3583e-e49f-4b7a-98dc-9943906b1588)

opgeladen indicatoren:
https://provincies.incijfers.be/admin/jive?var=v2503_warmtenet_aansluiting_huish,v2503_warmtenet_aansluiting_niethuish,%20v2503_warmtenet,v2503_warmtenet_hh,v2503_warmtenet_nhh,v2503_warmtenet_gemengd

Enkele aandachtspunten bij deze cijfers: 
Mogelijks zijn er nog niet-aangemelde warmtenetten die niet in de cijfers zijn opgenomen.  
Het aantal aansluitingen is lager dan het aantal effectieve afnemers. Denk aan een appartementsgebouw met meerdere huishoudens waarbij de VME het contract heeft gesloten met de leverancier. Dit telt als 1 aansluiting. 
De informatie over de warmteleveringen is commercieel gevoelig en kan niet beschikbaar worden gesteld. Er zijn ook geen gegevens beschikbaar over de warmtebronnen/gebruikte energiedragers. 

Voor gebruik in rapport Klimaat en Energie + op termijn in product voor Fossiel Wonen en Bouwen.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 20/02/24:
Wordt nog in de provinciale teams besproken. Tegen 01/03 geeft iedereen advies. 
Duidelijk in metadatafiche zetten dat er een onderschatting is. Stefan vraagt nog na hoeveel achterstand er kan opzitten

**Comment by Tine-VB** [comment]
Akkoord om het er op te zetten voor VLBR. Wel opletten: er staat nu een streepje (geen waarde) in plaats van een 0 in gemeenten waar geen enkel type warmtenet is. Dat moeten nog allemaal nullen worden.
