### ISSUE TITLE
Nieuwe indicatoren: mediaan bouwjaar en recentste wijziging (bewoonde) woongelegenheden

### ISSUE THREAD

**Issue by SarahMeire** [provinciesincijfers/PinC-taakopvolging#438]
In het kader van energie-armoede kwam de vraag naar een indicator over het gemiddelde bouwjaar van woongelegenheden. Gezien het technisch onmogelijk is om het gemiddelde te berekenen gezien de oudere bouwjaren in categorieën zitten, werden mediaanwaarden berekend. Op basis van de Kadastergegevens werden er vier nieuwe indicatoren opgesteld (op niveau statistische sectoren, gemeente, provincie, en gewest):

- Mediaan bouwjaar woongelegenheden (v2210_mediaan_bj_wgl)
- Mediaan bouwjaar bewoonde woongelegenheden (v2210_mediaan_bj_wgl_bewoond)
- Mediaan laatste wijziging woongelegenheden (= het bouwjaar of de laatst gekende wijziging) (v2210_mediaan_lw_wgl)
- Mediaan laatste wijziging bewoonde woongelegenheden (v2210_mediaan_lw_wgl_bewoond)

Een proefversie werd opgeladen in de bèta (voor data 2023) en gecontroleerd door Stefan. Het script kan ook gerund worden op data 2018-2022. Indien akkoord van de Redactiegroep, zal de metadatafiche overeenkomstig uitgebreid worden.

Wordt voorgelegd op de Redactiegroep van 20/02/2024.

**Comment by SarahMeire** [comment]
Stand van zaken:

- Alle jaargangen (2018-2023) zijn gerund en werden opgeladen in de **Bèta** onder _Admin only > Sarah > Mediaan bouwjaar en mediaan recentste wijzigingsjaar_. De 2023 data zijn reeds gecontroleerd door Stefan (in de vorige Bèta versie).
- De naam en codes van de indicatoren werden nog licht aangepast zodat ze meer in lijn zijn met de bestaande kadasterindicatoren _bouwjaar_ / _recentste wijziging_.
- Een voorstel voor hun **plaats in de themaboom** en de aanpassing van de **metadatafiche**: 
[voorstel_indicatoren_mediaan_bjlw.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14588236/voorstel_indicatoren_mediaan_bjlw.docx). Voor te leggen op RG 19/03 voor finaal akkoord en upload alfa.

**Comment by Emilien-Dupont** [comment]
Redactie 19/03/24:
plaats themaboom is oke
VLB: akkoord om extern te plaatsen. Deadline andere provincies: 22/03/24

**Comment by Lievendr** [comment]
Antwerpen is akkoord

**Comment by karolienbloemen** [comment]
ok voor Limburg

**Comment by EmielGrimonprez** [comment]
Oké voor Oost-Vlaanderen
