### ISSUE TITLE
Rapport kerncijfers voor provincie

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#44]
Het rapport kerncijfers is opvraagbaar voor niveau gemeenten en provincie. Wanneer echter provincie wordt gekozen, zijn aanpassingen in het rapport nodig

- [x] introtekst: vermelden van 'provincie' ipv 'gemeente'
- [x] grafieken: enkel bollen worden getoond, geen vergelijkingsgebied. Kan een balk voor Vlaams Gewest worden getoond?

andere globale aanpassing nodig: 
- [x] De grafiek secundair onderwijs bevat een "UITDOVEND" onderwerp

**Comment by joostschouppe** [comment]
Volledig gefixed. Wel nog een klein issue: lukt niet meer om provincie als standaard vergelijkingsgebied in te stellen voor gemeenten. Ingeseind bij ABF.
