### ISSUE TITLE
vernieuwing dashboard

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/PinC-taakopvolging#440]
Mockup Dashboard: https://beta-provincies.incijfers.be/dashadmin/preview/test/

Na open office van 22/02/24:
Front Dashboard:
- Bovenaan: tegel Dashboard, Rapporten en Databank
- Tussenbalk: In de kijker; met lay-out van bv. het overzicht rapporten
- Tegels met in de kijkers: 
  - Als je klikt op een in de kijker, zou je ook eerst meer informatie te zien moeten krijgen en nog niet direct doorverwezen worden naar bv. een externe pagina
  - Overzicht met voorgaande In de kijkers + nagaan of we linken naar documenten kunnen maken. Inspiratie opdoen bij limburg.incijfers
- Tussenbalk: Informatie
- Tegels met: Nieuwsbrief, Informatie, Contact en Opleidingen
- Banner met Dashboard Databank Over deze site en Contact moet weg. Indien onmogelijk: aanvullen met Rapporten
- Geen zoekfunctie en Gebiedskiezer

Dashboard met de oorspronkelijke thematische dashboards:
- Hier ook de bronnenpagina zetten
- Banner met Dashboard Databank Over deze site en Contact aanvullen met Rapporten
- Zoekfunctie en gebiedskiezer

**Comment by Emilien-Dupont** [comment]
Een nieuwe versie staat klaar: https://beta-provincies.incijfers.be/dashadmin/preview/test/
Je kan doorklikken op: 
- Dashboard
- Kansarmoedeatlas
- Archief
- Contact
- Nieuwsbrief
- Opleidingen

De kleuren en iconen van de nieuwe tegels zitten nog niet volledig goed:
- Dashboard: foute kleur
- Kansarmoedeatlas: icoon gekozen uit beschikbare iconen. Heeft zwarte kleur
- Archief, Contact en Opleidingen: icoon gekozen uit beschikbare iconen

**Comment by Emilien-Dupont** [comment]
Redactie 19/03/24:
- Dashboardtegel laten doorlinken naar het echte Dashboard
- Volgorde aanpassen: eerst Dashboard, dan Rapporten en dan Databank
- Iconen laten maken door de grafische dienst WVL: Dashboard en opleidingen
- Tekstbalken weg en In de kijker helemaal bovenaan zodat alles op twee lijnen staat en je niet moet scrollen
- Archief: weglaten. Eventueel kan 'Studies' in de plaats komen waaronder dan de Kansarmoede atlas en de uitrustingsgraad kan komen
- Opleidingen: een teksttegel voor elke provincie. De provincie is zelf verantwoordelijk voor hun eigen vak. Je kan hier ofwel doorlinken naar de provinciale opleidingen ofwel iets zetten als: 'als je een opleiding wenst, kan je contact opnemen met...'

**Comment by Emilien-Dupont** [comment]
De nieuwe versie kan je bekijken in de bèta: https://beta-provincies.incijfers.be/dashboard/test/
De tegels die al een inhoud hadden in het oorspronkelijke dashboard, heb ik naar daar laten doorlinken (nieuwsbrief, rapporten en gebruik van de website). Het vervelende is dan wel dat je dan op het oorspronkelijke dashboard terechtkomt en niet meer op het nieuwe:

![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/77432663/dbea51e8-791e-4b19-add3-2ae82e4b4c4f)

(home = oorspronkelijke dashboard). Deze tegels zullen dus opnieuw aangemaakt moeten worden.

**Comment by StefanJacques** [comment]
VRAAG: opletten met timing (gezien onze nieuwe tegel SDG op ons huidige dashboard en communicatie SDG-webinar op 07/05) - **wanneer zou dit online komen ?**

**Comment by Emilien-Dupont** [comment]
RG 18/4/24:
naar databank = databank
gebruik website naar boven, studies naar beneden, contact meer naar rechts.
we rollen pas in juni uit.
Emilien stelt nog de vraag aan ABF.

**Comment by Emilien-Dupont** [comment]
IPWG 28/5/24:
voorstel om, net zoals bij opeldiingen, ook door te linken naar provinciale webpagain's waar je provinciale studies kan terugvinden. Iets in de aard van: 'Wil je meer weten over provinciale studies, klik dan op de volgende linken'. Elke provincie levert een URL aan waarnaar verwezen kan worden.

**Comment by Emilien-Dupont** [comment]
Redactie 18/06/24
Tegen de zomervakantie stuurt elke provincie een tekst door mbt studies en rond opleidingen.

**Comment by Lievendr** [comment]
Heb je hulp nodig bij het gebruik van de databank of bij de interpretatie van cijfers en rapporten? 
De collega’s van [Data & [Analyse](url)](https://www.provincieantwerpen.be/lokale-besturen/gemeenten-in-beweging/data-en-analyse/provincie-in-cijfers.html) helpen je graag verder.

**Comment by Emilien-Dupont** [comment]
OVL:
- PinC-pleidingen in Oost-Vlaanderen: https://bestuursopleiding.paulo.be/opleidingen/2050
- geen link voor studies

**Comment by KoenSnyers** [comment]
@Emilien-Dupont 

Voor LIM:

- Verwijzing naar onze studies (in de vorm van onze Limburgse cijferdossier)s mag via de link naar deze pagina op onze website: https://limburg.incijfers.be/dossiers
- Voor opleidingen mag er gelinkt worden naar de info & contactpagina op onze website: https://limburg.incijfers.be/content/Info----Contact

**Comment by HildeC** [comment]
voorziene opleidingen in West-Vlaanderen  - najaar 2024

**Comment by Tine-VB** [comment]
Voor Vlaams-Brabant (ook al eerder doorgegeven, maar voor de volledigheid):
Opleidingen: https://www.vlaamsbrabant.be/nl/over-de-provincie/over-vlaams-brabant/cijfers-en-studies/workshop-provinciesincijfersbe
(de vermelding 'Wil je een opleiding op maat: stel je vraag aan data.analyse@vlaamsbrabant.be' mag er ook bij als dat bij de andere provincies wordt gedaan)
Studies: https://share.vlaamsbrabant.be/Informatie-en-technologie/Steunpunt-Data-&-Analyse/

**Comment by Emilien-Dupont** [comment]
Het nieuwe dashboard wordt maandag gelanceerd

**Comment by Emilien-Dupont** [comment]
Voorstel Stefan:

![afbeelding](https://github.com/user-attachments/assets/78c08ad6-9462-4a85-a0d8-cf35d5ad5af5)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/09/24:
Contacttegel gaat hoogstwaarschijnlijk verdwijnen: 5 5 links uitgelijnd

**Comment by Emilien-Dupont** [comment]
Voorlopig nieuw dashboard: https://provincies.incijfers.be/dashadmin/preview/dashboard/

**Comment by emdockx** [comment]
> Voorlopig nieuw dashboard: https://provincies.incijfers.be/dashadmin/preview/dashboard/

Zouden die twee witte tegels ook niet onder elkaar kunnen voor een net iets strakker zicht? (rap rap in photoshop een voorbeeldje gemaakt):

![Screenshot 2024-10-17 at 09 21 copy](https://github.com/user-attachments/assets/fe1001e4-3033-44a0-89ec-3fadb4939044)

**Comment by StefanJacques** [comment]
[like]  Jacques Stefan reacted to your message:

Met vriendelijke groeten
Stefan Jacques
expert limburg.incijfers.be
Data en Analyse
Provinciebestuur Limburg
Universiteitslaan 1 - 3500 Hasselt
Tel.: 011 23 72 32| Gsm: 0471 80 63 02
De bovenvermelde berichten/teksten, bijlagen verbinden de provincie Limburg op geen enkele wijze tenzij anders overeengekomen
bij een schriftelijke overeenkomst of tenzij zij later worden bevestigd bij een overeenkomstig de decretale voorschriften ondertekende
brief. Evenmin kan de provincie Limburg aansprakelijk worden gesteld op grond van de inhoud van deze berichten/teksten, bijlagen.
Denk even aan het milieu voor je deze mail print.
________________________________

**Comment by Emilien-Dupont** [comment]
Redactiegroep 17/10/24:
We volgen Manu zijn voorstel

**Comment by Emilien-Dupont** [comment]
Staat online sinds vorige maandag

**Comment by Emilien-Dupont** [comment]
Suggestie studies: 
- onderzoek naar de samenwerking tussen de Vlaamse maatwerkbedrijven en de reguliere bedrijven als meerwaarde voor de economie (dateert wel al van 2021);
- laatste rapport over de Vlaamse arbeidszorgmedewerkers (dateert van 2023).
[20211130-SamenwerkingMaatwerkbedrijvenReguliereEconomie-EINDRAPPORT.pdf](https://github.com/user-attachments/files/17714529/20211130-SamenwerkingMaatwerkbedrijvenReguliereEconomie-EINDRAPPORT.pdf)
[Rapport De Vlaamse arbeidszorgmedewerker in beeld 2018-2022_eindversie.pdf](https://github.com/user-attachments/files/17714530/Rapport.De.Vlaamse.arbeidszorgmedewerker.in.beeld.2018-2022_eindversie.pdf)

**Comment by Emilien-Dupont** [comment]
Redactiegroep 18/11/24:
We nemen enkel de tweede studie op.
