### ISSUE TITLE
Klimaat in provincies.incijfers - aanpassingen namen rapporten en subthema's in de themaboom

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#442]
Collega's klimaat hebben een nieuw voorstel uitgewerkt voor aanpassing van de **benaming van de rapporten**, meer **duidelijkheid in het dashboard**  en een lichte wijziging van de structuur in de themaboom - die samengaat met de wijziging van de inhoudstafel in hun rapport Klimaat - mitigatie.

Alles is verwerkt in:

Ik probeer de grote lijnen te vatten.

1) naamgeving rapporten wijzigen
Rapport klimaat - **mitigatie** (i.p.v. Rapport klimaat en energie)
Rapport klimaat - **verwachte verandering** (i.p.v. Rapport klimaatscenario's)
Rapport klimaat - **adaptatie** (i.p.v. Rapport klimaatadaptatie)
Cijfers klimaat - **mitigatie** opgelijst (i.p.v. Cijfers klimaat opgelijst)

2)
VRAAG - mag er op de titelpagina van een rapport een SUBTITEL worden toegevoegd ?

Rapport klimaat – mitigatie
**subtitel = Verminderen van de broeikasgasuitstoot - maatregelen**
Rapport klimaat - adaptatie
**subtitel  = Aanpassen   aan de gevolgen van het veranderende klimaat - maatregelen**
Rapport klimaat – verwachte verandering
**subtitel = Voorspelde toestand, effect en impact**

3) dashboard onduidelijk -->"Klimaatadaptatie" je weet niet dat er een subdashboard Klimaat - adaptatie onder zit
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/cb803b75-44b3-43fc-86fb-5a73c9eed20e)
voorstel: toevoegen **Dashboard klimaat - verwachte verandering en adaptatie**

4) themaboom wijzigingen
subthema Energie ---> Klimaatmitigatie
subthema Adaptatie [klimaatscenario's VMM] ---> Klimaatadaptatie [scenario's VMM]
sub-subthema Klimaat ---> Klimatologische parameters
subthema "Niet-energiegerelateerde broeikasgasemissie door landbouw" ---> verplaatsen naar subthema Klimaatmitigatie

**Comment by HildeC** [comment]
akkoord, voor niet-klimaatmensen maakt de ondertitel veel duidelijk

**Comment by demaesschalckfilip** [comment]
Het scenario dat wordt gebruikt is het hoog impactscenario. Dat komt overeen met de bovengrens van het 95% betrouwbaarheidsinterval. Dat is erg ongebruikelijk: alle gegevens van enquêtes die we publiceren zouden op die manier fout zijn op het 90%-interval (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/383).  Maar oké, het staat in de infofiche, en de andere scenario’s worden niet gepubliceerd door de VMM. Maar om dat nu _verwachte verandering_ te noemen, dat vind ik eigenlijk niet meer ernstig.  Een mogelijk alternatief: titel: 'Voorspelde klimaatverandering'; subtitel: 'Hoog-impactscenario'

**Comment by StefanJacques** [comment]
antwoord klimaat:

Hoog impact mag in subtitel vermeld wat mij betreft, maar ik zou wel analogie met andere titels behouden.
En ook onze subtitel behouden ‘voorspelde toestand, effect en impact’

Dus voorstel:
Titel: **Klimaat – voorspelde verandering**
Subtitel: **Voorspelde toestand, effect en impact volgens het hoog-impactscenario**

Ik veronderstel dat dit wel tegemoet komt aan bedenking van uw collega

**Comment by StefanJacques** [comment]
voor de rapporten die een subtitel nodig hebben: welke layout ?

h1 maar dan zonder het grafiek-icoontje (als dat kan aangemaakt worden ?)
of
h2 vette titel

voorbeeld:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/9fd4e118-6e25-4eda-9ba4-709951a7a1a6)

**Comment by Emilien-Dupont** [comment]
Redactie 19/03:
Verandering naam rapporten + subtitels: akkoord.
Subtitel in blauwe balk. Geert maakt deze week een paar voorstellen op. 
In de subdashboards mag vooraan 'Dashboard' komen in de naam.
Themaboom mag gewijzigd worden.

**Comment by GeertBonte** [comment]
Subtitels in rapporten zijn geïmplementeerd: `<h1 class="subtitel">...</h1>`

Voorbeeld:

![test_klimaat](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/101627698/314c72ca-d298-4351-b047-c8ac03fdaf82)

**Comment by Emilien-Dupont** [comment]
En ook toegevoegd aan de sjablonen
