### ISSUE TITLE
zonneboilers i.p.v. zonnecollectoren

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#443]
Vraag van collega's Klimaat (Yves Pepermans - provincie Antwerpen)
Bij nieuwbouw spreken we van **zonnecollectoren** in de databank bij energiepremies over **zonneboilers**. Ik zou pleiten voor een eengemaakte formulering. Ik vermoed dat zonneboilers de meest bekende term is.

het gaat over deze onderwerpen:
v2207_nbw_zoncol | nieuwbouwwoningen met zonnecollector
v2207_nbw_zoncol_ander | nbw met zonnecollector -  andere   residentiële gebouwen
v2207_nbw_zoncol_app | nbw met zonnecollector -    appartementen
v2207_nbw_zoncol_gesl | nbw met zonnecollector -  gesloten   eengezinswoningen
v2207_nbw_zoncol_hopen | nbw met zonnecollector - halfopen eengezinswoningen
v2207_nbw_zoncol_open | nbw met zonnecollector - vrijstaande eengezinswoningen
vp2207_nbw_zoncol | nieuwbouwwoningen met een zonnecollector (t.o.v. nieuwbouwwoningen)
vp2207_nbw_zoncol_ander | nbw - andere residentiële gebouwen met zonnecollector (t.o.v. nbw -   andere res. geb.)
vp2207_nbw_zoncol_app | nbw - appartementen met zonnecollector (t.o.v. nbw - appartementen)
vp2207_nbw_zoncol_gesl | nbw - gesloten eengezinswoningen met zonnecollector (t.o.v. nbw -   gesloten eengezinsw.)
vp2207_nbw_zoncol_hopen | nbw - halfopen eengezinswoningen met zonnecollector (t.o.v. nbw -   halfopen eengezinsw.)
vp2207_nbw_zoncol_open | zonnecollector aanwezig in vrijstaande eengezinswoningen (t.o.v.   vrijstaande eengezinswoningen)
v2207_nbw_zoncol_t5 | nieuwbouwwoningen met zonnecollector (laatste 5 jaar)
v2207_nbw_zoncol_ander_t5 | nbw met zonnecollector -  andere   residentiële gebouwen (laatste 5 jaar)
v2207_nbw_zoncol_app_t5 | nbw met zonnecollector -    appartementen (laatste 5 jaar)
v2207_nbw_zoncol_gesl_t5 | nbw met zonnecollector - gesloten eengezinswoningen (laatste 5 jaar)
v2207_nbw_zoncol_hopen_t5 | nbw met zonnecollector - halfopen eengezinswoningen (laatste 5 jaar)
v2207_nbw_zoncol_open_t5 | nbw met zonnecollector - vrijstaande eengezinswoningen (laatste 5 jaar)
vp2207_nbw_zoncol_t5 | nieuwbouwwoningen met zonnecollector (t.o.v. nbw), laatste 5 jaar
vp2207_nbw_zoncol_ander_t5 | nbw - andere residentiële gebouwen met zonnecollector (t.o.v. nbw-andere   res.geb.), laatste 5 jaar
vp2207_nbw_zoncol_app_t5 | nbw - appartementen met zonnecollector (t.o.v. nbw - appartementen),   laatste 5 jaar
vp2207_nbw_zoncol_gesl_t5 | nbw - gesloten eengezinswoningen met zonnecollector (t.o.v. nbw - gesl.   eengezinsw.), laatste 5 jaar
vp2207_nbw_zoncol_hopen_t5 | nbw - halfopen eengezinswoningen met zonnecollector (t.o.v. nbw-halfopen   eengezw.), laatste 5 jaar
vp2207_nbw_zoncol_open_t5 | zonnecollector in vrijstaande eengezinswoningen (t.o.v. vrijstaande   eengez., laatste 5 jaar)
v2207_nbw_zoncol_opp | oppervlakte zonnecollectoren bij nbw
v2207_nbw_zoncol_prod | productie zonnecollectoren bij nbw
v2207_nbw_zoncol_egw | nbw met zonnecollector -    eengezinswoningen
vp2207_nbw_zoncol_egw | nbw - eengezinswoningen met zonnecollector (t.o.v. nbw -   eengezinswoningen)
v2207_nbw_zoncol_egw_t5 | nbw met zonnecollector -    eengezinswoningen (laatste 5 jaar)
vp2207_nbw_zoncol_egw_t5 | nbw - eengezinswoningen met zonnecollector (t.o.v. nbw -   eengezinswoningen), laatste 5 jaar

**Comment by StefanieWVL** [comment]
Geen bezwaar, in tegendeel volgens mij is zonneboiler ook de juiste term. Zonneboiler verwijst naar het volledige systeem om warm water te produceren en de zonnecollectoren zijn daar er een onderdeel van.

**Comment by Emilien-Dupont** [comment]
Redactie 19/03/24:
akkoord
