### ISSUE TITLE
Nieuwe indicatoren bodembezetting

### ISSUE THREAD

**Issue by SarahMeire** [provinciesincijfers/PinC-taakopvolging#445]
### Voorstel nieuwe indicatoren bodembezetting:

Samenvatting voorstel (nieuwe indicatoren, plaats in de themaboom en aanzet aanpassing metadatafiches): 
[voorstel_indicatoren_bodembezetting.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/14586402/voorstel_indicatoren_bodembezetting.docx). De indicatoren werden opgeladen in de **Beta** onder _Admin only > Sarah > Statistiek van de bodembezetting._

### Context:

Vandaag zijn er in PinC 4 indicatoren uit de Statbel Statistiek van de Bodembezetting, tot gebiedsniveau ‘gemeente’:

•	Oppervlakte voor bedrijvigheid (v1501_bedrijvigheid)
•	Oppervlakte voor bedrijvigheid t.o.v. bebouwde oppervlakte (vp1501_bedrijvigheid)
•	Oppervlakte bebouwde percelen (v1501_bebouwd)
•	Oppervlakte bebouwde percelen t.o.v. oppervlakte (vp1501_bebouwd)

De dataset van Statbel is echter nog veel uitgebreider, met indicatoren die de **precieze bodembezetting** van de onbebouwde en bebouwde percelen weergeven. Deze data zijn wederom enkel tot op gemeenteniveau beschikbaar. Op basis van de eigen kadasterverwerking kunnen we deze indicatoren ook op statistisch sectorniveau en daardoor op alle daarop gebouwde gebiedsniveaus berekenen. In januari ’24 werd contact opgenomen met de FOD Economie om de vertaalslag tussen enkele zgn. ‘nature codes’ en ‘nis-indelingen’ (= samenvattende categorieën van bodembezetting) op te helderen / te verifiëren. Hierdoor werden de verschillen tussen beide databronnen merkelijk kleiner. Een vergelijkende analyse (zie [werkdocument ](https://vlbr.sharepoint.com/:w:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Ruwe%20data/FOD%20Financi%C3%ABn%20-%20Kadaster/projectwerking/Landgebruik/samenvatting_lgb_analyse.docx?d=wc63b8b0d7d144bc9b2b95ca2ba0f564f&csf=1&web=1&e=nYDjRs) en [analyse](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Ruwe%20data/FOD%20Financi%C3%ABn%20-%20Kadaster/projectwerking/Landgebruik/vergelijking%20met%20Statbel/vgl_opp_pinc_statbel.xlsx?d=w1ded351eed11407cb0ef62969a135e49&csf=1&web=1&e=qcdPkJ)) tussen de Statbel data en de kadasterdata toont echter nog steeds wat discrepanties aan, dewelke vermoedelijk (deels) te wijten zijn aan het niet helemaal actueel zijn van de kadasterdata. Ook bovenstaande vertaalslag kan hierbij nog een kleine rol spelen. Het verschil varieert bovendien sterk doorheen de tijd (nl. een verwaarloosbaar verschil voor data 2021 en 2023, een wat groter verschil voor data 2018, 2019, 2020 en 2022). Daarom opteert de kadaster werkgroep voor het opladen van **beide gegevensreeksen**, nl. de **officiële statistiek** en de **eigen verwerking** – conform andere gegevensreeksen in PinC. Op die manier kunnen we deze data ook op statistische sectorniveau aanbieden.

**Comment by Emilien-Dupont** [comment]
Redactiegroep 19/03/25:
Iedereen bekijkt dit tegen 25/03.

**Comment by emdockx** [comment]
Antwerpen is akkoord met indicatoren, themaboom en metadata.
@SarahMeire, ik wil eventueel wel controleren.

**Comment by karolienbloemen** [comment]
- het lijkt me niet nodig de eenheid in de indicatornaam te vermelden
- plaats in de themaboom ok (ik denk niet dat het verwarrend is met de map onbebouwde percelen obv ROP)
- de bestaande onderwerpen die al in PinC zijn opgenomen zou ik niet gewoon tussen de andere plaatsen omdat dat een som is van enkele anderen (bv als dan de hele reeks wordt opgevraagd zit je met dubbels) - beter met onderliggende map werken?

**Comment by EmielGrimonprez** [comment]
Oost-Vlaanderen is akkoord met voorstel Sarah en opmerking Karolien om eenheden niet in de indicatornaam te vermelden

**Comment by emdockx** [comment]
Controle uitgevoerd: data zijn ok om te publiceren.
Nog een paar kleine details te bekijken @SarahMeire:

In de indicatornamen staan bij de eigen verwerking telkens een spatie te veel (vlak voor de code tussen haakjes).
En ik vraag me ook af of we twee keer de eenheid moeten aanduiden (zie groen) (ook het geval bij de officiële statistiek).
Bijvoorbeeld “akkerland, niet elders genoemd  (1AE) in m² [m²]”.
Bij de meeste indicatoren rond ruimtegebruik op PinC zetten we de eenheid niet in de naam.
Dat komt normaal automatisch bij in de naam als je de indicator opvraagt in een tabel.

Ander klein detail, bij de officiële statistieken heb je twee keer een indicator “andere”.
In de eigen verwerking verduidelijk je met “onbebouwd” en “bebouwd”.
In de officiële statistiek geef je de aanduidingen “1MNOP” en “2RST” mee.
Als dat dezelfde insteek is als bij de officiële statistiek moeten we daar misschien ook “onbebouwd” en “bebouwd” bijzetten?

Bij de indicatoren eigen verwerking:
“ambacht - en industriegebouwen” staat nog een spatie voor het koppelteken
“banken,kantoren” spatie toevoegen
