### ISSUE TITLE
Stories-figuur --> extra info

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#450]
in Stories kan je een figuur **op 2 manieren** van **extra informatie** voorzien

1
als je op een figuur verder klikt (= gelijkaardig aan de linkermuisknop gebruiken in de databank en bijgevolg aan te leren in workshops aan onze klanten) krijg je steeds **extra informatie** die (hoogstwaarschijnlijk) **uit ons nieuwe metadatasysteem** komt.

klik op:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/fb35d017-3e60-4cab-b317-f12487e5c864)

en krijg:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/723775fd-c119-4b64-8eff-f845e3e663e2)

als je vervolgens op MEER INFO klikt verschijnt
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/e7a2cb08-6d47-4646-aaf4-69fe0aefb2e6)

zoals je kan zien, kunnen we daar MANUEEL een bepaalde "Toelichting" toevoegen:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/fa807816-923a-423f-85a4-a6f070a549bf)

Maar de overige gekozen velden die in deze popup verschijnen lijken dus te komen uit de metadatavelden
_Toelichting --> enkel als je daar dus MANUEEL iets invult_
Onderwerpen --> beschrijving van getoonde onderwerp(en)
Bronnen = korte naam
Referenties --> link naar onze pdf-metadatafiche

2
via een uitvalmenu "meer info" dat je al krijgt als je in de Stories zelf aan het navigeren bent
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/4dfe8127-c724-4a1f-a7b0-a9436c1aeef8)

klik op meer info:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/31841732/f31ce429-2ae2-436d-bab3-aafdf46f81a2)

We moeten er eens over nadenken wat we op welke manier onder de aandacht willen brengen in de toekomstige Stories-rapporten.
Graag eens bespreken op een Redactiegroep

**Comment by Emilien-Dupont** [comment]
Dit hangt samen met https://github.com/provinciesincijfers/PinC-taakopvolging/issues/318. Wat je zal zien in de Mosaic Detailview, zie je ook bij de tegels van Stories (nummer 1 hierboven van extra info)

**Comment by Emilien-Dupont** [comment]
RG 18/04/24:
We parkeren het tot het nieuwe metadatasysteem wordt uitgerold en nemen het dan verder op in de Stories werkgroep.
