### ISSUE TITLE
Presentatie exporteren - deel van onderwerpnaam verdwijnt!

### ISSUE THREAD

**Issue by GeertBonte** [provinciesincijfers/PinC-taakopvolging#455]
Er is een probleem bij het exporteren van presentaties uit de databank (bv. bij opslaan als afbeelding, maar ook bij opslaan als Word- of Excel-bestand) wanneer de presentatie bestaat uit meerdere onderwerpen met een gemeenschappelijk deel aan het begin van de onderwerpnamen. Dat deel van de onderwerpnaam verdwijnt dan namelijk.

Kijk bijvoorbeeld wat er gebeurt met grafiek 1.6 uit hoofdstuk 1 van de omgevingsanalyse:

![grafiek_in_rapport](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/101627698/94bb7f15-bc16-4e54-8422-9eb39e8eea15)

In het rapport zie je drie deelgrafieken, met onder elke deelgrafiek de naam van het betreffende onderwerp:

- _niet-Belgische_ huidige nationaliteit (t.o.v. inwoners)
- _niet-Belgische_ geboortenationaliteit (t.o.v. inwoners)
- _niet-Belgische_ herkomst (t.o.v. inwoners)

Deze drie onderwerpen hebben ‘niet-Belgische’ gemeenschappelijk aan het begin van hun naam.

Als je dezelfde grafiek opent in de databank, dan ziet dat er zo uit:

![grafiek_in_databank](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/101627698/8c1b5864-9752-46c1-a237-290fa2a743e6)

Het gemeenschappelijke deel (‘niet-Belgische’) verhuist naar de blauwe balk boven de grafiek, en onder de deelgrafieken zie je nu slechts het resterende deel van de onderwerpnaam staan:

- huidige nationaliteit (t.o.v. inwoners)
- geboortenationaliteit (t.o.v. inwoners)
- herkomst (t.o.v. inwoners)

Een beetje vreemd als je ’t mij vraagt, maar tot daaraan toe. Wanneer je nu echter de grafiek exporteert, bijvoorbeeld naar een PNG-afbeelding, dan krijg je dit:

![grafiek_export](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/101627698/3e70f3ba-5188-48de-8044-f7a212cbc791)

Onder de deelgrafieken zie je nog steeds maar een deel van de onderwerpnaam, maar het gemeenschappelijke deel, ‘niet-Belgische’, is nergens meer te bespeuren! Dat is nochtans essentiële informatie, die hier zomaar verdwijnt. Boven de geëxporteerde grafiek staat nu ‘Nationaliteit en herkomst’. Dat komt niet uit de onderwerpnaam, maar uit de themaboom.

Voor zover ik weet hebben we geen mogelijkheid om dit aan te passen. Het is ongetwijfeld wenselijk om bij een export de correcte onderwerpnamen te gebruiken zonder dat er een deel ervan in het niets verdwijnt. Idealiter zou een uit de databank geëxporteerde grafiek eruit moeten zien zoals de grafiek in het rapport, dus met de volledige onderwerpnamen bij elke deelgrafiek. Maar het gaat niet alleen om grafieken. Hetzelfde probleem doet zich voor wanneer je de presentatie exporteert als Excel-tabel. Bij export als CSV gaat het daarentegen wél goed: het CSV-bestand bevat wél de correcte onderwerpnamen (maar de CSV-export heeft dan weer andere problemen...).

**Comment by Tine-VB** [comment]
Een ander probleem met exports doet zich voor bij Stories, waar de titels van de figuren afgekapt blijven bij het trekken van een pdf. Maar in tegenstelling tot op het scherm, kan je er natuurlijk niet over hooveren om ze volledig te zien: 
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/61458346/3c29c801-0f55-4bef-afde-bd024feeb659)
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/61458346/44785e4c-435f-4499-b018-b7b89b549046)
ABF zou daar wel wat meer aandacht mogen voor hebben...

**Comment by Emilien-Dupont** [comment]
Dit werd doorgegeven aan ABF

**Comment by Emilien-Dupont** [comment]
Het probleem van het verdwijnen van een deel van de onderwerpnaam werd verholpen.
Wanneer je nu exporteert naar PNG krijg je:
![image](https://github.com/provinciesincijfers/PinC-taakopvolging/assets/77432663/26874673-af45-462f-aece-70a5fb615c46)
