### ISSUE TITLE
Vervanging logboek

### ISSUE THREAD

**Issue by dgees** [provinciesincijfers/PinC-taakopvolging#456]
Er is een voorstel om het Excel bestand waarin we de matomo links voor de nieuwsbrief aanmaken te vervangen door een nieuw bestand waarin we het logboek combineren met het matomo nieuwsbrieflinken bestand, [zie teams](https://vlbr.sharepoint.com/:x:/r/teams/DA-Interprovincialewerking/Gedeelde%20documenten/Communicatie/PinC%20nieuwsbrief/nieuw%20logboek.xlsx?d=w5635d830d5fe4aacbf95c83d7e401f66&csf=1&web=1&e=8XKpww). 

(Dit nieuwe bestand wordt momenteel voor het eerst gebruikt voor de nieuwsbrief, nog niet als logboek. )

Voordeel is dat alles dan in 1 bestand staat en er geen links gecopypaste moeten worden in een apart Excel bestand. En aangezien het huidige logboek een 'rapport' is, moeten we wellicht sowieso een andere oplossing hiervoor vinden. 

Tegen volgende redactie graag in de teams nagaan of er tegenargumenten zijn om het logboek te vervangen door de nieuwe Excel en eveneens nagaan of er nog aanpassingen nodig zijn in de Excel.

**Comment by Emilien-Dupont** [comment]
Redactie 18/06/24:
We starten vandaag met het nieuwe logboek en sluiten het oude logboek af.
