### ISSUE TITLE
Administratief beschikbaar inkomen van Statbel

### ISSUE THREAD

**Issue by HanneODB-VLBR** [provinciesincijfers/PinC-taakopvolging#457]
We publiceren op PinC reeds de fiscale inkomens, op statsec niveau. Een nadeel hiervan is dat alle inkomens die niet onder het belastingsstelsel vallen, hier niet bij zitten.

Statbel is nu naar buiten gekomen met een nieuwe indicator op gemeenteniveau 'administratief beschikbaar inkomen'. Dit is een inkomstenmaat waarbij ze de fiscale inkomens aanvullen met inkomens uit niet-belastbare inkomens en 'gesimuleerde' inkomens (voorlopig wel nog niet duidelijk hoe dergelijke simulatie tot stand komt, nog uit te zoeken):

Niet-belastbare inkomens:
Databank (equivalent) leefloon van de POD Maatschappelijke Integratie
Databanken zorgbudget voor ouderen met een zorgnood van FOD Sociale Zekerheid, Vlaamse Gemeenschap, AVIQ en Iriscase.
Databank zorgbudget voor zwaar zorgbehoevenden van de Vlaamse Gemeenschap.
Databank zorgbudget voor personen met een handicap van de Vlaamse Gemeenschap.
Databank inkomensvervangende tegemoetkoming van de FOD Sociale Zekerheid.
Databank integratietegemoetkoming van de FOD Sociale Zekerheid.

Gesimuleerd inkomen:
Kraamgeld
Kinderbijslag

Volgende posten worden in mindering gebracht:
Betaalde onderhoudsgelden
Bedrijfsvoorheffing
Voorafbetalingen
Bijzondere bijdrage voor de sociale zekerheid

Tot slot wordt rekening gehouden met de afrekening van de inkomensbelasting door het terug te betalen bedrag in mindering te brengen, of het terug te krijgen bedrag erbij op te tellen. De inkomens en uitgaveposten van alle individuele huishoudleden worden samengeteld tot het ‘administratief beschikbaar inkomen’ op huishoudniveau.

Een meer 'complete' maat voor inkomens lijkt dit dus wel te zijn, daarom vraag aan redactiegroep of ik deze kan opnemen in PinC _naast_ de fiscale inkomens (en niet ter vervanging van, omdat deze enkel op gemeenteniveau beschikbaar zijn). Het gaat om de volgende indicatoren:
Mediaan jaarlijks equivalent administratief beschikbaar inkomen
Bovengrens 1ste kwartiel jaarlijks equivalent administratief beschikbaar inkomen
Bovengrens 3de kwartiel jaarlijks equivalent administratief beschikbaar inkomen
Interkwartiel afstand - het verschil tussen het derde en eerste kwartiel van het inkomen

De cijfers zijn beschikbaar van 2015 - 2021.

**Comment by Tine-VB** [comment]
Ik zou ze misschien wel maar opnemen vanaf 2020, omwille van deze opmerking: 
De cijfers voor 2015 tot 2020 zijn ook beschikbaar
Statbel publiceert vandaag ook een chronologische reeks die teruggaat tot 2015. Omwille van een verbetering in de methodologie zijn de cijfers tot 2019 slechts tot op zekere hoogte vergelijkbaar met die vanaf 2020.
Anders worden dat weer uitgebreide metadata 😜

**Comment by StefanJacques** [comment]
ik kan Tine wel volgen - zie de extra uitleg hierover:
_De gedetailleerde informatie over de internationale ambtenaren uit de lijst van Europese instellingen is pas sinds 2020 beschikbaar, net zoals fiscale inkomens van personen die door de FOD Financiën als niet-inwoner worden beschouwd. Cijfers tot en met 2019 zijn dus van iets mindere goede kwaliteit en niet te vergelijken met cijfers vanaf 2020._

Opgelet bij het verwerken:
_Omwille van het lage bevolkingsaantal in Herstappe, zijn de resultaten van Herstappe en Tongeren samengevoegd._

**Comment by Tine-VB** [comment]
Wat Herstappe betreft: zouden we aan Statbel kunnen vragen om het cijfer voor Tongeren te krijgen, zonder Herstappe? Zodat we bij Herstappe een x kunnen zetten?

**Comment by Emilien-Dupont** [comment]
Redactie 18/06/2024:
Oke om op te nemen. @HanneODB-VLBR: kan je navragen of we de cijfers voor Tongeren kunnen krijgen, zonder Herstappe?
