### ISSUE TITLE
nieuwe data ivm eigenaar/huurder

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/PinC-taakopvolging#458]
In juni wordt in Pinc nieuwe data opgeladen mbt eigenaars en huurders.
De verwerkingsscripts werden op punt gezet, waardoor de data nu kwaliteitsvoller zijn dat wat er was.
Er werd ook met een nieuwe code gewerkt, dus bestaande datareeksen worden niet overschreven.

De rapporten en de dashboardtegels die gebruik maken van data over eigenaars en huurders moeten dus aangepast worden.
Omdat het nieuwe codes zijn, zullen er geen fouten optreden bij niet aanpassen, maar de cijfers zullen verschillend zijn, dus best te vermijden.
De bestaande indicatorcode is v(p)2210_eigenaar/v(p)2210huurder
Deze moeten vervangen worden door 
V2220_hurend_privaat_huishouden en vp2220_hurende_hh
v2220_eigenaarshuishouden en vp2220_eigenaars_hh
en desgevallend v2220_totaal_hh_onbepaald
De oude codes moeten vervolgens ook op uitdovend gezet worden 

In het excelbestand vind je in welke rapporten de 2210 eigenaars/huurders gebruikt worden. 
[Kopie van Consistency report - indicatoren in rapporten.xlsx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/15500080/Kopie.van.Consistency.report.-.indicatoren.in.rapporten.xlsx)

**Comment by Emilien-Dupont** [comment]
Daarbij aansluitend:
- als je de indicatoren verwijdert uit de themaboom, laat deze dan wel staan in de mappen van de connector, anders stroomt de info dat de indicator uitdovend is, niet automatisch door.
- Ga ook na of de indicatoren gebruikt worden in het Dashboard. Dit kan je jammergenoeg niet uit een consistency rapport trekken, maar moeten de themaverantwoordelijken zelf bekijken.
- vp2210_hh_verhuurd_bw en vp2210_hh_eig_bw gebruiken de uitdovende indicatoren in hun formule. Deze formules moeten dan ook nog aangepast worden. In het overzicht dat Hilde gaf, staan deze ook al aangegeven waar deze gebruikt worden in de rapporten.

**Comment by HildeC** [comment]
voor de duidelijkheid: hier nog een tabbel met de codes die vervangen moeten worden, en de codes die je daatvoor moet gebruiken:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hcd/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hcd/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


gebruikte   code | te vervangen door
-- | --
v2210_huishoudens | v2220_hh_met_bekende_bewoningstitel
v2210_huurders | v2220_hurend_privaat_huishouden
v2210_inwonend_eigenaarsgezin | v2220_eigenaarshuishouden
vp2210_hh_verhuurd_bw | vp2220_hurende_hh
vp2210_hh_eig_bw | vp2220_eigenaars_hh



</body>

</html>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hcd/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hcd/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">






</body>

</html>
