### ISSUE TITLE
Nieuwe indicatoren Landbouwgebruikspercelenkaart X ruimteboekhouding

### ISSUE THREAD

**Issue by valeriepirard** [provinciesincijfers/PinC-taakopvolging#460]
Op vraag van de diensten landbouw en ruimtelijke planning Limburg werden een reeks nieuwe indicatoren ontwikkeld (ook i.k.v. Beleidsplan Ruimte Limburg). Deze vind je momenteel intern in de admin/Jive onder project Ruimtegebruik/Landbouwgebruikspercelen X Ruimteboekhouding.
Het betreft dus statistieken uit de overlay van 2 GIS kaarten, zijnde de landbouwgebruikspercelenkaart 2023 en de ruimteboekhouding 2023.
Meer bepaald gaat het over de oppervlaktes landbouwgebruik binnen elk van de categorieën van de ruimteboekhouding.
In het BRL is men namelijk bezig met een pilootproject aangaande landbouwgronden binnen natuur bestemd gebied (en omgekeerd natuurgronden binnen agrarisch bestemd gebied). 
Vraag is om deze online te zetten onder het thema Landbouw.

**Comment by Emilien-Dupont** [comment]
Redactie:
Na te vragen of VB(LAN) dit controleert.
Filip vult aan tegen wanneer gecontroleerd kan worden.
