### ISSUE TITLE
Pendeldata

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#461]
De pendeldata (obv VAR) zijn geactualiseerd bij het steunpunt werk, maar door de nieuwe presentatiewijze kunnen we deze gegevens niet meer gebruiken om onze pendelcijfers te actualiseren op PinC.

Als mogelijk alternatief kunnen we de gegevens uit onze KSZ-aanvraag gebruiken.  Het gaat hier ook om de woon-werkpendel van de loontrekkenden door de link te leggen tussen het domicilieadres en het adres van de vestiging waar de loontrekkende vnl. werkt.
 Er zijn wel enkele verschillen:
- VAR = jaargemiddelde<> KSZ = momentopname op 31/12;
- VAR enkel totaalcijfers inkomende, uitgaande en geen pendel<> KSZ vertrekt van gemeentelijke pendelmatrix. We kunnen dus inkomende, uitgaande en geen pendel zelf berekenen, en dit niet enkel voor gemeenten, maar ook voor provincie en gewest.
- VAR gaf geen gemeentelijke pendelstromen <> voor KSZ kunnen we wel een gemeentelijke pendelmatrix opnemen
- VAR gaf initieel nog een indeling naar geslacht en 3 leeftijdsklassen, in hun nieuwe toepassing is deze indeling sowieso niet meer opgenomen<> deze hebben we niet bij KSZ.
- VAR 2008-2019 <> KSZ 2012-2023

De KSZ gegevens zijn opgeladen en te bekijken in de themaboom intern/project economie/in ontwikkeling (enkel intern)/woonwerkpendel (KSZ).

Ons voorstel:
- VB maakt nog nieuwe bron/infofiche
- LI controleert nieuwe reeks?
- KSZ 1221 vervangt VAR pendel 1202_pendel in de themaboom en de rapporten (mobiliteit, arbeidsmarkt, detailhandel, economie, omgevingsanalyse, ...?) 
- VAR gegevens worden gearchiveerd en intern geplaatst onder project economie

- Timing: begin juli 2024?

**Comment by Emilien-Dupont** [comment]
Redactie 18/06/24:
Akkoord met alles
