### ISSUE TITLE
Koppeling externe kaartlaag met gebiedsselectie in Mosaic/Stories

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#475]
ABF wijst ons op de mogelijkheid om kaartlagen aan gebiedsselectie in Mosaic/Stories.

Mail ABF:
Op https://brabantscan.nl/dashboard/brabantse-omgevingsscan--bros-/geluid zie je een voorbeeld van een dergelijke koppeling
De achterliggende url van de embedded kaartlaag is https://ggdbrabant.maps.arcgis.com/apps/instant/basic/index.html?appid=14e05f3174f244c8955f14283eaf5fba&extent=4.21879978543519,51.4396669827586,4.37279816072281,51.5706612668221
Zoals je ziet staan achter de parameter ‘extent’ 4 coördinaten. Dit zijn de hoekpunten van het gekozen gebied.
Het opvragen van de hoekpunten vindt plaats via get-statements, zoals je kunt in de onderstaande url.
[https://ggdbrabant.maps.arcgis.com/apps/instant/basic/index.html?appid=14e05f3174f244c8955f14283eaf5fba&extent={get](https://ggdbrabant.maps.arcgis.com/apps/instant/basic/index.html?appid=14e05f3174f244c8955f14283eaf5fba&extent=%7bget): data; varcode: abf_min_long},{get: data; varcode: abf_min_lat},{get: data; varcode: abf_max_long},{get: data; varcode: abf_max_lat}

Sarah heeft de bounding boxes van alle gemeenten (vertrokken van de gemeente-shapefile die op GitHub staat) aangemaakt met een Python-script (zie Excel-bestand hieronder). De min/max longitude en latitude weerspiegelen nu de uiterste grenzen van de gemeente, maar indien nodig/gewenst kan ik wat extra ruimte toevoegen zodat je een wat groter gebied hebt. Indien andere gebiedsniveaus aangemaakt moeten worden, kunnen die ook toegevoegd worden.

Figuur van de laadpunten in de Stories mobiliteit wordt opgeroepen door een PRESELECTIE van een MAP LAYER die in de Studio wordt aangemaakt (en wordt dus ook in de lijst van kaartlagen in de VIEWER weergegeven). 
Kan dit eenvoudiger ?

[bbox_gemeente.xlsx](https://github.com/user-attachments/files/17308413/bbox_gemeente.xlsx)

**Comment by Emilien-Dupont** [comment]
We voegden kaartlagen toe aan de Map Layers in de Studio om o.a. in rapporten te gebruiken omdat we hier de mogelijkheid hadden om een LayerID toe te voegen. 
Je kan kaarten ook toevoegen in Stories via een iframe link, maar je hebt hier nog niet de mogelijkheid om een LayerID aan toe te voegen. Dit staat bij ABF op de wensenlijst.
Vandaar dat de laadpuntenkaart via een viewer presentation opgeroepen werd. 

Het toevoegen van de coördinaten lijkt me heel erg nuttig om die kaarten op te roepen via iframe, maar dan moet je de URL van de kaartservice en de layerID wel in één URL krijgen. Soms lukt het door &layers=.. toe te voegen, maar niet altijd.
