### ISSUE TITLE
Kleine generieke taken in rapporten, part 2

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#49]
- [x] gebruik van `show(input_geo, " en ")` om opsommingen van type "A, B, C" te vervangen door "A, B en C"
- [x] verwijderen van overbodige #Write(name(level(item(input_geo,0))))# in teksten van rapporten: anders verschijnt er overal "gemeente" X of "provincie" Y. Volstaat om dit éénmalig in het begin van het rapport (inleiding of inhoud) te vermelden.
- [x] is de inhoudstafel in orde (zie sjabloon)
- [x] figuurtitels: automatische nummering in orde brengen
- [ ] figuurtitels: titels harmoniseren - @StefanJacques
- [x] figuurtitels en hoofdstuktitels: nakijken of er "de gekozen gebieden" komt te staan i.p.v. opsomming van de gebieden
- [x] belangrijke kaarten en alle figuren interactief maken - @StefanJacques
- [x] toevoegen "link terug naar begin van rapport" in stijl van sjabloon

**Comment by davidcardinaels** [comment]
Standaard structuur van begin rapport: ligt het zoals het nu in het sjabloon staat 100% vast? Volgens enkele collega's moet dit eerst nog naar redactiegroep?

**Comment by joostschouppe** [comment]
Ik geloof van niet, maar ik zal het nog eens voorleggen. Wel lijkt het me dat elk rapport een beetje anders is, en dat de "inhoudelijk verantwoordelijke" er mee naar moeten kijken. Ik zal het sowieso eerst nog eens aan de redactiegroep voorleggen. Mij lijkt plan van aanpak:
- rapport per rapport, pakweg begin met rapport_detailhandel (met mij dus)
- maak een kopie, bv rapport_detailhandel_intro. Werk daarin verder. Zet in rapport_detailhandel gans in het begin een opmerking "hier niet bewerken; doe aanpassingen in rapport_detailhandel_intro
- doe de eerste aanpassingen, en als je over inhoud twijfelt neem contact op met de verantwoordelijke
Of er nog wijzigingen zijn, laat ik ten laatste volgende week donderdag weten
Overigens is het misschien beter om dit naar een afzonderlijk Issue te verhuizen

**Comment by StefanJacques** [comment]
Afspraken ivm figuurtitels
Is de layout van de titels gebeurd volgens de standaardafspraken ? 
	niet beginnen met aantal of aandeel in titel
	zeker (een) jaartal(len) vermelden
	t.o.v. alle (personen) en t.o.v. totaal (objecten)
	bij 1 gebied het gebied vermelden (bij meerdere gebieden NIET, dan wijst de grafiek, tabel dat zelf uit)
	…
Voorbeelden voor aantallen:
•	Kaart 12 | Leeftijdsopbouw per 20-jarenklasse (2020)
Voorbeelden voor verhoudingscijfers:
•	Grafiek 10 | Eengezinswoningen naar bouwwijze in Alken, % t.o.v. totaal eengezinswoningen (2017) 
•	Tabel 07 | Werkloosheidsdruk, % NWWZ t.o.v. alle 18-64-jarigen (2016) 
Voorbeelden voor aantallen en verhoudingscijfers:
•	Tabel 10 | NWWZ jonger dan 25 jaar, aantal en % t.o.v. alle NWWZ (jaargemiddelde 2019)
Voorbeelden voor evoluties:
•	Grafiek 03 | Evolutie gebouwen in Alken (2009-2017) 
•	Tabel 12 | Evolutie eengezinswoningen in open bebouwing, % t.o.v. totaal eengezinswoningen (2000, 2010 en 2017) 
•	Grafiek 2 | Evolutie leerlingen secundair onderwijs volgens woonplaats (2010-2018, index 2010=100)

Mail verstuurd naar de verantwoordelijken rapporten met suggesties voor aanpassingen titels.

**Comment by VickyVB** [comment]
De titels voor de rapporten bevolking en huishoudens  en onderwijs zijn aangepast.
