### ISSUE TITLE
Gebiedsinfo rapport updaten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#50]
- [x] ouderenzorg ontbreekt
- [ ] nietszeggend tweede kaartje indien je gemeente opvraagt
- [x] aanpassen ivm wijken met onderwerp dat nis7-ggw onderscheidt - v9900_type_ggw7

**Comment by StefanJacques** [comment]
ouderenzorg al toegevoegd als je "gemeente" opvraagt

**Comment by joostschouppe** [comment]
@StefanJacques : ik vind dat kaartje van statsec bij gemeente wel leuk als teaser. Zou jij het helemaal laten vallen of vervangen door iets anders?

**Comment by StefanJacques** [comment]
laat me dit aanstaande vrijdag eens zien ? ik kan het niet reproduceren :-(
