### ISSUE TITLE
rapport gebieden kiezen op kaart en fusiegemeenten

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#52]
Bij het openen van een rapport via gebied samenstellen op kaart, loopt het mis bij fusiegemeenten: op de kaart staan nog de "oude" gemeenten, indien die mee geselecteerd worden, worden ze niet mee opgenomen in het rapport.

**Comment by joostschouppe** [comment]
Rode kaken. Ik fix het nu donderdag.

**Comment by joostschouppe** [comment]
Opgelost, wordt deze avond gepubliceerd. Van de gelegenheid gebruik gemaakt om in de code in Swing aan te duiden waar je meer info kunt vinden; en bij die meer-info instructies over hoe gebiedsniveaus hiervoor klaarzetten toegevoegd.
