### ISSUE TITLE
Rapport Klimaat export naar PDF is lelijk

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#53]
* op enkele plaatsen gekke plaats voor nieuwe bladzijde
* figuren verschijnen niet mooi naast elkaar
* ingeseind: niet alle grafieken verschijnen

**Comment by StefanJacques** [comment]
lijkt in de kopie die David heeft gemaakt en aangepast nu allemaal mooi in orde te komen/zijn

**Comment by joostschouppe** [comment]
dan sluiten we de boel af
