### ISSUE TITLE
Nakijken gebruik van "schuine streep" voor verhoudingen

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#55]
Afspraak:
Gemiddelde wordt enkel gebruikt als het écht een gemiddelde is (dit wordt dan ook met streep-over-x aangeduid in themaboom)
Percentage kan je op twee manieren gebruiken:
* als "echt" percentage, steeds met eenheid "p". (icoon in themaboom is dan %) 
* als ander type verhouding. Gebruik dan als Eenheid steeds "promille", “ratio” of “ratio_ietsanders” (je krijgt dan als symbool / in de themaboom)

Stefan bezorgt een lijst na te kijken onderwerpen per provincie

Joost kijkt na in afsprakenbestanden of dit correct gedocumenteerd is

**Comment by StefanJacques** [comment]
mail verstuurd op 13/12
nakijken voor 24/01/2020

**Comment by joostschouppe** [comment]
Aangevuld in basis swingbeheer
