### ISSUE TITLE
Iconen voor Dashboard

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#56]
Voorstel Koen:
![paginameticonen_witteachtergrond](https://user-images.githubusercontent.com/10122639/67679937-8beed900-f98a-11e9-8c46-24808d8326cd.png)

**Comment by Inejacobs** [comment]
Sprekende en heldere lay-out. Geen overbodige poespas en duidelijk voor bezoekers van het platform.
Ik stem voor :-)

Nog een leuke extra volgens mij: Voor de klanten van Data en Analyse Limburg ligt er ongetwijfeld nog een meerwaarde in het feit dat dit dashboard in lijn ligt met het (oude) lokale platform Limburg in Cijfers wat voor deze bezoekers een soort van 'vertrouwde en herkenbare omgeving' creëert. 

Utopie om de andere lokale landingsplatformen ook in een uniform jasje te gieten? (Limburg rood, Vla-Br groen, O-Vla geel etc ....)
