### ISSUE TITLE
Labelvariabele in Dashboard

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#57]
In de nieuwe versie kan dit: 
![afbeelding](https://user-images.githubusercontent.com/10122639/72821586-fef9aa00-3c70-11ea-927b-2192e8988040.png)

Dat lijkt me te betekenen dat we in het dashboard Landbouw met een native kaartje ipv een iframe kunnen werken. Er is een labelvariabele beschikbaar: v2710_typering

**Comment by KoenSnyers** [comment]
Ik heb een tegel toegevoegd op basis van de labelvariabele en dan het juiste kleurenpalet met 12 kleuren geselecteerd. Dat ziet er alvast veel mooier/beter uit dan de de iframe-kaart.
Het is te zien in de testversie van het dashboard, als je de tegel onder de iframekaart op zichtbaar zet. Ik liet de iframekaart nog staan en deed geen update van het dashboard. Als de iframekaart vervangen mag worden door de labelvariabelekaart, geef je maar een seintje.
Bij de labelvariabelekaart is er inderdaad ook een detailview, evenwel zonder keuzemogelijkheden om hier iets in te stellen als gebruiker, zo lijkt het.

**Comment by joostschouppe** [comment]
Ziet er inderdaad goed uit. Ik heb even gekeken naar de instellingen, maar ik denk niet dat het kan om de kaart in te stellen op "standaard Vlaanderen uitsplitsen"? Ik vrees dat dat wel belangrijk is voor Landbouw. En de kleurtjes zoals ingesteld in Swing Studio worden ook niet overgeërfd denk ik. Wellicht vindt Landbouw dat ook belangrijk. Stel jij voor beide de vraag aan Jona of dat een probleem voor hem is?

**Comment by KoenSnyers** [comment]
De kaart wordt inderdaad getoond voor de provincie waartoe de gemeente behoort.
En de kaart toont het standaardkleurenpalet van het dashboard, wat uiteraard het mooist is.

Ik heb Jona een mailtje gestuurd om te toetsen wat de mensen van landbouw ervan vinden

**Comment by KoenSnyers** [comment]
Op vraag van Jona heb ik getest met de landbouwtyperingskaart.
Ze kan helaas niet zo ingesteld worden dat ze ook verschijnt als mensen bovenaan een provincie als gebied kiezen.

Aan de mensen van landbouw om uit te maken of die kaart ook getoond hoort te worden als men bovenaan een provincie als gebied kiest.
Op dit ogenblik worden beide kaarten getoond in het dashboard.
Heb aan Jona gevraagd of ze de oude kaart wensen te behouden, dan wel of ze opteren voor de nieuwe kaart (die dan alleen maar op provinciaal niveau getoond wordt als er bovenaan een gemeente als gebied wordt ingesteld).

**Comment by KoenSnyers** [comment]
De mensen van landbouw hebben beslist dat ze de oude kaart verkiezen boven de nieuwe. Ik heb dus de nieuwe op onzichtbaar gezet in het dashboard.
