### ISSUE TITLE
tabellenrapport economie exporteert mottig naar pdf

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#59]

**Comment by StefanJacques** [comment]
@joostschouppe : dat mottig zijn valt best mee ! enkel één lege pagina in de pdf

[Cijfers economie opgelijst.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/4724131/Cijfers.economie.opgelijst.pdf)

**Comment by joostschouppe** [comment]
Opgelost door de tabel in drie te splitsen

**Comment by StefanJacques** [comment]
goed bezig !!! 
er staan nog amper issues open :-)
