### ISSUE TITLE
Aanpassing Over/Landingspagina

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#60]
## Landingspagina

- [x] schrappen OVER, Twitter, updates, schrappen nieuwsbrief
- [x] handleiding toevoegen als knopje
- [ ] ~~indien logged in: toon Logboek ipv landingspagina > geen eenvoudige oplossing mogelijk!~~

## Dashboard
- [x] NIEUWS
1. inschrijfformulier nieuwsbrief
2. verwijderen oude dingen
3. include van het archief van de nieuwsbrief indien mogelijk
4. toevoegen Twitter

- [ ] OVER
Toevoegen link Github + handleiding

**Comment by joostschouppe** [comment]
Voorstel aangepaste nieuwspagina: https://provincies.incijfers.be/dashadmin/preview/dashboard/nieuws/
(er komt nog een aangepaste introtekst)

**Comment by dgees** [comment]
Krijgen wij die ‘Aalst vergeleken met Oost-Vlaanderen’ nog weg van de nieuwspagina?

[cid:image001.png@01D61727.BCE0C9A0]

Van: Joost <notifications@github.com>
Verzonden: maandag 20 april 2020 11:22
Aan: provinciesincijfers/PinC-taakopvolging <PinC-taakopvolging@noreply.github.com>
CC: Deirdre Gees <deirdre.gees@data-en-analyse.be>; Assign <assign@noreply.github.com>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] Aanpassing Over/Landingspagina (#60)


Voorstel aangepaste nieuwspagina: https://provincies.incijfers.be/dashadmin/preview/dashboard/nieuws/
(er komt nog een aangepaste introtekst)

**Comment by dgees** [comment]
voorstel van intro voor het nieuwsbrieven archief:

Op regelmatige basis versturen we een nieuwsbrief naar al onze leden met nieuwtjes en weetjes over onze producten en alle recente bewegingen in de databank. Op deze pagina kan je alle nieuwsbrieven terugvinden. 
Krijg je het nieuws graag vers van de pers, schrijf dan in op onze nieuwsbrief via de onderstaande button.

**Comment by dgees** [comment]
to do: veranderen van Amerikaanse datumnotatie
