### ISSUE TITLE
Doorvoeren "favoriet gebied bij kaart enkel indien één gebied gekozen"

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#63]
Dit mag wellicht doorgevoerd worden in alle rapporten.

- [x] Controleren in test_klimaat_abf in enkele situaties, gecheckt dat het steeds werkt ! (Stefan)
- [x] Doorvoeren in alle inhoudelijke kaarten in rapport_klimaat waar er gebruik gemaakt wordt van favoriet gebied (dus de introkaarten hoeven niet aangepast)
- [x] rapport_klimaat na aanpassing eens door @StefanJacques laten nakijken
- [x] aanpassen in sjabloon_rapporten
- [x] aanpassen in alle rapporten in productie

Te gebruiken code in inleidend stuk (zie regel 93 van test_klimaat_abf):
```
/* indien er meer dan één gebied is gekozen, dan heeft het geen zin om een favoriet
gebied bij de legende van de kaart te tonen. Het is niet mogelijk en doorgaans
niet zinvol om dit te vervangen door een andere waarde (vb van een vergelijkingsgebied). 
De code gewest._99999 zorgt niet voor een zinvolle waarde, maar is er enkel om fouten af te vangen. */
if count > 1 then
favo_gebied = gewest._99999
else
favo_gebied = input_geo
end if
```

En binnen de presentaties zelf:

`FavoriteGeoItem: favo_gebied;`

**Comment by davidcardinaels** [comment]
Ik heb de code toegevoegd in rapport_klimaat. 
Het lijkt alleen mis te gaan wanneer je meerdere gemeenten hebt geselecteerd en daarna maak je een nieuwe selectie met 1 gemeente. Dan worden de kaarten niet goed getoond en moet je het rapport eerst afsluiten en opnieuw openen, dan worden de kaarten voor 1 gemeente weer goed getoond.

**Comment by joostschouppe** [comment]
Hmm, vreemd. Misschien helpt het als je vóór de if nog toevoegt: favo_gebied=input_geo

**Comment by davidcardinaels** [comment]
Nee, dat helpt niet. Het lijkt alsof Swing bepaalde dingen onthoudt van je vorige keuze ipv het rapport volledig opnieuw terug op te bouwen. Heeft eigenlijk niks te maken met deze specifieke code.

**Comment by joostschouppe** [comment]
Kan jij dit nog repliceren? Ik niet! Heb geprobeerd live en admin, zowel chrome als firefox. Dus: ik kies twee of meer gebieden; favoriet vervalt. Ik kies één gebied: favoriet wordt terug getoond...

**Comment by davidcardinaels** [comment]
Heb het hier met Stefan over gehad en heeft blijkbaar te maken met de aangevinkte vergelijkingsgebieden en is dus in orde.

**Comment by joostschouppe** [comment]
OK; ziet ernaar uit dat je ondertussen al naar alle rapporten hebt uitgerold?

**Comment by davidcardinaels** [comment]
Ja, is overal toegepast. Ik denk dat dit issue gesloten mag worden.

**Comment by joostschouppe** [comment]
Nice :)
Ik stuur het even rond naar de redactiegroep, zodat ze er even op letten
