### ISSUE TITLE
Beter beheer metadatafiches / logboek / beheersstructuur

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#65]
Ideeen worden hier uitgewerkt:
https://docs.google.com/document/d/1EN3ZxigfXtgKtxq1Lmfj2MWvaZZOVGJ3kQRCKfbfGFw/edit

Vereist aanvullen publicatiekalender en controleren verantwoordelijken in [bestand op alfresco](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/5ee48f87-c8a4-4aff-b2b3-dd15a59e9913)

closes #40

**Comment by joostschouppe** [comment]
Hier een metadatafiche uitgebreid met de velden waarmee ze gevoed kan worden:
[metadata met link naar uitgebreide bronnentabel.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/4510415/metadata.met.link.naar.uitgebreide.bronnentabel.docx)

**Comment by StefanJacques** [comment]
Op de _redactiegroep van 30/04/2020_ wordt afgesproken dat @joostschouppe contact opneemt met @Tine-VB om de impact hiervan op haar werk met de metadatafiches te bekijken.

**Comment by joostschouppe** [comment]
Detailopmerking: in sjabloon bij Contactgegevens iets toevoegen om het uitnodigender te maken om vragen te stellen

**Comment by joostschouppe** [comment]
Ondertussen is er ook een integratie met Dashboard mogelijk, maar dat kregen we nog niet aan de praat. Zie https://swing.eu/Release_notes/2020_12/Mosaic-Viewer-Studio/index_beta.html

**Comment by Tine-VB** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/tderijck/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/tderijck/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/tderijck/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=NL-BE style='tab-interval:35.4pt;word-wrap:break-word'>


<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>Ik heb
de ‘1 bron = 1 fiche’ problematiek eens nagekeken voor landbouw en onderstaande
wijzigingen doorgevoerd:<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p>&nbsp;</o:p></span></p>



Gegevens | Metadatafiche | Oude Bron | Nieuwe   Bron
-- | -- | -- | --
aantal bedrijven, investeringen en   omzet in het ABC | v2702_ABC_bedrijven_omzet_investeringen | Statbel | Statbel   - ABC
aantal en oppervlakte land- en   tuinbouwbedrijven | v2701_bedrijven_landbouwproductie | Statbel | Statbel   - Meitellingen
investeringen in de land- en tuinbouw | v2714_investeringen_landbouw | Departement Landbouw en Visserij | Departement   Landbouw en Visserij VLIF
oppervlakten van teelten | v2712_teelten | Departement Landbouw en Visserij | Dep.   Landbouw en Visserij Landbouwgebruikspercelen
oppervlakte biologische   landbouwbedrijven | v2711_oppervlakte_biologische_landbouwbedrijven | Departement Landbouw en Visserij | Departement   Landbouw en Visserij (Bio)



<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>Bij de
aanmaak van de nieuwe bronnen heb ik telkens bij ‘Info url’ het volgende
ingevuld:<o:p></o:p></span></p>

<p class=MsoNormal style='margin-left:35.4pt'><b><span style='font-size:10.5pt;
font-family:"Arial",sans-serif;color:#333333;background:white'>Files: </span></b><span
style='font-size:10.5pt;font-family:"Arial",sans-serif;color:#333333;
background:white'>verwijzing naar de bron, dus bij Statbel bron_Statbel.html en
bij Dep. L&amp;V bron_dep_lnv.html<o:p></o:p></span></p>

<p class=MsoNormal style='margin-left:35.4pt'><b><span style='font-size:10.5pt;
font-family:"Arial",sans-serif;color:#333333;background:white'>Link to more
information; </span></b><span style='font-size:10.5pt;font-family:"Arial",sans-serif;
color:#333333;background:white'>hier heb ik een verwijzing naar de
metadatafiche gezet<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>Ik zag
dat zo bij andere bronnen staan, maar weet niet of dat correct is zo?<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>Er is nu
geen enkele indicator binnen landbouw meer die louter ‘Statbel’ of ‘Departement
Landbouw en Visserij’ als bron heeft.<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>Blijft
over:<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>2703
(VPVB-bedrijven): bron Departement Omgeving <o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>2702
(toegevoegde waarde): bron NBB<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>Deze
worden ook gebruik voor andere data, dus daar moeten gezamenlijk afspraken over
gemaakt worden.<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'>Verder
heb ik de twee fiches van 2710 (gespecialiseerde bedrijven en de
landbouwtyperingskaart) samengevoegd tot 1 fiche, omdat ze gebruik maken van
dezelfde bron en basiscijfers (Landbouw en Visserij en Statbel). Dus ook hier:
1 bron = 1 fiche.<o:p></o:p></span></p>


</body>

</html>
