### ISSUE TITLE
Rapport Nationaliteit en herkomst

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#69]
Verantwoordelijke: Lore (WV)
Af te stemmen:
-inhoud
-subgemeentelijk

**Comment by joostschouppe** [comment]
Titel:
- moet zelfde zijn als in Dashboard en Themaboom
- "Nationaliteit en herkomst"

We schrappen Wachtregister uit themaboom en uit rapport

**Comment by StefanJacques** [comment]
De finale versie van het rapport nationaliteit en herkomst staat klaar. 
https://provincies.incijfers.be/admin/jive/report/?id=rapport_natioherkomst&openinputs=true

graag tegen volgende maandag 04/05 goedkeuring voor publicatie

**Comment by StefanJacques** [comment]
Besproken en goedgekeurd op _redactiegroep van 30/04/2020_. Enkel de grafiektitels (en sommige lange grafieklabels) zullen nog aangepast worden door Stefan.

**Comment by StefanJacques** [comment]
Dag @StefanieWVL ,
ik heb de grafiektitels nog eens nagekeken en aangepast waar nodig. Ik stuur Lore nog een lijstje van wat er nog dynamisch moet aangepast worden in de grafiektitels ... maar dan ben jij mee op de hoogte.

**Comment by joostschouppe** [comment]
rapport is gepubliceerd
