### ISSUE TITLE
IMA-data tot op statsecniveau

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#71]
De Redactiegroep wil deze data graag.
Stefanie probeert nog eens om een connector te leggen met IMA. We geven advies over hoe ze hun dataveiligheid nog kunnen verbeteren en vragen eventueel voorlopig om data aan te leveren - mogelijk mits aggregatie op meerdere niveaus.

**Comment by StefanJacques** [comment]
Op _redactiegroep van 07/04/2020_ wordt beslist dat Stefanie opnieuw een poging gaat ondernemen om een connector te leggen met IMA

**Comment by StefanieWVL** [comment]
De vraag aan het IMA werd gesteld ... fingers crossed

**Comment by StefanieWVL** [comment]
IMA gaat akkoord om dit nog eens te bespreken. Belinda is met verlof tot 2 juni. Na haar verlof leggen we datum vast voor overleg.

**Comment by joostschouppe** [comment]
Zie ook https://github.com/provinciesincijfers/connectorbeheer/issues/31 en https://github.com/provinciesincijfers/data-wishlist/issues/4

**Comment by VickyVB** [comment]
@Tine-VB nagaan of deze gegevens op statsec niveau kunnen gebruikt worden in het rapport armoede

**Comment by StefanieWVL** [comment]
Up-date mailtje van het IMA:

Beste, 
 
Zoals beloofd heb ik de connector aanvraag deze week herbekeken en besproken met het management.
We willen graag benadrukken dat we in principe positief staan tegenover dit initiatief. Toch kunnen we dit kalenderjaar nog niet tot een overeenkomst komen omdat we een aantal prioriteiten hebben die voorrang krijgen. Volgens onze inschatting zal het gedetailleerd uitwerken van de overeenkomst, en de implementatie van de connector, toch een significante tijd in beslag nemen. 
Dat betekent dat we de huidige ronde van opleveringen nog via de klassieke manier zullen regelen.
 
Hierbij hebben we nog een aantal elementen die een rol speelden in onze overwegingen.
1) Graag zouden we weten hoe de samenwerking tussen de Steunpunten Data en analyse verloopt met lokale steden en gemeenten. Hebben dezen allen een connector met PinC? 
Inzicht in deze organisatiestructuur kan ons helpen te evalueren welk gebruik er van de gegevens gemaakt kan worden via de connector, en zo wat de efficiëntiewinst is ten opzichte van de huidige werkwijze van leveringen.
2) We hebben verder nog een aantal bezorgdheden rond privacy, zoals secundaire identificatie van small cells.
3) De komende tijd gaan we inspanningen doen om extra gebiedsniveaus toe te voegen in de IMA Atlas, zoals deelgemeenten en eerstelijns zones. 
We hopen dat deze toevoeging reeds aan een deel van jullie vraag kan tegemoet komen, zodat downloads in elk geval op elk niveau mogelijk worden.

**Comment by HildeC** [comment]
aandachtspuntjes bij opvragen data:
we hebben ons  initieel gebaseerd op wat in de IMAatlas beschikbaar is. bij gerechtigden en VT zit er geen info over huishoudens. dit bijkomend vragen, betekent ook dat deze data moet beschikbaar zijn in hun atlas, vooraleer het in connector kan, en zal dus weer meer werk zijn.
een van de vragen van IMA was of dan alle data die antwerpen vraagt ook via de connector moet. ook hier weer zelfde vaststelling dat stad Antwerpen veel opvraagt wat niet in de ima-atlas (extren) zit

**Comment by StefanieWVL** [comment]
antwoord op vragen (zie bijlage) werd op 27/11/2020 naar IMA verstuurd mét de vraag om eind januari/begin februari een overleg in te plannen om dit te bespreken.
[Antwoord mail 20201016.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5606720/Antwoord.mail.20201016.docx)

**Comment by joostschouppe** [comment]
Laatste afstemming ivm connector ima is bezig
