### ISSUE TITLE
Toevoegen Groen uit gemeentemonitor

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#73]
https://gemeente-en-stadsmonitor.vlaanderen.be/groen-in-de-stad-gemeente
best ook direct buurtgroen?

**Comment by StefanJacques** [comment]
https://gemeente-en-stadsmonitor.vlaanderen.be/groen-in-de-stad-gemeente
Groen in de stad/gemeente
**Cijfers 2013 en 2016**

zullen toegevoegd worden:

**absolute cijfers:**
Inwoners Stadsbos
Oppervlakte Stadsbos (Are)
Inwoners Stadsdeelgroen
Oppervlakte Stadsdeelgroen (Are)
Inwoners Stadsgroen
Oppervlakte Stadsgroen (Are)

en daarvan telkens **ook een indicator**: ratio inwoners per opp. stadsbos en oppervlakte t.o.v. totale oppervlakte

**Comment by StefanJacques** [comment]
Upload is ondertussen gebeurd:
https://provincies.incijfers.be/admin/jive?var=vp2540_bos_inw,vp2540_bos_opp,vp2540_deelgroen_inw,vp2540_deelgroen_opp,vp2540_groen_inw,vp2540_groen_opp

In de *thematische indeling* onder *natuur* geplaatst:
![image](https://user-images.githubusercontent.com/31841732/78349295-af562980-75a3-11ea-8e3e-2ddf1118aeb8.png)

**Comment by joostschouppe** [comment]
Redactie: De werkgroep natuur zou misschien met een gelijkaardige indicator komen dus we moeten opletten daarmee. We moeten die van natuur misschien even laten praten met die van klimaat zodat we zeker zijn of ze hetzelfde willen weten of toch iets anders. 
Mieke en Stefan volgen op

**Comment by StefanJacques** [comment]
https://provincies.incijfers.be/jive?workspace_guid=9f2b670f-1fa5-4aca-8bfb-febfbb2e80cc

mag dit extern geplaatst worden ?
uit de indicatorenlijst van de werkgroep Natuur blijkt niet echt dat er ook cijfers over afstand tot buurtgroen opgenomen wordt ?

**Comment by joostschouppe** [comment]
Mag extern, na kleine uitbreiding van de metadatafiche
Voorlopig bij thema RUIMTE
