### ISSUE TITLE
kinderopvang kind&gezin

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#74]
update vanaf website; herorganisatie data nodig

**Comment by veravandestraat** [comment]
@joostschouppe zou je nog eens kunnen verduidelijken wat precies de vraag is? Ik weet nu niet zo goed wat ik moet navragen.

**Comment by joostschouppe** [comment]
Ik ook niet eerlijk gezegd. Ik vermoed dat Mieke daar ooit mee bezig was.

**Comment by miekevanopstal** [comment]
Ik denk dat dat te maken had met de kinderopvangcijfers. Vroeger was dat beperkt tot de voorschoolse kinderopvang. Ondertussen zijn ook de cijfers van de buitenschoolse kinderopvang opgenomen in PinC. 
Een andere mogelijkheid is dat we verwachtten om de cijfer te moeten herstructureren eens we opnieuw fijnmazige cijfers zouden ontvangen van K&G- niet dus! ;-)
Mag wat mij betreft geschrapt worden...

**Comment by ChrisMichelDS** [comment]
Hey Joost,

Ik zie dat je mij in cc gezet hebt voor de taakopvolging. Ik start pas
terug op 1 mei, dus vergeef mij als ik de komende weken mij nog wat afwezig
houd :-)

Vriendelijke groetjes, en tot binnenkort,

Chris

Op do 2 apr. 2020 om 10:01 schreef Joost <notifications@github.com>:
