### ISSUE TITLE
Standaardiseren begin van het rapport

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#78]
Plan van aanpak:

- [x] Goedkeuren sjabloon in de intro
- [x]  rapport per rapport, pakweg begin met rapport_detailhandel maak een kopie, bv rapport_detailhandel_intro. Werk daarin verder. Zet in rapport_detailhandel gans in het begin een opmerking "hier niet bewerken; doe aanpassingen in rapport_detailhandel_intro
    doe de eerste aanpassingen, en als je over inhoud twijfelt neem contact op met de verantwoordelijke
    Of er nog wijzigingen zijn, laat ik ten laatste volgende week donderdag weten
    Overigens is het misschien beter om dit naar een afzonderlijk Issue te verhuizen

| rapportcode   | verantwoordelijke  | begonnen | klaar | 
|---|---|---|---|
|rapport_detailhandel | Joost | x | x |
|rapport_onderwijs | Vicky | x | x |
|rapport_wonen | West-Vlaanderen | x | x |
|rapport_klimaat  | Stefan | x | x |
|rapport_veiligheid | Ine | x | x |
|rapport_armoede | Tine | x | x |
|rapport_ouderenzorg | Karolien | x | x |

**Comment by joostschouppe** [comment]
Opmerking leeswijzer:
- toevoegen uitleg over gebruik "opvragen achterliggende cijfers"

**Comment by davidcardinaels** [comment]
Alle intro's zijn aangepast en alle verantwoordelijken hebben een mail gekregen ter goedkeuring of om een inleiding toe te voegen.

**Comment by joostschouppe** [comment]
@davidcardinaels : nog een late opmerking binnengekregen, helaas. In de intro staan nog twee verwijzingen in u-vorm, terwijl we in je-vorm spreken. Kan je overal deze zinnetjes corrigeren:

Momenteel krijgt u het rapport te zien voor
Momenteel zie je het rapport voor

de door u gekozen vergelijkingsgebieden
de door jou gekozen vergelijkingsgebieden 

(in het sjabloon is dit al gebeurd)

**Comment by davidcardinaels** [comment]
De zinnetjes zijn aangepast.
