### ISSUE TITLE
Evaluatie nieuwe versie

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#79]
De nieuwe versie is er. De [release notes zijn online nog bijgewerkt](https://swing.eu/Release_notes/2019_12/viewer-studio/index.html). Joost heeft nogal wat issues gehad in de eerste dagen. De rest ook?

**Comment by veravandestraat** [comment]
Tanja en ik hebben allebei het probleem dat we bij het openen van de link naar het rapport Diversiteit de volgende waarschuwing krijgen: [* Warning 'geolevel' is a reserved word and cannot be used as a variable name. at line 78, column 0 *]. Ook bij het openen van andere links ben ik hetzelfde probleem al tegengekomen.

**Comment by joostschouppe** [comment]
Deze link nog eens rondsturen: https://support.swing.eu/content/kennisondersteuning
Nieuwe functionaliteit? Exporteer wijzigingen in data via Consistency Checks
