### ISSUE TITLE
nalezen op noodzaak voetnoten e.d.

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#8]
Is er inhoudelijke nood aan voetnoten/begrippen/bronverwijzingen? Indien wel, doe tekstueel voorstel.
Moet in alle rapporten overlopen worden

Feedback hieronder kan aangevuld worden in de bestaande Rapporten

**Comment by joostschouppe** [comment]
Eindnoot in OUderenzorg???

**Comment by veravandestraat** [comment]
Voorlopig de rapporten voor Wonen, Detailhandel en Kansarmoede bekeken.

1. Wonen: misschien zinvol om een verwijzing naar beschrijving LIPRO-indeling (https://www.vlaanderen.be/publicaties/lipro-een-classificatie-van-huishoudens) te geven?

2. Detailhandel: er zijn twee dingen waarvan ik zou overwegen om het naar een voetnoot te verplaatsen, omdat ze wel heel gedetailleerde informatie geven die gebruikers misschien juist in verwarring brengen.
- onder 2.2 Handelsaanbod per 1000 inwoners: Indien men de maat van voorzieningsniveau van het aanbod wil beoordelen, dienen meer elementen mee in rekening gebracht te worden, zoals, onder meer, het totale aanbod en de bevolkingskenmerken in de ruime omgeving. Deze benadering valt buiten de doelstelling van dit document. 
- onder 3. Koopstromen: Het koopstromenmodel houdt geen rekening met toe- en afvloeiingen over de grenzen. Grensoverschrijdende koopstromen naar Noord-Frankrijk, Nederland worden niet op kaart weergegeven. Wat betreft de relatie met Wallonië en Brussel wordt wel rekening gehouden met het shoppinggedrag van de inwoners van deze gewesten. Er wordt ook rekening gehouden met inwoners van Vlaanderen die in Brussel of Wallonië gaan shoppen, maar dit wordt niet op kaart of in de top vijf van bestemmingen weergegeven. 

3. Kansarmoede: geen inhoudelijke nood aan voetnoten/begrippen/bronverwijzingen denk ik.

**Comment by veravandestraat** [comment]
Ik heb het rapport Klimaat ook nagelezen. Geen opmerkingen, behalve een paar tekstuele aanpassingen en de vraag waarom voetnoot 1 gevolgd wordt door voetnoot 23?

**Comment by Lievendr** [comment]
rapporten Demografie, Onderwijs, Veiligheid en Ouderenzorg nagelezen. weinig nood aan voetnoten in algemeen. wel aan conformiteit in verwijzing figuren in tekst. 4 rapporten...4 verschillende manieren...elke auteur heeft een pdf met suggesties ontvangen.

**Comment by StefanJacques** [comment]
> Ik heb het rapport Klimaat ook nagelezen. Geen opmerkingen, behalve een paar tekstuele aanpassingen en de vraag waarom voetnoot 1 gevolgd wordt door voetnoot 23?

Ondertussen aangepast door @davidcardinaels
