### ISSUE TITLE
"Achter de schermen" bijwerken

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#80]
Toe te voegen aan het rapportje; zonder tekst maar in de tabel, met een PinC voorbeeld:

Met URL-parameter ‘dimmember_codes’ is het mogelijk gegevens van specifieke dimensie-items op te vragen. Bij de URL-parameter geef je de code van het dimensieniveau en het bijbehorend item op gescheiden door een underscore. Verschillende items geef je gescheiden met een komma op. Onderstaande URL illustreert de werking:

[Link naar versie van Swing Viewer]?var=kb_bev_lft05&dimmember_codes=dnc_gsl_v,dnc_gsl_m

Van het onderwerp ‘kb_bev_lft05’ (bevolking) zijn de dimensie-items ‘v’ en ‘m’ (vrouwen en mannen) van het dimensieniveau ‘dnc_gsl’ (geslacht) opgevraagd

**Comment by valeriepirard** [comment]
Ik heb een voorbeeld toegevoegd in de tabel.
