### ISSUE TITLE
afspraken bronnen en missings

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#82]
-wat met dubbele bron? bv vdab gekoppeld aan rijksregister en achtergrondkenmerken komen uit rr
- wanneer 0? wanneer -99999? wanneer hoofdcategorie 0 is? bv 0 werkzoekenden, - werkzoekende mannen of 0 werkzoekende mannen?

**Comment by joostschouppe** [comment]
Afspraak: indien een totaal als 0 weergegeven wordt, dan worden de subtotalen ook op 0 gezet

**Comment by joostschouppe** [comment]
Aangepast in [00 Basis Swingbeheer.docx](https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/3c11a4a0-4e2d-49d8-8763-20d7c4f4201f). Tekst:  

> Conventie voor Bron naam is “Naam van de bron | provincies.incijfers.be”. 
> * Bij percentages geven we enkel de Bron van de teller mee. 
> * Als onderwerpen de som vormen van andere onderwerpen uit verschillende Bronnen, dan maken we een nieuwe bron van type “Naam bron 1 & Naam bron 2 | provincies.incijfers.be”
> * Bij onderwerpen die gebaseerd zijn op een dataverwerking die meerdere bronnen combineert (vb VDAB-verrijkt-met-rijksregister) maken we een bron van type “Naam bron 1 & Naam bron 2 | provincies.incijfers.be”
>
