### ISSUE TITLE
Rapport demografie

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#84]

**Comment by VickyVB** [comment]
Een testversie vind je in de themaboom onder intern/rapporten/in ontwikkeling/rapport demografie
[Rapport Demografie.pdf](https://github.com/provinciesincijfers/PinC-taakopvolging/files/4527526/Rapport.Demografie.pdf)

**Comment by VickyVB** [comment]
Suggestie foto rapport demografie (shutterstock)
![foto_dossier](https://user-images.githubusercontent.com/50832398/80218746-dc957500-8641-11ea-8da2-e95386c27891.jpg)

**Comment by joostschouppe** [comment]
Gewenste aanpassing: op niveau statsec, eens de bevolkingsmutaties afgerond zijn

**Comment by VickyVB** [comment]
Het rapport Bevolking en huishoudens is nu ook beschikbaar op statsec niveau
