### ISSUE TITLE
Metadata, het sjabloon

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#88]
* Accuraatheid / betrouwbaarheid / volledigheid zijn 3 totaal verschillende concepten waarop je gedwongen wordt te antwoorden met een simpel vinkje ja/nee. In de praktijk is dit niet zo simpel. Ieder gaat hier anders mee om. Gevolg RSZ data zijn blijkbaar niet accuraat/betrouwbaar/volledig, data over de verkeersongevallen wel. Misschien kan dit item vervangen worden door "Beperkingen aan de data" ja / nee met dan indien nee een uitleg.
* Startjaar vervangen door startjaar in provincies.incijfers.be.
* Aanpassing naar nieuw sjabloon moet de tekst te plakken in het nieuwe sjabloon. Zo wordt de volledige opmaak van het bestand meegenomen. Ik wist dat niet, misschien anderen ook niet.

**Comment by joostschouppe** [comment]
Zie ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/65

**Comment by joostschouppe** [comment]
Redactiegroep:
Geen enkel vinkje bij accuraatheid/betrouwbaarheid/volledigeheid
Aanpassing startjaar OK
