### ISSUE TITLE
Update gebiedsniveaus

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#90]
Aanleiding: nieuwe statsec

## Wijzigingen in Swing:

- [x] pas in Swing naam van statsec aan naar statsec2019; maak een nieuwe statsec aan (en dus serieuze aanpassing aggregatietabellen. De oude aggregatietabellen worden wellicht best in hun geheel gewist (zéker te verwijderen: statsec2019 naar gemeente en statsec2019 naar ggw7)
- [x] volledige actualisatie van ggw7 (aggregatie, definitie, geometrie)
- [x] volledige actualisatie van deelgemeente (aggregatie, definitie, geometrie)
- [x] inhoudelijke uitbreiding van gemeentenbe en gemeentenbe2018 met buurlanden (aggregatie, definitie, geometrie) (closes #72)
- [x] update geometrie van alle andere gebiedsniveaus (dus enkel statsec2019 blijft behouden, plus enkele niet meer gebruikte gebiedsniveaus
- [x] actualisatie van gebiedsdefinities alle gebiedsindelingen (in de meeste gevallen gaat er niets veranderen)
- [x] update winkelgebieden / kernwinkelgebieden naar versie 2020 (nog laatste correctie nodig, 21/4)

[Pakket voor Richard](https://share.vlaamsbrabant.be/share/s/S2qmQTWNR3mVGOggZ3s6RA)

## In de marge:
- [x] gemeente_cluster(2018) niet vernieuwd en verborgen
- [x] fo_gem NIET uitgebreid met Denderstreek, want dat schijnt toch niet écht te bestaan
- [x] naamgeving deelgemeenten: Erpe wordt Erpe (Erpe-Mere) en Aalst wordt Aalst (Dg.)
- [x] onderwerp gemaakt om te laten zien wat voor wijkindeling er gebruikt word https://provincies.incijfers.be/admin/jive?var=v9900_type_ggw7
- [x] gebiedscode/naam toegevoegd voor wijken

## Eindfase
Eens de aanpassing binnen Swing is uitgevoerd (door Richard)

### Connector
 - Brugge & Oostende kunnen eventueel hun kustsector toevoegen. Wellicht beter, om oppervlaktes door te kunnen geven
 - voor Stad Antwerpen: de data kan ofwel van onze oude statsec naar hun oude statsec gaan, OF van onze nieuwe naar hun nieuwe. Voor nieuw-naar-nieuw moet enkel de gebiedsniveau code aangepast worden om 1-op-1 identiek te zijn. Om ook voor ggw7 af te stemmen moet zowel de gebiedsniveaucode als de gebiedscodes aangepast worden.

### Databeheer
- [x] vanaf dat moment: data op OUD statsec vanaf dan op statsec2019 moet ingelezen worden! (gecommuniceerd)
- [x] gebruik je de OUDE statsec, dan gebruik je voor gebied onbekend van fusiegemeenten de OUDE niscode van de gemeente + ZZZZ. Gebruik je de NIEUWE statsec, dan gebruik je voor gebied onbekende de NIEUWE niscode van de gemeente + ZZZZ (gecommuniceerd)
- [x] het onderwerp met de gebiedscode en naam opnieuw inlezen voor alle gebiedsniveaus
- [x] documenteren logica nummering gebieden in Geolevels tabel: 

### Aanpassingen in Swing
- [x] Nakijken rapporten > probleem in Detailhandel: kaart inkomen; opnieuw inlezen data k(wg); opnieuw inlezen data koopstromen (en dit nakijken voor alle stroomdata???)
- [x] gebiedsinfo rapportje bijwerken (ggw7-conditioneel!)
- [x] Kaartlagen gebiedsniveaus nakijken

### Laatste grote issues
- [x] probleem stroomdata gemeentenbe
- [x] foute aggregatie detailhandelsdata (k)wg? > met Richard (nakijken noodzaak winkelgebied_dummy en kernwinkelgebied_dummy ? Updaten of wegwerken?)
- [x]  data v2207_nbw_peil_mediaan op ggw7 manueel wissen

### Laatste kleine issues
- [ ]  nakijken logica: welke aggregatietabellen nodig? > met Richard
- [x]  artefacten in geometrie verspreid over heel Vlaanderen (fixen in GIS, geometrie opnieuw inladen)
- [x]  Updaten "kiezen op kaart" > eerst geometrie fixen
- [ ]  metadata gebiedsniveaus -  @valeriepirard 
 - extra info bij statsec (omdat er nu twee versies online staan)
 - toevoegen: winkelgebied, kernwinkelgebied
- [x]  publiceren alle gegevens op Github
- [ ]  bijwerken oppervlaktes - wachten op feedback statbel
- [ ] opnieuw draaien van het beperkt aantal sets dat op deelgemeente en ggw7 was ingelezen (test: niet aggregeerbaar en beschikbaar op statsec) - 

## Ter info: Opgelet bij gebruik nieuwe kerntabellen
- Updaten documentatie AlFresco 
- bij aggregatie vanaf statsec2019 is er nu een lege waarde omdat 11002K1MN gesplitst wordt in 11002K1WN en 11002P6PK. Maar we negeren die tweede optie en dus is er een lege cel die verwijderd moet worden als je werkt vanaf statsec2019
- dubbels op statsec/gemeente2018 omdat gebied onbekend samengevoegd wordt

**Comment by joostschouppe** [comment]
Opmerkingen Stefan en Richard nakijken

**Comment by StefanJacques** [comment]
Op de redactiegroep van 30/04/2020 wordt beslist: gebiedscodes van ‘gebieden onbekend’ + verschil tussen codes van een oude gemeente en een nieuwe gemeente wordt door @joostschouppe aangevuld.

**Comment by joostschouppe** [comment]
Fout: deelgemeente onbekend heeft een geometrie aan de kust!
