### ISSUE TITLE
risicokenmerk schooltoelage voor alle leerlingen

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/PinC-taakopvolging#93]
Als proxy voor lage inkomens wordt gebruik gemaakt van de onderwijsindicator 'krijgen van een schooltoelage'. Nu wordt deze variabele apart voor basisonderwijs en secundair onderwijs berekend en door alle drempels kunnen we daar geen eigen gebruiksonderwerp van maken. Kan dit in het SPSS-programma toegevoegd worden?

**Comment by joostschouppe** [comment]
Da's redelijk lastig, aangezien de verwerking van basis en secundair volledig los van elkaar verlopen.
Maaaaaaaar, volgens mij is de som van het drempelonderwerp voor lager en de som van het drempelonderwerp voor secundair gewoon geschikt als drempelonderwerp voor zo'n gecombineerd onderwerp.
(ik veronderstel hier dat je met gebruikersonderwerp hier eigenlijk formuleonderwerp bedoelt - ik ga alleszins zéker niet voor een gebruikersonderwerp mijn SPSS opstarten :D)

**Comment by joostschouppe** [comment]
Ik ga ervan uit dat het met mijn antwoord opgelost was
