### ISSUE TITLE
Harmonisatie Dashboard

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#95]
Van Karolien: 

> Ik verwerkte jullie input op de bevraging rond het dashboard in 1 document, dat in zijn geheel besproken kan worden op de redactiegroep van 19 maart. Hopelijk kunnen we dan tot afspraken komen.
> Het document vinden jullie op alfresco, zodat je er al op voorhand door kan gaan: https://share.vlaamsbrabant.be/share/page/site/socialeplanning/document-details?nodeRef=workspace://SpacesStore/fc948cfe-7c03-4b95-8573-acac1bc26cd2

**Comment by karolienbloemen** [comment]
Afspraken besproken en afgeklopt op redactiegroep 19 maart.
Te implementeren in bestaande dashboards (eindredacteur)

**Comment by KoenSnyers** [comment]
Even stand van zaken:
- opbouw startpagina dashboard is aangepast volgens draaiboek
- pagina rapporten en steekkaarten is up to date gemaakt (vraag: moeten rapporten en steekkaarten als favoriet aangeduid kunnen worden? mijn voorstel: nee)
- eindredactie van pagina 'Over' nog te doen (op basis van voorzet Deirdre): doe ik deze week nog
- thema's bevolking en huishoudens zijn aangepast volgens de richtlijnen van het draaiboek
- thema zorgaanbod is aangepast wat luik zorgaanbod betreft / kinderopvang werk ik deze week af
- ik overloop de komende weken systematisch alle thema's en pas ze aan
- bij het aanpassen breng ik eerst de hoofdviews van alle thema's in orde; als dat voor alle thema's klaar is, kijk ik naar de detailviews

**Comment by KoenSnyers** [comment]
Thema's die klaar zijn nu: bevolking, huishoudens en zorgaanbod.
Aandachtspunt om in draaiboek op te nemen: 
de grootte van de titel van een tegel (header font size onder 'Interface') staat standaard op 0; laat dit zo staan als de titel op één regel past; indien niet, geef dan als font size 15, 16 of 17 mee (en doe dat dan om esthetische redenen telkens voor twee tegels naast elkaar).

**Comment by KoenSnyers** [comment]
Eindredactie van pagina 'Over' op basis van voorzet Deirdre is gebeurd.

**Comment by KoenSnyers** [comment]
Kleine aanpassingen gedaan in dashboard.
Thema's die klaar zijn nu: bevolking, huishoudens, zorgaanbod en werken.

**Comment by KoenSnyers** [comment]
UPDATE.
Thema's waarvan de hoofdview nu klaar is: bevolking, huishoudens, zorgaanbod, werken, economie (fouten in enkele onderwerpen gemeld via mail), detailhandel en armoede.

**Comment by KoenSnyers** [comment]
UPDATE.
Thema's waarvan de hoofdview nu klaar is: bevolking, huishoudens, zorgaanbod, werken (@VickyVB: kan je ervoor zorgen dat de cijfers achter de twee tegels over bodembezetting kloppen?), detailhandel, armoede en landbouw.
Ook de startpagina en de pagina's nieuws en rapporten staan op punt.

**Comment by KoenSnyers** [comment]
> 
> 
> UPDATE.
> Thema's waarvan de hoofdview nu klaar is: bevolking, huishoudens, zorgaanbod, werken (@VickyVB: kan je ervoor zorgen dat de cijfers achter de twee tegels over bodembezetting kloppen?), detailhandel, armoede, landbouw en klimaat.
> Ook de startpagina en de pagina's nieuws en rapporten staan op punt.

**Comment by KoenSnyers** [comment]
UPDATE.
Thema's waarvan de hoofdview nu klaar is: bevolking, huishoudens, zorgaanbod, werken, economie, detailhandel, armoede, landbouw, klimaat, veiligheid, wonen, nationaliteit & herkomst, hoofdpagina onderwijs en subpagina basisonderwijs.
Ook de startpagina en de pagina's nieuws, over en rapporten staan op punt.

**Comment by KoenSnyers** [comment]
UPDATE.
Van alle thema's is de hoofdview klaar: bevolking, huishoudens, zorgaanbod, werken, economie, detailhandel, armoede, landbouw, klimaat, veiligheid, wonen, nationaliteit & herkomst, hoofdpagina onderwijs, subpagina basisonderwijs en subpagina secundair onderwijs.
Ook de startpagina en de pagina's nieuws, over en rapporten staan op punt.

Aandachtspunt voor themaverantwoordelijken van het dashboard: in de themaboom van het dashboard plaats je alleen de onderwerpen die je denkt/wenst te gebruiken, niet bijna alle beschikbare onderwerpen van het thema in de databank (zoals bij onderwijs bv. het geval was).

In de zomermaanden pak ik de detailview van alle cijfertegels aan.

**Comment by VickyVB** [comment]
Check van de harmonisering van het dashboard
[Draaiboek dashboard.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/4812210/Draaiboek.dashboard.docx)

**Comment by KoenSnyers** [comment]
Na de opmerkingen rond de harmonisatie en het online plaatsen van de nieuwe release van Swing zijn de laatste aanpassingen in het dashboard gebeurd.

Met release 5.7 van Swing is het helaas niet meer mogelijk om te selecteren welke presentatievormen in de detailviews getoond moeten worden. De detailview toont standaard alles wat er ook in de databank getoond wordt.
Voordeel is dat er meer en nieuwe presentatievormen mogelijk zijn, nadeel is dat we niet relevante presentatievormen niet meer kunnen uitschakelen, wat voor het dashboard in feite wel wenselijk is.
Joost seint het als vraag in om het zelf aan- en uitvinken van presentatievormen in de detailview weer mogelijk te maken.

Ziehier de geüpdatete versie van het draaiboek:

[Draaiboek.dashboardPinC.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/5149263/Draaiboek.dashboardPinC.docx)

**Comment by KoenSnyers** [comment]
@VickyVB (ter info aan @StefanJacques en @joostschouppe)

Ik ben bezig met het dashboard ruimte. Toen ik dat dashboard via url toonbaar wilde maken, merkte ik dat het dashboard naar een map ruimte onder het thema Economie wilde gaan.
In de themaboom van de map economie van het dashboard heb ik de map ruimte moeten verwijderen ...
Ik heb daar ook alle submappen verwijderd en alle onderwerpen van die submappen verplaatst naar de hoofdmap economie, plus ik heb ook de map rapporten (met de inhoud ervan) verwijderd.
Ter info even de algemene policy rond de themaboom van het dashboard voor Vicky:
- zet geen onderwerpen in submappen onder een themamap, maar wel alle onderwerpen gewoon onder elkaar in de themamap
- neem geen rapporten als onderwerp in de themaboom van het dashboard op, want rapporten worden via een tegel met link in het dashboard zelf aangemaakt.
Alvast bedankt om hiermee rekening te houden.

**Comment by VickyVB** [comment]
@KoenSnyers  Ik heb het dashboard Economie niet aangemaakt en ook geen map ruimte of een rapport erin gezet. Maar ik onthoud dus dat ik dat zeker niet mag doen :-). 

Ter info: Momenteel loopt er binnen de werkgroep economie wel een bevraging van hoe we het dashboard mogelijk gaan aanpassen in het licht van de nieuwe variabelen die het afgelopen jaar toegevoegd werden. Ik vermoed dat we daar begin 2021 met zullen landen. Ik hou je op de hoogte.

**Comment by KoenSnyers** [comment]
> 
> 
> @KoenSnyers Ik heb het dashboard Economie niet aangemaakt en ook geen map ruimte of een rapport erin gezet. Maar ik onthoud dus dat ik dat zeker niet mag doen :-).
> 
> Ter info: Momenteel loopt er binnen de werkgroep economie wel een bevraging van hoe we het dashboard mogelijk gaan aanpassen in het licht van de nieuwe variabelen die het afgelopen jaar toegevoegd werden. Ik vermoed dat we daar begin 2021 met zullen landen. Ik hou je op de hoogte.

Ik tagde jou en Stefan in het bericht als themaverantwoordelijke en checker, zodat jullie op de hoogte zijn dat ik dingen verwijderde en waarom.
Als er wijzigingen aan het dashboard economie moeten gebeuren, overleggen we daarover samen!
Dankjewel, @VickyVB.

**Comment by KoenSnyers** [comment]
Naar aanleiding van de wijkdashboards heb ik in het draaiboek op pagina 4 (in het rood) wat summiere richtlijnen voor wijkdashboards toegevoegd.
@Emilien-Dupont, kan jij dit aangepast document opnieuw uploaden naar de Jive Documentation van het dashboard hier op Github? Dat lukt me immers niet.
@joostschouppe, moeten deze aanpasingen ook besproken worden naar de redactiegroep? Zo ja, agendeer jij dat dan?
[Draaiboek dashboard.docx](https://github.com/provinciesincijfers/PinC-taakopvolging/files/6815433/Draaiboek.dashboard.docx)

**Comment by Emilien-Dupont** [comment]
De nieuwe versie staat online

**Comment by joostschouppe** [comment]
Lijkt ons wel OK om gewoon aan te passen, we zien niet direct iets cruciaal
