### ISSUE TITLE
Scope van Kerncijfers (omgevingsanalyse_steekkaart)

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#96]
Moet elk rapport en elke tegel een plaatsje krijgen in de omgevingsanalyse Kerncijfers?

**Comment by joostschouppe** [comment]
Redactiegroep:
1) We gebruiken deze pagina als "alternatieve landingspagina" (of promofolder). Elk nieuw thema mag hier dus een plaats krijgen. De naam "kerncijfers" is wellicht niet meer van toepassing. Deirdre denkt na over een andere naam
2) Voorstel nieuwe naam: Profiel van X; Waar staat mijn gemeente?
3) Intro herschrijven of herstructuren? @dgees doet een voorstel

**Comment by dgees** [comment]
Voorstel van aanpassing eerste paragraaf. 
Issue blijft dat dit 'rapport' niet echt past in het rijtje van rapporten. Misschien te overwegen om dit in het dashboard mee op te nemen als aparte tegel? 

**Profielschetsen provincies en gemeenten

Wie op zoek is naar een kort en duidelijk overzicht van de belangrijkste vergelijkende cijfers in een gemeente of provincie kan gebruik maken van onze profielschetsen voor provincies en gemeenten. 
Aan de hand van thematische profielstaaf grafieken tonen we een selectie van indicatoren die je toelaten om in een oogopslag een zicht te krijgen op waar jouw gemeente of provincie zich situeert ten opzicht van Vlaanderen of een andere gemeente of provincie. 
Elke grafiek kan op dezelfde manier gelezen worden: het balkje geeft de waarde van het door jou gekozen referentiegebied weer, nl. Vlaams Gewest, de bol toont de waarde van Lubbeek. Aan de hand van de kleur van de bol kan je aflezen of het gebied (veel) lager, gelijk of (veel) hoger dan het vergelijkingsgebied Vlaams Gewest scoort. Je kan de keuze van het gebied en vergelijkingsgebied aanpassen via de "Wijzig"-knop.
Meer achtergrondinformatie bij de indicatoren is terug te vinden via provincies.incijfers.be. Doorheen dit document staan links die doorverwijzen naar meer gedetailleerde info per thema.
Bij het openen van het rapport worden de meest recente gegevens uit de databank gehaald. Indien een waarde te klein is (onder de drempelwaarde), kan het voorkomen dat een bol niet wordt getoond.**

**Comment by StefanJacques** [comment]
Er toch over nadenken om kerncijfers te blijven gebruiken ?

waarom?
het blijven kerncijfers (zie ook Statbel https://statbel.fgov.be/sites/default/files/images/in de kijker/kerncijfers_2019_r.pdf en CBS Nederland https://opendata.cbs.nl/statline/#/CBS/nl/dataset/84583NED/table?ts=1590568345400 als voorbeeld)

terwijl we anders in het vaarwater van Vlaanderen komen: 
https://lokaalbestuur.vlaanderen.be/statistieken/gemeentelijke-profielschets

te bespreken ?

**Comment by joostschouppe** [comment]
Zomerproject Joost: proberen of dit aan de praat te krijgen is op lager-dan-gemeentelijk niveau

**Comment by joostschouppe** [comment]
Huurder/eigenaar kadaster mag misschien toegevoegd worden bij wonen?

**Comment by StefanJacques** [comment]
Ik heb Huurder/eigenaar kadaster toegevoegd ... meer nog, ik heb de samenvattende grafiek uit Wonen integraal naar kerncijfers gekopieerd:
https://github.com/provinciesincijfers/PinC-taakopvolging/issues/96#issuecomment-645391715
