### ISSUE TITLE
Voorstel: gebruik enkel "percentage" indien teller en noemer directe relatie hebben

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#97]
Gegeven issues als deze:
https://provincies.incijfers.be//jive?workspace_guid=d77bb72a-5c47-4f1e-8435-0f930cb9bf51 

Voorstel:
We gebruiken enkel een % als 
- de teller en noemer van dezelfde bron zijn
EN
- de teller is een deelgroep van de noemer

Indien de teller gebruik in dit soort situatie NIET % (dat zou ik beperken tot waar je berekening tot één bron behoort en je echt weet “dit totaal valt zo onder te verdelen”). Een % impliceert immers dat je een totaal in stukjes kapt. Maar gebruik in de plaats een “ratio van iets per 100 van iets anders zetten”. Daarmee geef je aan dat je gewoon een standaardisering van dit cijfer probeert te doen. En een standaardisering kan nu eenmaal af en toe misgaan.

Alternatieve (of bijkomende) oplossingen:
* uploadfiles manueel bijwerken
* we kunnen een voetnoot aan dit soort cijfers geven (als we het merken)
* we kunnen toch met treshold werken (maar dat is geen garantie!)
* gewoon negeren

**Comment by valeriepirard** [comment]
Goed voorstel. Ik heb enkele dagen geleden dezelfde bedenking gemaakt met een aantal cijfers over kinderopvang. Nl.:
aantal plaatsen B&P per 100 kinderen van 0 tot 2 jaar
aantal plaatsen BO per 100 kinderen van 3 tot 11 jaar.


-

**Comment by miekevanopstal** [comment]
@valeriepirard 
aantal plaatsen B&P per 100 kinderen van 0 tot 2 jaar
aantal plaatsen BO per 100 kinderen van 3 tot 11 jaar?
Wat is de bedenking hierover?
Zowel teller als noemerinformatie zijn afkomstig van K&G of speelt hier iets anders?

**Comment by valeriepirard** [comment]
@miekevanopstal 
Bij deze indicatoren is de teller geen deelgroep van de noemer, dacht ik. Dus, je deelt de groep kinderen niet op, zoals bij een echt % het geval is.
Ik zou hier geneigd zijn om een ratio te gebruiken: x aantal plaatsen per 100 kinderen

**Comment by miekevanopstal** [comment]
Hallo Valerie
klopt. Hebben we deze morgen in de redactieraad ook afgesproken.
groeten mieke

Van: valeriepirard <notifications@github.com>
Verzonden: dinsdag 7 april 2020 13:24
Aan: provinciesincijfers/PinC-taakopvolging <PinC-taakopvolging@noreply.github.com>
CC: Van Opstal Mieke <mieke.van.opstal@oost-vlaanderen.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] Voorstel: gebruik enkel "percentage" indien teller en noemer directe relatie hebben (#97)


@miekevanopstal<https://github.com/miekevanopstal>
Bij deze indicatoren is de teller geen deelgroep van de noemer, dacht ik. Dus, je deelt de groep kinderen niet op, zoals bij een echt % het geval is.
Ik zou hier geneigd zijn om een ratio te gebruiken: x aantal plaatsen per 100 kinderen

**Comment by miekevanopstal** [comment]
aangepast

Van: valeriepirard <notifications@github.com>
Verzonden: dinsdag 7 april 2020 13:24
Aan: provinciesincijfers/PinC-taakopvolging <PinC-taakopvolging@noreply.github.com>
CC: Van Opstal Mieke <mieke.van.opstal@oost-vlaanderen.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] Voorstel: gebruik enkel "percentage" indien teller en noemer directe relatie hebben (#97)


@miekevanopstal<https://github.com/miekevanopstal>
Bij deze indicatoren is de teller geen deelgroep van de noemer, dacht ik. Dus, je deelt de groep kinderen niet op, zoals bij een echt % het geval is.
Ik zou hier geneigd zijn om een ratio te gebruiken: x aantal plaatsen per 100 kinderen

**Comment by StefanJacques** [comment]
voorstel op de redactiegroep van 07/04/2020 is om alle gevallen waarbij **teller en noemer uit verschillende bron** komen, niet meer als percentage te **definiëren** maar als **ratio**.
