### ISSUE TITLE
voorstel dashboard zorgaanbod

### ISSUE THREAD

**Issue by karolienbloemen** [provinciesincijfers/PinC-taakopvolging#99]
Vorige redactiegroep werd afgesproken het thema ouderenzorg te vervangen door 1 thema zorgaanbod (ouderenzorg + kinderopvang). Hierbij voorstel voor dit aangepaste thema, obv bestaande thema ouderenzorg:

-	voor kinderopvang volgende 4 tegels toevoegen:  https://provincies.incijfers.be//jive?workspace_guid=760c7ebb-1a0b-48f2-87e4-ad9814aa87f0   
-	de 4 tegels demografie verwijderen
-	tegels zorgaanbod behouden
-	tegels zorgbudget: 2 tegels van de 80-plussers verwijderen

Graag feedback van de redactiegroep alvorens het dashboard wordt aangepast.

**Comment by StefanJacques** [comment]
Afgesproken op _redactiegroep 30/03/2020_

Dashboard hernoemen naar "ZORGAANBOD" (ander icoontje)
1. ondertitel - Kinderen en jongeren
2. ondertitel - Ouderen

**Comment by KoenSnyers** [comment]
Dashboard zorgaanbod is aangepast.
